### ISSUE TITLE
Quest #5064 - Grimtotem Spying

### ISSUE THREAD

**Issue by wow-classic** [Questie/Questie#1048]
## Description
"Grimtotem Spying" show only marker for "Secret Note #3" on the map (in the Russian version. Сan’t see the non-Russian version).

## Wowhead link
https://classic.wowhead.com/quest=5064/grimtotem-spying

## Questie version
4.1.1 BETA

**Comment by BreakBB** [comment]
This is liked to #1071

**Comment by BreakBB** [comment]
Fixed with #2438
