### ISSUE TITLE
Malyfous's Catalogue and Catalogue of the Wayward repeatable quests.

### ISSUE THREAD

**Issue by Orome123** [Questie/Questie#1335]
5 related quests are marked as "available" and not as "repeatable", when they are repeatable. I finished Breastplate of Bloodthirst and it still shows as "available". The quests are:

From Malyfous's Catalogue:
Breastplate of Bloodthirst: https://classic.wowhead.com/quest=5068/breastplate-of-bloodthirst
Cap of the Scarlet Savant: https://classic.wowhead.com/quest=5063/cap-of-the-scarlet-savant
Leggings of Arcana: https://classic.wowhead.com/quest=5067/leggings-of-arcana

From Catalogue of the Wayward:
Breastplate of the Chromatic Flight: https://classic.wowhead.com/quest=5166/breastplate-of-the-chromatic-flight
Legplates of the Chromatic Defier: https://classic.wowhead.com/quest=5167/legplates-of-the-chromatic-defier

![WoWScrnShot_101519_183148](https://user-images.githubusercontent.com/56611266/66871549-425dc180-ef7a-11e9-9665-7b1273b57808.jpg)
![WoWScrnShot_101519_183157](https://user-images.githubusercontent.com/56611266/66871560-4558b200-ef7a-11e9-87d3-5bf1c10942b5.jpg)

All these quests should be flaged as "repeatable".

Questie version  4.2.1

**Comment by Muehe** [comment]
Users Pan#0003 and Dom6#6515 both reported on Discord that quest 5166 and 5167 are **not** repeatable.

I'm not sure if or when this changed, but I'll change it to what Wowhead shows right now, which is that 5067 and 5068 are repeatable and 5063, 5166, and 5167 are not repeatable, for both expansions.

**Comment by Muehe** [comment]
Some new info from Dom6 via [Discord message](https://discord.com/channels/242423099184775169/616613385492103168/923210622508884008) from [All the Things](https://www.curseforge.com/wow/addons/all-the-things):

![pic_related](https://cdn.discordapp.com/attachments/579966856085897216/981063203964452934/unknown.png)

Screenshot says 5063 is repeatable, contrary to what Wowhead says, and 5166 and 5177 are not repeatable, same as what Wowhead says.
