### ISSUE TITLE
Rogue Quest "To Hulfdan!" Remains Visible

### ISSUE THREAD

**Issue by MerlijnVH** [Questie/Questie#1817]
## Description
The quest "To Hulfdan!" (Quest ID 2299) shows up on my map, but when I go there, I can't see or accept the quest from the NPC. Rogue's can either do the class questline "Redridge Rendezvous" (Quest ID 2281) or "To Hulfdan!" (Quest ID 2299), doing one of them makes the other one unavailable, but they still show up in Questie. According to "IsQuestFlaggedCompleted" I've completed ID 2281, so that seems to check out.

## Wowhead link
https://classic.wowhead.com/quest=2299/to-hulfdan

## Screenshots
![Screenshot 2020-03-11 21 15 44](https://user-images.githubusercontent.com/745922/76460053-a37caa80-63dd-11ea-8e53-b58ccfe102bd.png)

## Questie version
5.8.0 (currently, but I've had this issue for the last few months)

**Comment by BreakBB** [comment]
@MerlijnVH Thanks for the report of this. No other user reported this so we weren't able to fix it. This is an easy fix and will be included in the next version!

**Comment by Muehe** [comment]
We need to re-check this fix, it doesn't seem to work that way, as 2299 is still available when 2281 is already picked up. The solution also disregards Nightelf quests. [This quest](https://classic.wowhead.com/quest=2241/the-apple-falls) is a good entry point to see the three different chains.

**Comment by TorpedoCXC** [comment]
I will re-check this issue. @MerlijnVH @Muehe which WoW version were you on when this happened (Classic, BC, WotLK)? I need this information to know to which files a possible fix has to be applied.

@Muehe Please note that just picking up another quest does not affect Questie currently. So this may be a thing that we are not able to fix for now. The quest 2299 should of course disappear as soon as you complete 2281.

**Comment by BreakBB** [comment]
@TorpedoCXC I am quite sure this is a Classic issue and then most likely reflected in all versions where this quest exists.

> Please note that just picking up another quest does not affect Questie currently.
Not sure what exactly you mean by that 🤔 Because `exclusiveTo` also checks for quests in the quest log.

**Comment by TorpedoCXC** [comment]
> Not sure what exactly you mean by that 🤔 Because `exclusiveTo` also checks for quests in the quest log.

Oh, it does? That's good news in general. I misinterpeted your comment `Since you can complete both quests, while you can only accept one of them at the same time, this is a case Questie currently can not reflect 🤔` (https://github.com/Questie/Questie/issues/6439#issuecomment-2396014573) then.

**Comment by BreakBB** [comment]
I thought as much, hence my comment 😁 

I am quite sure the issue here is "classic", meaning there is a somewhat complex `preQuestSingle`, `preQuestGroup` and/or `exclusiveTo` connection between some quests.

**Comment by Cabro** [comment]
https://github.com/Questie/Questie/commit/6b8fa5eb1edfb86ae62953c1a32bf784de189ff6
Quest 2281 has some weird behavior for some quests.
