### ISSUE TITLE
Quest issue around [54] Corrupted Sabers 

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#1941]
## Description

The quest calls for you to release a cat at the Corrupted Moon Well, then escort it back to the quest giver. However, the icon only shows the magnifying glass at the quest giver, it needs to show a gear at the Corrupted Moon Well indicating where to use the item in the bag to release the cat to start the escort. Tested on 53 Orc Warrior.

Corrupted Moon Well is at 37,68 in Felwood.

## Wowhead link

* Corrupted Sabers - Quest - World of Warcraft || https://classic.wowhead.com/quest=4506/corrupted-sabers

## Screenshots

![WoWScrnShot_051220_221046](https://user-images.githubusercontent.com/55365231/81838463-c3c70380-950b-11ea-8f32-561fb87eca28.jpg)

## Questie version

5.10.2

**Comment by Gogo1951** [comment]
This needs a magnifying glass or gear at the moonwell, and another at the quest giver.

Get the quest > use the item at the moonwell to spawn the cat > take the cat back to the quest giver and talk to the cat to complete quest.

We're only showing the "talk to the cat" icon location still.

**Comment by Gogo1951** [comment]
Antique issue, nice work!

**Comment by Muehe** [comment]
It ain't much but it's honest work. ;)

Btw. forgot to say yesterday, I chose to mark the actual moonwell object at 32:66 instead of the entrance to the valley, since it was already done like that for the previous quest that also sends you to the same moonwell.
