### ISSUE TITLE
Missed translation strings in config.lua for localization

### ISSUE THREAD

**Issue by Iowerth** [Questie/Questie#2245]
Hi! I've noticed that some of words and phrases can not be translated from EN because there are no matching strings in \Questie\Locale\enUS\config.lua. For example:
• \Questie\Modules\Options\DBMTab\QuestieOptionsDBM.lua ("true" and "false" for DBM_HUD_FILTER_KILL_DESC or DBM_HUD_FILTER_QUEST_DESC, etc)
• \Questie\Modules\Journey\QuestieSearchResults.lua (like "Hidden by user", etc)
• maybe somewhere more

Please add missed translation strings in config.lua.

**Comment by anon1231823** [comment]
I found "Completed on:" is also not in there
