### ISSUE TITLE
Discovering new areas on the world map enables Questie settings that are marked as disabled

### ISSUE THREAD

**Issue by KCman13** [Questie/Questie#2255]
## Bug description

When a new area is discovered, disabled icons appear on the map/minimap that should not be. You have to Hide and then Show Questie on the map to fix it every time. Example screenshots shown below. I have all icons disabled for map, yet they now appear on the map. I also only have available quests enabled, but the objective marker comes up. Icons should not be on the map at all, but if I were close enough, it would be on my mini map as well. I only have low level quests enabled to be shown on my mini map, that should be it.

## Screenshots

![Before Discovering new area](https://user-images.githubusercontent.com/30799571/89963171-efde4780-dc14-11ea-9626-fe11549a2579.png)
![After Discovering new area](https://user-images.githubusercontent.com/30799571/89963224-071d3500-dc15-11ea-9bf5-b9c4bf1ef235.png)

## Questie version

Questie v6.0.4

**Comment by BreakBB** [comment]
@KCman13 This is most likely related to another issue which is currently in the code, about the Icon settings. We will look into it.

**Comment by Gogo1951** [comment]
Hey @KCman13 ,

This feature to show and hide based on what you've discovered is really buggy. Suggest just getting Leatrix Maps so you can see the whole map all the time. We're doing away with this feature in 7.0.

https://www.curseforge.com/wow/addons/leatrix-maps-classic
