### ISSUE TITLE
Blackrock Mountain not in the database

### ISSUE THREAD

**Issue by Cerby3BR** [Questie/Questie#2264]
I realized that Disharmony of Flame wasn't in the Journey despite being in the database. It would appear that Blackrock Mountain isn't included in the zone database despite its ID of 25 being assigned to a few quests in the quest database (specifically, both Overmaster Pyron kill quests and all quests associated with Bodley in the T0.5 questline).

Version 6.0.4

**Comment by Gogo1951** [comment]
@BreakBB or @AeroScripts is this issue fixed with the TBC data?

**Comment by BreakBB** [comment]
@Gogo1951 You can check when looking at the Journey. Quests by Zone should have an entry for Blackrock Mountain.

Haven't really looking into it, but it might be the quest belongs to another zone and Blackrock Mountain itself does not have quests.

**Comment by Muehe** [comment]
Issue is fixed in 7.4.10, quest shows in Quests by Zone for Horde characters.
