### ISSUE TITLE
Profession Objectives for Missing Recipes

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#2283]
## Description

* As a user who is a bit of a completionist, as I suspect all Questie users tend to be, I would love to see where I can get recipes when I'm out in the world. Often filling out my professions is a "quest" in and of itself.

* We've got a nice map interface, it seems like it'd be a good fit to add some other things to it.

* As the game matures, looking for ways to keep people engaged with Questie once they hit 60.

I reached out to the guy who created Recipe Radar Classic but I didn't get a response. He hasn't signed on since March and hasn't made any updates to his addon since 2019.

Anyway, I'd love the ability to toggle professions tracking on the Map and Minimap, so I could see where vendors were located who sold things I needed, or what mobs I should be farming to get rare drops.

I think patterns should essentially show up as objectives on the map, like instead of a little loot icon, a little pattern icon if I had the "track blacksmithing" feature enabled.

And for Name Plates, instead of a Loot Bag, or a Sword, a Recipe. I've noticed that when you have to both loot and kill, it just shows the Sword -- I think that sort of priority is fine... Kill would always show a sword >Loot would show a bag > Has a pattern you don't know yet shows a Pattern.

Here's the code:

* Recipe Radar Classic - Addons - World of Warcraft - CurseForge || https://www.curseforge.com/wow/addons/recipe-radar-classic

* yunohu / reciperadarclassic — Bitbucket | https://bitbucket.org/yunohu/reciperadarclassic/src/master/

## Possible UX Ideas

If we go ahead with Townsfolk Tracker (or not), we could add some profession icons to the bottom of the map. Clicking on them would open a menu that lets a user select what they want to track. (Townsfolk Tracker makes you open your profession every time you learn something new to register the change, we could have a note in the menu like that too.) At most 3 Buttons I think... Cooking, and then the two other profs. First Aid has a few items... Fishing, I can't think of anything that drops. Even if it were 5 Buttons, that's probably fine.

By default, only show "Patterns I can use Now."

Then just show the patterns like we would any other objective on the map. When you mouse over it, the tooltip would tell you what the pattern was and what mobs it was dropped by / obtained from.

![image](https://user-images.githubusercontent.com/55365231/90715717-b9d24080-e270-11ea-8606-78a7eed4a6c4.png)

**Comment by BreakBB** [comment]
From my perspective this has nothing to do with quests at all and therefore it nothing which should be added to Questie. Even though we have a complete database with all the required information, profession progression is a different field.
