### ISSUE TITLE
The completion marker for "Saving Yenniku" is missing

### ISSUE THREAD

**Issue by PowershellNinja** [Questie/Questie#2318]
## Description
The quest completion marker for the "Saving Yenniku" quest is missing. You have to turn in the quest with Nimboya, but he is not marked with a question mark.

## Wowhead link
https://classic.wowhead.com/quest=592/saving-yenniku

## Screenshots
![image](https://user-images.githubusercontent.com/12686296/91327380-b8030280-e7c5-11ea-9ca5-5048815d2afc.png)
![image](https://user-images.githubusercontent.com/12686296/91327546-f4366300-e7c5-11ea-8ab3-7d24fa1244f4.png)

## Questie version
v6.0.5

**Comment by Gogo1951** [comment]
Hey @drejjmit ,

I had a similar issue, where it just wasn't showing as completed. You get the item you need by trading with a "stunned" mob, and it never triggers "complete" -- so therefor it's not showing as completed on the map. I thought it had to do with the "auto-turn-in" issue we had with other quests (like the ones for hunting in Ashenvale / cloth turn ins). 

Apparently fixing that didn't fix this.

**Comment by drejjmit** [comment]
Not a quest issue. I would guess that when something is spawned inside your bag (not looted) some of the events are not triggering. Someone would need to do an ``/etrace`` on this. I don't play horde so can't help with this.

**Comment by BreakBB** [comment]
As @drejjmit already wrote this is not really an issue of Questie. Blizzard has some quests which don't trigger an USER_QUEST_LOG_CHANGED event, so we simply can not recognize something changed. This is most likely another case of this. Another example are the scouting reports in Ashenvale.

**Comment by BreakBB** [comment]
Closing this as there is currently no way for us to fix this, since the issue bases on an inconsistency on Blizzards side.
