### ISSUE TITLE
Grouping in Tooltips

### ISSUE THREAD

**Issue by drejjmit** [Questie/Questie#2336]
## Bug description
Show all players after ``Lord Lakmaeran (62+)`` instead of adding another line of ``Lord Lakmaeran (62+)``

## Screenshots
![image](https://user-images.githubusercontent.com/15526476/92041389-6be13080-ed78-11ea-874f-2f9ffe1e4c50.png)

## Questie version
v6.0.5

**Comment by Gogo1951** [comment]
Hey we'll be re-working this a bit. May try and group... only thing is that it only saves space if they are all 0/1 type quests. Once you start getting into the 13/20 type quests, grouping doesn't really work. Playing around a bit with how to do this along with the #1759 - closing this issue as a stand alone.

**Comment by Gogo1951** [comment]
https://github.com/Questie/Questie/issues/2514 rather.
