### ISSUE TITLE
Investigate the Blue Recluse

### ISSUE THREAD

**Issue by BreakBB** [Questie/Questie#2340]
## Description

A friend of mine notified me that this quest is not shown correctly. The objectives are not showing up and no hint is given where to complete this quest.

## Wowhead link

https://classic.wowhead.com/quest=1920/investigate-the-blue-recluse

## Questie version

v6.0.6

**Comment by drejjmit** [comment]
8624eaf72e8976e5397115718366a45f998ea3d5
