### ISSUE TITLE
Waypoint lines and cluster amount

### ISSUE THREAD

**Issue by drejjmit** [Questie/Questie#2346]
## Bug description
Not all waypoint lines are redrawn if you change "Objective icon cluster amount".
Reload is needed to get waypoints back.

## Screenshots
Before --> After
![image](https://user-images.githubusercontent.com/15526476/92339633-77ee2a80-f0b7-11ea-9f2e-a4d7b5b3871d.png)

## Questie version
v6.0.5

**Comment by BreakBB** [comment]
I honestly think waypoints should not be affected by the clustering at all

**Comment by drejjmit** [comment]
I'm not sure tey are. But the slider somehow doesn't redraw them correctly

**Comment by AeroScripts** [comment]
this happens because waypoints are tied to an icon for their tooltips, so if that icon is removed the line is also removed. We probably need to change that logic

**Comment by Muehe** [comment]
Seems to have been fixed in the meantime, waypoints are properly redrawn (and way before the actual icon actually).
