### ISSUE TITLE
Map doesn't close when pressing the escape key

### ISSUE THREAD

**Issue by KevinYang21** [Questie/Questie#2367]
## Bug description
Similar to [this issue](https://github.com/AeroScripts/QuestieDev/issues/1033), 6.0.5 after right click the quest to show the quest on the map, pressing escape won't close the map.

## Screenshots
pretty straight forward but can add if reqeusted.

## Questie version

6.0.5

**Comment by Gogo1951** [comment]
Hey @KevinYang21 ,

Different map addons handle this differently, but Questie doesn't change behavior of whatever addon you have.

Try Leatrix Maps. Esc works fine to close the map there. Or just default Questie with no map addon.

https://www.curseforge.com/wow/addons/leatrix-maps-classic

Cheers!
