### ISSUE TITLE
Repeatable quests are not tracked properly

### ISSUE THREAD

**Issue by boktai1000** [Questie/Questie#2405]
## Bug description
When a Repeatable quest is turned in, and then picked up in the same play session without a reload, the quest is not tracked by Questie.

And example of this can be done with the Winterspring Frostsaber quest (the first one Frostsaber Provisions), and I believe I noticed the same issue when doing the Field Duty/Silithus Quests.

## Questie version
v.6.1.0 (Although this problem has been occurring for a bit now)

**Comment by Gogo1951** [comment]
Hey @boktai1000 ,

What's not tracked correctly? What are you expecting for the fix?

**Comment by BreakBB** [comment]
This was fixed with #3111

**Comment by Laumesis** [comment]
I am not sure if this is fixed for sure. But most likely.
