### ISSUE TITLE
Lost coordinates on big map?

### ISSUE THREAD

**Issue by helelena** [Questie/Questie#2409]
I can't activate the coordinates, for player and cursor, on the world map - on the minimap if works fine

**Comment by helelena** [comment]
Sorry  - after a bit of reloading and relogging in it appeard again.

**Comment by BreakBB** [comment]
@helelena Glad you found a solution. Not sure if there is a problem in Questie though. Feel free to open another ticket when you encounter something :+1:

**Comment by drejjmit** [comment]
There definitely is something fishy with the cursor coordinates at least. 

Left = Questie (Doesn't change when i move the cursor) and right is TomTom.
Also: Checking and Unchecking "Player and Cursor Coorinates" in Map tab won't enable it again unless i reload.

![image](https://user-images.githubusercontent.com/15526476/96572790-91e17680-12cd-11eb-997b-41add549e598.png)

**Comment by Djfe** [comment]
Cursor position in the latest version 6.1.0 only updates while moving (reopening the map doesn't update the coordinates either).
So if you have autowalk on (Numkey by default), then the cursor position will update

**Comment by cubinsky** [comment]
> Cursor position in the latest version 6.1.0 only updates while moving (reopening the map doesn't update the coordinates either).
> So if you have autowalk on (Numkey by default), then the cursor position will update

Can confirm, still happening in my Questie for Classic, 6.2.1. Thanks.

**Comment by Djfe** [comment]
Did you disable the coordinates on the world map altogether (for now)?
Were you able to find the root of this issue?

**Comment by BreakBB** [comment]
This will be fixed once the TBC changes are merged to master. The commit fixing this is 656710c73c886f46438bdc41625d2891e362fd84
