### ISSUE TITLE
Accepting the level 60 version of "Claiming Arathi Basin" doesn't hide the lower level ones from map/minimap.

### ISSUE THREAD

**Issue by CaraleTheGnome** [Questie/Questie#2429]
## Description
If you accept the level 60 version of "Claiming Arathi Basin" from an Alliance Brigadier General then the lower level ones are still listed as being available, from the same npc, even though they are not. The same problem is not experienced when accepting the level 60 version of "Fight for Warsong Gulch".

## Wowhead link
I don't know which of these two are actually used in the game:
[Wowhead link 1 to level 60 quest](https://classic.wowhead.com/quest=8398/claiming-arathi-basin)
[Wowhead link 2 to level 60 quest](https://classic.wowhead.com/quest=8396/claiming-arathi-basin)

## Screenshots
![battle](https://user-images.githubusercontent.com/24671315/97306063-362f6400-185e-11eb-964a-c9bf1cd1837e.jpg)

## Questie version
6.1.0

**Comment by Cabro** [comment]
Should be fixed
