### ISSUE TITLE
Waypoints not drawn for different zone on pickup

### ISSUE THREAD

**Issue by drejjmit** [Questie/Questie#2440]
## Bug description
Only draws waypoints if quest giver and objective is in the same zone.
Will only show spawn icon in a different zone.

Example: [[[28] The Missing Diplomat (1243)]](https://classic.wowhead.com/quest=1243/the-missing-diplomat) is picked up in ``Stormwind`` but the objective/complete is in ``Duskwood``. Waypoint isn't drawn unless i ``/reload``

Same problem shown here: #2439

## Screenshots
Before and after ``/reload``

![image](https://user-images.githubusercontent.com/15526476/97792007-f9a29600-1bd8-11eb-9559-b0d95da209ff.png)

## Questie version
v6.2.0

**Comment by BreakBB** [comment]
Is this still an issue @drejjmit @MyTechnoHunter @Cabro ?

**Comment by Cabro** [comment]
I tested this exact quest a few days ago, I didn't notice that to be the case

**Comment by BreakBB** [comment]
Closing it then, thanks for the fast response <3
