### ISSUE TITLE
Galak messenger route

### ISSUE THREAD

**Issue by Ghoztkillah** [Questie/Questie#2455]
## Description
 When questing in Thousand Needles area a "route" of the Galak messenger was constantly displayed on my screen. Map or no map. Almost as if it had frozen on the screen along the path he runs. 

## Wowhead link

https://classic.wowhead.com/npc=10617/galak-messenger

## Questie version
--> I am currently running questie version 6.2.1

**Comment by Gogo1951** [comment]
Hey @Ghoztkillah ,

This isn't just a bug with this quest, sometimes objectives and routes get stuck on the screen. It's a bug with one of the other libraries we use.

We're working on a fix for 7.0. Cheers!
