### ISSUE TITLE
Bug in Quest 

### ISSUE THREAD

**Issue by Goldmoon29** [Questie/Questie#2456]
Hello wrong location for a cage to open. 
1st and 2nd it's ok but the third cage is on coordonate 32.0 X , 57.4 Y
thanks for your addon and your work
![2020-11-26_13h00_10](https://user-images.githubusercontent.com/68126821/100348842-cd1b4780-2fe7-11eb-95df-b0d3ebddc11f.png)

**Comment by drejjmit** [comment]
What client language are you using?

**Comment by Goldmoon29** [comment]
Hello i using french language.
Gwendal Le coz

**Comment by Goldmoon29** [comment]
I play on wow classic version 1.13.5 (36325)
Gwendal Le coz

**Comment by BreakBB** [comment]
Related to #2411

**Comment by BreakBB** [comment]
Should be fixed with #2438
