### ISSUE TITLE
Mouseover tooltip quest tracking ends prematurely

### ISSUE THREAD

**Issue by Paah** [Questie/Questie#2458]
## Bug description
You have 2 separate quests, one to kill mobs and another to loot items from said mobs. Tooltip is initially working as expected. Let's say we have situation like this:

Squirrel
Level 18 Beast
[20] Kill Squirrels!
Squirrel 12/20
[20] Loot Nuts!
Squirrel Nut 9/10

Let's say you now kill a squirrel and it drops a nut which you loot. The tooltip tracking completely ends for Squirrels and Questie acts like you don't need to kill any more Squirrels for any quest:

Squirrel
Level 18 Beast

 Of course the expected behaviour would be:

Squirrel
Level 18 Beast
[20] Kill Squirrels!
Squirrel 13/20

Thankfully /reloading UI seems to fix the issue so it is not super critical.

## Example quest pairs
I have encountered this issue with at least the following quest pairings so far:
The Bloodsail Buccaneers [604] + Up to Snuff [587]
Wastewander Justice [1690] + Water Pouch Bounty [1707]
Southsea Shakedown [8366] + Pirate Hats Ahoy! [8365]
Curse These Fat Fingers [7732] + The Flawless Flame [3442]

So it seems it is a generic issue and not related to any particular quest.

## Questie version
Currently using latest version 6.2.3 and experienced the bug again, but I can tell you this issue was already introduced in 6.2.0

**Comment by Paah** [comment]
Note: The bug happens exactly when all the objectives for the looting quest are completed. For example with the last pair of quests I mentioned the golems still show correctly with 17/20 golems and 4/4 golem oils, if you don't have 4 hearts of flame yet. However upon looting the 4th heart of flame from a fire elemental, the tooltip for golems disappears again even though the kill quest is still in progress.

**Comment by BreakBB** [comment]
This has been fixed with #2600
