### ISSUE TITLE
A Yeti of Your Own (8798)

### ISSUE THREAD

**Issue by Arccai** [Questie/Questie#2462]
**Misplaced in the Journey feature.**

**A Yeti of Your Own** (8798)
This is an "Engineer" quest,
but appears for everyone.

Placed in Winterspring section.
Should be placed in Profession section.

[Wowhead Link](https://classic.wowhead.com/quest=8798/a-yeti-of-your-own)

**Comment by Faeryqueenaeval** [comment]
Issue has already been corrected.
```
  [8798] = {
            [questKeys.requiredSkill] = {202,250},
        },
```
