### ISSUE TITLE
Fiery Plate Gauntlets (5124)

### ISSUE THREAD

**Issue by Arccai** [Questie/Questie#2464]
**Misplaced in the Journey feature.**

**Fiery Plate Gauntlets** (5124)
This is an "Blacksmith" quest,
but appears for everyone.

Placed in Winterspring section.
Should be placed in Profession section.

[Wowhead Link](https://classic.wowhead.com/quest=5124/fiery-plate-gauntlets#comments)

**Comment by Faeryqueenaeval** [comment]
Issue has been resolved:
```
  [5124] = {
            [questKeys.requiredSkill] = {164,275},
        },
```
