### ISSUE TITLE
The Family and the Fishing Pole (1141)

### ISSUE THREAD

**Issue by Arccai** [Questie/Questie#2468]
**Misplaced in the Journey feature.**

**The Family and the Fishing Pole** (1141)
This is an "Fishing" quest,
but appears in Darkshore.

Placed in Darkshore section.
Should be placed in Profession section.

[Wowhead Link](https://classic.wowhead.com/quest=1141/the-family-and-the-fishing-pole)

**Comment by drejjmit** [comment]
This can be picked up without learning Fishing first.
