### ISSUE TITLE
Sacred Cloth (6032)

### ISSUE THREAD

**Issue by Arccai** [Questie/Questie#2474]
**Misplaced in the Journey feature.**

**Sacred Cloth** (6032)
This is an "Tailor" quest,
but appears for everyone.

Placed in Felwood section.
Should be placed in Profession section.

[Wowhead Link](https://classic.wowhead.com/quest=6032/sacred-cloth)

**Comment by Gogo1951** [comment]
Hey @Arccai ,

I consolidated your report into one issue.

https://github.com/Questie/Questie/issues/2565
