### ISSUE TITLE
Erion Shadewhisper quest still show avaible and all lockpick quest are done and completed

### ISSUE THREAD

**Issue by pelgrino** [Questie/Questie#2476]
I have the issue with the quest ID 2259 Erion Shadewhisper . I have the Erion's Behest quest ( ID 2260 ) is in the complete list and the lockpick quests are completed too. The Quest ID 2259 consist to go contact Erion Shadewhisper in darnassus. After Erion give us the Erion's Behest (ID 2260) to go do talk to Renzik " The Shiv " in Stormwind. I want the quest ID 2259 to be put in the complet list, since all the other Lockpick quest have been put in the complet list. When I do the command to check if quest 2281 is competed, I got the answer of [true]. I just don't like to see this lvl 16 gray quest still in the avaible list when I can't accept it anymore and have done the quest after that one. Please fix the quest Erion Shadewhisper ( ID 2259 ) 

Thanks

**Comment by Nerillida** [comment]
2559 is a breadcrumb for 2560

**Comment by Ohseadee** [comment]
I would also like to see this resolved. The Ironforge breadcrumb and follow-up seem to have auto-completed as per Questie's database (despite the /dump check = false), but ID 2259 remains incomplete and "available" both in the "Quests by Zone" log and tracker. ID 2260 (the follow-up) is completed (also despite the /dump check = false), so clearly an isolated issue.

**Comment by Nerillida** [comment]
2281 has 3 breadcrumbs 2260, 2298, 2300

2260 has 1 breadcrumb 2259
2298 has 1 breadcrumb 2299
2300 has no breadcrumb

Wowhead's prerequisites are wrong.
It's possible to do all 5 of 2260, 2298, 2300,2259,2299

There are NO level 10 prerequisites for any of the level 16 quests.

**Comment by Jojachin** [comment]
I completed the Stormwindpart of theese Quests 2205 2281
I ventured to Teldrassil and completed 2241 and now I cant accept 2259

**Comment by Nerillida** [comment]
Once you have completed  2281, it locks out 
2260, 2298, 2300,2259,2299 unless you have done them prior to 2281

When I ran a character through, the level 10 quests were irrelevant to the level 16 quests.

I am 99% sure the Quest has the wrong values for prerequisites copied from Wowhead.
