### ISSUE TITLE
Bad information on quest.

### ISSUE THREAD

**Issue by Raithaam** [Questie/Questie#2488]
Questie v6.2.4, WoW classic

For the quest "Bailor's Ore Shipment," Questie marks "Jordan's Ore Shipment" as being a drop off certain Ogres, on the tooltip as well as having the item drop map icon.

However, this item is actually a box that spawns in various areas of the camp, and needs to be picked up.

**Comment by Gogo1951** [comment]
Closing this as a dupe, the new issues has more details.
