### ISSUE TITLE
"Ironband's excavation" given by Jern Hornhelm in loch Modan/Thelsamar

### ISSUE THREAD

**Issue by drejjmit** [Questie/Questie#2492]
## Description
From: https://www.curseforge.com/wow/addons/questie?comment=1390
I've encountered a bug, a quest that I've completed is shown as available in my journal, the quest is called "Ironband's excavation" given by Jern Hornhelm in loch Modan/Thelsamar

## Wowhead link
https://classic.wowhead.com/quest=436/ironbands-excavation

## Questie version
Unknown

**Comment by Nerillida** [comment]
Quest 436 is a breadcrumb for 297.
