### ISSUE TITLE
Tier 3 turn-in quests should be marked as repeatable

### ISSUE THREAD

**Issue by Cerby3BR** [Questie/Questie#2493]
They still show up on the minimap even though I've disabled Repeatable Quest Icons.

Warrior:
https://classic.wowhead.com/quest=9034/dreadnaught-breastplate
https://classic.wowhead.com/quest=9036/dreadnaught-legplates
https://classic.wowhead.com/quest=9037/dreadnaught-helmet
https://classic.wowhead.com/quest=9038/dreadnaught-pauldrons
https://classic.wowhead.com/quest=9039/dreadnaught-sabatons
https://classic.wowhead.com/quest=9040/dreadnaught-gauntlets
https://classic.wowhead.com/quest=9041/dreadnaught-waistguard
https://classic.wowhead.com/quest=9042/dreadnaught-bracers

Paladin:
https://classic.wowhead.com/quest=9043/redemption-tunic
https://classic.wowhead.com/quest=9044/redemption-legguards
https://classic.wowhead.com/quest=9045/redemption-headpiece
https://classic.wowhead.com/quest=9046/redemption-spaulders
https://classic.wowhead.com/quest=9047/redemption-boots
https://classic.wowhead.com/quest=9048/redemption-handguards
https://classic.wowhead.com/quest=9049/redemption-girdle
https://classic.wowhead.com/quest=9050/redemption-wristguards

Hunter:
https://classic.wowhead.com/quest=9054/cryptstalker-tunic
https://classic.wowhead.com/quest=9055/cryptstalker-legguards
https://classic.wowhead.com/quest=9056/cryptstalker-headpiece
https://classic.wowhead.com/quest=9057/cryptstalker-spaulders
https://classic.wowhead.com/quest=9058/cryptstalker-boots
https://classic.wowhead.com/quest=9059/cryptstalker-handguards
https://classic.wowhead.com/quest=9060/cryptstalker-girdle
https://classic.wowhead.com/quest=9061/cryptstalker-wristguards

Shaman:
https://classic.wowhead.com/quest=9068/earthshatter-tunic
https://classic.wowhead.com/quest=9069/earthshatter-legguards
https://classic.wowhead.com/quest=9070/earthshatter-headpiece
https://classic.wowhead.com/quest=9071/earthshatter-spaulders
https://classic.wowhead.com/quest=9072/earthshatter-boots
https://classic.wowhead.com/quest=9073/earthshatter-handguards
https://classic.wowhead.com/quest=9074/earthshatter-girdle
https://classic.wowhead.com/quest=9075/earthshatter-wristguards

Rogue:
https://classic.wowhead.com/quest=9077/bonescythe-breastplate
https://classic.wowhead.com/quest=9078/bonescythe-legplates
https://classic.wowhead.com/quest=9079/bonescythe-helmet
https://classic.wowhead.com/quest=9080/bonescythe-pauldrons
https://classic.wowhead.com/quest=9081/bonescythe-sabatons
https://classic.wowhead.com/quest=9082/bonescythe-gauntlets
https://classic.wowhead.com/quest=9083/bonescythe-waistguard
https://classic.wowhead.com/quest=9084/bonescythe-bracers

Druid:
https://classic.wowhead.com/quest=9086/dreamwalker-tunic
https://classic.wowhead.com/quest=9087/dreamwalker-legguards
https://classic.wowhead.com/quest=9088/dreamwalker-headpiece
https://classic.wowhead.com/quest=9089/dreamwalker-spaulders
https://classic.wowhead.com/quest=9090/dreamwalker-boots
https://classic.wowhead.com/quest=9091/dreamwalker-handguards
https://classic.wowhead.com/quest=9092/dreamwalker-girdle
https://classic.wowhead.com/quest=9093/dreamwalker-wristguards

Mage:
https://classic.wowhead.com/quest=9095/frostfire-robe
https://classic.wowhead.com/quest=9096/frostfire-leggings
https://classic.wowhead.com/quest=9097/frostfire-circlet
https://classic.wowhead.com/quest=9098/frostfire-shoulderpads
https://classic.wowhead.com/quest=9099/frostfire-sandals
https://classic.wowhead.com/quest=9100/frostfire-gloves
https://classic.wowhead.com/quest=9101/frostfire-belt
https://classic.wowhead.com/quest=9102/frostfire-bindings

Warlock:
https://classic.wowhead.com/quest=9103/plagueheart-robe
https://classic.wowhead.com/quest=9104/plagueheart-leggings
https://classic.wowhead.com/quest=9105/plagueheart-circlet
https://classic.wowhead.com/quest=9106/plagueheart-shoulderpads
https://classic.wowhead.com/quest=9107/plagueheart-sandals
https://classic.wowhead.com/quest=9108/plagueheart-gloves
https://classic.wowhead.com/quest=9109/plagueheart-belt
https://classic.wowhead.com/quest=9110/plagueheart-bindings

Priest:
https://classic.wowhead.com/quest=9111/robe-of-faith
https://classic.wowhead.com/quest=9112/leggings-of-faith
https://classic.wowhead.com/quest=9113/circlet-of-faith
https://classic.wowhead.com/quest=9114/shoulderpads-of-faith
https://classic.wowhead.com/quest=9115/sandals-of-faith
https://classic.wowhead.com/quest=9116/gloves-of-faith
https://classic.wowhead.com/quest=9117/belt-of-faith
https://classic.wowhead.com/quest=9118/bindings-of-faith

![WoWScrnShot_012121_030952](https://user-images.githubusercontent.com/54936174/105270496-2b067e80-5b96-11eb-9856-cab7343b24a6.jpg)

Version 6.2.4

**Comment by Cerby3BR** [comment]
![WoWScrnShot_012121_134914](https://user-images.githubusercontent.com/54936174/105353581-b6f8c480-5bef-11eb-9b4b-12b5c46e1005.jpg)

Another screenshot showing the lack of access and the non-repeatability of the quests.

**Comment by BreakBB** [comment]
Awesome issue description @Cerby3BR Thanks a lot for taking your time to make it this detailed. Helped **a lot**!
