### ISSUE TITLE
Frost Resistance crafting quests are class specific

### ISSUE THREAD

**Issue by Cerby3BR** [Questie/Questie#2494]
As a druid, for instance, Craftsman Wilhelm only offers the cloak quest and leather quests, but Questie thinks I have access to all thirteen quests.

Cloak (available to everyone):
https://classic.wowhead.com/quest=9237/glacial-cloak

Plate:
https://classic.wowhead.com/quest=9234/icebane-gauntlets
https://classic.wowhead.com/quest=9235/icebane-bracers
https://classic.wowhead.com/quest=9236/icebane-breastplate

Cloth:
https://classic.wowhead.com/quest=9238/glacial-wrists
https://classic.wowhead.com/quest=9239/glacial-gloves
https://classic.wowhead.com/quest=9240/glacial-vest

Leather:
https://classic.wowhead.com/quest=9241/polar-bracers
https://classic.wowhead.com/quest=9242/polar-gloves
https://classic.wowhead.com/quest=9243/polar-tunic

Mail:
https://classic.wowhead.com/quest=9244/icy-scale-bracers
https://classic.wowhead.com/quest=9245/icy-scale-gauntlets
https://classic.wowhead.com/quest=9246/icy-scale-breastplate

![WoWScrnShot_012121_031517](https://user-images.githubusercontent.com/54936174/105271833-846fad00-5b98-11eb-831a-36b72c02f37a.jpg)

Version 6.2.4

**Comment by BreakBB** [comment]
Once again, thanks for a detailed and very helpful issue @Cerby3BR 🙏
