### ISSUE TITLE
Senir's Observations

### ISSUE THREAD

**Issue by Djfe** [Questie/Questie#2496]
## Description

Senir's Observations shows up on the map on level 1 or at least on level 2 even though it has prequests that need to be done, before you can pick it up in front of the coldrigde pass.

## Wowhead link

https://classic.wowhead.com/quest=420/senirs-observations

## Questie version

6.2.4

**Comment by Ruathaz** [comment]
https://us.battle.net/support/en/article/247423

**Comment by Ruathaz** [comment]
Quest IDs 282 and 420 are unable to be completed if you did the quest ID 287.

**Comment by Djfe** [comment]
287 is only available at level 7.
What are you trying to say?

I think the quest should be hidden, until you complete the pre quests from the quest chain.

**Comment by Ruathaz** [comment]
What I am saying as someone who also cannot complete 282 and 420 now, Questie only tracks quests. If you have any more complaints please direct them to Blizzard, not me. I did no script the game.

**Comment by Djfe** [comment]
Also?
I was able to complete the quests but only after completing the pre quests ^^ (the char isn't even level 7, yet)
I hadn't started quest 182 when going by this npc.

this issue isn't about locking myself out of quests but them showing up too early on the map (during char leveling)

**Comment by BreakBB** [comment]
Realted to #2366
