### ISSUE TITLE
Replace Legacy HUD with Tom-tom Arrow; like old Quest Helper

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#2502]
## Objective

Replace dated HUD that requires DBM, with a Quest-Helper-like Tom-Tom arrow pointing the Quester to their next objective.

## Notes

- [ ] Show Objective
- [ ] Rotate Arrow Graphic to Point to First Objective in Tracker; and be aware of Social Mode.
- [ ] Show Distance to Objective
- [ ] Show time to Objective, at current speed.
- [ ] Should be moveable when you hold shift and click
- [ ] Visibility should be configurable in Options.
- [ ] Need to remove legacy HUD code.
- [ ] Should have tooltip on mouseover "Hold Shift + Left Click to Move Guide Arrow."
- [ ] Should show yellow (#FFD600) when en route to a turn-in; white (#FFFFFF) when en route to a party-member turn-in, green (#00FF80) when en route to an objective you're on, and blue when en route to an objective a party member is on (#0080FF).

## Wireframe(s)

![image](https://user-images.githubusercontent.com/55365231/105661139-5341f600-5e92-11eb-86f7-f7f24ebe8a88.png)

Sample from https://classic.wowhead.com/quest=606/scaring-shaky

![New Mockup 3](https://user-images.githubusercontent.com/55365231/109677027-de23a980-7b3e-11eb-8ec9-96154402258c.png)

Note: Simplified this vs. some other views. We don't need to duplicate the tracker with quest names and progress. Thought about like "This item drops from these guys..." and listing out all the guys... but nah, too messy. Less is better. On the fence is the objective name should go above or below the arrow... probably below, whatever you think looks best when building it out.

## See Also

https://github.com/Questie/Questie/issues/2511

**Comment by Gogo1951** [comment]
Spoke with jnwhiteh (https://www.curseforge.com/members/jnwhiteh/followers) and he's graciously granted us permission to use any of his code from TomTom we need, provided we provide appropriate credit and change out the graphic for the arrow so that if users have both installed it won't conflict.

https://www.curseforge.com/wow/addons/tomtom/files

**Comment by Fanatiikon** [comment]
It would be awesome if this worked for when marking NPCs through advanced search as well. As the current marker is too small and usually hidden behind any number of icons on the map.

**Comment by Gogo1951** [comment]
We had the code for this working under https://github.com/Questie/Questie/tree/routes

But, it'll never get built. Closing as stale.
