### ISSUE TITLE
Flight Path Objectives for Missing Flight Paths 

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#2503]
## Objective

Show an "Objective Marker" for any flight paths a Quester doesn't yet have in the zone.

## Notes

* Good to show these, we'll need to "finish" a zone at a flight path anyway.

## Wireframe

Graphics pending, for now just use old icon and toss it in a white circle -- same as we do for Completed Quests.

**Comment by BreakBB** [comment]
Not a Questie thing.
