### ISSUE TITLE
Exploration Objectives for Missing Map Areas

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#2504]

**Comment by BreakBB** [comment]
Is the target to show some sort of map marker for areas which haven't been explored by the player yet?

Not sure if this would be a good addition. Seems not really useful, will clutter the map and has only a very, very low benefit on the XP. Might also be out of scope.

**Comment by Gogo1951** [comment]
It's for people prepping for Achievements in Wrath. We can save people a ton of time if we help them get Explorer when they're organically questing, vs having to run through it later once the Achievements are out. Certainly low priority; we had just been brainstorming some other "completionist" features to help keep Questie relevant to users at max level.

**Comment by BreakBB** [comment]
Achievements is out of scope for Questie imo
