### ISSUE TITLE
Tooltip Suggestions for Item Deletion

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#2507]
## Objective

People collect a ton of quest items, and junk. We should help Questers know which items are safe to delete.

## Notes

- [ ] Need to show what quest items are for. 
- [ ] Needs to only show for Quests you could get, so like no Horde quests for Alliance, no Warrior quests for hunters, and no Blacksmithing quests for people who aren't Blacksmiths.
- [ ] Need to show for quest items, boes for a quest, and items that were provided for a quest.
- [ ] If you've completed the relevant quest(s) needs to show a safe to delete message.

Should be on the bottom of the tooltip. A lot of addons, especially Auction Addons, add crap in these tooltips. Best if we can be at the bottom.

(In the wire the level says like {12} but that's because the wire tool sucks. Should use standard brackets for quest names [12]...)

## Wireframe

![New Mockup 2](https://user-images.githubusercontent.com/55365231/115972697-89d0f080-a515-11eb-8238-f1350278183f.png)

**Comment by Gogo1951** [comment]
Hey @QartemisT ,

Tried to simplify this as much as possible.

Basically we'll just list all the quests available for the player, and if they quest(s) are complete we'll show a message that it's not needed for Questin' no more. And if not... leave it blank.

Copy for tooltip. (RT1 is the star icon, we use it a few places to call attention to Questie info.)

> {rt1} Questie : You no longer needs this item for a quest!

**Comment by BreakBB** [comment]
This should also ignore common items which are only implicit quest items.

Moreover `{rt1}` can't be used when printing something as debug message (since we don't want this to be printed as regular chat message/visible to other players).

**Comment by rbpaiett** [comment]
Sometimes a quest item gets left in inventory and the quest was completed long ago. Is it safe to delete? 

Also if we come across an item (an uncommon one or unique to a quest) and we'll say "this item is familiar, what quest does it belong to?"

**Comment by Gogo1951** [comment]
Everyone I spoke with loved this idea, but it'll never get built.

Closing as stale.
