### ISSUE TITLE
Improvements to Auto-Dialog

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#2509]
## Objective

Need to add an option settings to make it so when you talk to an NPC it automatically advanced the dialogue. Very useful for quests like the NPC in Uldaman, or the guy at the tower in Kagrath, or many others, who make you talk to them before they give you a quest.

## Notes

Leatrix Plus has this feature, and we need an option to turn it on by default. Just have it auto-chat with every NPC when yo open the the interact window.

https://www.curseforge.com/wow/addons/leatrix-plus-classic

> Automate gossip - Automatically select a single gossip option by holding down the alt key when opening a gossip window.  Banker, taxi, trainer and vendor gossip windows are automatically skipped with no alt key requirement.

## Testing Feedback

- [ ] Needs to check for available quests in menu before advancing.
- [ ] Shouldn't use Auto Dialog on City Guards.

**Comment by Gogo1951** [comment]
Hey @kristinclemens ,

Can you make this so it doesn't fire on city guards? Came into an issue last night where it was hard for Rawg to get instructions from the guard since it would auto advance. Pretty sure guard was an option, right?

- [ ] Don't auto dialog on City Guards.

**Comment by kristinclemens** [comment]
The way it's coded, it only continues if the only gossip types found are allowed gossip types, i.e. quest or gossip. If any disallowed type is found, it doesn't continue. Here are the [gossip types](https://wowwiki-archive.fandom.com/wiki/API_GetGossipOptions): `banker, battlemaster, binder, gossip, healer, petition, tabard, taxi, trainer, unlearn, or vendor`

**Comment by kristinclemens** [comment]
Although, `quest` isn't even on that list. Weird.

**Comment by BreakBB** [comment]
@kristinclemens You should be able to add the guard NPC IDs to the `_QuestieAuto.disallowedNPC` table. Not really easy to find all of them, but most likely the savest way to prevent auto from triggering on guards

**Comment by BreakBB** [comment]
Since this is already party done in master we should improve this even further. Currently the auto dialog makes it harder to pickup quests, when the NPC also has a dialog option. Same goes for guards are written above.

**Comment by kristinclemens** [comment]
Assuming I’m not working till 8pm again, I should have time to do this tomorrow evening. I’ll be busy from 8-10 but should hopefully have time before that.

**Comment by Gogo1951** [comment]
Moving this back to planning; out of 7.0 tasks. If we get to it great, but need to focus on what we can do for 7.0.

**Comment by Gogo1951** [comment]
Closing as stale.
