### ISSUE TITLE
Quest "Achievements" in Player Tooltips

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#2517]
## Objective

Add Quest "Achievments" to Player Tool Tips. Will help players show off, and give insight as to who they should ask to group with for questing.

## Notes

* Show current zone.
* Show Expansion Totals.
* Would not show current zone if a player was in a city.

## Wireframe

![New Mockup 1](https://user-images.githubusercontent.com/55365231/115966912-58e0c380-a4f5-11eb-8a98-74d99ee58f29.png)

**Comment by BreakBB** [comment]
This is a nice feature, but I don't see it as relevant for the initial Questie 7.0 version for TBC. We should also think about a way to present this new feature to the users. I don't think it is a good idea to show it by default.

**Comment by Gogo1951** [comment]
We'll have an easy way to turn it off, but always good to enable new features by default.

If someone doesn't want to use it, they'll be able to easily toggle it off in the Options. New UX here, if you have time to give feedback. #2511

**Comment by Logonz** [comment]
Sending the data for achivements should be fine as long as it does not hinder other comms messages that are more important.
How can we be sure peoples data is new and correct? We are always trusting the client and the idea of giving random people more access to data in other peoples addons is in my opinon risky and nothing stops anyone from just sending 100% complete messages.
If we have this i don't think it should be on by default

**Comment by Gogo1951** [comment]
Thinking it'd be nice to have some progress indicator for XP too.

### Questie

Current Level : 85%
%Current Zone Name% : 17 / 24 Quests
Classic Era : 123 Quests
Burning Crusade : 234 Quests

**Comment by Gogo1951** [comment]
Closing as stale. Will never get worked on.
