### ISSUE TITLE
Hunter Objectives for Missing Pet Abilities

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#2518]
Hunter's Helper got ported to Classic WoW, but then didn't get maintained. 

http://fizzwidget.com/notes/huntershelper/

https://www.curseforge.com/wow/addons/fizzwidget-hunters-helper-classic

Be cool if we could add that into Questie.

Nice to have, lowest priority.

**Comment by BreakBB** [comment]
This has nothing to do with quests so I think this is totally out of scope.
