### ISSUE TITLE
Show "Questie Team" Message to People who Target Questie Team Members In-game

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#2520]
## Objective

Great if we could get a bit more recognition while playing -- and maybe not get PVP'd so much when testing quests. (=

## Notes

On Earthfury there's a weak aura made by a coalition of guilds that reports if someone is a "friend" or "rat" -- it was very popular during the AQ opening events, likely will be for Naxx as well.

https://wago.io/f5MKYZMyw

* Should be turned off for anyone in your party or raid who targets you.

* We'd probably just have to add all of our alt's names, yeah?

Should Say, in green text:

```
%Name%
<Questie Team>
```

## Wireframe

![image](https://user-images.githubusercontent.com/55365231/105786137-18979680-5f42-11eb-8f63-370b14c66be5.png)

**Comment by BreakBB** [comment]
The team decided not to implement this.
