### ISSUE TITLE
Map icons continue to show for untracked quests

### ISSUE THREAD

**Issue by murphe** [Questie/Questie#2524]
## Bug description
If you untrack a quest, the icons still show on the map.

Being unable to single-click untrack all and just see a single objective icon that you are interested in, gets kindof annoying after a while. The inability to easily highlight a single quest objective that you want to the exclusion of all else, makes it very hard to find single-quest objectives.

If you want to focus on a single objective and not have it lost in amongst all the noise of the other icons, the only way to do that is the rather ugly workaround, to retrack all quests, individually right click on each one in the tracker, and hide each one's icons.

## Screenshots
![WoWScrnShot_020421_220324](https://user-images.githubusercontent.com/196374/106884006-e1d93180-6734-11eb-9332-48928215184b.jpg)
![WoWScrnShot_020421_220341](https://user-images.githubusercontent.com/196374/106884039-e867a900-6734-11eb-8769-e3c75488aae1.jpg)

## Questie version
6.2.4

**Comment by Gogo1951** [comment]
Hey @murphe ,

While what you're saying makes sense, it's not how Questie was built to work. Quesite isn't based on the quests you have tracked in the Trakcer or WoW UI, it will show all the icons for the quests you have.* We're working on some improvements for TBC - you can check them out here #2500 .

Totally understand that zones get really cluttered, working to fix this! 

Cheers!

*Actually it is based on the settings of what you have shown... like PVP quests, or Event Quests... but anything you have in the settings and in your log, will show up on your map.
