### ISSUE TITLE
If you hide all icons for a quest in the tracker, it still shows as an objective if there is another objective in roughly the same area.

### ISSUE THREAD

**Issue by murphe** [Questie/Questie#2525]
## Bug description
Minor bug. If you hide all icons for a quest, and its objective is roughly in the same map area as another objective, it lists as an objective.

## Screenshots
![raptor-thieves](https://user-images.githubusercontent.com/196374/106886796-6b3e3300-6738-11eb-9cb8-70fc05496ace.png)
![WoWScrnShot_020421_222409](https://user-images.githubusercontent.com/196374/106886221-bf94e300-6737-11eb-8bf7-5172cd1e4b7d.jpg)

## Questie version
6.2.4

**Comment by Gogo1951** [comment]
Thanks @Muehe ,

This is getting reworked for 7.0. Closing this but we'll make sure to test this situation in the new version.
