### ISSUE TITLE
Quests with patroling mobs are not hidden from the map

### ISSUE THREAD

**Issue by hethhhhh** [Questie/Questie#2528]
## Bug description
With questie icons hidden and none of the icons to be shown selected there are still visible paths of mobs that I don't even have a quest in my questlog for. Hide Show Questie from the minimap button doesn't work either. Only reloading (Ctrl + Click) works and only for a few seconds.

## Screenshots
![image](https://user-images.githubusercontent.com/6394809/107142361-1f0d1180-6937-11eb-80cb-875656cc3cb7.png)
![image](https://user-images.githubusercontent.com/6394809/107142368-292f1000-6937-11eb-87d5-edd1c144504b.png)
![image](https://user-images.githubusercontent.com/6394809/107142396-4fed4680-6937-11eb-9a0b-9ac069a9a7cf.png)

## Questie version
6.2.5

**Comment by Gogo1951** [comment]
Hey @hethhhhh ,

I think this is related to your other issue #2529 -- can you try turning of "hide unexplored area icons" and see if it's still a problem? Thanks!

**Comment by hethhhhh** [comment]
@Gogo1951  That doesn't change anything already tried

**Comment by Gogo1951** [comment]
@hethhhhh Turn "Objectives" back on via the minimap.
