### ISSUE TITLE
When hide unexplored areas checkmark is selected quests show up everytime a new area is revealed

### ISSUE THREAD

**Issue by hethhhhh** [Questie/Questie#2529]
## Bug description
Hide Questie from map, discover a new zone, see all questie icons again all over the map

## Screenshots
before and after discovering a new zone:
![image](https://user-images.githubusercontent.com/6394809/107147749-62c44300-6958-11eb-8790-f94a7b7007f1.png)
![image](https://user-images.githubusercontent.com/6394809/107147758-6f489b80-6958-11eb-926c-96713e299eb0.png)

## Questie version
6.2.4

**Comment by Gogo1951** [comment]
Hey @hethhhhh ,

The "hide unexplored areas" feature is likely going away in BC. Sorry it's buggy now, it hasn't been widely used or tested. We can revisit this if there's time to include it for BC.

**Comment by hethhhhh** [comment]
it's not only when hide unexplored areas is chosen. all these quests are shown even when questie is set to disabled icons in the options menu, as you can see on the minimap button, it still shows "show questie"
