### ISSUE TITLE
No quests shown when "Enable Event Quest Icons" is enabled but "Enable Available Quest Icons" is disabled

### ISSUE THREAD

**Issue by clintonmead** [Questie/Questie#2535]
## Bug description

If "Enable Event Quest Icons" is enabled but "Enable Available Quest Icons" is disabled, no quests will be shown. I would expect in this case instead for the event quests to be shown, and indeed `_Qframe:ShouldBeHidden` suggests this is the intent. 

This makes it difficult to complete the lunar festival "Coin Of Ancestry quests" because once "Enable Available Quest Icons" is set to true lots of non-event quests show on the map.

## Questie version
v6.2.5

**Comment by Gogo1951** [comment]
Hey @clintonmead ,

Sorry for the hassle. This is getting a re-work in v7. The team is working on that now, and this will get fixed as part of those revisions. Cheers!

#2511
