### ISSUE TITLE
[60] The Ice Guard & [60] The Shadow Guard

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#2541]
Quest is missing.

![image](https://user-images.githubusercontent.com/55365231/107898211-d3db9b80-6f00-11eb-95f9-48ca23e68aa0.png)

https://classic.wowhead.com/quest=9211/the-ice-guard
https://classic.wowhead.com/quest=9213/the-shadow-guard

**Comment by drejjmit** [comment]
Do you have 'Repeatable quests' turned off? The only requirements that quest has in the code is you need to be level 60.
![image](https://user-images.githubusercontent.com/15526476/107952095-99720d00-6f99-11eb-9ba4-61fe6a33a69b.png)
