### ISSUE TITLE
Craftsman Wilhelm - repair npc

### ISSUE THREAD

**Issue by Djfe** [Questie/Questie#2542]
## Bug description

related to #2329
Craftsman Wilhelm <Brotherhood of the Light> is not shown on the map but he does repairs (eastern plaguelands at the light's hope chapel since P6)
You need to be friendly with Argent Dawn though

https://classic.wowhead.com/npc=16376/craftsman-wilhelm

## Questie version

6.2.5

**Comment by drejjmit** [comment]
Are you sure you have latest version? We enabled him with Phase 6 and v6.2.3.
![image](https://user-images.githubusercontent.com/15526476/108000216-b6363100-6fe9-11eb-9a0c-dc8fe90bf432.png)

**Comment by Djfe** [comment]
You're right, I just didn't see it with all those Quests, there ^^
Disabling other things (quests, etc.) in the legend makes it visible :)
