### ISSUE TITLE
Questie tracker in invalid location, resetting....

### ISSUE THREAD

**Issue by Creansong** [Questie/Questie#2545]
## Bug description

My questie minimap interface is working fine but the tracker with the list of active quests is not functioning properly. When I open the game it says that is is resetting but never does. When I manually reset it to the center of the screen I can see it (though it is not populated) but when I go to move it anywhere else on the screen it disappears immediately 

## Questie version
v6.2.5

**Comment by Gogo1951** [comment]
Hey @Creansong ,

Try deleting your saved variables settings for Questie. If that doesn't work hit us up on Discord. (=

Cheers!
