### ISSUE TITLE
TBC Testing Notes

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#2548]
## Tracker 

- [ ] Issue where if a mob drops 2 objectives, for different quests, only one objective shows on map / in tracker. https://discord.com/channels/@me/657621890373779456/821607248009625620
- [ ] Escort Quests Should always be at top of tracker (under timed quests).
- [ ] Needs to clear when someone leaves the group.
- [ ] Missing "Collect 3 and turn into Real Objective" Type Quests
- [ ] Missing Timed Quests; should always be at top of Tracker.
- [ ] Needs "You don't have any objectives in this zone." message when tracker is empty.
- [x] Needs space between "Quest Complete!" and (Names)
- [x] Needs to say "Complete" when a quest has no objective other than "go talk to that guy over there"
- [x] Needs to show "Complete" for all party members, not just the quest name when it's a social mode quest.
- [ ] Needs to show in Dungeons
- [ ] Needs to show Quest Count at top of Tracker "13/20" (25 in BC, woot!)
- [ ] Needs to show quests like "[30] Elixir of Agony" that have objectives, as well as things you need to buy. Needs to show all quests that get turned in in the current zone.
- [ ] Needs to show Quests that would be turned in to a zone, and what's missing. So like quests in Hillsbrand vs. Alterac get wonky fast. Quests should always show if the quest turns in in the current zone, or has any objective in the current zone -- even if that objective is complete.
- [ ] Nice to have: Show Quest when in a City with an AH if any objectives can be bought (boes')
- [ ] Only show if item has a "use" feature; don't show items that started the quest
- [ ] Show Dungeon Quests in Surrounding Zones
- [ ] Show All Turn Ins in Zone, Regardless if Dungeon or Other Source
- [ ] Show BoE Objective Items when in Zone where they would be turned in
- [ ] Show the "Pre-Objective Items", like the Pylons with the Crystals for https://classic.wowhead.com/quest=717/tremors-of-the-earth / https://classic.wowhead.com/quest=793/broken-alliances
- [ ] - [ ] Some quests don't show? https://discord.com/channels/@me/657621890373779456/822285468917694514
- [ ] Remove double "complete" and just leave it on the text under the quest title. https://discord.com/channels/@me/657621890373779456/822318207863488550
- [x] "Event Trigger" goes away when it's the only objective. Also bad name. "Find where Gol'dir is being held."
- [x] Combine Objectives into One Line "Ambercorn : 0/2 (Gogopriest, Thrive)"
- [x] Complete needs to show for whom "Quest Complete! (Bugzug)"
- [x] Disable WoW Default Tracker on Objective Item Loot
- [x] IGNORE. Needs to have "move" spot to click to move. 
- [x] Missing Escort Quests
- [x] Needs to group objectives so not to have so many rows in the tracker when questing as a group. "0/3 Kill Trolls (Sally, Joe, Mike)" and then only split them on to separate rows if they are at different completion points.
- [x] Needs to have resize corner.
- [x] Needs to save location when you log out.
- [x] Needs to say "Complete" on 10/10 not "10/10"
- [x] Needs to show the same route for everyone in party
- [x] Objectives Need to be Grouped by Quest
- [ ] Objectives need to be sorted by proximity. https://discord.com/channels/@me/657621890373779456/818707244044517416
- [x] Quests show up multiple times based on number of objectives
- [x] Remove placeholder Hearthstones
- [x] Scroll bar needs to only show when it's needed.
- [x] Set Quest Text to 12pt; Objective Text to 10pt; Add bit of space between Objective Text (aprox 2pt worth)
- [x] Take Header and Footer out of Scrollable Section of Tracker
- [ ] Lards Lunch issue - quest kept disappearing and reappearing https://discord.com/channels/@me/657621890373779456/823074925396099092
- [ ] Grim Message showed as complete in quest log, but not complete in tracker. https://discord.com/channels/@me/657621890373779456/823075123338543105

### See Also

#2501 

## Map

- [ ] Should not have Double Turn In Icons when Old Objectives are Enabled; Need to Remove Old-Style Objectives.
- [ ] Need to hide Simplified Objective Markers and show Specific Objective Markers and Patrols when you hold shift
- [x] Objectives for same Quest should be the same color
- [ ] Switch back to WoW Icons for the Simplified Objective Markers https://discord.com/channels/@me/657621890373779456/804826761871097897
- [ ] Still getting both old and new tooltips
- [ ] Simplified Objective Icon tooltip needs "Hold Shift for more details." in footer of the tooltip.
- [ ] Need to show my turn in vs. other people turn ins differnetly; suggest dashed circle around when it's a group turn in and solid when it's my turn in. 
- [ ] Need glow around Objectives to max at 80% opacity. Should always still see the map behind the glow.
- [ ] Put available quests and quest turn ins on top of simplified objective icons.
- [ ] Needs to use entrance waypoints, if you don't have FP. Or FP if you do have one as starting points.
- [ ] Need to remove double tooltips on simplified objective markers. https://discord.com/channels/@me/657621890373779456/822271536329130004
- [ ] Need to show mobs that drop items, not items when you hold shift. https://discord.com/channels/@me/657621890373779456/822271695833661500
- [ ] Need to show who turns quests in on the tooltips. https://discord.com/channels/@me/657621890373779456/822285806353645598

### See Also

#2499 & #2500 

## Minimap

- [ ] Simplified Objective Icons change colors as you move around the zone / complete quests.
- [x] Remove Social Objectives for Quest Turn Ins from minimap as they clutter with your own turn ins.
- [x] Doesn't show objectives for Social Mode Quests
- [x] Remove Simplified Objectives as they interfere with turn-ins and hunter / druid tracking.

### See Also

#2499 & #2500 

## Routes

- [ ] Needs to end at Flight Path
- [ ] Needs to use Flight Path or Starting Locations for each Zone, not center of map

### See Also

#2498 

### See Also

#2502 

### See Also

#2511 

## Tooltips

- [ ] Should say name of item, currently shows name of mob that drops item in Simplified Objective Tooltips. Should also list multiple mobs for drop quests; it only seems to list one mob. https://discord.com/channels/@me/657621890373779456/821569480499920987
- [ ] Not showing when it's only 1 item until after item is looted.
- [ ] Switch off Old Tool Tip Comms
- [x] Quest Objectives showing twice on some quests. (Quests with multiple mobs / objectives like kill and get the head and get the crown off the same mob.)
- [ ] Escort Quests just say "Event" in tooltip https://discord.com/channels/@me/657621890373779456/823074846208032779

### See Also

#2499 & #2500 

## Misc

- [ ] "Work Complete" sound occasionally doesn't fire, or fires twice on Kill quests due to the delay caused by not using events.
- [x] @AeroScripts No completion sounds at all since recent merge into master
- [ ] Error when you Drop a Quest
- [ ] Issue where tracker stops updating and completed quests still show as objectives on map.
- [ ] Memory usage gets quite high, then dips down again. Was topping out at 120 MB, but running garbage collection got it down to 18. Needs some work. https://discord.com/channels/@me/657621890373779456/820420719808348242
- [ ] Needs to only show debugging data when debugging is on. Lots of random stuff still showing; all of it should be hidden behind the debugging enabled flag.
- [ ] Prints out Flight Paths in Chat when you change zones.
- [x] All group members should point to same quest as objective
- [ ] Objective Items aren't Links in Chat https://discord.com/channels/@me/657621890373779456/818716178008244234
- [x] Shift Click on Quests from Quest Log doesn't Link quest link in chat.

### See Also

#2397

**Comment by Gogo1951** [comment]
@AeroScripts Update

**Comment by Gogo1951** [comment]
@AeroScripts Updated with memory usage issue, debugging data flag issue, and "no objectives in zone" message for tracker.

**Comment by theAnton81** [comment]
In the current version 6.2.6 if a mob is involved in more than one quest and one of the quests are completed there is no longer any quest icon in the nameplate or objectives in the tooltip. A /reload fixes it. Will this also be fixed in 7.x?

**Comment by BreakBB** [comment]
@theAnton81 This has already been fixed with #2600 and will therefore be included in 7.0.

Since we are heavily developing for TBC and we "feared" to bring in TBC changes to Classic, the v6.2.6 update didn't include any fixes, sorry.

**Comment by BreakBB** [comment]
7.0 is "dead" with the plans we originally had. Prior to the release of TBC we (the Questie team) struggled with proper time management besides our regular life and jobs. People left the team and everyone is still very limited in time available for Questie since everyone does this in their free time.

**Comment by BreakBB** [comment]
Closing this as this is no longer relevant. If anyone thinks mayor things from the list above are missing then feel free to open separate issues for them.
