### ISSUE TITLE
Unable to resize tracker

### ISSUE THREAD

**Issue by frehrarri** [Questie/Questie#2549]
I'm currently unable to resize the tracker on one of my characters. It was working before and just started happening. I tested this on one of my other characters and it works how it should, so this bug is local to one character only. When I try to resize by dragging the bottom right hand corner with the lines, it does nothing. When holding ctrl and dragging it moves the entire module.

Things I've tried to do to fix the issue:
- Reloading UI
- Restarting WoW
- Resetting tracker
- Disabling/enabling tracker
- Resetting questie
- Disabling/enabling questie
- Deleting/Reinstalling questie

Nothing has solved this so far.

**Comment by frehrarri** [comment]
Issue resolved itself by installing backdated version

**Comment by BreakBB** [comment]
Did you try to delete the Saved Variables of Quesite? You can check the FAQ when you don't know which files you should look for :)
