### ISSUE TITLE
Darkmist Recluse do not drop Acidic Venom Sac

### ISSUE THREAD

**Issue by Bennus** [Questie/Questie#2551]
Quest: https://classic.wowhead.com/quest=1322/the-black-shield

You can see which spiders drop the sac, but ingame the addon tells you to kill Darkmist Recluse spiders, these do not drop it. Only the Darkfang spiders.

(I checked wowhead after killing about 60 spiders without getting a single sac)

**Comment by raethkcj** [comment]
Has this change not made it into a release yet? I'm using v6.2.6 and it's still showing this dropping off the Darkmist spiders after doing Recompile Database.

**Comment by BreakBB** [comment]
Hey @raethkcj yes, this fix is not released for Classic. We've been focussing on a stable TBC version and v6.2.6 didn't include any data fixes.
