### ISSUE TITLE
Quest Character Localisation

### ISSUE THREAD

**Issue by SonicMcCall** [Questie/Questie#2562]
Would it be possible to make an option where you can set it to only see quests in the areas you have travelled. It's personally quite annoying when I'm playing and I see quests from Telldrasil all the way to Elwynn Forest and everywhere in between. I would prefer a system where when you identify a location or a sublocation (eg. Goldshire)  that the quests show up then and not from when you start a brand new character and see quests in Elwynn Forest, Telldrasil and Dun Morogh. It makes the map really cluttered when you have the screen full of "!!!" 

Thanks for taking this feature into consideration
SonicMcCall

**Comment by Gogo1951** [comment]
In theory this exists now. You can hide objectives in unexplored areas, and I think that applies to Quests.

But it's not perfect. Like pats that go through multiple sub-zones, will be shown / hidden based on spawn location. And I think the pat is always there anyway.

Have you tried Leatrix Maps? Most people play with some sort of map mod to remove of war. Trying to pretend you don't know what the zone looks like is a stretch in 2021. (=

https://www.curseforge.com/wow/addons/leatrix-maps-classic
