### ISSUE TITLE
Quest tracker disappears

### ISSUE THREAD

**Issue by imagine82** [Questie/Questie#2568]
I've used Questie for a long time and love it! I have finally started using the tracker part of it as well.
The issue/bug here is, let's say I have a quest where I need to loot 20 pirate hats. Whenever I then pick up an item for that quest, the tracker disappears and I have to disable it and then reenable it for it to come back.
That happens every single time I pick up a quest item.

I am using Questie version 6.2.5

**Comment by Gogo1951** [comment]
Hey @imagine82 ,
What other addons are you using? I haven't seen this behavior at all with Questie. I suspect some sort of conflict. Hit us up on DIscord, and we'll try and work through it. Cheers!
