### ISSUE TITLE
Map/Mini-Map Settings Not Applying Correctly

### ISSUE THREAD

**Issue by SonicMcCall** [Questie/Questie#2569]
## Bug description
There are multiple discrepancies within the general options of Questie. For instance, when Show Available Quest Icons, Show Objective Icons and Mini-map Icons are enabled, there are either no icons on the mini-map or there are just objective icons (Image 1). This can be reverted however by unchecking and rechecking those options as well as Hide Unexplored Area Icons. However, this makes the setting Hide Unexplored Area Icons redundant as then it shows all quest markers and objective icons everywhere in the world despite having hide icons ticked. (Image 2-3) There is also a weirdity that depending on which setting you click first will dictate which gets shown and doesn't update (eg. Doesn't show icons when hide icons is unticked before ticking show available quests and objectives are ticked (Image 4) / Shows icons when hide icons is ticked after ticking show available quests and objectives (Image 5-6)).  This is annoying as when I open my map, (As a level 6 gnome) I see quests in Teldrassil and Elwynn Forest despite not going to either locations yet. I would be fine if the feature showed all quests and objectives in just the areas you've visited (eg. Dun Morogh) and then when I move onto identify Loch Modan, It shows all makers there however I don't want to see every quest maker and objective icon that is related to the alliance... 

## Screenshots
![InkedWoWScrnShot_030621_121450_LI](https://user-images.githubusercontent.com/72543176/110195543-e9e1d980-7e78-11eb-941f-3626a6be664b.jpg)
^Blue= Shows available quests above dwarfs' heads with Show Available Quests and Show Mini-Map Icons ticked but no quest icons show on the mini-map.
![InkedWoWScrnShot_030621_121548_LI](https://user-images.githubusercontent.com/72543176/110195547-ecdcca00-7e78-11eb-953c-2431ed552d2d.jpg)
^Blue= Shows objective icons and available quests despite Hide Unexplored Area Icons being ticked.
^Red= Now shows the available quests on the map unlike beforehand despite the fact that the same settings are enabled after being unticked and then re-ticked.
![InkedWoWScrnShot_030621_122105_LI](https://user-images.githubusercontent.com/72543176/110195549-eea68d80-7e78-11eb-93bc-8b89fcd9aa8c.jpg)
^Blue= Shows available quests in Elwynn Forest and Teldrassil despite Hide Unexplored Area Icons being ticked.
![InkedWoWScrnShot_030621_124248_LI](https://user-images.githubusercontent.com/72543176/110195718-4b567800-7e7a-11eb-912b-f00a1fd6f928.jpg)
^Red= Doesn't show available quests in an area that has been explored.
![InkedWoWScrnShot_030621_124251_LI](https://user-images.githubusercontent.com/72543176/110195721-4db8d200-7e7a-11eb-8b6c-72795169377d.jpg)
^Blue= Doesn't show objective icons and quests despite the fact that Hide Unexplored Area Icons is not ticked.
^Red= Still doesn't show available quests in an area that has been explored despite Hide Unexplored Area Icons not being ticked.
![InkedWoWScrnShot_030621_124305_LI](https://user-images.githubusercontent.com/72543176/110195723-4f829580-7e7a-11eb-8c03-b7a2c0c14920.jpg)
^Blue= Doesn't show objective icons and quests in Elwynn Forest, Teldrassil and Dun Morogh despite the fact that Hide Unexplored Area Icons is not ticked. (Reference Image 3 which is what it should do) (Hahaha shocked face on the right)

## Questie version
I'm currently using Questie v6.2.5 (Released 3 and a half weeks ago at time of report)

**Comment by Gogo1951** [comment]
All getting re-worked for BC. Cheers!

https://github.com/Questie/Questie/issues/2511

**Comment by SonicMcCall** [comment]
So it should be fixed by pre-patch or full release?

**Comment by BreakBB** [comment]
@SonicMcCall Sorry for the late response on this. We hope to get the reworked till the full release of BC. We might be able to get it done earlier, but there is much to do for the TBC/pre patch release. Make sure to follow our Discord and the issue Gogo linked above to get updated on this.
