### ISSUE TITLE
Egg Hunt

### ISSUE THREAD

**Issue by kristinclemens** [Questie/Questie#2574]
## Description
[Egg Hunt (#868)](https://classic.wowhead.com/quest=868/egg-hunt) requires looting 12 [Silithid Egg (#5058)](https://classic.wowhead.com/item=5058/silithid-egg). Questie thinks these drop from Silithid Creeper, Silithid Swarmer, and Silithid Protector, but as far as I can tell they only are lootable by using the Digging Claw on [Silithid Mound (#3685)](https://classic.wowhead.com/object=3685/silithid-mound).

**Comment by Gogo1951** [comment]
@AeroScripts and I saw this bug the other day too! (=

**Comment by Gogo1951** [comment]
Hey @Faeryqueenaeval ,

Looks good!

https://raw.githubusercontent.com/Questie/Questie/master/Database/itemDB.lua

> [5058] = {"Silithid Egg",nil,nil,nil,1,0,0,12,0,{3250,3251,3252,3503,},{3685,},nil,nil,nil,},

https://github.com/Questie/Questie/blob/master/Database/objectDB.lua

> [3685] = {"Silithid Mound",nil,nil,{[17]={{47.3,70.36},{48.09,70.99},{48.1,70.87},{48.54,70.11},{44.2,71.52},{42.88,69.89},{42.63,69.87},{43.54,70.18},{42.91,71.5},{42.93,71.1},{44.12,72.22},{45.17,72.31},{44.94,69.4},},},17,},

**Comment by BreakBB** [comment]
@Gogo1951 Quick heads up: Please don't close the issue before the PR is merged. The PR should automatically close the issue once it is merged :)

Not a real problem in this case, but the issue is not yet fixed ;)
