### ISSUE TITLE
Refactor Events System 

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#2575]
Creating a card for this.

**Comment by Gogo1951** [comment]
@AeroScripts can we mark this as done, or include it with the #2501 / comms around that?

**Comment by BreakBB** [comment]
The event system is something different than comms. At the moment we are listing to all kind of in game events (player login, player level up, quest complete, quest log update, etc.), but there are still timers involved and the handling itself is kind of in a fragile state.

This ticket targets to do a refactoring of all of this and should be done on its own :grin:

**Comment by BreakBB** [comment]
Closing this as we are refactoring the quest event system with #3111 and the other parts will come in smaller parts.
