### ISSUE TITLE
Wrong mob associated with quest item

### ISSUE THREAD

**Issue by Hendo72** [Questie/Questie#2578]
## Description
Darkmist spiders are being identified as dropping the quest item that they do not. It states specifically in the quest description that you get Acidic Venom Sacs from the Darkfang Spiders.

## Wowhead link
https://classic.wowhead.com/item=5959/acidic-venom-sac

## Screenshots
![image](https://user-images.githubusercontent.com/39675478/110251097-dd2eb580-7f4c-11eb-89cc-f80a8ea91039.png)

## Questie version
6.2.5

**Comment by Gogo1951** [comment]
Dupe of https://github.com/Questie/Questie/issues/2551

**Comment by Hendo72** [comment]
Sorry. I did a search and didn't find an open issue.
