### ISSUE TITLE
[Stalking the Stalkers] incorrect tooltip

### ISSUE THREAD

**Issue by Cerby3BR** [Questie/Questie#2580]
Stalking the Stalkers wants us to kill 15 Stalkers and Howlers each, not 10.

https://classic.wowhead.com/quest=7828/stalking-the-stalkers

![WoWScrnShot_030821_234004](https://user-images.githubusercontent.com/54936174/110391594-fd9f6280-8067-11eb-9339-08cc366bb655.jpg)

Version 6.2.5

**Comment by Faeryqueenaeval** [comment]
https://github.com/Questie/Questie/pull/2581

```
       },        
        [7828] = { -- #2580
            [questKeys.objectivesText] = {"Huntsman Markhor at Revantusk Village in the Hinterlands wants you to kill 15 Silvermane Stalkers and 15 Silvermane Howlers. Return to him once the task is complete.","Markhor mentioned that the wolves hide in the wilds of the Hinterlands."}
```

**Comment by Gogo1951** [comment]
Hey @Faeryqueenaeval,

Make sure to move the issue to "Review" when you do the PR fixes. (=
