### ISSUE TITLE
Unusable for a while after login

### ISSUE THREAD

**Issue by sipertruk** [Questie/Questie#2582]
Questie is unusable after login and start working only after I do some game action.
The problem is that at login _QUEST_LOG_UPDATE is happening before _PLAYER_LOGIN.
There's a variable intended for that in your code :
````lua
local hasFirstQLU = false
````
````lua
        -- manually fire QLU since enter has been delayed past the first QLU
        if hasFirstQLU then
            _QUEST_LOG_UPDATE()
        end
````
But it's always false, maybe something was lost in migration.
The problem is solved as soon as I set hasFirstQLU to true in _QUEST_LOG_UPDATE ().

**Comment by BreakBB** [comment]
Hey @sipertruk what version of Questie are you using? Since this topic comes up for the first time now it seems to be either a WIP state of Questie or a very rare scenario.

**Comment by BreakBB** [comment]
Did you try to reset your saved variables? You will lose your Journey progress though (not the completed quests on the map etc) Check [our wiki](https://github.com/Questie/Questie/wiki/FAQ#2-questie-still-doesnt-show-anything)

**Comment by sipertruk** [comment]
I just tested dropping the setting files, did nothing to solve it.

**Comment by BreakBB** [comment]
@AeroScripts could know more about this, since he was the original author of the code piece.

Also @Logonz might have refactored this part as well, with the latest rewrite of the event initialization and handeling.

**Comment by sipertruk** [comment]
This is fixed in recent versions.
