### ISSUE TITLE
Option to add a sound to "Quest complete" event

### ISSUE THREAD

**Issue by Painstormx** [Questie/Questie#2583]
I really miss the option to be able to add a sound to quest complete / quest progress events.
When you are just grinding away, it is very nice with the audible clue instead having to look constantly what you are looting.
In retail I use an addon for this, so that I get the peon "Work complete"/"Jobs done" soundbits on these events.

Since you are already handling these event for updating the tracker, I thought it would be a very nice addition to Questie to be able to add sounds to these events.

Thanks for a great addon, hoping for the continued support in TBC :)

**Comment by Logonz** [comment]
Duplicate of #2397
