### ISSUE TITLE
Questie comms on master

### ISSUE THREAD

**Issue by drejjmit** [Questie/Questie#2584]
## Bug description
```Date: 2021-03-11 23:33:17
ID: 1
Error occured in: Global
Count: 1
Message: ...face\AddOns\Questie\Modules\Network\QuestieComms.lua line 264:
   attempt to index field '?' (a nil value)
Debug:
   [C]: ?
   ...face\AddOns\Questie\Modules\Network\QuestieComms.lua:264: PopulateQuestDataPacketV2()
   ...face\AddOns\Questie\Modules\Network\QuestieComms.lua:453:
      ...face\AddOns\Questie\Modules\Network\QuestieComms.lua:451
   ...face\AddOns\Questie\Modules\Network\QuestieComms.lua:466:
      ...face\AddOns\Questie\Modules\Network\QuestieComms.lua:465
Locals:
```
Getting this error quite often on master.
Not getting it on release version.

## Questie version
master

**Comment by BreakBB** [comment]
If I remember correctly @AeroScripts already found the issue and a solution for it. It has something to do with changing the default state of `.Objectives` to be an empty table instead of `nil`.

**Comment by Logonz** [comment]
Looking at the code that wouldn't fix it right?
The code is basically looking for the ID related to the questIndex (say for example a mobId for a slayquest)
If it's an empty table it would either still get the nil issue or be an empty value which would create a desync potential.

The table has to be populated before the message is sent which is isn't currently, or am i wrong?

**Comment by Gogo1951** [comment]
It's been fixed with TBC fixes. @AeroScripts
