### ISSUE TITLE
"Revenge of Gann" Quest Misidentified on map & minimap

### ISSUE THREAD

**Issue by Zenatsu** [Questie/Questie#2586]
The quest "Revenge of Gann" obtained from "Gann Stonespire", requires you to destroy a "Bael Modan Flying Machine". Currently the Quest marker is a cog wheel that is at the keep Bael Modan proper, however the actual machine you must destroy is south west at the top of the archeological pit, on top of a wooden tower.

This is noted by the comments within the wow-head quest database, as well as attached screen shots.

wowhead link: https://classic.wowhead.com/quest=849/revenge-of-gann#comments
Quest Location Screenshots:
![Q2](https://user-images.githubusercontent.com/12805510/111104017-b4df2200-851d-11eb-9acb-ffb0a02b728f.png)
Cog wheel is shown at incorrect location. Player Arrow Icon is at correct location. (Coords: 47.0X, 85.6Y)
![Q1](https://user-images.githubusercontent.com/12805510/111104018-b577b880-851d-11eb-9b1e-389b6bfb774e.png)

**Comment by Gogo1951** [comment]
Hey @Zenatsu ,

I see you also have the Tear of the Moon quest -- that seems to be the gear on your minimap. It's located in the keep.

We seem to have the correct location for the flying machine in the data.

> [3644] = {"Bael Modan Flying Machine",nil,nil,{[17]={{46.97,85.63},},},17,},

Sometimes objectives bug / disappear when you go into a dungeon and come back out, or play for a long time without reloading UI. Guessing that's what happened here.

Cheers!
