### ISSUE TITLE
Hiding questie on map doesn't hide all icons 

### ISSUE THREAD

**Issue by Drat3r** [Questie/Questie#2587]
## Bug description

Hiding icons from map, either from menu or the map button doesn't hide all icons on the map. The objectives with "paths" stay showing.

## Screenshots

![WoWScrnShot_031521_115507](https://user-images.githubusercontent.com/80687774/111150367-4edeb300-858e-11eb-85be-9bceb471e110.jpg)
![WoWScrnShot_031521_115512](https://user-images.githubusercontent.com/80687774/111150399-57cf8480-858e-11eb-99d7-4ebdd1a0a36c.jpg)

## Questie version

Running on v6.2.5 (classic)

**Comment by Gogo1951** [comment]
Hey @Drat3r ,

Should be fixed with 7.0. Cheers!

**Comment by BreakBB** [comment]
... which will be released with the pre patch for TBC.

**Comment by BreakBB** [comment]
We need to handle the waypoint frames in `QuestieQuest:ToggleNotes`. This is most likely not tackled by any of our WIP branches yet.
