### ISSUE TITLE
Stutter on leaving combat

### ISSUE THREAD

**Issue by 19codeman93** [Questie/Questie#2588]
As the title says. Whenever I exit combat, I get a split-second freeze/stutter. I have disabled all addons but Questie to narrow it down. Is there a setting/fix for this?

**Comment by 19codeman93** [comment]
Downloaded the most recent master zip and it fixed my issue.

**Comment by BreakBB** [comment]
@19codeman93 Glad you already found a solution 👍 You should checkout an addon manager like [CurseForge client](https://curseforge.overwolf.com/) or [Ajour](https://www.getajour.com/) to keep your addons up to date all the time.

**Comment by BreakBB** [comment]
As a follow up this issue has the same reason as #2592 and will be permantely fixed with #2601

**Comment by 19codeman93** [comment]
Moot point now, but the version ajour had had the stutter. I had to do some googling to get me to here where I eventually found the master zip. Still no issues, though. Thanks!
