### ISSUE TITLE
The Bloodsail Buccaneers - Object locations are random

### ISSUE THREAD

**Issue by BreakBB** [Questie/Questie#2593]
## Description

The quest [https://classic.wowhead.com/quest=604/the-bloodsail-buccaneers](The Bloodsail Buccaneers) require you to collect three items. There are multiple possible locations where the objects holding the required items can spawn and it is totally random at which location which object spawns.

## Wowhead link

https://classic.wowhead.com/quest=604/the-bloodsail-buccaneers

## Screenshots

![grafik](https://user-images.githubusercontent.com/33514570/111906144-754d9400-8a4f-11eb-861e-7cb5162db432.png)

## Questie version

Current master

**Comment by Muehe** [comment]
Seems to have been fixed by some DB update in the meantime (present in all 3 DBs):

```
[2086] = {"Bloodsail Charts",nil,nil,{[33]={{29.59,80.84},{27.15,82.68},{27.73,83.1}}},33},
[2087] = {"Bloodsail Orders",nil,nil,{[33]={{26.96,82.56},{27.18,82.66},{27.74,83.13}}},33},
```
