### ISSUE TITLE
Tooltip shows own player name behind objective but lacking other players

### ISSUE THREAD

**Issue by BreakBB** [Questie/Questie#2594]
## Bug description

The map correctly showns the objective progress of other players. The tooltip of the mobs only shows my own progress but also prints the name behind it. No other players are shown though.

## Screenshots

![grafik](https://user-images.githubusercontent.com/33514570/111906302-310ec380-8a50-11eb-951d-f18f0fd08149.png)

## Questie version

Current state of the `l10n` branch, but most likely also on master

**Comment by Gogo1951** [comment]
Yell was disabled I think for the new tool tips. We were playing around to see what was useful and what wasn't. Probably need to add yell updates back to this.

**Comment by BreakBB** [comment]
Since this happened on the `l10n` branch which is pretty close to the master branch I think it will be on master as well. Most likely related to the objective refactoring. Tooltips in general seems to be bugged on the branch 🙈

**Comment by BreakBB** [comment]
This is fixed on the current master change. I can no longer reproduce this.
