### ISSUE TITLE
Unobtainable Quest listed as Available in "Quests by Zone"

### ISSUE THREAD

**Issue by FizzyBubblech9** [Questie/Questie#2596]
## Description

The Mage specific quest "Speak with Bink" becomes disabled after the quest "Speak with Jennea" is completed (According to WoWHead, links provided). This is also true the other way around (Speak with Bink disables Speak with Jennea). Questie still shows the one quest as "Available" when the other quest is completed. I believe when one of the mentioned quests are complete, the other should also be listed under complete (or alternately moved to "unobtainable") 

## Wowhead link

<https://classic.wowhead.com/quest=1879/speak-with-bink>
<https://classic.wowhead.com/quest=1860/speak-with-jennea>

## Screenshots

![Picture](https://user-images.githubusercontent.com/81126231/111928867-3e956f00-8a8b-11eb-8e05-6992a3730a0a.png)

## Questie version

V6.2.5

**Comment by BreakBB** [comment]
According to #1192 you can do both quests if you didn't accept/completed one of the follow up quests
