### ISSUE TITLE
A Final Blow link in whisper window (ALso using WIM) throws this error

### ISSUE THREAD

**Issue by MysticalOS** [Questie/Questie#2603]
1x ...rfaceQuestie\Modules\Tooltips\ChatFilter.lua:27: bad argument #1 to 'unpack' (table expected, got nil)
[C]: in function `unpack'
...rfaceQuestie\Modules\Tooltips\ChatFilter.lua:27: in function `filterFunc'
FrameXML\ChatFrame.lua:3074: in function `ChatFrame_MessageEventHandler'
FrameXML\ChatFrame.lua:2797: in function `ChatFrame_OnEvent'
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>

Locals:
(*temporary) = nil
(*temporary) = "table expected, got nil"

When Attempting to link "A Final Blow"

EDIT, got it a few more times too when user tried sharing quests in party chat. I was definitely on latest release version.

**Comment by BreakBB** [comment]
The recent changes to the chat filter logic should have fixed this.
