### ISSUE TITLE
Out of Date Pop-up for Major and Dot-Releases

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#2606]
We have a ton of users on very old versions of Questie in Classic and we need a better way to encourage people to keep their Questie up-to-date. 

## Minor Releases

At Sign On, in chat:

{rt1} Questie : There is a new version of Questie available! Update your add-ons to get the latest features, quest data, performance improvements.

## Major and Dot-Releases

At Sign On, in chat:

{rt1} Questie : There is a new version of Questie available! Update your add-ons to get the latest features, quest data, performance improvements.

Plus pop-up.

![New Mockup 4](https://user-images.githubusercontent.com/55365231/115158044-e59d0480-a051-11eb-965c-44c25ffa91f5.png)

### Text for Pop-up

Questie Update Notice

Your version of Questie is EXTREMELY old and you are missing out on some great new features, data fixes, and performance improvements!
 
We strongly recommend using an add-on manager to keep all of your add-ons up-to-date.

Ajour
https://www.getajour.com/

CurseForge
https://curseforge.overwolf.com/

WoWUp
https://wowup.io/

Wago
https://addons.wago.io/

Still prefer to manually install add-ons? You can download Questie directly from these locations:

Curseforge
https://www.curseforge.com/wow/addons/questie/files

GitHub
https://github.com/Questie/Questie

WoWInterface
https://wowinterface.com/downloads/info24994-Questie.html

Prefer not to see this reminder agian? You can disable it under Questie Options.

Close

**Comment by BreakBB** [comment]
We didn't really like the idea of Questie causing any pop ups. Even though it is a good idea to improve the highlighting of the "Questie out of date" message!

Maybe add a small popup/note when the options are open, but not on login.

**Comment by Gogo1951** [comment]
We can put something in the Options, "Disable Out of Date Popup Reminder" -- sure. @BreakBB

**Comment by BreakBB** [comment]
The idea behind my comment was to only show the "out of date popup" when someone opens the options. I don't like the idea of having a Questie popup on login!

**Comment by Gogo1951** [comment]
Details, Gargul, Elv... lots of add-ons use a pop-up.

Questie was in a great spot to promote updates and help all users and add-on creators.

Closing this as stale, it'll never get worked on.
