### ISSUE TITLE
Warrior class trainer showing for mage

### ISSUE THREAD

**Issue by Cyberzombie** [Questie/Questie#2608]
Title says it all. A `/console reloadui` did not help, nor was there a way within Quest to change it.

**Comment by Gogo1951** [comment]
Post a screenshot please. What trainer? What version of Questie are you on?

**Comment by Cyberzombie** [comment]
Sorry for the slow turnaround - I've been neglecting my email.

This is for classic.

![image](https://user-images.githubusercontent.com/759574/113888841-b1dbf800-9790-11eb-8d88-b2e70a5c55da.png)

**Comment by a7madelk** [comment]
Same issue

**Comment by Gogo1951** [comment]
@a7madelk & @Cyberzombie - did you rebuild the DB?

**Comment by Cyberzombie** [comment]
No… ?

**Comment by BreakBB** [comment]
@Cyberzombie You should be able to solve this by recompiling the database (Advanced Settings).

But @AeroScripts should still look into this!

**Comment by Muehe** [comment]
Working as intended now on WotLK PTR (Era realms seem to be offline, assumed resolved there too).
