### ISSUE TITLE
Questie quest Tracker cannot be disabled, re-appears after reloading ui or zoning

### ISSUE THREAD

**Issue by Chad90b** [Questie/Questie#2612]
## Bug description

After disabling the Questie Quest Tracker, it re-appears after reloading ui or zoning (screen load during boat travel)

## Screenshots

![image](https://user-images.githubusercontent.com/68355086/113083720-f558c400-91dc-11eb-84ca-3b32f164481f.png)
^ image: even with tracker disabled, the tracker is visible behind the kaliel's tracker as seen

![image](https://user-images.githubusercontent.com/68355086/113083764-11f4fc00-91dd-11eb-84cb-190e93196d15.png)
^ image: ticking auto track quests and then unticking it, fixes it, but, only temporarily until you reloading the ui or perform zoning...then the tracker re-appears

## Questie version

Questie v6.2.5

**Comment by Gogo1951** [comment]
We'll test this in the new tracker! #2501
