### ISSUE TITLE
TBC Beta Issue Notes

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#2613]
@AeroScripts I'll help clean up what we get form Discord.

**Comment by Gogo1951** [comment]
- [ ] didn't have the location for The Cleansing Must Be Stopped... [[62] The Cleansing Must Be Stopped (9370)]https://discord.com/channels/263036731165638656/809852539147255868/827018889640149012
- [ ] Who are they ? quest is Terokkar Forest isnt showing up https://tbcdb.com/?quest=10041 https://discord.com/channels/263036731165638656/809852539147255868/827019617037189130

**Comment by BreakBB** [comment]
Things which still needs fixes:

- [ ] "An Old Gift" is showing but not available (Level 58) [Discord link](https://discord.com/channels/263036731165638656/809852539147255868/827181415250264085)
- [ ] "Unyielding Souls" is showing but not available (Level 58) [Discord link](https://discord.com/channels/263036731165638656/809852539147255868/827181506408480800)
- [ ] End location for "The Missing Fisherman" is wrong [Discord link](https://discord.com/channels/263036731165638656/809852539147255868/827132646605848616)
- [ ] The whole Draenei Shaman "Call of Water" quest chain is broken [Discord link](https://discord.com/channels/263036731165638656/809852539147255868/827095433590997012)
- [ ] Tooltip data on mobs is missing for "A Warm Welcome" (9728) [Discord link](https://discord.com/channels/263036731165638656/809852539147255868/827081249314963467)
- [ ] No objective location for "The Seer's Relic" (9545) [Discord Link](https://discord.com/channels/263036731165638656/809852539147255868/827069261738541086)
- [ ] "Losing Gracefully" is showing but not available (Level 62) [Discord link](https://discord.com/channels/263036731165638656/809852539147255868/827069904410640436)
- [ ] Objective location for "Torgos!" might be wrong [Discord link](https://discord.com/channels/263036731165638656/809852539147255868/827064157731815434)
- [ ] No objective location for "An Ambitious Plan" (9383) [Discord link](https://discord.com/channels/263036731165638656/809852539147255868/827059367400046592)
- [ ] No objective location for "Cleansing the Waters" (9427) [Discord link](https://discord.com/channels/263036731165638656/809852539147255868/827056636320415765)
- [ ] No objective location for "Fel Spirits" (10909) [Discord link](https://discord.com/channels/263036731165638656/809852539147255868/827055421768073236)
- [ ] "Watcher Leesa'oh" is showing but not available [Discord link](https://discord.com/channels/263036731165638656/809852539147255868/827053054477991997)
- [ ] No objective location for "What Book? I Don't See Any Book." (10231) [Discord link](https://discord.com/channels/263036731165638656/809852539147255868/827051232732381184)
- [ ] No objective location for "Testing the Antidote" (10255) [Discord link](https://discord.com/channels/263036731165638656/809852539147255868/827042845273489418)
- [ ] No objective location for "Natural Remedies" (10351) [Discord link](https://discord.com/channels/263036731165638656/809852539147255868/827040551069155348)
- [ ] No objective locations for "Birds of a Feather" (9397) [Discord link](https://discord.com/channels/263036731165638656/809852539147255868/827026893483671552)
- [ ] No objective locations for "The Cleansing Must Be Stopped" (9370) [Discord link](https://discord.com/channels/263036731165638656/809852539147255868/827018889640149012)
- [ ] "Malevlent Remnants" is still available while on "Curse of the Violet Tower" [Discord link](https://discord.com/channels/263036731165638656/809852539147255868/827433942738665502)
- [ ] "Sunfury Garrison" is showing but not available [Discord link](https://discord.com/channels/263036731165638656/809852539147255868/827434603848925205)

**Comment by BreakBB** [comment]
Thinks left to do after the merge of #2607:

- [ ] Update HBD again when it's updated or tempfix (for #2625 )
- [ ] Find out why `zoneMap[QuestieDB.sortKeys.SPECIAL]` does seem to not exist
- [ ] Find out if `QuestieProfessions` needs to be updated, since the required functions were Classic specific and removed prior to Shadowlands
- [ ] Find a solution for `Questie\Libs\LibUIDropDownMenu\LibUIDropDownMenu.lua:1586: hooksecurefunc(): UIDropDownMenu_HandleGlobalMouseEvent is not a function` (A fix is already provided in [this issue](https://www.curseforge.com/wow/addons/libuidropdownmenu/issues/11))

**Comment by Gogo1951** [comment]
Closing this as we have the spreadsheet now. Feel free to compare the two, but feels like there's a lot of overlap. 

https://docs.google.com/spreadsheets/d/1_zqtjyafw83HJ-Umu9x_IbWGx9XGjzZpxXvj3FHhWWc

**Comment by drejjmit** [comment]
Issues on this list are missing in the sheet. Maybe best to move them over before closing the issue so they don't get lost.

**Comment by BreakBB** [comment]
I agree to @drejjmit closing this issue without going through the changes will make us lose information on open bugs.

Moreover I just listed new things we have to do yesterday because of the merge to master :sweat_smile: Please leave this open or move the issue to the sheet.
