### ISSUE TITLE
Lag/freezes upon killing mobs

### ISSUE THREAD

**Issue by jonomurphy** [Questie/Questie#2620]
Hiya,

I've checked with/without Questie enabled, and it seems that whenever I kill a mob from a quest, I'll have a 0.5 second lag/freeze right after?

not too sure how to sort this out. This may have only been for a specific quest or two (timed quests in Loch Modan).

**Comment by Gogo1951** [comment]
Hey @jonomurphy ,

In the Options under Advanced you'll find the "Profiler" -- can you run that for a bit and post a screenshot of what you find? Thanks!

**Comment by jonomurphy** [comment]
Will do!

**Comment by BreakBB** [comment]
This was fixed with #2601 and will be included in the next release 👍
