### ISSUE TITLE
Questie tracker in invalid location, resetting...

### ISSUE THREAD

**Issue by LegioN7** [Questie/Questie#2621]
## Bug description
Bug is related to the quest tracker location. It seems to be malfunctioning when ElvUi is installed.
Move the ElvUi quest tracker location to the right side of the screen and it will eventually recreate this error.

## Image
![image](https://user-images.githubusercontent.com/1086104/113515968-b496dd00-9545-11eb-86e2-8970b2cecbcf.png)

## Questie version
6.2.5

**Comment by Gogo1951** [comment]
Hey @LegioN7,

I don't have this problem on Classic. 

I play with ElvUII and the tracker on the right.

Tracker is getting replaced soon.

We'll keep an eye out.

**Comment by LegioN7** [comment]
@Gogo1951 
I am able to recreate the issue with a brand new installation of WoW Classic, Questie, and ElvUI

Set the font size for zones to 14.

For ElvUI
Let the default Quest Objective Frame Location be
x:-135 Z:-300

It will error out every time.

![image](https://user-images.githubusercontent.com/1086104/116061230-9efe6a00-a650-11eb-8a10-daa6710717e4.png)
![image](https://user-images.githubusercontent.com/1086104/116061251-a6be0e80-a650-11eb-9287-b2f3ff925bdc.png)

**Comment by oscarTGouch** [comment]
I found a solution. it seems to be a conflict with Elvui and Questie tracker locations. My Elvui locator was in the center of the screen and the Questie locator was where I asked it to be, under the mini map on the right side of the screen. When logging on it would error out and reset to the Elvui position.
Solution:
1. Login to WOW and enable Elvui
2. 2. Enable the Elvui "Toggle Anchors"
3.  Move the Elvui quest tracker window to the location you want your Questie tracker title bar to be
4. Close Elvui
5. Open Questie options and locate the Questie tracker to the same place.
6. Log off WOW to save the locations, then log back in.
7. Done
