### ISSUE TITLE
Roll the bones - Missing item drop source

### ISSUE THREAD

**Issue by davidcraig** [Questie/Questie#2622]
## Description
Hovering over mob (Elder Diametradon) not showing as a quest objective for Roll the Bones

## Wowhead link
https://classic.wowhead.com/quest=3882/roll-the-bones (quest)
missing drop source:
https://classic.wowhead.com/npc=9164/elder-diemetradon

![image](https://user-images.githubusercontent.com/11975187/114094672-7f2b2000-98b4-11eb-8d5e-1af4574e99be.png)

## Questie version
v6.2.5

**Comment by BreakBB** [comment]
Hey @davidcraig can you tell if you killed the mob for another quest so it was initially used for two quests and not the "Rolling the Bones"?

**Comment by davidcraig** [comment]
As far as the quests I have done, there was only Dinosaur Bone as a reason for me to kill the elder's, the elite ravasaur dino's were the only ones showing as an objective of the quest whereas this mob did not, I knew that it was not only the elites that dropped the item thankfully

**Comment by BreakBB** [comment]
The thing is the current Questie version has a bug which removes all tooltips on a mob if just one of them is complete. This bug is already fixed and will be included in the next version.

Our database does have the reference that the bones also drop from the Elders.

Are you sure the Elders were also not marked as valid objective on the map? Or if it was just the misleading tooltip?

**Comment by davidcraig** [comment]
I don't recall if I saw them on the map, but they definitely weren't on the tooltip (and the icon that usually shows when a mob has a quest drop was also missing) - perhaps the bug you mentioned will fix this in future :)

**Comment by BreakBB** [comment]
Since our data looks just fine for this quest I actually assume it was the bug I memtioned before. I will close this issue for now, but feel free to open up a new one if you encounter anything unusual! We really appreciate the reports 🙏
