### ISSUE TITLE
Bailor's Ore Shipment

### ISSUE THREAD

**Issue by Stajni** [Questie/Questie#2624]
## Description

Paladin Weapon Quest - Part of it is to do the quest (the title of this issue) in Loch Modan. The "bug/issue" is that Questie shows it drops from mobs, but its actually from a box you can loot from the ground.

## Wowhead link

https://classic.wowhead.com/object=92420/bailors-ore

**Comment by BreakBB** [comment]
This is a duplicate of #2561 and has already been fixed. Thanks @Stajni for the report the fix will be included in the next release 👍
