### ISSUE TITLE
Rhapsody's Kalimdor Kocktail don't show up River thing

### ISSUE THREAD

**Issue by SunnyJang38** [Questie/Questie#2626]
## Description

Rhapsody's Kalimdor Kocktail don't show up River thing
[6258] = {"Ironfur Liver",nil,nil,nil,1,0,0,12,0,{5274,5272,5268,},nil,nil,nil,nil,},
[6259] = {"Groddoc Liver",nil,nil,nil,1,0,0,12,0,{5260,5262,},nil,nil,nil,nil,},

## Wowhead link

https://classic.wowhead.com/quest=1452/rhapsodys-kalimdor-kocktail

## Questie version

v6.2.5

**Comment by BreakBB** [comment]
Hey @SunnyJang38 can you explain what you mean by "River thing"? Is an objective missing or something wrong with the "Roc Gizzard" item?

**Comment by SunnyJang38** [comment]
> Hey @SunnyJang38 can you explain what you mean by "River thing"? Is an objective missing or something wrong with the "Roc Gizzard" item?

sorry, i mean Ironfur Liver & Groddoc Liver. it's no show in Feralas but Tanaris

**Comment by Gogo1951** [comment]
I'm seeing all these items in the DB. My guess is that the bug where if you duck into a Dungeon or toggle Questie on / off is actually at fault here. Data looks good. We'll keep an eye out.
