### ISSUE TITLE
Kalimdor Quest Pins and objectives are missing entirely + some NPC pins (banker, auction etc.)

### ISSUE THREAD

**Issue by Trabole** [Questie/Questie#2627]
## Description
All quest Icons and objectives are not working on Kalimdor, the image relates to 6161, error is generic to all of them.

## Wowhead link
https://classic.wowhead.com/quest=6161/claim-rackmores-treasure 

## Screenshots
![image](https://user-images.githubusercontent.com/82372544/114369910-8b023500-9b87-11eb-9054-d06ff6960803.png)
![image](https://user-images.githubusercontent.com/82372544/114370290-fcda7e80-9b87-11eb-8411-3a1f36141e8c.png)

## Questie version
v6.2.5

**Comment by Trabole** [comment]
have tried sync, reinstall, disabling all other addons, issues started before downloading curseforge(have that now as well).

**Comment by Trabole** [comment]
![image](https://user-images.githubusercontent.com/82372544/114378185-213a5900-9b90-11eb-9fbc-b4f7053bc319.png)

getting these as well.

**Comment by BreakBB** [comment]
Uff, looks like this is a bugged quest which "kills Questie".

I will look into it later today! Thanks for the report.

To verify it would be nice if you could abandon the bugged quest or complete it.

**Comment by Trabole** [comment]
True, it could be one quest, problem is I do not know which one it would be, going to abandaon a few, I can pinpoint the zone (ashenvale) as root cause.

**Comment by Trabole** [comment]
It is not, at some point yesterday evening I had lost all questie functionality on Kalimdor, I am tracerouting now to the remaining quests from Ashenvale which I have, I do not have the exact quest from which this began.

**Comment by Trabole** [comment]
Have abandoned all quests from both chars, nothing change.

Proceeded to reinstall the addon still nothing changed.

Will attempt with game reinstall as well.

**Comment by Trabole** [comment]
After reinstalling the client and addon, the situation has been restored, but the root cause is still missing.

**Comment by BreakBB** [comment]
@Trabole You should have checked [the FAQs](https://github.com/Questie/Questie/wiki/FAQ#2-questie-still-doesnt-show-anything) before reinstalling all. The settings of addons are stored at a different point than the addon itself. So a "reinstall" requires more than just deleting the Questie folder.

I am glad it is fixed for you, but strange that is happened in the first place. I will close this issue for now, but would be very happy if something similar will happen again 👍
