### ISSUE TITLE
Blizzard Quest List imposed over Questie Tracker - How to remove?

### ISSUE THREAD

**Issue by Zalaan** [Questie/Questie#2629]
Recently the Blizzard quest list has been appearing over the top of the Questie Quest Tracker I am using. Can I get advice on how to turn it off please. I tried turning off 'Automatic Quest Tracking', under 'Display', but this turns off Questie - not the blizzard list.

Would appreciate any advice.

**Comment by BreakBB** [comment]
@Zalaan Do you have "Enable Tracker Hooks" enabled? This needs to be enabled to prevent the Blizzard tracker to show up.

**Comment by Zalaan** [comment]
Thank you - this was the problem!! Must admit didn't really understand what the "hooks" aspect meant.
Cheers
