### ISSUE TITLE
Gathering Leather (768)

### ISSUE THREAD

**Issue by Arccai** [Questie/Questie#2637]
**Misplaced in the Journey feature.**

**Gathering Leather** (768)
This is an "Skinning" quest,
but appears for everyone.

Placed in Thunder Bluff section.
Should be placed in Profession section.

[Wowhead Link](https://classic.wowhead.com/quest=768/gathering-leather)

**Comment by BreakBB** [comment]
Fixed wtih 29ef101fe3cff7d44425bf577c61936a2a7d2347
