### ISSUE TITLE
Kodo Hide Bag (769)

### ISSUE THREAD

**Issue by Arccai** [Questie/Questie#2638]
**Misplaced in the Journey feature.**

**Kodo Hide Bag** (769)
This is an "Leatherworking" quest,
but appears for everyone.

Placed in Thunder Bluff section.
Should be placed in Profession section.

[Wowhead Link](https://classic.wowhead.com/quest=769/kodo-hide-bag)

**Comment by BreakBB** [comment]
Fixed with 29ef101fe3cff7d44425bf577c61936a2a7d2347
