### ISSUE TITLE
Option to only show icons for currently tracked quests.

### ISSUE THREAD

**Issue by theAnton81** [Questie/Questie#2640]
Some zones have a lot of quest making it hard to keep track of where you need to go when the whole map is plastered with tiny icons, an option to only show currently tracked quests would be awesome. :)

**Comment by BreakBB** [comment]
Hey @theAnton81 did you try to "focus" a quest in the tracker? That reduces the visibility of all other quest icons.

**Comment by Gogo1951** [comment]
New tracker will have a tracking / untracking ability I believe. Marking this as closed / dupe.

#2501
