### ISSUE TITLE
Tracker enchancements

### ISSUE THREAD

**Issue by theAnton81** [Questie/Questie#2641]
Would love to have the ability to set a fixed size/position for the tracker, objectives that are being truncated would preferably prioritize showing counts. Height wise a scroll bar could be implemented.

**Comment by BreakBB** [comment]
Did you check #2501 ? We are planning to do a complete overhaul of the Tracker in a near future :grin:

**Comment by Gogo1951** [comment]
New tracker will have a scroll bar. Marking this as closed / dupe.
