### ISSUE TITLE
Hunter trainer -- showing warrior trainer 

### ISSUE THREAD

**Issue by Qylie** [Questie/Questie#2651]
When asked to show trainers it is showing the warrior ones, even though I am on a hunter.  

Questie v6.2.6

![wrong train](https://user-images.githubusercontent.com/35853634/115969221-2e910500-a4f9-11eb-836e-9a185eb920fa.jpg)

**Comment by Qylie** [comment]
![wrong train](https://user-images.githubusercontent.com/35853634/115969361-d0185680-a4f9-11eb-852a-f86d950083db.jpg)

**Comment by QartemisT** [comment]
Related to #2608 ?

**Comment by Qylie** [comment]
I solved this by doing a recompile of the database

**Comment by Gogo1951** [comment]
Solved. Closing.
