### ISSUE TITLE
Can't hide quests like "A Donation of Wool"?

### ISSUE THREAD

**Issue by Bogdanov89** [Questie/Questie#2653]
In vanilla classic in every capital city there are quests like A donation of wool.
Unfortunately they can not be hidden with any of the questie options like "hide repeatable quest" and similar.

Please allow us to hide these particular Donation quests without also having to hide other types of quests.

**Comment by drejjmit** [comment]
Just shift click them on the map and you can hide any quest you want.

**Comment by Gogo1951** [comment]
Closing. We'll add better tooltips to help people know about the Shift to Hide functionality in 7.0.
