### ISSUE TITLE
Option to hide untracked quest icons on the Map?

### ISSUE THREAD

**Issue by Bogdanov89** [Questie/Questie#2658]
Thank you for this great addon!

Would it please be possible to implement an option that would hide the quest item icons on the big Map for quests that we are not tracking in the tracker?

For example when i am in the classic Barrens the entire zone Map is filled with various quest item icons from all the 10+ barrens quests i have - but i only wish to currently see the quest item icons on the map for the two quests i am actively tracking.

**Comment by Gogo1951** [comment]
We've spoken on this a few times... check the new dynamic tracker and simplified objective markers in 7.0. Should help!

Closing this.
