### ISSUE TITLE
Integrate Wide Quest Log Functionality into Questie

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#2685]
Many users prefer using a wide quest log, and instead of forcing them to install another add-on, we want to include that functionality into Questie. bloodline_, the creator of Wide Quest Log, will be helping out here! (=

- [x] Add Wide Quest Log Functionality https://www.curseforge.com/wow/addons/widequestlog
- [x] Nice to have: Toggle On / Off for Options if users want to Disable

Thanks!

**Comment by BreakBB** [comment]
Won't happen see #2686
