### ISSUE TITLE
Support for Seasonal Phased Content

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#2702]
Hey @AeroScripts & @BreakBB ,

So this is a bit forward looking, but I think it'd be great if we added in a "Phase" to Quests for TBC content. This would be to support the content if Blizzard ever does create Seasonal Classic Releases. We won't want to have to support the addon content every release, we'll just want to have it smart enough to know "That Quest came in Phase 2, and since we're in Phase 3 now it's safe to show it." Just don't want to have to re-jig the content every patch like we did the first time through. Seems easy enough to add a Phase flag to Quests, NPCs, Items, etc. going forward.

**Comment by BreakBB** [comment]
The problem with this is, that we don't really know when a phase is released. We could guess the interface version of the patches coming.

Addind some sort of "Phase flag" we can set with a release, might be possible though. It would also require to add this information to every quest (or at least to every quest not available in P1). We have a list of most of these quests in `QuestieQuestBlacklist.lua` which might be useful.

**Comment by Gogo1951** [comment]
Step 1 - Getting the data right.

Step 2 - Coming up with UI for the data.

Assuming we want this to be as effortless on our part as possible to support.

I think something simple like a drop down in Options letting the user pick which phase they are in would work.

Accompanied by an addition to the communications around which phase others were using, and a little message reminding the user to toggle the correct phase if a mismatch was detected.

Would be good to build "Phase" as a field in the data ASAP I think.

**Comment by Gogo1951** [comment]
Closing as stale. Will never get worked on.
