### ISSUE TITLE
Localization Status Report

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#2704]
Not quite sure where to put this, but would love a feature that gave a summary of what still needed to be translated. Maybe during the build process, it could search for "nil" by each locale, and post a summary?

Would also be good if we had a programmatic way of identifying missing English strings that were added, or English strings that were changed, from the original files. Seems like every time we change English, we should reset the other Locales.

Open to suggestions.

Love to just have a summary file like this at the top of the Locale folder, something like: 

## Missing Strings in All Files

["zhTW"] 88
["koKR"] 64
["deDE"] 41
["ruRU"] 37
["zhCN"] 35
["esES"] 13
["ptBR"] 10
["frFR"] 9
["esMX"] 4 

## Unmatched English Strings Found In

1 - FilePath/FileName.lua
     - line 12
     - line 72

2 - FilePath/FileName.lua
     - line 99

**Comment by BreakBB** [comment]
This is a great idea! And should be quite easy to add.

Missing translations are currently printed with `Questie:Debug`, which can be easily changed to something more useful. Finding these in the build script might be more complicated though.
