### ISSUE TITLE
Missing Dungs & Zones

### ISSUE THREAD

**Issue by GillsITWorld** [Questie/Questie#2744]
We are missing the following Dungs for https://github.com/Questie/Questie/blob/master/Database/Zones/zoneTables.lua
Old Hillsbrad Foothills
The Black Morass
Stratholme Past
Hyjal Summit

Also missing Zone
2300 = caverns-of-time

**Comment by drejjmit** [comment]
All are added except 'The Culling of Stratholme' because that's a Wrath of the Lich King dungeon.
