### ISSUE TITLE
Latest zhCN locale database change in tbc-api-fixes branch not included in master/B2 release

### ISSUE THREAD

**Issue by qqytqqyt** [Questie/Questie#2751]
## Questie version TBC - B2

Hello,

I noticed the branch _tbc-api-fixes_ has been deleted however the changes to the zhCN locale data base was not merged. 

E.g. I made a change to add all TBC quests data through this PR https://github.com/Questie/Questie/pull/2630 but the quest data from https://github.com/Questie/Questie/blob/master/Localization/lookups/lookupQuests/zhCN.lua was unchanged.

However, the change we made earlier for zhTW (https://github.com/Questie/Questie/pull/2623) was included in the latest zhTW locale data.

Will there be any plans that the TBC zhCN locale data will be included in the newly formatted locale code?

Thanks

**Comment by BreakBB** [comment]
Uff, damn! :O I am sorry that this happened. I will look into it, reopening another PR to include the data would still be very helpful! 🙏🏻

**Comment by qqytqqyt** [comment]
New PR has been submitted https://github.com/Questie/Questie/pull/2800 based on the latest master code
Note that some new entries have already been added through other commits. The PR has corrected some of these entries (mainly because of incomplete data from Wowhead db) after comparing them against in-game data.

**Comment by qqytqqyt** [comment]
The new commits have been merged
