### ISSUE TITLE
Objective not showing - Tome of the Cabal

### ISSUE THREAD

**Issue by lucasfevi** [Questie/Questie#2752]
## Description
The quest objective **Tattered Manuscript** of Warlock's level 30 quest for Felhunter **Tome of the Cabal** does not have a marker on the map. Also when you hover the chest, it does not show on the tooltip it contains the item needed.

## Wowhead link
Chest: https://classic.wowhead.com/object=92423/damaged-chest
Objective: https://classic.wowhead.com/item=6997/tattered-manuscript
Quest: https://classic.wowhead.com/quest=1803/tome-of-the-cabal

## Screenshots
_**Chest that contains Tattered Manuscript**_
![image](https://user-images.githubusercontent.com/4010591/118391264-cfab4100-b609-11eb-85a3-26cead02ba49.png)

## Questie version
v6.2..6

**Comment by Muehe** [comment]
Objective is shown now on WotLK, and looking at the raw data should be shown on Classic/TBC as well.
