### ISSUE TITLE
Quest ID 1243 doesn't show turn in location

### ISSUE THREAD

**Issue by Lavick81** [Questie/Questie#2753]
## Description
Questie showed me where to pick up the quest but not where to turn it in.

## Wowhead link
https://classic.wowhead.com/quest=1243/the-missing-diplomat

## Screenshots
![Screenshot 2021-05-16 173747](https://user-images.githubusercontent.com/3069018/118415009-783ebc80-b66d-11eb-89be-9d03ce29258a.png)

## Questie version
V6.2.6

**Comment by Lavick81** [comment]
Update on this. It does show the location but only after I clicked the Hide Questie button and then clicked the Show Questie button again.

![Screenshot 2021-05-16 174146](https://user-images.githubusercontent.com/3069018/118415102-0450e400-b66e-11eb-8ae7-f4c42fe86a39.png)

**Comment by BreakBB** [comment]
This was caused by a "desync" which is very hard for us to investigate. We are working on improving the logic around this issue.
