### ISSUE TITLE
"Speak with Bink" mage quest incorrectly shown as being incomplete and available

### ISSUE THREAD

**Issue by MisterTibbs** [Questie/Questie#2755]
## Description
According to Questie I have completed every mage quest in the game but this one, but when I visit the npc the quest is not available to me.
My guess is that when you complete a part or the whole [Speak with Jennea](https://classic.wowhead.com/quest=1860/speak-with-jennea) quest chain this quest becomes no longer possible to complete.

## Wowhead link
[Speak with Bink](https://classic.wowhead.com/quest=1879/speak-with-bink)

## Screenshots
<img width="538" alt="mage" src="https://user-images.githubusercontent.com/24671315/118730410-d919f080-b837-11eb-8032-63bf488154cc.png">

## Questie version
v6.2.6

**Comment by BreakBB** [comment]
Fixed with d646721d0de5e1bafd2ad5eff5c0c8fadd0f8473
