### ISSUE TITLE
Quest item pickups not detected for "Claim Rackmore's Treasure!"

### ISSUE THREAD

**Issue by kilgorep** [Questie/Questie#2757]
## Description

While working on the quest "Claim Rackmore's Treasure!", Questie is not detecting progress on the quest when picking up the two objective items. The items do get stored on the keyring instead of in a bag, so that might be a likely suspect.

## Wowhead link

https://tbc.wowhead.com/quest=6161/claim-rackmores-treasure

## Questie version

6.3.10

**Comment by BreakBB** [comment]
This should no longer be an issue for quite some time 🙈
