### ISSUE TITLE
Automatic Quest Accepting

### ISSUE THREAD

**Issue by swinnbv** [Questie/Questie#2758]
I was accepting quests in Eversong Woods, and the quests were automatically accepting themselves before I clicked the button. I had no settings for autoaccepting quests turned on, and nothing I did worked. After a few quests, the bug stopped. I was using Questie v6.3.10.

**Comment by BreakBB** [comment]
You should update to v6.3.11. If this happens again make sure to only enable Questie and if the error still persists open up a new issue please :)
