### ISSUE TITLE
Eversong Woods quest still appearing as available after completion

### ISSUE THREAD

**Issue by hendronderson** [Questie/Questie#2762]
## Bug description
Quest "Corrupted Soil" still appears on the mini map and world map as available even after handing it in. Complete quest to recreate.

## Questie version
6.3.10

**Comment by hendronderson** [comment]
Also the Whitebark's Memory quest. The same bug.

**Comment by BreakBB** [comment]
Hey @hendronderson try a `/reload` and see if the quests still show up.

**Comment by hendronderson** [comment]
Yea i didnt even think to reload with the first two, but it happened again with "A Study of Power" and i reloaded and it fixed it
