### ISSUE TITLE
Many quests listed with wrong race

### ISSUE THREAD

**Issue by Nerillida** [Questie/Questie#2763]
Version 6.3.10 and 6.3.11

I was flicking through the quest lists in the Journey/Advanced search

There are a large number of quests with race: Oct, Undead, Turen, Troll, Dranei eg 3123
and
a large number with
race: Human, Dwarf,Nightelf, Gnome, Elfo de Sangre. eg 6261

ALSO

6181, 6281, 6261, 6285  should be Human only

**Comment by drejjmit** [comment]
Fixed in v6.3.13
