### ISSUE TITLE
Paladin Questline

### ISSUE THREAD

**Issue by jimmyfromthefuture** [Questie/Questie#2766]
Paladin Questline - A Study in Power
https://tbc.wowhead.com/quest=9681/a-study-in-power#comments

questie stopped tracking all the paladin quests in this chain starting with this.
I received an error that the quest ID was not found.
From there on the quest appeared as acceptable on my map even after I had completed the questline.

**Comment by Nerillida** [comment]
It has the wrong race attached to it in my version 6.3.11

**Comment by BreakBB** [comment]
Blizzard added a duplicate version of "A Study in Power", which we don't have in our database yet. Will be fixed shortly.
