### ISSUE TITLE
Questie is not appearing in Add-on list.

### ISSUE THREAD

**Issue by Jovanya3** [Questie/Questie#2769]
Hello! 

Downloaded the latest version of Questie from Curseforge. But, Addon does not appear in my Addon list. 

I play on MacBook Pro 2018

What to do?

**Comment by drejjmit** [comment]
Try this install guide and report back: 
https://github.com/Questie/Questie/wiki/Installation-Guide

**Comment by Jovanya3** [comment]
@drejjmit found the actual problem! If it helps so somebody.
Because I downloaded Questie many times, Mac system gives the next periodic number to each new Questie folder, e.g. Questie, Questie-2, Questie-3, and in my case Questie-11. So I just deleted "-11" and left the name Questie and it works! 

<img width="226" alt="Снимок экрана 2021-05-20 в 10 17 16" src="https://user-images.githubusercontent.com/84496106/118936072-de209200-b954-11eb-8d97-b56a041fe312.png">

**Comment by drejjmit** [comment]
Glad you figured it out 👍
