### ISSUE TITLE
missing objective data for quest error

### ISSUE THREAD

**Issue by Djfe** [Questie/Questie#2770]
## Description

Error:
Missing objective data for quest 5517 2

## Wowhead link

I guess it's this one due to the id
https://tbc.wowhead.com/quest=5517/chromatic-mantle-of-the-dawn

## Screenshots

![questie 6 3 11 bug beta4](https://user-images.githubusercontent.com/5685512/118940853-70269b80-b951-11eb-9e34-22c843e7e550.png)

## Questie version

6.3.11 beta4 (according to the addons menu)
according to curseforge I'm using the latest version, while in-game tells me there is a newer one

**Comment by drejjmit** [comment]
Thanks for the report. Fixed in v6.3.13
