### ISSUE TITLE
bug when reloading update from Burning crusaded

### ISSUE THREAD

**Issue by Dedalios** [Questie/Questie#2773]
Message: Interface\AddOns\Questie\Modules\QuestieMenu.lua:588: attempt to index field 'factionSpecificTownsfolk' (a nil value)
Time: Thu May 20 11:32:31 2021
Count: 1
Stack: Interface\AddOns\Questie\Modules\QuestieMenu.lua:588: attempt to index field 'factionSpecificTownsfolk' (a nil value)
[string "=(tail call)"]: ?
[string "@Interface\AddOns\Questie\Modules\QuestieMenu.lua"]:588: in function `BuildCharacterTownsfolk'
[string "@Interface\AddOns\Questie\Modules\QuestieEventHandler.lua"]:211: in function <...rface\AddOns\Questie\Modules\QuestieEventHandler.lua:148>
[string "=[C]"]: ?
[string "@Interface\AddOns\Bartender4\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29: in function <...er4\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Interface\AddOns\Bartender4\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface\AddOns\Bartender4\libs\AceEvent-3.0\AceEvent-3.0.lua"]:120: in function <...AddOns\Bartender4\libs\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: <none>

After reload it s ok

**Comment by BreakBB** [comment]
This has already been fixed.
