### ISSUE TITLE
Some flightmasters appear on mini map but are unvailable

### ISSUE THREAD

**Issue by Dichotomia** [Questie/Questie#2779]
## Bug description
Some flightmasters appear on mini map but are unvailable:
Kiz Coilspanner in Ghostlands
Ohura in Isle of Quel'Danas

## Screenshots
![image](https://user-images.githubusercontent.com/5593198/118982408-b264d280-b97b-11eb-8700-75a2a8236900.png)

![image](https://user-images.githubusercontent.com/5593198/118982639-e93ae880-b97b-11eb-992e-c0fcb31934f1.png)

## Questie version
6.3.11

**Comment by BreakBB** [comment]
This is no longer an issue
