### ISSUE TITLE
Blood elf only quests appearing available for non-belfs

### ISSUE THREAD

**Issue by Cerby3BR** [Questie/Questie#2780]
https://tbc.wowhead.com/quest=9189/delivery-to-the-sepulcher
https://tbc.wowhead.com/quest=9425/report-to-tarren-mill
These two quests are Blood elf exclusive bread crumb quests, but Questie shows them as available on my map as a tauren.

Version 6.3.11

**Comment by drejjmit** [comment]
Thanks for the report. Fixed in v6.3.13
