### ISSUE TITLE
issue with questie tracker

### ISSUE THREAD

**Issue by totalletdown** [Questie/Questie#2783]
## Question

For WOW BCC my Questie tracker wont appear. I've uninstalled and reinstalled it, manually installed it, and uninstalled and reinstalled BCC and none of that fixed it so I'd like to know if something can be done about this.

**Comment by BreakBB** [comment]
Sorry for the late response on this @totalletdown 

I hope it is now working again for you. You should make sure you have a quest tracked (Shift + left click a quest in your quest log) and also try to use the "Reset location" button in the Tracker option.

Feel free to open a new issue if this is still an issue.
