### ISSUE TITLE
Seems to work properly but I keep getting this error in Swatter.

### ISSUE THREAD

**Issue by liquid573** [Questie/Questie#2787]
It seems as if there's some new conflict with BigDebuffs and AtlasLootClassic. All was working well prior to the pre-patch update. As stated in the title, I do not notice any problems with the functionality of the addon. I simply get this error every time the UI loads.

Date: 2021-05-20 16:23:34
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Questie\Questie.lua line 248:
   attempt to concatenate local 'str' (a nil value)
Debug:
   [string "@Questie\Questie.lua"]:248: Colorize()
   [string "@Questie\Modules\QuestieMenu.lua"]:94:
      Questie\Modules\QuestieMenu.lua:87
   [string "@..\SharedXML\C_TimerAugment.lua"]:16:
      ..\SharedXML\C_TimerAugment.lua:14
Locals:
self = <table> {
 SetDefaultModuleLibraries = <function> defined @Interface\AddOns\BigDebuffs\Libs\AceAddon-3.0\AceAddon-3.0.lua:367
 Colorize = <function> defined @Interface\AddOns\Questie\Questie.lua:221
 Enable = <function> defined @Interface\AddOns\BigDebuffs\Libs\AceAddon-3.0\AceAddon-3.0.lua:294
 RegisterChatCommand = <function> defined @Interface\AddOns\Questie\Libs\AceConsole-3.0\AceConsole-3.0.lua:85
 GetClassColor = <function> defined @Interface\AddOns\Questie\Questie.lua:251
 EnableModule = <function> defined @Interface\AddOns\BigDebuffs\Libs\AceAddon-3.0\AceAddon-3.0.lua:332
 modules = <table> {
 }
 GetModule = <function> defined @Interface\AddOns\BigDebuffs\Libs\AceAddon-3.0\AceAddon-3.0.lua:210
 IterateEmbeds = <function> defined @Interface\AddOns\BigDebuffs\Libs\AceAddon-3.0\AceAddon-3.0.lua:442
 started = true
 UnregisterComm = <function> defined @Interface\AddOns\AtlasLootClassic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 defaultModuleLibraries = <table> {
 }
 TimeLeft = <function> defined @Interface\AddOns\Questie\Libs\AceTimer-3.0\AceTimer-3.0.lua:172
 Deserialize = <function> defined @Interface\AddOns\NovaWorldBuffs\Lib\AceSerializer-3.0\AceSerializer-3.0.lua:246
 UnregisterChatCommand = <function> defined @Interface\AddOns\Questie\Libs\AceConsole-3.0\AceConsole-3.0.lua:111
 minimapConfigIcon = <table> {
 }
 ScheduleRepeatingTimer = <function> defined @Interface\AddOns\Questie\Libs\AceTimer-3.0\AceTimer-3.0.lua:129
 CancelAllTimers = <function> defined @Interface\AddOns\Questie\Libs\AceTimer-3.0\AceTimer-3.0.lua:160
 Printf = <function> defined @Interface\AddOns\Questie\Libs\AceConsole-3.0\AceConsole-3.0.lua:69
 RegisterBucketEvent = <function> defined @Interface\AddOns\Questie\Libs\AceBucket-3.0\AceBucket-3.0.lua:184
 SetDefaultModulePrototype = <function> defined @Interface\AddOns\BigDebuffs\Libs\AceAddon-3.0\AceAddon-3.0.lua:409
 TBC_BETA_BUILD_VERSION_SHORTHAND = ""
 baseName = "Questie"
 Debug = <function> defined @Interface\AddOns\Questie\Questie.lua:281
 name = "Questie"
 Error = <function> defined @Interface\AddOns\Questie\Questie.lua:277
 IsEnabled = <function> defined @Interface\AddOns\BigDebuffs\Libs\AceAddon-3.0\AceAddon-3.0.lua:451
 orderedModules = <table> {
 }
 ScheduleTimer = <function> defined @Interface\AddOns\Questie\Libs\AceTimer-3.0\AceTimer-3.0.lua:94
 DisableModule = <function> defined @Interface\AddOns\BigDebuffs\Libs\AceAddon-3.0\AceAddon-3.0.lua:350
 HandleSlash = <function> defined @Interface\AddOns\Questie\Questie.lua:217
 OnDisable = <function> defined @Interface\AddOns\Questie\Questie.lua:213
 OnEnable = <function> defined @Interface\AddOns\Questie\Questie.lua:209
 OnUpdate = <function> defined @Interface\AddOns\Questie\Questie.lua:205
 RegisterMessage = <function> defined @Interface\AddOns\AtlasLootClassic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 GetArgs = <function> defined @Interface\AddOns\Questie\Libs\AceConsole-3.0\AceConsole-3.0.lua:144
 Print = <function> defined @Interface\AddOns\Questie\Libs\AceConsole-3.0\AceConsole-3.0.lua:54
 OnInitialize = <function> defined @Interface\AddOns\Questie\Questie.lua:134
 UnregisterAllBuckets = <function> defined @Interface\AddOns\Questie\Libs\AceBucket-3.0\AceBucket-3.0.lua:229
 UnregisterBucket = <function> defined @Interface\AddOns\Questie\Libs\AceBucket-3.0\AceBucket-3.0.lua:206
 RegisterBucketMessage = <function> defined @Interface\AddOns\Questie\Libs\AceBucket-3.0\AceBucket-3.0.lua:200
 IsModule = <function> defined @Interface\AddOns\BigDebuffs\Libs\AceAddon-3.0\AceAddon-3.0.lua:468
 db = <table> {
 }
 SetDefaultModuleState = <function> defined @Interface\AddOns\BigDebuffs\Libs\AceAddon-3.0\AceAddon-3.0.lua:387
 SendCommMessage = <function> defined @Interface\AddOns\NovaWorldBuffs\Lib\AceComm-3.0\AceComm-3.0.lua:87
 UnregisterAllComm = <function> defined @Interface\AddOns\AtlasLootClassic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 SetEnabledState = <function> defined @Interface\AddOns\BigDebuffs\Libs\AceAddon-3.0\AceAddon-3.0.lua:424
 Serialize = <function> defined @Interface\AddOns\NovaWo
AddOns:
  MoncaiCompare, v7.2.0
  Swatter, v1.13.6652 (SwimmingSeadragon)
  AtlasLootClassic, vv2.1.0
  AtlasLootClassicData, vv2.1.0
  AtlasLootClassicDungeonsAndRaids, vv2.1.0
  AtlasLootClassicMaps, vv1.0.0
  Bagnon, v9.0.6
  BigDebuffs, vv10.0
  ClassicInterrupt, v
  DisenchantCraftedItems, v2.0.1
  GuildRosterManager, v1.928
  Informant, v1.13.6650 (SwimmingSeadragon)
  LootMagic, v1.0
  MooidesMountMod, v1.0
  NovaWorldBuffs, v2.02
  OmniBar, vv11.5
  OmniCC, v9.0.10
  Postal, vr436
  Questie, v6.3.11
  SigmaProfessionFilter, v
  SigmaProfessionFilterEnchanting, v
  Stubby, v1.13.6614 (SwimmingSeadragon)
  ToLevel, v0.1
  WeakAuras, v3.4.1
  WeakAurasCompanion, v1.1.0
  ZygorGuidesViewerClassicTBC, v7.0
  BlizRuntimeLib_enUS v2.5.1.20501 <none>
  (ck=2f1)

**Comment by BreakBB** [comment]
We reworked the init process of Questie a few updates back which should have fixed issues like this.

If you still experience this, feel free to open up a new issue.
