### ISSUE TITLE
[DND] TAR Pedestal Shown on Map When Repair is Checked

### ISSUE THREAD

**Issue by KingKoopa94** [Questie/Questie#2788]
When turning on the option to show Repair on the Map/Minimap tons of extra things show up, all starting with [DND] TAR Pedestal

![Questie-Bug](https://user-images.githubusercontent.com/14955477/119050316-b0a50a00-b98f-11eb-9728-1f066661b456.png)

Running current version (6.3.11) on BC Classic.

**Comment by KingKoopa94** [comment]
https://user-images.githubusercontent.com/14955477/119051279-fc0be800-b990-11eb-90d6-3ce9a0f81dbb.mp4

**Comment by drejjmit** [comment]
If you see this you have 6.3.10 installed and not 6.3.11, or you haven't restarted WoW after update.

**Comment by KingKoopa94** [comment]
v6.3.11 (Beta 4) -- Thanks for being so quick, I'll try the DB thing and report back

**Comment by drejjmit** [comment]
DB gets saved when you exit game/reload. Disconnect or crash does not save DB. Could be that it loaded the old 6.3.10 DB, even if you used 6.3.11 DB for a while.

**Comment by KingKoopa94** [comment]
Noted. You might be right on that theory, can't remember if I actually closed or just Alt+F4'd out
