### ISSUE TITLE
townsfolk error

### ISSUE THREAD

**Issue by amey1956** [Questie/Questie#2790]
## Bug description

boosted character, started appearing when i left ironforge - first time it showed up was in southshore, cleared bugsack errors and it appeared again

`5x Questie\Modules\QuestieMenu.lua:64: attempt to index field 'townsfolk' (a nil value)
[string "@Questie\Modules\QuestieMenu.lua"]:64: in function <Questie\Modules\QuestieMenu.lua:63>
[string "@Questie\Modules\QuestieMenu.lua"]:155: in function `OnLogin'
[string "@Questie\Modules\QuestieEventHandler.lua"]:194: in function <...rfaceQuestie\Modules\QuestieEventHandler.lua:161>

Locals:
key = "Mailbox"
forceRemove = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'townsfolk' (a nil value)"
_townsfolk_texturemap = <table> {
 197 = "Icons\trade_tailoring"
 Class Trainer = "Minimap\tracking\class"
 Trade Goods = 132912
 Pet Food = 132165
 Flight Master = "Minimap\tracking\flightmaster"
 Profession Trainer = "Minimap\tracking\profession"
 Bags = 133634
 393 = "Icons\inv_misc_pelt_wolf_01"
 356 = "Icons\trade_fishing"
 333 = "Icons\trade_engraving"
 129 = "Icons\spell_holy_sealofsacrifice"
 Weapon Master = "Questie\Icons\slay.blp"
 202 = "Icons\trade_engineering"
 Stable Master = "Minimap\tracking\stablemaster"
 Food = 133964
 186 = "Icons\trade_mining"
 Drink = 134712
 Portal Trainer = "Minimap\vehicle-alliancemageportal"
 182 = "Icons\trade_herbalism"
 Spirit Healer = "raidframe\raid-icon-rez"
 171 = "Icons\trade_alchemy"
 165 = "Icons\trade_leatherworking"
 164 = "Icons\trade_blacksmithing"
 Ammo = 132382
 185 = "Icons\inv_misc_food_15"
 755 = "Icons\inv_misc_gem_01"
 Reagents = "Minimap\tracking\poisons"
}
QuestieMap = <table> {
 zoneWaypointColorOverrides = <table> {
 }
 DrawLineIcon = <function> defined @Questie\Modules\Map\QuestieMap.lua:379
 drawTimer = <table> {
 }
 DrawWorldIcon = <function> defined @Questie\Modules\Map\QuestieMap.lua:489
 UnloadQuestFrames = <function> defined @Questie\Modules\Map\QuestieMap.lua:74
 UnloadManualFrames = <function> defined @Questie\Modules\Map\QuestieMap.lua:109
 manualFrames = <table> {
 }
 ShowObject = <function> defined @Questie\Modules\Map\QuestieMap.lua:331
 questIdFrames = <table> {
 }
 DrawWaypoints = <function> defined @Questie\Modules\Map\QuestieMap.lua:886
 FindClosestStarter = <function> defined @Questie\Modules\Map\QuestieMap.lua:648
 ICON_MAP_TYPE = "MAP"
 GetFramesForQuest = <function> defined @Questie\Modules\Map\QuestieMap.lua:61
 RescaleIcons = <function> defined @Questie\Modules\Map\QuestieMap.lua:127
 InitializeQueue = <function> defined @Questie\Modules\Map\QuestieMap.lua:149
 _mapDrawQueue = <table> {
 }
 GetNearestQuestSpawn = <function> defined @Questie\Modules\Map\QuestieMap.lua:802
 processCounter = 0
 ProcessQueue = <function> defined @Questie\Modules\Map\QuestieMap.lua:239
 DrawManualIcon = <function> defined @Questie\Modules\Map\QuestieMap.lua:398
 _minimapDrawQueue = <table> {
 }
 ICON_MINIMAP_TYPE = "MINIMAP"
 ProcessShownMinimapIcons = <function> defined @Questie\Modules\Map\QuestieMap.lua:204
 fadeLogicTimerShown = <table> {
 }
 ShowNPC = <function> defined @Questie\Modules\Map\QuestieMap.lua:272
 GetManualFrames = <function> defined @Questie\Modules\Map\QuestieMap.lua:96
 utils = <table> {
 }
 GetNearestSpawn = <function> defined @Questie\Modules\Map\QuestieMap.lua:768
 zoneWaypointHoverColorOverrides = <table> {
 }
 private = <table> {
 }
 ResetManualFrames = <function> defined @Questie\Modules\Map\QuestieMap.lua:119
 QueueDraw = <function> defined @Questie\Modules\Map\QuestieMap.lua:228
 GetScaleValue = <function> defined @Questie\Modules\Map\QuestieMap.lua:175
}
l10n = <table> {
 GetUILocale = <function> defined @Questie\Localization\l10n.lua:155
 objectNameLookup = <table> {
 }
 SetUILocale = <function> defined @Questie\Localization\l10n.lua:147
 Initiali`

## Questie version
Version: 6.3.11 per toc

**Comment by bmsbwd** [comment]
Not only boosted Chars.
New Bloodelf with only Questie activated:

Message: Interface\AddOns\Questie\Modules\QuestieMenu.lua:588: attempt to index field 'factionSpecificTownsfolk' (a nil value)
Time: Fri May 21 14:49:32 2021
Count: 1
Stack: Interface\AddOns\Questie\Modules\QuestieMenu.lua:588: attempt to index field 'factionSpecificTownsfolk' (a nil value)
[string "@Interface\AddOns\Questie\Modules\QuestieMenu.lua"]:588: in function `BuildCharacterTownsfolk'
[string "@Interface\AddOns\Questie\Modules\QuestieEventHandler.lua"]:211: in function <...rface\AddOns\Questie\Modules\QuestieEventHandler.lua:148>
[string "=[C]"]: ?
[string "@Interface\AddOns\Questie\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29: in function <...tie\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Interface\AddOns\Questie\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface\AddOns\Questie\Libs\AceEvent-3.0\AceEvent-3.0.lua"]:120: in function <...ce\AddOns\Questie\Libs\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: <none>

**Comment by legacy3** [comment]
Can confirm this.

**Comment by AeroScripts** [comment]
This should be fixed in the next release, in the meantime you can solve it by resetting questie

/questie
^ slash command

Then in the advanced tab -> "Reset Questie" button. Sorry about that

**Comment by drejjmit** [comment]
New version v6.3.13 is out. Thanks for the reports.
