### ISSUE TITLE
Map vendor icons

### ISSUE THREAD

**Issue by Quijib0** [Questie/Questie#2791]
## Bug description

Food and drink vendor icons not showing on map in Darnassus or Ironforge.  It is this way for two characters.  

Also, on two characters and not a third,  there is a string of repair icons on the map.  One character has this happening in Ironforge in the Commons area.  I've attached a screenshot of it happening in Darnassus on the other character. 

## Screenshots
![WowClassic_2021_05_20_17_24_40_252](https://user-images.githubusercontent.com/72253734/119056488-640dfe80-b990-11eb-8050-038ac39d2fdc.jpg)

## Questie version

6.3.11

**Comment by drejjmit** [comment]
Go to ``Questie Options`` -> ``Advanced`` -> ``Recompile Database`` and see if that fixes the problem.

**Comment by Quijib0** [comment]
Okay.  That fixed the repair icons issue.  All vendor icons, except general goods, are still not showing.  Didn't realize it was all icons except general goods.

**Comment by drejjmit** [comment]
Will be fixed for next release
