### ISSUE TITLE
Wrong prequest for quest Chieftain Oomooroo #9573

### ISSUE THREAD

**Issue by max-ri** [Questie/Questie#2793]
For 
https://tbc.wowhead.com/quest=9573/chieftain-oomooroo
the quest
https://tbc.wowhead.com/quest=9562/murlocs-why-here-why-now
is reported as a prequest.
The correct prequest is
https://tbc.wowhead.com/quest=9560/beasts-of-the-apocalypse

Observed in Questie version v6.3.10 (Beta3)

**Comment by BreakBB** [comment]
Hey @max-ri Did you test this yourself? Because in the beta I was able to complete "Chieftain Oomooroo" without "Beasts of the Apocalype"

**Comment by max-ri** [comment]
Just tested on live.
Turning in "Beasts of the Apocalypse" made "Chieftain Oomooroo" appear.

It might be either one of the two.

![grafik](https://user-images.githubusercontent.com/51713394/119185676-51222980-ba77-11eb-87ab-57b6e0d658a5.png)

![grafik](https://user-images.githubusercontent.com/51713394/119185705-5ed7af00-ba77-11eb-9708-a35b7d3f3762.png)
