### ISSUE TITLE
Blood Elf -only quest shown for all races

### ISSUE THREAD

**Issue by economou** [Questie/Questie#2795]
This quest seems to be restricted to Blood Elves: https://tbc.wowhead.com/quest=9425/report-to-tarren-mill

There are comments from 2008 on Wowhead indicating this, and it's not available to my level 60 non-BE character.  But, the quest is shown by Questie (with low-level quests enabled).

**Comment by hjelp200121** [comment]
Didnt wanna add a new issue, so commenting here, but i think it is a general problem for many race specific quests, eg. both "The deathstalkers" and "Fenwick Thatros" (both undead rogue only quests) shows up for me as an orc rogue.

**Comment by drejjmit** [comment]
Thanks for the reports. All three are fixed in v6.3.13
