### ISSUE TITLE
Lua error upon logging in

### ISSUE THREAD

**Issue by papaprone** [Questie/Questie#2796]
## Bug description

Upon logging in I'm met with this Lua error

Message: Interface\AddOns\Questie\Modules\QuestieMenu.lua:523: bad argument #1 to 'unpack' (table expected, got nil)
Time: Thu May 20 22:14:51 2021
Count: 1
Stack: Interface\AddOns\Questie\Modules\QuestieMenu.lua:523: bad argument #1 to 'unpack' (table expected, got nil)
[string "=[C]"]: ?
[string "=[C]"]: in function `unpack'
[string "@Interface\AddOns\Questie\Modules\QuestieMenu.lua"]:523: in function `UpdateAmmoVendors'
[string "@Interface\AddOns\Questie\Modules\QuestieMenu.lua"]:550: in function `UpdatePlayerVendors'
[string "@Interface\AddOns\Questie\Modules\QuestieMenu.lua"]:503: in function `PopulateTownsfolkPostBoot'
[string "@Interface\AddOns\Questie\Modules\QuestieEventHandler.lua"]:168: in function <...rface\AddOns\Questie\Modules\QuestieEventHandler.lua:156>

Locals: 

## Questie version
6.3.10

**Comment by BreakBB** [comment]
Hey @papaprone you should update to v6.3.11 which fixes this issue 👍🏻
