### ISSUE TITLE
"[DND] Tar Pedestal" at lots of places

### ISSUE THREAD

**Issue by Doxxy0** [Questie/Questie#2798]
## Bug description
Lots of blacksmith icons on the map, named "dnd tar pedestal", only reinstall fix this for me, but they reappear after a while.
I don't have any profession trainers selected with a tick in questie, or in the default tracker

## Screenshots
[WoWScrnShot_052121_103040](https://user-images.githubusercontent.com/84509345/119108259-4ee0b080-ba20-11eb-821d-c212c2aea89d.jpg)

## Questie version
v6.3.11

**Comment by Quijib0** [comment]
Had same issue.  Go to advanced tab in options and click recompile button at bottom.

**Comment by BreakBB** [comment]
As @Quijib0 already suggested:

Do the following to fix this (no idea why the update to v6.3.11 didn't fix it by itself): `/questie` -> Advanced -> Recompile Database @Doxxy0
