### ISSUE TITLE
Game stutters everytime it updates a quest

### ISSUE THREAD

**Issue by Valiath** [Questie/Questie#2801]
## Bug description

My game stutters everytime I loot a quest item, kill a quest objective etc. Issue disappears if I disable questie.

## Questie version
6.3.11

**Comment by Lumanos** [comment]
Might be related, getting a really big game stutter every time opening the map on version 6.3.11

**Comment by BreakBB** [comment]
Please update to v6.3.12 and report if that helps 👍🏻

**Comment by Valiath** [comment]
It didn't fix the issue. I should say this issue is not new in TBC client, I had it before prepatch aswell. I don't remember having it when I used questie back when classic originally launched though.

**Comment by BreakBB** [comment]
Hey @Lumanos the lag issue on world map opening is a bug on Blizzards side which they are already aware of.

@Valiath could you run the Profiler (Advanced -> Open Profiler), move it a bit off screen and try to provoke the lag you are experiencing? If you did then share a screenshot of what the Profiler recorded.

**Comment by Valiath** [comment]
@BreakBB 
![WoWScrnShot_052721_201606](https://user-images.githubusercontent.com/84580876/119869184-9b4c5480-bf28-11eb-9ac9-6821ebe50813.jpg)
I took this screenshot right after looting the quest item from the mob.

**Comment by tronusqw** [comment]
I have same issue, it started 2-3 days ago after i update addon. 
![WowClassic_iLiibzIfmH](https://user-images.githubusercontent.com/55791833/121914103-2b2d3380-cd5c-11eb-8272-b63e9dccdc02.png)

**Comment by BreakBB** [comment]
Hey @Valiath and @tronusqw 

Sorry for not coming back to this earlier. We are still very limited in time and this issue got lost in the flood of TBC issues 🙈 

Are you still having trouble with Questie lagging your game? Especially when looting quest icons?

**Comment by Valiath** [comment]
@BreakBB Hi, no problem dude.

Issue still persists and Questie still lags whenever I do quest tracker related stuff.

Only time it doesn't lag is when I create a fresh character. It doesn't lag for some levels and when I start reaching 10 or so levels and quests pile up, it starts lagging again.

**Comment by BreakBB** [comment]
@Valiath Sorry to hear that.

It would be nice, if you could once again run the Profiler for some time and post the results here. You should also really check if this is an issue with just Questie and no other addons enabled.

**Comment by Laumesis** [comment]
@Valiath
Does it lag while you play with Questie's Tracker disabled?
Please disable it this way to test. This is not a solution for the issue, but to help diagnose it. :
`/questie` -> Tracker -tab -> Disable The Tracker -button
And restart game after that to be absolutely sure game's lua-engine gets clean.

**Comment by balsh** [comment]
happens to me on SOM

**Comment by BreakBB** [comment]
Hey @balsh did you go through the comments above and tried to disable all other addons or disable the Tracker?

If none of it helped we need you to run the Profiler and report the outcome to us.

**Comment by Feper24** [comment]
> 

This is currently happening to me right now, through much trouble I figured it was Questie and not just randomly, I thought it was BGs or something but realized the stutter began after handing in the PVP Daily quest.

**Comment by BreakBB** [comment]
Hey @Feper24 can you run the Profiler and did you also try to disable all other addons and try with just Questie?

**Comment by Feper24** [comment]
> Hey @Feper24 can you run the Profiler and did you also try to disable all other addons and try with just Questie?

Hi, yes, I think these all the culprits:

![image](https://user-images.githubusercontent.com/60163442/151674587-bf36e62a-84ab-4642-ad16-8fd81b103c09.png)

**Comment by BreakBB** [comment]
That helps a lot @Feper24 thanks! 👍🏻

**Comment by Feper24** [comment]
> That helps a lot @Feper24 thanks! 👍🏻

One thing though, this is not instant. Kinda accumulates through BGs. If you do the biggest one, AV, its faster (in 2 quest turn ins or games im already stuttering). With smaller ones it takes longer.

**Comment by balsh** [comment]
@BreakBB disabling the tracker kinda fixes the issue for me

**Comment by BreakBB** [comment]
Hey @balsh can you share a screenshot of your Tracker settings? We already know the Tracker has serious performance problems, but we are very limited in time to tackle this issue atm 🙈

**Comment by Feper24** [comment]
> @BreakBB disabling the tracker kinda fixes the issue for me

Gonna try to do this too, I also found out part of the "stutter" blame was form TSM addon but still gonna keep testing!

**Comment by BreakBB** [comment]
I am closing this and assume it is no longer an issue. Feel free to open up a new issue if it remains.
