### ISSUE TITLE
Minimum level for quest "They're Alive Maybe..." #9749 is reported as 19, quest can be accepted at 18

### ISSUE THREAD

**Issue by max-ri** [Questie/Questie#2802]
![grafik](https://user-images.githubusercontent.com/51713394/119156908-f677d600-ba54-11eb-8c57-0d0acc7623a2.png)

Questie version is v6.3.11 (Beta 4)

(Also quest name has "BETA" in it.)

**Comment by BreakBB** [comment]
Hey @max-ri can you explain where you saw the "minimum required level" and also the "BETA"?

In our database the quest already has level 16 as required level, but it is a level 19 quest. Also we blacklisted the BETA variant of that quest (there is quest ID 9749 == BETA and 9670 == The correct one).

You should make sure to go into the Advanced settings of Questie and enable "Show Quest IDs" option to always make sure you report the correct IDs 👍🏻

**Comment by max-ri** [comment]
Ok I see!
The quest was referenced in a guide for the leveling addon Guidelime. So this in fact is an error of that guide which uses the wrong quest id and not of Questie. Thank you for your answer and sorry for bothering you! For the future we know that when quest names start with BETA it probably is an incorrect id.
Cheers!
