### ISSUE TITLE
3093 Rune-Inscribed Note shown as available but can't accept

### ISSUE THREAD

**Issue by TobiasDrees** [Questie/Questie#2803]
## Description
"Rune-Inscribed Note" quest is displayed on the map as available, but i'm unable to accept it from him.

### Further info
Running `/run print(C_QuestLog.IsQuestFlaggedCompleted(3093))` yields `false`
Running `/run print(C_QuestLog.IsQuestFlaggedCompleted(747))` (required pre-quest according to wowhead) yields `true`

## Wowhead link
https://tbc.wowhead.com/quest=3093/rune-inscribed-note
https://tbc.wowhead.com/quest=747/the-hunt-begins

## Screenshots
![Untitled](https://user-images.githubusercontent.com/20279592/119187802-1c63a180-ba7a-11eb-9210-253a074ea3ff.png)

## Questie version
v6.3.11

**Comment by Nerillida** [comment]
It should be Tauren only.

**Comment by TobiasDrees** [comment]
I guess the tauren only filter is missing, since i am an orc shaman.

**Comment by drejjmit** [comment]
Thanks for the report. Fixed in v6.3.13
