### ISSUE TITLE
Lua error [Classic ERA]

### ISSUE THREAD

**Issue by waytoomuchgaming** [Questie/Questie#2807]
## Bug description
While overring titan panel questie button.

## Questie version
Which version of Questie are you using? You can find it by:
6.3.11

2x ...Questie\Libs\LibUIDropDownMenu\LibUIDropDownMenu.lua:1457: attempt to index field '?' (a nil value)
...Questie\Libs\LibUIDropDownMenu\LibUIDropDownMenu.lua:1457: in function `ToggleDropDownMenu'
...Questie\Libs\LibUIDropDownMenu\LibUIDropDownMenu.lua:233: in function <...Questie\Libs\LibUIDropDownMenu\LibUIDropDownMenu.lua:228>
...Questie\Libs\LibUIDropDownMenu\LibUIDropDownMenu.lua:324: in function <...Questie\Libs\LibUIDropDownMenu\LibUIDropDownMenu.lua:323>

Locals:
self = <table> {
 UIDropDownMenu_SetButtonText = <function> defined @Questie\Libs\LibUIDropDownMenu\LibUIDropDownMenu.lua:1715
 UIDropDownMenu_HandleGlobalMouseEvent = <function> defined @Questie\Libs\LibUIDropDownMenu\LibUIDropDownMenu.lua:1584
 UIDropDownMenu_SetAnchor = <function> defined @Questie\Libs\LibUIDropDownMenu\LibUIDropDownMenu.lua:1674
 Create_UIDropDownMenu = <function> defined @Questie\Libs\LibUIDropDownMenu\LibUIDropDownMenu.lua:575
 UIDropDownMenu_SetButtonWidth = <function> defined @Questie\Libs\LibUIDropDownMenu\LibUIDropDownMenu.lua:1619
 UIDropDownMenu_DisableButton = <function> defined @Questie\Libs\LibUIDropDownMenu\LibUIDropDownMenu.lua:1707
 ColorPicker_GetPreviousValues = <function> defined @Questie\Libs\LibUIDropDownMenu\LibUIDropDownMenu.lua:1783
 ToggleDropDownMenu = <function> defined @Questie\Libs\LibUIDropDownMenu\LibUIDropDownMenu.lua:1329
 UIDropDownCustomMenuEntryMixin = <table> {
 }
 UIDropDownMenuButton_OpenColorPicker = <function> defined @Questie\Libs\LibUIDropDownMenu\LibUIDropDownMenu.lua:1698
 UIDropDownMenu_Refresh = <function> defined @Questie\Libs\LibUIDropDownMenu\LibUIDropDownMenu.lua:1158
 Create_UIDropDownCustomMenuEntry = <function> defined @Questie\Libs\LibUIDropDownMenu\LibUIDropDownMenu.lua:1877
 UIDropDownMenu_AddSeparator = <function> defined @Questie\Libs\LibUIDropDownMenu\LibUIDropDownMenu.lua:730
 UIDropDownMenu_Initialize = <function> defined @Questie\Libs\LibUIDropDownMenu\LibUIDropDownMenu.lua:589
 UIDropDownMenu_SetSelectedName = <function> defined @Questie\Libs\LibUIDropDownMenu\LibUIDropDownMenu.lua:1272
 EasyMenu = <function> defined @Questie\Libs\LibUIDropDownMenu\LibUIDropDownMenu.lua:1939
 UIDropDownMenu_GetValue = <function> defined @Questie\Libs\LibUIDropDownMenu\LibUIDropDownMenu.lua:1760
 LargeDropDownMenuButtonMixin = <table> {
 }
 UIDropDownMenu_GetText = <function> defined @Questie\Libs\LibUIDropDownMenu\LibUIDropDownMenu.lua:1634
 UIDropDownMenu_RefreshAll = <function> defined @Questie\Libs\LibUIDropDownMenu\LibUIDropDownMenu.lua:1241
 UIDropDownMenu_SetInitializeFunction = <function> defined @Questie\Libs\LibUIDropDownMenu\LibUIDropDownMenu.lua:613
 EasyMenu_Initialize = <function> defined @Questie\Libs\LibUIDropDownMenu\LibUIDropDownMenu.lua:1947
 OpenColorPicker = <function> defined @Questie\Libs\LibUIDropDownMenu\LibUIDropDownMenu.lua:1770
 UIDropDownMenu_RegisterCustomFrame = <function> defined @Questie\Libs\LibUIDropDownMenu\LibUIDropDownMenu.lua:1099
 UIDropDownMenu_GetSelectedID = <function> defined @Questie\Libs\LibUIDropDownMenu\LibUIDropDownMenu.lua:1298
 UIDropDownMenu_SetDisplayMode = <function> defined @Questie\Libs\LibUIDropDownMenu\LibUIDropDownMenu.lua:617
 UIDropDownMenu_EnableDropDown = <function> defined @Questie\Libs\LibUIDropDownMenu\LibUIDropDownMenu.lua:1744
 UIDropDownMenu_DisableDropDown = <function> defined @Questie\Libs\LibUIDropDownMenu\LibUIDropDownMenu.lua:1732
 UIDropDownMenu_SetButtonClickable = <function> defined @Questie\Libs\LibUIDropDownMenu\LibUIDropDownMenu.lua:1728
 UIDropDownMenu_SetButtonNotClickable = <function> defined @Questie\Libs\LibUIDropDownMenu\LibUIDropDownMenu.lua:1724
 UIDropDownMenu_SetSelectedID = <function> defined @Questie\Libs\LibUIDropDownMenu\LibUIDropDownMenu.lua:1287
 HideDropDownMenu = <function> defined @Questie\Libs\LibUIDropDownMenu\LibUIDropDownMenu.lua:1324
 UIDropDownMenuButton_GetChecked = <function> defined @Questie\Libs\LibUIDropDownMenu\LibUIDropDownMenu.lua:1690
 DropDownExpandArrowMixin = <table> {
 }
 UIDropDownMenu_GetSelectedValue = <function> defined

**Comment by BreakBB** [comment]
Please update to v6.3.12 and report if that helps @Altoholic

**Comment by Altoholic** [comment]
i still got errors about LibUIDropDownMenu, but now there's no mention of Questie in it.
it always happen when overring Titan drop down menus.

66x TBag\LibUIDropDownMenu\LibUIDropDownMenu.lua:1411: attempt to index field '?' (a nil value)
TBag\LibUIDropDownMenu\LibUIDropDownMenu.lua:1411: in function `L_ToggleDropDownMenu'
TBag\LibUIDropDownMenu\LibUIDropDownMenu.lua:553: in function `L_UIDropDownMenuButton_OnEnter'
TBag\LibUIDropDownMenu\LibUIDropDownMenu.lua:190: in function <TBag\LibUIDropDownMenu\LibUIDropDownMenu.lua:189>

Locals:
level = 3
value = "BugSack"
dropDownFrame = Titan_Bar__Display_BarRightClickMenu {
 0 = <userdata>
 point = "TOPLEFT"
 Right = Titan_Bar__Display_BarRightClickMenuRight {
 }
 Left = Titan_Bar__Display_BarRightClickMenuLeft {
 }
 displayMode = "MENU"
 relativePoint = "BOTTOMLEFT"
 initialize = <function> defined @TitanClassic\TitanPanelClassic.lua:2108
 Button = Titan_Bar__Display_BarRightClickMenuButton {
 }
 Icon = Titan_Bar__Display_BarRightClickMenuIcon {
 }
 Middle = Titan_Bar__Display_BarRightClickMenuMiddle {
 }
 Text = Titan_Bar__Display_BarRightClickMenuText {
 }
}
anchorName = nil
xOffset = nil
yOffset = nil
menuList = nil
button = L_DropDownList2Button2 {
 0 = <userdata>
 hasArrow = 1
 checked = 1
 invisibleButton = L_DropDownList2Button2InvisibleButton {
 }
 func = <function> defined @TitanClassic\TitanPanelClassic.lua:2090
 Highlight = L_DropDownList2Button2Highlight {
 }
 ExpandArrow = L_DropDownList2Button2ExpandArrow {
 }
 ColorSwatch = L_DropDownList2Button2ColorSwatch {
 }
 UnCheck = L_DropDownList2Button2UnCheck {
 }
 value = "BugSack"
 keepShownOnClick = 1
 Icon = L_DropDownList2Button2Icon {
 }
 Check = L_DropDownList2Button2Check {
 }
}
autoHideDelay = nil
listFrameName = "L_DropDownList3"
listFrame = L_DropDownList3 {
 0 = <userdata>
 parentLevel = 2
 Button1 = L_DropDownList3Button1 {
 }
 MenuBackdrop = L_DropDownList3MenuBackdrop {
 }
 Border = L_DropDownList3Border {
 }
 maxWidth = 131.897408
 dropdown = Titan_Bar__Display_BarRightClickMenu {
 }
 parentID = 1
 shouldRefresh = false
 numButtons = 5
 parent = L_DropDownList2 {
 }
}
tempFrame = L_DropDownList2 {
 0 = <userdata>
 parentLevel = 1
 Button1 = L_DropDownList2Button1 {
 }
 MenuBackdrop = L_DropDownList2MenuBackdrop {
 }
 Border = L_DropDownList2Border {
 }
 maxWidth = 183.470078
 dropdown = Titan_Bar__Display_BarRightClickMenu {
 }
 parentID = 5
 shouldRefresh = false
 parent = L_DropDownList1 {
 }
 numButtons = 10
 Backdrop = L_DropDownList2Backdrop {
 }
}
point = "TOPLEFT"
relativePoint = "TOPRIGHT"
relativeTo = nil
uiScale = 0.650000
uiParentScale = 0.650000
anchorFrame = L_DropDownList2Button2 {
 0 = <userdata>
 hasArrow = 1
 checked = 1
 invisibleButton = L_DropDownList2Button2InvisibleButton {
 }
 func = <function> defined @TitanClassic\TitanPanelClassic.lua:2090
 Highlight = L_DropDownList2Button2Highlight {
 }
 ExpandArrow = L_DropDownList2Button2ExpandArrow {
 }
 ColorSwatch = L_DropDownList2Button2ColorSwatch {
 }
 UnCheck = L_DropDownList2Button2UnCheck {
 }
 value = "BugSack"
 keepShownOnClick = 1
 Icon = L_DropDownList2Button2Icon {
 }
 Check = L_DropDownList2Button2Check {
 }
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = "Backdrop"
(*temporary) = L_DropDownList2Button2 {
 0 = <userdata>
 hasArrow = 1
 checked = 1
 invisibleButton = L_DropDownList2Button2InvisibleButton {
 }
 func = <function> defined @TitanClassic\TitanPanelClassic.lua:2090
 Highlight = L_DropDownList2Button2Highlight {
 }
 ExpandArrow = L_DropDownList2Button2ExpandArrow {
 }
 ColorSwatch = L_DropDownList2Button2ColorSwatch {
 }
 UnCheck = L_DropDownList2Button2UnCheck {
 }
 value = "BugSack"
 keepShownOnClick = 1
 Icon = L_DropDownList2Button2Icon {
 }
 Check = L_DropDownList2Button2Check {
 }
}
(*temporary) = "TOPRIGHT"
(*temporary) = 0
(*temporary) = 0
(*temporary) = <userdata>
(*temporary) = 3
(*temporary) = 2
(*temporary) = 1
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field '?' (a nil value)"
L_UIDropDownMenuDelegate = <unnamed> {
 0 = <userdata>
}
_G = <table> {
 UpdateOnBarHighlightMarksBySpell = <function> defined @FrameXML\ActionButton.lua:70
 ERR_OUT_OF_CHI = "Not enough chi"
 DH_HAVOC_CORE_ABILITY_2 = "Strong melee attack that consumes Fury. If it critical strikes, some Fury is refunded."
 MerchantItem9ItemButtonStock = MerchantItem9ItemButtonStock {
 }
 GetTrainerServiceTypeFilter = <function> defined =[C]:-1
 UNIT_NAMES_COMBATLOG_TOOLTIP = "Color unit names."
 aux.frame11Shine10 = aux.frame11Sh

**Comment by Altoholic** [comment]
Still, the error only happen when questie is activated.

**Comment by Altoholic** [comment]
I also have that one at each login 

16x Questie\Modules\Map\QuestieMap.lua:185: attempt to index field 'char' (a nil value)
Questie\Modules\Map\QuestieMap.lua:185: in function `GetScaleValue'
Questie\Modules\Map\QuestieMap.lua:201: in function `OnMapChanged'
...aceBlizzard_MapCanvas\Blizzard_MapCanvas.lua:529: in function `OnMapChanged'
...rfaceBlizzard_WorldMap\Blizzard_WorldMap.lua:115: in function `OnMapChanged'
...aceBlizzard_MapCanvas\Blizzard_MapCanvas.lua:37: in function `SetMapID'
TitanClassicLocation\TitanClassicLocation-1.2.10.11307.lua:75: in function `TitanPanelLocationButton_OnShow'
[string "*:OnShow"]:1: in function <[string "*:OnShow"]:1>
[C]: in function `Show'
TitanClassic\TitanPanelClassic.lua:1475: in function `TitanPanel_InitPanelButtons'
TitanClassic\TitanClassicVariables.lua:1045: in function `TitanVariables_UseSettings'
TitanClassic\TitanPanelClassic.lua:400: in function <TitanClassic\TitanPanelClassic.lua:327>
[C]: in function `pcall'
TitanClassic\TitanPanelClassic.lua:467: in function `?'
TitanClassic\TitanPanelClassic.lua:309: in function <TitanClassic\TitanPanelClassic.lua:308>

Locals:
self = <table> {
 zoneWaypointColorOverrides = <table> {
 }
 ShowNPC = <function> defined @Questie\Modules\Map\QuestieMap.lua:276
 GetManualFrames = <function> defined @Questie\Modules\Map\QuestieMap.lua:96
 UnloadQuestFrames = <function> defined @Questie\Modules\Map\QuestieMap.lua:74
 utils = <table> {
 }
 UnloadManualFrames = <function> defined @Questie\Modules\Map\QuestieMap.lua:109
 GetNearestSpawn = <function> defined @Questie\Modules\Map\QuestieMap.lua:772
 zoneWaypointHoverColorOverrides = <table> {
 }
 GetNearestQuestSpawn = <function> defined @Questie\Modules\Map\QuestieMap.lua:806
 manualFrames = <table> {
 }
 private = <table> {
 }
 _minimapDrawQueue = <table> {
 }
 questIdFrames = <table> {
 }
 DrawWaypoints = <function> defined @Questie\Modules\Map\QuestieMap.lua:890
 FindClosestStarter = <function> defined @Questie\Modules\Map\QuestieMap.lua:652
 ResetManualFrames = <function> defined @Questie\Modules\Map\QuestieMap.lua:119
 DrawWorldIcon = <function> defined @Questie\Modules\Map\QuestieMap.lua:493
 DrawManualIcon = <function> defined @Questie\Modules\Map\QuestieMap.lua:402
 DrawLineIcon = <function> defined @Questie\Modules\Map\QuestieMap.lua:383
 ShowObject = <function> defined @Questie\Modules\Map\QuestieMap.lua:335
 ProcessQueue = <function> defined @Questie\Modules\Map\QuestieMap.lua:243
 QueueDraw = <function> defined @Questie\Modules\Map\QuestieMap.lua:232
 ProcessShownMinimapIcons = <function> defined @Questie\Modules\Map\QuestieMap.lua:208
 ICON_MAP_TYPE = "MAP"
 GetFramesForQuest = <function> defined @Questie\Modules\Map\QuestieMap.lua:61
 RescaleIcons = <function> defined @Questie\Modules\Map\QuestieMap.lua:127
 InitializeQueue = <function> defined @Questie\Modules\Map\QuestieMap.lua:149
 GetScaleValue = <function> defined @Questie\Modules\Map\QuestieMap.lua:175
 _mapDrawQueue = <table> {
 }
 ICON_MINIMAP_TYPE = "MINIMAP"
}
mapId = 1414
scaling = 1
(*temporary) = nil
(*temporary) = "attempt to index field 'char' (a nil value)"
HBDPins = <table> {
 minimapPins = <table> {
 }
 SetMinimapObject = <function> defined @Questie\Libs\HereBeDragons\HereBeDragons-Pins-2.0.lua:656
 worldmapPinsPool = <table> {
 }
 RemoveMinimapIcon = <function> defined @Questie\Libs\HereBeDragons\HereBeDragons-Pins-2.0.lua:630
 IsMinimapIconOnEdge = <function> defined @Questie\Libs\HereBeDragons\HereBeDragons-Pins-2.0.lua:619
 Minimap = Minimap {
 }
 RemoveAllWorldMapIcons = <function> defined @Questie\Libs\HereBeDragons\HereBeDragons-Pins-2.0.lua:778
 worldmapPins = <table> {
 }
 RemoveAllMinimapIcons = <function> defined @Questie\Libs\HereBeDragons\HereBeDragons-Pins-2.0.lua:643
 worldmapProviderPin = <table> {
 }
 worldmapProvider = <table> {
 }
 updateFrame = <unnamed> {
 }
 GetVectorToIcon = <function> defined @Questie\Libs\HereBeDragons\HereBeDragons-Pins-2.0.lua:793
 RemoveWorldMapIcon = <function> defined @Questie\Libs\HereBeDragons\HereBeDragons-Pins-2.0.lua:764
 AddMinimapIconWorld = <function> defined @Questie\Libs\HereBeDragons\HereBeDragons-Pins-2.0.lua:555
 AddMinimapIconMap = <function> defined @Questie\Libs\HereBeDragons\HereBeDragons-Pins-2.0.lua:595
 AddWorldMapIconMap = <function> defined @Questie\Libs\HereBeDragons\HereBeDragons-Pins-2.0.lua:724
 AddWorldMapIconWorld = <function> defined @Questie\Libs\HereBeDragons\HereBeDragons-Pins-2.0.lua:683
 MinimapGroup = QuestieFrameGroup {
 }
 worldmapPinRegistry = <table> {
 }
 activeMinimapPins = <table> {
 }
 minimapPinRegistry = <table> {
 }
}

**Comment by BreakBB** [comment]
The latter issue will be fixed with the next release. Would be nice @waytoomuchgaming if you could report back here if the other issue is fixed as well with v6.3.13 (once it is out).

**Comment by waytoomuchgaming** [comment]
The latter issue have disappeared with 6.3.13.
The first one is still there.

**Comment by waytoomuchgaming** [comment]
> So it only happend when you hover over the Titan Panel location toolbar?
Yes.
And only in sub sub menus (the first sub menu don't trigger the error, i must go one sub menu deeper).

**Comment by drejjmit** [comment]
I believe it's because they haven't updated LibUIDropDownMenu from 2.0 to 4.0.
So unless he fixes that, more and more addons that update to latest LibUIDropDownMenu will break Titan Panel:
https://sourceforge.net/p/titan-panel-classic/tickets/42/

**Comment by BreakBB** [comment]
Closing this as this is not a Questie issue.
