### ISSUE TITLE
Class related quests

### ISSUE THREAD

**Issue by Nerillida** [Questie/Questie#2808]
We can search quests by name and by ID
This gives us quest info ID/starter/ender etc

It would be useful if you could search by class.
I would guess that you may have this info in the database. 

Class related quests do not seem to show up in zone lists or on the map, even for the class of the searcher.
Class related quests do not seem to show up in completed quests.
Not tested exhaustively.

**Comment by BreakBB** [comment]
There is now a "Class" section in the Quests by Zone tab which allows you look through all quests related to the players class.
