### ISSUE TITLE
Unplayable Lag whenever Shapeshifting on a Druid (Tauren Druid)

### ISSUE THREAD

**Issue by zgtmedia** [Questie/Questie#2809]
Problem goes away when disabling the addon, 
specs
5900x ryzen
3080 nvidia rtx
128gb 3600 mhz ram
corsair mp600 1tb ssd

**Comment by sungerbob** [comment]
I got same issue starting with classic tbc and Questie-v6.3.11-TBC version. Questie addon causing this issue.

**Comment by mkavalecz** [comment]
Same here, please, someone fix this.

**Comment by BreakBB** [comment]
The main issue lies on Blizzards side.

With the recent release of v6.3.12 we introduced a workaround for this which should help a lot!

Please update to the latest Questie and report back.

For future reports please add a screenshot of the Profile after you experienced these lags.

You can open the Profile in the Advanced section of the Questie settings!

**Comment by mkavalecz** [comment]
![image](https://user-images.githubusercontent.com/796242/119261528-1aaff000-bbd8-11eb-87fc-d339490b775e.png)

**Comment by mkavalecz** [comment]
![Uploading image.png…]()

**Comment by BreakBB** [comment]
Oh to be clear @mkavalecz the Profiler only records while it is open (at this point). So you have to have it open while you are testing the Shapeshifting 🙈

**Comment by drejjmit** [comment]
I usually just drag it down in one corner and let it sit there partially off screen until i need it.

**Comment by mkavalecz** [comment]
Ah, sorry. I thought that might be the case, but I didn't want to have a huge window open in combat.
For me, this usually happens in combat, when I try to reproduce it by just shifting forms and moving around, it usually works okay. Anyway, I'll try to get back with some better results. The update did seem to help a tiny bit, but it's still terrible.
I'll try moving the window away as @drejjmit suggested.

**Comment by sungerbob** [comment]
It's much better but sometimes I got a second lag when shapeshifting to cat form. I don't get same behavior with other questing addon like classiccodex, codexlite, carbonite etc. only happens with questie addon.

![1233232](https://user-images.githubusercontent.com/31207969/119266057-e3e6d380-bbf1-11eb-93c9-707f9eee8c6f.gif)

**Comment by btnmasher** [comment]
Adding a +1 to this. I am on the latest update and it hasn't made it any better. It gradually worsens until it is particularly bad to the point of multi-second-long freezing. I can /reload to help it for a while but only then it's a temporary alleviation.

**Comment by BreakBB** [comment]
@sungerbob @btnmasher Please read my comment above. We need data of our Profiler to investigate this further. Please start it up and then provoke the issue you have.

**Comment by lewis56060** [comment]
![error](https://user-images.githubusercontent.com/84785267/119505300-b79f9400-bd64-11eb-80b1-37f1c75dd0f3.png)

I'm having the same issue. It gets worse the more time goes on. Here is the outputs of about 1 minute of collection.

**Comment by BreakBB** [comment]
After further investigation we have to say that this is **NOT A QUESTIE BUG**, even though Questie increases this issue further. Please report it to Blizzard.

We will still try to implement a fix/work around for it! 👍🏻

**Comment by mkavalecz** [comment]
How should we report it? Can you share some details? I'm more than happy to do it, but I can't just say that "Shapeshifting causes lag, and if I enable an addon, it gets much worse."

**Comment by BreakBB** [comment]
Yes @mkavalecz this is related to the "Track Humanoid" spell that automatically gets activated when shifting into cat.

There is [a Reddit post](https://old.reddit.com/r/classicwow/comments/nk7qkx/every_time_i_shapeshift_it_lags_anyone_know_a_fix/) of it. In the past "viral" posts there got some attention.

There are also multiple posts on the Blizzard Forum where you should raise attention to this issue:

https://us.forums.blizzard.com/en/wow/t/druid-cat-shapeshift-broken/971944/10
https://us.forums.blizzard.com/en/wow/t/druid-shapeshift-track-humanoid-bug-now-w-hd-video-support/972063/2

**Comment by mkavalecz** [comment]
Thank you!

**Comment by BreakBB** [comment]
From what I know, this is no longer a problem. Please report back, if it still is.

**Comment by btnmasher** [comment]
Seems to be solved as far as I am aware.

**Comment by BreakBB** [comment]
Thanks for the fast response @btnmasher 👍🏻
