### ISSUE TITLE
Badlands Reagent Run II incorrectly shows up in log for non alchemists

### ISSUE THREAD

**Issue by Amolang** [Questie/Questie#2811]
The quest Badlands Reagent Run II (ID 2203) for Horde is showing for characters without Alchemy. 

alchemy being required is info I gathered from wowhead and can't verify it. All I can verify is that the npc Jarkal Mossmeld (ID 6868) doesn't offer the quest to me.

This is only an issue for the Quest by Zone option. It does not show on my minimap.

Questie v6.3.11 (Beta 4)

**Comment by BreakBB** [comment]
Fixed with 29ef101fe3cff7d44425bf577c61936a2a7d2347
