### ISSUE TITLE
Error on login

### ISSUE THREAD

**Issue by Nils89** [Questie/Questie#2812]
## Bug description
If I login I got the error, reload is not fixing it

## Questie version
latest on wowhub

Message: Interface\AddOns\Questie\Modules\QuestieMenu.lua:516: attempt to index field 'petFoodVendorTypes' (a nil value)
Time: Sat May 22 12:53:07 2021
Count: 1
Stack: Interface\AddOns\Questie\Modules\QuestieMenu.lua:516: attempt to index field 'petFoodVendorTypes' (a nil value)
[string "@Interface\AddOns\Questie\Modules\QuestieMenu.lua"]:516: in function `UpdatePetFood'
[string "@Interface\AddOns\Questie\Modules\QuestieMenu.lua"]:543: in function `UpdatePlayerVendors'
[string "@Interface\AddOns\Questie\Modules\QuestieMenu.lua"]:509: in function `PopulateTownsfolkPostBoot'
[string "@Interface\AddOns\Questie\Modules\QuestieEventHandler.lua"]:173: in function <...rface\AddOns\Questie\Modules\QuestieEventHandler.lua:161>

Locals: self = <table> {
 UpdateFoodDrink = <function> defined @Interface\AddOns\Questie\Modules\QuestieMenu.lua:527
 PopulateVendors = <function> defined @Interface\AddOns\Questie\Modules\QuestieMenu.lua:551
 BuildCharacterTownsfolk = <function> defined @Interface\AddOns\Questie\Modules\QuestieMenu.lua:581
 private = <table> {
 }
 Show = <function> defined @Interface\AddOns\Questie\Modules\QuestieMenu.lua:192
 UpdateAmmoVendors = <function> defined @Interface\AddOns\Questie\Modules\QuestieMenu.lua:523
 PopulateTownsfolkPostBoot = <function> defined @Interface\AddOns\Questie\Modules\QuestieMenu.lua:482
 UpdatePetFood = <function> defined @Interface\AddOns\Questie\Modules\QuestieMenu.lua:512
 PopulateTownsfolk = <function> defined @Interface\AddOns\Questie\Modules\QuestieMenu.lua:309
 PopulateTownsfolkType = <function> defined @Interface\AddOns\Questie\Modules\QuestieMenu.lua:292
 OnLogin = <function> defined @Interface\AddOns\Questie\Modules\QuestieMenu.lua:141
 UpdatePlayerVendors = <function> defined @Interface\AddOns\Questie\Modules\QuestieMenu.lua:539
}
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = "Fleisch"
}
(for control) = 1
_ = 1
key = "Fleisch"
(*temporary) = nil
(*temporary) = "Fleisch"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'petFoodVendorTypes' (a nil value)"
QuestieMenu = <table> {
 UpdateFoodDrink = <function> defined @Interface\AddOns\Questie\Modules\QuestieMenu.lua:527
 PopulateVendors = <function> defined @Interface\AddOns\Questie\Modules\QuestieMenu.lua:551
 BuildCharacterTownsfolk = <function> defined @Interface\AddOns\Questie\Modules\QuestieMenu.lua:581
 private = <table> {
 }
 Show = <function> defined @Interface\AddOns\Questie\Modules\QuestieMenu.lua:192
 UpdateAmmoVendors = <function> defined @Interface\AddOns\Questie\Modules\QuestieMenu.lua:523
 PopulateTownsfolkPostBoot = <function> defined @Interface\AddOns\Questie\Modules\QuestieMenu.lua:482
 UpdatePetFood = <function> defined @Interface\AddOns\Questie\Modules\QuestieMenu.lua:512
 PopulateTownsfolk = <function> defined @Interface\AddOns\Questie\Modules\QuestieMenu.lua:309
 PopulateTownsfolkType = <function> defined @Interface\AddOns\Questie\Modules\QuestieMenu.lua:292
 OnLogin = <function> defined @Interface\AddOns\Questie\Modules\QuestieMenu.lua:141
 UpdatePlayerVendors = <function> defined @Interface\AddOns\Questie\Modules\QuestieMenu.lua:539
}
_reformatVendors = <function> defined @Interface\AddOns\Questie\Modules\QuestieMenu.lua:284

**Comment by BreakBB** [comment]
@Nils89 Please update to v6.3.12 and reply if that error is fixed.

**Comment by Nils89** [comment]
@BreakBB this one is gone, now i got:

Message: Interface\AddOns\Questie\Modules\Map\QuestieMap.lua:185: attempt to index field 'char' (a nil value)
Time: Mon May 24 19:56:00 2021
Count: 1
Stack: Interface\AddOns\Questie\Modules\Map\QuestieMap.lua:185: attempt to index field 'char' (a nil value)
[string "@Interface\AddOns\Questie\Modules\Map\QuestieMap.lua"]:185: in function `GetScaleValue'
[string "@Interface\AddOns\Questie\Modules\Map\QuestieMap.lua"]:201: in function `OnMapChanged'
[string "@Interface\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua"]:531: in function `OnMapChanged'
[string "@Interface\AddOns\Blizzard_WorldMap\Blizzard_WorldMap.lua"]:121: in function `OnMapChanged'
[string "@Interface\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua"]:39: in function `SetMapID'
[string "@Interface\AddOns\Blizzard_WorldMap\Blizzard_WorldMap.lua"]:144: in function <...rface\AddOns\Blizzard_WorldMap\Blizzard_WorldMap.lua:142>
[string "=[C]"]: in function `Show'
[string "@Interface\FrameXML\UIParent.lua"]:2088: in function `SetUIPanel'
[string "@Interface\FrameXML\UIParent.lua"]:1933: in function `ShowUIPanel'
[string "@Interface\FrameXML\UIParent.lua"]:1794: in function <Interface\FrameXML\UIParent.lua:1790>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface\FrameXML\UIParent.lua"]:2559: in function `ShowUIPanel'
[string "@Interface\AddOns\GW2_UI\immersive\skins\worldmap.lua"]:69: in function `SkinWorldMap'
[string "@Interface\AddOns\GW2_UI\GW2_ui.lua"]:446: in function <Interface\AddOns\GW2_UI\GW2_ui.lua:355>
[string "@Interface\AddOns\GW2_UI\GW2_ui.lua"]:657: in function <Interface\AddOns\GW2_UI\GW2_ui.lua:653>

Locals: self = <table> {
 zoneWaypointColorOverrides = <table> {
 }
 ShowNPC = <function> defined @Interface\AddOns\Questie\Modules\Map\QuestieMap.lua:276
 GetManualFrames = <function> defined @Interface\AddOns\Questie\Modules\Map\QuestieMap.lua:96
 UnloadQuestFrames = <function> defined @Interface\AddOns\Questie\Modules\Map\QuestieMap.lua:74
 utils = <table> {
 }
 UnloadManualFrames = <function> defined @Interface\AddOns\Questie\Modules\Map\QuestieMap.lua:109
 GetNearestSpawn = <function> defined @Interface\AddOns\Questie\Modules\Map\QuestieMap.lua:772
 zoneWaypointHoverColorOverrides = <table> {
 }
 GetNearestQuestSpawn = <function> defined @Interface\AddOns\Questie\Modules\Map\QuestieMap.lua:806
 manualFrames = <table> {
 }
 private = <table> {
 }
 _minimapDrawQueue = <table> {
 }
 questIdFrames = <table> {
 }
 DrawWaypoints = <function> defined @Interface\AddOns\Questie\Modules\Map\QuestieMap.lua:890
 FindClosestStarter = <function> defined @Interface\AddOns\Questie\Modules\Map\QuestieMap.lua:652
 ResetManualFrames = <function> defined @Interface\AddOns\Questie\Modules\Map\QuestieMap.lua:119
 DrawWorldIcon = <function> defined @Interface\AddOns\Questie\Modules\Map\QuestieMap.lua:493
 DrawManualIcon = <function> defined @Interface\AddOns\Questie\Modules\Map\QuestieMap.lua:402
 DrawLineIcon = <function> defined @Interface\AddOns\Questie\Modules\Map\QuestieMap.lua:383
 ShowObject = <function> defined @Interface\AddOns\Questie\Modules\Map\QuestieMap.lua:335
 ProcessQueue = <function> defined @Interface\AddOns\Questie\Modules\Map\QuestieMap.lua:243
 QueueDraw = <function> defined @Interface\AddOns\Questie\Modules\Map\QuestieMap.lua:232
 ProcessShownMinimapIcons = <function> defined @Interface\AddOns\Questie\Modules\Map\QuestieMap.lua:208
 ICON_MAP_TYPE = "MAP"
 GetFramesForQuest = <function> defined @Interface\AddOns\Questie\Modules\Map\QuestieMap.lua:61
 RescaleIcons = <function> defined @Interface\AddOns\Questie\Modules\Map\QuestieMap.lua:127
 InitializeQueue = <function> defined @Interface\AddOns\Questie\Modules\Map\QuestieMap.lua:149
 GetScaleValue = <function> defined @Interface\AddOns\Questie\Modules\Map\QuestieMap.lua:175
 _mapDrawQueue = <table> {
 }
 ICON_MINIMAP_TYPE = "MINIMAP"
}
mapId = 1414
scaling = 1
(*temporary) = nil
(*temporary) = "attempt to index field 'char' (a nil value)"
HBDPins = <table> {
 minimapPins = <table> {
 }

**Comment by Nils89** [comment]
a reload is fixing it.
Can be also a addon conflict?

**Comment by BreakBB** [comment]
The second error will be fixed in the next release. See #2822
