### ISSUE TITLE
Some errors on zone change

### ISSUE THREAD

**Issue by Telison** [Questie/Questie#2814]
I get the following errors on every zone change, version 6.3.11 in TBC classic:

![QuestieErrors](https://user-images.githubusercontent.com/6370160/119230040-d9a5d600-bb1a-11eb-877b-069f721a0c2e.PNG)

These are the quests in my log atm

![QuestieQuests](https://user-images.githubusercontent.com/6370160/119230051-e5919800-bb1a-11eb-86b6-40b684c8553f.PNG)

**Comment by drejjmit** [comment]
1437 got an Explore Objective in TBC that isn't there in Classic vanilla.
1382 will be fixed in next release.

**Comment by drejjmit** [comment]
Thanks for the report. I collected all similar problems in a new issue #2866
We will try to get it sorted for next release!
