### ISSUE TITLE
LUA-ERROR on login

### ISSUE THREAD

**Issue by tronix90** [Questie/Questie#2817]
Message: Interface\AddOns\Questie\Questie.lua:248: attempt to concatenate local 'str' (a nil value)
Time: Sat May 22 21:04:32 2021
Count: 1
Stack: Interface\AddOns\Questie\Questie.lua:248: attempt to concatenate local 'str' (a nil value)
[string "@Interface\AddOns\Questie\Questie.lua"]:248: in function `Colorize'
[string "@Interface\AddOns\Questie\Modules\QuestieMenu.lua"]:94: in function <Interface\AddOns\Questie\Modules\QuestieMenu.lua:87>
[string "@Interface\SharedXML\C_TimerAugment.lua"]:16: in function <Interface\SharedXML\C_TimerAugment.lua:14>

Locals: self = <table> {
 SetDefaultModuleLibraries = <function> defined @Interface\AddOns\HandyNotes\Libs\AceAddon-3.0\AceAddon-3.0.lua:367
 Colorize = <function> defined @Interface\AddOns\Questie\Questie.lua:221
 Enable = <function> defined @Interface\AddOns\HandyNotes\Libs\AceAddon-3.0\AceAddon-3.0.lua:294
 RegisterChatCommand = <function> defined @Interface\AddOns\HandyNotes\Libs\AceConsole-3.0\AceConsole-3.0.lua:85
 GetClassColor = <function> defined @Interface\AddOns\Questie\Questie.lua:251
 EnableModule = <function> defined @Interface\AddOns\HandyNotes\Libs\AceAddon-3.0\AceAddon-3.0.lua:332
 modules = <table> {
 }
 GetModule = <function> defined @Interface\AddOns\HandyNotes\Libs\AceAddon-3.0\AceAddon-3.0.lua:210
 IterateEmbeds = <function> defined @Interface\AddOns\HandyNotes\Libs\AceAddon-3.0\AceAddon-3.0.lua:442
 started = true
 UnregisterComm = <function> defined @Interface\AddOns\AtlasLootClassic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 defaultModuleLibraries = <table> {
 }
 TimeLeft = <function> defined @Interface\AddOns\Questie\Libs\AceTimer-3.0\AceTimer-3.0.lua:172
 Deserialize = <function> defined @Interface\AddOns\Questie\Libs\AceSerializer-3.0\AceSerializer-3.0.lua:246
 UnregisterChatCommand = <function> defined @Interface\AddOns\HandyNotes\Libs\AceConsole-3.0\AceConsole-3.0.lua:111
 minimapConfigIcon = <table> {
 }
 ScheduleRepeatingTimer = <function> defined @Interface\AddOns\Questie\Libs\AceTimer-3.0\AceTimer-3.0.lua:129
 CancelAllTimers = <function> defined @Interface\AddOns\Questie\Libs\AceTimer-3.0\AceTimer-3.0.lua:160
 Printf = <function> defined @Interface\AddOns\HandyNotes\Libs\AceConsole-3.0\AceConsole-3.0.lua:69
 RegisterBucketEvent = <function> defined @Interface\AddOns\Questie\Libs\AceBucket-3.0\AceBucket-3.0.lua:184
 SetDefaultModulePrototype = <function> defined @Interface\AddOns\HandyNotes\Libs\AceAddon-3.0\AceAddon-3.0.lua:409
 TBC_BETA_BUILD_VERSION_SHORTHAND = ""
 baseName = "Questie"
 Debug = <function> defined @Interface\AddOns\Questie\Questie.lua:281
 name = "Questie"
 Error = <function> defined @Interface\AddOns\Questie\Questie.lua:277
 IsEnabled = <function> defined @Interface\AddOns\HandyNotes\Libs\AceAddon-3.0\AceAddon-3.0.lua:451
 orderedModules = <table> {
 }
 ScheduleTimer = <function> defined @Interface\AddOns\Questie\Libs\AceTimer-3.0\AceTimer-3.0.lua:94
 DisableModule = <function> defined @Interface\AddOns\HandyNotes\Libs\AceAddon-3.0\AceAddon-3.0.lua:350
 HandleSlash = <function> defined @Interface\AddOns\Questie\Questie.lua:217
 OnDisable = <function> defined @Interface\AddOns\Questie\Questie.lua:213
 OnEnable = <function> defined @Interface\AddOns\Questie\Questie.lua:209
 OnUpdate = <function> defined @Interface\AddOns\Questie\Questie.lua:205
 RegisterMessage = <function> defined @Interface\AddOns\AtlasLootClassic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 GetArgs = <function> defined @Interface\AddOns\HandyNotes\Libs\AceConsole-3.0\AceConsole-3.0.lua:144
 Print = <function> defined @Interface\AddOns\HandyNotes\Libs\AceConsole-3.0\AceConsole-3.0.lua:54
 OnInitialize = <function> defined @Interface\AddOns\Questie\Questie.lua:134
 UnregisterAllBuckets = <function> defined @Interface\AddOns\Questie\Libs\AceBucket-3.0\AceBucket-3.0.lua:229
 UnregisterBucket = <function> defined @Interface\AddOns\Questie\Libs\AceBucket-3.0\AceBucket-3.0.lua:206
 RegisterBucketMessage = <function> defined @Interface\AddOns\Quest

**Comment by BreakBB** [comment]
Please update to v6.3.12 and report if you still encounter this issue @tronix90

**Comment by tronix90** [comment]
It is fixed. THX!!!!
