### ISSUE TITLE
Test of Faith / Test of Endurance nil error

### ISSUE THREAD

**Issue by raethkcj** [Questie/Questie#2819]
## Bug description
This error appeared after:
1. Completing Test of Faith as normal
2. Accepting Test of Endurance
3. Flying to Orgrimmar, getting on the Zeppelin to UC. Error appeared after loading screen. The quest ID questie shows in the chat window is for Test of Faith (1149), but the quest in the chain I was on at the time was Test of Endurance (1150).

## Screenshots
![image](https://user-images.githubusercontent.com/7716908/119240662-c8f36100-bb16-11eb-9d67-50e3a6bed48f.png)

## Questie version

v6.3.11

**Comment by drejjmit** [comment]
Thanks for the report. I collected all similar problems in a new issue #2866
We will try to get it sorted for next release!
