### ISSUE TITLE
QuestieLib.lua:256: bad argument #1 to 'unpack' (table expected, got nil)

### ISSUE THREAD

**Issue by rbpaiett** [Questie/Questie#2821]
## Bug description

I was killing a mob for quest #9513 Reclaiming the Ruins and I just killed off I think was a Wrathscale Myrmidon when this error popped up:

1x Questie\Modules\Libs\QuestieLib.lua:256: bad argument #1 to 'unpack' (table expected, got nil)
[string "=[C]"]: in function `unpack'
[string "@Questie\Modules\Libs\QuestieLib.lua"]:256: in function `GetTbcLevel'
[string "@Questie\Modules\Tooltips\ChatFilter.lua"]:37: in function `filterFunc'
[string "@FrameXML\ChatFrame.lua"]:3207: in function `ChatFrame_MessageEventHandler'
[string "@FrameXML\ChatFrame.lua"]:2930: in function `ChatFrame_OnEvent'
[string "*:OnEvent"]:1: in function <[string "*:OnEve
Locals:
(*temporary) = nil
(*temporary) = "table expected, got nil"

I had no errors up until then but right after I joined a group it appeared.   It appears I only got one error.

## Questie version

Questie version 6.3.11-TBC

**Comment by BreakBB** [comment]
This should no longer happen, but feel free to open up a new issue if you still experience issues.

**Comment by rbpaiett** [comment]
Thanks so much!
