### ISSUE TITLE
lua error [Classic ERA]

### ISSUE THREAD

**Issue by waytoomuchgaming** [Questie/Questie#2822]
## Bug description
at every login

## Questie version
v6.3.12

2x Questie\Modules\Map\QuestieMap.lua:185: attempt to index field 'char' (a nil value)
Questie\Modules\Map\QuestieMap.lua:185: in function `GetScaleValue'
Questie\Modules\Map\QuestieMap.lua:201: in function `OnMapChanged'
...aceBlizzard_MapCanvas\Blizzard_MapCanvas.lua:529: in function `OnMapChanged'
...rfaceBlizzard_WorldMap\Blizzard_WorldMap.lua:115: in function `OnMapChanged'
...aceBlizzard_MapCanvas\Blizzard_MapCanvas.lua:37: in function `SetMapID'
TitanClassicLocation\TitanClassicLocation-1.2.10.11307.lua:75: in function `TitanPanelLocationButton_OnShow'
[string "*:OnShow"]:1: in function <[string "*:OnShow"]:1>
[C]: in function `Show'
TitanClassic\TitanPanelClassic.lua:1475: in function `TitanPanel_InitPanelButtons'
TitanClassic\TitanClassicVariables.lua:1045: in function `TitanVariables_UseSettings'
TitanClassic\TitanPanelClassic.lua:400: in function <TitanClassic\TitanPanelClassic.lua:327>
[C]: in function `pcall'
TitanClassic\TitanPanelClassic.lua:467: in function `?'
TitanClassic\TitanPanelClassic.lua:309: in function <TitanClassic\TitanPanelClassic.lua:308>

Locals:
self = <table> {
 zoneWaypointColorOverrides = <table> {
 }
 ShowNPC = <function> defined @Questie\Modules\Map\QuestieMap.lua:276
 GetManualFrames = <function> defined @Questie\Modules\Map\QuestieMap.lua:96
 UnloadQuestFrames = <function> defined @Questie\Modules\Map\QuestieMap.lua:74
 utils = <table> {
 }
 UnloadManualFrames = <function> defined @Questie\Modules\Map\QuestieMap.lua:109
 GetNearestSpawn = <function> defined @Questie\Modules\Map\QuestieMap.lua:772
 zoneWaypointHoverColorOverrides = <table> {
 }
 GetNearestQuestSpawn = <function> defined @Questie\Modules\Map\QuestieMap.lua:806
 manualFrames = <table> {
 }
 private = <table> {
 }
 _minimapDrawQueue = <table> {
 }
 questIdFrames = <table> {
 }
 DrawWaypoints = <function> defined @Questie\Modules\Map\QuestieMap.lua:890
 FindClosestStarter = <function> defined @Questie\Modules\Map\QuestieMap.lua:652
 ResetManualFrames = <function> defined @Questie\Modules\Map\QuestieMap.lua:119
 DrawWorldIcon = <function> defined @Questie\Modules\Map\QuestieMap.lua:493
 DrawManualIcon = <function> defined @Questie\Modules\Map\QuestieMap.lua:402
 DrawLineIcon = <function> defined @Questie\Modules\Map\QuestieMap.lua:383
 ShowObject = <function> defined @Questie\Modules\Map\QuestieMap.lua:335
 ProcessQueue = <function> defined @Questie\Modules\Map\QuestieMap.lua:243
 QueueDraw = <function> defined @Questie\Modules\Map\QuestieMap.lua:232
 ProcessShownMinimapIcons = <function> defined @Questie\Modules\Map\QuestieMap.lua:208
 ICON_MAP_TYPE = "MAP"
 GetFramesForQuest = <function> defined @Questie\Modules\Map\QuestieMap.lua:61
 RescaleIcons = <function> defined @Questie\Modules\Map\QuestieMap.lua:127
 InitializeQueue = <function> defined @Questie\Modules\Map\QuestieMap.lua:149
 GetScaleValue = <function> defined @Questie\Modules\Map\QuestieMap.lua:175
 _mapDrawQueue = <table> {
 }
 ICON_MINIMAP_TYPE = "MINIMAP"
}
mapId = 1415
scaling = 1
(*temporary) = nil
(*temporary) = "attempt to index field 'char' (a nil value)"
HBDPins = <table> {
 minimapPins = <table> {
 }
 SetMinimapObject = <function> defined @Questie\Libs\HereBeDragons\HereBeDragons-Pins-2.0.lua:656
 worldmapPinsPool = <table> {
 }
 RemoveMinimapIcon = <function> defined @Questie\Libs\HereBeDragons\HereBeDragons-Pins-2.0.lua:630
 IsMinimapIconOnEdge = <function> defined @Questie\Libs\HereBeDragons\HereBeDragons-Pins-2.0.lua:619
 Minimap = Minimap {
 }
 RemoveAllWorldMapIcons = <function> defined @Questie\Libs\HereBeDragons\HereBeDragons-Pins-2.0.lua:778
 worldmapPins = <table> {
 }
 RemoveAllMinimapIcons = <function> defined @Questie\Libs\HereBeDragons\HereBeDragons-Pins-2.0.lua:643
 worldmapProviderPin = <table> {
 }
 worldmapProvider = <table> {
 }
 updateFrame = <unnamed> {
 }
 GetVectorToIcon = <function> defined @Questie\Libs\HereBeDragons\HereBeDragons-Pins-2.0.lua:793
 RemoveWorldMapIcon = <function> defined @Questie\Libs\HereBeDragons\HereBeDragons-Pins-2.0.lua:764
 AddMinimapIconWorld = <function> defined @Questie\Libs\HereBeDragons\HereBeDragons-Pins-2.0.lua:555
 AddMinimapIconMap = <function> defined @Questie\Libs\HereBeDragons\HereBeDragons-Pins-2.0.lua:595
 AddWorldMapIconMap = <function> defined @Questie\Libs\HereBeDragons\HereBeDragons-Pins-2.0.lua:724
 AddWorldMapIconWorld = <function> defined @Questie\Libs\HereBeDragons\HereBeDragons-Pins-2.0.lua:683
 MinimapGroup = QuestieFrameGroup {
 }
 worldmapPinRegistry = <table> {
 }
 activeMinimapPins = <table> {
 }
 minimapPinRegistry = <table> {
 }
}

**Comment by BreakBB** [comment]
This has been fixed with 77dd3669bae41a137682d8064af9fad6dafd2d50 and e356efb5e4be4b5a3a7c3945493f35caac3f7318 and will be included in the next release (which is coming out soon).
