### ISSUE TITLE
Wrong position for NPC Vincent Hyal (5082)

### ISSUE THREAD

**Issue by max-ri** [Questie/Questie#2823]
Vincent Hyal (id 5082), quest giver of quest James Hyal (id 1301), for no apparent reason seems now to be permanently positioned at the docks in Menethil Harbor. He used to be in the inn. Maybe needed fresh air.
New coordinates: 8.39, 61.76

![grafik](https://user-images.githubusercontent.com/51713394/119252024-0b19b280-bbaa-11eb-9897-a35f92e2db68.png)

**Comment by Nerillida** [comment]
He moved to dock in tbc, see comments of

https://tbc.wowhead.com/npc=5082/vincent-hyal

**Comment by drejjmit** [comment]
2aa1bb714ccbc76c06aa37901123d4024e5bdd9e
