### ISSUE TITLE
Wrong prequest for quest Inspecting the Ruins (id 11123)

### ISSUE THREAD

**Issue by max-ri** [Questie/Questie#2825]
According to Questie (6.3.12) completing They Call Him Smiling Jim (id 1282) is required in order to accept this quest. This is not the case.

![image](https://cdn.discordapp.com/attachments/627284872335196170/845735354618478642/WoWScrnShot_052221_144619.jpg)

**Comment by drejjmit** [comment]
97bb520d4dbbb2c6b1322744ccd1cd7b74018774
