### ISSUE TITLE
Wrong prequest for quest Search Stillpine Hold (9565)

### ISSUE THREAD

**Issue by max-ri** [Questie/Questie#2826]
Same as it was for Chieftain Oomooroo (9573). See #2793.
Able to pick it up without having completed Murlocs Why Here Why Now(9562). Have completed Beasts of the Apocalypse (9560) though.
Probably requires either one.

![grafik](https://user-images.githubusercontent.com/51713394/119257448-90f72700-bbc5-11eb-965e-dbd0a5bf8126.png)

Questie is 6.3.12

**Comment by Nerillida** [comment]
The comments of

https://tbc.wowhead.com/quest=9565/search-stillpine-hold

suggest it's one of 
https://tbc.wowhead.com/quest=9560/beasts-of-the-apocalypse
https://tbc.wowhead.com/quest=9562/murlocs-why-here-why-now

https://tbc.wowhead.com/quest=9570/the-kurken-is-lurkin
needs
https://tbc.wowhead.com/quest=9565/search-stillpine-hold#comments:id=154910;40

**Comment by drejjmit** [comment]
4111fadc0696ebdb35ed7dd4d072a0e9dd6037bb
