### ISSUE TITLE
Frequent 6.3.12

### ISSUE THREAD

**Issue by Nerillida** [Questie/Questie#2829]
Message: Interface\AddOns\Questie\Modules\Map\QuestieMap.lua:185: attempt to index field 'char' (a nil value)
Time: Sun May 23 17:23:23 2021
Count: 1
Stack: Interface\AddOns\Questie\Modules\Map\QuestieMap.lua:185: attempt to index field 'char' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\Questie\Modules\Map\QuestieMap.lua"]:185: in function `GetScaleValue'
[string "@Interface\AddOns\Questie\Modules\Map\QuestieMap.lua"]:201: in function `OnMapChanged'
[string "@Interface\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua"]:531: in function `OnMapChanged'
[string "@Interface\AddOns\Blizzard_WorldMap\Blizzard_WorldMap.lua"]:121: in function `OnMapChanged'
[string "@Interface\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua"]:39: in function `SetMapID'
[string "@Interface\AddOns\TitanClassicLocation\TitanClassicLocation.lua"]:75: in function `TitanPanelLocationButton_OnShow'
[string "*:OnShow"]:1: in function <[string "*:OnShow"]:1>
[string "=[C]"]: in function `Show'
[string "@Interface\AddOns\TitanClassic\TitanPanelClassic.lua"]:1475: in function `TitanPanel_InitPanelButtons'
[string "@Interface\AddOns\TitanClassic\TitanClassicVariables.lua"]:1045: in function `TitanVariables_UseSettings'
[string "@Interface\AddOns\TitanClassic\TitanPanelClassic.lua"]:400: in function <Interface\AddOns\TitanClassic\TitanPanelClassic.lua:327>
[string "=[C]"]: in function `pcall'
[string "@Interface\AddOns\TitanClassic\TitanPanelClassic.lua"]:467: in function `?'
[string "@Interface\AddOns\TitanClassic\TitanPanelClassic.lua"]:309: in function <Interface\AddOns\TitanClassic\TitanPanelClassic.lua:308>

Locals:

**Comment by rbpaiett** [comment]
I'm getting this error as well.

This is Questie 6.3.12

**Comment by Nerillida** [comment]
From dev
> By troubleshooting, there seems to be a conflict between Questie & TitanClassicLocation. The error can temporarily be stopped by disabling TitanClassicLocation while we wait for resolution.

Closed as duplicate

**Comment by rbpaiett** [comment]
If this is a duplicate, where would I find the original petition so I can follow it?

**Comment by Nerillida** [comment]
https://github.com/Questie/Questie/issues/2836

**Comment by rbpaiett** [comment]
Thanks so much!
