### ISSUE TITLE
Rethban ore quest status showing up for all copper/tin mining nodes

### ISSUE THREAD

**Issue by matthewhively** [Questie/Questie#2831]
Questie version 6.3.12

Quest: https://tbc.wowhead.com/quest=347/rethban-ore
All mining nodes all over the world (for instance westfall & deadmines) show rethban ore 0/5 tooltip

Screenshot
![WoWScrnShot_052321_204455](https://user-images.githubusercontent.com/25018092/119293731-de948380-bc07-11eb-86f9-f9d0fcd794cb.jpg)

**Comment by Nerillida** [comment]
Agree, this is not a new error. Noticed it pre tbc

**Comment by Laumesis** [comment]
FYI, The bug still exists in Questie v6.5.0

**Comment by Nerillida** [comment]
I guess it's a low priority.

**Comment by drejjmit** [comment]
Wow doesn't give object ids like they do npc ids. We need to compare object name with the database. So you either get all Copper / Tin veins or none.

**Comment by matthewhively** [comment]
Wouldn't it be possible to do a zone check? If you're in the correct zone for the quest it'll modify the tooltip, and it won't otherwise?

**Comment by snookylops** [comment]
![Rethban Ore Quest](https://user-images.githubusercontent.com/70088140/163466074-6974d3fc-9210-4090-a316-00f6d37b095f.jpg)

**Comment by snookylops** [comment]
So I hopped back over to Kalimdor, and noticed on the map that it's showing Rethban Ore dotted all over the Barrens for some reason. It's not appearing in any other zone in Kalimdor, so not sure what's going on with that.

**Comment by matthewhively** [comment]
> So I hopped back over to Kalimdor, and noticed on the map that it's showing Rethban Ore dotted all over the Barrens for some reason. It's not appearing in any other zone in Kalimdor, so not sure what's going on with that.

I suspect that is because you're currently in the barrens. I suspect if you moved to an adjacent zone the map would re-render to show in that zone instead.

**Comment by snookylops** [comment]
> 

The map looked like that when I was in Darkshore after getting off the boat (I was making the run to pick up the flight path in Ratchet, then take the boat to STV to get the fishing book) and decided to swing by while passing thru the Barrens and see if the quest markers actually turned up anything or if it was a bug. There were no quest icons for the Rethban ore in Darkshore while I was there, nor while running through Ashenvale.

**Comment by Muehe** [comment]
Seems to have fixed itself with some DB update, it only shows [tin](https://www.wowhead.com/classic/object=2054/tin-vein)/[copper](https://www.wowhead.com/classic/object=2055/copper-vein) veins in Redridge Mountains now, and one [NPC](https://www.wowhead.com/classic/npc=580/redridge-drudger). (Only confirmed with marking the item through Advanced Search though, veins might be blacklisted for quest display; Either way it won't show all over the world anymore.)
