### ISSUE TITLE
Blood Elf Paladin Epic Mount Quest [True Masters of the Light]

### ISSUE THREAD

**Issue by Aviana** [Questie/Questie#2832]
## Description
Having the quest produces the following error.
The quests leading up to this also produce errors but i forgot to take screenshots.

## Wowhead link
https://tbc.wowhead.com/quest=9737

## Screenshots
![error](https://user-images.githubusercontent.com/425023/119320252-afb7f500-bc7b-11eb-8583-c307b13fed33.png)

## Questie version
v6.3.12

**Comment by BreakBB** [comment]
Has been fixed with e1ece1d1df837211763d5de14d5fa915b20e891b and will be included in the next release.
