### ISSUE TITLE
Missing objective data for quest 1437

### ISSUE THREAD

**Issue by zdeyn** [Questie/Questie#2833]
Howdy,

I'm getting the following error:

` Questie: [ERROR] Missing objective data for quest 1437 and objective ` 
`Questie: [ERROR] Missing objective data for quest 1437 1 `

Quests in my quest log:
(Desolace):
Centaur Bounty
Vahlarriel's Search
Strange Alliance

I'm playing a level 34 Night Elf Priest

Thanks

**Comment by drejjmit** [comment]
https://eu.forums.blizzard.com/en/wow/t/vahlarriels-search-desolace-quest-bugged/280921/
Blizzard issue.
