### ISSUE TITLE
Completed quest icon showing despite the option being disabled

### ISSUE THREAD

**Issue by jukuf** [Questie/Questie#2835]
## Bug description
Despite having the option disabled, a completed quest icon shows for the quest A Watchful Eye in Redridge Mountains. Not really sure what triggers it, but this particular bug with A Watchful Eye happened on 2 of my characters. Another important detail is that when this happens, not only does it show the completed quest icon for A Watchful Eye, but it shows the completed quest icon for EVERY completed quest in my quest log, as if I enabled the option (checked it multiple times, it is not enabled). Tried turning the option off and on, doing /reload, but it just keeps appearing. It turns to normal once I turn in the quest.

Another instance of the completed quest icon showing when the option is disabled is when an NPC has a completed quest on it and a quest to pick up from them, so it's basically as if the quest icon for pick up gets replaced by an icon for completed quest.

## Questie version
Using version v6.3.11

**Comment by Laumesis** [comment]
@jukuf
I think this is fixed now in v6.6.0. Do you still have the issue?

**Comment by BreakBB** [comment]
Assuming this is fixed.
