### ISSUE TITLE
Error on login

### ISSUE THREAD

**Issue by throw-this-shit-away** [Questie/Questie#2836]
Hi, 

I have the newest version and get this error on login:

Message: Interface\AddOns\Questie\Modules\Map\QuestieMap.lua:185: attempt to index field 'char' (a nil value)
Time: Tue May 25 00:00:13 2021
Count: 1
Stack: Interface\AddOns\Questie\Modules\Map\QuestieMap.lua:185: attempt to index field 'char' (a nil value)
[string "@Interface\AddOns\Questie\Modules\Map\QuestieMap.lua"]:185: in function `GetScaleValue'
[string "@Interface\AddOns\Questie\Modules\Map\QuestieMap.lua"]:201: in function `OnMapChanged'
[string "@Interface\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua"]:531: in function `OnMapChanged'
[string "@Interface\AddOns\Blizzard_WorldMap\Blizzard_WorldMap.lua"]:121: in function `OnMapChanged'
[string "@Interface\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua"]:39: in function `SetMapID'
[string "@Interface\AddOns\TitanClassicLocation\TitanClassicLocation.lua"]:75: in function `TitanPanelLocationButton_OnShow'
[string "*:OnShow"]:1: in function <[string "*:OnShow"]:1>
[string "=[C]"]: in function `Show'
[string "@Interface\AddOns\TitanClassic\TitanPanelClassic.lua"]:1475: in function `TitanPanel_InitPanelButtons'
[string "@Interface\AddOns\TitanClassic\TitanClassicVariables.lua"]:1045: in function `TitanVariables_UseSettings'
[string "@Interface\AddOns\TitanClassic\TitanPanelClassic.lua"]:400: in function <Interface\AddOns\TitanClassic\TitanPanelClassic.lua:327>
[string "=[C]"]: in function `pcall'
[string "@Interface\AddOns\TitanClassic\TitanPanelClassic.lua"]:467: in function `?'
[string "@Interface\AddOns\TitanClassic\TitanPanelClassic.lua"]:309: in function <Interface\AddOns\TitanClassic\TitanPanelClassic.lua:308>

Locals: self = <table> {
 zoneWaypointColorOverrides = <table> {
 }
 ShowNPC = <function> defined @Interface\AddOns\Questie\Modules\Map\QuestieMap.lua:276
 GetManualFrames = <function> defined @Interface\AddOns\Questie\Modules\Map\QuestieMap.lua:96
 UnloadQuestFrames = <function> defined @Interface\AddOns\Questie\Modules\Map\QuestieMap.lua:74
 utils = <table> {
 }
 UnloadManualFrames = <function> defined @Interface\AddOns\Questie\Modules\Map\QuestieMap.lua:109
 GetNearestSpawn = <function> defined @Interface\AddOns\Questie\Modules\Map\QuestieMap.lua:772
 zoneWaypointHoverColorOverrides = <table> {
 }
 GetNearestQuestSpawn = <function> defined @Interface\AddOns\Questie\Modules\Map\QuestieMap.lua:806
 manualFrames = <table> {
 }
 private = <table> {
 }
 _minimapDrawQueue = <table> {
 }
 questIdFrames = <table> {
 }
 DrawWaypoints = <function> defined @Interface\AddOns\Questie\Modules\Map\QuestieMap.lua:890
 FindClosestStarter = <function> defined @Interface\AddOns\Questie\Modules\Map\QuestieMap.lua:652
 ResetManualFrames = <function> defined @Interface\AddOns\Questie\Modules\Map\QuestieMap.lua:119
 DrawWorldIcon = <function> defined @Interface\AddOns\Questie\Modules\Map\QuestieMap.lua:493
 DrawManualIcon = <function> defined @Interface\AddOns\Questie\Modules\Map\QuestieMap.lua:402
 DrawLineIcon = <function> defined @Interface\AddOns\Questie\Modules\Map\QuestieMap.lua:383
 ShowObject = <function> defined @Interface\AddOns\Questie\Modules\Map\QuestieMap.lua:335
 ProcessQueue = <function> defined @Interface\AddOns\Questie\Modules\Map\QuestieMap.lua:243
 QueueDraw = <function> defined @Interface\AddOns\Questie\Modules\Map\QuestieMap.lua:232
 ProcessShownMinimapIcons = <function> defined @Interface\AddOns\Questie\Modules\Map\QuestieMap.lua:208
 ICON_MAP_TYPE = "MAP"
 GetFramesForQuest = <function> defined @Interface\AddOns\Questie\Modules\Map\QuestieMap.lua:61
 RescaleIcons = <function> defined @Interface\AddOns\Questie\Modules\Map\QuestieMap.lua:127
 InitializeQueue = <function> defined @Interface\AddOns\Questie\Modules\Map\QuestieMap.lua:149
 GetScaleValue = <function> defined @Interface\AddOns\Questie\Modules\Map\QuestieMap.lua:175
 _mapDrawQueue = <table> {
 }
 ICON_MINIMAP_TYPE = "MINIMAP"
}
mapId = 1414
scaling = 1
(*temporary) = nil
(*temporary) = "attempt to index field 'char' (a nil value)"
HBDPins = <table> {
 minimapPins = <table> {
 }
 SetMinimapObject

**Comment by Nerillida** [comment]
See issue 2829

**Comment by rbpaiett** [comment]
By troubleshooting, there seems to be a conflict between Questie & TitanClassicLocation.  The error can temporarily be stopped by disabling TitanClassicLocation while we wait for resolution.

**Comment by Nerillida** [comment]
Thanks

**Comment by BreakBB** [comment]
This is already fixed on master and will be included in the next release!

**Comment by throw-this-shit-away** [comment]
Very nice, thanks for the quick replies everyone!

**Comment by rbpaiett** [comment]
Excellent!
