### ISSUE TITLE
The Champion of the Horde: Rexxar no longer in Desolace (TBC Prepatch)

### ISSUE THREAD

**Issue by kevinganster** [Questie/Questie#2837]
# Bug description
The Quest "The Champion of the Horde" (Quest-ID 6567) for the Onyxia Attunement Chain still shows the old path of Rexxar in Desolace. Instead you now speak to an NPC in Shadowpray Village, since Rexxar is no longer in Desolace.

## Screenshots
![image](https://user-images.githubusercontent.com/8361636/119476394-4d7bf480-bd4e-11eb-8a85-35e811826bdb.png)

## Questie version
6.3.11

**Comment by drejjmit** [comment]
Thank you. 
Fixed with a4ab9612b96c9316a32780a5fc38cd3e9c87d2b8 and will be included in next release.
