### ISSUE TITLE
questie doesn't load with decursive loaded as well in BCC

### ISSUE THREAD

**Issue by odsblood** [Questie/Questie#2839]
I've recently updated both decursive and questie to the BCC versions but i can't use both addons at the same time.  If i load decrusive questie doesn't appear somehow they're conflicting with each other i'm not getting any error messages to post here sorry.  Just thought you should be made aware there is a conflict somewhere i'll also be posting this with the developers of decursive as well in hopes we can figure out how to get them to work together again. i'm running version v6.3.12 questie

**Comment by drejjmit** [comment]
Does it work with just Questie loaded? I loaded Decursive 2.7.8.2-bcc together with Questie v6.3.12 with no issues.

**Comment by odsblood** [comment]
just tried that and no with all addons turned off and only questie and decursive turned on i get decrusive only

**Comment by BreakBB** [comment]
@odsblood Can you try first to startup with just Questie (no Decursive) and if that works fine activate Decursive again?

You should also try to run `/console scriptErrors 1` to show possible errors after a `/reload`.
