### ISSUE TITLE
Interaction between Questie & TitanPanel Location module?

### ISSUE THREAD

**Issue by darvoso** [Questie/Questie#2845]
│   Up-to-date CF   │ Questie by Drejjmit, Dyaxler, Lawgon, The… │ v6.3.12 - Universal (TBC)    │
│   Up-to-date CF   │ Titan Panel Classic by HonorGoG, urnati    │ 1.3.1.20501

from swatter:
Date: 2021-05-26 16:36:22
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Questie\Modules\Map\QuestieMap.lua line 185:
   attempt to index field 'char' (a nil value)
Debug:
   [string "@Questie\Modules\Map\QuestieMap.lua"]:185: GetScaleValue()
   [string "@Questie\Modules\Map\QuestieMap.lua"]:201: OnMapChanged()
   [string "@Blizzard_MapCanvas\Blizzard_MapCanvas.lua"]:531: OnMapChanged()
   [string "@Blizzard_WorldMap\Blizzard_WorldMap.lua"]:121:
      ...rface\AddOns\Blizzard_WorldMap\Blizzard_WorldMap.lua:120
   [string "=[C]"]: OnMapChanged()
   [string "@Blizzard_MapCanvas\Blizzard_MapCanvas.lua"]:39: SetMapID()
   [string "@TitanClassicLocation\TitanClassicLocation.lua"]:75: TitanPanelLocationButton_OnShow()
   [string "*:OnShow"]:1:
      [string "*:OnShow"]:1
   [string "=[C]"]: Show()
   [string "@TitanClassic\TitanPanelClassic.lua"]:1475: TitanPanel_InitPanelButtons()
   [string "@TitanClassic\TitanClassicVariables.lua"]:1045: TitanVariables_UseSettings()
   [string "@TitanClassic\TitanPanelClassic.lua"]:400:
      TitanClassic\TitanPanelClassic.lua:327
   [string "=[C]"]: pcall()
   [string "@TitanClassic\TitanPanelClassic.lua"]:467: ?()
   [string "@TitanClassic\TitanPanelClassic.lua"]:309:
      TitanClassic\TitanPanelClassic.lua:308
Locals:
self = <table> {
 zoneWaypointColorOverrides = <table> {
 }
 ShowNPC = <function> defined @Interface\AddOns\Questie\Modules\Map\QuestieMap.lua:276
 GetManualFrames = <function> defined @Interface\AddOns\Questie\Modules\Map\QuestieMap.lua:96
 UnloadQuestFrames = <function> defined @Interface\AddOns\Questie\Modules\Map\QuestieMap.lua:74
 utils = <table> {
 }
 UnloadManualFrames = <function> defined @Interface\AddOns\Questie\Modules\Map\QuestieMap.lua:109
 GetNearestSpawn = <function> defined @Interface\AddOns\Questie\Modules\Map\QuestieMap.lua:772
 zoneWaypointHoverColorOverrides = <table> {
 }
 GetNearestQuestSpawn = <function> defined @Interface\AddOns\Questie\Modules\Map\QuestieMap.lua:806
 manualFrames = <table> {
 }
 private = <table> {
 }
 _minimapDrawQueue = <table> {
 }
 questIdFrames = <table> {
 }
 DrawWaypoints = <function> defined @Interface\AddOns\Questie\Modules\Map\QuestieMap.lua:890
 FindClosestStarter = <function> defined @Interface\AddOns\Questie\Modules\Map\QuestieMap.lua:652
 ResetManualFrames = <function> defined @Interface\AddOns\Questie\Modules\Map\QuestieMap.lua:119
 DrawWorldIcon = <function> defined @Interface\AddOns\Questie\Modules\Map\QuestieMap.lua:493
 DrawManualIcon = <function> defined @Interface\AddOns\Questie\Modules\Map\QuestieMap.lua:402
 DrawLineIcon = <function> defined @Interface\AddOns\Questie\Modules\Map\QuestieMap.lua:383
 ShowObject = <function> defined @Interface\AddOns\Questie\Modules\Map\QuestieMap.lua:335
 ProcessQueue = <function> defined @Interface\AddOns\Questie\Modules\Map\QuestieMap.lua:243
 QueueDraw = <function> defined @Interface\AddOns\Questie\Modules\Map\QuestieMap.lua:232
 ProcessShownMinimapIcons = <function> defined @Interface\AddOns\Questie\Modules\Map\QuestieMap.lua:208
 ICON_MAP_TYPE = "MAP"
 GetFramesForQuest = <function> defined @Interface\AddOns\Questie\Modules\Map\QuestieMap.lua:61
 RescaleIcons = <function> defined @Interface\AddOns\Questie\Modules\Map\QuestieMap.lua:127
 InitializeQueue = <function> defined @Interface\AddOns\Questie\Modules\Map\QuestieMap.lua:149
 GetScaleValue = <function> defined @Interface\AddOns\Questie\Modules\Map\QuestieMap.lua:175
 _mapDrawQueue = <table> {
 }
 ICON_MINIMAP_TYPE = "MINIMAP"
}
mapId = 1414
scaling = 1
(*temporary) = nil
(*temporary) = "attempt to index field 'char' (a nil value)"
HBDPins = <table> {
 minimapPins = <table> {
 }
 SetMinimapObject = <function> defined @Interface\AddOns\Questie\Libs\HereBeDragons\HereBeDragons-Pins-2.0.lua:656
 worldmapPinsPool = <table> {
 }
 RemoveMinimapIcon = <function> defined @Interface\AddOns\Questie\Libs\HereBeDragons\HereBeDragons-Pins-2.0.lua:630
 IsMinimapIconOnEdge = <function> defined @Interface\AddOns\Questie\Libs\HereBeDragons\HereBeDragons-Pins-2.0.lua:619
 Minimap = Minimap {
 }
 RemoveAllWorldMapIcons = <function> defined @Interface\AddOns\Questie\Libs\HereBeDragons\HereBeDragons-Pins-2.0.lua:778
 worldmapPins = <table> {
 }
 RemoveAllMinimapIcons = <function> defined @Interface\AddOns\Questie\Libs\HereBeDragons\HereBeDragons-Pins-2.0.lua:643
 worldmapProviderPin = <table> {
 }
 worldmapProvider = <table> {
 }
 updateFrame = <unnamed> {
 }
 GetVectorToIcon = <function> defined @Interface\AddOns\Questie\Libs\HereBeDragons\HereBeDragons-Pins-2.0.lua:793
 RemoveWorldMapIcon = <function> defined @Interface\AddOns\Questie\Libs\HereBeDragons\HereBeDragons-Pins-2.0.lua:764
 AddMinimapIconWorld = <function> defined @Interface\AddOns\Questie\Libs\HereBeDragons\HereBeDragons-Pins-2.0.lua:555
 AddMinimapIconMap = <function> defined @Interface\AddOns\Questie\Libs\HereBeDragons\HereBeDragons-Pins-2.0.lua:595
 AddWorldMapIconMap = <function> defined @Interface\AddOns\Questie\Libs\HereBeDragons\HereBeDragons-Pins-2.0.lua:724
 AddWorldMapIconWorld = <function> defined @Interface\AddOns\Questie\Libs\HereBeDragons\HereBeDragons-Pins-2.0.lua:683
 MinimapGroup = QuestieFrameGroup {
 }
 worldmapPinRegistry = <table> {
 }
 activeMinimapPins = <table> {
 }
 minimapPinRegistry = <table> {
 }
}

**Comment by BreakBB** [comment]
This has been fixed with 77dd3669bae41a137682d8064af9fad6dafd2d50 and e356efb5e4be4b5a3a7c3945493f35caac3f7318 and will be included in the next release (will come out shortly). Thanks for the report on this! 👍🏻
