### ISSUE TITLE
Belf/Draenei class started quests

### ISSUE THREAD

**Issue by Nerillida** [Questie/Questie#2850]
https://tbc.wowhead.com/quest=9279/you-survived 

is a breadcrumb to

https://tbc.wowhead.com/quest=9280/replenishing-the-healing-crystals

and is not available once 9280 is completed/in log

=====

https://tbc.wowhead.com/quest=9283/rescue-the-survivors

has as a prerequisite 

https://tbc.wowhead.com/quest=9409/urgent-delivery

Not sure if you have this as I can't fully grasp your data files

=====
the below
https://tbc.wowhead.com/quest=9289/warrior-training
https://tbc.wowhead.com/quest=9287/paladin-training
https://tbc.wowhead.com/quest=9288/hunter-training
https://tbc.wowhead.com/quest=9291/priest-training - started end ended by Zalduun (16502)
https://tbc.wowhead.com/quest=9421/shaman-training
https://tbc.wowhead.com/quest=9290/mage-training - started end ended by Valaatu )16500)

are all required race Draenei and appropriate classes (not faction), all have 

https://tbc.wowhead.com/quest=9280/replenishing-the-healing-crystals as a prerequisite
=====
Quest 8329 - Belf warrior training does not exist on Wowhead, nor should it.
=====
the below
https://tbc.wowhead.com/quest=9676/paladin-training
https://tbc.wowhead.com/quest=9393/hunter-training
https://tbc.wowhead.com/quest=9392/rogue-training
https://tbc.wowhead.com/quest=8564/priest-training
https://tbc.wowhead.com/quest=8328/mage-training
https://tbc.wowhead.com/quest=8563/warlock-training

are all required race Blood Elf and appropriate classes (not faction), all have 

https://tbc.wowhead.com/quest=8325/reclaiming-sunstrider-isle as a prerequisite

**Comment by drejjmit** [comment]
I believe all these are fixed in v6.3.13

**Comment by Cabro** [comment]
Necro revive, but [Warrior Training ](https://www.wowhead.com/wotlk/quest=9289/warrior-training) shows as available for non-draenei. Even if you already completed the race warrior quest already
