### ISSUE TITLE
Cloth turn ins

### ISSUE THREAD

**Issue by Nerillida** [Questie/Questie#2853]
6.3.12
• From https://tbc.wowhead.com/npc=14722/clavicus-knavingham
https://tbc.wowhead.com/quest=7795/a-donation-of-runecloth
has prerequisites of
https://tbc.wowhead.com/quest=7791/a-donation-of-wool
https://tbc.wowhead.com/quest=7793/a-donation-of-silk
https://tbc.wowhead.com/quest=7794/a-donation-of-mageweave
after one turn in opens
https://tbc.wowhead.com/quest=7796/additional-runecloth

•From https://tbc.wowhead.com/npc=14729/ralston-farnsley
https://tbc.wowhead.com/quest=7818/a-donation-of-runecloth#comments
has prerequisites of
https://tbc.wowhead.com/quest=7813/a-donation-of-wool
https://tbc.wowhead.com/quest=7814/a-donation-of-silk
https://tbc.wowhead.com/quest=7817/a-donation-of-mageweave
after one turn in opens
https://tbc.wowhead.com/quest=7819/additional-runecloth

• From https://tbc.wowhead.com/npc=14728/rumstag-proudstrider
https://tbc.wowhead.com/quest=7823/a-donation-of-runecloth
has prerequisites of
https://tbc.wowhead.com/quest=7820/a-donation-of-wool
https://tbc.wowhead.com/quest=7821/a-donation-of-silk
https://tbc.wowhead.com/quest=7822/a-donation-of-mageweave
after one turn in opens
https://tbc.wowhead.com/quest=7825/additional-runecloth

• From https://tbc.wowhead.com/npc=14725/raedon-duskstriker
https://tbc.wowhead.com/quest=7800/a-donation-of-runecloth
has prerequisites of
https://tbc.wowhead.com/quest=7792/a-donation-of-wool
https://tbc.wowhead.com/quest=7798/a-donation-of-silk
https://tbc.wowhead.com/quest=7799/a-donation-of-mageweave
after one turn in opens
https://tbc.wowhead.com/quest=7801/additional-runecloth

• From https://tbc.wowhead.com/npc=14723/mistina-steelshield
https://tbc.wowhead.com/quest=7805/a-donation-of-runecloth
has prerequisites of
https://tbc.wowhead.com/quest=7802/a-donation-of-wool
https://tbc.wowhead.com/quest=7803/a-donation-of-silk
https://tbc.wowhead.com/quest=7804/a-donation-of-mageweave
after one turn in opens
https://tbc.wowhead.com/quest=7806/additional-runecloth

• From https://tbc.wowhead.com/npc=14724/bubulo-acerbus
https://tbc.wowhead.com/quest=7811/a-donation-of-runecloth
has prerequisites of
https://tbc.wowhead.com/quest=7807/a-donation-of-wool
https://tbc.wowhead.com/quest=7808/a-donation-of-silk
https://tbc.wowhead.com/quest=7809/a-donation-of-mageweave
after one turn in opens
https://tbc.wowhead.com/quest=7812/additional-runecloth

• From https://tbc.wowhead.com/npc=14726/rashona-straglash
https://tbc.wowhead.com/quest=7824/a-donation-of-runecloth
has prerequisites of
https://tbc.wowhead.com/quest=7826/a-donation-of-wool
https://tbc.wowhead.com/quest=7827/a-donation-of-silk
https://tbc.wowhead.com/quest=7831/a-donation-of-mageweave
after one turn in opens
https://tbc.wowhead.com/quest=7832/additional-runecloth

• From https://tbc.wowhead.com/npc=14727/vehena
https://tbc.wowhead.com/quest=7836/a-donation-of-runecloth
has prerequisites of
1https://tbc.wowhead.com/quest=7833/a-donation-of-wool
https://tbc.wowhead.com/quest=7834/a-donation-of-silk
https://tbc.wowhead.com/quest=7835/a-donation-of-mageweave
after one turn in opens
https://tbc.wowhead.com/quest=7837/additional-runecloth

• From https://tbc.wowhead.com/npc=20604/dugiru
https://tbc.wowhead.com/quest=10357/a-donation-of-runecloth
has prerequisites of
https://tbc.wowhead.com/quest=10352/a-donation-of-wool 
https://tbc.wowhead.com/quest=10354/a-donation-of-silk
https://tbc.wowhead.com/quest=10356/a-donation-of-mageweave
after one turn in opens
https://tbc.wowhead.com/quest=10358/additional-runecloth

• From https://tbc.wowhead.com/npc=20612/sorim-lightsong
https://tbc.wowhead.com/quest=10362/a-donation-of-runecloth
has prerequisites of
https://tbc.wowhead.com/quest=10359/a-donation-of-wool
https://tbc.wowhead.com/quest=10360/a-donation-of-silk
https://tbc.wowhead.com/quest=10361/a-donation-of-mageweave
after one turn in opens
https://tbc.wowhead.com/quest=10363/additional-runecloth

NOTE 
Raedon Duskstriker and  Dugiru have their quest numbers corrected. Wowhead values are confused.

**Comment by Laumesis** [comment]
@Nerillida The NOTE is wrong. They do have quest ids non logically in TBCC live.
Who on their right mind would hijack old quest ids for new quests and then assign new quest ids for those old quests. >.<

I have never visited Exodar on this character and `/dump C_QuestLog.IsQuestFlaggedCompleted(10354)` returns true. The quest id is for Darnassus reputation like wowhead says. Also I have completed Darnassus rep ones before prepatch and quest id 7798 returns false for me.

I have completed non-repeatable ones for Darnassus and these are quest ids completed statuses:
10352 true
10354 true
7799 true
7800 true

And these are Exodar ones:
7792 false
7798 false
10356 false
10357 false

Looking comments for these quests in classic/tbcc wowhead and retail wowhead it seems Blizzard did this silly quest id swap also in original TBC.

So these match TBCC as correction for the original issue:

• From https://tbc.wowhead.com/npc=14725/raedon-duskstriker
https://tbc.wowhead.com/quest=7800/a-donation-of-runecloth
has prerequisites of
https://tbc.wowhead.com/quest=10352/a-donation-of-wool
https://tbc.wowhead.com/quest=10354/a-donation-of-silk
https://tbc.wowhead.com/quest=7799/a-donation-of-mageweave
after one turn in opens
https://tbc.wowhead.com/quest=7801/additional-runecloth

• From https://tbc.wowhead.com/npc=20604/dugiru
https://tbc.wowhead.com/quest=10357/a-donation-of-runecloth
has prerequisites of
https://tbc.wowhead.com/quest=7792/a-donation-of-wool
https://tbc.wowhead.com/quest=7798/a-donation-of-silk
https://tbc.wowhead.com/quest=10356/a-donation-of-mageweave
after one turn in opens
https://tbc.wowhead.com/quest=10358/additional-runecloth

As a bug: Quest ids 7792, 7798, 10352, 10354 are wrong in Questie v6.3.16 TBC. Note that 7792 and 7798 are correct in v6.3.16 Era.

**Comment by Laumesis** [comment]
Just to document: Wool, Silk, Mageweave turnins don't have each other pre-requirements.
![image](https://user-images.githubusercontent.com/75958501/130346907-2c4e38f5-dc02-45ae-838a-fe6484805aac.png)
