### ISSUE TITLE
Questie is not working at all.

### ISSUE THREAD

**Issue by heltenmin** [Questie/Questie#2855]
Have tried to reinstall it multiple times and manually install. still not working.
It shows up on my addon list, and its activated... but wont do anything.

**Comment by drejjmit** [comment]
Try ``Reset Questie`` in ``Questie Options > Advanced``
Try reinstall again with installation guide found here: https://github.com/Questie/Questie/wiki/Installation-Guide
There will also be an update out later today that may work you.
