### ISSUE TITLE
Tracker doesn't refresh text cut off

### ISSUE THREAD

**Issue by drejjmit** [Questie/Questie#2858]
Tracker resizes but doesn't refresh shortened text until you open/close the tracker.
Looks like it's using "Questie Tracker: 1/25" as a cut off.
Easy to reproduce if you have 0 quest and picks up your first quest.

![image](https://user-images.githubusercontent.com/15526476/119903807-8df39200-bf49-11eb-9b15-8762b6c3b8a0.png)

**Comment by Laumesis** [comment]
Can also be reproduced:
1.  Untrack **all** quests by shift-clicking tracked quests in quest log
2.  Questie options -> Tracker tab -> click `Auto Track Quests` off if it was on and then back on.

![image](https://user-images.githubusercontent.com/75958501/128762248-18eb8d70-8f86-42e9-8c49-a1fbb3e82d3f.png)
