### ISSUE TITLE
Minimap button can't be hidden / icon position isn't saved

### ISSUE THREAD

**Issue by waytoomuchgaming** [Questie/Questie#2860]
## Bug description
It came back after each reload.

## Questie version
6.3.13

**Comment by drejjmit** [comment]
Seems to affect both Classic Era and TBC

**Comment by alphabitnz** [comment]
+1 still having this issue even after deleting savedvariables file and starting with fresh config

**Comment by matthewhively** [comment]
> 
> 
> Also it doesnt retain previous set position on minimap

This is the more annoying part for me. I hope this gets fixed.

**Comment by karai17** [comment]
This is especially annoying now as it comes back every reload, but even before this it would come back every update. **I hide the icon for a reason, please do not *ever* display it again.**
