### ISSUE TITLE
Plater conflict

### ISSUE THREAD

**Issue by Marangwe** [Questie/Questie#2863]
## Bug description
11x Questie\Questie-6.3.13.lua:256: attempt to index field 'global' (a nil value)
[string "@Questie\Questie-6.3.13.lua"]:256: in function `Debug'
[string "@Questie\Modules\Tooltips\Tooltip.lua"]:97: in function `GetTooltip'
[string "@Plater\Plater-Plater-v330-BCC.lua"]:8457: in function `IsQuestObjective'
[string "@Plater\Plater-Plater-v330-BCC.lua"]:6891: in function `UpdatePlateFrame'
[string "@Plater\Plater-Plater-v330-BCC.lua"]:3539: in function `func'
[string "@Plater\Plater-Plater-v330-BCC.lua"]:3757: in function <Plater\Plater.lua:3753>

Locals:
self = <table> {
 SetDefaultModuleLibraries = <function> defined @Questie\Libs\AceAddon-3.0\AceAddon-3.0.lua:367
 _sessionWarnings = <table> {
 }
 modules = <table> {
 }
 CancelTimer = <function> defined @Ace3\AceTimer-3.0\AceTimer-3.0.lua:147
 IterateEmbeds = <function> defined @Questie\Libs\AceAddon-3.0\AceAddon-3.0.lua:442
 UnregisterComm = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 Warning = <function> defined @Questie\Questie.lua:249
 Printf = <function> defined @Ace3\AceConsole-3.0\AceConsole-3.0.lua:69
 SetDefaultModulePrototype = <function> defined @Questie\Libs\AceAddon-3.0\AceAddon-3.0.lua:409
 defaultModuleState = true
 IsEnabled = <function> defined @Questie\Libs\AceAddon-3.0\AceAddon-3.0.lua:451
 ScheduleTimer = <function> defined @Ace3\AceTimer-3.0\AceTimer-3.0.lua:94
 DisableModule = <function> defined @Questie\Libs\AceAddon-3.0\AceAddon-3.0.lua:350
 RegisterMessage = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 GetArgs = <function> defined @Ace3\AceConsole-3.0\AceConsole-3.0.lua:144
 RegisterBucketEvent = <function> defined @Ace3\AceBucket-3.0\AceBucket-3.0.lua:184
 SendCommMessage = <function> defined @Ace3\AceComm-3.0\AceComm-3.0.lua:87
 db = <table> {
 }
 UnregisterAllComm = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 SetEnabledState = <function> defined @Questie\Libs\AceAddon-3.0\AceAddon-3.0.lua:424
 enabledState = true
 RegisterEvent = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 ContinueInit = <function> defined @Questie\Questie.lua:122
 IterateModules = <function> defined @Questie\Libs\AceAddon-3.0\AceAddon-3.0.lua:437
 Colorize = <function> defined @Questie\Questie.lua:189
 OnInitialize = <function> defined @Questie\Questie.lua:116
 NewModule = <function> defined @Questie\Libs\AceAddon-3.0\AceAddon-3.0.lua:235
 GetClassColor = <function> defined @Questie\Questie.lua:219
 GetModule = <function> defined @Questie\Libs\AceAddon-3.0\AceAddon-3.0.lua:210
 IsClassic = false
 defaultModuleLibraries = <table> {
 }
 OnUpdate = <function> defined @Questie\Questie.lua:173
 Deserialize = <function> defined @Ace3\AceSerializer-3.0\AceSerializer-3.0.lua:246
 UnregisterChatCommand = <function> defined @Ace3\AceConsole-3.0\AceConsole-3.0.lua:111
 ScheduleRepeatingTimer = <function> defined @Ace3\AceTimer-3.0\AceTimer-3.0.lua:129
 CancelAllTimers = <function> defined @Ace3\AceTimer-3.0\AceTimer-3.0.lua:160
 GetName = <function> defined @Questie\Libs\AceAddon-3.0\AceAddon-3.0.lua:279
 name = "Questie"
 RegisterBucketMessage = <function> defined @Ace3\AceBucket-3.0\AceBucket-3.0.lua:200
 orderedModules = <table> {
 }
 Error = <function> defined @Questie\Questie.lua:245
 Disable = <function> defined @Questie\Libs\AceAddon-3.0\AceAddon-3.0.lua:314
 UnregisterBucket = <function> defined @Ace3\AceBucket-3.0\AceBucket-3.0.lua:206
 Print = <function> defined @Ace3\AceConsole-3.0\AceConsole-3.0.lua:54
 minimapConfigIcon = <table> {
 }
 IsModule = <function> defined @Questie\Libs\AceAddon-3.0\AceAddon-3.0.lua:468
 TBC_BETA_BUILD_VERSION_SHORTHAND = ""
 SendMessage = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:59
 baseName = "Questie"
 Enable = <function> defined @Questie\Libs\AceAddon-3.0\AceAddon-3.0.lua:294
 OnDisable = <function> defined @Questie\Questie.lua:181
 Serialize = <function> defined @Ace3\AceSerializer-

**Comment by drejjmit** [comment]
Duplicate #2843
