### ISSUE TITLE
2 The ''Chow'' Quests in Dustwallow Marsh

### ISSUE THREAD

**Issue by GitHubMan12345** [Questie/Questie#2864]
## Description
In the ''Quests by Zone'' section of Dustwallow Marsh, there are two quests called ''The ''Chow'' Quest'', which can't be found anywhere there. I'm seeing them on a freshly boosted character.

## Wowhead link
https://classic.wowhead.com/quest=1/the-chow-quest-123-aa

## Screenshots
![WoWScrnShot_052821_215241](https://user-images.githubusercontent.com/84990724/120029982-8b537400-bfff-11eb-9449-056891b6e613.jpg)

## Questie version
I'm using version 6.3.13

**Comment by drejjmit** [comment]
Thanks for the report. 
Fixed with https://github.com/Questie/Questie/commit/7c064227740182fcc948d4b77151ad176702dce1 and will be included in next release.
