### ISSUE TITLE
Draenei/Belf Classic starter quests

### ISSUE THREAD

**Issue by Nerillida** [Questie/Questie#2868]
See
#2850

You closed this with "I believe all these are fixed in v6.3.13"

No, they are not.
Draenei
The class quests still show (on the map) as available before the prerequisite is done.
They still do not show in the Quests by zone
Blood Elf
Class quests OK map-wise
They still do not show in the Quests by zone

Thanks

**Comment by drejjmit** [comment]
![image](https://user-images.githubusercontent.com/15526476/120046930-92847d00-c013-11eb-855b-5d26b85c4aae.png)
![image](https://user-images.githubusercontent.com/15526476/120046984-c069c180-c013-11eb-9292-57e424659349.png)
![image](https://user-images.githubusercontent.com/15526476/120047298-85b45900-c014-11eb-90ad-f90523b628a6.png)
![image](https://user-images.githubusercontent.com/15526476/120047377-b8f6e800-c014-11eb-8c72-613655283b3b.png)
![image](https://user-images.githubusercontent.com/15526476/120047457-ef346780-c014-11eb-90e0-10d779472200.png)
![image](https://user-images.githubusercontent.com/15526476/120047525-11c68080-c015-11eb-8005-fd0c33455ff8.png)

**Comment by Nerillida** [comment]
Yes, I looked.

**Comment by drejjmit** [comment]
They don't show up on the map for any of my characters except the ones i did "Replenishing the Healing Crystals" on.

**Comment by drejjmit** [comment]
Blood Elf:

![image](https://user-images.githubusercontent.com/15526476/120047712-8699ba80-c015-11eb-845e-b9bb2fe0ce61.png)

**Comment by Nerillida** [comment]
Alas, I checked with several characters, Draenei warrior, hunter, one other I forget.

No idea what's going on.

**Comment by drejjmit** [comment]
Hehe. Try recompile database in Questie Options > Advanced. Maybe it didn't rebuild database after you updated.

**Comment by Nerillida** [comment]
Thanks,
