### ISSUE TITLE
Hathvelion Sungaze listed twice

### ISSUE THREAD

**Issue by b-morgan** [Questie/Questie#2869]
## Description
Quests given by Hathvelion Sungaze (Eversong Woods, 30.24, 58.54) in BCC 
appear twice slightly offset from each other.

## Wowhead link
http://tbc.wowhead.com/quest=8885

## Screenshots
![WoWScrnShot_052821_165745](https://user-images.githubusercontent.com/1547854/120048990-e7a19e00-bfd5-11eb-8661-b41aa5f6635e.jpg)

## Questie version
6.3.13

**Comment by BreakBB** [comment]
This is because of the new minimap icons the default Blizzard UI has.

We need to adjust the spawn of the NPC to overlap the default icon.
