### ISSUE TITLE
Quests shows available after completion

### ISSUE THREAD

**Issue by rufio1337** [Questie/Questie#2870]
## Description
Quest "Cleaning up the Grounds" shows as available after completion. Logs show that, rather than completed, the quest was abandoned and re-accepted.

## Wowhead link
https://tbc.wowhead.com/quest=8894/cleaning-up-the-grounds

## Screenshots
![image](https://user-images.githubusercontent.com/20973820/120052294-d494cb00-bfe1-11eb-9c1c-e42f82ec94e8.png)

## Questie version
6.3.13

**Comment by rufio1337** [comment]
I've found a number of quests in the B.Elf starting area that appear to be logging as "abandoned" rather than "completed", so this is not limited to this single quest.

**Comment by drejjmit** [comment]
Use ``/reload`` for now. This is something we'll look in to after TBC release.
