### ISSUE TITLE
Quest 1132  Fiora Longears error

### ISSUE THREAD

**Issue by Nerillida** [Questie/Questie#2872]
Version 6.3.13

With quest https://tbc.wowhead.com/quest=1133/journey-to-astranaar in the log,

https://tbc.wowhead.com/quest=1132/fiora-longears is showing as available in Questie. It is not available. 
1132 a breadcrumb and its acquisition is blocked by 1133.

**Comment by drejjmit** [comment]
Same as with #2873. You need to turn in the quest for them to be flagged completed.
