### ISSUE TITLE
Error during initialization

### ISSUE THREAD

**Issue by juggernout3300** [Questie/Questie#2875]
Hello. Installed latest Questie (6.3.13 beta 6), and it doesnt initilize showing this error:

![изображение](https://user-images.githubusercontent.com/66667581/120072411-77aa1b00-c09c-11eb-8581-54fa2772ee06.png)

Maybe there is a way to fix it now? Thank you.

**Comment by cbollin** [comment]
Same error here, Questie unable to be interacted with on minimap as well
![image](https://user-images.githubusercontent.com/14946044/120084923-dfab3200-c099-11eb-8a36-00ea0243b192.png)

**Comment by drejjmit** [comment]
Exit WoW and delete ``Questie.lua`` and ``Questie.lua.bak`` in ``_classic_\WTF\Account\<ACCOUNT NAME>\SavedVariables``

**Comment by cbollin** [comment]
no luck with that method ![image](https://user-images.githubusercontent.com/14946044/120085372-3fefa300-c09d-11eb-800f-ce42e7e45d39.png)
![image](https://user-images.githubusercontent.com/14946044/120085377-4716b100-c09d-11eb-988d-7c914ae5eb90.png)

**Comment by drejjmit** [comment]
Try this in chat ``/run QuestieLoader:ImportModule("QuestieOptions").tabs.advanced:Initialize().args.questieReset.func()``

**Comment by cbollin** [comment]
That did the trick, thanks!

**Comment by Feper24** [comment]
> Try this in chat `/run QuestieLoader:ImportModule("QuestieOptions").tabs.advanced:Initialize().args.questieReset.func()`

Thanks a lot, I had another type of initialization issue and this solved it entirely.

Could you send this to the developer so he can include it in a future update or similar?

Thanks again.
