### ISSUE TITLE
Quest #10917 The Outcast's Plight does not have a max reputation limit

### ISSUE THREAD

**Issue by max-ri** [Questie/Questie#2876]
https://tbc.wowhead.com/quest=10917/the-outcasts-plight

This quest can be accepted even when Exalted with Lower City. Questie has a limit for this quest which apparently is incorrect and only applies to the repeatable version of the quest (https://tbc.wowhead.com/quest=10918/more-feathers).

![grafik](https://user-images.githubusercontent.com/51713394/120072718-7cb79c00-c095-11eb-9e54-d53590b9e00b.png)

**Comment by drejjmit** [comment]
6eb086d8762a5a39f7b23532833b1466cda7301a
