### ISSUE TITLE
Curseforge always shows Questie as "Modified"

### ISSUE THREAD

**Issue by puffybc** [Questie/Questie#2877]
Questie v6.3.13-TBC
Always shows as modified in Curseforge. Uninstalling/reinstalling doesn't fix. Seems to be functioning okay in game, but this bugs me because when Curseforge shows this it indicates a problem.
![2021-05-29](https://user-images.githubusercontent.com/85028326/120075724-719e4500-c070-11eb-8dde-0450a464f0c3.png)

**Comment by drejjmit** [comment]
Would make sense that Questie-v6.3.13-TBC.zip is modified from Questie-v6.3.12.zip. Not sure why it doesn't just show that an update is available.
