### ISSUE TITLE
ERROR lua 189

### ISSUE THREAD

**Issue by Hect016** [Questie/Questie#2878]
## Bug description
Error message shows up immediately when starting game. 
"?" on minimap is unclickable/non responsive in any way. 

Error during initialization! Interface\AddOns\Questie\Modules\QuestieInit.lua:189:bad argument #1 to 'pairs' (table expected, got nil)

## Questie version
Have tried both Questie v6.3.13 (Beta 6) and Questie Universal (TBC)
Same error code on both, no amount of /reloads fixes

##Screenshot
![WoWScrnShot_052921_103115](https://user-images.githubusercontent.com/85031146/120077871-d5713f80-c069-11eb-9303-75ef8b5b71bb.jpg)

**Comment by drejjmit** [comment]
Thanks for the report. Fixed with f813a7fd8825bdf02dd8a78e7abb0da87f840916
