### ISSUE TITLE
Questie Minimap Icon keeps appearing

### ISSUE THREAD

**Issue by ramboozer** [Questie/Questie#2879]
## Bug description
Anytime my UI Reloads Questie Icon is on my MiniMap with it being disabled in the Qustie Options

## Screenshots
https://puu.sh/HKHA2/3d9998e25d.png

## Questie version
v6.3.13

## Game Version
WoW TBC Pre-Patch

**Comment by MightBeChris** [comment]
Same.  Done everything I can.  The box is even still unchecked.  But the icon shows back up.  I ahve to enable, then disable to make it go away again.

**Comment by drejjmit** [comment]
We'll try to get it fix for next release. #2860.
