### ISSUE TITLE
Suggestion for the murloc heads quest in Dustwallow Marsh (Hungry!)

### ISSUE THREAD

**Issue by jimbology** [Questie/Questie#2880]
## Description

(Preface: I'm not sure if this is the addon guiding all these players here, but this is the most popular addon so it's most likely)

I'm a mage trying to aoe farm the murlocs on the island near Witch Hill in dustwallow marsh, and I know there's also a quest to kill those murlocs for their heads (Quest: Hungry! - Get 8 Mirefin Heads), but I'm running into an issue where i have random questers coming onto the island and only staying on the island and killing the mobs there, despite the same murlocs being found everywhere along that coast. Could a future update guide players to kill the mobs along the coast, instead of disrupting my grinding for 30 minutes to an hour at a time? It's really annoying.

Thanks in advance,

Nanami - Faerlina

**Comment by BreakBB** [comment]
Hey @jimbology 

I just checked our data and we are showing all the NPCs listed on this wowhead page: https://classic.wowhead.com/item=5847/mirefin-head

So Questie does not only list the NPCs on the island you as mage are farming on 😅
