### ISSUE TITLE
ALl of the sudden pretty much nothing works anymore for me

### ISSUE THREAD

**Issue by SledgeHammer87** [Questie/Questie#2881]
When I hover over a mob that I need to kill for a quest, it doesn't tell me this or anything else related to the quest (like the amount or the name of the quest) anymore. Also when I hover over quest items in my bag it doesn't tell me which quest exactly they are related to. Yesterday everything was ok, what has happened?

**Comment by drejjmit** [comment]
Try ``Rewat Questie`` in ``Questie Options > Advanced``

**Comment by SledgeHammer87** [comment]
Thanks, that did the trick. At least with new quest items I gain, this didn't change anything for the quest items I already owned, but that's alright. This also solved the issue with the nameplates, thanks again
