### ISSUE TITLE
Questie not honoring Minimap icon option

### ISSUE THREAD

**Issue by Jeremy7600** [Questie/Questie#2882]
Since Beta 6 Questie is on the Minimap despite "Enable Minimap button" UNCHECKED. Have unchecked and re-checked this option several times and saved and logged out. 

6.3.13 beta 6

**Comment by drejjmit** [comment]
It's currently not honoring that option. There's another issue wherer you can track progress of this bug. We'll try to get it sorted for next release. #2860
