### ISSUE TITLE
Questie Settings Revert to Default

### ISSUE THREAD

**Issue by alpturedi** [Questie/Questie#2883]
## Question
Everytime I close the client and login again, questie interface settings reset. More specifically I have to re-hide minimap icon everytime I login. Is it a know issue? Or is it a WoW issue? Thank you

## Questie version
v6.3.13
Client 2.5.1

**Comment by lynnrinkui** [comment]
I'm experiencing the same issue. Seems like a bug.

**Comment by drejjmit** [comment]
It's a know issue. Follow progress in issue #2860. We'll try to get it sorted for next release.
