### ISSUE TITLE
Heroes of Darrowshire 5168

### ISSUE THREAD

**Issue by Nerillida** [Questie/Questie#2884]
6.3.13
https://tbc.wowhead.com/quest=5168/heroes-of-darrowshire

You have this quest having a prerequisite of 

https://tbc.wowhead.com/quest=5211/defenders-of-darrowshire

I had it offered after turning in 

https://tbc.wowhead.com/quest=5241/uncle-carlin
and 
https://tbc.wowhead.com/quest=5210/brother-carlin

![Screen Shot 2021-05-30 at 20 56 28](https://user-images.githubusercontent.com/55858788/120118492-b74f3080-c18a-11eb-977d-c7207364d5da.png)

**Comment by drejjmit** [comment]
c4618c3c7dff97ea89131655b00b6bb153f4596b
