### ISSUE TITLE
Profession quests showing up in zone journals despite not having that profession

### ISSUE THREAD

**Issue by Cerby3BR** [Questie/Questie#2890]
Gonna put them here by zone:

Felwood
https://tbc.wowhead.com/quest=6032/sacred-cloth (tailoring)

Orgrimmar
https://classic.wowhead.com/quest=7493/the-journey-has-just-begun (leatherworking)

Stormwind
https://classic.wowhead.com/quest=7497/the-journey-has-just-begun (leatherworking)

Thunder Bluff
https://classic.wowhead.com/quest=768/gathering-leather (skinning)
https://classic.wowhead.com/quest=769/kodo-hide-bag (leatherworking)

Winterspring
https://classic.wowhead.com/quest=8798/a-yeti-of-your-own (engineering)
https://classic.wowhead.com/quest=5126/loraxs-tale (blacksmithing)
https://classic.wowhead.com/quest=5124/fiery-plate-gauntlets (blacksmithing)

Blackrock Depths
https://classic.wowhead.com/quest=4083/the-spectral-chalice (mining)

Blackrock Spire
https://classic.wowhead.com/quest=5127/the-demon-forge (blacksmithing)

Version 6.3.14

**Comment by BreakBB** [comment]
This should be fixed with 29ef101fe3cff7d44425bf577c61936a2a7d2347 Feel free to open up a new issue after v6.5.0 has released and this is still an issue
