### ISSUE TITLE
All six [Well Watcher Solanian] showing up for my tauren druid despite them being both belf- and class-exclusive

### ISSUE THREAD

**Issue by Cerby3BR** [Questie/Questie#2891]
These are part of the belf beginner's guide quests and are completely unavailable to all other races.

https://tbc.wowhead.com/quest=10068/well-watcher-solanian (mage)
https://tbc.wowhead.com/quest=10069/well-watcher-solanian (paladin)
https://tbc.wowhead.com/quest=10070/well-watcher-solanian (priest)
https://tbc.wowhead.com/quest=10071/well-watcher-solanian (rogue)
https://tbc.wowhead.com/quest=10072/well-watcher-solanian (hunter)
https://tbc.wowhead.com/quest=10073/well-watcher-solanian (warlock)

Version 6.3.14

**Comment by drejjmit** [comment]
db0e62428a821a753c36ce1ec4f0740c3b7a9f66
