### ISSUE TITLE
Journal confusion about the boostie questline

### ISSUE THREAD

**Issue by Cerby3BR** [Questie/Questie#2892]
The Journal seems to think it is available for all and goes something like this (for all three cities in which it is available, aka Thunder Bluff, Stormwind and Orgrimmar):

A New Beginning (not actually in the Journal for some reason)
->
Tools for Survival
->
Combat Training
->
Talented
->
Eastern Plaguelands & The Dark Portal

In reality, The Dark Portal is *not* part of that questline, and the questline is only available to boosted characters, as the first quest is an auto-accept upon logging on after boosting to level 58.

So:
Stormwind
https://tbc.wowhead.com/quest=64028/a-new-beginning
https://tbc.wowhead.com/quest=64031/tools-for-survival
https://tbc.wowhead.com/quest=64034/combat-training
https://tbc.wowhead.com/quest=64035/talented
https://tbc.wowhead.com/quest=64037/eastern-plaguelands

Orgrimmar:
https://tbc.wowhead.com/quest=64046/a-new-beginning
https://tbc.wowhead.com/quest=64048/tools-for-survival
https://tbc.wowhead.com/quest=64050/combat-training
https://tbc.wowhead.com/quest=64052/talented
https://tbc.wowhead.com/quest=64064/eastern-plaguelands

Thunder Bluff:
https://tbc.wowhead.com/quest=64047/a-new-beginning
https://tbc.wowhead.com/quest=64049/tools-for-survival
https://tbc.wowhead.com/quest=64051/combat-training
https://tbc.wowhead.com/quest=64053/talented
https://tbc.wowhead.com/quest=64128/eastern-plaguelands
are all only available to boosted characters (with the Thunder Bluff line being specifically for druids and the Orgrimmar one being for non-druids, as Orgrimmar lacks a druid trainer).

Meanwhile,
https://tbc.wowhead.com/quest=64038/the-dark-portal (Alliance)
https://tbc.wowhead.com/quest=64063/the-dark-portal (Horde)
https://tbc.wowhead.com/quest=64217/the-dark-portal (Horde as well??? seems to be depreciated)
are part of the questline that brings us to Outland once TBC finally drops, and have nothing to do with the Talented quest like Questie seems to think.

Version 6.3.14

**Comment by BreakBB** [comment]
@Cabro @MyTechnoHunter these are all fixed already, aren't they?

**Comment by Cabro** [comment]
These ids should be fixed, yes. Also the 70000 range ids. The newest boost quests however, are not.
