### ISSUE TITLE
when the addon is activated, the right mouse button starts to stick

### ISSUE THREAD

**Issue by Kojeed** [Questie/Questie#2895]

**Comment by Kojeed** [comment]
you can't move the camera

**Comment by drejjmit** [comment]
We only add pins to the map. We don't change anything in the world frame.
Is it the same with only Questie active?

**Comment by Kojeed** [comment]
Yes, only when Questie is turned on, when the addon is turned off, everything works well. It started 2 days ago. I have already reinstalled the addon several times

**Comment by drejjmit** [comment]
Try ``Reset Questie`` in ``Questie Options > Advanced``

**Comment by Kojeed** [comment]
Thank you very much. It seemed to help
