### ISSUE TITLE
[13] Vanquishing Aquantion

### ISSUE THREAD

**Issue by shadospike** [Questie/Questie#2896]
Quest in the Ghostlands given by Geranis Whitemorn on the island in Lake Elrendar. Still shows as available directly after completion.

![](https://media.discordapp.net/attachments/380905164774703115/849240294707953694/unknown.png)

**Comment by drejjmit** [comment]
Does it disapperad if you ``/reload``?

**Comment by shadospike** [comment]
Unfortunately I hid it manually after submitting this, how do I unhide to check that?

**Comment by drejjmit** [comment]
Go to Questie Journey ( ``/questie journey`` ) > ``Advanced Search`` and Search for the quest. Then uncheck Hidden. 

![image](https://user-images.githubusercontent.com/15526476/120317776-57b66980-c2df-11eb-908d-942d5ab8f4c8.png)

Does it say Completed?

**Comment by shadospike** [comment]
Ah, it does. Okay, good to know that I should simply reload in this scenario. Thank you for the help.
![image](https://user-images.githubusercontent.com/71995413/120319449-a4ca1980-c2a6-11eb-8a37-8be50e708275.png)
