### ISSUE TITLE
Questie: [ERROR] [QuestieTracker] 261 is an unknown uiMapId 

### ISSUE THREAD

**Issue by Lebaowski** [Questie/Questie#2898]
Description
Whenever I loot something, accept or turn in any quest in outland, track/untrack or show/hide the questie tracker the error "Questie: [ERROR] [QuestieTracker] 261 is an unknown uiMapId " pops up in chat. The map ID is for Blood Furnace according to wowpedia. No one else is experiencing this bug as far as I've been able to tell.

Version
Questie v6.3.14

I can add a screenshot if needed but theres not much to screenshot besides the error message I get in chat.

**Comment by Jahum** [comment]
Same issue here except the number is different. We're in Hellfire/Zangarmarsh and the error gets spammed so often the game's FPS is effected. Rebooting fixes FPS for an hour or so.
Questie: [ERROR] [QuestieTracker] 247 is an unknown uiMapId

**Comment by Lebaowski** [comment]
247 seems to be Ruins of Ahn'Qiraj. Maybe this is from a quest we have in our log? I have 2 blood furnace quests active atm.

**Comment by Jahum** [comment]
There are definitely no AQ quests in my quest log, not sure why it'd be saying that

**Comment by Lebaowski** [comment]
Stopped for me after turning in my 2 quests in Blood Furnace. Can't say which of the two available quests for the dungeon caused the issue.

**Comment by Doxxer** [comment]
Same for me, but zone=347
Related to quest=9575

**Comment by drejjmit** [comment]
Weird. I had no errors with quest=9575 (Weaken the Ramparts).
Tried both inside and outside the dungeon.
If a dungeon quests gives you problems, wait until you're doing the dungeons.
We'll try to get a fix out for next release for those who have issues.

**Comment by Lebaowski** [comment]
Issue came back once I entered Zangarmarsh. Questie Options > Advanced > Reset Questie did not solve the issue. uiMapId is now 262, Underbog. Most likely connected to quest=9738 (Lost in Action).

**Comment by drejjmit** [comment]
It has to do with being on a new dungeon quest while using ``Objective Sorting`` > ``By Proximity`` in ``Questie Options`` > ``Tracker``. 
For now: Change to another sorting or abandon that dungeon quest until you're doing that dungeon.
We'll try to have a fix out for next release.
Thanks for the reports.

**Comment by gaymer77** [comment]
I've been getting the "265 is unknown uiMapId" error in Hellfire, Zangermarsh, Org, and Shat in addition to UB too.  Only quests in my log are the Zangermarsh quests.  I did have the Lost In Action quest in my log but have since completed it but I'm still getting this error.  I've tried reverting back to the 5/27 version of Questie but that did not fix it.

**Comment by drejjmit** [comment]
> I've been getting the "265 is unknown uiMapId" error in Hellfire, Zangermarsh, Org, and Shat in addition to UB too. Only quests in my log are the Zangermarsh quests. I did have the Lost In Action quest in my log but have since completed it but I'm still getting this error. I've tried reverting back to the 5/27 version of Questie but that did not fix it.

There is a work around in the poste above yours.

**Comment by Calcole** [comment]
I arrived in the Zangermarsh (Everlook) today. Suddenly the error occurs: "347 is an unknown uiMapID". Any ideas?
Maybe I should delete one quest at a time and see if the error stops after one...

**Comment by drejjmit** [comment]
Fixed in [v6.3.15](https://github.com/Questie/Questie/releases)
