### ISSUE TITLE
"Into the Breach" (10259) should be removed?

### ISSUE THREAD

**Issue by reticentae** [Questie/Questie#2902]
v6.3.14 - Universal(TBC)

This quest doesn't seem to exist in the current tbc classic release, but questie still shows a marker for it.

**Comment by drejjmit** [comment]
It was the pre quest for Tabard. We haven't released a new version since pre patch

**Comment by drejjmit** [comment]
13d41b2982fb06211a68b2ffe5ec39fddcd29648

**Comment by Alessandro-Barbieri** [comment]
This issue is up again for tbc anniversary
