### ISSUE TITLE
Questie: [ERROR] [QuestieTracker] 347 is an unknown uiMapId

### ISSUE THREAD

**Issue by neverke1** [Questie/Questie#2903]
## Bug description
I just log in and then my chat is spawned with this error.

## Screenshots
![image](https://user-images.githubusercontent.com/68199224/120568039-669e3880-c413-11eb-83f5-10018007f514.png)

## Questie version
v6.3.14

**Comment by drejjmit** [comment]
It has to do with being on a new dungeon quest while using ``Objective Sorting`` > ``By Proximity`` in ``Questie Options`` > ``Tracker``. 
For now: Change to another sorting or abandon that dungeon quest until you're doing that dungeon.
We'll try to have a fix out for next release.
Thanks for the reports.

**Comment by drejjmit** [comment]
Fixed in [v6.3.15](https://github.com/Questie/Questie/releases)
