### ISSUE TITLE
Couple Thousand Needles Quests Not Disappearing on Completion

### ISSUE THREAD

**Issue by Bellidrael** [Questie/Questie#2905]
## Bug description
Turned in two quests around the same time in Thousand Needles - Freewind Post. The first is Alien Egg, and the second is Free at Last. It seems that when I turned the quests in, Questie marked them as abandoned, instead of completed, and so despite me having completed the quests it kept them marked on the map as available to be picked up. I have screenshots showing both quests completed in the chat window. 

## Screenshots
![WoWScrnShot_060321_142312](https://user-images.githubusercontent.com/85317575/120714176-b7e01380-c477-11eb-951e-dbf85ad51dec.jpg)
![WoWScrnShot_060321_142305](https://user-images.githubusercontent.com/85317575/120714178-b878aa00-c477-11eb-8b52-3fbf410fa3ab.jpg)
![WoWScrnShot_060321_142846](https://user-images.githubusercontent.com/85317575/120714426-05f51700-c478-11eb-86e2-e8e39ba2db14.jpg)
![WoWScrnShot_060321_142848](https://user-images.githubusercontent.com/85317575/120714429-068dad80-c478-11eb-8f4d-a200c40a558d.jpg)

## Questie version
v6.3.14

**Comment by NeutyBooty** [comment]
I'm not a developer, but a quick suggestion - try reloading Questie by performing Ctrl + Left click on the Questie icon by your mini-map. Has worked for me in the past when Questie did not update following quest completions.

**Comment by BreakBB** [comment]
Yes, Questie sometimes gets "desynced" and forgets that you already completed a quest. This only persists in the current session though and is very hard for us to debug.

You should always try a `/reload` and see if that fixes it.

We are looking into this and hope to fix it soon.
