### ISSUE TITLE
Some Horde Quests in BEM giving "There was an error populating objectives for [Quest]"

### ISSUE THREAD

**Issue by Prefo** [Questie/Questie#2909]
Hello,

doing the Horde Quest "Trial and Error", i encountered a bug. For the Quest, you have to use 4 different Wands, from your bag, onto mobs to test them. Everytime doing so, the following error message appears in chat. furthermore, the objectives dont show up in the tooltips of the mobs, you have to use the wands on.

[09:10] ...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:690: bad argument #1 to 'next' (table expected, got nil) 
 [09:10] [string "@Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua"]:556: in function <...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:554>
[string "=[C]"]: in function `next'
[string "@Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua"]:690: in function <...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:683>
[string "=[C]"]: in function `xpcall'
[string "@Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua"]:554: in function `UpdateObjectiveNotes'
[string "@Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua"]:469: in function `UpdateQuest'
[string "@Interface\AddOns\Questie\Modules\Libs\QuestieHash.lua"]:108: in function <...nterface\AddOns\Questie\Modules\Libs\QuestieHash.lua:103>
[string "@Interface\AddOns\Questie\Modules\Libs\QuestieHash.lua"]:91: in function `CompareQuestHashes'
[string "@Interface\AddOns\Questie\Modules\QuestieEventHandler.lua"]:296: in function <...rface\AddOns\Questie\Modules\QuestieEventHandler.lua:278>
[string "=[C]"]: ?
[string "@Interface\AddOns\Questie\Libs\AceBucket-3.0\AceBucket-3.0.lua"]:73: in function <...\AddOns\Questie\Libs\AceBucket-3.0\AceBucket-3.0.lua:71>
[string "@Interface\AddOns\Questie\Libs\AceBucket-3.0\AceBucket-3.0.lua"]:89: in function `func'
[string "@Interface\AddOns\ElvUI\Libraries\Ace3\AceTimer-3.0\AceTimer-3.0.lua"]:57: in function <...s\ElvUI\Libraries\Ace3\AceTimer-3.0\AceTimer-3.0.lua:50>
 
 [09:10] ...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:690: bad argument #1 to 'next' (table expected, got nil) 
 [09:10] [string "@Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua"]:556: in function <...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:554>
[string "=[C]"]: in function `next'
[string "@Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua"]:690: in function <...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:683>
[string "=[C]"]: in function `xpcall'
[string "@Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua"]:554: in function `UpdateObjectiveNotes'
[string "@Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua"]:469: in function `UpdateQuest'
[string "@Interface\AddOns\Questie\Modules\Libs\QuestieHash.lua"]:108: in function <...nterface\AddOns\Questie\Modules\Libs\QuestieHash.lua:103>
[string "@Interface\AddOns\Questie\Modules\Libs\QuestieHash.lua"]:91: in function `CompareQuestHashes'
[string "@Interface\AddOns\Questie\Modules\QuestieEventHandler.lua"]:296: in function <...rface\AddOns\Questie\Modules\QuestieEventHandler.lua:278>
[string "=[C]"]: ?
[string "@Interface\AddOns\Questie\Libs\AceBucket-3.0\AceBucket-3.0.lua"]:73: in function <...\AddOns\Questie\Libs\AceBucket-3.0\AceBucket-3.0.lua:71>
[string "@Interface\AddOns\Questie\Libs\AceBucket-3.0\AceBucket-3.0.lua"]:89: in function `func'
[string "@Interface\AddOns\ElvUI\Libraries\Ace3\AceTimer-3.0\AceTimer-3.0.lua"]:57: in function <...s\ElvUI\Libraries\Ace3\AceTimer-3.0\AceTimer-3.0.lua:50>
 
 [09:10] ...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:690: bad argument #1 to 'next' (table expected, got nil) 
 [09:10] [string "@Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua"]:556: in function <...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:554>
[string "=[C]"]: in function `next'
[string "@Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua"]:690: in function <...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:683>
[string "=[C]"]: in function `xpcall'
[string "@Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua"]:554: in function `UpdateObjectiveNotes'
[string "@Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua"]:469: in function `UpdateQuest'
[string "@Interface\AddOns\Questie\Modules\Libs\QuestieHash.lua"]:108: in function <...nterface\AddOns\Questie\Modules\Libs\QuestieHash.lua:103>
[string "@Interface\AddOns\Questie\Modules\Libs\QuestieHash.lua"]:91: in function `CompareQuestHashes'
[string "@Interface\AddOns\Questie\Modules\QuestieEventHandler.lua"]:296: in function <...rface\AddOns\Questie\Modules\QuestieEventHandler.lua:278>
[string "=[C]"]: ?
[string "@Interface\AddOns\Questie\Libs\AceBucket-3.0\AceBucket-3.0.lua"]:73: in function <...\AddOns\Questie\Libs\AceBucket-3.0\AceBucket-3.0.lua:71>
[string "@Interface\AddOns\Questie\Libs\AceBucket-3.0\AceBucket-3.0.lua"]:89: in function `func'
[string "@Interface\AddOns\ElvUI\Libraries\Ace3\AceTimer-3.0\AceTimer-3.0.lua"]:57: in function <...s\ElvUI\Libraries\Ace3\AceTimer-3.0\AceTimer-3.0.lua:50>
 
 [09:10] Questie: [ERROR] [QuestieQuest]: [Tooltips] There was an error populating objectives for Test the fourth wand 10566 0 No error 
 [09:10] ...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:773: bad argument #1 to 'next' (table expected, got nil) 
 [09:10] [string "@Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua"]:556: in function <...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:554>
[string "=[C]"]: in function `next'
[string "@Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua"]:773: in function <...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:772>
[string "@Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua"]:710: in function <...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:683>
[string "=[C]"]: in function `xpcall'
[string "@Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua"]:554: in function `UpdateObjectiveNotes'
[string "@Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua"]:469: in function `UpdateQuest'
[string "@Interface\AddOns\Questie\Modules\Libs\QuestieHash.lua"]:108: in function <...nterface\AddOns\Questie\Modules\Libs\QuestieHash.lua:103>
[string "@Interface\AddOns\Questie\Modules\Libs\QuestieHash.lua"]:91: in function `CompareQuestHashes'
[string "@Interface\AddOns\Questie\Modules\QuestieEventHandler.lua"]:296: in function <...rface\AddOns\Questie\Modules\QuestieEventHandler.lua:278>
[string "=[C]"]: ?
[string "@Interface\AddOns\Questie\Libs\AceBucket-3.0\AceBucket-3.0.lua"]:73: in function <...\AddOns\Questie\Libs\AceBucket-3.0\AceBucket-3.0.lua:71>
[string "@Interface\AddOns\Questie\Libs\AceBucket-3.0\AceBucket-3.0.lua"]:89: in function `func'
[string "@Interface\AddOns\ElvUI\Libraries\Ace3\AceTimer-3.0\AceTimer-3.0.lua"]:57: in function <...s\ElvUI\Libraries\Ace3\AceTimer-3.0\AceTimer-3.0.lua:50>

Edit: Another Quest seems to give me the same Error (On Spirit's Winds)

 [09:43] Questie: [ERROR] [QuestieQuest]: [Tooltips] There was an error populating objectives for Eavesdrop on the Bloodmaul ogres' plans 10714 0 No error 
 [09:43] ...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:726: bad argument #1 to 'next' (table expected, got nil) 
 [09:43] [string "@Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua"]:968: in function <...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:966>
[string "=[C]"]: in function `next'
[string "@Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua"]:726: in function <...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:683>
[string "=[C]"]: in function `xpcall'
[string "@Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua"]:966: in function <...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:964>
[string "@Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua"]:1019: in function `PopulateObjectiveNotes'
[string "@Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua"]:509: in function `GetAllQuestIds'
[string "@Interface\AddOns\Questie\Modules\QuestieInit.lua"]:148: in function <Interface\AddOns\Questie\Modules\QuestieInit.lua:45>
 
 [09:43] Questie: [ERROR] [QuestieQuest]: v6.3.14 - There was an error populating objectives for On Spirit's Wings 10714 1 No error 

Im using Version 6.3.14, did a relog and a /rl.

Greetings,
Prefo

**Comment by drejjmit** [comment]
Fixed in [v6.3.15](https://github.com/Questie/Questie/releases)
