### ISSUE TITLE
Four "Available" quests in 'Quests by Zone' (My Journey) actually have profession pre-reqs

### ISSUE THREAD

**Issue by NeutyBooty** [Questie/Questie#2910]
In clearing out the quests in the 'Quests by Zone' tab of 'My Journey', I have so far encountered three quests marked as 'Available' in their respective zones that I have discovered actually have profession requirements upon further research:

**Quest ID 768: Gathering Leather (_Thunder Bluff_)** - Requires skinning. Stated specifically at the top of the Wowhead Classic entry (Quick Facts - Profession: Skinning). Comments seem to indicate that minimum skinning level is 5.

https://classic.wowhead.com/quest=768/gathering-leather

**Quest ID 5126: Lorax's Tale (_Winterspring_)** - Requires blacksmithing. Not confirmed directly on Wowhead Classic entry, but comments speculate _at least_ level 275 blacksmithing is required (precise level minimum is not indicated in entry or comments). 

https://classic.wowhead.com/quest=5126/loraxs-tale

**Quest ID 4083: The Spectral Chalice (_Blackrock Depths_)** - Requires mining. Not confirmed directly on Wowhead Classic entry, but comments speculate that minimum mining level is 230 (level requirement to mine Dark Iron).

https://classic.wowhead.com/quest=4083/the-spectral-chalice#comments

Does Questie have any feature to indicate profession level requirements for each quest like it does minimum level? It would make sense to me to mark these quests as "Unobtainable" in their respective zones if the profession pre-requisite is not met.

Likewise, I see that there is also a "Professions" menu in 'Quests by Zone' - wouldn't it make more sense for these quests be sorted into their specific profession lists?

_Bug reported using **Questie v6.3.14** in **The Burning Crusade Classic** client._

**Comment by NeutyBooty** [comment]
An additional quest discovered with profession pre-requisite.

**Quest ID 8798: A Yeti of Your Own (_Winterspring_):** Requires engineering. Quest text referenced from the Wowhead page states "Say! You know what?! You're **_an engineer_** too!". Minimum engineering level is indicated on Wowpedia as 250.

https://classic.wowhead.com/quest=8798/a-yeti-of-your-own
https://wowpedia.fandom.com/wiki/A_Yeti_of_Your_Own

**Comment by NeutyBooty** [comment]
UPDATE: Wowpedia entry for **Quest ID 4083: "The Spectral Chalice"** confirms minimum mining level required as **230**:

https://wowpedia.fandom.com/wiki/The_Spectral_Chalice

**Comment by NeutyBooty** [comment]
Is this issue report misformatted or bad in some way? Haven't seen any response on it so far.

**Comment by BreakBB** [comment]
Hey @NeutyBooty sorry for not responding to this earlier.

No, the report is perfectly fine! We just had a pretty stressful TBC release and are more than understaffed to check all the issues coming in "soon".

I adjusted the "Profession" section of Quests by Zone to also filter all quests which have a `requiredSkill` listed in this commit: 29ef101fe3cff7d44425bf577c61936a2a7d2347

It would be great if you could counter check the quests you listed here after the release of v6.5.0 (which will be released in the next few days!)

**Comment by NeutyBooty** [comment]
Ah of course, I forgot I had reported this right after TBC launch. Nonetheless, I'm even more grateful you returned to this issue after so long. The fact that you all support this as a volunteer project is incredible. Questie is pretty much the best AddOn for WoW, hands down. It's not even the same game without it. Very cool to see the code changes being made as well.

I will gladly validate the changes once v6.5.0 releases.

**Comment by BreakBB** [comment]
Thanks, that is a very kind response of you @NeutyBooty ❤️

**Comment by BreakBB** [comment]
Hey @NeutyBooty did you find time to check the changes of v6.5.0 and v6.5.1 towards this issue?

**Comment by NeutyBooty** [comment]
I was just thinking about this the other day and how I needed to check. I saw that one or two of them were correctly allocated but did will correctly validate them all on Saturday if that works for you.

**Comment by NeutyBooty** [comment]
You folks can close this one out. I've verified that all of the four quests mentioned above no longer appear in their respective Zones. I do not have the above professions so cannot verify that they now appear under their respective Professions menu, however.

**Comment by BreakBB** [comment]
Thank you very much for coming back to this @NeutyBooty 🙏🏻 Feel free to open a new issue if anything comes up again 👍🏻
