### ISSUE TITLE
[Feature Request] Quest Announce default OFF 

### ISSUE THREAD

**Issue by Ischtaratu** [Questie/Questie#2911]
Since the launch of Burning Crusade Classic, hundreds and thousands of players are on the move. Rows and rows of quests are completed and tasks are finished.

The fact that the quest announcement is active by default, and the players of course do not turn it off, the quest progress is constantly and repeatedly posted in all chats.

I understand the purpose of this feature. But it should not be active by default. Meanwhile, it simply disturbs and gives neither absolutely necessary, nor useful information.

This function is good as it is, but should not be active by default !

**Comment by Iowerth** [comment]
Already exists https://github.com/Questie/Questie/issues/2897

**Comment by BreakBB** [comment]
Merging this with the linked issue.
