### ISSUE TITLE
My questie doesn't show up for my warrior, I have tried resetting questie but it didn't work.  The add on doesn't even show as being installed when I log into the warrior but it works for every other character.

### ISSUE THREAD

**Issue by wyspir1566** [Questie/Questie#2912]

**Comment by BreakBB** [comment]
Join our Discord channel and follow the install guide posted in the #download-questie channel.

If Questie does not show up in your ingame Addon list you either didn't install it correctly or didn't restart the game after installing Questie.

If the guide doesn't help you feel free to open up a new issue and include the required information.
