### ISSUE TITLE
Questie Tracker always resets its position on login

### ISSUE THREAD

**Issue by Darangen** [Questie/Questie#2915]
Whenever I log in, Questie always resets the tracker position to an area half off of the screen.  I have to move it every time I log in or reload the ui.

Is there a fix for this? Or some setting I'm missing?

**Comment by BreakBB** [comment]
You should try `/questie` -> Tracker -> "Reset Tracker position".

Also try to play a bit with the UI scaling in the default Blizzard settings.

**Comment by BreakBB** [comment]
Closing this as it doesn't seem to be an issue any longer.
