### ISSUE TITLE
Questie error for the quest Gorgrom the dragon-Eater

### ISSUE THREAD

**Issue by Thaowyr** [Questie/Questie#2916]
Hi, using questie 6.3.14

Got mass error when accepting Gorgrom the dragon-Eater in blades edge.

Questie: [ERROR] [QuestieQuest]: v6.3.14 - There was an error populating objectives for Gorgrom the Dragon-Eater 

10723 1 No error
...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:690: bad argument #1 to 'next' (table expected, got nil)
[string "@Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua"]:556: in function <...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:554>
[string "=[C]"]: in function `next'
[string "@Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua"]:690: in function <...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:683>
[string "=[C]"]: in function `xpcall'
[string "@Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua"]:554: in function `UpdateObjectiveNotes'
[string "@Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua"]:469: in function `UpdateQuest'
[string "@Interface\AddOns\Questie\Modules\Libs\QuestieHash.lua"]:108: in function <...nterface\AddOns\Questie\Modules\Libs\QuestieHash.lua:103>
[string "@Interface\AddOns\Questie\Modules\Libs\QuestieHash.lua"]:91: in function `CompareQuestHashes'
[string "@Interface\AddOns\Questie\Modules\QuestieEventHandler.lua"]:296: in function <...rface\AddOns\Questie\Modules\QuestieEventHandler.lua:278>
[string "=[C]"]: ?
[string "@Interface\AddOns\Quartz\libs\AceBucket-3.0\AceBucket-3.0.lua"]:73: in function <...e\AddOns\Quartz\libs\AceBucket-3.0\AceBucket-3.0.lua:71>
[string "@Interface\AddOns\Quartz\libs\AceBucket-3.0\AceBucket-3.0.lua"]:89: in function `func'
[string "@Interface\AddOns\Details\Libs\AceTimer-3.0\AceTimer-3.0.lua"]:57: in function <...ce\AddOns\Details\Libs\AceTimer-3.0\AceTimer-3.0.lua:50>

**Comment by furydeath9** [comment]
Same I get a LOT of this in blade's edge quests

**Comment by drejjmit** [comment]
Fixed in [v6.3.15](https://github.com/Questie/Questie/releases)
