### ISSUE TITLE
Questie not showing icons on Outlands Map

### ISSUE THREAD

**Issue by Teqtotem** [Questie/Questie#2917]
I found an issue with Questie not showing icons out the outlands map.  Ive had no issues until today. No settings changed.  I logged in and they werent appearing.  I've tried changing settings in the addon, toggling the on off on the map. reinstalling from curseforge and manually installing, using /reload. I dropped any recent quests I picked up incase there was an issue with no changes and I turned off all other addons except for questie with no changes.  It's showing items for me in the old world, but nothing at all in Outland.  Any further advice or troubleshooting methods are appreciated.

**Comment by BreakBB** [comment]
You should try `/questie` -> Advanced -> Reset Questie

**Comment by drejjmit** [comment]
May also be that you're running Classic Era version on TBC.
Install TBC version and go to Questie Options > Advanced > Reset Questie
