### ISSUE TITLE
Blacklist Kara Violet Ring Selection Quest from Autoturnin

### ISSUE THREAD

**Issue by serioux1337** [Questie/Questie#2918]
## Description

Many people have the auto-turnin activated when they reach max level. Three people in our raid autoselected the first caster ring instead of their spec, because the quest does not provide multiple items to choose from but is split up in different quests. I undestand, that it is the users fault, but it would help out if you would add this quest to a blacklist for auto-turnin.

Quests:
https://wowwiki-archive.fandom.com/wiki/Violet_Signet

**Comment by drejjmit** [comment]
Already been done. 6f4e9752bf5a97a31e4eb2abfd4dc64b509e7ab4
Will be in next release.
