### ISSUE TITLE
Specific icon enabling on full map only

### ISSUE THREAD

**Issue by Natondin** [Questie/Questie#2919]
I want to know if it is possible to have an icon show up on the minimap and not the main map, without having to disable EVERY icon on the main map. 

Specifically, I want my main map to show everything EXCEPT available quests, but still have available quests show up on my minimap. However, I cannot seem to find an option to make that happen. Please let me know if I am missing something here :)

**Comment by BreakBB** [comment]
Hey @Natondin in TBC there are minimap icons for completed and avaiable quests in the default Blizzard UI. These don't have a really high range though. But this might help you anyways.

So you could disable the available quest icons in the general settings and still see available quests on the minimap when you are close enough.
