### ISSUE TITLE
Sticky Tracker

### ISSUE THREAD

**Issue by Trowlerman** [Questie/Questie#2921]
ver. 6.3.14

Clicking on tracker while playing sometimes causes the tracker  to become stuck to the cursor. Once it sticks, it stays stuck to the tracker and only solution I've found so far is to close window and restart game. While it is stuck no other actions are available. Tried pressing various keys without any success.

**Comment by BreakBB** [comment]
Hey @Trowlerman a `/reload` should also work whenever such an issue happens.

If you are still experiencing issues with this feel free to open up a new issue 👍🏻
