### ISSUE TITLE
Reputation gained per quest

### ISSUE THREAD

**Issue by johanscho** [Questie/Questie#2922]
## Description

It would be nice now with TBC being launced making it possible to see the reputation gained pew quest and with what faction.
Would help alot through the rep-grind and not making the mistake as I did turning in quests with the wrong faction.

**Comment by gaymer77** [comment]
The "turning in quests with the wrong faction" part is only applicable for Aldor & Scryer quests.  The ones I'm sure you're referring to are ones that are meant to decrease your rep with the current one that is neutral or higher while increasing your rep with the other faction so you can start doing positive quests with the new faction once you hit neutral with them.  All other quests have zero negative faction rewards.

**Comment by johanscho** [comment]
Well, i´m not going to lie, it was afte rsuch incident it came to my mind. :) But i´m just thinking it would be a nice feature being added since I bet i´m not the only one having to google certain quests just to make sure it gives rep with the wanted faction. For example, if you´re grinding for a specifik faction it would be alot more easier or atleast smoother to have all the information in-game. 
Just a thought :)
