### ISSUE TITLE
"The Bladespire Threat" tracking issue

### ISSUE THREAD

**Issue by KeeganTrundy** [Questie/Questie#2923]
## Bug description
When questing in Blade's Edge Mountains, the quest "The Bladespire Threat" tracks the wrong mobs in the tooltip. When one mouses over a raptor, the tooltip displays information for ogre kills. When one mouses over an ogre, the tooltip displays information for raptor kills.

## Screenshots
![image](https://user-images.githubusercontent.com/9338815/121103756-cef76c00-c7bd-11eb-8ff6-f12cd3f66172.png)
![image](https://user-images.githubusercontent.com/9338815/121103799-e20a3c00-c7bd-11eb-9c37-562c54ceb507.png)

## Questie version
v6.3.14

**Comment by mnejing** [comment]
Just so we're clear, it's got the mobs reversed. It's tagging the ogres as raptors, and the raptors as ogres. It's just a flip.
