### ISSUE TITLE
When shift-hovering a quest, report its rep gain along with the exp gain

### ISSUE THREAD

**Issue by addohm** [Questie/Questie#2928]
## Description

In addition to the exp and gold gained from doing a quest, given the rep gains needed in TBC, it would be advantageous to also see the rep gains from a quest.  
![image](https://user-images.githubusercontent.com/25333107/121191755-423ec380-c83a-11eb-9c3f-7e85ea915286.png)

**Comment by Painstormx** [comment]
Came here to suggest the same thing, since reputation so important in BCC.
Right now I'm trying to max my reps and I have to crosscheck every single quest with wowhead to see if it gives any rep :(

**Comment by addohm** [comment]
> Came here to suggest the same thing, since reputation so important in BCC.
> Right now I'm trying to max my reps and I have to crosscheck every single quest with wowhead to see if it gives any rep :(

Then thumbs up for visibility :D
