### ISSUE TITLE
262 is an unknown uiMapid

### ISSUE THREAD

**Issue by LuckyDan07** [Questie/Questie#2929]
Version 6.3.14 TBC

Questing in Zangarmarsh in TBC Classic. Been popping up pretty much since I got here, been getting worse it feels, spams the entire chat box at times. My limited understanding can't find a correspondence in the quest log.

![WoWScrnShot_060821_114608](https://user-images.githubusercontent.com/85572816/121216755-327daa00-c84f-11eb-8259-a111c783e9cc.jpg)

**Comment by LuckyDan07** [comment]
Friend has 6.3.12 and doesn't have this issue.

**Comment by drejjmit** [comment]
It has to do with being on a new dungeon quest while using ``Objective Sorting`` > ``By Proximity`` in ``Questie Options`` > ``Tracker``. 
For now: Change to another sorting or abandon that dungeon quest until you're doing that dungeon.
Will be fixed for next release.
