### ISSUE TITLE
Exclusive Shadowmoon Valley Breadcrumbs

### ISSUE THREAD

**Issue by Cerby3BR** [Questie/Questie#2933]
These quests, for Alliance:
https://tbc.wowhead.com/quest=11043/building-a-better-gryphon
https://tbc.wowhead.com/quest=11044/visions-of-destruction
https://tbc.wowhead.com/quest=11045/zorus-the-judicator
and for Horde:
https://tbc.wowhead.com/quest=11046/chief-apothecary-hildagard
https://tbc.wowhead.com/quest=11047/the-apprentices-request
https://tbc.wowhead.com/quest=11048/kroghans-report
are all mutually exclusive to each other. Starting one disables the others (and, obviously completing one makes the others completely unavailable)

Version 6.3.14

**Comment by drejjmit** [comment]
Can you test with [v6.3.15](https://github.com/Questie/Questie/releases). I tested all Alliance ones and they show as complete in Journey after completing one.

**Comment by Cerby3BR** [comment]
Haven't completed one of them yet, but accepting one does not remove the two others from the map/minimap.

**Comment by Cerby3BR** [comment]
I have now completed Chief Apothecary Hildagard, and although the npcs of the other two quests don't offer them, Questie still shows them as available in the Journal/map/tooltips.

**Comment by Cerby3BR** [comment]
Now that I've reloaded Questie does consider them complete.
