### ISSUE TITLE
Quest objectives and tooltips flickering

### ISSUE THREAD

**Issue by theAnton81** [Questie/Questie#2934]
## Bug description
Often when I mouse over a quest objective on the map or minimap both quest objectives and tooltips flicker. This also happens for enemies tracked as a hunter, but does not seem to affect other tooltips. There is no error messages so I cannot be sure it has to do with Questie, some conflict with another addon or the client itself which was recently updated.

## Screenshots
You can't really see it on a screenshot, but if required I could always upload a video somewhere.

## Questie version
v6.3.15 (Beta 8)

**Comment by drejjmit** [comment]
Some say it's this addon: https://www.curseforge.com/wow/addons/guild-tooltip
Can you test with only Questie loaded?

**Comment by GeodesicDragon** [comment]
> Some say it's this addon: https://www.curseforge.com/wow/addons/guild-tooltip
> Can you test with only Questie loaded?

GuildTooltip does appear to be the issue, but I can't see how, since it shouldn't be interacting interacting with other addons at all.

I can only assume that Questie is using GameTooltip to display quest info, and something in either addon (likely mine) is causing this to happen. I've been looking for a fix since the issue was brought to my attention on my own Discord server.

(I'm the developer of GuildTooltip, BTW.)

**Comment by BreakBB** [comment]
Hey @GeodesicDragon sorry for not responding to this earlier. Did you manage to find a fix for this? I am not using your addon, but I know Questie is calling the tooltip code very often when hovering over something relevant.

I'd bet Questie clears the tooltip, adds its information and then your addon also wants to adds something, before the loop starts again (maybe the other way around).

**Comment by GeodesicDragon** [comment]
> Hey @GeodesicDragon sorry for not responding to this earlier. Did you manage to find a fix for this? I am not using your addon, but I know Questie is calling the tooltip code very often when hovering over something relevant.
> 
> I'd bet Questie clears the tooltip, adds its information and then your addon also wants to adds something, before the loop starts again (maybe the other way around).

I actually fixed it a couple of months ago; I'd forgotten that this ticket even existed until I got your reply. It was a single line of code in my addon that was the problem; I can't remember what it was, but I do remember that removing it fixed the issue.

**Comment by BreakBB** [comment]
Thanks a lot for coming back to this @GeodesicDragon and also good job on fixing the issue 👍🏻
