### ISSUE TITLE
[A Visit With the Greatmother] prerequisites not right

### ISSUE THREAD

**Issue by Cerby3BR** [Questie/Questie#2935]
The quest https://tbc.wowhead.com/quest=10044/a-visit-with-the-greatmother showed up as available well before it actually was for me. It only actually became available after I completed https://tbc.wowhead.com/quest=10011/forge-camp-annihilated, which was the final Nagrand quest I could do. This may have something to do with the database data, perhaps  it should be {9868,9934,10011,},nul, rather than {9868,9934,},{10011,}, at the preQuestGroup/preQuestSingle markers?

Version 6.3.15

**Comment by drejjmit** [comment]
Fixed with 0a0dc9246b3fe8b8dc9589a1d2068c6c85c830e0
