### ISSUE TITLE
Questie not working after update to 6.3.15

### ISSUE THREAD

**Issue by NNGeneral** [Questie/Questie#2937]
## Bug description
After updating to 6.3.15, Questie no longer loads and I receive the following error in Bugsack:

4x ...rfaceQuestie\Modules\QuestieEventHandler.lua:67: attempt to call method 'Init' (a nil value)
[string "@Questie\Modules\QuestieEventHandler.lua"]:67: in function <...rfaceQuestie\Modules\QuestieEventHandler.lua:66>

**Comment by drejjmit** [comment]
Try this in chat: ``/run QuestieLoader:ImportModule("QuestieOptions").tabs.advanced:Initialize().args.questieReset.func()``

**Comment by NNGeneral** [comment]
No go, still get the same error :(

**Comment by drejjmit** [comment]
Then you should probably delete your ``\World of Warcraft\_classic_\Interface\AddOns\Questie`` folder and reinstall. Be sure to install Questie-v6.3.15-TBC and not Questie-v6.3.15-Era

**Comment by NNGeneral** [comment]
Got it working. I had to move the old Questie folder in the addons folder to another location. just in case, then reinstalled.  There must have been remnants of the older version.

**Comment by NNGeneral** [comment]
Thanks for the assistance :)
