### ISSUE TITLE
"Questie: [ERROR]" all quests missing from database

### ISSUE THREAD

**Issue by Keellath** [Questie/Questie#2938]

**Comment by drejjmit** [comment]
That's because you have TBC quests in your quest log while running Classic Era version.
Install TBC version and go to ``Questie Options`` > ``Advanced`` > ``Reset Questie``

**Comment by cbcatanz** [comment]
> That's because you have TBC quests in your quest log while running Classic Era version.
> Install TBC version and go to `Questie Options` > `Advanced` > `Reset Questie`
> If you're using `WowUp`, make sure to install latest version and it will grab TBC version for you, then restart Wow and `Reset Questie`

This is not fixing the issue.

**Comment by ccadenhead** [comment]
I'm using 6.3.15 and I've reset questie and I'm still getting the error.

**Comment by Raina1007** [comment]
> I'm using 6.3.15 and I've reset questie, a couple of times now, and I'm still getting the error.

What version of wowup are you using? if its anything other than 2.3.4, its a version that doesn't support tbcc. Check lower right hand corner in wowup, if it is older, you should have a green arrow or update button you can click to update it. Once it updates, follow drejjmit directions the rest of the way.

**Comment by ccadenhead** [comment]
It was 2.0.2 This is so complicated!

**Comment by Raina1007** [comment]
> It was 2.0.2 This is so complicated!

if you want you are welcome to go to WowUp's discord to be walked through how to update WowUp

**Comment by ccadenhead** [comment]
Already done. Thanks ;)

**Comment by ccadenhead** [comment]
WoWup and Questie updated. Looks to be working. Thanks!

**Comment by tomcass240** [comment]
getting the same error myself. even reinstalled the mod and deleted my WTF folder but still getting it. It seems resetting it worked but can someone tell me what exactly resetting it do that reinstalling the whole mod and deleting my config folders didn't do?

**Comment by Raina1007** [comment]
> getting the same error myself. even reinstalled the mod and deleted my WTF folder but still getting it. It seems resetting it worked but can someone tell me what exactly resetting it did that reinstalling the whole mod and deleting my config folders didn't do?

if you installed it from an older version of wowup, having the older version caused a bug that reinstalling over via different methods doesn't seem to fix. Once you update wowup and uninstall/reinstall from their, the bug is cleared out after resetting Questie.

**Comment by drejjmit** [comment]
Fixed in v6.3.16 for people who still insist on installing Classic Era version of their addons on TBC.
