### ISSUE TITLE
Unwanted Added Dashed Lines, Underscores, and periods  to all game text.

### ISSUE THREAD

**Issue by HarleyDav** [Questie/Questie#2939]

**Comment by drejjmit** [comment]
What?

**Comment by HarleyDav** [comment]
Unwanted Added Dashed Lines, Underscores, and periods to all game text.  I first noticed this problem after launch of PrePatch TBC.      I have verified I am using current version of Questie and Reinstalled the game file, the error goes away if I remove my Questie add on but returns if I reinstall Questie.    I am using a i7 computer using Windows 10 operating system.

**Comment by drejjmit** [comment]
Can you post a picture?

**Comment by HarleyDav** [comment]
![061121-overscores-1](https://user-images.githubusercontent.com/85738442/121673571-de004780-ca65-11eb-81a1-f2419b75d573.PNG)

**Comment by HarleyDav** [comment]
I rebooted after last update...  trying to repeat problem now.. ill update if i have continued problem in 20 minutes

**Comment by HarleyDav** [comment]
the problem persists... see pictures

**Comment by HarleyDav** [comment]
![061121-overscores-3](https://user-images.githubusercontent.com/85738442/121676420-751ace80-ca69-11eb-8972-7b11a07824fb.PNG)

**Comment by HarleyDav** [comment]
![061121-overscores-2](https://user-images.githubusercontent.com/85738442/121676451-81069080-ca69-11eb-97b3-24674dad4706.PNG)

**Comment by drejjmit** [comment]
Same with only Questie loaded? That looks like a client wide font corruption/graphic driver issue

**Comment by HarleyDav** [comment]
I'm about to transfer to a new location. I need about 4 hours and I will confirm it still is doing it but yes in past updates i had problem with just questie working.. but verified after reinstall with questie uninstalled no problem... ill try again later today.. to verify the fix removing questie still works..

**Comment by drejjmit** [comment]
I doubt this is Questie. We don't touch font or Quest log.

**Comment by HarleyDav** [comment]
I verified that with no add ons installed and a complete new install of the game... in Burning Crusades version of the game the problem persists... so you are correct it is not Questie.. I wish Blizzard would fix this..

**Comment by drejjmit** [comment]
Good luck finding the solution. I would make a bug report to Blizzard.
