### ISSUE TITLE
Getting error messages after updating Questie a few minutes ago

### ISSUE THREAD

**Issue by cbcatanz** [Questie/Questie#2942]
Sorry I accidently closed the last report.

I'm getting an error that states the quests I have are not in the Questie database. I have uninstalled and reinstalled the addon using WoWUp. I have uninstalled and installed the addon manually. Also, I have tried resetting the addon in game under the Advance tab but I'm getting the same error messages.

**Comment by cbcatanz** [comment]
I just tried resetting the addon again. It is not fixing the issue.

**Comment by drejjmit** [comment]
Resetting does not install the correct version.

**Comment by cbcatanz** [comment]
> Resetting does not install the correct version.

I've installed it using WoWUp.

**Comment by Raina1007** [comment]
what version of wowup do you have? check the lower right hand of wowup, if it states anything other than 2.3.4, then you need to update it. you should have a green arrow next to the version number if its not at 2.3.4 for wowup

**Comment by cbcatanz** [comment]
> what version of wowup do you have? check the lower right hand of wowup, if it states anything other than 2.3.4, then you need to update it. you should have a green arrow next to the version number if its not at 2.3.4 for wowup. Once you get it updated, follow the directions you got from drejjmit

And I think that must have been the issue. I was on version 2.0.......When I got in the game it was giving me the same error but I reset the addon now everything is working. Thanks for the help, guys.
