### ISSUE TITLE
Quest tracking does not work properly with auto accept/complete enabled

### ISSUE THREAD

**Issue by ClawhammerLobotomy** [Questie/Questie#2943]
## Bug description

When handing in and picking up a quest in a chain with the auto complete/accept, the quest does not appear on the tracker window.
However, the quest does show listed as tracked in the Blizzard quest log.
This happens when the quest is picked up in a "complete" status or if there are objectives to do.

I tested holding shift while doing the turn in and pick up which seems to track properly.

## Screenshots

Chat log
![image](https://user-images.githubusercontent.com/6299800/121764108-4ce5ab00-cb0f-11eb-9e5c-d47b79edc3aa.png)
Blizzard Quest Log
![image](https://user-images.githubusercontent.com/6299800/121764122-5d962100-cb0f-11eb-96ef-2f40da76b8ad.png)
Questie Tracker
![image](https://user-images.githubusercontent.com/6299800/121764171-de551d00-cb0f-11eb-9f76-e5e36d511fa2.png)
General Settings
![image](https://user-images.githubusercontent.com/6299800/121764157-bc5b9a80-cb0f-11eb-8f39-c8d7058c188b.png)
Tracker Settings
![image](https://user-images.githubusercontent.com/6299800/121764159-c2ea1200-cb0f-11eb-9aa1-50ef21611ac5.png)

## Questie version

v6.3.15

**Comment by ClawhammerLobotomy** [comment]
Additional info: it seems to be inconsistent in whether the quest will appear in the tracker.

**Comment by BreakBB** [comment]
Fixed with 997d1b451df8ffb2a6c5b63448c3772086296b6f
