### ISSUE TITLE
World Map Icons --> stable masters mixed up with flight masters

### ISSUE THREAD

**Issue by Biomatrix1993** [Questie/Questie#2951]
Hello :) I've found a small bug in the version 6.3.15

## Bug description
If you allow world map icons and check the box for flight masters it will display the location of all stable masters. (If you hover over the icon you'll see the name of the stable masters.)

Unfortunately it won't show the flight masters at all, even if you try to do the opposite (activate stable masters).
It seems that there is something mixed up.

## Screenshots
Screenshot 1 and 2 has the box for flight masters checked, but it only displays the stable master. (The 2 flight masters, in Splintertree Post and Zoram Strand aren't displayed. If I hover over the icon in the Splintertree Post it tells me the name of the stable master.)

https://i.imgur.com/tSHbUv0.png
https://i.imgur.com/dVqREaF.png

Screenshot 3 has the box for stable masters checked, but it shows nothing.

https://i.imgur.com/MlFKCHZ.png

## Questie version
v6.3.15

Thank you very much. :)
Have a nice day

**Comment by drejjmit** [comment]
I would check what version you have. This happens if you have Classic Era version on TBC

**Comment by Biomatrix1993** [comment]
Thank you for the answer :) I double checked my version and it seems that I have the correct version (v6.3.15 - TBC). I deleted the addon folder and installed the TBC version again but my problem is still there...

Screenshot of the downloaded addon:
https://i.imgur.com/jeUjtmV.png

**Comment by drejjmit** [comment]
Try ``Questie Options`` > ``Advanced`` > ``Reset Questie`` and see if that fixes it.

**Comment by Biomatrix1993** [comment]
It worked! Bloody hell, I tried everything for the longest time but I never reseted it ingame.

THANK YOU drejjmit! :) YOU ROCK!
