### ISSUE TITLE
Hide minimap button resets on every update

### ISSUE THREAD

**Issue by joseph3114** [Questie/Questie#2953]
With every Questie update, the hide minimap button setting resets and the button is visible again.

**Comment by BreakBB** [comment]
Are you sure you are on the latest version? We had an issue where the minimap button would show up after every `/reload` or game startup. But that is fixed in the last two versions at least.

**Comment by joseph3114** [comment]
6.3.16 on BCC.
All of my other settings are fine every update, but the minimap button always reappears after it's done doing the 7 step optimizing thing it does after each update.

**Comment by Laumesis** [comment]
Works For Me.
I had the issue always before fix in recent version. (And total brake of setting in previous version). Now it works fine.

**Comment by Zaldoras** [comment]
I have exactly the same problem since the BCC release.

**Comment by Laumesis** [comment]
@joseph3114 @Zaldoras  I would try deleting `_classic_\Interface\Addons\Questie\` folder and extract/install v6.3.16 again to make sure all files are really up to date.

**Comment by joseph3114** [comment]
This past update did not trigger it again.

**Comment by BreakBB** [comment]
This was fixed with b6963ead8057532a8ce1809f3c3f56d613aa01e3
