### ISSUE TITLE
Show in Joyrney if player is on quest now

### ISSUE THREAD

**Issue by Laumesis** [Questie/Questie#2954]
A feature request to show if the player is on a quest right now while browsing Available Quests in Questie Journey. This would help checking missing quests while gathering those for example for a dungeon.

Sketch how it could look like: 
![Questie Journey sketch of quests in Quests Log](https://user-images.githubusercontent.com/75958501/122494184-8fb4f080-cff1-11eb-8075-e919cf78d4ee.png)

**Comment by drejjmit** [comment]
Duplicate of #2341
