### ISSUE TITLE
Rune Covered Tablet (23759) requires a pre quest : A Small Start (9506)

### ISSUE THREAD

**Issue by Laumesis** [Questie/Questie#2956]
I couldn't get the quest start item to drop even after many tens of kills, so I looked wowhead comments and found this one to be accurate [https://tbc.wowhead.com/item=23759/rune-covered-tablet#comments:id=3344897](https://tbc.wowhead.com/item=23759/rune-covered-tablet#comments:id=3344897)

After I turned in A Small Start (9506) quest, 3rd kill dropped the quest start item. I did not turn in or accept other quests in between.

**Comment by drejjmit** [comment]
d9c8874f23c9cc361830ee5c621221da431e66df
