### ISSUE TITLE
 'Questie' tried to call the protected function 'FocusFrame:SetFrameStrata()'.

### ISSUE THREAD

**Issue by Z3ng** [Questie/Questie#2958]
hello, 
questie version : 6.3.16 (beta9)
I use buggraber with bugsack to track addon bug and it send me that : 

1x [ADDON_ACTION_BLOCKED] AddOn 'Questie' tried to call the protected function 'FocusFrame:SetFrameStrata()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `SetFrameStrata'
[string "@FrameXML\TargetFrame.lua"]:1151: in function <FrameXML\TargetFrame.lua:1147>

**Comment by Z3ng** [comment]
2x [ADDON_ACTION_BLOCKED] AddOn 'Questie' tried to call the protected function 'CompactPartyFrame:unusedFunc()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `unusedFunc'
[string "@Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua"]:160: in function `CompactRaidFrameContainer_LayoutFrames'
[string "@Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua"]:130: in function `CompactRaidFrameContainer_TryUpdate'
[string "@Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua"]:76: in function `CompactRaidFrameContainer_SetGroupMode'
[string "@Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameManager.lua"]:403: in function <...mpactRaidFrames\Blizzard_CompactRaidFrameManager.lua:394>
[string "@Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameManager.lua"]:471: in function `CompactRaidFrameManager_SetSetting'
[string "@Blizzard_CUFProfiles\Blizzard_CompactUnitFrameProfiles.lua"]:565: in function `func'
[string "@Blizzard_CUFProfiles\Blizzard_CompactUnitFrameProfiles.lua"]:542: in function `CompactUnitFrameProfiles_ApplyProfile'
[string "@Blizzard_CUFProfiles\Blizzard_CompactUnitFrameProfiles.lua"]:173: in function `CompactUnitFrameProfiles_ApplyCurrentSettings'
[string "@Blizzard_CUFProfiles\Blizzard_CompactUnitFrameProfiles.lua"]:82: in function `CompactUnitFrameProfiles_CancelChanges'
[string "@Blizzard_CUFProfiles\Blizzard_CompactUnitFrameProfiles.lua"]:75: in function <...rd_CUFProfiles\Blizzard_CompactUnitFrameProfiles.lua:73>
[string "=[C]"]: in function `pcall'
[string "@FrameXML\InterfaceOptionsFrame.lua"]:216: in function <FrameXML\InterfaceOptionsFrame.lua:215>
[string "=[C]"]: ?
[string "@FrameXML\InterfaceOptionsFrame.lua"]:251: in function <FrameXML\InterfaceOptionsFrame.lua:247>

**Comment by Z3ng** [comment]
57x FrameXML\UnitFrame.lua:284: Usage: GameTooltip:SetUnit("unit"[, hideStatus])
[string "=[C]"]: in function `SetUnit'
[string "@FrameXML\UnitFrame.lua"]:284: in function `UnitFrame_UpdateTooltip'
[string "@FrameXML\UnitFrame.lua"]:270: in function <FrameXML\UnitFrame.lua:257>

Locals:
(*temporary) = GameTooltip {
 0 = <userdata>
 OnBackdropLoaded = <function> defined @SharedXML\Backdrop.lua:239
 GetBackdropColor = <function> defined @SharedXML\Backdrop.lua:477
 SetHyperlink = <function> defined =[C]:-1
 _owner = QuestieFrame741 {
 }
 SetVoidDepositItem = <function> defined =[C]:-1
 SetVoidWithdrawalItem = <function> defined =[C]:-1
 questOrder = <table> {
 }
 SetSocketGem = <function> defined =[C]:-1
 ClearBackdrop = <function> defined @SharedXML\Backdrop.lua:369
 default = 1
 SetLootItem = <function> defined =[C]:-1
 SetRecipeReagentItem = <function> defined @TradeSkillMaster\LibTSM\Service\ItemTooltipClasses\Wrapper.lua:96
 SetBuybackItem = <function> defined =[C]:-1
 SetMerchantItem = <function> defined =[C]:-1
 SetupTextureCoordinates = <function> defined @SharedXML\Backdrop.lua:301
 HasBackdropInfo = <function> defined @SharedXML\Backdrop.lua:365
 GetEdgeSize = <function> defined @SharedXML\Backdrop.lua:275
 updateTooltip = 0.121000
 SetInventoryItem = <function> defined =[C]:-1
 TopEdge = <unnamed> {
 }
 SetLootRollItem = <function> defined =[C]:-1
 SetAuctionSellItem = <function> defined =[C]:-1
 SetBagItem = <function> defined =[C]:-1
 BottomRightCorner = <unnamed> {
 }
 SetBackdropColor = <function> defined @SharedXML\Backdrop.lua:486
 LeftEdge = <unnamed> {
 }
 SetAuctionItem = <function> defined =[C]:-1
 backdropBorderColor = <table> {
 }
 SetGuildBankItem = <function> defined =[C]:-1
 SetVoidItem = <function> defined =[C]:-1
 SetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:509
 Hide = <function> defined =[C]:-1
 comparing = false
 SetBackdrop = <function> defined @SharedXML\Backdrop.lua:416
 TopOverlay = <unnamed> {
 }
 GetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:496
 GetBackdrop = <function> defined @SharedXML\Backdrop.lua:434
 SetItemByID = <function> defined =[C]:-1
 SetQuestItem = <function> defined =[C]:-1
 backdropColor = <table> {
 }
 SetTrainerService = <function> defined =[C]:-1
 SetInboxItem = <function> defined =[C]:-1
 shoppingTooltips = <table> {
 }
 miniMapIcon = false
 SetQuestLogItem = <function> defined =[C]:-1
 OnBackdropSizeChanged = <function> defined @SharedXML\Backdrop.lua:269
 SetTradeTargetItem = <function> defined =[C]:-1
 manualOrder = <table> {
 }
 SetTradePlayerItem = <function> defined =[C]:-1
 BottomLeftCorner = <unnamed> {
 }
 SetSendMailItem = <function> defined =[C]:-1
 SetExistingSocketGem = <function> defined =[C]:-1
 npcOrder = <table> {
 }
 Center = <unnamed> {
 }
 SetMerchantCostItem = <function> defined @TradeSkillMaster\LibTSM\Service\ItemTooltipClasses\Wrapper.lua:96
 TopLeftCorner = <unnamed> {
 }
 RightEdge = <unnamed> {
 }
 ApplyBackdrop = <function> defined @SharedXML\Backdrop.lua:381
 BottomEdge = <unnamed> {
 }
 SetBorderBlendMode = <function> defined @SharedXML\Backdrop.lua:353
 backdropInfo = <table> {
 }
 needsReset = true
 SetupPieceVisuals = <function> defined @SharedXML\Backdrop.lua:333
 BottomOverlay = <unnamed> {
 }
 TopRightCorner = <unnamed> {
 }
 SetRecipeResultItem = <function> defined =[C]:-1
}
(*temporary) = nil
(*temporary) = nil

**Comment by Z3ng** [comment]
I prefer precise that i don't know how addon works and blizzard shared lib works etc.
But i think it's maybe a problem related to blizzard because i also have this kind of bug report : 
78x FrameXML\UnitFrame.lua:284: Usage: GameTooltip:SetUnit("unit"[, hideStatus])
[string "=[C]"]: in function `SetUnit'
[string "@FrameXML\UnitFrame.lua"]:284: in function `UnitFrame_UpdateTooltip'
[string "@FrameXML\UnitFrame.lua"]:270: in function <FrameXML\UnitFrame.lua:257>

Locals:
(*temporary) = GameTooltip {
 0 = <userdata>
 OnBackdropLoaded = <function> defined @SharedXML\Backdrop.lua:239
 GetBackdropColor = <function> defined @SharedXML\Backdrop.lua:477
 SetHyperlink = <function> defined =[C]:-1
 _owner = QuestieFrame741 {
 }
 SetVoidDepositItem = <function> defined =[C]:-1
 SetVoidWithdrawalItem = <function> defined =[C]:-1
 questOrder = <table> {
 }
 SetSocketGem = <function> defined =[C]:-1
 ClearBackdrop = <function> defined @SharedXML\Backdrop.lua:369
 default = 1
 SetLootItem = <function> defined =[C]:-1
 SetRecipeReagentItem = <function> defined @TradeSkillMaster\LibTSM\Service\ItemTooltipClasses\Wrapper.lua:96
 SetBuybackItem = <function> defined =[C]:-1
 SetMerchantItem = <function> defined =[C]:-1
 SetupTextureCoordinates = <function> defined @SharedXML\Backdrop.lua:301
 HasBackdropInfo = <function> defined @SharedXML\Backdrop.lua:365
 GetEdgeSize = <function> defined @SharedXML\Backdrop.lua:275
 updateTooltip = 0.121000
 SetInventoryItem = <function> defined =[C]:-1
 TopEdge = <unnamed> {
 }
 SetLootRollItem = <function> defined =[C]:-1
 SetAuctionSellItem = <function> defined =[C]:-1
 SetBagItem = <function> defined =[C]:-1
 BottomRightCorner = <unnamed> {
 }
 SetBackdropColor = <function> defined @SharedXML\Backdrop.lua:486
 LeftEdge = <unnamed> {
 }
 SetAuctionItem = <function> defined =[C]:-1
 backdropBorderColor = <table> {
 }
 SetGuildBankItem = <function> defined =[C]:-1
 SetVoidItem = <function> defined =[C]:-1
 SetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:509
 Hide = <function> defined =[C]:-1
 comparing = false
 SetBackdrop = <function> defined @SharedXML\Backdrop.lua:416
 TopOverlay = <unnamed> {
 }
 GetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:496
 GetBackdrop = <function> defined @SharedXML\Backdrop.lua:434
 SetItemByID = <function> defined =[C]:-1
 SetQuestItem = <function> defined =[C]:-1
 backdropColor = <table> {
 }
 SetTrainerService = <function> defined =[C]:-1
 SetInboxItem = <function> defined =[C]:-1
 shoppingTooltips = <table> {
 }
 miniMapIcon = false
 SetQuestLogItem = <function> defined =[C]:-1
 OnBackdropSizeChanged = <function> defined @SharedXML\Backdrop.lua:269
 SetTradeTargetItem = <function> defined =[C]:-1
 manualOrder = <table> {
 }
 SetTradePlayerItem = <function> defined =[C]:-1
 BottomLeftCorner = <unnamed> {
 }
 SetSendMailItem = <function> defined =[C]:-1
 SetExistingSocketGem = <function> defined =[C]:-1
 npcOrder = <table> {
 }
 Center = <unnamed> {
 }
 SetMerchantCostItem = <function> defined @TradeSkillMaster\LibTSM\Service\ItemTooltipClasses\Wrapper.lua:96
 TopLeftCorner = <unnamed> {
 }
 RightEdge = <unnamed> {
 }
 ApplyBackdrop = <function> defined @SharedXML\Backdrop.lua:381
 BottomEdge = <unnamed> {
 }
 SetBorderBlendMode = <function> defined @SharedXML\Backdrop.lua:353
 backdropInfo = <table> {
 }
 needsReset = true
 SetupPieceVisuals = <function> defined @SharedXML\Backdrop.lua:333
 BottomOverlay = <unnamed> {
 }
 TopRightCorner = <unnamed> {
 }
 SetRecipeResultItem = <function> defined =[C]:-1
}
(*temporary) = nil
(*temporary) = nil

**Comment by BreakBB** [comment]
Mergin this with #2936
