### ISSUE TITLE
No Tracker, new version bad arg to 'pairs' - got nil.

### ISSUE THREAD

**Issue by CristenPerret** [Questie/Questie#2959]
Previously while using the v6.3.16, my tracker bugged out where the window would appear for a moment upon login- then go back to the default vanilla ui.
After multiple attempts to fix this myself, wiping the Saved var + reinstalling the addon while no addon being on but just questie. To no avail. 

So now after another wipe, I try out the BETA 9 Version. Upon loading. 
`[12:00] Questie: [ERROR] Error during initialization! ...erface\AddOns\Questie\Modules\QuestieProfessions.lua:17: bad argument #1 to 'pairs' (table expected, got nil)`

For the issue with my tracker, I can go to /Questie > Tracker, and reset it. It does appear in the center of the screen. However upon interaction, after releasing the mouse the tracker window disappears. And while the window is visible no quest in my log is populated.

**Comment by drejjmit** [comment]
You most likley don't have Automatic Quest Tracking on in Blizzard Interface > Display.

**Comment by MilaPi** [comment]
I have the same issue. I have set Automatic Quest Tracking on in Blizzard Interface options. When I reset Trqcker in Questie options it only appears for a short while on the center of screen, but when I move it to the side, it disappears.

**Comment by CristenPerret** [comment]
Weird it was toggled on when reviewing things. Re-enabling it did sorted it.
ty drejjmit, mvp.
