### ISSUE TITLE
Additional viable mobs for "Are We There, Yeti?"

### ISSUE THREAD

**Issue by Webberjo** [Questie/Questie#2960]
## Description
Ice Thistle Matriarchs and Ice Thistle Patriarchs are also capable of dropping Thick Yeti Fur but do not indicate so. Wowhead does not indicate so either.
I've attached screenshots below as proof, of which I only covered up other peoples' names and messages in my chat.

## Wowhead link
https://classic.wowhead.com/quest=3783/are-we-there-yeti
https://classic.wowhead.com/npc=7459/ice-thistle-matriarch
https://classic.wowhead.com/npc=7460/ice-thistle-patriarch

## Screenshots
![WoWScrnShot_062021_174136](https://user-images.githubusercontent.com/11682731/122687944-a32daa80-d1ef-11eb-8fcd-cf56f357221e.jpg)
![WoWScrnShot_062021_172919](https://user-images.githubusercontent.com/11682731/122687947-a5900480-d1ef-11eb-8fa9-d38be7d58870.jpg)

## Questie version
v6.3.16 (Beta 9)

**Comment by BreakBB** [comment]
Fixed with 82ccab31eff327ca978fc37c8c828747b1fe4127
