### ISSUE TITLE
Missing Icon for quest 2967 Return to Thunder Bluff

### ISSUE THREAD

**Issue by Jakobud** [Questie/Questie#2962]
## Description
I don't see the question mark icon for quest 2967 Return to Thunder Bluff: 

## Wowhead link
https://tbc.wowhead.com/quest=2967/return-to-thunder-bluff

## Questie version
6.3.16 (BCC version)

**Comment by drejjmit** [comment]
Map icons will not update inside dungeons/raids. They will update when you leave or leave and /reload

**Comment by Jakobud** [comment]
I'm in Thunder Bluff and the icon is not on the map or mini map.

**Comment by BreakBB** [comment]
I also assume this happened because of a desync.
