### ISSUE TITLE
Missing Map Icon: Delivery to Magatha

### ISSUE THREAD

**Issue by Jakobud** [Questie/Questie#2963]
## Description
Missing icon for the quest Delivery to Magatha and also missing I think there should be something on the tooltip for the NPC.

## Wowhead link
https://tbc.wowhead.com/quest=3518/delivery-to-magatha

## Screenshots
![Screenshot 2021-06-21 234053](https://user-images.githubusercontent.com/87356/122869899-259a9500-d2ea-11eb-9808-2c416bfb0381.png)

## Questie version
v6.3.16

**Comment by BreakBB** [comment]
@Jakobud Did you do a `/reload` after this issue appeared? Since you reported other similar issues, it looks like a simple "desync" which unfortunately sometimes happens with Questie.

**Comment by Jakobud** [comment]
No I didn't and I turned in the quest so I have no way to recreating the problem. If you are confident it was a desync issue you can close.

**Comment by Jakobud** [comment]
If I encounter an issue like this in the future how do I fix the desync issue? Is there a "sync" command I can run or something?

**Comment by BreakBB** [comment]
@Jakobud A `/reload` should always fix the desync issues. You could also try to press "Hide Questie" followed by "Show Questie" on the map.
