### ISSUE TITLE
Quest "The Sunken Temple" showed the wrong XP in tooltip

### ISSUE THREAD

**Issue by Jakobud** [Questie/Questie#2965]
## Description
The quest "The Sunken Temple" when holding SHIFT and mousing over the icon on the map, showed an XP amount of 10,000+ xp. I think it was like 10,500xp. But when I turned it in, I only got 5300 xp. Verified on wowhead that the maximum xp you can get for this quest is 5300. I'm not sure where exactly Questie gets the XP values. If that is from the API or if there is a maintained database of XP turn in values in the code.

## Wowhead link
https://tbc.wowhead.com/quest=3380/the-sunken-temple

## Questie version
v6.3.16

**Comment by drejjmit** [comment]
Not sure where you get 10,500 xp from. We have it as this in the DB:
```[3380] = {["xp"] = 5300, ["level"] = 51},```

Questie\Libs\LibQuestXP
