### ISSUE TITLE
Ability to hide non-tracked quest objectives from the map and minimap

### ISSUE THREAD

**Issue by githubgavin2** [Questie/Questie#2968]
When your quest log is starting to get a tad crowded and you'd like to work your way through, let's say, starting from the lowest level quests that you have, it might be cumbersome to find the particular nodes on the map when it's cluttered with the icons of 15+ quests in the same area, so my suggestion would be to add a feature which, if toggled on, would allow only tracked quest objective icons to show up on the map and on the minimap instead of showing or hiding all of them at once.

**Comment by svalentin** [comment]
@BreakBB, I think this can be closed. Feature implemented in v6.7.0 ;)
