### ISSUE TITLE
Instialization error "AddtoBlizOptions

### ISSUE THREAD

**Issue by Plutch28** [Questie/Questie#2970]
I have been running Questie since the launch of TBC.  However, since of late my Questie addon hasn't been working properly.  Every time I launch TBC I get an error saying "[ERROR] Error during initialization!" Then at the end of the error message it says "attempt to call method 'AddToBlizOptions' (a nil value)".

Help with this issue would be greatly appreciated.

Thank you.

**Comment by BreakBB** [comment]
@Plutch28 You should disable all other addons except Questie and try again. Seems some other addon is loading a bad dependency version which then breaks Questie.
