### ISSUE TITLE
Is this Questie?  Can't tell.

### ISSUE THREAD

**Issue by MightBeChris** [Questie/Questie#2971]
## Bug description
I log in.

## Screenshots
Message: ...ce\AddOns\Questie\Libs\AceEvent-3.0\AceEvent-3.0.lua:33: Attempt to register unknown event "PARTY_MEMBERS_CHANGED"
Time: Thu Jun 24 12:31:57 2021
Count: 1
Stack: ...ce\AddOns\Questie\Libs\AceEvent-3.0\AceEvent-3.0.lua:33: Attempt to register unknown event "PARTY_MEMBERS_CHANGED"
[string "@Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua"]:758: in function <...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:717>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `RegisterEvent'
[string "@Interface\AddOns\Questie\Libs\AceEvent-3.0\AceEvent-3.0.lua"]:33: in function `OnUsed'
[string "@Interface\AddOns\Questie\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:142: in function `RegisterEvent'
[string "@Interface\AddOns\Prat-3.0\modules\PlayerNames.lua"]:1132: in function `OnModuleEnable'
[string "@Interface\AddOns\Prat-3.0\addon\modules.lua"]:189: in function <Interface\AddOns\Prat-3.0\addon\modules.lua:178>
[string "=[C]"]: ?
[string "@Interface\AddOns\Questie\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:70: in function <...ce\AddOns\Questie\Libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Interface\AddOns\Questie\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:527: in function `EnableAddon'
[string "@Interface\AddOns\Questie\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:540: in function `EnableAddon'
[string "@Interface\AddOns\Questie\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:630: in function <...ce\AddOns\Questie\Libs\AceAddon-3.0\AceAddon-3.0.lua:615>

Locals: <none>

**Comment by drejjmit** [comment]
``RegisterEvent' [string "@Interface\AddOns\Prat-3.0\modules\PlayerNames.lua"]:1132:``
Since the author of Prat unfortunately passed away you need to use a community updated version.
https://github.com/sylvanaar/prat-3-0/pulls
