### ISSUE TITLE
Questie initialization error

### ISSUE THREAD

**Issue by nathansensation** [Questie/Questie#2973]
Running Questie-v6.3.16-TBC.zip

was working fine and for with no trigger when I logged in I got this error message:

[ERROR] Error during initialization!
Interface\AddOns\Questie\Modules\QuestieMenu.lua:590: bad argument
#1 to 'band' (number expected, got nil)

I've tried reinstalling, disabling all other addons, i've installed from both curseforge and direct, I've installed manually, 

Help :(

**Comment by BreakBB** [comment]
You should remove the Questie.lua files you can find in your WTF folder. Looks like something got corrupted when you updated.

**Comment by alin-faur** [comment]
I have a similar issue with initialization after I updated to 6.3.16 "error during initialization,  ...Addons/Questie/Modules/QuestieProfessions.lua:17 bad argument #1 to 'pairs'(table expected, got nil)

I deleted all the Questie.lua files ...

**Comment by BreakBB** [comment]
@alin-faur If you have deleted all `Questie.lua` and `Questie.lua.bak` files in your WTF folder Questie should startup just fine. Make sure to delete the correct files in the correct folder.

**Comment by gcaliber** [comment]
I have a similar issue. Error during init about line 443 of QuestieLib.lua

```
        local name, title, _, _, reason = GetAddOnInfo("QuestieDev-master")
        if (reason == "MISSING") then name, title = GetAddOnInfo("Questie") end
```

If I change the second line to use GetAddonOnInfo("Questie-BCC") then it works again as "Questie" just returns nil.

I've deleted every Questie related file from all WTF folders and reinstalled it.
