### ISSUE TITLE
Learn to Fly not available

### ISSUE THREAD

**Issue by thebohster** [Questie/Questie#2974]
The quest Learn to Fly is not available for me from the flight master. I assume this is because I had already trained max riding without picking up the quest.
![Learn to Fly](https://user-images.githubusercontent.com/3538320/123377135-73103f80-d540-11eb-9715-d4f4ca3a85d0.PNG)

**Comment by drejjmit** [comment]
This has been fixed in the three latest version. I suggest you update.

**Comment by thebohster** [comment]
Ah thank you, the CurseForge app didn't autoupdate.
