### ISSUE TITLE
The Powers Below (968)

### ISSUE THREAD

**Issue by Nerillida** [Questie/Questie#2975]
Version 6.3.16

This quest is started from an item (Book: The Powers Below (5352)) dropped by mobs in the Master's Glaive and probably in the base of the Cave Mushrooms cave.

Twilight Disciples (2338) and Twilight Thugs (2339) - Wowhead has some coordinates.

As far as I can see, there are no coordinates/clue as to the item's occurrence in your database.

**Comment by BreakBB** [comment]
The problem with this quest is, that it would flood the map with icons since the NPCs have a lot of spawns. We have yet to implement a nice way to show such quests.

**Comment by Nerillida** [comment]
Surely you do not need an icon for each occurrence, just representative ones in each location? Wholly/Grail use one icon at each corner of the Master's Grave and one in the cave in the north.
