### ISSUE TITLE
Questie shows quest icons where there are no quest items!

### ISSUE THREAD

**Issue by LunesseHD** [Questie/Questie#2977]
Questie shows quest icon symbols where there are no quest items! e.g. in Dust Wallow Marshes once The Turtle quest shows it in completely Dust Wallow Marshes, and in the quest Hunger (ID 1177) it shows the quest icon symbols in the middle of the pond.

Rework your crappy addon. it's unbearable how often the addon shows faulty icons (felt at every 2nd quest)

And yes. i'm pissed because i can't switch to monkeyquest, the better questaddon. that at least worked correctly in tbc times. while questie is a total bug bunch since tbc.

Translated with www.DeepL.com/Translator (free version)

**Comment by drejjmit** [comment]
It's ok. We don't want you as a user of our free product anyways.
