### ISSUE TITLE
Questie can't initialize

### ISSUE THREAD

**Issue by SunnyJang38** [Questie/Questie#2978]
22:57:32 Questie: [Migration] Migrating Questie for v6.0.0
22:57:32 Questie: [Migration] Migrated Questie to v6.0.0 and removed 0 party entries from the Journey
22:57:32 Questie: [ERROR] 설치중에 에러 발생! Interface\AddOns\Questie\Localization\l10n.lua:37: attempt to index field 'itemData' (a nil value) 

<!-- Error Occured during Install (in Korean)
relogin  after i deleted questie.lua & questie.bak
but same error occured change character

v6.4.0 TBC

**Comment by BreakBB** [comment]
Hey thanks for this report. We already shipped v6.4.1 which should be available soon on CurseForge and so on. You can already grab it off our Discord or [here](https://github.com/Questie/Questie/releases/tag/v6.4.1)
