### ISSUE TITLE
Is there a way to hide the Midsummer event quests?

### ISSUE THREAD

**Issue by SeanSawyers** [Questie/Questie#2979]
Exactly as the title says, is there any way to hide quests that I have not picked up that are event-specific, such as for the Midsummer event? Sorry if this is obvious, I only just started using Questie and other addons.

**Comment by drejjmit** [comment]
Just update to latest version where Midsummer event dates are corrected.

**Comment by BreakBB** [comment]
@SeanSawyers Update to v6.4.1 and they will go away 🙌🏻

**Comment by SeanSawyers** [comment]
> @SeanSawyers Update to v6.4.1 and they will go away 🙌🏻

I'll definitely be sure to update, but I'm talking about even when the event IS active I want to be able to hide them.

**Comment by drejjmit** [comment]
Did you check first options page?

**Comment by SeanSawyers** [comment]
> Did you check first options page?

Ahhhh I see it now. I figured I was just missing something obvious. Thanks!
