### ISSUE TITLE
Ingame error - quest updates not showing on screen + quest items not showing in tracker.

### ISSUE THREAD

**Issue by ERFmama** [Questie/Questie#2980]
## Bug description
13x ...ceQuestie\Modules\Tracker\QuestieTracker.lua:1541: Action[SetPoint] failed because[Failure]: attempted from: Questie_ItemButton2:SetPoint.
[string "=[C]"]: in function `SetPoint'
[string "@Questie\Modules\Tracker\QuestieTracker.lua"]:1541: in function `func'
[string "@Questie\Modules\Libs\QuestieCombatQueue.lua"]:17: in function <...eQuestie\Modules\Libs\QuestieCombatQueue.lua:9>
[string "@SharedXML\C_TimerAugment.lua"]:16: in function <SharedXML\C_TimerAugment.lua:14>

It is there when I log in. I cant' seem to see the quest items anymore on the tracker and the text to update on kills etc on screen are no longer there. 

## Screenshots

![image](https://user-images.githubusercontent.com/24800030/123553247-08dee100-d772-11eb-8c89-ab6ab8ae1953.png)
![image](https://user-images.githubusercontent.com/24800030/123553285-3166db00-d772-11eb-8233-9a1c1695429a.png)

## Questie version
v6.4.1 - TBC

**Comment by BreakBB** [comment]
Hey @ERFmama

Sorry for the late response on this. Looks like some conflict with another addon or Questie simply had a hick up and is in an invalid state.

Did you try to reset Questie? `/questie` -> Advanced -> Reset Questie

**Comment by Laumesis** [comment]
What is this `...ceQuestie` addon? Start of its name is truncated. Do you have two Questie addons running?
Truncated addon name:
`...ceQuestie\Modules\Tracker\QuestieTracker.lua`
`...eQuestie\Modules\Libs\QuestieCombatQueue.lua`
Not truncated Questie addon:
`Questie\Modules\Tracker\QuestieTracker.lua`
`Questie\Modules\Libs\QuestieCombatQueue.lua`

**Comment by BreakBB** [comment]
This is fixed after the latest Tracker reworks.
