### ISSUE TITLE
Error in QuestieLib.lua during initialization

### ISSUE THREAD

**Issue by gcaliber** [Questie/Questie#2981]
> 4x ...rfaceQuestie-BCC\Modules\Libs\QuestieLib.lua:447: bad argument #1 to 'match' (string expected, got nil)
> [string "=[C]"]: in function `match'
> [string "@Questie-BCC\Modules\Libs\QuestieLib.lua"]:447: in function `GetAddonVersionInfo'
> [string "@Questie-BCC\Modules\Libs\QuestieLib.lua"]:462: in function `GetAddonVersionString'
> [string "@Questie-BCC\Modules\MinimapIcon.lua"]:75: in function `OnTooltipShow'

The issue is GetAddOnInfo("Questie") returns nil. Changing this to GetAddOnInfo("Questie-BCC") fixes this error and the addon will load for me.

This started when I updated to 6.4.1. I tried clearing out all the old lua files in WTF, but that didn't do anything. Now this also happens on all the older versions of Questie I tried as well, I guess because previously it had a valid cached name and title.

**Comment by drejjmit** [comment]
Why do you name the folder Questie-BCC?

**Comment by gcaliber** [comment]
> Why do you name the folder Questie-BCC?

I didn't realize that could be the problem. It was how the addon manager named it, so that sounds like the source of the problem.

**Comment by drejjmit** [comment]
What addon manager does this? That's not good.

**Comment by gcaliber** [comment]
> What addon manager does this? That's not good.

I'm using wowa and updating from github and curse both do the same thing. I think it must be lazily looking for a toc file and renaming based on that. I'll close this and report the bug there.
