### ISSUE TITLE
Option to disable icons from the world map and only show them per zone

### ISSUE THREAD

**Issue by ghost** [Questie/Questie#2982]
I'd like an option that let me only show icons per zone instead of on the world map because it makes everything look cluttered. 

Disable them from showing here: 
![2021-06-27 at 16 55 45](https://user-images.githubusercontent.com/45472577/123559176-70902e80-d768-11eb-8bf6-6537638a601e.png)

And have them only show per zone like here: 
![2021-06-27 at 16 56 50](https://user-images.githubusercontent.com/45472577/123559194-8dc4fd00-d768-11eb-8a10-5b438fc19102.png)

**Comment by EricMichaelLP** [comment]
Would be nice. This can also currently be achieved by manually when checking the world map, clicking the top left button to hide questie. But not having to click it each time could be a good QoL option.
