### ISSUE TITLE
Right click Focus or master looter throws error

### ISSUE THREAD

**Issue by Dinoburt** [Questie/Questie#2984]
## Bug description

When right clicking on unit frame to set focus or change loot settings, questie throws error preventing  being able to right click until reload.

## Questie version

Questie, v6.4.1

Date: 2021-06-28 13:06:17
ID: 11
Error occured in: AddOn: Questie
Count: 1
Message: Error: AddOn Questie attempted to call a forbidden function (FocusUnit()) from a tainted execution path.
Debug:
   [string "=[C]"]: FocusUnit()
   [string "@..\FrameXML\UnitPopup.lua"]:1938: func()
   [string "@..\FrameXML\UIDropDownMenu.lua"]:960: UIDropDownMenuButton_OnClick()
   [string "*:OnClick"]:1:
      [string "*:OnClick"]:1
Locals:
None
AddOns:
  Swatter, v1.13.6652 (SwimmingSeadragon)
  WowheadLooter, v20501
  Atlas, vv1.49.01
  AtlasBattlegrounds, vv1.49.00
  AtlasBurningCrusade, vv1.49.00
  AtlasClassicWoW, vv1.49.00
  AtlasDungeonLocs, vv1.49.00
  AtlasTransportation, vv1.49.00
  AtlasLootClassic, vv2.3.1-bcc
  AtlasLootClassicData, vv2.3.1-bcc
  AtlasLootClassicDungeonsAndRaids, vv2.3.1-bcc
  Attune, v236
  AucAdvanced, v1.13.6707 (SwimmingSeadragon)
  AucFilterBasic, v1.13.6680 (SwimmingSeadragon)
  AucScanData, v1.13.6630 (SwimmingSeadragon)
  AucStatHistogram, v1.13.6681 (SwimmingSeadragon)
  AucStatiLevel, v1.13.6705 (SwimmingSeadragon)
  AucStatPurchased, v1.13.6672 (SwimmingSeadragon)
  AucStatSimple, v1.13.6634 (SwimmingSeadragon)
  AucStatStdDev, v1.13.6635 (SwimmingSeadragon)
  AucUtilFixAH, v1.13.6608 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v9.0.7
  BagnonConfig, v
  BeanCounter, v1.13.6682 (SwimmingSeadragon)
  BuffTimers, vv1.5.0
  CharacterStatsTBC, v1.1.0
  ChatCopyPaste, v1.6
  DBMCore, v2.5.7
  DBMPartyBC, v2.5.7
  DBMStatusBarTimers, v
  Details, v
  DetailsTinyThreat, v
  FishingBuddy, v0.7.5.2
  GatherMate2, v1.46.1-classic
  Grid2, v2.0.14
  Grid2LDB, v2.0.14
  Grid2RaidDebuffs, v2.0.14
  GuildRosterManager, v1.9294
  HealBarsClassic, v
  ItemRack, v
  KuiMedia, v
  KuiNameplates, v2.27.3a
  KuiNameplatesCore, v
  LagBar, v5.4
  LeatrixMaps, v2.5.43
  LeatrixPlus, v2.5.43
  LFGBulletinBoard, v2.58
  MikScrollingBattleText, v5.7.152
  NovaWorldBuffs, v2.09
  Questie, v6.4.1
  RepHelperClassic, v2.5.1-release
  ShadowedUnitFrames, vv4.3.1-classic
  SkilletClassic, v1.27
  Stubby, v1.13.6614 (SwimmingSeadragon)
  ThreatClassic2, v2.36
  TomTom, vv3.0.1
  TotemTimers, v1.18.10
  WeakAuras, v3.4.3
  BlizRuntimeLib_enUS v2.5.1.20501 <none>
  (ck=6da)

**Comment by BreakBB** [comment]
Hey @Dinoburt from the error I can see that you had many addons enabled when this issue appeared. Can you try again with just Questie enabled?

We know the current state of the Blizzard UI is pretty easy to break (these issues are called "taint") for addons.

**Comment by Dinoburt** [comment]
@BreakBB  Looks to be something else other than questie. Seems to be something tied to the following that I can't quite seem to narrow down even with addons turned off. Thanks for the guidance on at least the questie front. Hope I can get to the bottom of it. 

Error occured in: Global
Count: 1
Message: ..\FrameXML\UIDropDownMenu.lua line 1084:
   Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: DropDownList1:SetPoint.
Debug:
   [string "=[C]"]: SetPoint()
   [string "@..\FrameXML\UIDropDownMenu.lua"]:1084:
      ..\FrameXML\UIDropDownMenu.lua:975
   [string "=[C]"]: ToggleDropDownMenu()
   [string "@..\FrameXML\SecureTemplates.lua"]:306: handler()
   [string "@..\FrameXML\SecureTemplates.lua"]:616: SecureActionButton_OnClick()
   [string "@..\FrameXML\SecureTemplates.lua"]:656:
      ..\FrameXML\SecureTemplates.lua:648

**Comment by Dinoburt** [comment]
Closing this as a non-questie issue
