### ISSUE TITLE
[35] Suspicious Hoofprints 1268 Doesn't Disappear when Completed

### ISSUE THREAD

**Issue by Danacetia** [Questie/Questie#2985]
## Bug description

I accepted this quest to turn into Krog. After completing it, it won't disappear from my map.

## Screenshots

![World Of Warcraft - Classic Screenshot 2021 06 29 - 13 10 35 66](https://user-images.githubusercontent.com/86680287/123840755-bd951180-d8dc-11eb-97e1-902907f19cb3.png)

## Questie version

v6.3.10

**Comment by BreakBB** [comment]
@Danacetia Did you do a `/reload` after you encountered this?

You are also using a quite old version of Questie. v6.4.1 ist the latest version which adds a possible fix for this issue.
