### ISSUE TITLE
Could We Move the Icon to Not Overlap Other Addons

### ISSUE THREAD

**Issue by Danacetia** [Questie/Questie#2986]
## Description

I also download LFG Bulletin Board. Both Questie and LFG Bulletin Board overlap each other. Is there a way to move the icons on the map to not have them overlap. If not, could it be programmed to be able to do so?

![World Of Warcraft - Classic Screenshot 2021 06 29 - 13 22 42 39](https://user-images.githubusercontent.com/86680287/123841402-82471280-d8dd-11eb-9f48-cbe6e09ccb21.png)

**Comment by drejjmit** [comment]
Did you try drag and drop?

**Comment by BreakBB** [comment]
@Danacetia as Drejjmit already said: You can move the icons by simply dragging them around the minimap. For some icons you have to hold the `Shift` or `Crtl` button while dragging.
