### ISSUE TITLE
Could Questie Show the Fire Festival Icons in July in TBC Classic?

### ISSUE THREAD

**Issue by Danacetia** [Questie/Questie#2987]
## Question

I read somewhere that the Midsummer Fire Festival was postponed until July for TBC Classic servers because TBC was launched in June. I have those icons for the holiday event displayed now on my map. I'm more hoping that the markers will be available when the MFF happens in July.

**Comment by BreakBB** [comment]
@Danacetia As already wrote in #2985 you are using an outdated version of Questie. We already postponed the Midsummer festival for a month.
