### ISSUE TITLE
The Bladespire Threat - Enemies misnamed in hover tab

### ISSUE THREAD

**Issue by phocito** [Questie/Questie#2988]
## Description

Bladespire Ogres objective shows when hovering over raptors, and vice versa.

## Wowhead link

https://tbc.wowhead.com/quest=10503/the-bladespire-threat
https://tbc.wowhead.com/npc=20728/bladespire-raptor

## Screenshots

![1](https://user-images.githubusercontent.com/86697472/123890060-3a93ab80-d91c-11eb-8bb0-b1dc380b3d1d.PNG)
![2](https://user-images.githubusercontent.com/86697472/123890061-3b2c4200-d91c-11eb-96c4-8fd3ed1a46e4.PNG)

## Questie version

Version: 6.3.16

**Comment by BreakBB** [comment]
@phocito You are using an outdated version of Questie. This bug is fixed in the latest version, please update.
