### ISSUE TITLE
Questie dont show maps on outlands. Old map is ok

### ISSUE THREAD

**Issue by wojt5** [Questie/Questie#2991]

**Comment by wojt5** [comment]
it happend on my boosted oppositew faction char on another account. I tried deletingWTF files as reseting questie in options nothing works

**Comment by BreakBB** [comment]
@wojt5 Please share a screenshot of what you are experiencing. Deleting all `Questie.lua` and `Questie.lua.bak` files in the WTF folder is a hard reset and should always work. Make sure to close WoW before deleting these files.

**Comment by drejjmit** [comment]
Check if you have a ``QuestieDev-master`` folder inside your ``AddOns`` folder.
It can load very old versions of Questie when you create a new character if you have multiple installs.
