### ISSUE TITLE
Shift click not linking quest in chat

### ISSUE THREAD

**Issue by xiaopigu** [Questie/Questie#2994]
## Description
I am unable to shift click a quest and link it in chat. Only the texts shows up, not the link. This only happened recently, within the past few weeks. I tried reloading addons, deleting and reinstalling questie, only enabling questie, and enabling questie and tukui. In all instances I was not able to shift click to link a quest, it only showed the text.

## Questie version
latest version, 6.4.1

Edit: ignore everything on top, I just had to turn on questie tracker in settings

**Comment by BreakBB** [comment]
@xiaopigu It sounds really strange, that it does not work with just Questie enabled.

Do you play Classic Era oder TBC?

**Comment by xiaopigu** [comment]
My apologies, turns out the setting to turn on questie’s tracker was turned off and I just had to check it.

**Comment by TiberiusPendraco** [comment]
I'm having this problem and I've got the hooks option ticked. Can anyone help me out? Really bugging me that I can't link things from the tracker into chat anymore..

**Comment by BreakBB** [comment]
> I'm having this problem and I've got the hooks option ticked. Can anyone help me out? Really bugging me that I can't link things from the tracker into chat anymore..

Hey there, could you open up a new issue for this and share a screenshot of your settings with it?
