### ISSUE TITLE
Quest: The Absent Minded Prospector - incorrect minimum level

### ISSUE THREAD

**Issue by teelolws** [Questie/Questie#2998]
## Description

Quest requires Level 15 but Questie is showing its available at Level 14.

## Wowhead link

https://tbc.wowhead.com/quest=729/the-absent-minded-prospector

## Screenshots

![image](https://user-images.githubusercontent.com/49792789/124212468-1cf45b00-db43-11eb-9a16-a95df98b95d1.png)

## Questie version

6.4.1

**Comment by BreakBB** [comment]
Thanks for this report @teelolws

Will be easy to fix and included in the next release 👍🏻

**Comment by drejjmit** [comment]
806841fb17433eafbbb6a41f880733851eb8230b
