### ISSUE TITLE
The Weathered Grave quest appears on the Minimap but not the Map

### ISSUE THREAD

**Issue by SeanSawyers** [Questie/Questie#2999]
The quest [The Weathered Grave](https://tbc.wowhead.com/quest=225/the-weathered-grave) correctly appears on the Minimap, but not on the Map. Tried reloading/toggling/hiding/etc. Questie with no luck. On most recent version.
![Quest](https://user-images.githubusercontent.com/61792546/124214289-f5a87a00-dabf-11eb-9bb8-2fd685b33470.png)

**Comment by BreakBB** [comment]
The minimap icon you see is wrong the default UI.

At first glace it looks like we have the wrong min level in our database. An old wowhead comment says level 28 is the min level, but it should be 25.

Mabye @drejjmit can take care of this?
