### ISSUE TITLE
Quest: Creatures of the Eco Domes (quest=10427)

### ISSUE THREAD

**Issue by c4ck4** [Questie/Questie#3002]
First, amazing addon, thank you so much for all the work you put into maintaining Questie.

## Description

Missing objective marker for:
Creatures of the Eco Domes (quest=10427)
Talbuk Doe is working properly as a quest objective.
Talbuk Sires  are an additional quest objective that can also be tagged with Talbuk Tagger (item=29817)

## Wowhead link
https://tbc.wowhead.com/npc=20777/talbuk-sire

## Questie version
v6.4.1

**Comment by BreakBB** [comment]
Fixed with 04cf00575271947d488737164a4df7e383f826e0
