### ISSUE TITLE
Initializing Error

### ISSUE THREAD

**Issue by Flirpado** [Questie/Questie#3003]
Hello, i have updated Questie to the version v6.4.1 but now when i start to play with my Blood Elf paladin this error comes to my screen. The thing is that if i enter with my Tauren Druid this error does not happen. This is a screenshot of the error, i tried some solutions i found on the web but nothing fix it.

![unknown1](https://user-images.githubusercontent.com/86883051/124357186-7da29700-dc1a-11eb-9262-06e69f1bd288.png)

**Comment by rapidrespond** [comment]
I am having the same issue, ive removed it, reinstalled it through curseforge, then manually and still getting the error.  Everything is as it should be as far as i can tell but still getting the error.

**Comment by Onetail123** [comment]
Also seeing this issue started around 10:30am EST on Blood Elf paladin when I hit lvl 45 currently questing in Stranglethorn

**Comment by Onetail123** [comment]
Check that. I messed around with disabling and enabling a combination of addons bc i also saw my map was not populating correctly even with Questie off. This is actually a defect with ExtendedCharacterSheet. If you turn off ExtendedCharacterSheet on your paladin, questie works fine.

**Comment by Flirpado** [comment]
It works! Thank you so much! 

I thought that maybe was another addon messing around but i updated like 7-8 this morning and in other characters Questie was fine. Anyway I prefer Questie than Extended CharacterSheet!

**Comment by BreakBB** [comment]
Sorry @Flirpado and @rapidrespond and also @Onetail123 for the broken ECS update. Roll back to v2.8.7 for now I will release a new version once I am back at home.
