### ISSUE TITLE
variable collision in global namespace with other addons

### ISSUE THREAD

**Issue by orionshock** [Questie/Questie#3004]
## Bug description
Error On Load

Questie: [ERROR] Error during initialization! Interface\AddOns\Questie\Database\QuestieDB.lua:636: attempt to call global 'mod' (a number value)

## Questie version
Latest : 6.4.1-tbc

In QuestieDB.lua:636 - is calling a global variable "mod()". There is no variable declaration for "mod" anywhere in the file.

[10:37 AM] Dump: mod
[10:37 AM] mod=3
[10:38 AM] Dump: value=issecurevariable("mod")
[10:38 AM] [1]=false,
[10:38 AM] [2]="ExtendedCharacterStats"

apparently there is a variable collision with other addons.

**Comment by syntruth** [comment]
You literally just saved us some headaches; GF had the same issue, turned off ExtendedCharacterStats, and things are fine now.

**Comment by orionshock** [comment]
https://github.com/BreakBB/ExtendedCharacterStats/issues/144#issue-936299372

typo and update from ECS :)

**Comment by orionshock** [comment]
as this is ECS causing problems by overwriting a default math function - im going to close this.

**Comment by BreakBB** [comment]
Sorry @orionshock for the broken ECS update. Roll back to v2.8.7 for now I will release a new version once I am back at home.
