### ISSUE TITLE
Scalding Mornbrew Delivery show Abandoned after completion.

### ISSUE THREAD

**Issue by Cynthian73** [Questie/Questie#3006]
## Description
Completed the quest to deliver the Durnan's Scalding Mornbrew to Durnan Furcutter before the 5 minutes.  He then asks me to return Nori's Mug to  Nori Pridedrift which I was able to complete. When looking in My Journey - shows the quest as Abandoned.

## Wowhead link
https://classic.wowhead.com/quest=3364/scalding-mornbrew-delivery
https://classic.wowhead.com/quest=3365/bring-back-the-mug

## Screenshots

![WoWScrnShot_070521_133902](https://user-images.githubusercontent.com/86979035/124505027-a059ba80-dd96-11eb-9960-c256c7a0e116.jpg)

## Questie version
Questie 6.4.1

**Comment by Laumesis** [comment]
Fixed with #3111
