### ISSUE TITLE
"A Somber Task" shows as Abandoned after completion (TBC Classic)

### ISSUE THREAD

**Issue by DeuzenFIN** [Questie/Questie#3008]
After completing the quest "A Somber Task" in TBC Classic, My Journey marks it as _abandoned_, thus retaining the quest icon on the map.

Quest in question:
https://tbc.wowhead.com/quest=8473/a-somber-task

Screenshot:
![WowClassic 2021-07-07 11-40-15](https://user-images.githubusercontent.com/56039877/124728867-9bbd0f80-df18-11eb-980c-adf4e931981a.png)

**Comment by BreakBB** [comment]
I am merging this with #3006 since it is a Questie bug which is not easy to reproduce for us. But we are on it, thanks for reporting it!
