### ISSUE TITLE
Draenai Quest Start Item

### ISSUE THREAD

**Issue by SunnyJang38** [Questie/Questie#3009]
Draenai Quest Start Item
23850
23678
23900
24414
23759
23870

**Comment by BreakBB** [comment]
Hey @SunnyJang38 can you explain a bit more in detail what the issue is with these quest IDs? And what version you are running?

**Comment by SunnyJang38** [comment]
it's kind of "[Gold Pickup Schedule](https://classic.wowhead.com/item=1307/gold-pickup-schedule)" in elwynn forest

**Comment by BreakBB** [comment]
Oh I see, so you want to say that these questIds are not shown on the map and they are started off an item that "randomly" drops off mobs?

We hide several quests atm, because showing them would flood the map with icons for most of them (too many mobs can possibly drop the item).

**Comment by SunnyJang38** [comment]
just want Quesite Said "xxxx is quest start item" when i get it
