### ISSUE TITLE
"Trouble at the Underlight Mines" shows as Abandoned after completion

### ISSUE THREAD

**Issue by DeuzenFIN** [Questie/Questie#3010]
## Description
After turning in the quest "Trouble at the Underlight Mines", My Journey considers it _abandoned_ and thus the quest marker persists.

## Wowhead link
https://tbc.wowhead.com/quest=9192/trouble-at-the-underlight-mines

## Screenshots
![WowClassic 2021-07-07 21-05-01](https://user-images.githubusercontent.com/56039877/124807965-07c66480-df67-11eb-8a97-0ccee07aa308.png)

## Questie version
v6.4.1

**Comment by BreakBB** [comment]
You can solve this with a `/reload`.

But it is bad that it still happens... We tried to fix this but it is very, very hard for us to test.

**Comment by BreakBB** [comment]
Also @DeuzenFIN are you sure you were using v6.4.1 when you experienced this issue?

**Comment by DeuzenFIN** [comment]
Should be, at least according to the pop-up.
![WowClassic 2021-07-08 15-32-25](https://user-images.githubusercontent.com/56039877/124922040-c20aaa00-e001-11eb-9efc-1eef0013c770.png)

**Comment by BreakBB** [comment]
Also merging this with #3006
