### ISSUE TITLE
Delete and remaking character does not reset class trainers.

### ISSUE THREAD

**Issue by joce55** [Questie/Questie#3011]
## Bug description

I deleted a low level Hunter and used the same character name for a Shaman. If I track class trainer on the map/minimap, it will still show the Hunter trainers, and will not switch to Shaman.

## Questie version

v6.4.1

**Comment by BreakBB** [comment]
@joce55 Yeah this is a real edge case and not handled gracefully in Questie.

You can always recompile the database to fix such issues though:

`/questie` -> Advanced -> Recompile Database
