### ISSUE TITLE
"[QuestieQuest] [Tooltips] Error happened while creating objectives 10607 No error"

### ISSUE THREAD

**Issue by Vloz** [Questie/Questie#3012]
## Bug description
Having the message box being spam at every loading, the problem came with tbc classic.
The message itself is translated (as i am playing in french) must be something like this in english:
`Questie: [ERROR] [QuestieQuest]: vXXXX - An error occured during the creation of objectives for *Name of the quest* 10607 X No error`

## Screenshots
![image](https://user-images.githubusercontent.com/2368643/124956032-dc4f8280-e017-11eb-8610-4b3bbc5ea5b8.png)

## Questie version
v6.3.12 (but occur since tbc classic)

**Comment by drejjmit** [comment]
You're 6 versions out of date.
