### ISSUE TITLE
Too many Error

### ISSUE THREAD

**Issue by SunnyJang38** [Questie/Questie#3024]
18x Questie\Modules\Libs\QuestieLib.lua:257: bad argument #1 to 'unpack' (table expected, got nil)
[string "=[C]"]: in function `unpack'
[string "@Questie\Modules\Libs\QuestieLib.lua"]:257: in function `GetTbcLevel'
[string "@Questie\Modules\Tooltips\ChatFilter.lua"]:35: in function `filterFunc'
[string "@Prat-3.0-3.9.1-6-f65d85e\services\chatsections.lua"]:49: in function <Prat-3.0\services\chatsections.lua:41>
[string "@Prat-3.0-3.9.1-6-f65d85e\services\chatsections.lua"]:340: in function `SplitChatMessage'
[string "@Prat-3.0-3.9.1-6-f65d85e\addon\addon.lua"]:639: in function <Prat-3.0\addon\addon.lua:613>
[string "=(tail call)"]: ?
[string "@FrameXML\ChatFrame.lua"]:2930: in function `ChatFrame_OnEvent'
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>

Locals:
(*temporary) = nil
(*temporary) = "table expected, got nil"

**Comment by BreakBB** [comment]
Hey @SunnyJang38 you should checkout the TBC version of Prat https://www.curseforge.com/wow/addons/prat-tbc/files

**Comment by SunnyJang38** [comment]
it's solved changed chat addon NOT prat. (prat-tbc same error)

**Comment by BreakBB** [comment]
Glad you got it fixed 👍🏻
