### ISSUE TITLE
My Journey reset

### ISSUE THREAD

**Issue by ddiewer** [Questie/Questie#3028]
Hi,

I recently created a new character with the same name as one of my old characters which I had deleted. When looking under the 'My Journey' tab I noticed it transferred the data over from my old, deleted character to my new character or something, idk what I'm talking about. Anyway, is there a way to reset this data, so the feature can track my new character. Thank you.

**Comment by BreakBB** [comment]
Hey @ddiewer 

Try `/run Questie.db.char.journey = nil` and then do a `/reload` on the character you want your Journey to be cleared.
