### ISSUE TITLE
This Error Just Pops UP

### ISSUE THREAD

**Issue by Comicus** [Questie/Questie#3034]
## Bug description

Error just pops up when moving mouse over quests

## Screenshots

76x [ADDON_ACTION_BLOCKED] AddOn 'Questie' tried to call the protected function 'Questie_TrackedQuests:ClearAllPoints()'.
!BugGrabber\BugGrabber.lua:519: in function <!BugGrabber\BugGrabber.lua:519>
[C]: in function `ClearAllPoints'
...ceQuestie\Modules\Tracker\QuestieTracker.lua:593: in function `Update'
...ceQuestie\Modules\Tracker\QuestieTracker.lua:1228: in function `Update'
...ceQuestie\Modules\Tracker\QuestieTracker.lua:2398: in function <...ceQuestie\Modules\Tracker\QuestieTracker.lua:2383>
SharedXML\C_TimerAugment.lua:16: in function <SharedXML\C_TimerAugment.lua:14>

Locals:
InCombatSkipped

**Comment by BreakBB** [comment]
Hey @Comicus can you to do a `/reload` and see if that helps?

And you should also try to disable all other addons and see if that issue still pops up.

If you can reproduce it consistently please add a list of steps for us!

**Comment by Villefrance** [comment]
Experienced the same issue. The culprit (for me) seems to be Luna Unit Frames. I haven't experienced the error since I disabled that addon.

**Comment by Comicus** [comment]
Need to go thru all my addons (have quite a few)
