### ISSUE TITLE
Questie not loading properly. Error during initialization!

### ISSUE THREAD

**Issue by THERUSSIANDANE** [Questie/Questie#3043]
## Bug description
questie not loading properly

## Screenshots
![Capture](https://user-images.githubusercontent.com/87785204/126564822-90e34a96-ac82-4495-8126-31c187c41493.JPG)

## Questie version
Questie-v6.5.0-tbc

**Comment by zach710** [comment]
I am experiencing the same issue since updating to 6.5.0

**Comment by drejjmit** [comment]
Restart your client after updating should be enough to fix this.

**Comment by lloskka** [comment]
> Restart your client after updating should be enough to fix this.

Not, it does not.

Clean install, clean reboot of computer and of course client reset.

**Comment by drejjmit** [comment]
Try to reinitialize Questie with this command ingame:
```/run QuestieLoader:ImportModule("QuestieOptions").tabs.advanced:Initialize().args.questieReset.func()```

**Comment by lloskka** [comment]
Same result with same message as OP stated.

**Comment by Rychard** [comment]
I was able to resolve this issue by deleting the `Questie` folder and re-installing the addon.

**Comment by BreakBB** [comment]
You should try `/run Questie.db.global.dbIsCompiled = false` and then do a `/reload`.

It really is important to close WoW before updating your addons or restart it right away. This does not only affect Questie but can screw up any addon.

**Comment by temporaldoom** [comment]
I fixed this by doing the following

/run Questie.db.global.dbIsCompiled = false
/reload

closed down client completely, deleted the existing questie addon folder and unpacked the latest questie again into the addons folder

**Comment by Bagiraa** [comment]
Got the same error, fixed by deleting Questie folder and re extract.

But now i have another error "Questie: [ERROR] Missing objective data for quest 11886 and objective Twilight Correspondence"

**Comment by BreakBB** [comment]
Hey @Bagiraa could you open up a separate issue for this? Your second issue has nothing to do with the initial issue of this post.

**Comment by BreakBB** [comment]
Assuming this is fixed.
