### ISSUE TITLE
Errors after update

### ISSUE THREAD

**Issue by Prefo** [Questie/Questie#3045]
Hi, after updating Questie to the newest version i got the following Error Message.

[09:27] ...ce\AddOns\Questie\Modules\FramePool\QuestieFrame.lua:405: attempt to call method 'IsActiveDailyQuest' (a nil value) 
 [09:27] [string "@Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua"]:982: in function `IsActiveDailyQuest'
[string "@Interface\AddOns\Questie\Modules\FramePool\QuestieFrame.lua"]:405: in function `ShouldBeHidden'
[string "@Interface\AddOns\Questie\Modules\Map\QuestieMap.lua"]:617: in function `DrawWorldIcon'
[string "@Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua"]:921: in function <...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:868>
[string "@Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua"]:766: in function <...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:697>
[string "=[C]"]: in function `xpcall'
[string "@Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua"]:980: in function <...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:978>
[string "@Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua"]:1033: in function `PopulateObjectiveNotes'
[string "@Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua"]:392: in function `val'
[string "@Interface\AddOns\Questie\Modules\TaskQueue.lua"]:8: in function <Interface\AddOns\Questie\Modules\TaskQueue.lua:6>
 
 [09:27] Questie: [ERROR] [QuestieQuest]: v6.5.0 - There was an error populating objectives for Scaring Shaky 606 1 No error 

Hoping it helps you to identify the issue!

Thanks for all your work, have a nice day!

**Comment by drejjmit** [comment]
Did you restart your client after updating? 
If that isn't enought, try this command ingame to reinitialize Questie:
```/run QuestieLoader:ImportModule("QuestieOptions").tabs.advanced:Initialize().args.questieReset.func()```
