### ISSUE TITLE
QuestieNameplate.lua's "UpdateNameplate()" attempts to update nameplates too soon, leads to bugged plates.

### ISSUE THREAD

**Issue by Bananaman** [Questie/Questie#3051]
Very simple bug report:

1. Event handler triggers the "quest progress changed" event.
2. It in turn instantly calls `QuestieNameplate:UpdateNameplate()`
3. Which in turn instantly loops through all active nameplates and runs the `_GetValidIcon()` function for them, and changes icon based on its result.
4. Which in turn calls the `:Update()` function to refresh the latest quest log data for each objective that's being tracked.
5. Therein lies the problem. This is all happening too fast. By the time the first plates are being updated, the `_GetValidIcon()` still returns an icon. And by the time the final plates are being updated, it returns nothing.

This leads to lingering icons that "hang on" to some of the NPCs.

Let's say you are surrounded by 4 NPCs. All have the "loot item" icon. You kill 1 of them and loot it.

The code will then loop through the remaining 3 living NPCs, and it will look something like this:

- NPC 1: `_GetValidIcon()` result = Keep "Loot" icon.
- NPC 2: `_GetValidIcon()` result = Keep "Loot" icon.
- NPC 3: `_GetValidIcon()` result = Delete icon.

So two of the three NPCs still have lingering icons.

Solution: Perhaps make `QuestieNameplate:UpdateNameplate()` start a 1 second timer of a processing callback (so that the quest log has time to refresh its cached state in the client) and THEN loop through all plates and update them.

In fact, an improved solution: Start ONE 1-second timer. And if any other `UpdateNameplate()` events happen while that timer is queued, de-queue it and start a new 1-second timer. Meaning, if the player loots multiple mobs really quickly, the nameplates won't be processed and refreshed until 1 second AFTER the final quest log update event. This cuts down on the amount of wasteful processing.

**Comment by Bananaman** [comment]
The optimal solution can be achieved via https://wowpedia.fandom.com/wiki/API_C_Timer.NewTicker (read the `C_Timer.NewTimer()` notes), which creates a single-tick, cancelable timer.

1. Just `:Cancel()` any previous timer.
2. Create a new 1-second timer.
3. Repeat step 1 and 2 every time the `QuestieNameplate:UpdateNameplate()` function fires.
4. Eventually, when the updates have stopped firing, the final timer will be allowed to finish its countdown and will execute the nameplate updates. And the bug will be fixed.

**Comment by Bananaman** [comment]
After some testing, 1 second does feel a tiny bit sluggish. 0.5 seconds also fixes the bug and feels completely perfect. Therefore I recommend `NewTimer(0.5,` instead. Fixing the nameplate icon bug is the main concern, so 0.5 is proper. The reduction of processing when mass-looting (which 1 second handles better) was just a bonus.

**Comment by BreakBB** [comment]
This was fixed with the refactoring of our event system in 997d1b451df8ffb2a6c5b63448c3772086296b6f
