### ISSUE TITLE
Error after updating to the latest version

### ISSUE THREAD

**Issue by anton-andreenko** [Questie/Questie#3052]
## Bug description
Hello!
After updating Questie (TBC) from version 6.4.1 to version 6.5.0 - an error appeared.
```
Usage:
_RegisterComm("eventname", "methodname"): "methodname" - method 'OnCommReceived' not found on self.
```

## Screenshots
![questie_error](https://user-images.githubusercontent.com/25147895/126826996-ab9e342f-2d68-44fe-b9ed-7f49b30ac105.png)

## Questie version
Version: 6.5.0

**Comment by drejjmit** [comment]
You need to restart your client after updating addons.

**Comment by anton-andreenko** [comment]
Thx!
