### ISSUE TITLE
LUA error with latest version

### ISSUE THREAD

**Issue by GregoryGH** [Questie/Questie#3054]
2x Questie\Modules\Libs\QuestieLib.lua:257: bad argument #1 to 'unpack' (table expected, got nil)
[string "=[C]"]: in function `unpack'
[string "@Questie\Modules\Libs\QuestieLib.lua"]:257: in function `GetTbcLevel'
[string "@Questie\Modules\Libs\QuestieLib.lua"]:176: in function <Questie\Modules\Libs\QuestieLib.lua:174>
[string "@HarmlessQuestRep\HarmlessQuestRep-0.1.lua"]:120: in function `GetColoredQuestName'
[string "@Questie\Modules\QuestLinks\Link.lua"]:66: in function `GetQuestHyperLink'
[string "@Questie\Modules\QuestLinks\ChatFilter.lua"]:38: in function `filterFunc'
[string "@Prat-3.0-3.9.1-6-f65d85e\services\chatsections.lua"]:49: in function <Prat-3.0\services\chatsections.lua:41>
[string "@Prat-3.0-3.9.1-6-f65d85e\services\chatsections.lua"]:340: in function `SplitChatMessage'
[string "@Prat-3.0-3.9.1-6-f65d85e\addon\addon.lua"]:639: in function <Prat-3.0\addon\addon.lua:613>
[string "=(tail call)"]: ?
[string "@FrameXML\ChatFrame.lua"]:2930: in function `ChatFrame_OnEvent'
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>

**Comment by Laumesis** [comment]
Seems duplicate of #3036 - please check if fixes suggested in that issue are working for you and report back

**Comment by GregoryGH** [comment]
Havent done anything but dont see any errors anymore. May be it related to midsummer quests because ive got errors while doing this quests.

**Comment by BreakBB** [comment]
Will close this, but feel free to open up a new issue if you experience anything odd again @GregoryGH
