### ISSUE TITLE
Error with release 6.5

### ISSUE THREAD

**Issue by neodata83** [Questie/Questie#3057]
Getting load errors with the new release

> 1x Questie\Database\QuestieDB.lua:490: attempt to call method 'IsActiveDailyQuest' (a nil value)
> [string "@Questie\Database\QuestieDB.lua"]:490: in function `IsDoable'
> [string "@Questie\Modules\Quest\QuestieQuest.lua"]:1449: in function <Questie\Modules\Quest\QuestieQuest.lua:1433>
> [string "@SharedXML\C_TimerAugment.lua"]:16: in function <SharedXML\C_TimerAugment.lua:14>
> 
> Locals:
> self = <table> {
>  FactionGroup = "Alliance"
>  questDataOverrides = <table> {
>  }
>  _QueryItemSingle = <function> defined @Questie\Database\compiler.lua:1130
>  itemCompilerOrder = <table> {
>  }
>  questKeys = <table> {
>  }
>  npcFlags = <table> {
>  }
>  objectDataOverrides = <table> {
>  }
>  _npcAdapterQueryOrder = <table> {
>  }
>  NPCPointers = <table> {
>  }
>  IsActiveEventQuest = <function> defined @Questie\Database\QuestieDB.lua:361
>  ObjectPointers = <table> {
>  }
>  IsComplete = <function> defined @Questie\Database\QuestieDB.lua:336
>  factionTemplate = <table> {
>  }
>  IsParentQuestActive = <function> defined @Questie\Database\QuestieDB.lua:406
>  objectKeys = <table> {
>  }
>  questCompilerTypes = <table> {
>  }
>  objectKeysReversed = <table> {
>  }
>  QueryNPC = <function> defined @Questie\Database\QuestieDB.lua:131
>  _QueryQuestSingle = <function> defined @Questie\Database\compiler.lua:1130
>  QuestPointers = <table> {
>  }
>  GetQuestsByZoneId = <function> defined @Questie\Database\QuestieDB.lua:1077
>  itemKeys = <table> {
>  }
>  GetQuestTagInfo = <function> defined @Questie\Database\QuestieDB.lua:323
>  GetNPC = <function> defined @Questie\Database\QuestieDB.lua:1015
>  _itemAdapterQueryOrder = <table> {
>  }
>  IsRaidQuest = <function> defined @Questie\Database\QuestieDB.lua:295
>  npcDataOverrides = <table> {
>  }
>  GetQuest = <function> defined @Questie\Database\QuestieDB.lua:579
>  questCompilerOrder = <table> {
>  }
>  npcKeys = <table> {
>  }
>  itemDataOverrides = <table> {
>  }
>  raceKeys = <table> {
>  }
>  questKeysReversed = <table> {
>  }
>  fakeTbcItemStartId = 40000
>  IsRepeatable = <function> defined @Questie\Database\QuestieDB.lua:354
>  classKeys = <table> {
>  }
>  objectCompilerTypes = <table> {
>  }
>  QueryItemSingle = <function> defined @Questie\Database\QuestieDB.lua:131
>  sortKeys = <table> {
>  }
>  QueryObjectSingle = <function> defined @Questie\Database\QuestieDB.lua:131
>  IsPvPQuest = <function> defined @Questie\Database\QuestieDB.lua:302
>  QueryQuestSingle = <function> defined @Questie\Database\QuestieDB.lua:131
>  _QueryItem = <function> defined @Questie\Database\compiler.lua:1156
>  _QueryObject = <function> defined @Questie\Database\compiler.lua:1156
>  Initialize = <function> defined @Questie\Database\QuestieDB.lua:146
>  QueryObject = <function> defined @Questie\Database\QuestieDB.lua:131
>  ItemPointers = <table> {
>  }
>  _QueryQuest = <function> defined @Questie\Database\compiler.lua:1156
>  _QueryNPC = <function> defined @Questie\Database\compiler.lua:1156
>  _QueryObjectSingle = <function> defined @Questie\Database\compiler.lua:1130
>  _QueryNPCSingle = <function> defined @Questie\Database\compiler.lua:1130
>  QueryItem = <function> defined @Questie\Database\QuestieDB.lua:131
>  npcCompilerOrder = <table> {
>  }
>  QueryQuest = <function> defined @Questie\Database\QuestieDB.lua:131
>  GetZoneOrSortForClass = <function> defined @Questie\Database\QuestieDB.lua:315
>  IsLevelRequirementsFulfilled = <function> defined @Questie\Database\QuestieDB.lua:384
>  IsProfessionQuest = <function> defined @Questie\Database\QuestieDB.lua:471
>  _CreatureLevelCache = <table> {
>  }
>  IsPreQuestSingleFulfilled = <function> defined @Questie\Database\QuestieDB.lua:447
>  private = <table> {
>  }
>  IsDungeonQuest = <function> defined @Questie\Database\QuestieDB.lua:288
>  IsPreQuestGroupFulfilled = <function> defined @Questie\Database\QuestieDB.lua:418
>  IsDoable = <function> defined @Questie\Database\QuestieDB.lua:478
>  GetCreatureLevels = <function> defined @Questie\Database\QuestieDB.lua:971
>  IsExclusiveQuestInQuestLogOrComplete = <function> defined @Questi

Questie: [ERROR] Error during initialization! Usage: _RegisterComm("eventname", "methodname"): 'methodname' - method 'OnCommReceived' not found on self.

**Comment by drejjmit** [comment]
Always restart your client after updating addons.
If this does not work. Delete Questie folder and reinstall Questie.
