### ISSUE TITLE
Lua error on the last version ( v6.5.0 TBC )

### ISSUE THREAD

**Issue by ftabarie** [Questie/Questie#3059]
## Bug description
After the install, Questie asked to reinitialized data, things done, and now I have this on every char

```
Questie: [ERROR] Error during initialization! Usage: _RegisterComm("eventname", "methodname"): 'methodname' - method 'OnCommReceived' not found on self. 
```

I tried a 
`/run QuestieLoader:ImportModule("QuestieOptions").tabs.advanced:Initialize().args.questieReset.func()`

but here is the result

```
Questie: [Migration] Migrating Questie for v6.0.0 
Questie: [Migration] Migrated Questie to v6.0.0 and removed 0 party entries from the Journey 
Questie DB has updated! Data is being processed, this may take a few moments and cause some lag... 
 [1/7] Loading database... 
 [2/7] Applying database corrections... 
 [3/7] Initializing locale... 
 [4/7] Updating NPCs... 
[Questie] The 'Midsummer' world event is active! 
 [5/7] Updating objects... 
 [6/7] Updating quests... 
 [7/7] Updating items... 

Questie DB update complete! 
Questie: [ERROR] Error during initialization! Usage: _RegisterComm("eventname", "methodname"): 'methodname' - method 'OnCommReceived' not found on self. 
```
stil the same issue

## Screenshots
![WoWScrnShot_072421_164552](https://user-images.githubusercontent.com/6246773/126872112-1d253869-fa6e-4a02-b0f4-0997a65362dd.jpg)

## Questie version
 v6.5.0 TBC

**Comment by drejjmit** [comment]
Always restart your client after updating addons.
If this does not work. Delete Questie folder and reinstall Questie.

**Comment by ftabarie** [comment]
Thx bro, I just deleted the folder then reinstall it and now it works.
Is this because a conflict is present from an older version ?

**Comment by Laumesis** [comment]
@ftabarie 
Addons have a .toc file telling which files the game should load for an addon. Those .toc files are read and parsed **only** at start of the game. If a character has the addon enabled, then files told in .toc file are read **always** when the character logins or interface is reloaded (/reload).
