### ISSUE TITLE
Quests / Objectives Errors.

### ISSUE THREAD

**Issue by Umbraemoon** [Questie/Questie#3062]
Error messages when accepting new Quests and Objectives of all types unavailable on WorldMap.
![QuestieUpdated-ErrorMessages](https://user-images.githubusercontent.com/87947957/126910616-d70f67e4-27d0-4294-a789-c6f47c8a91f4.png)

**Comment by Umbraemoon** [comment]
Disabled Attuned! in case addons were interfering with each others processes.  
  Same error appeared once new quest was accepted.
(Both addons have been updated today for TBC use).
![QuestieUpdated-ErrorMessages-AttuneDisabled](https://user-images.githubusercontent.com/87947957/126910723-df5fb62a-45bc-4026-99df-d20a6ac7ad2e.png)

**Comment by Umbraemoon** [comment]
Login / Reload Error message.
![QuestieUpdated-ErrorMessages-Reload](https://user-images.githubusercontent.com/87947957/126910812-9c96a50c-3865-4cab-9ca1-13930e54e3ee.png)

**Comment by Umbraemoon** [comment]
Attempts to access Questie interface -- entirely non-responsive.

**Comment by drejjmit** [comment]
Always restart your client after updating addons.
If this does not work. Delete Questie folder and reinstall Questie.
