### ISSUE TITLE
Daily quest objectives not appearing in map or minimap

### ISSUE THREAD

**Issue by dlecina** [Questie/Questie#3065]
## Bug description
Since the latest update, I have not been able to see any daily quest objectives in the map. Daily exclamation marks still work, as do regular (non-daily) quest objectives.

## Screenshots
![image](https://user-images.githubusercontent.com/1137825/127014280-a025e202-3fe7-4792-bcfb-8985bfc2a17f.png)

## Questie version
Questie v6.5.0

**Comment by dlecina** [comment]
May be related (or not):
```Daily quests are now filtered to only show the active ones (Big thanks to the Reputable team!)```
I have noticed that the exclamation mark icon shows a different quest that the one actually active, at least on my realm (EU - Mandokir). Perhaps this mismatch is also filtering the map icons?

Even if the quests are matching correctly on some other realm, it may be worth testing if the icons still appear if you do not complete the daily within the day it's active (and instead decide to complete it some other day).

**Comment by PontusNyberg** [comment]
i have the same issue.
