### ISSUE TITLE
Missing From Questie Database

### ISSUE THREAD

**Issue by bearaujus** [Questie/Questie#3066]
![Screenshot 2021-07-27 021221](https://user-images.githubusercontent.com/64161364/127045302-972e4069-fcf6-4354-ae86-ff5b8ac36f6b.png)

**Comment by BreakBB** [comment]
@bearaujus You should update to v6.5.0

8e39fc324277d74993e3eb2b0342b63dffc3143e already added this quest.

If you are already using v6.5.0 and do `/questie` -> Advanced -> Recompile database
