### ISSUE TITLE
Quest [66] The Bladespire Threat

### ISSUE THREAD

**Issue by Matroyzy** [Questie/Questie#3068]
Quest look like this:

[66] The Bladespire Threat
Bladespire Ogres Killed: 0/30
Bladespire Raptor: 0/10

When I hover my mouse over a raptor it shows the encounter of "Bladespire Ogres Killed: 0/30" and same otherwise when I hover over a Orge it shows "Bladespire Raptor: 0/10"

Simply it shows the wrong quest-mob-progress in the detail frame.

**Comment by BreakBB** [comment]
@Matroyzy you should check that you are using the latest version of Questie (which is v6.5.0).

This bug has been fixed over a month ago.

**Comment by drejjmit** [comment]
Just tested this and i don't see any issues on latest version
![image](https://user-images.githubusercontent.com/15526476/127227857-536d564c-7b7e-49bf-a23a-010993e4115b.png)
