### ISSUE TITLE
think the error is for the event.

### ISSUE THREAD

**Issue by fubar187421** [Questie/Questie#3082]
**1x [ADDON_ACTION_BLOCKED] AddOn 'Questie' tried to call the protected function 'CompactRaidFrame1:ClearAllPoints()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `ClearAllPoints'
[string "@FrameXML\FlowContainer.lua"]:157: in function `FlowContainer_DoLayout'
[string "@FrameXML\FlowContainer.lua"]:17: in function `FlowContainer_ResumeUpdates'
[string "@Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua"]:185: in function `CompactRaidFrameContainer_LayoutFrames'
[string "@Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua"]:130: in function `CompactRaidFrameContainer_TryUpdate'
[string "@Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua"]:62: in function `CompactRaidFrameContainer_OnEvent'
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>**

**Comment by Laumesis** [comment]
Most likely same or related to issue #2846

**Comment by BreakBB** [comment]
Merging this issue with #2936

We are aware of the taint issue, but we were not able to fix it yet without losing functionality.
