### ISSUE TITLE
Stable Master tracking removed?

### ISSUE THREAD

**Issue by bucketss** [Questie/Questie#3086]
It's just gone :(

**Comment by BreakBB** [comment]
Hey @bucketss You should try to recompile your database.

`/questie` -> Advanced -> Recompile Database

We didn't change anything towards the QuestieMenu on the minimap icon.

**Comment by drejjmit** [comment]
I have it on my hunter
![image](https://user-images.githubusercontent.com/15526476/127631466-f47485d3-f273-4bd6-9157-86c893ee5579.png)![image](https://user-images.githubusercontent.com/15526476/127631564-9fd59be3-2ac1-4e22-88f6-1bc9298c904c.png)

**Comment by bucketss** [comment]
> 
> 
> Hey @bucketss You should try to recompile your database.
> 
> `/questie` -> Advanced -> Recompile Database
> 
> We didn't change anything towards the QuestieMenu on the minimap icon.

I did that right away and it didn't work

tried again today and now it's fine

thank you, that was weird  :O

**Comment by Laumesis** [comment]
Could very well be an issue from not restarting the game after updating Questie addon.

**Comment by Laumesis** [comment]
I must double check later if I can reproduce this:

`[02:58:00] Questie: [INFO] Invalid townsfolk key Stable Master`
after HS'ing to Shattrath from Ashenvale on my hunter.

And Questie's menu is missing Stable Master after that.
![image](https://user-images.githubusercontent.com/75958501/129119126-cfe8241b-8bbe-479a-a839-ef050b2409cc.png)

Questie ver:
after v6.5.1 master 80ac103e0c69962355e4c51591a0b851432b5f61 + PR #3126 first commit

**Comment by Laumesis** [comment]
I can't reproduce it now. Either I had missed recompiling DB or there is something strange triggering it
