### ISSUE TITLE
Missing turnin questionmark Call of Water (1536) on world map

### ISSUE THREAD

**Issue by wazerstar** [Questie/Questie#3087]
## Description
Shaman quest, doing [[44] Call of Water (1536)] and completing it will not show Completed question(?) mark on world map to turn in at Brine in barrens.

## Wowhead link
https://tbc.wowhead.com/quest=1536/call-of-water

## Questie version
v6.5.1

**Comment by BreakBB** [comment]
This is a desync issue and will be fixed with #3111
