### ISSUE TITLE
Hellfire fortifications still available

### ISSUE THREAD

**Issue by Cerby3BR** [Questie/Questie#3091]
For some reason Questie thinks https://tbc.wowhead.com/quest=10110/hellfire-fortifications is unavailable, but it still is.

Version 6.5.1

**Comment by drejjmit** [comment]
Do you have PvP and Repeatable icons enabled?

**Comment by Cerby3BR** [comment]
Yes:
![image](https://user-images.githubusercontent.com/54936174/127720978-2f57460e-3d2d-4c8e-b6cf-5da2f1e663bc.png)
Also:
![image](https://user-images.githubusercontent.com/54936174/127721013-65014c09-3a19-4508-908e-ad0b3c539587.png)

**Comment by drejjmit** [comment]
People say it gets unavailable at exalted. Is that not the case? 
I'm guessing you are exalted.

**Comment by Cerby3BR** [comment]
I'm 999/1000 and I can still do it.
Why would it be unavailable at exalted? It's the only reliable source of Marks.
