### ISSUE TITLE
Quests 1079 and 1080 are missing prerequirements.

### ISSUE THREAD

**Issue by Laumesis** [Questie/Questie#3096]
## Description
Questie shows quests 1079 and 1080 available on npc 4077 even the npc has nothing to offer right now. It started to show those after I turned in quest 1077. I have not yet done quest 1073, which should be requirement for quests 1079 and 1080 to be available.

## Wowhead link
https://tbc.wowhead.com/npc=4077/gaxim-rustfizzle
https://tbc.wowhead.com/quest=1079/covert-ops-alpha
https://tbc.wowhead.com/quest=1080/covert-ops-beta
https://tbc.wowhead.com/quest=1073/ineptitude-chemicals-fun

## Screenshots
![image](https://user-images.githubusercontent.com/75958501/127727419-6fbb97fd-0137-40a1-a8cc-d92242340002.png)

## Questie version
v6.5.1

**Comment by BreakBB** [comment]
The wowhead comments reflect what our database says. So either 1077 or 1074 should unlock both quests. Maybe both quests are required and not just one of them.

Was you able to test if the quests show up after you did 1073 or 1074?

**Comment by Laumesis** [comment]
Now looking DB, the DB seems correct. I looked history and it was correct also back then.

But Questie showed the quests 1079, 1080 available even neither of preQuestSingle {1074,1077} were completed. 😬
As 1077 wasn't completed and 1074 should not have been done yet because it should have requirement to do 1073 which wasn't completed yet.

I must test again with another character and see if 1074 can be done before 1073 is done. 🤔

**Comment by Laumesis** [comment]
Yes, iirc quests 1079 and 1080 came available in game once I had completed **both** 1077 and 1074 - like wowhead shows for quests and like wowhead comments say:
https://tbc.wowhead.com/quest=1079/covert-ops-alpha#comments:id=3194972
https://tbc.wowhead.com/quest=1079/covert-ops-alpha#comments:id=2946176
https://tbc.wowhead.com/quest=1079/covert-ops-alpha#comments:id=68639
https://tbc.wowhead.com/quest=1080/covert-ops-beta#comments:id=3194973
https://tbc.wowhead.com/quest=1080/covert-ops-beta#comments:id=68645:reply=6426

So preQuestGroup instead of preQuestSingle.
