### ISSUE TITLE
QuestieCorrections.lua:161: attempt to index field 'itemData' (a nil value)

### ISSUE THREAD

**Issue by TheJellly** [Questie/Questie#3106]
QuestieVersion: 6.5.1
...\Questie\Database\Corrections\QuestieCorrections.lua:161: attempt to index field 'itemData' (a nil value)
![Unbenannt](https://user-images.githubusercontent.com/22217283/128226214-d15a221f-e503-46f2-8861-a8cfea2d4a01.PNG)

**Comment by BreakBB** [comment]
@TheJellly Try `/questie` -> Advanced -> Recompile database.

If that doesn't help remove the Questie folder and do a fresh install of v6.5.1

**Comment by TheJellly** [comment]
Fresh install doesn't help.
/questie won't open a window.

**Comment by TheJellly** [comment]
I also get a new error now.
Interface\AddOns\Questie\Modules\Libs\QuestieLib.lua:373: attempt to call global 'GetQuestLogTitle' (a nil value)

**Comment by drejjmit** [comment]
> /questie won't open a window.

Try to run this:
``/run QuestieLoader:ImportModule("QuestieOptions").tabs.advanced:Initialize().args.questieReset.func()``

**Comment by TheJellly** [comment]
> 
> 
> > /questie won't open a window.
> 
> Try running this:
> `/run QuestieLoader:ImportModule("QuestieOptions").tabs.advanced:Initialize().args.questieReset.func()`

Still won't open and following error message in chat Interface\AddOns\Questie\Modules\Libs\QuestieLib.lua:373: attempt to call global 'GetQuestLogTitle' (a nil value)!
Already fresh installed it 3 times

**Comment by BreakBB** [comment]
@TheJellly Are playing TBC Classic or Classic Era? Note that we don't support private servers or any vanilla versions of WoW anymore.

Last resort is to remove the `Questie.lua` and `Questie.lua.bak` files you find in the `WTF` folder. This will reset all the Questie settings (won't touch completed quests).

**Comment by nervusdm** [comment]
Reopening ? Same error here.
CLassic Era

**Comment by Laumesis** [comment]
@nervusdm You have most likely TBC .zip from curseforge installed instead Era .zip
Could you show a screenshot of your Questie folder files? `_classic_era_\Interface\AddOns\Questie\`

After the screeshot, you could try to fix the thing by manually installing version GitHub has. It works on both TBC and Era+SoM unlike ones on CurseForge. <https://github.com/Questie/Questie/releases/latest>

**Comment by nervusdm** [comment]
You are right, I am sorry. I was using TBC...
