### ISSUE TITLE
仲夏火焰节任务被隐藏

### ISSUE THREAD

**Issue by singlehanded2022** [Questie/Questie#3112]

**Comment by BreakBB** [comment]
Yes, the Midsummer festival is already hidden. We didn't know when it will end exactly and it should be over now (so hidden correctly).

Thanks for the report though.

**Comment by singlehanded2022** [comment]
明白   谢谢

**Comment by singlehanded2022** [comment]
明白 谢谢

**Comment by singlehanded2022** [comment]
好的  谢谢
