### ISSUE TITLE
how to manually enable midsummer event?

### ISSUE THREAD

**Issue by BPolygon** [Questie/Questie#3113]
Hi, in my region  midsummer event still avable but addon stopped displaying icons "fire quest".
Which command can I manually activate the displaying quest?
Thanks

**Comment by drejjmit** [comment]
Change this line to ``8/8`` (if that's the date Blizzard sitcks with)https://github.com/Questie/Questie/blob/f0bb76f6def76cce9df1c1c9f6c3225a60d643f8/Database/Corrections/QuestieEvent.lua#L212

**Comment by BPolygon** [comment]
Yep, I see. Thanks
