### ISSUE TITLE
Questie: [CRITICAL] ERRRRORRRRRRR not mutually exclusive for questID: 10711

### ISSUE THREAD

**Issue by Laumesis** [Questie/Questie#3117]
## Bug description
Debug message `Questie: [CRITICAL] ERRRRORRRRRRR not mutually exclusive for questID: 10711`
1. Level 62+ character. Atleast alliance lvl 62-64 works to reproduce
2. Enable debug & debug print & DEBUG_CRITICAL in Questie config
3. reload ui or login

Correct issue label might also be `Questie - Quest issue`, but I am not sure.

Link to the questid on wowhead https://tbc.wowhead.com/quest=10711/test-flight-razaans-landing

## Questie version
v6.5.1  unmodified

**Comment by BreakBB** [comment]
Fixed with b14df8648d646dbae7b1c7fa6ccf05d98671a391
