### ISSUE TITLE
Quest timer isnt showing

### ISSUE THREAD

**Issue by martinboy1974** [Questie/Questie#3119]
I just did Iverrons Antidote quest that have a timer to deliver the antidote. Problem is, that the timer doesnt show in the tracker. If I enable Blizzard Timer Frame in the addon, the standard frame is shown. If I disable the Blizzard Timer Frame, the timer that should be embedded in the tracker, still doesnt show up.

I am using Questie 6.5.1TBC

**Comment by BreakBB** [comment]
Hey @martinboy1974 can you check if you have the "Enable Tracker Hooks" checkbox enabled in the Tracker options?

**Comment by martinboy1974** [comment]
Tracker hooks is enabled. The quest showed as complete in the tracker, but there was a timer for the quest in the questlog.

**Comment by BreakBB** [comment]
Oh I see, that could indeed be a problem. Thanks for reporting it, we will look into it!

**Comment by BreakBB** [comment]
Fixed in 002b12f5f3a663a6b0aaaa59e355f360168505ca
