### ISSUE TITLE
Holiday Commoners

### ISSUE THREAD

**Issue by Nerillida** [Questie/Questie#3122]
Regarding the commoners - specifically mapped for the Midsummer Holiday

- in pairs, centred on middle of pair 

NOTE:
I can find no sign of a Tauren Commoner in Silvermoon

Human Commoner	18927
    Stormwind
         54.30,64.34
         61.53,62.35

Dwarf Commoner	19148
    Ironforge
        30.91,63.05

Gnome Commoner	19172
    Ironforge
        58.04,49.52

Night Elf Commoner	19173
    Darnassus
         41.51,44.78

Draenei Commoner	19171

    Azuremyst Isle
        20.46,54.38
    The Exodar
	68.06,61.83
	60.89,28.51
	51.93,42.72
	60.15,48.96

Orc Commoner		19175
    Orgrimmar
         51.45,69.42

Troll Commoner		19177
    Orgrimmar
         46.65,62.22

Forsaken Commoner	19178
    Undercity
         63.18,47.47
         67.71,39.16

Tauren Commoner		19176
    Thunder Bluff
         41.84,55.67

Blood Elf Commoner	19169
    Silvermoon City
        78.01,57.63
        90.17,57.50
        89.61,49.15
    Eversong Woods
        54.18,50.77

Goblin Commoner		20102
    The Barrens (Ratchet)
        63.03,37.15
    Stranglethorn Vale (Booty By)
        26.82,76.90
        27.54,77.61
        26.85,73.91
    Winterspring (Everlook)
        62.38,36.80
        60.37,36.41
        61.27,37.55
        61.38,38.59
    Tanaris (Gadgetzan)
        50.94,29.23
        52.05,28.45
        52.34,27.63
        51.59,25.63

    Shattrath City
        63.60,39.74   by Flight Point
        54.95,38.49   by Old Alliance Capital Portals
        58.03,46.13   by New Capital Portals
        53.04,51.09   by Old Horde Capital Portals
        49.16,31.48   by Aldor Tier base
        28.17,47.04   by Aldor Tier Inn
        58.92,58.09   by Scryer Tier base
        55.22,80.53   by Scryer Tier Inn

**Comment by BreakBB** [comment]
@Cabro do you think this can be closed?

**Comment by Cabro** [comment]
Yeah, from what i know, wotlk already had good spawns on these
