### ISSUE TITLE
Going into an instance moves the tracker off-screen

### ISSUE THREAD

**Issue by Jokaleth** [Questie/Questie#3132]
I'm stupid ignore this

**Comment by jcadduono** [comment]
wait how did you solve it this drives me insane

**Comment by drejjmit** [comment]
Isn't there a setting to hide tracker in dungeons? Just change that setting.

**Comment by jcadduono** [comment]
surely it's a bug that the tracker position has to be reset once you leave a dungeon in order to get it back if that setting is enabled?
