### ISSUE TITLE
some error

### ISSUE THREAD

**Issue by SunnyJang38** [Questie/Questie#3134]
1x ...Questie\Libs\AceSerializer-3.0\AceSerializer-3.0-5.lua:247: bad argument #1 to 'gsub' (string expected, got nil)
[string "=[C]"]: ?
[string "@Questie\Libs\AceSerializer-3.0\AceSerializer-3.0-5.lua"]:247: in function `Deserialize'
[string "@Details\core\network.lua"]:404: in function `func'
[string "@Details\core\network.lua"]:648: in function `?'
[string "@Questie\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:119: in function <...tie\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Questie\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...tie\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Questie\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `Fire'
[string "@Questie\Libs\AceComm-3.0\AceComm-3.0-12.lua"]:222: in function `OnReceiveMultipartLast'
[string "@Questie\Libs\AceComm-3.0\AceComm-3.0-12.lua"]:256: in function <...faceQuestie\Libs\AceComm-3.0\AceComm-3.0.lua:246>

**Comment by BreakBB** [comment]
Hey @SunnyJang38 can you reproduce this issue and explain when this happens? We need more information than just the stack trace you posted.

**Comment by Laumesis** [comment]
This is a bug in `Details`.
All references to `Questie` in trace are to libraries both use.

**Comment by BreakBB** [comment]
Oh right, I overlooked the `@Details\core\network.lua`

@SunnyJang38 can you report this to the Details authors please? :)

**Comment by SunnyJang38** [comment]
someone report about @Details\core\network.lua:648 error to Detail's Discord 
but, no answer about it

**Comment by BreakBB** [comment]
Go ahead and open up an issue on their issue tracker @SunnyJang38 https://github.com/Tercioo/Details-Damage-Meter/issues 👍🏻
