### ISSUE TITLE
Error during initialization 

### ISSUE THREAD

**Issue by RavenUK** [Questie/Questie#3141]
Hi there, I have just found you addon along with Kaliels tracker, I have installed both. 
I installed yours via the instructions for the non classic version. So a new / clean install. 

I keep getting this error below. Not sure what to do next, I did try deleting the folder and installing it again. But still keep getting this error.

![Screenshot 2021-08-22 144910](https://user-images.githubusercontent.com/89346545/130357811-1f37c053-73c0-442b-a247-17f20fe3bfb9.png)

Many thanks for any help / support / advice etc.

**Comment by Otegarr** [comment]
Same here 
![Capturewowclassic](https://user-images.githubusercontent.com/89347113/130358210-f4032247-3643-4ba4-a5b8-e85a0e2e837f.PNG)

**Comment by drejjmit** [comment]
Always restart your client after updating.
If this doesn't work: Delete ``Questie`` in AddOns folder and reinstall Questie (not just replace files)

**Comment by RavenUK** [comment]
Hi there drejjmit, I did not have the client / wow running when I installed the addons, however I have done both things you said above. I still have the same issue. 

I did delete the folder and then copy from the zip extract to the addons folder , then started wow.

**Comment by Laumesis** [comment]
@RavenUK What is "the non classic version" ? Is this some private server?

@Otegarr Your issue is different. You have corrupted install of addon or didn't restart the game.

**Comment by RavenUK** [comment]
Hi @Laumesis , sorry my bad description above. 

What I meant is that I have followed this guide 
https://github.com/Questie/Questie/wiki/Installation-Guide

To install 
https://github.com/Questie/Questie/releases/tag/v6.5.1

I did not use the curse forge file 
https://www.curseforge.com/wow/addons/questie/files
Which I understood to be classic / tbc wow and not the retail (shadowlands) version. 

Sorry for any confusion on my other post above.

**Comment by Laumesis** [comment]
@RavenUK Questie is only for classic / burning crusader classic wow. It is not available for retail (shadowlands) and won't work there as you noticed. Retail wow has most of the functionality build in by Blizzard.

Curse forge files and the release file at GitHub are basicly the same file.
