### ISSUE TITLE
"The Agony and the Darkness" still showing.

### ISSUE THREAD

**Issue by SubbyDK** [Questie/Questie#3162]
## Description
The quest "The Agony and the Darkness" is showing even though I just turned it in.
I can't talk to the NPC again, so no quest.

## Wowhead link
https://tbc.wowhead.com/quest=10389

## Screenshots
<img width="1386" alt="The Agony and the Darkness" src="https://user-images.githubusercontent.com/31448358/133923008-3ebc618d-8b62-4adb-9601-eb71d01fddb4.png">
<img width="1918" alt="Magister Bloodhawk" src="https://user-images.githubusercontent.com/31448358/133923120-96f76cc2-ac27-4b48-a115-0095d53e66f1.png">

## Questie version
Version 6.6.0 (TBC)

**Comment by Laumesis** [comment]
Known desync bug, will be fixed once PR #3111 is ready.

**Comment by SubbyDK** [comment]
Sounds good. :)
Thanks for all the great work you put in to this. ;)
