### ISSUE TITLE
Alternate solution for bugged worldmap dropdowns in BCC

### ISSUE THREAD

**Issue by Goldpaw** [Questie/Questie#3163]
So I notice you're removing the dropdowns on the WorldMap in BCC in the latest Questie versions. Is this because of the blizzard bugs occurring on mouseover? Because I use another solution for that in my own WorldMap addon, that doesn't require them to be removed. 

The problem was that the Blizzard OnEnter scripts assumes a keybind for the battlefield minimap always has been set by the user, which of course doesn't have to be true. So I just replaced the script with one that checks for the existence of a keybind before running the original script. At least in my own testing, this is a safe way of fixing it, and it doesn't taint the map. 

If this was the issue, I hope it can be somewhat helpful! If you removed the dropdowns for completely different reasons, then totally ignore this whole thing! (I haven't really looked at your code, just going on a wild assumptions here, heh!)

```Lua
if (_G.WorldMapZoneMinimapDropDown) then
	_G.WorldMapZoneMinimapDropDown:SetScript("OnEnter", function(self)
		-- Blizzard don't check for a key (yet), so this bugs out with no bind.
		local key = GetBindingKey("TOGGLEBATTLEFIELDMINIMAP")
		if (key) then
			_G.WorldMapZoneMinimapDropDown_OnEnter(self)
		end
	end)
end
```

**Comment by BreakBB** [comment]
Hey @goldpaw thanks for taking the time to get in touch with us :)

We removed the dropdowns because of this Blizzard UI issue: https://github.com/Stanzilla/WoWUIBugs/issues/165

Every drop down menu gets tainted because of this and removing the world map drop down menus is the easist workaround for now. Leatrix maps implemented the same workaround 👍🏻

**Comment by BreakBB** [comment]
Closing this as we move forward investigating the changes Blizzard made towards the taint issues.
