### ISSUE TITLE
Armor Repair Icon Disappears On Questie Load

### ISSUE THREAD

**Issue by AugustEverywhere** [Questie/Questie#3185]
## Bug description
When screen loads, the armor icon under the minimap appears and shows I have damaged armor.  It disappears and then Questie loads and takes it place.

## Screenshots

![WoWScrnShot_093021_075300](https://user-images.githubusercontent.com/91682702/135479591-fa098c11-05d6-40a1-99c6-bc50958e7321.jpg)

![WoWScrnShot_093021_075306](https://user-images.githubusercontent.com/91682702/135479629-200cf4f0-6b63-411b-873c-a6a964460b20.jpg)

**Comment by AugustEverywhere** [comment]
Hey there has been resolved.  ty. . .the update turned it off.

**Comment by chienb** [comment]
im also having this issue on v6.8.2 tbc classic. 
![image](https://user-images.githubusercontent.com/12900266/147384199-23fc7a6e-75e6-4180-a996-1ce8349b796c.png)

**Comment by Laumesis** [comment]
@chienb
Try enabling `Sticky Durability Frame`

**Comment by BreakBB** [comment]
I experienced this myself even with the "Sticky Durability" frame option enabled. Something we need to fix

**Comment by BreakBB** [comment]
@Dyaxler you looked into this while reworking the Tracker, didn't you?

**Comment by MyTechnoHunter** [comment]
@BreakBB verified working
