### ISSUE TITLE
The quest 12421 is missing from Questie's database

### ISSUE THREAD

**Issue by EugeneLeclerc** [Questie/Questie#3189]
## Description

As the title states, the quest 12421 is missing from Questie's database. The quest is [Brew of the Month Club](https://tbc.wowhead.com/quest=12421/brew-of-the-month-club), which starts from ["Brew of the Month" Club membership form](https://tbc.wowhead.com/item=37571/brew-of-the-month-club-membership-form).

I suspect [the alliance quest (12420)](https://tbc.wowhead.com/quest=12420/brew-of-the-month-club) is also missing but I have no way to test it.

Wowhead also shows two other quests, I'm not sure if/how they are available in game right now.

## Wowhead link

Item:
https://tbc.wowhead.com/item=37571/brew-of-the-month-club-membership-form

Missing quests:
https://tbc.wowhead.com/quest=12420/brew-of-the-month-club
https://tbc.wowhead.com/quest=12421/brew-of-the-month-club

Other quests?
https://tbc.wowhead.com/quest=12278/brew-of-the-month-club
https://tbc.wowhead.com/quest=12306/brew-of-the-month-club

## Questie version

Questie v6.6.2, which is the latest as the time of writing.

**Comment by Laumesis** [comment]
Thanks reporting 👍
Already fixed in master 6 days ago a52f33bccc72dcb44e5940ab279234f54c78dbd0, but there hasn't been a release after it.

**Comment by EugeneLeclerc** [comment]
Perfect, thanks!
