### ISSUE TITLE
[Feature Request] Hide Quest announce from Questie from other players

### ISSUE THREAD

**Issue by Rumchiller** [Questie/Questie#3220]
Since you do not want to change the default "quest announce" option, please add an option to hide those massages from other players, since it causes a huge spam problem while in the chat. You could add a special hidden attribute in those messages, so you can filter them out, if this option is activated.

**Comment by Muehe** [comment]
FYI @Velarax, will be included in next release.

**Comment by Muehe** [comment]
@Rumchiller Named the option like you named the addon as an homage, hope that's OK.

Any particular reason you took it off CurseForge? Might be good to have a way for people to get rid of it without installing Questie.

**Comment by Velarax** [comment]
That's wonderful!  Many thanks.

**Comment by Rumchiller** [comment]
> @Rumchiller Named the option like you named the addon as an homage, hope that's OK.
> 
> Any particular reason you took it off CurseForge? Might be good to have a way for people to get rid of it without installing Questie.

@Muehe Yeah, of course, I'm very pleased, that you named it like this as an homage.
Regarding the CurseForge project: "Someone" complained about the addon logo some time ago, since it does not belong to me^^ I'm just updated the logo, so the project should be online in some time.
I'm sorry, that I won't keep the addon updated, since I don't have time now for WoW. Everyone is welcome to copy the project and update it or use it for his/her own projects (you can also use my logo for free^^).

**Comment by Velarax** [comment]
Just tried the new Questie and the SUQ works great!  Thanks for doing this.  Totally solved my issue and that of my friends :D
