### ISSUE TITLE
No Tracker - SortID : 0 was not found in the database

### ISSUE THREAD

**Issue by YoShiiro** [Questie/Questie#3223]
## Bug description
When i load the wow TBC session i got this error below, and no tracker appear, but the rest of questie work (item on map & quest announce in chat). I've try to delete folder / WTF but still have this problem.

And the strangest things is that i got this error on one account, my second account got no problem tracker & quest.

_ Questie: [ERROR] SortID: 0 was not found in the Database. Please file a bugreport at: 
 Questie: [ERROR] https://github.com/Questie/Questie/issues _

## Screenshots
![image](https://user-images.githubusercontent.com/6746150/139693377-7e962e84-853e-43a8-b6b2-5d31ee1d7215.png)

## Questie version
Question version 6.6.4

**Comment by Laumesis** [comment]
See #3222

**Comment by BreakBB** [comment]
These are different issues I think. The quests in #3222 had no sortID, not 0.

**Comment by Laumesis** [comment]
https://github.com/Questie/Questie/blob/eaa009fb4147e2eccc5b783a50f7e2072e3d8a3e/Modules/Libs/QuestieCompressedTable.lua#L302

**Comment by Laumesis** [comment]
Oh right. You are correct. This issue maches the one that was on Discord earlier. #3222 is maybe different, at least it manifest itself differently.

**Comment by Laumesis** [comment]
It is the same. Most users don't have lua errors enabled, so they see only the message in chat. And seems some who have lua errors enabled ignore the chat message.
#3222 tried to compare number to string.

if zoneorsort is <0 or >0 it gets converted to string. while 0, it stays as 0. Imo another bug, which should be fixed. And while fixing the sort function should be declared before passed to function.

**Comment by NordikaMan** [comment]
I'm having the same issue on a new boosted character after accepting the Boost-related starter quests that get you some gear, skills and send you off to the Dark Portal. 

All my other characters on this account work just fine!

**Comment by Laumesis** [comment]
@NordikaMan Check #3222 for temporary solution

**Comment by NordikaMan** [comment]
> @NordikaMan Check #3222 for temporary solution

Haha I was just editing my comment to say that temp fix does indeed work :) tyty

**Comment by Laumesis** [comment]
Fixed by eaa009fb4147e2eccc5b783a50f7e2072e3d8a3e in release v6.7.0, availabel to download.
