### ISSUE TITLE
Duskwood zone is nil in Quests by Zone tab

### ISSUE THREAD

**Issue by Cabro** [Questie/Questie#3229]
Wanted to quest in Duskwood and wanted to check how many quests there still were, but the dropdown list was missing completely. It reappeared when i changed the zone and i could select Duskwood, however nothing was changed in the numbers of the available/missing/prequest from the previous zone that was selected.
Right click minimap icon > select quests by zone > select Duskwood in the dropdown. There seems to be an issue with the database for that menu.
Questie for TBC

**Comment by Laumesis** [comment]
```
Message: Interface\AddOns\Questie\Modules\Libs\QuestieLib.lua:255: bad argument #1 to 'unpack' (table expected, got nil)
Time: Sun Nov  7 13:24:56 2021
Count: 2
Stack: Interface\AddOns\Questie\Modules\Libs\QuestieLib.lua:255: bad argument #1 to 'unpack' (table expected, got nil)
[string "=[C]"]: in function `unpack'
[string "@Interface\AddOns\Questie\Modules\Libs\QuestieLib.lua"]:255: in function `GetTbcLevel'
[string "@Interface\AddOns\Questie\Modules\Libs\QuestieLib.lua"]:542: in function `SortQuestIDsByLevel'
[string "@Interface\AddOns\Questie\Modules\Journey\tabs\QuestsByZone\QuestsByZone.lua"]:124: in function `CollectZoneQuests'
[string "@Interface\AddOns\Questie\Modules\Journey\tabs\QuestsByZone\QuestsByZoneTab.lua"]:147: in function <...odules\Journey\tabs\QuestsByZone\QuestsByZoneTab.lua:146>
[string "=[C]"]: ?
[string "@Interface\AddOns\Ace3\AceGUI-3.0\AceGUI-3.0.lua"]:72: in function <Interface\AddOns\Ace3\AceGUI-3.0\AceGUI-3.0.lua:70>
[string "@Interface\AddOns\Ace3\AceGUI-3.0\AceGUI-3.0.lua"]:306: in function `Fire'
[string "@Interface\AddOns\Ace3\AceGUI-3.0\widgets\AceGUIWidget-DropDown.lua"]:437: in function <...ns\Ace3\AceGUI-3.0\widgets\AceGUIWidget-DropDown.lua:428>
[string "=[C]"]: ?
[string "@Interface\AddOns\Ace3\AceGUI-3.0\AceGUI-3.0.lua"]:72: in function <Interface\AddOns\Ace3\AceGUI-3.0\AceGUI-3.0.lua:70>
[string "@Interface\AddOns\Ace3\AceGUI-3.0\AceGUI-3.0.lua"]:306: in function `Fire'
[string "@Interface\AddOns\Ace3\AceGUI-3.0\widgets\AceGUIWidget-DropDown-Items.lua"]:351: in function <...3\AceGUI-3.0\widgets\AceGUIWidget-DropDown-Items.lua:341>

Locals: <none>
```

**Comment by Laumesis** [comment]
questId 3 is culprit

**Comment by Laumesis** [comment]
DB doesn't have questID 3, so it gets added dynamically from quest starts/ends, I guess.
v6.6.3 works okey
v6.6.4 bugs
Commit 3260d28661d74be617f56c086db1c27986656677 broke it
Commit eaa009fb4147e2eccc5b783a50f7e2072e3d8a3e doesn't fix it. I tried to apply it top of breaking commit and top of v6.6.4 tag.

**Comment by Laumesis** [comment]
`QuestieDB.sortKeys` is missing value `-367` used in eaa009f. That's why it doesn't fix this.
https://github.com/Questie/Questie/blob/fa774f3da59884e517858762c078f42cedb87854/Database/Constants.lua#L4

@BreakBB  Would `REPUTATION = -367,` be okey addition? I haven't traced where all the table is used.

**Comment by Cabro** [comment]
glad to see someone found the source of the problem

**Comment by BreakBB** [comment]
@Laumesis thanks for looking into this. Totally forgot about the dependency towards the Journey and `QuestieDB.sortKeys`
