### ISSUE TITLE
Questie ERROR

### ISSUE THREAD

**Issue by rzzlj** [Questie/Questie#3230]
Questie ERROR, when i want to active the quest tracker
![isuees](https://user-images.githubusercontent.com/93842311/140623110-c15c30d0-9706-482e-949d-76fb85572d08.png)

**Comment by TinkerSpella** [comment]
Same issue here. Tracker is gone, and same error message every time completing a quest.

**Comment by rzzlj** [comment]
fortunatelly its just fixed, idk. after reach 60 its just fixed lol.

**Comment by Laumesis** [comment]
Duplicate #3223
