### ISSUE TITLE
Untracking a quest via Questie Tracker won't hide its icons

### ISSUE THREAD

**Issue by Laumesis** [Questie/Questie#3233]
The icons of the quest stay visible on map even user untracks the quest via right click menu on Questie Tracker while `Hide icons of untracked quests` is enabled.

![image](https://user-images.githubusercontent.com/75958501/140826328-542d0777-13b2-4058-81a9-a86483af337a.png)

v6.7.0

**Comment by svalentin** [comment]
Ah, my bad. I didn't realize you can untrack quests from that r.click menu. Will try to make a fix for it for next version.
