### ISSUE TITLE
Quest has no finisher: 11242 Free at Last! ; 11972 Shards of Ahune

### ISSUE THREAD

**Issue by Laumesis** [Questie/Questie#3235]
```
Questie: [CRITICAL] [QuestieQuest]: Quest has no finisher: 11242 Free at Last!
Questie: [CRITICAL] [QuestieQuest]: finisher or finisher.spawns == nil
Questie: [CRITICAL] [QuestieQuest]: Quest has no finisher: 11972 Shards of Ahune
Questie: [CRITICAL] [QuestieQuest]: finisher or finisher.spawns == nil
```
![image](https://user-images.githubusercontent.com/75958501/140828399-162bcfe8-823a-4a35-96c5-928825b51092.png)

v6.7.0

**Comment by BreakBB** [comment]
https://tbc.wowhead.com/quest=11403/free-at-last needs

Start NPC: https://tbc.wowhead.com/npc=23904/sir-thomas (spawns need to be corrected to SM Graveyard)
End NPC: https://tbc.wowhead.com/npc=23973/masked-orphan-matron (spawns available)

----
https://tbc.wowhead.com/quest=11972/shards-of-ahune needs

Starting object to be corrected to Slave Pens (https://tbc.wowhead.com/item=35723/shards-of-ahune)
End NPC: https://tbc.wowhead.com/npc=25697/luma-skymother (needs spawn set to Slave Pens)

**Comment by Laumesis** [comment]
Alliance and originally refered 11242 is not fixed. You fixed Horde version :)

```
Questie: [CRITICAL] [QuestieQuest]: Quest has no finisher: 11242 Free at Last!
Questie: [CRITICAL] [QuestieQuest]: finisher or finisher.spawns == nil
```
The quest <https://tbc.wowhead.com/quest=11242/free-at-last>
Start npc <https://tbc.wowhead.com/npc=23904/sir-thomas>
Finish npc <https://tbc.wowhead.com/npc=24519/costumed-orphan-matron>

Seems missing from events, blacklisting, quest corrections (start and finish not in original data). npcDB is okey.
