### ISSUE TITLE
Show Available Quest Icon over NPC when Show Low Level Quests Enabled

### ISSUE THREAD

**Issue by rbpaiett** [Questie/Questie#3236]
## Description

When enabling lower level quests on map, is it possible to make the available quest icon that hovers over the NPC to appear as well? (I don't mean the tooltip)  

I get the feeling the Blizz devs may have made that a reserved action (restricted or whatever it's called) but if it isn't, that would be helpful.

There were addons in Vanilla that did that but mysteriously that feature went away.

**Comment by BreakBB** [comment]
Hey @rbpaiett

I am sorry to tell you, but Addons can't add icons to the world like game objectd. So no there is no way for us to add an `!` above quest NPCs if they have a low level quest for the player.
