### ISSUE TITLE
TBC classic not showing any map items, cant open questie, have newest version 6.7

### ISSUE THREAD

**Issue by Struck99** [Questie/Questie#3245]
since i updated to 6.7 i cannot see anything on the map, cant open questie but still see quests tracked on side bar?

**Comment by BreakBB** [comment]
Hey @Struck99 we need some more informaton to help you...

DId you check your settings? Any error message? Maybe a screenshot would also help.

**Comment by Struck99** [comment]
i cant even open the menu to check settings
![Screenshot_3](https://user-images.githubusercontent.com/94148026/141657455-e89f75a0-2be3-4902-ada2-ada01bd3b9e6.png)
![Screenshot_4](https://user-images.githubusercontent.com/94148026/141657457-cdd1db0b-4e0f-4e43-bdd4-7249dd9c763f.png)

**Comment by Laumesis** [comment]
@Struck99 check the pinned issue https://github.com/Questie/Questie/issues/3043

**Comment by Struck99** [comment]
thank you, i should have thought of that before asking, that fixed it.

**Comment by Laumesis** [comment]
No worries :)

**Comment by Struck99** [comment]
I deleted the questie folder and reinstalled and it fixed it
