### ISSUE TITLE
Questie shows as available both centaur quest chains in Desolace, even if you don't have the reputation to take them.

### ISSUE THREAD

**Issue by Cabro** [Questie/Questie#3251]
Similar to how Scryers/Aldor quests are only shown as available for players with that faction's reputation, it should also only show the available quests for the centaur faction that you are friendly with (Excepting the initial quests that allow you to choose the faction).

**Comment by BreakBB** [comment]
Hey @Cabro could you add a screenshot and/or the wowhead links for the quests in question? That really helps fixing them 😃

**Comment by Cabro** [comment]
Sure!
Quests 1385 and 1382 are always available, how it should be.
Quests 1367 1369 1371 1375 1386 are only available when you are Friendly+ with Magram.
Quests 1368 1370 1373 1374 1380 are only available when you are Friendly+ with Gelkis.

**Comment by BreakBB** [comment]
Hey @Cabro I couldn't find an issue in our data. What version of Questie are you using and did you experience this problem on Classic Era/SoM or TBC?

**Comment by Cabro** [comment]
I am using TBC version of  the latest version. The issue is that Questie shows me those quests as missing prequest, instead of unobtainable, or missing completely from that list (just like SMV zone with aldor/scryer quests).
