### ISSUE TITLE
Missing Pre-req requirement for 2 quests

### ISSUE THREAD

**Issue by Jakobud** [Questie/Questie#3257]
This is for BCC.

## Bug description
Two quests show up as available on minimap, etc when they are not available because the pre-req has not been completed. The quests are:

https://tbc.wowhead.com/quest=10840/the-tomb-of-lights#comments
https://tbc.wowhead.com/quest=10842/the-vengeful-harbinger

The quest DOES become available after you complete the following quest:

https://tbc.wowhead.com/quest=10852/missing-friends

## Questie version
v6.7.0

**Comment by Jakobud** [comment]
Also, I did reload UI and reload Questie but that made no difference.

**Comment by BreakBB** [comment]
Hey @Jakobud I recently made changes to these two quests because they were available for me without completing "Missing Friends".

Did you complete https://tbc.wowhead.com/quest=10849/seek-out-kirrik before?

The current pre quests listed in our database say that you either have to complete 10849 or 10852 for both quests to become available.

There must be another connection to a quest which unlucks them 🤔

**Comment by Jakobud** [comment]
Okay so yes I definitely did do Seek out Kirrik (https://tbc.wowhead.com/quest=10849/seek-out-kirrik) and it was not available. I know this because I did the following two quests at the same time:

https://tbc.wowhead.com/quest=10839/veil-skith-darkstone-of-terokk
https://tbc.wowhead.com/quest=10852/missing-friends

I came back to the caravan and did not turn either in yet. I could see that the two quests were still not available. When I turned in Missing Friends, both of them became available.

So the question now: Is Missing Friends the only pre-req or is Seek out Kirrik also a pre-req and both need to be completed first? The only way to test I suppose would be to have someone turn in Missing Friends but not turn in Seek out Kirrik and see if they become available.

Here is screenshot before I turned in Missing Friends (Seek out Kirrik had already been turned in at this point). Take note of the minimap showing that the quest(s) should be available but you can see they are not on the NPC.

![WoWScrnShot_111721_205152](https://user-images.githubusercontent.com/87356/142374023-dfee6d2b-edb1-4795-ae36-9d8357696949.jpg)

Here is the screenshot after turning in Missing Friends (see the chat window)

![WoWScrnShot_111721_205402](https://user-images.githubusercontent.com/87356/142374184-ad93ec8a-7d8c-4025-b2a9-802cdd3934fd.jpg)

**Comment by BreakBB** [comment]
Great additon to your initial issue @Jakobud thanks a lot 👍🏻 

I agree that we need someone testing to turn in just Missing Friends and not do any other quests related, especially not "Seek out Kirrik". I am currently leveling a new character, but it will need a bit more time till I can test this. Hopefully I will remember then 😅

**Comment by BreakBB** [comment]
So I did some quests and forgot to check after every quest, but again I am able to accept "The Tomb of Lights" and "The Vengeful Harbinger" without completing "Missing Friends". The quests I did after the last check are:

- Taken in the Night
- The Dread Relic
- An Improper Burial
- For the Fallen
- Digging Through Bones
- Fumping
- A Hero is Needed
- The Fallen Exarch

Since the two quests in question reward reputation with Lower City I assume the quest which unlock them also rewards Lower City reputation. And the search led me to [this comment](https://tbc.wowhead.com/quest=10915/the-fallen-exarch#comments:id=72986) which states that "The Fallen Exarch" is required to get the quests. So it seems this issue can finally be solved 👍🏻

**Comment by Jakobud** [comment]
So I leveled another alt and paid close attention to this when I got here. My original observations held true:

The Tomb of Lights and The Vengeful Harbringer are not available until I completed Missing Friends.

I did not accept or complete any of these yet:

- Taken in the Night
- The Dread Relic
- An Improper Burial
- For the Fallen
- Digging Through Bones
- Fumping
- A Hero is Needed
- The Fallen Exarch

Haven't even been to that part of the map yet. I accepted "Seeking out Kirrik" and then went to the caravan. Before turning in, the The Tomb of Lights and The Vengeful Harbringer and Missing Friends were not available.

When I turned in Seeking out Kirrik two things happened: I got the follow up from Kirrik called Veil Skith: Darkstone of Terokk and also Missing Friends became available. The Tomb of Lights and The Vengeful Harbringer were still not available.

I went to Veil Skith and completed several quests there and returned to the caravan. The moment I turned in Missing Friends, The Tomb of Lights and The Vengeful Harbringer both become available.

I have no idea how it is possible that you were able to accept both of those quests before Missing Friends. 

Anyways, it's a bit of a moot point because I originally made this report because I noticed Questie incorrectly showed the 2 quests available when they were not. Now, with version 6.8.3, Questie shows it correctly. They do not show up in Questie as available until I turned in Missing Friends. So everything seems to be in order on Questie's end. 

Just thought I would follow up on it anyhow.

**Comment by BreakBB** [comment]
Hey @Jakobud thanks for coming back to bring more detail to this. As explained above I did the "Fallen Exarch" quest chain before Missing Friends which opened up the two quests in question. So everything should be working as intended now :+1:

**Comment by Jakobud** [comment]
Strange. So are those 2 quests being available dependent on either Missing Friends OR Fallen Exarch being completed?

**Comment by BreakBB** [comment]
Correct, that is what the commit changed which closed this ticket :+1:
