### ISSUE TITLE
The tracker doesn't always update quest objectives.

### ISSUE THREAD

**Issue by Cabro** [Questie/Questie#3264]
It seems the tracker has problems updating quest objectives when they are prison keys.
The key was received as a quest reward from daily dungeon. The tracker failed to pick this up.
Here's a screenshot to show the problem:
https://i.imgur.com/SJKWhkR.jpg

**Comment by BreakBB** [comment]
Yes, that is a known issue which we call "desync". The PR #3111 tackles this problem already and is close to be done. The update which contains the changes of that PR will fix this issue 👍🏻
