### ISSUE TITLE
Classic SoM quest ID 1206

### ISSUE THREAD

**Issue by MyTechnoHunter** [Questie/Questie#3265]
## Description
quest text on tooltip(shift) is wrongly stating 20 eyes needed, when the tracker and the quest itself say it needs 40

![image](https://user-images.githubusercontent.com/55214545/142798941-e27d5a4d-ea33-496e-95f5-6efef24bee84.png)

## Questie version
6.8.1

**Comment by drejjmit** [comment]
https://classic.wowhead.com/quest=1206/jarl-needs-eyes

**Comment by Laumesis** [comment]
The report was regarding SoM, so yep
