### ISSUE TITLE
Quest availability not strict enough: The Tomb of Lights (10840) & The Vengeful Harbinger (10842)

### ISSUE THREAD

**Issue by Treeston** [Questie/Questie#3276]
## Description
The quests **The Tomb of Lights** and **The Vengeful Harbinger** are being displayed as available, despite not being available.

_(Wowhead comments suggest that [Missing Friends](https://tbc.wowhead.com/?quest=10852) is a pre-requisite. I have not completed this quest.)_

## Wowhead link
[The Tomb of Lights](https://tbc.wowhead.com/quest=10840/the-tomb-of-lights#comments)
[The Vengeful Harbinger](https://tbc.wowhead.com/quest=10842/the-vengeful-harbinger#comments)

## Screenshots
![image](https://user-images.githubusercontent.com/14020072/145039456-e07cdcd7-a812-4156-a178-3b79f2aa1073.png)

## Questie version
`## Version: 6.8.1`

**Comment by BreakBB** [comment]
Hey @Treeston Thanks for the report!

You are not the first reporting this as you can see in #3257 - I am still looking for a way to check which quests are required and which are not.
It would be great if you could read through the comments on that issue and see if you find similarities about quests you did complete and quests you did not at the point of you report 💪🏻 

Also I am merging the issues for a better overview.
