### ISSUE TITLE
Cuergo's Gold Turn in Map Marker Missing

### ISSUE THREAD

**Issue by azulprime** [Questie/Questie#3280]

**Comment by BreakBB** [comment]
Hey @azulprime could you add at least some kind of the minimal information to the issue? What version of Questie are you using? Is this about Classic or TBC?...

**Comment by azulprime** [comment]
> Hey @azulprime could you add at least some kind of the minimal information to the issue? What version of Questie are you using? Is this about Classic or TBC?...

Version 6.8.1, Classic
