### ISSUE TITLE
Questie does not load for certain toons on Burning Crusade.

### ISSUE THREAD

**Issue by ucapbba** [Questie/Questie#3281]
## Bug description
Questie does not load for certain toons on Burning Crusade.  I updated to latest version yesterday with Curse Forge and there was some issue with other addons when logging in in with 2 toons so I removed everything and restarted.   The affected toons now do not load Questie upon entering (i.e. I see nothing in chat and no symbols on map) whereas other ones load Questie, albeit with the message "Hiding drop-down menus on the world map" 

Solution : I found that for these toons the AddOns.txt has Questie: Disabled.  It turns out I had to disable and re-enable after install (from the AddOns button in the login screen for your toon) for them to be enabled.  I create the issue incase anyone else has a similar issue. 

## Questie version
6.8.1

**Comment by drejjmit** [comment]
Check that the checkmark isn't silver on the character you're trying to load Questie on
![image](https://user-images.githubusercontent.com/15526476/145674418-19604cd0-59a6-4a4f-b9fd-6d998d75ec46.png)
If it is, click it twice so it's gold.

**Comment by ucapbba** [comment]
Thanks for your response - I didn't notice if it was silver before, but it is gold now and working well.
![QuestieTick](https://user-images.githubusercontent.com/87702063/145793475-fb2d095e-4835-4ad9-a776-ba60c5f39291.png)
