### ISSUE TITLE
The Great Ezra Grimm

### ISSUE THREAD

**Issue by LotG-Catherine** [Questie/Questie#3283]
## Description
The quest The Great Fras Siabi has been changed to The Great Ezra Grimm.  As you might know, the quest and that character were named after one of the Blizzard execs at the heart of last year's revelations about Blizzard's poor work environment.  Blizzard slipped in this change; I happened to take the quest and saw the name and character change last night.  I also saw Questie tell me the Great Fras Siabi was completed.  Given the circumstances, it might be nice, or at least non-damaging, if Questie didn't appear to be supporting the disgraced exec.

## Wowhead link
They did update their info!  
https://tbc.wowhead.com/quest=5214/the-great-ezra-grimm

## Screenshots
Didn't think to get a screenshot.

## Questie version
v6.8.1

**Comment by BreakBB** [comment]
Hey @LotG-Catherine thanks for the report, yes we will rename this to match what ever the game shows 👍🏻
