### ISSUE TITLE
Announcement improvements

### ISSUE THREAD

**Issue by lbuchholz79** [Questie/Questie#3285]
When leveling in a group, one member might miss when a quest is accepted or abandoned. Thou Questie syncs quests in the background, but 1) thats a bit cumbersome to check regularly, 2) new quests wont be shown in your quest log at all. So I thought it would be nice to get informed every time, a party member accepts, abandons or hands-in a quest. (implemented in PR #3273)

Based on the code in #3273, I also implemented some improvements for more announcement control:
* renamed original announce option to something like "announce objective completion to other players in group or raid" 
* refactor a master announcement toggle (currently events use "announce progress steps" for all kinds of party announcements)
* master toggle controls the target channel for announcements (in group, raid, both or "disabled" for global deactivation)
* migrate settings in DB storage and options UI adaptions
* refactoring of announcement code (split objectives, items, quest events)

Depends on # #3111 being merged.

**Comment by lbuchholz79** [comment]
See implemention in #3286

**Comment by BreakBB** [comment]
This can be closed after mergin #3286 can't it @lbuchholz79 ?
