### ISSUE TITLE
Quest Link in Chat 

### ISSUE THREAD

**Issue by Gluecksbaerli** [Questie/Questie#3288]
Hello 
im using Questie with version 6.8.1
the tooltip of the quest link in chat ( when use shift click on the quest) will show me the tooltip in english - can i switch that tooltip into german witch is my client ? 
in generell settings i set German 

LG Bärli

**Comment by BreakBB** [comment]
Hey @Gluecksbaerli could you share a screenshot of the tooltip and your settings?

Iirc the tooltip is added my the Reputable addon and not Questie.

**Comment by Gluecksbaerli** [comment]
ahhhh yes 
sorry did not think that it comes from another addon haha 
(hook out on "Show quest tooltip on Questie Hyperlink mouseover"
then it works :)
