### ISSUE TITLE
Regthar Deathgate not showing on the map

### ISSUE THREAD

**Issue by tap3ah** [Questie/Questie#3289]
## Description
When I hit level 30, the quest **Regthar Deathgate** was offered to me, but Questie did not show the mark on the map.

## Wowhead link
https://classic.wowhead.com/quest=1361/regthar-deathgate

## Questie version
6.8.1

**Comment by BreakBB** [comment]
Hey @tap3ah I guess this report is for Classic SoM?

**Comment by tap3ah** [comment]
Hi
Yes

**Comment by BreakBB** [comment]
I can't find any issue in our database for this. The quest has the correct level requirements, no pre quest and the starting NPC has the correct spawns. I'll write this off as desync issue which will be fixed once #3111 is finally merged.
