### ISSUE TITLE
Having several questieframe icons in game

### ISSUE THREAD

**Issue by lewisam69** [Questie/Questie#3291]
I installed from curseforge the latest version of questie v6.8.1 in world of Warcraft classic burning crusade, I get several icons maybe 5-6 questieframe 346, questieframe 780 all numbers like that. I try to remove add-on folder questie and to reinstall the same issue
![thumbnail](https://user-images.githubusercontent.com/96268225/146935953-7335fc98-c9f1-4ec1-a6a9-3d99365ac055.jpeg)

**Comment by BreakBB** [comment]
Hey @lewisam69 did you already solve this issue? I am not sure if I fully understand what the problem is you are experienceing. A screenshot might help.

Moreover did you try to delete the [Questie related files in your WTF folder](https://github.com/Questie/Questie/wiki/FAQ#2-questie-still-doesnt-show-anything)?

**Comment by lewisam69** [comment]
Hello,

Hereby a screenshot where you can this icon QuestieFrame (on top right of screenshot) and a number but I have many of them under that one.
I reinstall my Mac for other reasons, I reinstall world of warcraft, other adding and Questie but the problem is still there even I delete the folder Questie and I put it manually instead through Curseforge.

Regards,

**Comment by BreakBB** [comment]
Hey @lewisam69 unfortunately you can't send images when answering via mail. Please open the issue in a browser and attach the screenshot there https://github.com/Questie/Questie/issues/3291

**Comment by lewisam69** [comment]
Hello,
I updated the issue with image.
Regards,
    On Tuesday, 21 December 2021, 13:05:39 CET, Björn Böing ***@***.***> wrote:  
 
 


Hey @lewisam69 unfortunately you can't send images when answering via mail. Please open the issue in a browser and attach the screenshot there #3291

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by BreakBB** [comment]
This looks interesting 🤔 Could you try to disable all other addons and just keep Questie enabled and see if it still happens?

**Comment by lewisam69** [comment]
Hello Bjorn,

I désactivante all addons, it is working fine no more QuestieFrame icons, I reactivate slowly all adding one by one, it seems that add-on Leatrix Plus makes conflict with that. If I disable Leatrix Plus, no QuestieFrame and as soon I enable back, it appears again.

Regards,

**Comment by lewisam69** [comment]
Hello,

As I say Leatrix Plus add-on makes conflict with Questie add-on but not on all computers  and Mac computers, only on new MacBook Pro M1Max (the one I have maybe also M1Pro). It doesn’t make conflict on my Asus computer or my old MacBook Pro.

Regards,

**Comment by BreakBB** [comment]
Hey @lewisam69 addons are completely independent to the OS. So it makes no difference if an addon is used on a Windows PC or a Mac.

Could it be, it is related to some setting you have enabled on your Mac, but not on the Asus? Maybe something related to the minimap or minimap icons?

Also which version of Leatrix are you using? You should also reach out to the developers of Leatrix Plus, maybe they will be able to fix it on their side. Conflicts to other addons somewhat have a low priority for us, sorry.

**Comment by Laumesis** [comment]
@lewisam69 
Hey. Do you still have this issue?
Did you test having only Questie and Leatrix Plus addons enabled to confirm it is conflict between these too?
If things work with these only these two enabled together: Could you try again re-enabling your other addons slowly in addition to these two so you could see which one breaks things?

**Comment by lewisam69** [comment]
Hello,No it is resolved since the update of addons.Thanks to you
    On Friday, 11 February 2022, 11:20:20 CET, Laume ***@***.***> wrote:  
 
 


@lewisam69
Hey. Do you still have this issue?
Did you test having only Questie and Leatrix Plus addons enabled to confirm it is conflict between these too?
If things work with these only these two enabled together: Could you try again re-enabling your other addons slowly in addition to these two so you could see which one breaks things?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
