### ISSUE TITLE
TBC Questie Missing Quest

### ISSUE THREAD

**Issue by x-Jake-s** [Questie/Questie#3296]
Quest: Whitebark's Memory
Giver: Larianna Riverwind
Location: The Scorched Grove

Quest doesn't show where to place the pendant you are given.
![image](https://user-images.githubusercontent.com/8519492/147842706-6b31ca79-cbd5-4bc6-a895-5a670fabd536.png)

Turn in location:
![image](https://user-images.githubusercontent.com/8519492/147842723-f2affada-0bd2-4965-9d95-98eae572f697.png)

**Comment by BreakBB** [comment]
Hey @x-Jake-s

thanks for reporting this, looks like the fix I did for it in the TBC beta didn't work then and you are the first one reporting it. Will be an easy fix though (even though not as nice as the fix initially planned) 😁
