### ISSUE TITLE
Imperial Plate Plans quests (TBC/SoM)

### ISSUE THREAD

**Issue by Wintertime1** [Questie/Questie#3299]
Please change all the plans for Imperial Plate to be excluded from auto-completion so I never waste 85 fucking bars on shit I don't need again thanks.

**Comment by BreakBB** [comment]
I guess you are talking about the quests [Derotain Mudsipper](https://classic.wowhead.com/npc=14567/derotain-mudsipper) hands out in Tanaris.

Will be an easy fix. Thanks for letting us know 👍🏻

**Comment by Laumesis** [comment]
Maybe blacklist also <https://classic.wowhead.com/npc=7802/galvan-the-ancient> if not already
