### ISSUE TITLE
Problem with Questie tracking quests

### ISSUE THREAD

**Issue by Todehh** [Questie/Questie#3300]
I'm always having to /reload for quests to update, I've tried reinstalling the addon.

Playing on SoM

**Comment by Todehh** [comment]
These are the other addons I use in case one conflicts with questie 
![image](https://user-images.githubusercontent.com/97182820/148380639-189bed1a-e5f3-4ca7-bb23-d09f2380af7d.png)
![image](https://user-images.githubusercontent.com/97182820/148380713-5828c949-cd87-4306-98b7-4aa1084cc83b.png)
![image](https://user-images.githubusercontent.com/97182820/148380785-6330911e-4482-4246-aaab-c72df0e82f77.png)

**Comment by xecutable** [comment]
I can confirm, Questie does not update the progress of your quests. It still shows the minimap icons of the objectives, even after completion and does not show where to turn in your quest. I have disabled all other addons just to make sure. I'm playing SoM as well

**Comment by xecutable** [comment]
After a while, seems like Addon managers like Adjour, mess up the version of Questie and download some version 4.0.9 BETA and that's where the problem is.

**Comment by Laumesis** [comment]
#3111

**Comment by MimmiLand** [comment]
I have the same issue these days, I think it might not work well with "NDui(core) Classic" but that is just a guess. I don't really want to swap out the UI so I'll just keep recompiling the database when I need to find something. The most annoying thing is that it seems to track quests I'm not on though.
