### ISSUE TITLE
showing marker for completed quest

### ISSUE THREAD

**Issue by tap3ah** [Questie/Questie#3303]
## Description
After I completed the last quest in [A New Plague] chain, it's marker re-appeared on the map.

## Wowhead link
https://classic.wowhead.com/quest=492/a-new-plague

## Questie & WoW version
SoM
v6.8.2

**Comment by tap3ah** [comment]
UPDATE: after UI reload the marker disappeared.

**Comment by BreakBB** [comment]
Thanks for updating this @tap3ah - We call this "desync bug" which happens from time to time (and a /reload always helps on this). The PR #3111 tackles this issue and has the highest priority with our limited time!

I will close this since there is nothing quest specific to do.
