### ISSUE TITLE
No TBC tracking

### ISSUE THREAD

**Issue by uklesh8888** [Questie/Questie#3308]
## Bug description
Azeroth tracking seems to be working just fine.  Can't seem to get anything to populate in Outlands on the world map or mini map.  The side bar with the list of quests is working.

## Questie & WoW version
I'm running 6.8.2 version.  Tried uninstalling and reinstalling, clearing WTF, disabled all other addons.  Not sure if I'm just overlooking something simple.

**Comment by BreakBB** [comment]
Hey @uklesh8888 can you share a screenshot to clearify your issue?

**Comment by uklesh8888** [comment]
![WoWScrnShot_011422_115308](https://user-images.githubusercontent.com/97708174/149554300-10334e21-d9e0-44c6-b3e9-8d45ea43586c.jpg)
![WoWScrnShot_011422_115334](https://user-images.githubusercontent.com/97708174/149554329-7b128e84-4d36-4de4-9934-fabe70417778.jpg)
![WoWScrnShot_011422_115506](https://user-images.githubusercontent.com/97708174/149554344-89c07022-fa27-482b-b4f4-bc398e5598c3.jpg)

**Comment by BreakBB** [comment]
Hey @uklesh8888 sorry for the late response. Could you try to recompile the database?

`/questie` -> Advanced -> Recompile database

This is indeed very strange 🤔 If that does not help could you share a screenshot of your "General" settings? Does the minimap icon of Questie also shows v6.8.2?

**Comment by Laumesis** [comment]
There is something wrong in these screenshots: There are two `Hide Questie` buttons.
Could you try disable other addons?

**Comment by BreakBB** [comment]
Yeah you are right Laume @uklesh8888 can you make sure you are running only one version of Questie?
