### ISSUE TITLE
missing quest marker

### ISSUE THREAD

**Issue by tap3ah** [Questie/Questie#3310]
## Description
The quest "Speak with Ruga" from Torm Ragetotem in Thunder Bluff was available but no marker was shown. Character: lvl 21 Troll Warrior

## Wowhead link
https://classic.wowhead.com/quest=1823/speak-with-ruga

## Questie & WoW version
v6.8.2
SoM

**Comment by BreakBB** [comment]
Hey @tap3ah thanks for reporting this. The database indeed only had one of the three possible starting NPCs listed 👍🏻
