### ISSUE TITLE
BCC - Missing quest 65593 "Hearts of the Lovers"

### ISSUE THREAD

**Issue by daveg717** [Questie/Questie#3317]
## Description
Warlock quest 65593 shows a Missing quest error

## Wowhead link
https://tbc.wowhead.com/quest=65593/hearts-of-the-lovers

## Screenshots
![IMG_20220120_232625](https://user-images.githubusercontent.com/26509992/150469423-a5e29e78-8400-464c-be02-3a96148445d5.jpg)
![IMG_20220120_232520](https://user-images.githubusercontent.com/26509992/150469431-82917a7b-eaf9-46d4-ae26-fce1b94617c8.jpg)

## Questie & WoW version
Questie v6.8.2
BCC v2.5.3.41812

**Comment by BreakBB** [comment]
Fixed with 14611a7ad86a7128dc318395c293200858c4edab and will be included in the next release. Thanks for reporting this @daveg717
