### ISSUE TITLE
Questie missing quest 65602

### ISSUE THREAD

**Issue by vLGrok** [Questie/Questie#3323]
Questie: [ERROR] The quest 65602 is missing from Questie's database, Please report this on GitHub or Discord!

**Comment by vLGrok** [comment]
Questie v 6.8.2
TBC Burning Crusade Classic
Level 31 Warlock picked up quest Questie didn't know about.

**Comment by BreakBB** [comment]
Fixed with 14611a7ad86a7128dc318395c293200858c4edab and will be included in the next release.
