### ISSUE TITLE
lost minimap icon, /questie doesn't work

### ISSUE THREAD

**Issue by xuwol** [Questie/Questie#3325]
accidentally got rid of the questie icon on my minimap and now i can't config because /questie doesn't pull up anything either. tried /reload and uninstalling/reinstalling; still no icon :/

**Comment by BreakBB** [comment]
Hey @xuwol

If `/questie` does not open up the settings, it is not loaded correctly. Press Escape, select Addons and check the "Load outdated addons" checkbox in the upper right. The next release will update Questie to be "up to date", don't worry it works as it is already.

**Comment by xuwol** [comment]
hey there! i already had it checked.. so i dissabled it and re-enabled it just to see if that would work and unfortuantely it didn't

**Comment by BreakBB** [comment]
Can you share a screenshot of your ingame Addons list? Questie should be one of the last spots in the list.

**Comment by xuwol** [comment]
here you go! [Capture](https://user-images.githubusercontent.com/98236699/150672653-64103b2f-d139-4bb6-a6bb-94a3f9fedd5e.PNG)

**Comment by Muehe** [comment]
Based on your location that screenshot is from Shadowlands, Questie only works for Classic and TBC.

**Comment by BreakBB** [comment]
Exactly what Muehe says @xuwol There is no improvement Questie can bring since the retails questing system is far superior.
