### ISSUE TITLE
Missing Quest 65603, TBC Alliance Warlock

### ISSUE THREAD

**Issue by hzleyz** [Questie/Questie#3327]
## Questie & WoW version

![Screenshot (2)](https://user-images.githubusercontent.com/98272098/150685693-d9ef7e01-a56f-45af-8558-51a03ff35ec5.png)
![Screenshot (1)](https://user-images.githubusercontent.com/98272098/150685694-04164783-baa3-4e99-bdaa-928d66a41861.png)

Questie 6.8.2

I started the campaign quest "What is Love?" Alliance Warlock I believe in Stormwind City. Was sent to Ratchet where I picked up the "What is Love?" quest that sent me to Ashenvale. That was missing with an error as well. Once turned in back at Ratchet, it gave me the follow up "The Binding" which is missing too.

**Comment by BreakBB** [comment]
This has been fixed with 14611a7ad86a7128dc318395c293200858c4edab which will be included in the next release. Thanks for the report @hzleyz 👍🏻
