### ISSUE TITLE
65602 is not in the DB

### ISSUE THREAD

**Issue by salkrit** [Questie/Questie#3331]
## Bug description
Quest 65602 is not found in the DB

## Screenshots
![image](https://user-images.githubusercontent.com/19415649/150924635-4c9068c0-e0e7-45c4-a48f-80aacedf580d.png)

## Questie & WoW version
Questie-v6.8.2.zip

**Comment by drejjmit** [comment]
Thanks for the report. 
Fixed with 14611a7ad86a7128dc318395c293200858c4edab and will be included in next release.
