### ISSUE TITLE
missing warloc quest Love Hurts #65601

### ISSUE THREAD

**Issue by nikitamarchenko** [Questie/Questie#3333]
## Description

Missing quest Series "Love Hurts" 

## Wowhead link

https://tbc.wowhead.com/quest=65601/love-hurts

## Questie & WoW version

TBC v2.5.3 build 41812 Questie v6.8.2

**Comment by nikitamarchenko** [comment]
nice id btw

**Comment by BreakBB** [comment]
Hey @nikitamarchenko nice ID indeed 😁 

This issue is already fixed by 14611a7ad86a7128dc318395c293200858c4edab and will be in the next release (which will be online later today). Thanks for reporting 👍🏻
