### ISSUE TITLE
Classic SoM: Quest 5678 is missing

### ISSUE THREAD

**Issue by stempst0r** [Questie/Questie#3334]
## Description
WoW Classic SoM:
As lvl 20 Human Priest I accepted a priest-q in Darnassus and the following was shown in Chat-Window:

 Questie: [ERROR] The quest 5678 is missing from Questie's database, Please report this on GitHub or Discord!

So here I'm reporting the quest. I had the latest version of Questie installed the time of writing htis

## Wowhead link
[https://classic.wowhead.com/quest=5678/arcane-feedback](https://classic.wowhead.com/quest=5678/arcane-feedback)

The Quest is actually provided by [Priestress Alathea](https://classic.wowhead.com/npc=11401/priestess-alathea) which isn't noted at wowhead

## Questie & WoW version
6.8.3
 Classic SoM

**Comment by BreakBB** [comment]
Hey @stempst0r thanks for the report. This quest is missing indeed. Wonder when Blizzard added it 🤔 The fix will be easy
