### ISSUE TITLE
TBC Lunar Festival 2022: Elder quests 'hidden by questie'

### ISSUE THREAD

**Issue by dennisknudsen18** [Questie/Questie#3339]
## Description
The Lunar festival is ongoing now, but the quests are not shown because they are 'hidden by questie'
If I go to an elder, the quest appears in the minimap - guess that's wow doing that.

## Wowhead link
None I guess.

## Screenshots
Advanced search for the quest:
![image](https://user-images.githubusercontent.com/17129670/151762047-e8fe01c1-c228-4e4c-b715-4592af4f2413.png)

## Questie & WoW version
TBC Classic questie version 6.8.3.
WOW TBC Classic.

**Comment by dennisknudsen18** [comment]
Dates from https://www.wowhead.com/lunar-festival-guide

Modifying QuestieEvent.lua:
From
    ["22"] = {startDate = "1/2", endDate = "15/2"},
to
    ["22"] = {startDate = "31/1", endDate = "15/2"},

made the quests turn up, albeit as grey icons.

Tried to modify init of QuestieEvent.eventDateCorrections to reflect the dates but that didn't change the grey color.

**Comment by Laumesis** [comment]
Dates are corrected in v6.8.4 for year 2022.

Our DB (corrections) have wrong quest level for Elder Quests in TBC.
On TBC quest level for elder collection quests should be `-1`, and on Era/SoM `60`.
