### ISSUE TITLE
Word wrap for long texts (or another solution)

### ISSUE THREAD

**Issue by Iowerth** [Questie/Questie#3343]
Hi. There is a problem with long texts - you can't see full description and numbers:
![unknown1](https://user-images.githubusercontent.com/10152411/152763330-905dc656-9fda-443d-871f-2e325a52c5d9.png)
Word wrap can do another addon. See red selection on screenshot. If you can't do this, maybe it is possible to align numbers left? See green selection:
![unknown2](https://user-images.githubusercontent.com/10152411/152763432-db7fe81c-2364-492a-ab59-171cf9847edd.png)

**Comment by Iowerth** [comment]
Hi. Are there any news?

**Comment by BreakBB** [comment]
Hey @Iowerth nope, no progress on this, sorry.

The alignment is not that easy and neither is "good" word wrap. But we plan to do a major refactoring of the Tracker in the future, which has to fix this.

**Comment by BreakBB** [comment]
@Dyaxler @Cabro @MyTechnoHunter is this still an issue?

**Comment by Cabro** [comment]
Not anymore

**Comment by Cabro** [comment]
I only play with auto resize, so not sure how it behaves on manual size

**Comment by BreakBB** [comment]
Closing this then. I assume manual sizing will work the same
