### ISSUE TITLE
Quest Completion Point Missing for Kael'thas and the Verdant Sphere is Missing

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#3350]
Quest Completion for 

https://tbc.wowhead.com/item=32405/verdant-sphere

https://tbc.wowhead.com/quest=11007/kaelthas-and-the-verdant-sphere

**Comment by BreakBB** [comment]
I can't find an issue in our database for this 🤔 Hand in is at A'dal which is in the center of Shattrat.

**Comment by Gogo1951** [comment]
Is there something where Questie is disabled form plotting new destination points while you are in a raid, or when you leave a raid?

**Comment by BreakBB** [comment]
I don't fully remember what the current behaviour is, but in the past Questie was fully disabled while in a raid instance. IIrc Questie is now not fully disabled but also does not draw new markers when inside an raid instance. After leaving it the icons _should_ be drawn 🤔

**Comment by Gogo1951** [comment]
With Mag's head, it showed me right away. Even when I was in raid. With the KT item, it didn't show until I reloaded the UI. Dunno what the root cause is, just weird behavior. You can close this, just keep an eye out for future bugs around this stuff.
