### ISSUE TITLE
In Search of Thaelrid (1198)

### ISSUE THREAD

**Issue by Arccai** [Questie/Questie#3360]
**Misplaced in the Journey feature.**

**In Search of Thaelrid** (1198)
This is an "Breadcrumb / Alliance" quest,
but appears for Horde.

**Shouldn't exists for hordes.**

[Wowhead Link](https://classic.wowhead.com/quest=1198/in-search-of-thaelrid)

**Comment by BreakBB** [comment]
The issue #3292 shows that it is also available for Horde.
