### ISSUE TITLE
Questie v6.8.5 Tracker bug

### ISSUE THREAD

**Issue by Raggydesune** [Questie/Questie#3363]
## Bug description

When game launched, tracker was too far to the right so that I couldn't read anything on it. After resetting its position, it won't move from the center of my screen. With any combo of header, background, and/or frame it won't move even if I use ctrl+hold or regular hold (tried other combinations of ctrl, alt, and shift to no avail). Can't find anything in settings to help or unlock it.

## Screenshots

![bug1](https://user-images.githubusercontent.com/71685723/155915269-2f02d591-f763-42c1-9372-3ab3482464d6.png)
![bug2](https://user-images.githubusercontent.com/71685723/155915273-5d7cb7c7-045c-42c5-a2dd-46d4ae8b1c91.png)

## Questie & WoW version

v6.8.5 TBC Classic

**Comment by BreakBB** [comment]
Hey @Raggydesune there is a right click menu on the Tracker which has a lock/unlock functionality. Did you check that?

**Comment by Raggydesune** [comment]
The only right click menu that pops up for me is the Journey screen

**Comment by BreakBB** [comment]
@Raggydesune What I mean is right clicking a quest on the Tracker which brings up this window:

![grafik](https://user-images.githubusercontent.com/33514570/156053435-f766721f-6286-4dbf-ba9a-9a4f43558586.png)

**Comment by Raggydesune** [comment]
That seems to have fixed the issue of moving it. Thank you.
