### ISSUE TITLE
Dungeon Objectives Missing for Variety of Common Raid / Heroic Quests

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#3367]
https://tbc.wowhead.com/quest=10885/trial-of-the-naaru-strength

https://tbc.wowhead.com/quest=10884/trial-of-the-naaru-mercy

https://tbc.wowhead.com/quest=10886/trial-of-the-naaru-tenacity

https://tbc.wowhead.com/quest=10901/the-cudgel-of-kardesh

**Comment by BreakBB** [comment]
I couldn't find any issues about "The Cudgel of Kardesh". The required items are correctly linked to the NPCs which have the spawn in their raids and also the quest NPC has the correct spawn location.

**Comment by Gogo1951** [comment]
Looks good in new build!
