### ISSUE TITLE
New Questie Reset Questie Settings

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#3368]
@BreakBB 

Installing the new Questie from Curseforge reset all my tracker fonts, filters around which quests to display, and auto-complete toggles. Location of tracker wasn't reset, but that was the only setting I can see that wasn't defaulted.

**Comment by BreakBB** [comment]
The latest release had no changes except for data corrections as you can see [here](https://github.com/Questie/Questie/compare/v6.8.5...v6.8.6).

Could be your addon manager, WoW not saving settings or something like that, but nothing Questie did, sorry.

**Comment by Gogo1951** [comment]
Please double check the code that got uploaded to Curseforge. Sometimes the builds are jacked. Seen it on a few other add-ons recently.
