### ISSUE TITLE
Missing objective data for Warlock Quest "Hearts of the Lovers"

### ISSUE THREAD

**Issue by anodosian** [Questie/Questie#3379]
## Bug description

Warlock Quest "Hearts of the Lovers"  Quest ID 65593, as Undead, throws the following errors:

[ERROR] Missing objective data for quest 65593 and objective Issac's Heart
[ERROR] Missing objective data for monster ' table: 000002CCD167B240 ' 54261

## Screenshots

![Hearts of the Lovers - ERROR](https://user-images.githubusercontent.com/20913886/157363110-e488ddb0-0d60-477d-b26a-2da4ead0d5c7.png)

## Questie & WoW version

Questie version: 6.8.6
WoW TBC version: 2.5.3 (42598)

**Comment by BreakBB** [comment]
Fixed with 316c15202acc7b01d3c96637854fad7f20874222
