### ISSUE TITLE
Quest: Blood Crystals [QID:9566] Error

### ISSUE THREAD

**Issue by Cerelion** [Questie/Questie#3380]
The Burning Crusade Classic
Quest Blood Crystals (9566)
Azuremyst Isle
Once quest is turned it, journal registers it as abandoned and still shows on the minimap as available.

**Comment by BreakBB** [comment]
That is caused by the so called "desync issue". We are working on for fix for quite a while.

A simple `/reload` should remove the icon from the minimap.

**Comment by BreakBB** [comment]
Will be fixed with #3111
