### ISSUE TITLE
Most Heroic Daily Quests are Missing Objective Locations

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#3385]
Missing objective location on map.

[[70] Wanted: The Exarch's Soul Gem (11374)]

**Comment by Gogo1951** [comment]
A lot of the heroic & normal dailies are missing.

**Comment by Gogo1951** [comment]
![image](https://user-images.githubusercontent.com/55365231/167327952-68bde0f8-3019-406d-bf4d-bea3f7ba022e.png)

Another heroic daily missing objective locations.

**Comment by Cabro** [comment]
Should be fixed
