### ISSUE TITLE
Zul Aman quest:  X Marks... Your Doom!

### ISSUE THREAD

**Issue by gerinamoo** [Questie/Questie#3388]
Version 6.8.6

Getting the attached error on this quest
![Questie2](https://user-images.githubusercontent.com/71583837/160107276-91ccf2d9-acd8-4764-a109-94300a5a6ada.jpg)
![Questie1](https://user-images.githubusercontent.com/71583837/160107278-f07a11a9-eed9-4439-8fad-3b0b9de1e89f.jpg)
.

**Comment by erounsavall** [comment]
Getting the same error, same version

**Comment by Cabro** [comment]
Add in Questie\Database\Zones\zoneTables.lua line 197:

    [3805] = {{3433, 82.2, 64.2}},

**Comment by gerinamoo** [comment]
Confirmed working.  Thanks!
