### ISSUE TITLE
Quest: Heart of the Lovers - Missing Objective Data Error

### ISSUE THREAD

**Issue by Feronas** [Questie/Questie#3397]
![questie error](https://user-images.githubusercontent.com/65334149/161044838-ae0d21cf-fe40-49b3-822b-1ab411b51f22.jpg)

**Comment by BreakBB** [comment]
Hey @Feronas are you using the latest version of Questie? And did this happen on SoM, Era or TBC?

**Comment by Feronas** [comment]
Dear Björn,

I am using the latest version of questie, and this happened on TBC.

Kind regards

Sent from my iPhone

________________________________

**Comment by Feronas** [comment]
@BreakBB Hi Björn, kind follow up, any update? thank you

**Comment by BreakBB** [comment]
I have yet to look into it, sorry @Feronas

**Comment by BreakBB** [comment]
Thanks for coming back to this @Feronas I'll take another look then to fully fix this issue.

**Comment by Feronas** [comment]
@BreakBB Dear Björn, kind reminder :) the following 2 errors remains from the original issue.
![image](https://user-images.githubusercontent.com/65334149/172310692-8de14fbd-d51a-4e3e-985c-c48b2b15e48c.png)
many thanks!

**Comment by Laumesis** [comment]
Fixed with #3786, #3791
