### ISSUE TITLE
New Bug 2022-04-01 when opengame

### ISSUE THREAD

**Issue by Dedalios** [Questie/Questie#3399]
[questi1.txt](https://github.com/Questie/Questie/files/8399913/questi1.txt)
[questi2.txt](https://github.com/Questie/Questie/files/8399914/questi2.txt)
[questi3.txt](https://github.com/Questie/Questie/files/8399915/questi3.txt)
[questi4 (2).txt](https://github.com/Questie/Questie/files/8399916/questi4.2.txt)
[Questi5.txt](https://github.com/Questie/Questie/files/8399918/Questi5.txt)
New Bug 2022-04-01 when opengame after update game BBG and questie

**Comment by BreakBB** [comment]
Hey @Dedalios does this happen on SoM, Era or TBC? And did you try to disable all addons except Questie and see if the error still occurs? Sounds like an addon incompatability
