### ISSUE TITLE
Database field requiredSourceItems can not handle 6 digit numbers

### ISSUE THREAD

**Issue by BreakBB** [Questie/Questie#3402]
## Bug description

The result of `/dump QuestieDB.QueryQuestSingle(65604, "requiredSourceItems")` is `{[1]=59115}` instead of `{[1]=190187}` which results in an error about an unknown itemId.

## Screenshots

![grafik](https://user-images.githubusercontent.com/33514570/161614130-c085ca96-2ecf-4844-9955-12fba7cdc527.png)

## Questie & WoW version

v6.8.7

**Comment by Laumesis** [comment]
Teah, because itemids are using 16 bit unsigned integers atm.

**Comment by Laumesis** [comment]
Discord report, which is mosty likely also id overflow:
> I think they appeared after picking up both warlock quests 'Hearts of the Lovers' and 'Hearts of the Pure', but I'm not entirely sure
![image](https://user-images.githubusercontent.com/75958501/172075618-6e3327eb-d90e-4074-b02f-c27c25ae02df.png)

**Comment by Laumesis** [comment]
Fixed in #3786
