### ISSUE TITLE
Sometimes the quest objectives fail to load.

### ISSUE THREAD

**Issue by Cabro** [Questie/Questie#3405]
# Bug description

Sometimes the quest objectives fail to load, and you get random completion messages later for partially completed quests that are bugged in this way, when some event triggers them.

# Screenshots
![imgur](https://i.imgur.com/e4q6RU6.png)
![imgur](https://i.imgur.com/09UMuH0.png)
![imgur](https://i.imgur.com/5eeAvdp.png)

# Questie & WoW version
6.8.7 TBC

# questie settings
![settings1](https://imgur.com/YduhYy6.png)
![settings2](https://imgur.com/XTTVD0l.png)

**Comment by BreakBB** [comment]
This will be fixed with #3111 We have yet to finalize the changes we do with that PR.
