### ISSUE TITLE
"Banish the Demons" missing objective markers

### ISSUE THREAD

**Issue by Muehe** [Questie/Questie#3411]
## Description

Original report from [Discord Thread](https://discord.com/channels/263036731165638656/962549818067144714/962735600023248938)

> Questie does not display [objective] info for the Ogri'la quest Banish the Demons (both the initial and the repeatable)

The problem is that the "collection NPC" is missing, we need to create it as a correction.

## Wowhead links

https://tbc.wowhead.com/npc=23327
https://tbc.wowhead.com/quest=11026/banish-the-demons
https://tbc.wowhead.com/quest=11051/banish-more-demons

**Comment by Cabro** [comment]
Should be fixed
