### ISSUE TITLE
Quest: Murkblood Leaders...

### ISSUE THREAD

**Issue by Raulfin** [Questie/Questie#3413]
## Description

Quest: Murkblood Leaders... (9867) shows the location of Ortor of Murkblood (18204) as along the roads north and south of Halaa, on the same path as the Murkblood Invaders (18238) that drop the Murkblood Invasion Plans to start Murkblood Invaders (9872).
His correct location is 30,42 inside the main building in Sunspring Post.

## Wowhead link

https://tbc.wowhead.com/quest=9867/murkblood-leaders
https://tbc.wowhead.com/npc=18204/ortor-of-murkblood

## Questie & WoW version

TBC 2.5.4.42940
Questie 6.8.7 (completed it just before 6.9 came out)

**Comment by BreakBB** [comment]
The data we have is absolutely fine. The NPC in question has the correct location and the item is also correctly linked to it.

![grafik](https://user-images.githubusercontent.com/33514570/165564611-12843b93-0b37-4578-9316-583e3cef1e33.png)

I am quite sure this is linked to a waypoint issue we have and will merge this issue with #3282
