### ISSUE TITLE
Questie bugged my chat, can't read 

### ISSUE THREAD

**Issue by celey123** [Questie/Questie#3415]

**Comment by BreakBB** [comment]
Hey @celey123 could you fill out the information we asked for in the template? The heading of your report does not help or explain at all.

To be able to help you we need more.

**Comment by MimmiLand** [comment]
Not sure if it is the same but everytime I open the bank I get a bunch of ERROR-lines in chat. Like shown in the picture. 
![questie error](https://user-images.githubusercontent.com/100846832/163685888-78f12c17-b30d-4896-8685-ed39a5664fc6.png)

**Comment by BreakBB** [comment]
Yeah that is the same as #3412 Closing this in favor of the other

**Comment by Road-block** [comment]
This is just me thinking. I have no way to verify without running a packet sniffer.

I have the option Objective Sorting "By Zone".  I have noticed that when the error happens it's usually not all the tracked quests but some.

What if they changed something in a recent patch that keeps quests cached by zone and invalidates other zones.
In that case the objective sorting is not causing the bug but it might just be exposing it by causing a refresh on the tracker when changing zone at which point the invalidated cache for other zones makes it manifest.

Recent example: I'm doing Manalicious (cooking daily) at Netherstorm. No debug prints. I cross a zone boundary I get the ERROR! spam but it only affects my Netherwing Crystals (SMV) and Daily Heroic (HFC) quests.

Anyway I've no idea really what exactly causes the client to invalidate the cache but it's obviously happening.

**Comment by BreakBB** [comment]
Hey @Road-block I think you are reffering to the #3412 issue aren't you?

**Comment by Road-block** [comment]
I was sorry for posting under the duplicate.
