### ISSUE TITLE
Locking Issues is Childish

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#3424]
Re: https://github.com/Questie/Questie/issues/3423

So @BreakBB & @Muehe. Closing issues is childish.

As is posting and then revoking my ability to respond.

You don't plan to do anything more than keep the lights on, and you won't step away. Kind of just dooms the project, no?

Yup, same issues we had when I was working on the project. I was hoping that by me stepping away you'd come together and get something done. 

But yeah, you guys are just camping this. 

You won't make room for others. You have no desire to improve it. You won't take PRs.

Look at how much interest there was for new features.

https://old.reddit.com/r/classicwow/comments/liyxyb/upcoming_questie_updates/

@BreakBB @Muehe you can't say you want new people... but then turn people away when they try and contribute.

What's your vision for Questie? How do you see this playing out? Have it eek by into Wrath, no new features at all... just data updates? Continue to be weeks behind because nobody is doing any testing on the PTR or engaging with people on the PTR?

I'm not being mean, I'm calling you guys out for how poor a job you've done at keeping this healthy. 

It's why I had to work directly with @AeroScripts to get anything done. Without you guys, we'd have been able to move unencumbered.

You can close this, I have nothing more to add.

**Comment by Muehe** [comment]
Ok, so if I understand you right you promised a bunch of features to people, never implemented them, then stepped away, solely in the interest of the project of course, and people who stuck around to do the boring maintenance part of the work are the bad guys. Alright. But that's your version of events. Others have a different interpretation.

Features have been added over the last year, PRs have been merged.

If you feel the project is moving too slowly then fork it. Nobody is stopping you.

As I said in the locked issue, if you think #2686 in particular should have been merged than the place to discuss that is on that PR or in a dedicated issue. Just FYI though we still haven't ironed out all the taint bugs from the tracker.

But to be honest I don't really see any point beyond you venting here, there is not really any constructive criticism. Why the need to add features? How is the project "rotting" through not adding any? We don't have a quarterly report to fill out... And what manpower we have left is mostly spent on ironing out bugs. Should we ignore the bugs and just add new features instead? I really don't get your point here.

**Comment by Muehe** [comment]
It's been an hour so I'll assume you indeed don't have anything to add and close here. Just to be clear, it's not locked, so if you want to tell me anything feel free to do so here, as we don't have contact on Discord.

@AeroScripts is indeed busy with other things than WoW these days, so I don't think he'll be dropping in.

I wouldn't have locked the other issue, but I can understand why @BreakBB has no desire to discuss this with you, as you have been insulting his tireless volunteer work over the past year. I don't think what you said here or in the other issue is a fair representation of past and present events.

**Comment by Gogo1951** [comment]
@Muehe  - "promised a bunch of features to people..."

What really happened was Aero and I put out a vision for what we wanted to accomplish.

And we shared this with the group.

And we didn't get much help. 

And everyone said, "Oh, I don't want to do work when it's assigned to us, this is a volunteer project, not a job! We shouldn't have a vision or a feature map. It should just be everyone works on whatever they want, and nobody can override other people's past work, even when the user experience is shit. You can't tell me to re-factor events, or update stuff I've worked on in the past! We all work better without leadership!"

And instead of just getting out of the way, you guys fought us at ever turn.

Over things that didn't matter.  And all the times, "Take my code out!" was your default answer to everything if you disagreed with us. 

And we got as far as we got before burn out from dealing with you set in.

And look, a year later... nothing has happened. 

You guys are just holding Questie's head under the water waiting for it to drown and fade into obscurity.

Remember how hard it was to even get the roles cleaned up in Discord? Look at the number of bugs still in the quest data... oh right, I don't think any of you guys even play any more. 

And you guys are petty. You have people listed on the credits who haven't even signed in to Curseforge in 2+ years, but the moment I left Discord... gone. And a bunch of people I helped recruit to do community management, and testing, and even devs I brought in have said the same things: it's a shit group to work with.

You don't credit product managers, designers, testers. You think devs are the only ones who should get a voice... So dev... it's yours, you don't have any interference from me... and still a year in... nothing happens.

And it pisses me off that you guys aren't doing more, or aren't looking for replacements. Questie deserves better than the team of do-nothings holding it hostage.

**Comment by Muehe** [comment]
> What really happened was Aero and I put out a vision for what we wanted to accomplish.
> 
> And we shared this with the group.
> 
> But we didn't get much help.

Again, that's your interpretation. There is another I won't discuss in too much detail without permission in a public place.

My interpretation is that you gained the ear of the BDFL, got into a beef with the person who single-handedly ported Questie from 1.12 to 1.13 to the point that that person effectively left, repeatedly offended other longstanding project members, then you left yourself when you realised non of the members were really interested in your "vision".

> You guys just sort of said, "Oh, I don't want to do work when it's assigned to us, this is a volunteer project, not a job! We shouldn't have a vision or a feature map. It should just be everyone works on whatever they want, and nobody can override other people's past work, even when the user experience is shit. You can't tell me to re-factor events, or update stuff I've worked on in the past! We all work better without leadership!"

Yes, the project has always been a meritocracy of volunteers. You swooped in and wanted to lead the project hierarchically. Nobody was interested in that. Nobody was stopping you from implementing your road map either though, but you had better put your fingers where your mouth was if you wanted it done. You didn't.

And as for overwriting other peoples work, yeah that got people offended, go figure. The feature in question was at that point just recently finished by another member and you wanted to completely replace it without so much as a discussion. The UX was fine. I tried to get you to compromise and just make the feature switchable with an option, but you left before anything ever came of it and also never provided a finished implementation IIRC.

> And look, a year later... nothing has happened.
> 
> Software is a grow or die culture. If you aren't growing something, constantly improving it, warding off competitors, then you guys are just holding Questie's head under the water waiting for it to drown and fade into obscurity.

Over a thousand commits in the last year, insane number of bugs worked out, but nothing happened. Bold statement. If you want to use your corporate culture template on a project like Questie I guess your only option is starting one yourself, as it seems to me that nobody in the current team is interested in what you call "leadership".

> And you guys are petty. You have people listed on the credits who haven't even signed in to Curseforge in 2+ years, but the moment I left Discord... gone.

Well AFAIK you left Discord and the Github organisation of your own volition, so I can see why somebody would assume you just missed CurseForge. But I have no idea who did that or why. Do you want me to ask the others about it?

> And a bunch of people I helped recruit to do community management, and testing, and translators, and even devs I brought in have said the same things: it's a shit group to work with.

If that is indeed the case I invite them to discuss this with me privately or publicly. Don't know what you are talking about specifically, but we aim to always have an open ear for reasonable concerns.

> And it pisses me off that you guys aren't doing more, or aren't looking for replacements. Questie deserves better than the team of do-nothings holding it hostage.

Another rousing speech by our great leader. And you really wonder why nobody wanted to work with - or rather for - you? I'm not really sure how you can be so blind to your part in the whole situation, I guess that kind of behaviour somehow works for you in a professional setting.

You showed up to the project, offended everybody, shattered the team and its morale, then left. And now you are complaining that the cart is stuck in the mud. Yeah it was for a while, after you drove it there. But we are doing just fine now, thank you very much for your concern.

Just to make this perfectly clear: Questie is a volunteer project, everybody puts in as little or as much time as they choose. Always has been this way, always will be.

**Comment by Gogo1951** [comment]
While my claim that you guys are do-nothings may seem harsh if you weren't do-nothings you'd have done something this last year. And you'd have plans to do things in the future. You'd understand the landscape, and you'd understand that you're losing market share; other add-ons that have their finger on the pulse of the modern game. It used to be 99% of everyone had Questie installed, and the ones who didn't just didn't know about it. Now... I'd say 10% of people don't have it installed at all. They're using RXP or some other add-on. That number is only going to grow. People would rather pay $65 for a good leveling experience than use old and busted Questie. Think about the opportunity you're missing... people would rather pay than use your free product. Oof.

I don't want to belabor this, but Aero and I were working on our vision for the future, and at every turn, we got pushback. We never got a competing vision. We just got pushback. It's why I no longer wanted to work on the project, I thought if I stepped away you guys would gel again and things would get done. But sadly that hasn't happened. You guys made working on this add-on so un-fun for Aero, even without me there, that he stepped away to do other things too. Sad.

Look... here's my ask. Get motivated, or get out. It's shit or get off the pot time. If you aren't going to be the one to put the time in, make a big post on the Discord, on Reddit, on WoW Forums... "Looking for our replacements!" You've got some big issues to address.

1) Data. We can't do much around testing automation in WoW, but this is a no-brainer. Write test automation in the form of database queries to identify the quests that are missing things; spot the quests without turn in NPCs, NPCs without locations, spot items that don't have drop locations, or buy locations. You'd find 90% of the bugs before they ever hit production. Partnerships were always an option to get data too. It becomes a lot easier if you find some organization, like WoWHead or WoWDB, and just have them shore up the data. Not everything can, or should be, just a problem for devs to solve.

2) Onboarding New Devs. I remember the first time I did a data fix for Questie, I had worked to get like 50 quests added that weren't in the game. And it was fun. And it worked locally, and I was excited. But then I got my PR rejected because I didn't sort the quests by IDs. Oof. Being pedantic, it's fine, but Crux takes it to an insane level. Same feedback I've gotten when I brought in any new dev... "Is it going to be this tedious every time I check in code? They do know I just copied the code they have problems with from another Questie file, yeah? Like 99% of their existing code would pass code review..." There is a balance here, but it needs to be skewed towards making it easy for new people to come into the project. Crux has to drop the misguided "I'm the teacher" mentality and just fix minor things during the merge. Think of how much more bandwidth we'd have if new devs weren't put off the moment they tried to engage. Stop making it painful to help.

3) Bugs. Questie has so many bugs. A lot of this has to do with raids / dungeons. Zoning in and out, play for a few hours, and Questie just gets buggy. New quests stop appearing in the tracker, objectives stop appearing on the map, auto-turn glitches. Most everyone who plays the game knows to /reload when Questie is buggy, but the fact that people know this should be a great shame to everyone working on the project. There are long-standing bugs that only get identified and resolved by having devs who use the thing they built. Nobody without an active sub should be working on this. Eat your own dog food. You've got 150 or so open tickets, and nobody working to identify which are real, and aggressively prune the backlog.

4) Lack of new features. Quesite is such a great add-on. But you're foolish if you think people aren't constantly looking for something better. Every time something in Questie doesn't work quite right... every time an auto-turn in selects the 1-turn-in vs the 10-turn-in... every time you grab a daily and it doesn't show up on the map... Many more players will be back for Wrath. One of the biggest things people remember about Questing from Wrath was Quest Helper -- with predictive routes. This has been a planned feature of Questie for years, but dev bickering around how routes should work, and over-thinking things like where hills and paths are, has doomed it. RestedXP has a lot of great features, stuff that Questie realy missed the boat on launching first. DugiGuides too. But bottom line, you guys aren't interested in improving anything... and you're just sort of coasting on some old ideas... ideas that were, frankly, never that great from a UX perspective and now 10-years-in are really showing their age. Every time Aero and I wanted to re-do something, we got pushback. "Oh no, that would require you touching my code... I'll re-do it... but I don't have time, and I don't really want to re-do it... so just don't make any new features, yeah? No new features after all. Woot, we all win!" It was batshit trying to work with developers who had such a phobia of change.

I hope that you guys get your act together, I really do. But I don't think you will. The best thing for Questie would be for you all to collectively step away.

**Comment by Muehe** [comment]
You are just doing the same thing here you did while on the project. Take a minimally viable argument, spin it to death, add lots of insults and outright lies when things aren't going your way. Presto, Gogo's leadership. Nobody needs that mate.

I hope you get your act together and stop insulting people all the time, I really do. But I don't think you will.
