### ISSUE TITLE
Questie not initializing

### ISSUE THREAD

**Issue by peidshjt** [Questie/Questie#3426]
I'm running the latest version of everything... I've tried reinstalling/downloading Questie... I've cleared WTF folders... I can't get it to initialize.

<img width="729" alt="Screen Shot 2022-04-30 at 10 32 52 AM" src="https://user-images.githubusercontent.com/104691647/166116240-7e0194a2-446e-4343-abca-3dae18da6e50.png">

**Comment by Muehe** [comment]
If you can still access the Questie settings there should be a "Recompile DB" option that might help.

If you haven't already you can also try to completely delete the Questie directory and then installing again. Remember to close WoW before you do so.

**Comment by peidshjt** [comment]
Not able to access settings.. it doesnt really load at all

**Comment by dagid4** [comment]
Same for me. Happened today
![Screenshot_163](https://user-images.githubusercontent.com/22964985/166124717-b0550f54-c843-41ed-a2f2-c17ab4ce8764.png)
.

**Comment by wilsoncpw** [comment]
Exactly the same for me.  Wow Classic Era -Questie v6.9.0

**Comment by Muehe** [comment]
@peidshjt @dagid4 @wilsoncpw I can not reproduce, but with the help of Yoman on Discord I found a workaround:

```diff
diff --git a/Database/Corrections/QuestieEvent.lua b/Database/Corrections/QuestieEvent.lua
index 9e9e6912..9a12ca52 100755
--- a/Database/Corrections/QuestieEvent.lua
+++ b/Database/Corrections/QuestieEvent.lua
@@ -234,7 +234,7 @@ QuestieEvent.eventDates = {
         startDate = "13/5",
         endDate = "19/5"
     },
-    ["Children's Week"] = {startDate = "1/5", endDate = "7/5"},
+    ["Children's Week"] = {startDate = "7/5", endDate = "7/5"},
     ["Midsummer"] = {startDate = "21/6", endDate = "5/7"},
     ["Brewfest"] = {startDate = "20/9", endDate = "6/10"}, -- TODO: This might be different (retail date)
     ["Harvest Festival"] = { -- WARNING THIS DATE VARIES!!!!
```

**Comment by wilsoncpw** [comment]
Muehe, many thanks.  That worked great!

**Comment by Nikkun59** [comment]
Hi Muehe,
I am having the same issue as mentioned above. I note the workaround but do not know how or where to add this.
Can you please advise?

**Comment by Muehe** [comment]
@Nikkun59 First close WoW, then:

1. Go to the WoW directory. This is usually at `C:\Program Files (x86)\World of Warcraft\_classic_`, but there should be an option in the Battle.net launcher to go there.
2. Go to `Interface\AddOns\Questie\Database\Corrections`
3. Open the file `QuestieEvent.lua` in an editor
4. Search for `["Children's Week"] = {startDate = "1/5", endDate = "7/5"}`
5. Change `1/5` to `7/5` and save the file

**Comment by Nikkun59** [comment]
Hi Muehe,
I have shut down wow, and followed your instructions -
QuestieEvent.eventDates = {
    ["Lunar Festival"] = { -- WARNING THIS DATE VARIES!!!!
        startDate = "23/1",
        endDate = "10/2"
    },
    ["Love is in the Air"] = {startDate = "11/2", endDate = "16/2"},
    ["Noblegarden"] = { -- WARNING THIS DATE VARIES!!!!
        startDate = "13/5",
        endDate = "19/5"
    },
    ["Children's Week"] = {startDate = "7/5", endDate = "7/5"},
However, when I restart wow I get the same error as shown in the screenshot above

**Comment by Muehe** [comment]
Hmm, the only thing I can think of right now is that you might have been in the wrong directory if you have both Classic SOM and TBC installed, as the workaround seems to have worked for all other affected users so far.

**Comment by Nikkun59** [comment]
You were correct, I had not updated the Classic_era_ directory. Didnt realise that classic era was the actual Classic and TBC comes under the Classic directory.....
Thanks for your help with this. 
Have a great day/Night.

**Comment by Laumesis** [comment]
People experiencing the bug,
What langauage your WoW installation is?

**Comment by joothly** [comment]
Got the same issue in SoM, installation is in english on windows10.

Fixed it by adding the following to [...]\AddOns\Questie\Database\Zones\zoneDB.lua
```diff
213    local questsToSplit = zoneMap[QuestieDB.sortKeys.SEASONAL]
+       if questsToSplit == nil then
+           return zoneMap
+       end
214    -- Merging SEASONAL and SPECIAL quests to be split into real groups
215    for k, v in pairs(zoneMap[QuestieDB.sortKeys.SPECIAL]) do questsToSplit[k] = v end
```

Cheers.

**Comment by dagid4** [comment]
> Got the same issue in SoM, installation is in english on windows10.
> 
> Fixed it by adding the following to [...]\AddOns\Questie\Database\Zones\zoneDB.lua
> 
> ```diff
> 213    local questsToSplit = zoneMap[QuestieDB.sortKeys.SEASONAL]
> +       if questsToSplit == nil then
> +           return zoneMap
> +       end
> 214    -- Merging SEASONAL and SPECIAL quests to be split into real groups
> 215    for k, v in pairs(zoneMap[QuestieDB.sortKeys.SPECIAL]) do questsToSplit[k] = v end
> ```
> 
> Cheers.

Thanks @joothly, your workaround works. I have first tried the https://github.com/Questie/Questie/pull/3431/commits/8f29c1d74a1a76ae53adaac7f8bcca6622ec8d2a, but it didn't solve the issue.

**Comment by Laumesis** [comment]
@dagid4
I guess you didn't Recompile Database after 8f29c1d ?
That would get automatically done as Questie version changes when user updates to new Questie release.

**Comment by dagid4** [comment]
> @dagid4 I guess you didn't Recompile Database after [8f29c1d](https://github.com/Questie/Questie/commit/8f29c1d74a1a76ae53adaac7f8bcca6622ec8d2a) ? That would get automatically done as Questie version changes when user updates to new Questie release.

My apologize, I haven't recompiled, didn't know it is necessary.
