### ISSUE TITLE
zoneDB.lua:215 attempt to index loacl 'questsToSplit' (a nil value)

### ISSUE THREAD

**Issue by alexander-m-ivanov** [Questie/Questie#3429]
Hello,

the following message appeared today after I played for over a month using questie:

`zoneDB.lua:215 attempt to index loacl 'questsToSplit' (a nil value)`

The only thing I did was to log in to retail WOW and then to classic WOW. I did not try to load them at the same time.

The effect of the issue is that questie is not loading at all. I cannot use it. I tried deleting the old files and installing it anew, but it did not work. I am using the latest verison of questie: 6.9.0

**Comment by Jazzman1976** [comment]
I have the same bug. Comes out of nowhere.

**Comment by MatthewANormand** [comment]
I am having the same problem. Just happened randomly. Now my questie wont work at all. Please some help.

**Comment by BreakBB** [comment]
Hey there,

This is a duplicate of #3426 - Check that issue for a workaround.

We are already working on a real fix for this. Sorry for the trouble
