### ISSUE TITLE
Mountaineer Kadrell

### ISSUE THREAD

**Issue by CD-69** [Questie/Questie#3430]
Hi - just outside Thelsamar (32,49) two quests showing up as available from a quest giver who isn't there (Mountaineer Kadrell) - Rat Catching and Stonegear's Search. Latest version 6.9.0 running on vanilla Classic (not TBC)
![Screenshot 2022-05-01 084927](https://user-images.githubusercontent.com/104712648/166137383-28e591cd-c593-48e4-ae1b-ebfbcc6a4826.png)
.

**Comment by Cabro** [comment]
Doesn't this NPC patrol up and down the road?

**Comment by CD-69** [comment]
I did wonder that - I had a couple of looks - will check again. I'm sure there used to be a "where is?"-type tracker in one of the old mods, I'll check that too.

**Comment by BreakBB** [comment]
The Questie database also shows that this NPC travels around and does not just stand still. The world map should therefore show these patrol lines 🤔

**Comment by CD-69** [comment]
Yep, great point – I can think of several others where the track/trail is shown – but I can confirm that I do not see the patrol lines with this quest. That’s why I thought we were missing a “static” quest giver – I should have checked Wowhead for that (doh).

**Comment by BreakBB** [comment]
The partrol for this NPC is quite short @CD-69. If you use an map addon like Leatrix Maps, could you zoom in the world map and check again that no patrol like is drawn?

**Comment by CD-69** [comment]
My bad. Finally found him. I never saw him at the position of the quest marker, though – is that one end of his range? Found him down “in town” near shops and other NPCs.

**Comment by BreakBB** [comment]
Hey @CD-69 did you zoom in to check if the patrol lines are drawn for this NPC? Might be hard to see if other quest icons are near by

**Comment by CD-69** [comment]
Hey – so I went back to Thelsamar and checked, the NPC patrols through the centre of the village, with a short time spent stationary at either end; the co-ords for [11] Rat Catching look fine. I must have just kept missing him. Quest handed-in so not sure if I can see the patrol lines.

**Comment by Muehe** [comment]
Confirmed working on latest Questie version and Wotlk, waypoints are shown:

![Screenshot_20230124_221936](https://user-images.githubusercontent.com/8838573/214418917-fe4801e4-fb5d-4cdf-9203-e5414b0f7e09.png)

Waypoint data is present on the other expansions as well. Might have been a database update in the meantime. :shrug: Thanks anyway for the report @CD-69 :+1:
