### ISSUE TITLE
Error: attempt to index local 'questToSplit' (a nil value)

### ISSUE THREAD

**Issue by Minitag** [Questie/Questie#3436]
## Bug description
Questie is not loading at all and producing the error screenshot attached

## Screenshots

![Capture](https://user-images.githubusercontent.com/104731408/166157288-ccd7c172-5ceb-4219-b66a-1d5c9db084ef.PNG)

## Questie & WoW version
<!--
Which version of Questie are you using? You can find it by:
v6.8.1 but also appeared in newer versions, I tried going backward to see if it would resolve the issue
This is for Classic SoM

**Comment by Muehe** [comment]
Fix is already done and will be release shortly. Thanks for reporting though! 👍
