### ISSUE TITLE
Unable to load Questie - Error During Initialization

### ISSUE THREAD

**Issue by zephear0** [Questie/Questie#3437]
Getting the attached error: Error during intitialization.  Tried to delete entire Questie folder, close WoW then relog on with v.6.9.0 and v6.8.7.  Getting the same thing.  Could you please look into this?

Questie v6.9.0.  Classic Era.

Thanks,

![Capture](https://user-images.githubusercontent.com/104732609/166158809-8a988ad0-57c1-419e-a962-d2b1374c9668.PNG)

**Comment by Muehe** [comment]
New version 6.9.1 that should fix this was just released, please update. CurseForge and Wago uploads are still pending, but you can already get it from [here](https://github.com/Questie/Questie/releases/tag/v6.9.1).
