### ISSUE TITLE
Erreur au démarrage

### ISSUE THREAD

**Issue by Pepsiphal** [Questie/Questie#3441]
## Bug description

Nothing appears : icons on map and list of quests

## Screenshots
 DRAG and DROP or LOADING File ENABLE

Message error : "Questie:[ERROR] Erreur durant l'initialisation !Interface\Addons\Questie\Database\Zones\zoneDB.lua:215: attempt to index local 'questsToSplit' (a nil value)

## Questie & WoW versionn or TBC.
CLASSIC 1.14.2 with Questie Version 6.9.0

THANK YOU

**Comment by BreakBB** [comment]
Hey @Pepsiphal grab the newest version of Questie [v6.9.1](https://github.com/Questie/Questie/releases/tag/v6.9.1) either from here on GitHub or from the addon manager you are using. That version fixes this issue.
