### ISSUE TITLE
It fails to load everytime I log in

### ISSUE THREAD

**Issue by SingingHen** [Questie/Questie#3442]
It fails to load every time I log in. Have reinstalled it. Still fails.

Questie version 5.9.0, classic WoW.
-->
![WoWScrnShot_050222_112226](https://user-images.githubusercontent.com/104780280/166260584-25cf6a37-da9f-444b-8372-8124e3834e68.jpg)

**Comment by BreakBB** [comment]
Hey @SingingHen you are a few versions behind. The most current is v6.9.1 which includes a fix for your error.

**Comment by SingingHen** [comment]
> Hey @SingingHen you are a few versions behind. The most current is v6.9.1 which includes a fix for your error.

thanks for the heads up. I forgot to check today. It dropped an hour after I checked yesterday *sigh*
