### ISSUE TITLE
Initialization Error

### ISSUE THREAD

**Issue by brophym** [Questie/Questie#3448]
Questie not loading since Children's Week started...

Error during Initialization!
Interface\Addons\Questie\Database\Zones\zoneDB.lua:213: attempt to index local 'questsToSplit' (a nil value)

Have no idea how to fix this...

Please Help!!  I miss my Questie.....

Thanks
brophym

**Comment by BreakBB** [comment]
This has been fixed with the latest version of Questie v6.9.1 released two days ago.
