### ISSUE TITLE
"The Respect of Another" is being renamed by Questie.

### ISSUE THREAD

**Issue by Cabro** [Questie/Questie#3450]
Whenever you try to link quest (id 9898) Questie renames it chat to "Nothin' Says Lovin' Like a Big Stinger". There is no quest named like that ingame. 
I assume this renaming is Questie's erroneously doing.

**Comment by Muehe** [comment]
Well more historical than erroneous. This is one of the quests that was renamed due to the sexual harassment scandal at Blizzard.

Thanks for the report. :+1:

**Comment by Cabro** [comment]
Wow i had no idea this was the history behind.
