### ISSUE TITLE
Some quest objectives (especially ones with secondary objectives) are not redrawn when the map is reloaded (on continent switch, leaving a dungeon etc).

### ISSUE THREAD

**Issue by Cabro** [Questie/Questie#3464]
# Bug description

The addon doesn't draw quest secondary objectives on the map or minimap if the map is reloaded on continent change, dungeon/raid/arena/bg exit. This is true for quests with secondary objectives.
They will be properly drawn if you reload UI.
LE: the same is true for the quest items provided on acceptance. Their questie tooltip doesn't exist anymore.

# Screenshots
Before reload UI:
![imgur](https://i.imgur.com/yVRVe43.png)
After reload UI:
![imgur](https://i.imgur.com/ZIkzvtN.png)

# Questie & WoW version
6.10.0 TBC

**Comment by Laumesis** [comment]
I'm not sure if there is github issue for this already. But yeah, SmoothReset() is known to derp those. Will be fixed at some point
