### ISSUE TITLE
Remove minimap ! when daily has been completed?

### ISSUE THREAD

**Issue by xathian** [Questie/Questie#3476]
Is it possible to have the ! for daily quests go away once they're finished without entirely disabling them?

As it stands, if you turn off the Repeatable Quest toggle even while leaving Available on it removes all daily quest icons from the map/minimap regardless if they're available or not. I'd like all the blue !s for available dailies to show then go away after I turn them in. This would help to visibly keep track of what's left on my daily reset and what I may have missed on my map.

**Comment by Raithaam** [comment]
This seems to be a new problem, I'm having it ever since they updated for Sunwell. It's showing the ! for the precursor to the dailies, the ! for the daily after finished and the ! for the dailies that aren't available yet. Tried reinstalling and restoring the database with no change.

**Comment by BreakBB** [comment]
Hey @xathian and @Raithaam 

This is related to us currently showing ALL daily quests no matter at which state of the Isle zone your realm is.

If you enable the "Show Quest IDs" in the Advanced Options of Questie you should be able to see that the daily quest you see after completing one is a different one.

We are already working on a fix for this so players can select the state of the Isle.

Would be nice if you could add a screenshot showing the quest you completed and the one you see afterwards (with the settings "Show Quest IDs" enabled).

**Comment by Raithaam** [comment]
![WoWScrnShot_051222_115206](https://user-images.githubusercontent.com/77211907/168148054-f716a492-40b9-48d9-8712-b8bc47c463ea.jpg)
![WoWScrnShot_051222_115152](https://user-images.githubusercontent.com/77211907/168148070-104919cd-ddc2-419d-bf20-a68c91d194be.jpg)
![WoWScrnShot_051222_115059](https://user-images.githubusercontent.com/77211907/168148080-a3ad3e04-9f46-4a1d-94ec-2305d06c4acd.jpg)
![WoWScrnShot_051222_115047](https://user-images.githubusercontent.com/77211907/168148084-60e9cc9f-0bd9-4162-a5cc-eb2148b8731d.jpg)
![WoWScrnShot_051222_115124](https://user-images.githubusercontent.com/77211907/168148419-ec707e1c-554b-4b55-9424-e9d627ec24f6.jpg)

So here are the tooltips showing both the first quest, and the repeatable quest as available when mousing over the NPC or the ! on the minimap. Sorry for the screen clutter, gotta get to work! hehe

**Comment by BreakBB** [comment]
Yeah @Raithaam thanks for the screenshots!

This is exactly what I meant in the previous comment, Questie currently shows ALL quests from ALL the "Isle of Quel'Danas phases". It does not hide the ones that are no longer available because your server already progressed to the second phase and also does not hide the ones that you can not accept yet because your server did not progress to the required phase yet.

I am currently fixing this by adding a option menu to select the phase your server is at so the users can control which quests to show and which not. Questie has no way to know the phase each server is at on the Isle.

**Comment by Raithaam** [comment]
Cool yeah, that makes sense. Appreciate all the work you do!!!
