### ISSUE TITLE
LUA Error on Quest Turn In

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#3491]
Message: ...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:370: bad argument #1 to 'mod' (number expected, got nil)
Time: Tue May 17 00:10:24 2022
Count: 2
Stack: ...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:370: bad argument #1 to 'mod' (number expected, got nil)
[string "@Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua"]:761: in function <...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:717>
[string "=[C]"]: ?
[string "=[C]"]: in function `mod'
[string "@Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua"]:370: in function `CompleteQuest'
[string "@Interface\AddOns\Questie\Modules\Quest\QuestEventHandler.lua"]:162: in function `QuestTurnedIn'
[string "@Interface\AddOns\Questie\Modules\Quest\QuestEventHandler.lua"]:338: in function <...e\AddOns\Questie\Modules\Quest\QuestEventHandler.lua:334>

Locals: errMsg = "...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:370: bad argument #1 to 'mod' (number expected, got nil)"
isBugGrabber = nil
tsmErrMsg = nil
oldModule = nil
private = <table> {
 globalNameTranslation = <table> {
 }
 FormatErrorMessageSection = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:517
 ErrorHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:134
 origErrorHandler = <function> defined @Interface\SharedXML\SharedBasicControls.lua:355
 hitInternalError = false
 CreateErrorFrame = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:536
 num = 0
 SanitizeString = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:510
 AddonBlockedHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:502
 GetStackLevelInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:344
 ParseLocals = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:396
 ignoreErrors = false
 errorReports = <table> {
 }
 IsTSMAddon = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:478
 localLinesTemp = <table> {
 }
 GetStackInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:313
}
MAX_STACK_DEPTH = 50
OLD_TSM_MODULES = <table> {
 1 = "TradeSkillMaster_Accounting"
 2 = "TradeSkillMaster_AuctionDB"
 3 = "TradeSkillMaster_Auctioning"
 4 = "TradeSkillMaster_Crafting"
 5 = "TradeSkillMaster_Destroying"
 6 = "TradeSkillMaster_Mailing"
 7 = "TradeSkillMaster_Shopping"
 8 = "TradeSkillMaster_Vendoring"
 9 = "TradeSkillMaster_Warehousing"
}

**Comment by BreakBB** [comment]
Hey @Gogo1951 can you tell which quest it was you turned in?

**Comment by Muehe** [comment]
@Gogo1951 Also, does the error go away when you disable `TradeSkillMaster` addon?

**Comment by BreakBB** [comment]
Nah @Muehe I think I already found the issue, but wasn't able to test this yet. TSM only adds a custom error handler so that's the reason it appears in the stack trace.

**Comment by BreakBB** [comment]
The linked commit above fixed this rare error.

**Comment by Gogo1951** [comment]
Fixed in latest release.
