### ISSUE TITLE
TBC quest missing tooltips - Disrupt the Greengill Coast

### ISSUE THREAD

**Issue by Offroads** [Questie/Questie#3498]
## Description
The quest [[70] Disrupt the Greengill Coast (11541)] is missing objectives on the map and tooltips.
https://tbc.wowhead.com/npc=25073/darkspine-siren drops https://tbc.wowhead.com/item=34483/orb-of-murloc-control
You use those on https://tbc.wowhead.com/npc=25084/greengill-slave 
It is completed in this area: 
![image](https://user-images.githubusercontent.com/28876369/168931622-44e892ee-3518-4495-bd00-3b195e88b50d.png)

## Wowhead link
https://tbc.wowhead.com/quest=11541/disrupt-the-greengill-coast
https://tbc.wowhead.com/npc=25073/darkspine-siren
https://tbc.wowhead.com/item=34483/orb-of-murloc-control
https://tbc.wowhead.com/npc=25084/greengill-slave 

## Questie & WoW version
Questie v6.10.2
TBC

**Comment by BreakBB** [comment]
Great report @Offroads thanks! I will look into this soon and push an update.

**Comment by BreakBB** [comment]
Fixed in 259baa5b44c6f49d271c89701013ef57353be8ff and already released
