### ISSUE TITLE
TBC quest missing toolstips - Discovering Your Roots

### ISSUE THREAD

**Issue by Offroads** [Questie/Questie#3499]
## Description
The quest [Discovering Your Roots ](https://tbc.wowhead.com/quest=11520/discovering-your-roots) is missing tooltips and map objectives.
You need to kill [Razorthorn Flayer](https://tbc.wowhead.com/npc=24920/razorthorn-flayer) to get [Razorthorn Flayer Gland](https://tbc.wowhead.com/item=34255/razorthorn-flayer-gland) which is used to tame a [Razorthorn Ravager](https://tbc.wowhead.com/npc=24922/razorthorn-ravager)
Using [Expose Razorthorn Root](https://tbc.wowhead.com/spell=44935/expose-razorthorn-root) on a Razorthorn Dirt Mound will expose a [Razorthorn Root](https://tbc.wowhead.com/item=34254/razorthorn-root)

I would suggest putting some markers on the map here:
![image](https://user-images.githubusercontent.com/28876369/168931699-728fe5da-ceb6-411d-8b5c-cc89a5bd6e56.png)
and tooltip on the flayers to indicate they drop Razorthorn Flayer Gland

## Wowhead link
https://tbc.wowhead.com/quest=11520/discovering-your-roots
https://tbc.wowhead.com/npc=24920/razorthorn-flayer
https://tbc.wowhead.com/item=34255/razorthorn-flayer-gland
https://tbc.wowhead.com/npc=24922/razorthorn-ravager
https://tbc.wowhead.com/spell=44935/expose-razorthorn-root
https://tbc.wowhead.com/item=34254/razorthorn-root

## Questie & WoW version
Questie v6.10.2
TBC

**Comment by BreakBB** [comment]
Another great report, thanks @Offroads

My server didn't unlock Phase 4 yet, but will soon :tm:. I will fix this together with the other new quests once I can test it 👍🏻
