### ISSUE TITLE
Can't install from github via Ajour (no TBC release found)

### ISSUE THREAD

**Issue by Rewyn** [Questie/Questie#3501]
Yes, I know Ajour isn't further developed anymore, but it works perfectly fine in most cases for addons from github for me.
And this seems like an easy enough fix, so figured I'd give it a shot.
It basically just tells me there's no release available for TBC under the github releases. Not sure if its as simple as somehow tagging the releases as such, or if it just looks for something like "bcc" in the filename.
Addons like WA2 (https://github.com/WeakAuras/WeakAuras2/releases/tag/3.7.16) for example work perfectly fine.

**Comment by BreakBB** [comment]
Hey @Rewyn 

I agree with your that Ajour most likely just looks for `-tbc`, `-bcc` suffixes on the GitHub ZIPs.

We just publish one ZIP file which works on Classic Era, SoM and TBC. Therefore we don't have specific ZIP files for each game version.

I will talk with the team if we will change that, but I don't think it really is useful for an addon manager that is not actively developed anymore. Especially as there are many alternatives which do the same. I guess you should just give WowUpa shot.

**Comment by Laumesis** [comment]
I didn't search, but any pointer to documentation of `releasae.json`?

**Comment by Laumesis** [comment]
@Talryn If you want help even more, do you know some project using the packager and producing a single ZIP which works in all game versions?

**Comment by Talryn** [comment]
I cannot think of one but perhaps it is as simple as using the WeakAuras example and just making one release entry for each game version but they all point to the same file.

Here is the WeakAuras release.json:

```json
{
    "releases": [
        {
            "filename": "WeakAuras-4.0.1-bcc.zip",
            "nolib": false,
            "metadata": [
                {
                    "flavor": "bcc",
                    "interface": 20504
                }
            ]
        },
        {
            "filename": "WeakAuras-4.0.1-classic.zip",
            "nolib": false,
            "metadata": [
                {
                    "flavor": "classic",
                    "interface": 11402
                }
            ]
        },
        {
            "filename": "WeakAuras-4.0.1.zip",
            "nolib": false,
            "metadata": [
                {
                    "flavor": "mainline",
                    "interface": 90200
                }
            ]
        }
    ]
}
```

If you wanted to generate the release.json, I think you could use this as a template but the file name would be the same for each game version.  Just update the interface for each game version to the appropriate version number.

**Comment by Talryn** [comment]
It looks like you can simplify it by having multiple metadata entries.

From `https://github.com/mooreatv/AuctionDB`:

```json
{
    "releases": [
        {
            "filename": "AuctionDB-v1.06.04.zip",
            "nolib": false,
            "metadata": [
                {
                    "flavor": "classic",
                    "interface": 11402
                },
                {
                    "flavor": "mainline",
                    "interface": 90200
                },
                {
                    "flavor": "bcc",
                    "interface": 20504
                }
            ]
        }
    ]
}
```

**Comment by Muehe** [comment]
@Rewyn @Talryn I have added automatic creation of a release file to our build script. I also created a file manually and added it to our latest release (6.11.0) for testing purposes.

FYI @BreakBB

**Comment by Rewyn** [comment]
This went far beyond what I expected, works like a charm for the latest release.
