### ISSUE TITLE
Constant Errors in Chat Box

### ISSUE THREAD

**Issue by Jokaleth** [Questie/Questie#3502]
## Bug description
Occasionally get a ton of error notices, often completely filling the chat box. Happens randomly when doing quest things.

## Screenshots
![image](https://user-images.githubusercontent.com/87456827/169103757-d3d0883a-ba82-4266-9139-ed7da5c38b87.png)

## Questie & WoW version
Questie v6.10.2
WoW TBCC v2.5.4.43638

**Comment by BreakBB** [comment]
This is a known issue as described in #3412 We are working on a fix for this.

A workaround can be to disable the "LootReserve" Addon.

**Comment by Jokaleth** [comment]
> This is a known issue as described in #3412 We are working on a fix for this.
> 
> A workaround can be to disable the "LootReserve" Addon.

I disabled that addon, but I am still getting the same errors.
