### ISSUE TITLE
Keeps automatically swapping to phase 4 of Isle despite being in 3.1

### ISSUE THREAD

**Issue by Jokaleth** [Questie/Questie#3503]
## Bug description
As the title says, Questie keeps automatically switching the Isle Phase to be 4 when it should be in 3.1. The badge vendor/Anvil and Forge was completed this morning and it's been happening since then

## Screenshots
![image](https://user-images.githubusercontent.com/87456827/169104215-fef4d6f3-c890-4c20-98a3-887147f81800.png)

## Questie & WoW version
Questie v6.10.2
WoW TBCC v2.5.4.43638

**Comment by BreakBB** [comment]
Oh, that is clearly an issue then. Thanks for reporting this @Jokaleth we will look into it to get a fix out soon :)
