### ISSUE TITLE
XP rewards at lvl 70 in TBC classic

### ISSUE THREAD

**Issue by 7Krown7** [Questie/Questie#3511]
I was searching for optimal quests to turn in when WOTLK will come out. 
Turns out when you reach max lvl (70), questie do not show the xp rate given by quests when you shift a quest on the map.

Maybe there is an option to restore the option but i can't find it :(

Help please

**Comment by BreakBB** [comment]
Hey @7Krown7 I wonder why you closed this issue.

We are actually planning to (at least) show XP values on quests at max level so you can save them for turn in as a head start for Wrath.

For me I'll reopen it since I know many other users asking for this.
