### ISSUE TITLE
Download bug

### ISSUE THREAD

**Issue by Selket2** [Questie/Questie#3516]
TBC I cant download questie through Curseforge. It literally just sits there 'processing'. It doesnt download.

**Comment by BreakBB** [comment]
Hey @Selket2 

If you try to download it manually then you can also use the ZIP from our [GitHub release](https://github.com/Questie/Questie/releases/download/v6.11.0/Questie-v6.11.0.zip).

If you use the CurseForge client then try restarting it. Not much we can do about it, sorry.
