### ISSUE TITLE
Quest doesn't show the tracker come up when killing mobs

### ISSUE THREAD

**Issue by Toxicreaction** [Questie/Questie#3519]
While questing on one of my toons I notice the tracker only works on the little quest tracker on the side vs coming on the middle of the screen announcing the tracker. While on the same computer but other toons I am noticing that the tracker shows on the left side but also will show on the screen the count of something where it would track the quest. I have reinstalled questie, my game and removed WTF folder otherwise and still am seeing this issue for this toon only. I have turned all my addons off just questie on and still noticing the issue. Is there anything that I can try maybe setting wise that would have stopped the tracker from showing on the screen vs just the quest tracker area?

**Comment by Toxicreaction** [comment]
Still an issue anyone have any ideas?

**Comment by Laumesis** [comment]
Could you give a screenshot telling what you mean, please. Sorry that I can't understand from explanation what you mean.

**Comment by Toxicreaction** [comment]
Yep no problem. So to specify the center of the screen tracking I am referring to is the big yellow at the top of my screenshot. The regular tracker is on the right side. How do I make it so the center tracker shows as well?
![InkedWoWScrnShot_053022_090712_LI](https://user-images.githubusercontent.com/106268279/170999158-3c5fe612-7579-445f-bef4-5de2aa07edf3.jpg)

**Comment by Laumesis** [comment]
"The center tracker" comes from default game interface, not from Questie. And Questie *should* not affect it.

Have you tested disabling *all* addons to see if it works then?

**Comment by Toxicreaction** [comment]
Yea, I have done that. To note it works on all my alts but not my main. Is there a command I can type in that would turn it back on by chance?

**Comment by Muehe** [comment]
@Toxicreaction If this also happens with no addons enabled it's probably not a Questie problem. I'd suggest you contact Blizzard support and let them know the problem happens without any addons on a fresh install. If you find (or have found) a solution feel free to post it here.
