### ISSUE TITLE
Error during Initialization

### ISSUE THREAD

**Issue by qKorey** [Questie/Questie#3521]
Having an error randomly pop up, not sure what it could be. 

![Screenshot_1](https://user-images.githubusercontent.com/106286158/170388755-85d718ac-f494-4169-8ae1-41d095b3a85d.png)

Im running Version 6.11.0 on TBC version of the game.

**Comment by MyTechnoHunter** [comment]
Open questie options and go to the advancedand tell  it to rebuild the database

**Comment by Muehe** [comment]
@qKorey Any updates? Did recompiling the DB help?

**Comment by Muehe** [comment]
Assumed solved, please re-open or create a new issue if you still have problems.
