### ISSUE TITLE
Play sound when quest objective is finished

### ISSUE THREAD

**Issue by Laumesis** [Questie/Questie#3526]
Play sound when quest objective is finished. So sleepy player can stop grinding quest mobs.

**Comment by Gogo1951** [comment]
Exited in the Routes branch.

https://github.com/Questie/Questie/tree/routes

We had an announce sound for completing an objective, and a sound for completing a quest. There was logic set up to not play the objective sound if it completed the quest.

From the testers we had running this, it was a really popular feature. Nice little audio reward for players.
