### ISSUE TITLE
GetQuest: The quest doesn't exist in QuestLogCache. 7261

### ISSUE THREAD

**Issue by yavour** [Questie/Questie#3531]
Recently I noticed questie has some glitches. Ex. The quest icons did not show corretly on big map or for certain characters even he does not accept a quest the icons still show on big map.
And it constantly reported such error info in chat window. Screenshot as the following:
![image](https://user-images.githubusercontent.com/1232373/170849002-24ddde5f-da7a-45b4-8668-72d8b5e83500.png)

I tried reset in questie or rebuild the quest database but neither does not work.
Could you help check this? Thanks a lot in advance.

**Comment by Muehe** [comment]
@yavour Can you please test if deactivating `NDui` addon removes the error?

Quite a lot of things changed in Questie's backend in the last versions and if `NDui` uses our code that might lead to this problem.

**Comment by yavour** [comment]
OK I see. I will test that and let you know. Yes these errors just popped up only in the recent 1-2 versions. And I have uesed questie and NDui together since long ago.

**Comment by yavour** [comment]
> @yavour Can you please test if deactivating `NDui` addon removes the error?
> 
> Quite a lot of things changed in Questie's backend in the last versions and if `NDui` uses our code that might lead to this problem.

By disbling NDui, these errors are gone during character initialization. And when turning on NDui again, these errors appeared again.

**Comment by yavour** [comment]
Hi Muche, any updates for this issue? Or any workaround? The current version of Questie I am using is 6.12.1 for BCC2.5.4

**Comment by Muehe** [comment]
@yavour Sorry for not being clear earlier, I think what happens here is that Questie is only printing the error, but the problem is actually that NDui is using our code (that changed) in a (now) wrong way, that creates this error. They have to fix this on their end I believe.

If this turns out to be an incorrect assessment feel free to re-open this issue or create a new one, but until then I'm suggesting you turn to the NDui developers (I think they use CurseForge for communication).

**Comment by yavour** [comment]
> @yavour Sorry for not being clear earlier, I think what happens here is that Questie is only printing the error, but the problem is actually that NDui is using our code (that changed) in a (now) wrong way, that creates this error. They have to fix this on their end I believe.
> 
> If this turns out to be an incorrect assessment feel free to re-open this issue or create a new one, but until then I'm suggesting you turn to the NDui developers (I think they use CurseForge for communication).

Thank you for your clarification. I posted this issue to NDui author a couple of days ago.
And in release log of latest version on yesterday it mentioned they fixed the error  of name plate support to Questie quest indicator.
