### ISSUE TITLE
not able to get quests where i have to talk to someone appear on the map

### ISSUE THREAD

**Issue by stirnergang** [Questie/Questie#3532]
as the title says quests where I'm meant to talk to someone and its not the final phase of the quest seem to be bugged for me right now or not working. 
![image](https://user-images.githubusercontent.com/106483225/170878248-2a70b311-454a-4843-b0fa-e032ae26c0a9.png)
![image](https://user-images.githubusercontent.com/106483225/170878256-800debd9-8a6c-44f4-9193-be8d6c62f2e8.png)
Hopefully these images show the problem that is occuring for me as the "on guard in stonetalon" quest isn't appearing on the map if this is a known issue or something i may need to change in my addon settings as this issue has only occured with a recent questie update.

**Comment by Laumesis** [comment]
Does it show up if you do  `/reload` ?

**Comment by stirnergang** [comment]
nope

**Comment by Jokaleth** [comment]
> Does it show up if you do `/reload` ?

I am having the same issue and I can confirm it does not show up with a reload or even a relog.

 It does not show up on the minimap or regular map

![image](https://user-images.githubusercontent.com/87456827/170879441-f6d85226-ec21-42cc-8b10-ecded7020d11.png)

![image](https://user-images.githubusercontent.com/87456827/170879462-d7e6599b-21e3-4316-b2d1-b49935a0f781.png)

**Comment by Laumesis** [comment]
are you still on the quest?
Could you show output of
`/dump GetQuestLogTitle(GetQuestLogIndexByID(1070))`
and
`/dump C_QuestLog.GetQuestObjectives(1070)`
please.

**Comment by stirnergang** [comment]
![image](https://user-images.githubusercontent.com/106483225/170879681-8145d34d-1558-47ac-ad12-47daee68930d.png)
![image](https://user-images.githubusercontent.com/106483225/170879691-f3ae5c24-19eb-4ca9-90df-1ce6107df7c3.png)
![image](https://user-images.githubusercontent.com/106483225/170879700-a627caee-77c6-499d-b50b-38305cfdb3a9.png)
![image](https://user-images.githubusercontent.com/106483225/170879714-9d26161e-8409-4131-91b0-7b43c5d50f03.png)

**Comment by Laumesis** [comment]
Thank you for report. It is a new bug in v6.12.0 code. I'll fix it.

**Comment by stirnergang** [comment]
ah nice

**Comment by Laumesis** [comment]
Fixed in v6.12.1
