### ISSUE TITLE
Hellfire Fortifications quest 

### ISSUE THREAD

**Issue by Zarak456** [Questie/Questie#3537]
## Description
Hellfire Fortifications shows as level 60 quest. It should be a level 55 quest with no quest level. It may be a level -1 quest.  (That it will show as your level, as level 60 quest if you're 60 and a level 70 quest if you're 70)

## Wowhead link
https://tbc.wowhead.com/quest=10110/hellfire-fortifications

##Screenshot
![hellfire fortification](https://user-images.githubusercontent.com/106586294/171658098-0a733851-0807-425e-8ce4-1a0b12207e1a.png)

## Questie 
Version: 6.12.1   TBC Classic

**Comment by Zarak456** [comment]
i have lvl 70 and questie shows me that it is lvl 60 quest (low lvl quest) but in my quest log i have it in yellow color

**Comment by drejjmit** [comment]
Yes, then it should be quest level -1 and not 60

**Comment by Zarak456** [comment]
yes its bugged
