### ISSUE TITLE
Addon communitcations between Questie and Reputable can lead to network problems for users of Reputable

### ISSUE THREAD

**Issue by Muehe** [Questie/Questie#3540]
Thanks @Road-block for reporting ([on Discord](https://discord.com/channels/263036731165638656/579966856085897216/981193094609395772)).

TBC
Questie 6.12.1 and lower

We use data from [Reputable](https://www.curseforge.com/wow/addons/reputable) sent over the [SendAddonMessage](https://wowpedia.fandom.com/wiki/API_C_ChatInfo.SendAddonMessage) interface for daily quests.

The way we do it right now can trigger a network issues that requires a system reboot for users of Reputable, as per [this thread on Curse](https://www.curseforge.com/wow/addons/reputable#c109).

We call [SendAddonMessage here](https://github.com/Questie/Questie/blob/6fb47766cf87fafb832070ecc3d7312e0e4cc90a/Modules/QuestieInit.lua#L211-L212), which is what triggers the problem apparently.

It is probably safe to just remove the Send calls and rely on the [Register call here](https://github.com/Questie/Questie/blob/6fb47766cf87fafb832070ecc3d7312e0e4cc90a/Modules/Network/QuestieComms.lua#L161) passively getting the data, but would need to be tested/refactored.

We should just remove the SendAddonMessage calls in the next update either way, in order to not trigger the "network bomb" for some Reputable users.

Long term we would probably want to exchange daily quest info through our own comms module, in a way that is properly throttled, instead of relying on other addons. Case in point, Reputable seems to be abandoned (for now).

**Comment by BreakBB** [comment]
This will be fixed with #4106
