### ISSUE TITLE
The Deadliest Trap Ever Laid  quest

### ISSUE THREAD

**Issue by Zarak456** [Questie/Questie#3544]
## Description
The Deadliest Trap Ever Laid quest don’t show on map as  blue !  (missing on map)

## Wowhead link
https://tbc.wowhead.com/quest=11101/the-deadliest-trap-ever-laid

## Screenshots
![deadliest trap ever laid 1](https://user-images.githubusercontent.com/106586294/171674903-5d2ac33f-308a-44b9-95ea-2d0c3bf7b33a.png)
![deadliest trap ever laid 2](https://user-images.githubusercontent.com/106586294/171674934-a2c94b37-0e78-470c-8070-d5fe8ea1a03e.png)

## Questie & WoW version
Version: 6.12.1  TBC

**Comment by BreakBB** [comment]
From the linked issue above:

> Quests id: 11097 for scryer and 11101 for aldor, should show up once you get revered with Netherwing.

**Comment by Zarak456** [comment]
I am exalted with Netherwing and still dont show up.

![deadliest trap ever laid](https://user-images.githubusercontent.com/106586294/176137617-61c8c00b-c1b9-4f39-b4ef-5dc00a022396.png)

**Comment by BreakBB** [comment]
Yes @Zarak456 I didn't fix this yet. Seems like the reputation requirements are not correct yet on our side.

**Comment by Zarak456** [comment]
still bugged

**Comment by Zarak456** [comment]
fix it please

**Comment by BreakBB** [comment]
Hey @Zarak456 sorry for taking so long to fix this issue 🙈 With the start of the Wotlk beta our priorities shifted towards that, but I will try to get a fix out for this, this week.

**Comment by Zarak456** [comment]
thanks
