### ISSUE TITLE
Lag spikes when auto-accepting from specific NPC while having Leatrix Plus installed

### ISSUE THREAD

**Issue by Muehe** [Questie/Questie#3552]
Reported by Dom6#6515 ([on Discord](https://discord.com/channels/263036731165638656/579966856085897216/983100584846569522))

> Hello all, I've noticed a bug with Questie when used in conjunction with another addon that lets you automate dialogue/quests as well (in my case Leatrix).
> 
> The only time I've ever had this happen is during the Weekly Fishing Extravaganza in STV, when talking to all the NPCs with the blue questionmarks for the repeatable turn-ins (Fishbot 5000, Jang, Riggle Bassbait). It should also be noted that these NPCs are slightly bugged on my server and probably most servers, that there is actually two of each NPC after someone turns in and the NPCs sort of "respawn" on top of each other - I am not sure if this is part of the problem.
> 
> Anyways, when dialoguing through them - I get brought through and attempt to do each of their repeatable turn ins, but shortly after doing that my game gets incredibly laggy and I proceed to get disconnect from the server. Logging back in everything is fine, but as soon as I go to interact and get stuck in that loop again, I can reproduce it and get disconnected.
> 
> Addons used in conjunction to trigger this in my case: Questie, Leatrix Plus
> 
> ![A](https://cdn.discordapp.com/attachments/579966856085897216/983100583990935693/unknown.png)

**Comment by Cabro** [comment]
I think Blizzard fixed their own mess here
