### ISSUE TITLE
Auto-hiding tracker in instances

### ISSUE THREAD

**Issue by silverhawke249** [Questie/Questie#3567]
## Description

Currently, Questie offers the option to auto-minimize tracker in dungeons (which I assume, works in raids/battlegrounds/arenas as well). Is it possible to add the option to completely hide the tracker in instances? Perhaps even a more fine-tuned setting like "Don't change/Minimize tracker/Hide tracker" for each type of instance (dungeon/raid/battleground/arena).

**Comment by BreakBB** [comment]
Hey @deadmeu would you mind creating a new issue and explain what you need? There is the "Minimize In Dungeons" setting in the Tracker section, which should also collapse the Tracker when entering a BG (though the name is misleading).

> disable Questie entirely

This will be quite hard and I don't understand the need.
