### ISSUE TITLE
A Thief's Reward available after completion

### ISSUE THREAD

**Issue by dlecina** [Questie/Questie#3570]
## Bug description

Despite #2124 apparently being fixed and the quest appearing in My Journey as completed, A Thief's Reward still appearing in my map as available in all Alliance Festival Flamekeepers after completion. The issue persists after reloading and even restarting.

## Screenshots

![WowClassic_OmoSoZ1c9A](https://user-images.githubusercontent.com/1137825/175281613-2c8b7d8e-1697-4689-b232-3a71be3aa49a.png)

![WowClassic_0oAMaHNSUJ](https://user-images.githubusercontent.com/1137825/175281694-c42cf67d-33c1-4316-88f6-392b0b6599b0.png)

## Questie & WoW version

Questie v.6.12.2
TBC build 20504

**Comment by BreakBB** [comment]
Hey @dlecina could you do me a favor and run the following two commands in the ingame chat and report the output?

```
/dump C_QuestLog.IsQuestFlaggedCompleted(9339)
/dump C_QuestLog.IsQuestFlaggedCompleted(9365)
```

**Comment by dlecina** [comment]
```
[19:33] Dump: value=C_QuestLog.IsQuestFlaggedCompleted(9339) 
[19:33] [1]=false 
[19:33] Dump: value=C_QuestLog.IsQuestFlaggedCompleted(9365) 
[19:33] [1]=true
```

**Comment by BreakBB** [comment]
You are an Alliance player, right @dlecina ?

**Comment by dlecina** [comment]
I am!

**Comment by BreakBB** [comment]
Thanks for reporting, testing and keep coming back to this @dlecina - This helped a lot 👍🏻
