### ISSUE TITLE
"Against the Legion" Objectives Missing

### ISSUE THREAD

**Issue by stratoru** [Questie/Questie#3584]
## Description
Quest "Against the Legion" is not showing any objective information on the map, minimap, or tooltips. 

## Wowhead link
https://tbc.wowhead.com/quest=10641/against-the-legion

## Screenshots
![image](https://user-images.githubusercontent.com/43893231/177198932-425a4ddc-5add-4313-b71a-0ae3c4c38853.png)

Screenshot shows quest log description (objectives should highlight that Wrath Priestess should be killed), open map showing no objective markers, tooltip showing no objective information, and Questie Tracker showing I am actively tracking the quest. 

## Questie & WoW version
v6.12.3
TBCC

**Comment by BreakBB** [comment]
Hey @stratoru did you do a `/reload` to see if this error persists?

**Comment by stratoru** [comment]
> Hey @stratoru did you do a `/reload` to see if this error persists?

Seems to have fixed the issue. Odd, I did not get any interface errors during this.

**Comment by BreakBB** [comment]
Could it be that you have been in a dungeon before doing this quest? I know of an issue that "extraObjectives" are not correctly loaded again after leaving a dungeon.

**Comment by Muehe** [comment]
@BreakBB Do you need this as a reminder to look into the extraObjectives-thingy or can it be closed?
