### ISSUE TITLE
Report to Nasuun - Not auto-flagged complete if you bypass

### ISSUE THREAD

**Issue by Mazz312** [Questie/Questie#3586]
There are two SSO quests relating to a vendor on IQD sending you back to Shattrath to speak with the portal daily questgiver when unlocked. If you bypass this quest and and speak to Nasuun / start the portal daily, it appears these quests are flagged as completed and/or disappear from the tradesman. 

Questie does not flag them as completed/remove them from the Shattrath quest list when this happens. 

## Screenshots
![image](https://user-images.githubusercontent.com/19984148/177227259-63d5a218-7ce5-4f4e-8309-41c6a60c1ff8.png)

## Questie & WoW version
Questie - v6.12.3

Please also state if your quest issue is about Classic Era/SoM or TBC.
TBC

**Comment by Laumesis** [comment]
It *should* be shown as unobtainable at that point. - after fixing. No idea if anything has done to this yet.

**Comment by Muehe** [comment]
We need to find out if the two "Report to Nasuun" quests (11517/11534) become available again when the daily resets. If they don't this needs a database format change, because when the daily resets we would show the quests as available again because the API says it's unfinished.

**Comment by BreakBB** [comment]
Closing this in favor of #4012
