### ISSUE TITLE
The Amphitheater of Anguish: Yggdras!

### ISSUE THREAD

**Issue by catasstropy** [Questie/Questie#3589]
## Description
Missing objective data

## Wowhead link
https://www.wowhead.com/wotlk/quest=12932/the-amphitheater-of-anguish-yggdras

## Screenshots
![image](https://user-images.githubusercontent.com/89228211/178892151-1f55b543-7d76-4e1a-944d-697855b7aa1d.png)

## Questie & WoW version
7.0.0 Wotlk 3.4.0.44644

**Comment by BreakBB** [comment]
Fixed in e5096a852428a31b1a0f035ae457890e81b1548a
