### ISSUE TITLE
The Amphitheater of Anguish: Magnataur!

### ISSUE THREAD

**Issue by catasstropy** [Questie/Questie#3590]
## Description
Missing objective data

## Wowhead link
https://www.wowhead.com/wotlk/quest=12933/the-amphitheater-of-anguish-magnataur

## Screenshots
![image](https://user-images.githubusercontent.com/89228211/178892975-4ef0cf50-12e4-40e9-8508-7c94123b4a88.png)

## Questie & WoW version
7.0.0 Wotlk 3.4.0.44644

**Comment by BreakBB** [comment]
Fixed in e5096a852428a31b1a0f035ae457890e81b1548a
