### ISSUE TITLE
Objective locations missing for "A Bear of an Appetite"

### ISSUE THREAD

**Issue by BreakBB** [Questie/Questie#3617]
## Wowhead link

https://www.wowhead.com/wotlk/quest=12279/a-bear-of-an-appetite

**Comment by Karl-HeinzSchneider** [comment]
Most of the spawn points (School of Northern Salmon)
![cRhldTh](https://user-images.githubusercontent.com/56960197/179646429-47f20986-e536-413f-933e-0ccf8e4a73e6.png)
.

76.7 16.8
78.4 18.2
78.9 20.4
79.4 21.5
78.2 22.0
76.3 24.6
75.5 26.9
75.6 29.1
75.1 32.6
75.5 34.4
76.5 34.5
77.1 36.3
77.9 37.7
80.1 38.7
79.9 41.2
81.3 45.6
82.3 46.2
81.7 47.7
82.5 48.3
83.3 49.6

They respawn quickly, and seem fixed
