### ISSUE TITLE
Objective locations missing for "One Size Does Not Fit All"

### ISSUE THREAD

**Issue by BreakBB** [Questie/Questie#3633]
## Description

> Incorrectly shows that the Proto-whelp mob can drop the item "Westguard Cannonball" requried for the quest

## Wowhead link

https://www.wowhead.com/wotlk/quest=11190/one-size-does-not-fit-all

**Comment by drejjmit** [comment]
01b6b4a2e2e4b33a69401775d89ca5131ed34fb6
