### ISSUE TITLE
Extra objective for "Break the Blockade" would be very helpful

### ISSUE THREAD

**Issue by BreakBB** [Questie/Questie#3636]
## Description

> Could use an additional objective at 28.1, 42.2 (the location of the zeppelin) to remove any confusion and maybe save someone from swimming all the way out to the boats 😂

## Wowhead link

https://www.wowhead.com/wotlk/quest=11153/break-the-blockade

**Comment by drejjmit** [comment]
c61095364364fa476ba7a1bcae8a835233f101b1
