### ISSUE TITLE
Wrong objective location for "Scare the Guano Out of Them!"

### ISSUE THREAD

**Issue by BreakBB** [Questie/Questie#3641]
## Description

> Questie incorrectly shows that the "Riven Widow" mobs can drop the "Darkclaw Guano" quest item. The "Darkclaw Bat" is correctly marked.

## Wowhead link

https://www.wowhead.com/wotlk/quest=11154/scare-the-guano-out-of-them

## Screenshots

![image](https://user-images.githubusercontent.com/33514570/179216591-5e956e02-fb5a-4e71-90cb-8a1970f7b105.png)

**Comment by BreakBB** [comment]
[Discord Link](https://discord.com/channels/263036731165638656/998043521103712266/998043521103712266)

**Comment by drejjmit** [comment]
31ac0f0292d6705871cafddb4c4011dc03616e38
