### ISSUE TITLE
Objective locations missing for "The Storm King's Vengeance"

### ISSUE THREAD

**Issue by BreakBB** [Questie/Questie#3649]
## Wowhead link

https://www.wowhead.com/wotlk/quest=12919/the-storm-kings-vengeance

**Comment by Karl-HeinzSchneider** [comment]
Prince Navarius: 32.6 63.6
Algar the Chosen: (circle around) 28 46  (https://www.wowhead.com/npc=29872/algar-the-chosen)
Thrym: pat betweeen 31 67 and 14.5 67

**Comment by BreakBB** [comment]
> Mousing over Vargul Slayer should not show the objective for Prince Navarius - instead, it should track "Scourge Slain"

**Comment by BreakBB** [comment]
Thsi is already fixed
