### ISSUE TITLE
Objective locations missing for "Runes of Compulsion"

### ISSUE THREAD

**Issue by BreakBB** [Questie/Questie#3650]
## Wowhead link

https://www.wowhead.com/wotlk/quest=12093/runes-of-compulsion

**Comment by Karl-HeinzSchneider** [comment]
Overseer Durval 67 29
Overseer Krogan 71 34
Overseer Lochli 74 37
Overseer Brunon 78 43

from https://www.wowhead.com/wotlk/quest=12093/runes-of-compulsion#comments:id=504611 etc, and confirmed on beta

**Comment by BreakBB** [comment]
Fixed with dfad6615b2746aaabfdd6420440349508b8cbd61
