### ISSUE TITLE
Hand of Adal Quest Numbers have Changed

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#3660]
I think the Hand of Adal Quest Number shifted in Wrath.

Anyway legs of that chain are showing up as available for me, but I've completed the chain already and the quests aren't actually available in game.

![image](https://user-images.githubusercontent.com/55365231/179360154-d352c390-1477-456e-ae5c-95cc411692f2.png)

**Comment by Cabro** [comment]
Should be fixed
