### ISSUE TITLE
Showing Event Quests when Event Quests are Turned Off

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#3661]
May just be this one quest.

![image](https://user-images.githubusercontent.com/55365231/179360290-27fb4e12-74a8-4c5c-ae63-f78f10b1078a.png)

![image](https://user-images.githubusercontent.com/55365231/179360332-9a51075e-bcf7-4473-8b65-e277bf2dc214.png)

**Comment by BreakBB** [comment]
Merging this with #3624 Most quests should already be hidden
