### ISSUE TITLE
Making Peace - Missing Objective

### ISSUE THREAD

**Issue by catasstropy** [Questie/Questie#3678]
## Description
Missing Objective

## Wowhead link
https://www.wowhead.com/wotlk/quest=12573/making-peace

## Screenshots
![image](https://user-images.githubusercontent.com/89228211/179379262-d9382968-419b-44c3-ac39-252ca13170c0.png)

## Questie & WoW version
v7a14 WotLK 3.4.0.44644

**Comment by BreakBB** [comment]
Fixed with the triggerEnd commit
