### ISSUE TITLE
Header colour change

### ISSUE THREAD

**Issue by Mace-Dindu** [Questie/Questie#3679]
## Description

![image](https://user-images.githubusercontent.com/104075538/179379341-ee1961fd-8bb6-4f84-88b5-ae83ddc58b61.png)

With the newest blue header for Quests its rather difficult to see what the quests actually are under specific conditions (vibrant greens, greens, etc). Could you possibly revert it back to the default yellow text or could you possibly add a colour picker so we can choose the colour of the Quest headers. Thanks

**Comment by MyTechnoHunter** [comment]
unless i missed it it might not even be questie.. did they re-enable the questie tracker cause last i read it was defaulted to off and the tracker in question is the games.. 
if it is questie, pretty sure those would be dailies? or repeatable.. 

now you got me curious..

**Comment by BreakBB** [comment]
Hey @Mace-Dindu 

Not sure what you mean with "special conditions". All repeatable quests now have a blue header and all the quests in your screenshot are daily quests.

Non repeatable quests will still show in green/yellow/red depending on the level difference.

**Comment by BreakBB** [comment]
@MyTechnoHunter the Tracker is only disabled for the Wotlk beta at this point.
