### ISSUE TITLE
Falsely showing "A Disturbance In The West" as available

### ISSUE THREAD

**Issue by BreakBB** [Questie/Questie#3688]
## Description

[Discord Link](https://discord.com/channels/263036731165638656/997907530044944414/997907530044944414)

## Wowhead link

https://www.wowhead.com/wotlk/quest=12439/a-disturbance-in-the-west

**Comment by BreakBB** [comment]
This seems to be breadcrumb quest for https://www.wowhead.com/wotlk/quest=11995/your-presence-is-required-at-stars-rest

**Comment by Ksamal** [comment]
Still an issue should be reopened. Still shows after completing quests in chain after it.
