### ISSUE TITLE
Quest objectives missing for WoTLK-beta: "A Suitable Test Subject" - Borean Tundra

### ISSUE THREAD

**Issue by DDnutz** [Questie/Questie#3706]
## Description
 Quest Objective not showing up at all for this quest.

## Wowhead link
https://www.wowhead.com/wotlk/quest=11719/a-suitable-test-subject

## Screenshots
 
![WoWScrnShot_071822_112508](https://user-images.githubusercontent.com/59131125/179546263-9cbf5650-65e5-440c-971a-1ec8c34e373e.jpg)

## Questie & WoW version
 WOTLK - BETA

**Comment by DDnutz** [comment]
was my own fault for not reading the quest. Closing, all better now.

**Comment by BreakBB** [comment]
Hey @DDnutz not sure why you closed this. Did Questie show you what to do or not? If not then this issue should stay open so we can fix it.

**Comment by DDnutz** [comment]
Yeah, was my own fault, I need to Learn to read the quest.On Jul 18, 2022 12:07 PM, Björn Böing ***@***.***> wrote:
Hey @DDnutz not sure why you closed this. Did Questie show you what to do or not? If not then this issue should stay open so we can fix it.
