### ISSUE TITLE
Bitter Departure

### ISSUE THREAD

**Issue by catasstropy** [Questie/Questie#3707]
## Description
Missing Objective

## Wowhead link
https://www.wowhead.com/wotlk/quest=12832/bitter-departure

## Screenshots
![image](https://user-images.githubusercontent.com/89228211/179654304-272eb942-aecf-4606-898d-64cae39e17a9.png)

## Questie & WoW version
v7a14 WotLK 3.4.0.44644

**Comment by BreakBB** [comment]
Fixed in 9e87c995fded11cea651d6976e772a57327144a4
