### ISSUE TITLE
Armor of Darkness

### ISSUE THREAD

**Issue by catasstropy** [Questie/Questie#3737]
## Description
Missing Objective

## Wowhead link
https://www.wowhead.com/wotlk/quest=12979/armor-of-darkness

## Screenshots
![image](https://user-images.githubusercontent.com/89228211/179895119-65f0efa2-b54f-4bb9-a179-a8dfc6b4b666.png)

## Questie & WoW version
v7a18 WotLK 3.4.0.44644

**Comment by Cabro** [comment]
Commenting on this - it's one of the quests completely missing from database. Title not very useful for spotting this report

**Comment by ejaandersson** [comment]
[Quest Item: Dark Armor Sample (42204)](https://www.wowhead.com/wotlk/item=42204/dark-armor-sample)
[Mob: Stormforged War Golem (29380)](https://www.wowhead.com/wotlk/npc=29380/stormforged-war-golem)

**Comment by BreakBB** [comment]
Fixed in 46561dd17b82aadd5f9b5308099aa58ca8a80cbf
