### ISSUE TITLE
Wrong objective locations for "Dirty, Stinkin' Snobolds!"

### ISSUE THREAD

**Issue by BreakBB** [Questie/Questie#3772]
## Description

> Questie shows the Magmoth Forager, Magmoth Shaman, and Mate of Magmothregar mobs as dropping the Crafty's Stuff required for the quest, cannot replicate on beta. They only loot from the object Crafty's Stuff (Object ID 187689).

## Wowhead link

https://www.wowhead.com/wotlk/quest=11645/dirty-stinkin-snobolds

**Comment by Cabro** [comment]
Should be fixed
