### ISSUE TITLE
Not showing "Scouting the Sinkholes" as available

### ISSUE THREAD

**Issue by BreakBB** [Questie/Questie#3781]
## Description

> I could pick this quest up before Questie thought I should be able to. My guess is that it's requiring the quest Give Fizzcrank the News (11873) to be complete, but I can pick up Scouting the sinkholes before handing in that quest, as per the screenshot.
>
> I don't know what the true pre-requisite is: it might be accepting Give Fizzcrank The News (but not necessarily having handed it in), it might be a quest earlier in the chain like I guessed in the screenshot. Will need further testing.

## Wowhead link

https://www.wowhead.com/wotlk/quest=11713/scouting-the-sinkholes

**Comment by Cabro** [comment]
Should be fixed
