### ISSUE TITLE
The Black Shield Quest -  Dustwallow Marsh 

### ISSUE THREAD

**Issue by Dale218** [Questie/Questie#3782]
The Black Shield Quest -  Dustwallow Marsh 

The App incorrectly shows that the Darkfang Spiders randomly populating the zone will drop the acidic venom sacs. They do not. The DarkMIST spiders that are found northwest of Brackenwall drop them.

**Comment by BreakBB** [comment]
Hey @Dale218 is this a report for TBC or Classic or Wotlk beta?

I know for sure that from Classic to TBC they changed it, so that the DarkFANG Spiders also drop the acid venom sacs.

**Comment by Dale218** [comment]
I just killed 25 of them with no drop. They don't drop it nor does the
quest indicate that they would.

**Comment by BreakBB** [comment]
What version is this report for @Dale218 ? Classic Era, SoM, TBC or Wotlk?

**Comment by Dale218** [comment]
Tbc.
