### ISSUE TITLE
Questie quest error still present somehow.

### ISSUE THREAD

**Issue by Cabro** [Questie/Questie#3783]
Was just opening bank when i had this error pop up on me.

![imgur](https://imgur.com/xVrxg4v.png)

Since i know it is related, i use LootReserve. Seems this compatibility is not full.

**Comment by PleaseFixTY** [comment]
I received the same error, for these questIds today. Not sure if it's related, but the only area that my map has been showing quest objectives for (for the past week+) has been the isle of quel danas. 
10253 0 1
9572 0 3
9496 0 3
11500 0 1
9853 0 1
10290 0 1
10405 0 1
10481 0 1
10704 0 2
11521 0 1
10901 0 2 
11164 0 1
11166 0 3

**Comment by PleaseFixTY** [comment]
I deleted the questie addon and reinstalled--seems to be working for me now. not sure if that will fix the issue on your end.

**Comment by Laumesis** [comment]
@PleaseFixTY that's different.

@Cabro  ack.
There is one (or two) known bug still, but your looks another. How long that was from login and do you remember if you had opened bank earlier, or accepted/abandoned/progressed any quest?

**Comment by Cabro** [comment]
I had completely missed the reply. It happened after bank interaction.

**Comment by Cabro** [comment]
Haven't seen this one happen in a long time
