### ISSUE TITLE
Falsely showing "Of Traitors and Treason" as available

### ISSUE THREAD

**Issue by drejjmit** [Questie/Questie#3788]
https://www.wowhead.com/quest=12297/of-traitors-and-treason

Could not figure out what the pre quest is. Not available as a fresh 80.

Not to be confused with ~~quest=12171/of-traitors-and-treason~~

**Comment by Road-block** [comment]
https://discord.com/channels/263036731165638656/579966856085897216/1001737373278814249 might be relevant

**Comment by Road-block** [comment]
The TL;DR is 
1. The quests in this chain <https://www.wowhead.com/wotlk/quest=11157> turn the 12171 version off.
2. The 12297 alternative version only becomes available after <https://www.wowhead.com/wotlk/quest=11250> has been completed.
