### ISSUE TITLE
[[27] Deep Cover (2458)]

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#3795]
Rogue quest shows as complete before it's actually complete.

You have to fire a flare gun twice, then salute the guy to turn him friendly.

Questie shows the quest as complete, but when you run up to turn it in he kills you. Need to do the objectives first.

**Comment by Laumesis** [comment]
which game and questie version?

**Comment by Gogo1951** [comment]
@Laumesis It's broken on all. The data for these quests don't change until Cata.

**Comment by Gogo1951** [comment]
It's your default, "I don't want to do work..." response. It gets old. Rogues have reported broken quests for a long time... the issue is the are all little one-off quests. What other quest in the game requires you to "/salute" before turning in? None. It's gotta be listed as an objective... I don't think Quesite supports that. Just adding it as a bug in hopes that someday someone gives a shit enough to fix all the rogue quests that have been overlooked for... 4 years?

**Comment by Laumesis** [comment]
There is a thing... objectless quests aren't necessary complete. There should be different logic used for quests that are type of "go talk to turn-in npc". Iiirc there was some flag for this or something. I can't remember anymore.

Questie use and has always used the no objectives -> go talk to npc who is turn-in.
