### ISSUE TITLE
[[28] Mission: Possible But Not Probable (2478)]

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#3796]
![image](https://user-images.githubusercontent.com/55365231/180628864-b7a8f8ac-cd31-446e-ad0f-886d10db57f1.png)

Incorrectly shows one of the items as being ON the boss but it's actually in a chest behind him.

![image](https://user-images.githubusercontent.com/55365231/180628897-143e07e4-2029-489d-aa4d-1851e3e10762.png)

**Comment by BreakBB** [comment]
Classic Era, SoM, TBC or Wotlk beta?

**Comment by drejjmit** [comment]
Do you remember the name of the chest/object it was looted from?
