### ISSUE TITLE
Pre quests missing for quests in "Agmar's Hammer" quest hub

### ISSUE THREAD

**Issue by BreakBB** [Questie/Questie#3816]
## Description

The following quests were not available:

- Victory Nears...
- The Kor'kron Vanguard!
- Message from the West
- Black Blood of Yogg-Saron
- Strengthen the Ancients
- Containing the Rot
- Strength of Icemist
- To Dragon's Fall
- Marked for Death: High Cultist Zangus

**Comment by BreakBB** [comment]
https://www.wowhead.com/wotlk/quest=12056/marked-for-death-high-cultist-zangus requires https://www.wowhead.com/wotlk/quest=12036/from-the-depths-of-azjol-nerub

**Comment by BreakBB** [comment]
https://www.wowhead.com/wotlk/quest=12034/victory-nears

requires

https://www.wowhead.com/wotlk/quest=12008/agmars-hammer

**Comment by BreakBB** [comment]
https://www.wowhead.com/wotlk/quest=12224/the-korkron-vanguard

requires

https://www.wowhead.com/wotlk/quest=12072/blightbeasts-be-damned

**Comment by Yttrium-tYcLief** [comment]
Some of these have already been fixed over time; the remainders will be fixed+corrected by #4326
