### ISSUE TITLE
Questie shows only one of possible many finisher NPCs and Objects of quest

### ISSUE THREAD

**Issue by Laumesis** [Questie/Questie#3818]
If a quest has multiple NPCs or Objects where the quest can be turned in, then questie shows only one of those.

**Comment by BreakBB** [comment]
Is there any example quest for this to be an actual bug?

**Comment by Cabro** [comment]
Are you referring to the case where there are different NPC ids to turn the quests in to? Or a single id NPC with multiple locations? 
Because the 2nd case is not present anymore (if it was in the past).
