### ISSUE TITLE
Questie Tracker can break when updated in-combat

### ISSUE THREAD

**Issue by Road-block** [Questie/Questie#3819]
## Bug description
Questie tracker fails to update if the update is attempted while in combat.
For example: Picking up a new quest with auto-track enabled while in-combat, or completing an objective etc.

The buttons on the tracker for quest item use are secure so their whole anchor hierarchy becomes protected.
Protected frames are prohibited from show/hide/move or re-anchor during combat both explicitly and implicitly (if a re-anchor show/hide etc of a parent frame would cause them to change state)

```lua
1x [ADDON_ACTION_BLOCKED] AddOn 'Questie' tried to call the protected function 'Questie_TrackedQuests:ClearAllPoints()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `ClearAllPoints'
[string "@Questie\Modules\Tracker\QuestieTracker.lua"]:610: in function `Update'
[string "@Questie\Modules\Tracker\QuestieTracker.lua"]:1231: in function `Update'
[string "@Questie\Modules\Quest\QuestieQuest.lua"]:357: in function `val'
[string "@Questie\Modules\TaskQueue.lua"]:8: in function <Questie\Modules\TaskQueue.lua:6>
```
The easiest solution is probably to defer prohibited updates on the tracker to combat exit (alpha + color changes are fine, show/hide/move/reanchor not). So some kind of CombatQueue.

## Questie & WoW version
Questie Version: v6.13.1
WoW Version: BCC 2.5.4.44400 enGB

**Comment by Road-block** [comment]
```ml
1x [ADDON_ACTION_BLOCKED] AddOn 'Questie' tried to call the protected function 'Questie_BaseFrame:SetHeight()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `SetHeight'
[string "@Questie\Modules\Tracker\QuestieTracker.lua"]:1248: in function `Update'
[string "@Questie\Modules\Quest\QuestieQuest.lua"]:356: in function `val'
[string "@Questie\Modules\TaskQueue.lua"]:8: in function <Questie\Modules\TaskQueue.lua:6>
```
Questie Version: v7.0.2
WoW Version: Wrath prepatch 3.4.0.45435 enUS

**Comment by BreakBB** [comment]
Arg 🙈  thanks @Road-block for reporting back on this. Yeah, looks like I missed another point for this. The upper one should be fixed.
