### ISSUE TITLE
error on login

### ISSUE THREAD

**Issue by houlia** [Questie/Questie#3859]
This is Questie 6.13.2 on TBCC live.  I only see this on 1 character (mage).

5:59] Interface\AddOns\Questie\Modules\Map\QuestieMap.lua:557: No UiMapID or fitting parentAreaId for areaId : 3535 - Warbringer O'mrogg
[21:55:59] [string "@Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua"]:951: in function <...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:949>
[string "=[C]"]: in function `error'
[string "@Interface\AddOns\Questie\Modules\Map\QuestieMap.lua"]:557: in function `DrawWorldIcon'
[string "@Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua"]:889: in function <...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:836>
[string "@Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua"]:701: in function <...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:646>
[string "=[C]"]: in function `xpcall'
[string "@Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua"]:949: in function <...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:947>
[string "@Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua"]:1004: in function `PopulateObjectiveNotes'
[string "@Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua"]:502: in function `GetAllQuestIds'
[string "@Interface\AddOns\Questie\Modules\QuestieInit.lua"]:242: in function <Interface\AddOns\Questie\Modules\QuestieInit.lua:162>

[21:55:59] Questie: [ERROR] [QuestieQuest]: v6.13.2 - There was an error populating objectives for Tear of the Earthmother 10670 1 No error

**Comment by BreakBB** [comment]
Hey @houlia it seems there is some required information missing in our database for this quest. Thanks for reporting, we will get a fix out for this quest soon 👍🏻

**Comment by BreakBB** [comment]
Hey @houlia it seems that you are using wowup and got the wrong Questie version (you got the latest Wrath-beta version instead of the stable TBC version). Can you delete the current Questie folder and then install the following version?

https://github.com/Questie/Questie/releases/download/v6.13.2/Questie-v6.13.2.zip

We are already working on a fix together with wowup.

**Comment by Raina1007** [comment]
@houlia  Hey, I'm a mod for WowUp team. Is there any chance you can hop into our discord so we can try to figure out how you ended up w/ the wrong version of Questie? You can use this link to get to our discord if you aren't part of it yet. https://discord.gg/aewPPjnJQ5
