### ISSUE TITLE
Objective locations missing for "But First My Offspring"

### ISSUE THREAD

**Issue by BreakBB** [Questie/Questie#3877]
## Description

> Given you need to kill and revive Cursed Offspring of Har'koa mobs, it should track on them.

## Wowhead link

https://www.wowhead.com/wotlk/quest=12632/but-first-my-offspring

**Comment by Yttrium-tYcLief** [comment]
fixed with https://github.com/Questie/Questie/commit/1e0b2acdfdf1f29c27cb5841f05397b8b1a3b2f2 (forgot to include "fixes" comment in commit)
