### ISSUE TITLE
Wrong objective locations for "Relics of the Snow Leopard Goddess"

### ISSUE THREAD

**Issue by BreakBB** [Questie/Questie#3878]
## Description

> They don't drop from Cursed Offspring of Har'koa, just the tablet relics around the area. Nor do they drop off Claw of Har'koa mobs nor Har'koan Subduers.

## Wowhead link

https://www.wowhead.com/wotlk/quest=12635/relics-of-the-snow-leopard-goddess

**Comment by Cabro** [comment]
wotlkItemFixes.lua

>        [38677] = {
>            [itemKeys.npcDrops] = {},
>        },
