### ISSUE TITLE
Available quest "Into the Fold" is not shown

### ISSUE THREAD

**Issue by BreakBB** [Questie/Questie#3902]
## Description

> Quest is available to pick up without any prequests, however it is not shown by Questie on the map.

## Wowhead link

https://www.wowhead.com/wotlk/quest=11978/into-the-fold

**Comment by BreakBB** [comment]
Moreover the "Horde Armaments" do not drop from mobs (remove NPC source)

**Comment by Yttrium-tYcLief** [comment]
Worth noting this quest is actually not eligible to be picked up without any prequests - it has *two* possible lead-in prequests, `11977` [A Tauren Among Taunka](https://www.wowhead.com/wotlk/quest=11977/a-tauren-among-taunka) *or* `11979` [The Taunka and the Tauren](https://www.wowhead.com/wotlk/quest=11979/the-taunka-and-the-tauren). The former is part of the chain stemming from Borean Tundra, the latter can be picked up at a higher level without prereqs from Agamar's Hammer, however you need to at least complete one of them before you can pick up Into the Fold.
