### ISSUE TITLE
Objective location missing for "The Thane of Voldrune"

### ISSUE THREAD

**Issue by BreakBB** [Questie/Questie#3916]
## Description

> One quest objective for getting Flamebringer in the west of Voldrune is missing on the map.

## Wowhead link

https://www.wowhead.com/wotlk/quest=12259/the-thane-of-voldrune
AND
https://www.wowhead.com/wotlk/quest=12255/the-thane-of-voldrune

**Comment by Gogo1951** [comment]
[[74] The Thane of Voldrune (12259)] 
- missing talk to dragon location

**Comment by Yttrium-tYcLief** [comment]
this one's fixed in my bundle of edits, will be in a PR shortly
