### ISSUE TITLE
Objective locations missing for "Not-So-Honorable Combat"

### ISSUE THREAD

**Issue by BreakBB** [Questie/Questie#3923]
## Description

> No Map location marker for the Battlescar Spire, coordinates are 28.7x, 52.0y

## Wowhead link

https://www.wowhead.com/wotlk/quest=13137/not-so-honorable-combat

**Comment by Yttrium-tYcLief** [comment]
fixed with https://github.com/Questie/Questie/commit/1a063d59bd7505146a916428d96a9f89f6776476
