### ISSUE TITLE
Objective locations missing for "Banshee's Revenge"

### ISSUE THREAD

**Issue by BreakBB** [Questie/Questie#3924]
## Description

> Map location for the War Horn of Jotunheim is 18.1x, 56.3y

## Wowhead link

https://www.wowhead.com/wotlk/quest=13142/banshees-revenge

**Comment by Yttrium-tYcLief** [comment]
fixed with https://github.com/Questie/Questie/commit/92706b6d898d18552280c82709af73bfd5a88ec6
