### ISSUE TITLE
What happened to quest progress/complete sounds?

### ISSUE THREAD

**Issue by Painstormx** [Questie/Questie#3929]
Like the title says...
Quite some time ago, there were discussions about adding options to attach quest complete/progress sounds to Questie, since it handles the events anyway.
Did that nice addition completely die?

Would love to have this since when you are grinding away for quests, you're not always paying attention to screen messages.

**Comment by BreakBB** [comment]
Hey @Painstormx this is still on our list, we didn't find the time to implement it yet though. I'll merge this with #3526
