### ISSUE TITLE
"Chamber of Secrets" quest showing up in Darnassus for Horde characters

### ISSUE THREAD

**Issue by BreakBB** [Questie/Questie#3935]
## Description

The [NPC Argent Emissary](https://www.wowhead.com/wotlk/npc=16285/argent-emissary) should be located in EPL and is not available in Darnassus.

## Wowhead link

https://www.wowhead.com/wotlk/quest=12616/chamber-of-secrets

**Comment by Muehe** [comment]
This seems to be incorrect, in fact we are missing the locations in the Horde capitals:

> To begin with, we recommend you that you visit an Argent Emissary in any Alliance / Horde major city, and pick up the following quests:

[Source: Warcraft Tavern Guide](https://www.warcrafttavern.com/wotlk/news/scourge-invasion-guide-wotlk-pre-patch/)

It stands to reason that the NPCs themselves aren't hostile to either faction and the quest could be accepted in hostile capitals.
