### ISSUE TITLE
Mudrock Soup and Bugs objectives in incorrect place on the map

### ISSUE THREAD

**Issue by RichieSM** [Questie/Questie#3939]
## Description
The Alliance quest "Mudrock Soup and Bugs" is showing the incorrect map locations in game. See the third Wowhead link for the true locations.

## Wowhead link
Quest: https://www.wowhead.com/wotlk/quest=1204/mudrock-soup-and-bugs
Item: https://www.wowhead.com/wotlk/item=5883/forked-mudrock-tongue
Items dropped by: https://www.wowhead.com/wotlk/npc=4397/mudrock-spikeshell#map

## Screenshots
![WoWScrnShot_081022_154052](https://user-images.githubusercontent.com/4363217/183930531-1dba638b-0c13-4548-a172-88d5731750c4.jpg)

## Questie & WoW version
v6.14.0
TBC Classic

**Comment by BreakBB** [comment]
This is no longer an issue
