### ISSUE TITLE
Questie completely stopped working for me this morning.

### ISSUE THREAD

**Issue by Stealthycat** [Questie/Questie#3941]
I uninstalled questie through curseforge, then reinstalled and still nothing is showing up on my map in game.  Not sure what happened.  I am running version v6.14.0

**Comment by BreakBB** [comment]
Hey @Stealthycat sorry for the late response. For this urgent help you should [join our Discord](https://discord.gg/s33MAYKeZd) which will get you faster responses.

Do you still need help or did you figure it out?

**Comment by BreakBB** [comment]
Glad you got it fixed @Stealthycat 

If anything else pops up feel free to open up a new issue.
