### ISSUE TITLE
[TBC] "Ursius of the Shardtooth" quest line not showing up for Alliance.

### ISSUE THREAD

**Issue by Kolmarwow** [Questie/Questie#3942]
## Description
The quest chain that starts off with "Ursius of the Shardtooth" in Winterspring does not show up for Alliance characters. I believe this was originally a Horde only quest in vanilla and was changed to neutral in TBC (in fact Wowhead still shows it as being horde-only). 

## Wowhead link
https://tbc.wowhead.com/quest=5054/ursius-of-the-shardtooth

## Questie & WoW version
Questie v6.14.0
WoW 2.5.4

**Comment by BreakBB** [comment]
This was fixed in 50cd07437fbb4d328bcf9302620488ab6dd43be9
