### ISSUE TITLE
[[37] Frostmaw (1136)]

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#3944]
You can't complete this quest in OHB. Objectives for it shouldn't show up there.

![image](https://user-images.githubusercontent.com/55365231/184266618-262e00d9-e6e8-456b-bff8-e2a3ad63252e.png)

**Comment by BorniPL** [comment]
Can confirm - marker shown, the mob (https://www.wowhead.com/wotlk/npc=2385/feral-mountain-lion) doesn't spawn there.

**Comment by BreakBB** [comment]
It actually shows the spawn for the Caverns of Time dungeon where you travel through the old Hillsbrad Foothills 😅 I'll remove the spawns.
