### ISSUE TITLE
[WotLK] Breadcrumb quests show as available

### ISSUE THREAD

**Issue by economou** [Questie/Questie#3949]
## Description

I have a character (70 Tauren Druid) that has completed (just about) all available quests in the game.  After copying the character to the 3.4 PTR, the latest version of Questie shows the following quests as available on my map:

- Delivery to the Sepulcher (9189)
- Ranger Sareyn (9358)
- Report to Tarren Mill (9425)
- Gaining Acceptance (13662)

I've visited the quest-giver in each case and confirmed these quests are _not_ available.

## Wowhead link

- https://www.wowhead.com/wotlk/quest=9189/delivery-to-the-sepulcher
- https://www.wowhead.com/wotlk/quest=9358/ranger-sareyn
- https://www.wowhead.com/wotlk/quest=9425/report-to-tarren-mill
- https://www.wowhead.com/wotlk/quest=13662/gaining-acceptance

## Screenshots

![questie](https://user-images.githubusercontent.com/11949200/184683483-5731a560-c6c9-4a4b-9987-1b080b1be25e.jpg)

## Questie & WoW version

v7.0.0-beta.2

**Comment by economou** [comment]
Two more quests to add from Outland:

- Failed Incursion (9876)
- Can't Stay Away (10180)

- https://www.wowhead.com/wotlk/quest=9876/failed-incursion
- https://www.wowhead.com/wotlk/quest=10180/cant-stay-away

**Comment by BreakBB** [comment]
Thanks for the report @economou sadly our base database changed quite a bit with the move from TBC to Wotlk and therefore these issues now show up. Will be easy to fix though 👍🏻

**Comment by BreakBB** [comment]
The other quests have been fixed in b2d502db8002f6df0582ca3c56da55e141387f24
