### ISSUE TITLE
Missing objective locations for "Fate of the TItans"

### ISSUE THREAD

**Issue by BreakBB** [Questie/Questie#3968]
## Description

> Map marker for only 1 of 4 temples(Life 64.3x, 46.8y)
> Please add map coordinate marker for other 3 temples:
> Winter = 52.6x, 56.9y
> Order = 53.5x, 42.3y
> Invention = 45.5x, 49.2y

## Wowhead link

https://www.wowhead.com/wotlk/quest=12986/fate-of-the-titans

**Comment by drejjmit** [comment]
a3b87b92cddd61cb3a659f2fb3575e6cc86f4162
