### ISSUE TITLE
Continent and zone drop menu are gone on the World Map

### ISSUE THREAD

**Issue by vbakinskiy** [Questie/Questie#3974]
I faced this issue on TBC client 2.5.4. I'm using the latest version v6.14.0 of Questie. When I installed it, these drop menus are gone. After uninstalling they come back.

<img width="1480" alt="Screenshot 2022-08-25 at 07 39 01" src="https://user-images.githubusercontent.com/62370020/186576369-24700ba6-ceca-4d17-bf27-ec5480baccab.png">

**Comment by MyTechnoHunter** [comment]
Known game issue questie specifically mentions it when you log into the game

Remove for reasons of tainting menus if I recall

**Comment by vbakinskiy** [comment]
So, will it be fixed soon?

**Comment by MyTechnoHunter** [comment]
Short answer until the game fixes its taint problem no removing the drop-downs is the fix

**Comment by BreakBB** [comment]
Duplicate of #3277 We are aware of it, but adding them back will (at this point) cause more harm than help. The [Leatrix Maps](https://www.curseforge.com/wow/addons/leatrix-maps-wrath) addon adds its own dropdowns to work around this issue though
