### ISSUE TITLE
Tracker isn't Updating when in Vehicle

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#3978]
![image](https://user-images.githubusercontent.com/55365231/187054803-44d9b4d9-ad85-4d89-89ac-84a7f41826b1.png)

Note I'm not in combat.

![image](https://user-images.githubusercontent.com/55365231/187054808-88203c94-c532-4f11-8702-08ef18818624.png)

Also when I land and exit the vehicle, it still doesn't update until I click on a quest.

![image](https://user-images.githubusercontent.com/55365231/187054832-bf960bc7-a909-487a-9a25-4e540caed914.png)

This was really bad during the Death Knight start zone, as you had a cannon quest and a few others and since Questie replaces the default tracker it's really impossible to see how far along you are without opening the quest log.

**Comment by Gogo1951** [comment]
Eww, and I turned the quest in but it's still showing on the tracker as incomplete, and I get an interface error.

![image](https://user-images.githubusercontent.com/55365231/187054883-7728adcd-13d9-4dd1-a11b-1ff14e9c761b.png)

**Comment by Muehe** [comment]
My brother in Christ, I appreciate you still sending reports and I swear we will get to them soon™, but for the love of God please add a Questie version and the WoW expansion. :sob: :pray: 

I assume this is TBC PTR and Questie 6.14.0 (latest atm)?

Also about that interface action failed, any addons beside Questie and did you have scriptErrors turned on on that particular client?

**Comment by Gogo1951** [comment]
Wrath Beta. Talk about Death Knight start zone should have helped give it away.

**Comment by BreakBB** [comment]
The Tracker isn't updating when in combat, due to API limitations. This is kind of an edge case and not easy for us to solve. We understand the pain and will try to look into a solution at some point.

**Comment by Gogo1951** [comment]
You aren't in combat. It doesn't update until you dismount.

Just ran this again yesterday.

**Comment by BreakBB** [comment]
That is a good hint then. I swear I was in combat when I did the quest but shouldn't be hard to verify and see if there is a solution now.
