### ISSUE TITLE
Attack on Camp Narache

### ISSUE THREAD

**Issue by dewmguy** [Questie/Questie#3990]
## Description
Quest is horde only. Quest shows as available for me being a human mage

## Wowhead link
https://tbc.wowhead.com/quest=781/attack-on-camp-narache

## Questie & WoW version
7.0.0
3.4 wotlk pre-patch

**Comment by ILikeLions** [comment]
Can confirm that this is still occurring as of 10/13/22.  Item that starts the quest cannot be interacted with in any way, yet quest still appears on the map.
