### ISSUE TITLE
Vials of Eternity

### ISSUE THREAD

**Issue by dewmguy** [Questie/Questie#3991]
## Description
There is a new version of the quest that replaces the old version. If you've completed the old version, the new version should be shown as unavailable by default.

## Wowhead link
New - https://www.wowhead.com/wotlk/quest=13432/the-vials-of-eternity
Old - https://www.wowhead.com/wotlk/quest=10445/the-vials-of-eternity

## Questie & WoW version
7.0.0
3.4 wotlk pre-patch

**Comment by Cabro** [comment]
Should be fixed
