### ISSUE TITLE
The Cudgel of Kar'desh

### ISSUE THREAD

**Issue by jerbookins** [Questie/Questie#3992]
## Description
The new version of this quest shows as available even if you've completed the old version.

## Wowhead link
New - https://tbc.wowhead.com/quest=13431/the-cudgel-of-kardesh
Old - https://tbc.wowhead.com/quest=10901/the-cudgel-of-kardesh

## Questie & WoW version
7.0.0
3.4 wotlk pre-patch

**Comment by BreakBB** [comment]
Fixed in e91797ae2985942446ae0e5126dfe36307c4e2e0 Thanks for the report @jerbookins
