### ISSUE TITLE
Cant get questie to work on Wotlk prepatch

### ISSUE THREAD

**Issue by Crosserbn** [Questie/Questie#3994]
Hello

i have just updated to questie v7.0.0 but i cant get it to work ingame - in character selection it shows up under my addons.
But when i go ingame it doesnt show up under "interface > addons"
Anyone else have this issue? im stuck and i wanna level to 70 fast :(

**Comment by BreakBB** [comment]
Hey @Crosserbn make sure to follow our [Install Guide](https://github.com/Questie/Questie/wiki/Installation-Guide) if you are manually installing addons.

If you are using an addon manager like WowUp, then close WoW and do a reinstall of Questie.

**Comment by Crosserbn** [comment]
Hello

Im using curseforge - ive tryed reinstalling questie 4 times now.. and ive had wow closed every single time.
Again it shows up at my character selection screen, just not ingame

**Comment by BreakBB** [comment]
That is indeed a strange behaviour. Can you make sure Questie is also enabled for your character? In the character selection addon list there is a drop down on the top left where you can select a specific character.

**Comment by Crosserbn** [comment]
I only have 1 character on this server, and it worked before the prepatch - thats why its really weird, but give me 2 mins then ill doublecheck its enabled

**Comment by BreakBB** [comment]
Maybe share a screenshot or two, so we might spot something else.

**Comment by Crosserbn** [comment]
I got it working! Found out that curseforge apparently didnt know how to apply updated addons to the correct folder!

and now i got it working :D thanks alot for quick answers tho!

**Comment by BreakBB** [comment]
@4nc3st0r Addons don't care about the OS you use. Addon manager might indeed be an issue. Make sure the Questie folder is in `_classic_/Interface/Addons` folder for the Wotlk pre patch.
