### ISSUE TITLE
Error (10702 1) it appears every time I start WoW Woltk.

### ISSUE THREAD

**Issue by julianwgit** [Questie/Questie#3996]
## Bug description
Everytime i start WoW Woltk Classic, the same issues above seen appears. The Questie icons can be seen on the small map as well as on the big map. But the Quest log on my UI is just the same without Questie, like the Classic Quest Log ^^

## Screenshots
First img-link: https://ibb.co/1KJH24q
Second img-link: https://ibb.co/BNPTyMv

## Questie & WoW version

Which version of Questie are you using? You can find it by:
- v7.0.0
- there are only some informations, but no more

Please also state if your quest issue is about Classic Era/SoM or TBC.

**Comment by GazZoOL** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/38363185/187709846-330a72dd-1f51-42ac-a9c0-144113d69422.png)
Same problem :/

**Comment by BreakBB** [comment]
Hey @julianwgit and @GazZoOL 

Can you both try the following and report if that helps: `/questie` -> Advanced -> Recompile Database

**Comment by ciolpaintilami** [comment]
> 

This solution work for me, Thx !

**Comment by GazZoOL** [comment]
It's ok now, Thx !!!

**Comment by julianwgit** [comment]
Recompiling the DB works.. but the Error is still alife.

![QuestieBUGNeu](https://user-images.githubusercontent.com/75977578/187869672-bb3cea64-d60e-45aa-a99f-c94406b7725d.PNG)
![QuestieBugNeu2](https://user-images.githubusercontent.com/75977578/187869687-b6fa4079-678b-42f3-8db2-ba22e5156e87.PNG)

**Comment by ciolpaintilami** [comment]
Be carreful, Questie must bu update to 7.0.0 to be compatible with WOTLK version.

**Comment by BreakBB** [comment]
@julianwgit Could you create a seperate issue for your error. That is indeed a quest data bug on our side then.

**Comment by julianwgit** [comment]
> Be carreful, Questie must bu update to 7.0.0 to be compatible with WOTLK version.

i've already updated to v7.0.0.
