### ISSUE TITLE
Odd Behavior

### ISSUE THREAD

**Issue by AugustEverywhere** [Questie/Questie#3997]
When I reposition the Tracker, if I click sections to close them the top of the Tracker continuously moves down the screen.  If I drag that back up before it ends up going off the bottom, it shows quests lightly and abbreviated like it's not wide enough to show the full text.  The text ellipses happen on minimize and maximize and when I don't even touch the Tracker, it seems

![image](https://user-images.githubusercontent.com/91682702/187715422-2e5e390d-2eb0-4f61-b183-c9eb87a5bf6c.png)

**Comment by Cabro** [comment]
I also notice this shrinking. Each time you move the tracker/ right click the lines on bottom right, the width auto shrinks.

**Comment by BreakBB** [comment]
Known issue, which I am about to fix! Thanks for reporting it @AugustEverywhere and @Cabro
