### ISSUE TITLE
10702 1 No error - WOTLK Pre-Patch

### ISSUE THREAD

**Issue by volostyle** [Questie/Questie#3998]
Hello, every time I log into the game, I see this error:

...ddOns\Questie\Modules\Quest\QuestieQuestPrivates.lua:30: attempt to index a nil value 
[string "@Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua"]:946: in function <...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:944>
[string "@Interface\AddOns\Questie\Modules\Quest\QuestieQuestPrivates.lua"]:30: in function `?'
[string "@Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua"]:650: in function <...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:641>
[string "=[C]"]: in function `xpcall'
[string "@Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua"]:944: in function <...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:942>
[string "@Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua"]:987: in function `PopulateObjectiveNotes'
[string "@Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua"]:498: in function `GetAllQuestIds'
[string "@Interface\AddOns\Questie\Modules\QuestieInit.lua"]:241: in function <Interface\AddOns\Questie\Modules\QuestieInit.lua:162>
 
Questie: [ERROR] [QuestieQuest]: v7.0.0 - There was an error populating objectives for A Grunt's Work... 10702 1 No error

This is for version 7.0.0.

**Comment by BreakBB** [comment]
We'll look into it

https://www.wowhead.com/wotlk/quest=10702/a-grunts-work
