### ISSUE TITLE
[[62] Saving the Sporeloks (10096)] - missing kill targets on map

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#4000]
Wrath

Other two quests there show markers.

![image](https://user-images.githubusercontent.com/55365231/187781979-8ba2f1c0-2a0c-4f8b-beaa-caacf7a86c48.png)

**Comment by Gogo1951** [comment]
![image](https://user-images.githubusercontent.com/55365231/187782116-0712eaeb-8603-497e-8398-0b455bb9b511.png)

Kill targets show up on nameplates. Just not the map.

**Comment by BreakBB** [comment]
Fixed in c315620ca4fd40094ee2d5914cfc01ed184a891d
