### ISSUE TITLE
Error after recompiling the DB

### ISSUE THREAD

**Issue by julianwgit** [Questie/Questie#4002]
## Description
I've already updated to v7.0.0 and after recompiling the database in the questie settings, the error below appears. 
I only see the questie icons on the big and on the small map. The quest log still remains unchanged

The Error is 10702

## Screenshots
![QuestieBUGNeu](https://user-images.githubusercontent.com/75977578/187880954-499fd96c-3919-491c-a897-d5592a285446.PNG)
![QuestieBugNeu2](https://user-images.githubusercontent.com/75977578/187880969-cec20aca-2c4b-46eb-804c-335b91395156.PNG)

## Questie & WoW version
Which version of Questie are you using? 
- v7.0.0

**Comment by BreakBB** [comment]
This is actually the same error as in #3998

**Comment by julianwgit** [comment]
> This is actually the same error as in #3998

Yeah, but is there any solution to fix this error while recompiling the DB?

**Comment by BreakBB** [comment]
No, this is an issue in our data we have to fix.
