### ISSUE TITLE
"Game client not supported"

### ISSUE THREAD

**Issue by ASDasfjd123** [Questie/Questie#4004]
Since the new pre-patch questie sends a message in-game saying they do not support retail wow or private servers...not sure why this pops up since this classic retail.

Will not work or even show up on the screen needless to say. I used cursed forge and yes its been updated. Ive deleted all the addons, reinstalled all the addons, and restarted my computer.

Not sure what else there is to do...Can someone help?

**Comment by drejjmit** [comment]
You need latest version of Questie for Wrath pre patch. 
You can find it here:
https://github.com/Questie/Questie/releases/latest

**Comment by ASDasfjd123** [comment]
Ive already updated. Curse Forged shows 7.01 which is what i have

**Comment by drejjmit** [comment]
And what version does it say in your addon list?

**Comment by ASDasfjd123** [comment]
![image](https://user-images.githubusercontent.com/112646651/188197902-f83a2e7f-8ae2-48fe-bc1b-77f6c2347d91.png)


is what i see

**Comment by BreakBB** [comment]
And ingame, what does it say @ASDasfjd123 ?

**Comment by ASDasfjd123** [comment]
It was saying something along the lines of " you cannot use questie for retail or private server use"

Long story short i delete all of questie from all the files and redownloaded it again and its fixed. For some reason it sent questie to all the folders. Retail, classic and classic era.

So this has been resolved
