### ISSUE TITLE
Lua Error for On Spirit's Wings 

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#4006]
Got a lua error in chat. Classic WoW.

 Reunion completed. 
 Experience gained: 4350. 
 You receive item: [Rexxar's Whistle]. 
 Quest accepted: On Spirit's Wings 
 Questie: [ERROR] [QuestieQuest]: [Tooltips] There was an error populating objectives for Eavesdrop on the Bloodmaul ogres' plans 10714 0 No error 
 ...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:666: bad argument #1 to 'next' (table expected, got nil) 
 [string "@Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua"]:946: in function <...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:944>
[string "=[C]"]: in function `next'
[string "@Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua"]:666: in function <...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:641>
[string "=[C]"]: in function `xpcall'
[string "@Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua"]:944: in function <...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:942>
[string "@Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua"]:999: in function `PopulateObjectiveNotes'
[string "@Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua"]:355: in function `val'
[string "@Interface\AddOns\Questie\Modules\TaskQueue.lua"]:8: in function <Interface\AddOns\Questie\Modules\TaskQueue.lua:6>
 
 Questie: [ERROR] [QuestieQuest]: v7.0.1 - There was an error populating objectives for On Spirit's Wings 10714 1 No error

**Comment by Gogo1951** [comment]
And I get a similar error whenever I pick up a new quest as long as I have that quest in my log.

**Comment by BreakBB** [comment]
Fixed in ee6944275d33e534a17604235b735305a47c57ec
