### ISSUE TITLE
Tracker Bugs when you Minimize a Quest with an item

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#4008]
![image](https://user-images.githubusercontent.com/55365231/188040275-8e5b872f-f8a6-458e-99c1-1507c99cce5f.png)

Can't re-open the quest. It's just gone. Minimized forever. Look at "Fire at Will"

Happens when the quest has an item associated with it. OLD bug.

**Comment by BreakBB** [comment]
I know this sounds stupid, but how did you even manage to minimize a quest with a quest item? The collapse/expand button is not rendered for these quests, because at that place is the item. Therefore you can't expand that quest.

**Comment by acusano** [comment]
I encountered this while doing one of the bombing run daily quests on the isle. Accidentally right clicked the quest item button, which caused the quest to collapse in the tracker, and had no way to expand that line item afterward.

**Comment by Gogo1951** [comment]
They items and the minimize buttons overlap. It's bad design, easy to click the wrong one. 

![image](https://user-images.githubusercontent.com/55365231/188332073-639f0941-b469-4578-a7ce-a3fb362891fe.png)

**Comment by Gogo1951** [comment]
You likely wouldn't need a minimize at all if you just built a dynamic list, like was proposed a billion years ago.

Just show the quests that have objectives in the current zone. Ez, cleans the list up for everyone.

It wastes so much space now with extra zones, and forces users to manually toggle shit constantly. It's all bad design.

So much space wasted to shit that isn't a focus - the only thing I need to focus on is stuff that's in my current zone.

![image](https://user-images.githubusercontent.com/55365231/188332377-4df2957a-c495-40e0-ad65-60329442a688.png)
