### ISSUE TITLE
"Report to Nasuun" shows on map, but isn't available.

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#4012]
Wrath.

"Report to Nasuun" shows on map, but isn't available. Horde DK.

![image](https://user-images.githubusercontent.com/55365231/188050964-536468a2-3cba-44b2-854e-10f8d446a6e4.png)

**Comment by pyledriverATX** [comment]
I still have this issue, November 2022.

**Comment by BreakBB** [comment]
Fixed in https://github.com/Questie/Questie/pull/5136/commits/a660d7fe4af4c800b0688164e6e40663b270daf4
