### ISSUE TITLE
Dungeon and meeting stone on the map

### ISSUE THREAD

**Issue by Ikav8** [Questie/Questie#4014]
Hi, 

TBC Questie used to show dungeon info (location and meeting stones with level info). When WOTLK comes I install the new version of Questie and that info useful information didn't show again.. 

It was very usefull..

EDIT: If I use advanced search and type "meeting stone" there is a list of locations that you can show on the map but the icon used is the generic one... not the meeting stone one.. any ways to change the icon?

**Comment by BreakBB** [comment]
Hey @Ikav8 this is a known issue, which came in with the update of our database for Wotlk. It's on our list to show them again in the future, once we have all the correct data.

@Muehe and/or @Logonz will most likely take of it 😁

**Comment by Ikav8** [comment]
Great news :) 

Thank you!

**Comment by BreakBB** [comment]
We'll keep this open until it is really fixed :grin:
