### ISSUE TITLE
LUA Error on Quest Turn In

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#4019]
1x [ADDON_ACTION_BLOCKED] AddOn 'Questie' tried to call the protected function '<unnamed>:ClearAllPoints()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `ClearAllPoints'
[string "@Questie\Modules\Tracker\ActiveQuestsHeader.lua"]:40: in function `Update'
[string "@Questie\Modules\Tracker\QuestieTracker.lua"]:928: in function `Update'
[string "@Questie\Modules\Quest\QuestieQuest.lua"]:356: in function `val'
[string "@Questie\Modules\TaskQueue.lua"]:8: in function <Questie\Modules\TaskQueue.lua:6>

**Comment by BreakBB** [comment]
I encountered this yesterday as well and already fixed it in a0d5c510a322bb658576f9bde8791e36dc32f307

Will release the fix later today, thanks for reporting it!
