### ISSUE TITLE
Maatparm Mushroom Menagerie sometimes shows incorrect name

### ISSUE THREAD

**Issue by alex47** [Questie/Questie#4020]
## Description

Quest name shows incorrect name in the box in the bottom right corner when hovering over mobs or related quest items in the world.
The quest name is: Maatparm Mushroom Menagerie
The dialog box shows: Mac'Aree Mushroom Menagerie

## Wowhead link

https://tbc.wowhead.com/quest=9648/maatparm-mushroom-menagerie

## Screenshots

![Untitled](https://user-images.githubusercontent.com/10761683/188261158-a0df336b-648f-4809-9b6b-494c0f9d5126.png)

## Questie & WoW version

v7.0.1
WotLK classic 3.4.0.45435

**Comment by BreakBB** [comment]
Oh yeah, another quest that got renamed after the outrage a few month ago 😁 Will be an easy fix, thanks for the report @alex47
