### ISSUE TITLE
[wotlk classic]The list window does not appear

### ISSUE THREAD

**Issue by lookau1004** [Questie/Questie#4021]
wotlk classic

![2](https://user-images.githubusercontent.com/59619810/188272810-673276d4-e9d4-44f9-9470-75abf634bbdd.jpg)

When I shift+click

![1](https://user-images.githubusercontent.com/59619810/188272808-d02470c4-32c2-4602-9eb1-e99834018c7e.jpg)

 shift+click again

It worked out well at first, but Not now

It is the same even if I reinstall it or reset the db

**Comment by BreakBB** [comment]
@lookau1004 Make sure you track quests in your quest log (shift + left click on them). And also make sure you install v7.0.1

**Comment by lookau1004** [comment]
> @lookau1004 Make sure you track quests in your quest log (shift + left click on them). And also make sure you install v7.0.1

i did shift + left click , but it's same

<img width="649" alt="11" src="https://user-images.githubusercontent.com/59619810/188275865-9c332523-4eef-4b36-b1c9-4f87b14857c9.png">

with v7.0.1

**Comment by BreakBB** [comment]
If you just left click on "Questemie Tracker" it expands/collapse. But that only works if you have quests tracked. Also try to reset the Tracker position. `/questie` -> Tracker -> Reset Position

**Comment by Arnibou** [comment]
Same bug !
/questie -> Tracker -> uncheck : Show complete quest
For me, the list window appear everytime now

**Comment by lookau1004** [comment]
> Same bug ! /questie -> Tracker -> uncheck : Show complete quest For me, the list window appear everytime now, however the completed quests don't appear.

I pressed the auto-tracking quest twice, and I saw it right

thank you!!!
