### ISSUE TITLE
Tooltips for Pre-Objectives Aren't Showing on Mobs

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#4023]
![image](https://user-images.githubusercontent.com/55365231/188279498-2a842246-af29-42af-9dd1-d97140756693.png)

![image](https://user-images.githubusercontent.com/55365231/188279469-dee8a5d7-4b34-48c3-9ac0-2483289531ca.png)

https://www.wowhead.com/quest=10855/fel-reavers-no-thanks

**Comment by Cabro** [comment]
Should be fixed
