### ISSUE TITLE
Prisoner of the Bladespire (10724)

### ISSUE THREAD

**Issue by Raina1007** [Questie/Questie#4027]
## Description
After pre-patch, got an error message in chat pane, but questie was working. I am currently on Questie 7.0.1 and it was downloaded via wowup through Wago provider. After I did the quest and got the key, I went to the cage, clicked on the flute item to summon the spirit so the cage could be unlocked. Once the cage was unlocked, got another error message in the chat pane. 

## Wowhead link
(https://tbc.wowhead.com/quest=10724/prisoner-of-the-bladespire)

## Screenshots
<img width="456" alt="Day of prepatch" src="https://user-images.githubusercontent.com/72997449/188285524-ad1bd8ee-1581-40c2-aba7-0728d86c4aaf.png">
r TBC.
-->
<img width="446" alt="after completing it" src="https://user-images.githubusercontent.com/72997449/188285530-a72a8e1e-25a7-4029-b6fa-9389d7a4e2da.png">

## Questie & WoW version
<!--
Which version of Questie are you using? You can find it by:
- 1. Hovering over the Questie Minimap Icon: Questie v7.0.1
- 2. looking at your Questie.toc file (open it with any text editor). For WoW Wrath 3.4.0 
It looks something like this: "v5.9.0" or "## Version: 5.9.0".

Please also state if your quest issue is about Classic Era/SoM
Not possible

**Comment by BreakBB** [comment]
Fixed with ee6944275d33e534a17604235b735305a47c57ec
