### ISSUE TITLE
Game client unsupported

### ISSUE THREAD

**Issue by selenn1986** [Questie/Questie#4029]
Downloaded Questie and it will not load. It's a fresh install. Using current WotLK Classic client.
![image](https://user-images.githubusercontent.com/112784897/188290270-29a5f2da-4c9c-4537-996d-ba1fc49a84aa.png)

**Comment by BreakBB** [comment]
You installed the wrong version of Questie. Follow [this installation guide](https://github.com/Questie/Questie/wiki/Installation-Guide) or simply grab [the latest Questie version](https://github.com/Questie/Questie/releases/latest) @selenn1986

**Comment by selenn1986** [comment]
This is the same version I downloaded from Curse. Version 7.0.1. Everyone in my household downloaded it. It worked for everyone but me.

**Comment by BreakBB** [comment]
What does the AddOn section ingame and in the character selection say? And did you try to close the game, delete the Questie folder, then start up the game and check if Questie is still listed in your AddOn section. If it is, then you most likely have more than one WoW installation and are installing Questie to the wrong one.
