### ISSUE TITLE
Event handler picked up this error while i was fighting a mob in Theremore.

### ISSUE THREAD

**Issue by Phoenixrexx** [Questie/Questie#4031]
Date: 2022-09-04 13:34:08
ID: 1
Error occured in: AddOn: Questie
Count: 1
Message: Note: AddOn Questie attempted to call a protected function (<unnamed>:ClearAllPoints()) during combat lockdown.
Debug:
   [string "=[C]"]: ClearAllPoints()
   [string "@Questie\Modules\Tracker\ActiveQuestsHeader.lua"]:40: Update()
   [string "@Questie\Modules\Tracker\QuestieTracker.lua"]:928: Update()
   [string "@Questie\Modules\Quest\QuestieQuest.lua"]:356: val()
   [string "@Questie\Modules\TaskQueue.lua"]:8:
      Questie\Modules\TaskQueue.lua:6
Locals:
None

**Comment by Phoenixrexx** [comment]
I had 10 errors like this at one time that caused my game to crash...

**Comment by BreakBB** [comment]
This was fixed in a0d5c510a322bb658576f9bde8791e36dc32f307 and the fix will most likely be released later today. Thanks for the report @Phoenixrexx 👍🏻
