### ISSUE TITLE
[ERROR] The quest 70865 is missing from Questie's

### ISSUE THREAD

**Issue by sjanssen15** [Questie/Questie#4032]
## Bug description
After the latest Pre-patch WOTLK there are new quests added which is missing.

## Screenshots
![2022-09-04_10-34](https://user-images.githubusercontent.com/58788519/188304879-45771032-2577-4b56-afaf-24900219a792.png)

![2022-09-04_10-38](https://user-images.githubusercontent.com/58788519/188305023-0a0dd874-182e-48f5-9fbd-e15a27d7d663.png)

It seems to be related to the quest you get when buying the latest WOTLK "Northrend Heroic/Epic Upgrade". These quest(s) don't exist on Wowhead.com yet

## Questie & WoW version
Which version of Questie are you using? 
- v7.0.1

Game version:
- 3.4.0 (45435) Sep 1 2022

**Comment by BreakBB** [comment]
Merging this with #4351
