### ISSUE TITLE
The quest 70397 is missing from Questie's database

### ISSUE THREAD

**Issue by infamousjoeg** [Questie/Questie#4034]
## Description
`Questie: [ERROR] The quest 70397 is missing from Questie's database, Please report this on GitHub or Discord!`

## Wowhead link
[Tools for Survival - Quest - WotLK Classic](https://www.wowhead.com/wotlk/quest=70397/tools-for-survival)

## Screenshots
Not relevant

## Questie & WoW version
- Tested on Questie v7.0.0 and v7.0.1
- Classic WotLK

**Comment by BreakBB** [comment]
Merging this with #4351
