### ISSUE TITLE
LUA Errors crash Questie.

### ISSUE THREAD

**Issue by Mrshades812** [Questie/Questie#4036]
## Bug description
LUA errors when I select certain quests in Blade's edge mountains. Questie tracker crashes and the new quests do not show up on maps. I have disabled all other addons and restarted the game. 

## Screenshots
![image](https://user-images.githubusercontent.com/112825489/188330337-6976062d-c819-4320-a04a-58b1b67065e0.png)
![image](https://user-images.githubusercontent.com/112825489/188330361-218f9a72-24f7-4889-b027-1da2c9b4ec4a.png)
![image](https://user-images.githubusercontent.com/112825489/188330418-b02077bf-528b-4bad-8711-77d00b192410.png)

## Questie & WoW version
Questie ver. 7.0.1  WOW ver. 3.4.0
[questie.txt](https://github.com/Questie/Questie/files/9485373/questie.txt)

**Comment by BreakBB** [comment]
Thanks for the report @Mrshades812 the next update will most likely contain a fix for this. I'll counter check that.

**Comment by BreakBB** [comment]
Fixed in ee6944275d33e534a17604235b735305a47c57ec
