### ISSUE TITLE
Next Questie update???? (Questie virtually unusable)

### ISSUE THREAD

**Issue by Phoenixrexx** [Questie/Questie#4039]
It was mentioned that the fix for the disconnection caused by Questie was in the next update... when will that be? Questie is virtually unusable due to disconnected in the worst of places. It has always had Auto accept and turn in off so doing that doesnt fix anything. Please when will the next update be put up so we dont have to deal with this dropout anymore... :( 
Otherwise ill have to look at another addon.

**Comment by BreakBB** [comment]
First things first: The next Questie update will hit when it hits, but most likely that will be today.

But we don't have a fix for the disconnects @Phoenixrexx The next update will contain some fixes for other places and maybe some improvements which _might_ affect the people with disconnect problems.

No member of the Questie team was able to reproduce the disconnect issue, so we are still quite in the dark here. Yes, people are reporting they are having issue when auto accepting/completing quests, but others are also getting disconnects while crafting stuff or simply mid fight out in the world. We'll keep you posted and would like to reference #3987 to keep all information of this issue in one place.
