### ISSUE TITLE
CHAT_MSG_SKILL event register causes disconnects

### ISSUE THREAD

**Issue by seppala1626** [Questie/Questie#4042]
## Bug description
In QuestieEventHandler.lua, CHAT_MSG_SKILL is registered and used in the function at line 185.
Each time this function receives a skillup event, Questie runs some stuff.

After about 4-10 skillups, I am disconnected.

When I comment out these lines, I am not disconnected.

## Questie & WoW version
Questie 7.0.1
WoW 3.4.0

**Comment by BreakBB** [comment]
Closing this in favor of #3987

Thanks for adding these details @seppala1626
