### ISSUE TITLE
11 Errors popped u might want to check

### ISSUE THREAD

**Issue by Phoenixrexx** [Questie/Questie#4043]
ate: 2022-09-05 22:04:13
ID: 1
Error occured in: AddOn: Questie
Count: 1
Message: Note: AddOn Questie attempted to call a protected function (<unnamed>:ClearAllPoints()) during combat lockdown.
Debug:
   [string "=[C]"]: ClearAllPoints()
   [string "@Questie\Modules\Tracker\ActiveQuestsHeader.lua"]:40: Update()
   [string "@Questie\Modules\Tracker\QuestieTracker.lua"]:928: Update()
   [string "@Questie\Modules\Quest\QuestieQuest.lua"]:356: val()
   [string "@Questie\Modules\TaskQueue.lua"]:8:
      Questie\Modules\TaskQueue.lua:6
Locals:
None

Date: 2022-09-05 22:04:13
ID: 2
Error occured in: AddOn: Questie
Count: 1
Message: Note: AddOn Questie attempted to call a protected function (<unnamed>:SetWidth()) during combat lockdown.
Debug:
   [string "=[C]"]: SetWidth()
   [string "@Questie\Modules\Tracker\ActiveQuestsHeader.lua"]:63: Update()
   [string "@Questie\Modules\Tracker\QuestieTracker.lua"]:928: Update()
   [string "@Questie\Modules\Quest\QuestieQuest.lua"]:356: val()
   [string "@Questie\Modules\TaskQueue.lua"]:8:
      Questie\Modules\TaskQueue.lua:6
Locals:
None

Date: 2022-09-05 22:04:13
ID: 3
Error occured in: AddOn: Questie
Count: 1
Message: Note: AddOn Questie attempted to call a protected function (<unnamed>:SetHeight()) during combat lockdown.
Debug:
   [string "=[C]"]: SetHeight()
   [string "@Questie\Modules\Tracker\ActiveQuestsHeader.lua"]:64: Update()
   [string "@Questie\Modules\Tracker\QuestieTracker.lua"]:928: Update()
   [string "@Questie\Modules\Quest\QuestieQuest.lua"]:356: val()
   [string "@Questie\Modules\TaskQueue.lua"]:8:
      Questie\Modules\TaskQueue.lua:6
Locals:
None

Date: 2022-09-05 22:04:13
ID: 4
Error occured in: AddOn: Questie
Count: 1
Message: Note: AddOn Questie attempted to call a protected function (<unnamed>:Show()) during combat lockdown.
Debug:
   [string "=[C]"]: Show()
   [string "@Questie\Modules\Tracker\ActiveQuestsHeader.lua"]:65: Update()
   [string "@Questie\Modules\Tracker\QuestieTracker.lua"]:928: Update()
   [string "@Questie\Modules\Quest\QuestieQuest.lua"]:356: val()
   [string "@Questie\Modules\TaskQueue.lua"]:8:
      Questie\Modules\TaskQueue.lua:6
Locals:
None

Date: 2022-09-05 22:04:13
ID: 5
Error occured in: AddOn: Questie
Count: 1
Message: Note: AddOn Questie attempted to call a protected function (<unnamed>:SetPoint()) during combat lockdown.
Debug:
   [string "=[C]"]: SetPoint()
   [string "@Questie\Modules\Tracker\ActiveQuestsHeader.lua"]:74: Update()
   [string "@Questie\Modules\Tracker\QuestieTracker.lua"]:928: Update()
   [string "@Questie\Modules\Quest\QuestieQuest.lua"]:356: val()
   [string "@Questie\Modules\TaskQueue.lua"]:8:
      Questie\Modules\TaskQueue.lua:6
Locals:
None

Date: 2022-09-05 22:04:13
ID: 6
Error occured in: AddOn: Questie
Count: 1
Message: Note: AddOn Questie attempted to call a protected function (Questie_TrackedQuests:ClearAllPoints()) during combat lockdown.
Debug:
   [string "=[C]"]: ClearAllPoints()
   [string "@Questie\Modules\Tracker\QuestieTracker.lua"]:385: Update()
   [string "@Questie\Modules\Tracker\QuestieTracker.lua"]:929: Update()
   [string "@Questie\Modules\Quest\QuestieQuest.lua"]:356: val()
   [string "@Questie\Modules\TaskQueue.lua"]:8:
      Questie\Modules\TaskQueue.lua:6
Locals:
None

Date: 2022-09-05 22:04:13
ID: 7
Error occured in: AddOn: Questie
Count: 1
Message: Note: AddOn Questie attempted to call a protected function (Questie_TrackedQuests:SetPoint()) during combat lockdown.
Debug:
   [string "=[C]"]: SetPoint()
   [string "@Questie\Modules\Tracker\QuestieTracker.lua"]:369:
      ...ce\AddOns\Questie\Modules\Tracker\QuestieTracker.lua:357
   [string "@Questie\Modules\Tracker\QuestieTracker.lua"]:386: Update()
   [string "@Questie\Modules\Tracker\QuestieTracker.lua"]:929: Update()
   [string "@Questie\Modules\Quest\QuestieQuest.lua"]:356: val()
   [string "@Questie\Modules\TaskQueue.lua"]:8:
      Questie\Modules\TaskQueue.lua:6
Locals:
None

Date: 2022-09-05 22:04:13
ID: 8
Error occured in: AddOn: Questie
Count: 1
Message: Note: AddOn Questie attempted to call a protected function (Questie_BaseFrame:SetWidth()) during combat lockdown.
Debug:
   [string "=[C]"]: SetWidth()
   [string "@Questie\Modules\Tracker\QuestieTracker.lua"]:1253: Update()
   [string "@Questie\Modules\Quest\QuestieQuest.lua"]:356: val()
   [string "@Questie\Modules\TaskQueue.lua"]:8:
      Questie\Modules\TaskQueue.lua:6
Locals:
None

Date: 2022-09-05 22:04:13
ID: 9
Error occured in: AddOn: Questie
Count: 1
Message: Note: AddOn Questie attempted to call a protected function (Questie_BaseFrame:SetHeight()) during combat lockdown.
Debug:
   [string "=[C]"]: SetHeight()
   [string "@Questie\Modules\Tracker\QuestieTracker.lua"]:1269: Update()
   [string "@Questie\Modules\Quest\QuestieQuest.lua"]:356: val()
   [string "@Questie\Modules\TaskQueue.lua"]:8:
      Questie\Modules\TaskQueue.lua:6
Locals:
None

Date: 2022-09-05 22:04:13
ID: 10
Error occured in: AddOn: Questie
Count: 1
Message: Note: AddOn Questie attempted to call a protected function (Questie_TrackedQuests:Show()) during combat lockdown.
Debug:
   [string "=[C]"]: Show()
   [string "@Questie\Modules\Tracker\QuestieTracker.lua"]:1284: Update()
   [string "@Questie\Modules\Quest\QuestieQuest.lua"]:356: val()
   [string "@Questie\Modules\TaskQueue.lua"]:8:
      Questie\Modules\TaskQueue.lua:6
Locals:
None

Date: 2022-09-05 22:04:13
ID: 11
Error occured in: AddOn: Questie
Count: 1
Message: Note: AddOn Questie attempted to call a protected function (Questie_BaseFrame:Show()) during combat lockdown.
Debug:
   [string "=[C]"]: Show()
   [string "@Questie\Modules\Tracker\QuestieTracker.lua"]:1327: Update()
   [string "@Questie\Modules\Quest\QuestieQuest.lua"]:356: val()
   [string "@Questie\Modules\TaskQueue.lua"]:8:
      Questie\Modules\TaskQueue.lua:6
Locals:
None
AddOns:
  Swatter, v2.5.6773 (SwimmingSeadragon)
  Atlas, vv1.51.06
  AtlasBurningCrusade, vv1.51.02
  AtlasClassicWoW, vv1.51.02
  AtlasWrathoftheLichKing, vv1.51.02
  AtlasLootClassic, vv2.4.4-bcc
  AtlasLootClassicData, vv2.4.4-bcc
  AtlasLootClassicDungeonsAndRaids, vv2.4.4-bcc
  Auctionator, v9.2.33
  BagBrother, v
  Bagnon, v9.2.1
  BagnonConfig, v
  BeanCounter, v2.5.6767 (SwimmingSeadragon)
  DBMCore, vd87d644
  DBMSoundEventsPack, v1.6.18
  DBMStatusBarTimers, vd87d644
  DBMVPVEM, v6746e8a
  Details, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsVanguard, v
  Dominos, v9.3.4
  DominosCast, v
  DominosEncounter, v
  DominosProgress, v
  DominosRoll, v
  GatherMate2, v1.46.3-classic
  HealBot, v3.4.0.3
  HealBotData, v
  HealBotOptions, v
  HealBotTips, v
  HidingBar, vv9.2.14
  Informant, v2.5.6770 (SwimmingSeadragon)
  Pawn, v2.6.2
  Questie, v7.0.1
  RareScanner, v3.4.0
  SlideBar, v2.5.6771 (SwimmingSeadragon)
  SpeedyAutoLoot, v2.1.15
  Stubby, v2.5.6772 (SwimmingSeadragon)
  ThreatClassic2, v2.45
  TitanAttributesMulti, v1.1.1
  TitanClassic, v1.5.3.30400
  TitanClassicAmmo, v1.5.3.30400
  TitanClassicBag, v1.5.3.30400
  TitanClassicClock, v1.5.3.30400
  TitanClassicGold, v1.5.3.30400
  TitanClassicLocation, v1.5.3.30400
  TitanClassicLootType, v1.5.3.30400
  TitanClassicPerformance, v1.5.3.30400
  TitanClassicReagentTracker, v2.5.1.38707
  TitanClassicRegen, v1.5.3.30400
  TitanClassicRepair, v1.5.3.30400
  TitanClassicVolume, v1.5.3.30400
  TitanClassicXP, v1.5.3.30400
  ZPerl, v6.3.4
  ZPerlArcaneBar, v
  ZPerlParty, v
  ZPerlPartyPet, v
  ZPerlPlayer, v
  ZPerlPlayerBuffs, v
  ZPerlPlayerPet, v
  ZPerlRaidAdmin, v
  ZPerlRaidFrames, v
  ZPerlRaidHelper, v
  ZPerlRaidMonitor, v
  ZPerlRaidPets, v
  ZPerlTarget, v
  ZPerlTargetTarget, v
  ZygorGuidesViewerClassicTBC, v2.1
  BlizRuntimeLib_enUS v3.4.0.30400 <none>
  (ck=74c)

**Comment by BreakBB** [comment]
Fixed in #4664
