### ISSUE TITLE
Lua Error Spam

### ISSUE THREAD

**Issue by 1Botnet** [Questie/Questie#4050]
7.0.2 

[code]1719x Questie\Database\QuestieDB.lua:417: attempt to compare nil with number
[string "@Questie\Database\QuestieDB.lua"]:417: in function `IsLevelRequirementsFulfilled'
[string ""]:1: in function <[string ""]:1>
[string ""]:1: in function <[string ""]:1>
[string "=(tail call)"]: ?
[string ""]:1: in function `?'
[string ""]:1: in function `Md75a'
[string ""]:1: in function <[string ""]:1>

Locals:
questId = <table> {
 objectCompilerOrder = <table> {
 }
 questDataOverrides = <table> {
 }
 _QueryItemSingle = <function> defined @Questie\Database\compiler.lua:1161
 itemCompilerOrder = <table> {
 }
 questKeys = <table> {
 }
 questFlags = <table> {
 }
 objectDataOverrides = <table> {
 }
 _npcAdapterQueryOrder = <table> {
 }
 NPCPointers = <table> {
 }
 IsActiveEventQuest = <function> defined @Questie\Database\QuestieDB.lua:382
 ObjectPointers = <table> {
 }
 IsComplete = <function> defined @Questie\Database\QuestieDB.lua:602
 factionTemplate = <table> {
 }
 IsParentQuestActive = <function> defined @Questie\Database\QuestieDB.lua:436
 objectKeys = <table> {
 }
 questCompilerTypes = <table> {
 }
 objectKeysReversed = <table> {
 }
 QueryNPC = <function> defined @Questie\Database\QuestieDB.lua:153
 _QueryQuestSingle = <function> defined @Questie\Database\compiler.lua:1161
 QuestPointers = <table> {
 }
 GetQuestsByZoneId = <function> defined @Questie\Database\QuestieDB.lua:995
 itemKeys = <table> {
 }
 GetQuestTagInfo = <function> defined @Questie\Database\QuestieDB.lua:369
 GetNPC = <function> defined @Questie\Database\QuestieDB.lua:944
 _itemAdapterQueryOrder = <table> {
 }
 IsRaidQuest = <function> defined @Questie\Database\QuestieDB.lua:339
 npcDataOverrides = <table> {
 }
 GetQuest = <function> defined @Questie\Database\QuestieDB.lua:642
 questCompilerOrder = <table> {
 }
 npcKeys = <table> {
 }
 itemDataOverrides = <table> {
 }
 raceKeys = <table> {
 }
 questKeysReversed = <table> {
 }
 fakeTbcItemStartId = 40000
 itemCompilerTypes = <table> {
 }
 IsExclusiveQuestInQuestLogOrComplete = <function> defined @Questie\Database\QuestieDB.lua:388
 objectCompilerTypes = <table> {
 }
 sortKeys = <table> {
 }
 QueryItemSingle = <function> defined @Questie\Database\QuestieDB.lua:153
 Initialize = <function> defined @Questie\Database\QuestieDB.lua:168
 QueryObject = <function> defined @Questie\Database\QuestieDB.lua:153
 ItemPointers = <table> {
 }
 QueryObjectSingle = <function> defined @Questie\Database\QuestieDB.lua:153
 _questAdapterQueryOrder = <table> {
 }
 _QueryObjectSingle = <function> defined @Questie\Database\compiler.lua:1161
 QueryQuestSingle = <function> defined @Questie\Database\QuestieDB.lua:153
 _QueryItem = <function> defined @Questie\Database\compiler.lua:1188
 npcCompilerOrder = <table> {
 }
 QueryItem = <function> defined @Questie\Database\QuestieDB.lua:153
 _QueryQuest = <function> defined @Questie\Database\compiler.lua:1188
 _QueryNPC = <function> defined @Questie\Database\compiler.lua:1188
 IsLevelRequirementsFulfilled = <function> defined @Questie\Database\QuestieDB.lua:405
 _QueryNPCSingle = <function> defined @Questie\Database\compiler.lua:1161
 _CreatureLevelCache = <table> {
 }
 GetZoneOrSortForClass = <function> defined @Questie\Database\QuestieDB.lua:361
 IsPreQuestSingleFulfilled = <function> defined @Questie\Database\QuestieDB.lua:477
 private = <table> {
 }
 GetCreatureLevels = <function> defined @Questie\Database\QuestieDB.lua:902
 _QueryObject = <function> defined @Questie\Database\compiler.lua:1188
 IsPreQuestGroupFulfilled = <function> defined @Questie\Database\QuestieDB.lua:448
 IsDoable = <function> defined @Questie\Database\QuestieDB.lua:503
 npcFlags = <table> {
 }
 QueryQuest = <function> defined @Questie\Database\QuestieDB.lua:153
 IsRepeatable = <function> defined @Questie\Database\QuestieDB.lua:317
 classKeys = <table> {
 }
 itemKeysReversed = <table> {
 }
 _objectAdapterQueryOrder = <table> {
 }
 IsDailyQuest = <function> defined @Qu[/code]

**Comment by BreakBB** [comment]
Hey @1Botnet when exactly does this error pop up?
