### ISSUE TITLE
[The Mark of the Nexus-King (10976)] - incorrect objective locations

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#4052]
![image](https://user-images.githubusercontent.com/55365231/188554898-386bc87f-dbfc-4501-82d7-2a4dfcc2eaae.png)

Objective is in Mana-Tombs.

Not Blades Edge Mountain.

![image](https://user-images.githubusercontent.com/55365231/188554996-f74499ee-c61d-4393-b81b-8f8ce15fd085.png)

**Comment by Cabro** [comment]
Ok, the mark 100% drops from elites in Blade's Edge. It actually does not drop AT ALL in Mana Tombs.

**Comment by Logonz** [comment]
Cabro seems to be right, if you check wowhead [https://tbc.wowhead.com/quest=10976/the-mark-of-the-nexus-king](url).
It also reports it being blades edge mountains, as well as the QuestLog title says blades edge which is a good indication if you combine it with wowhead.
