### ISSUE TITLE
Error on loading game. Questie w/ Guidelime

### ISSUE THREAD

**Issue by AlsoPeters** [Questie/Questie#4053]
## Bug description

When loading into game i get this error:

Message: Interface\AddOns\Questie\Database\QuestieDB.lua:370: Usage: GetQuestTagInfo(questID)
Time: Tue Sep  6 14:38:15 2022
Count: 1
Stack: Interface\AddOns\Questie\Database\QuestieDB.lua:370: Usage: GetQuestTagInfo(questID)
[string "=[C]"]: ?
[string "=[C]"]: in function `GetQuestTagInfo'
[string "@Interface\AddOns\Questie\Database\QuestieDB.lua"]:370: in function `GetQuestTagInfo'
[string "@Interface\AddOns\Questie\Database\QuestieDB.lua"]:333: in function `IsDungeonQuest'
[string "@Interface\AddOns\Guidelime\Data\Guidelime_Questie.lua"]:91: in function <...nterface\AddOns\Guidelime\Data\Guidelime_Questie.lua:89>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\Guidelime\Guidelime.lua"]:640: in function `getQuestText'
[string "@Interface\AddOns\Guidelime\Guidelime_Map.lua"]:129: in function <Interface\AddOns\Guidelime\Guidelime_Map.lua:124>
[string "@Interface\AddOns\Guidelime\Guidelime_Map.lua"]:161: in function `addMapIcon'
[string "@Interface\AddOns\Guidelime\Guidelime.lua"]:1233: in function `updateStepsMapIcons'
[string "@Interface\AddOns\Guidelime\Guidelime.lua"]:1314: in function `updateSteps'
[string "@Interface\AddOns\Guidelime\Data\Guidelime_Questie.lua"]:40: in function <...nterface\AddOns\Guidelime\Data\Guidelime_Questie.lua:36>

Locals: 

## Questie & WoW version
Questie version 7.0.2 
WoW version: WoTLK 3.4.0

**Comment by BreakBB** [comment]
This is an issue on GuideLimes side. An issue was already created there and I also took the time to submitted a PR for a fix https://github.com/max-ri/Guidelime/issues/150

**Comment by max-ri** [comment]
Thanks for your help!
