### ISSUE TITLE
Questie breaks the shift-click tracking feature

### ISSUE THREAD

**Issue by Meivyn** [Questie/Questie#4054]
## Bug description

This piece of code breaks base game behavior of using shift-click to track quests, for some quests.

https://github.com/Questie/Questie/blob/33cd23d78cf33ab211d7f4edcec9961fd6d8864e/Modules/QuestLinks/Hooks.lua#L37-L45

This happens when the tracker is disabled, since Questie overwrites `QuestLogTitleButton_OnClick` regardless of its enabled state.

## Questie & WoW version

Using Questie v7.0.2 on WotLK.

**Comment by BreakBB** [comment]
Ouh that is a good catch and should be easy to fix 👍🏻
