### ISSUE TITLE
Dirt-stained Map showing up for alliance

### ISSUE THREAD

**Issue by ironpeak** [Questie/Questie#4057]
## Description
I'm playing as Alliance and I can see a quest marker in Mulgore for a `Dirt-stained Map` that should start `Attack on Camp Narache` but when I went there (achivement hunting) I was unable to click on the map on the cave floor.

## Wowhead link
Wowhead: 
- https://classic.wowhead.com/item=4851/dirt-stained-map
- https://classic.wowhead.com/quest=781/attack-on-camp-narache

## Screenshots
![Questie](https://user-images.githubusercontent.com/9979987/188729252-adc48c58-f98e-482e-8e54-7cfe42d6020e.jpg)

## Questie & WoW version
Questie: 7.0.2
WoW Wotlk: 3.4.0.45435

**Comment by ironpeak** [comment]
The Wowhead link also says it's Horde only

**Comment by drejjmit** [comment]
Adding some info:
Replaced in Wrath by https://www.wowhead.com/wotlk/quest=24857/attack-on-camp-narache
https://github.com/Questie/Questie/pull/4058
