### ISSUE TITLE
tracker blank 

### ISSUE THREAD

**Issue by amey1956** [Questie/Questie#4073]
## Bug description

the quest tracker is enabled and i can see it on the screen but it is blank, no quests even though the header shows 13/25 currently working on. i have deleted the questie folder and all of the questie files in wtf and still have the same problem.

**Comment by Siel** [comment]
Have exactly the same problem

**Comment by BreakBB** [comment]
Hey @amey1956 and @Siel sorry for this late response.

Is this still an issue for you? Did you click on "Questie Tracker"? And are you sure you have any quest tracked in your quest log?
