### ISSUE TITLE
Wall o Spam

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#4079]
Dabrats has left the raid group. 
 Questie: [ERROR] Please report on Github or Discord! Number of the objectives of the quest changed. questId, oldNum, newNum 6822 4 0 
 Questie: [ERROR] Please report on Github or Discord! Number of the objectives of the quest changed. questId, oldNum, newNum 4201 3 0 
 Questie: [ERROR] Please report on Github or Discord! Number of the objectives of the quest changed. questId, oldNum, newNum 11000 1 0 
 Questie: [ERROR] Please report on Github or Discord! Number of the objectives of the quest changed. questId, oldNum, newNum 10445 2 0 
 Questie: [ERROR] Please report on Github or Discord! Number of the objectives of the quest changed. questId, oldNum, newNum 6584 1 0 
 Questie: [ERROR] Please report on Github or Discord! Number of the objectives of the quest changed. questId, oldNum, newNum 6582 1 0 
 Questie: [ERROR] Please report on Github or Discord! Number of the objectives of the quest changed. questId, oldNum, newNum 6583 1 0 
 Questie: [ERROR] Please report on Github or Discord! Number of the objectives of the quest changed. questId, oldNum, newNum 9824 2 0 
 Questie: [ERROR] Please report on Github or Discord! Number of the objectives of the quest changed. questId, oldNum, newNum 10739 1 0 
 Questie: [ERROR] Please report on Github or Discord! Number of the objectives of the quest changed. questId, oldNum, newNum 9825 1 0 
 Questie: [ERROR] Please report on Github or Discord! Number of the objectives of the quest changed. questId, oldNum, newNum 10265 1 0 
 Questie: [ERROR] Please report on Github or Discord! Number of the objectives of the quest changed. questId, oldNum, newNum 10270 1 0 
 Questie: [ERROR] Please report on Github or Discord! Number of the objectives of the quest changed. questId, oldNum, newNum 10411 2 0 
 Questie: [ERROR] Please report on Github or Discord! Number of the objectives of the quest changed. questId, oldNum, newNum 10408 1 0 
 Questie: [ERROR] Please report on Github or Discord! Number of the objectives of the quest changed. questId, oldNum, newNum 10437 1 0 
 Questie: [ERROR] Please report on Github or Discord! Number of the objectives of the quest changed. questId, oldNum, newNum 10751 3 0 
 Questie: [ERROR] Please report on Github or Discord! Number of the objectives of the quest changed. questId, oldNum, newNum 11096 1 0 
 Questie: [ERROR] Please report on Github or Discord! Number of the objectives of the quest changed. questId, oldNum, newNum 11385 1 0 
 Questie: [ERROR] Please report on Github or Discord! Number of the objectives of the quest changed. questId, oldNum, newNum 9718 1 0 
 Twinkielols has joined the raid group. 
 You have been removed from the group.

**Comment by Yttrium-tYcLief** [comment]
Can this be reproduced?

**Comment by Gogo1951** [comment]
It happened when I had those quests... but who knows. I don't see it any more. I got a few people tell me they had a similar "wall of text" issue, but not for a few weeks now.

Just close this, keep an eye out for people who bring it up again. I know you guys are understaffed and these go-nowhere-bugs are just a time sink. Cheers!
