### ISSUE TITLE
Inscription is missing from the profession tracking menu.

### ISSUE THREAD

**Issue by Cabro** [Questie/Questie#4081]
The new profession Inscription is missing from this menu:

![menu](https://imgur.com/rAZUC37.png)

Questie 7.0.2 - still missing in 7.1.0

**Comment by Gogo1951** [comment]
![image](https://user-images.githubusercontent.com/55365231/192619152-994a0711-f828-4d57-99f4-e829f6c8821f.png)

Yup (=
