### ISSUE TITLE
Announcements are Broken in Latest Build

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#4083]
![image](https://user-images.githubusercontent.com/55365231/189458938-1c8878e1-bb7c-4444-9c5b-be0072795738.png)

I have announcements turned on but they are not announcing that I picked up the item.

**Comment by Gogo1951** [comment]
It's bad copy.

"I'm in a group."

"What kind of group? A party, or a raid?"

It uses "group" when it means "party" and it has some "both" option.

Options should be:

None
Group
Party
Raid

Party by Default is fine.

**Comment by BreakBB** [comment]
So there is nothing broken, but the "Group" setting is not clear enough to mean "Party", do I understand you correct @Gogo1951 ?

**Comment by Gogo1951** [comment]
You aren't using default wow language.

"Group" is a party or a raid. It's what you are calling "Both" but you're using it as "Party."

You're making up your own language here, when perfectly suitable language exists.

**Comment by BreakBB** [comment]
I coult that as a "Yes".
