### ISSUE TITLE
Position of blood of heroes in Eastern Plaguelands

### ISSUE THREAD

**Issue by Krauht** [Questie/Questie#4087]
Hi :)

![Blood of Heroes position - After prepatch](https://user-images.githubusercontent.com/113235282/189477222-bc5f1e1f-d7b6-4da9-a7d4-a60d3782ba73.png)
![Blood of Heroes position - Before prepatch](https://user-images.githubusercontent.com/113235282/189477223-9c76af10-4236-430f-a47e-12d5ae3795b6.png)

## Bug description
Since the prepatch has landed, the position of every Blood of Heroes in the Eastern Plaguelands are mistaken. I've been farming them for weeks now and saw it this morning. I think this is due to the map change at the Eastern Plaguelands (Death knight starting zone was added), and the coordinates of the Bloods weren't updated.

Object ID : 176213

The Blood of Heroes in Western Plaguelands are still well positioned, as the map haven't changed.

## Questie & WoW version
Questie v7.1.0

Please also state if your quest issue is about Classic Era/SoM or TBC.
--> Wow classic Lich King - Prepatch

Thank you !

**Comment by BreakBB** [comment]
Good catch @Krauht that is indeed a bug introduces through the DK starting area. Shouldn't be hard to fix 👍🏻

**Comment by BreakBB** [comment]
This just got fixed in a1183c19c7fcb52f6b4fe03bd1634fd4708da942 and will be in the next release
