### ISSUE TITLE
Jail Break removed from game in Wrath Classic; still an available quest in Questie

### ISSUE THREAD

**Issue by Pastasalad1** [Questie/Questie#4090]
## Description

The Jail Break quest is no longer accessible in game as of the Wrath pre-patch, but Questie still shows this as an available quest.

## Wowhead link

https://www.wowhead.com/wotlk/quest=4322/jail-break

## Screenshots

![image](https://user-images.githubusercontent.com/113238479/189478890-f3777b9b-b137-4fd3-b496-653c6ff7438e.png)

## Questie & WoW version

Questie 7.0.2; Wrath Classic

**Comment by BreakBB** [comment]
Hey @Pastasalad1 could you checkout v7.1.0 and see if that fixes this issue?

**Comment by Pastasalad1** [comment]
Hi @BreakBB I have 7.1.1 now and the issue remains.

**Comment by BreakBB** [comment]
Thanks for posting back @Pastasalad1 👍🏻 We'll take another look then 😁

**Comment by Pastasalad1** [comment]
@BreakBB I'm not sure if it's related, or if you need a separate issue raising for each, but there are some other unavailable quests in game still showing as available in Questie e.g.:

https://www.wowhead.com/wotlk/quest=9123/the-dread-citadel-naxxramas

**Comment by Pastasalad1** [comment]
Still exists in 7.1.2

**Comment by Yttrium-tYcLief** [comment]
Naxx attunes are now hidden as of https://github.com/Questie/Questie/commit/505bcdb81c153ec79a881c47f46247a699c4fac1

Which *exact* quests from the Jail Break questline are no longer present?
