### ISSUE TITLE
Quests on map have their quest type bugged

### ISSUE THREAD

**Issue by mokilok3** [Questie/Questie#4091]
## Bug description

Hi, ever since the new v7.1.0 Questie, all quests shown on the map, which are "Dungeon" and "Raid" type now show as general type. 

Example - quest "Tinkee Steamboil" in Winterspring before the update was marked as "Raid", now it's marked as "Available", **as many others are**. 
No longer function the filters in Questie options, tab General, where you can Enable/Disable certain quest types from appearing on the map.

## Screenshots

![image](https://user-images.githubusercontent.com/113244628/189484218-1b1cc46e-9e93-44cb-91dd-4c6fd41394ef.png)

## Questie & WoW version

WotLK questie v7.1.0

**Comment by mokilok3** [comment]
When I reinstalled Questie and restarted the game, the issue fixed itself. Sorry if this is a red alarm.

**Comment by BreakBB** [comment]
Uff, great! Thanks for checking again @mokilok3
