### ISSUE TITLE
Error with tracker in DK start zone with 7.1.1

### ISSUE THREAD

**Issue by laric** [Questie/Questie#4092]
## Bug description

Just getting quests in the DK start zone.

## Screenshots

15x ...ceQuestie\Modules\Tracker\QuestieTracker.lua:1009: attempt to concatenate local 'zoneName' (a nil value)
[string "@Questie\Modules\Tracker\QuestieTracker.lua"]:1009: in function `Update'
[string "@Questie\Modules\Quest\QuestieQuest.lua"]:400: in function `func'
[string "@Questie\Modules\Libs\QuestieCombatQueue.lua"]:25: in function <...eQuestie\Modules\Libs\QuestieCombatQueue.lua:17>
[string "@SharedXML\C_TimerAugment.lua"]:16: in function <SharedXML\C_TimerAugment.lua:14>

Locals:
self = <table> {
 HookBaseTracker = <function> defined @Questie\Modules\Tracker\QuestieTracker.lua:1334
 MoveDurabilityFrame = <function> defined @Questie\Modules\Tracker\QuestieTracker.lua:632
 Enable = <function> defined @Questie\Modules\Tracker\QuestieTracker.lua:670
 Unhook = <function> defined @Questie\Modules\Tracker\QuestieTracker.lua:1320
 Expand = <function> defined @Questie\Modules\Tracker\QuestieTracker.lua:710
 UntrackQuestId = <function> defined @Questie\Modules\Tracker\QuestieTracker.lua:1457
 _GetNumQuestWatches = <function> defined =[C]:-1
 _order = <table> {
 }
 GetBaseFrame = <function> defined @Questie\Modules\Tracker\QuestieTracker.lua:608
 private = <table> {
 }
 CheckDurabilityAlertStatus = <function> defined @Questie\Modules\Tracker\QuestieTracker.lua:646
 _last_aqw = 4
 Untrack = <function> defined @Questie\Modules\Tracker\QuestieTracker.lua:1315
 UpdateQuestProximityTimer = <function> defined @Questie\Modules\Tracker\QuestieTracker.lua:1643
 started = true
 _alreadyHooked = true
 _IsQuestWatched = <function> defined =[C]:-1
 _alreadyHookedSecure = true
 ResetDurabilityFrame = <function> defined @Questie\Modules\Tracker\QuestieTracker.lua:627
 AQW_Insert = <function> defined @Questie\Modules\Tracker\QuestieTracker.lua:1484
 RemoveQuest = <function> defined @Questie\Modules\Tracker\QuestieTracker.lua:1412
 Collapse = <function> defined @Questie\Modules\Tracker\QuestieTracker.lua:704
 Initialize = <function> defined @Questie\Modules\Tracker\QuestieTracker.lua:75
 Update = <function> defined @Questie\Modules\Tracker\QuestieTracker.lua:884
 Toggle = <function> defined @Questie\Modules\Tracker\QuestieTracker.lua:696
 Disable = <function> defined @Questie\Modules\Tracker\QuestieTracker.lua:684
 ResetLocation = <function> defined @Questie\Modules\Tracker\QuestieTracker.lua:612
}
order = <table> {
 1 = 5805
 2 = 12850
}
firstQuestInZone = true
zoneCheck = "Northshire Abbey"
line = <unnamed> {
 0 = <userdata>
 label = <unnamed> {
 }
 expandZone = <unnamed> {
 }
 SetZone = <function> defined @Questie\Modules\Tracker\LinePool.lua:64
 SetQuest = <function> defined @Questie\Modules\Tracker\LinePool.lua:69
 SetVerticalPadding = <function> defined @Questie\Modules\Tracker\LinePool.lua:78
 SetMode = <function> defined @Questie\Modules\Tracker\LinePool.lua:356
 expandQuest = <unnamed> {
 }
 mode = "zone"
 Quest = <table> {
 }
 SetObjective = <function> defined @Questie\Modules\Tracker\LinePool.lua:74
}
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = 5805
 2 = 12850
}
(for control) = 2
_ = 2
questId = 12850
quest = <table> {
 Description = <table> {
 }
 reputationReward = <table> {
 }
 startedBy = <table> {
 }
 trackTimedQuest = false
 IsTrivial = <function> defined @Questie\Database\QuestieDB.lua:662
 requiredLevel = 55
 SpecialObjectives = <table> {
 }
 Objectives = <table> {
 }
 Sort = 372
 ObjectiveData = <table> {
 }
 questFlags = 136
 level = 55
 Finisher = <table> {
 }
 nextQuestInChain = 12670
 requiredRaces = 0
 IsRepeatable = false
 requiredClasses = 32
 questLevel = 55
 sourceItemId = 0
 Starts = <table> {
 }
 specialFlags = 0
 Id = 12850
 preQuestSingle = <table> {
 }
 parentQuest = 0
 name = "Report To Scourge Commander Thalanor"
 IsComplete = <function> defined @Questie\Database\QuestieDB.lua:657
 zoneOrSort = -372
 objectivesText = <table> {
 }
 finishedBy = <table> {
 }
 objectives = <table> {
 }
}
complete = 1
zoneName = nil
remainingSeconds = nil
(*temporary) = <function> defined @Questie\Modules\Tracker\LinePool.lua:47
(*temporary) = <unnamed> {
 _SetText = <function> defined =[C]:-1
 frame = <unnamed> {
 }
 SetText = <

## Questie & WoW version
 WRATH 7.1.1

**Comment by BreakBB** [comment]
This was fixed some time ago.
