### ISSUE TITLE
Lua Error with latest

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#4093]
1x [ADDON_ACTION_BLOCKED] AddOn 'Questie' tried to call the protected function 'Questie_BaseFrame:SetHeight()'.
[string "@!BugGrabber\BugGrabber.lua"]:480: in function <!BugGrabber\BugGrabber.lua:480>
[string "=[C]"]: in function `SetHeight'
[string "@Questie\Modules\Tracker\QuestieTracker.lua"]:1251: in function `Update'
[string "@Questie\Modules\Quest\QuestieQuest.lua"]:374: in function `val'
[string "@Questie\Modules\TaskQueue.lua"]:8: in function <Questie\Modules\TaskQueue.lua:6>

**Comment by omggga** [comment]
Yeah, tracker is dead for now :\

**Comment by BreakBB** [comment]
Hey @omggga would be nice of you to explain what exactly you mean with "tracker is dead for now". It is working for most people even though it is not working perfectly fine atm (which we are working on). Feel free to open a new issue or even better: Hop on our Discord and explain your issue.

**Comment by omggga** [comment]
Hi @BreakBB 
Im sorry for misunderstaning.
Seems tracker ok for now, but i needed to reset its position several time and to enable/disable blizzard tacker to let make it work right.
