### ISSUE TITLE
Lua error

### ISSUE THREAD

**Issue by seakoria** [Questie/Questie#4094]
bugsack Quote:
”1x ...rfaceQuestie\Modules\QuestieEventHandler.lua:69: attempt to call method 'Error' (a nil value)
[string "@Questie\Modules\QuestieEventHandler.lua"]:69: in main chunk

2x Questie\Questie-7.1.1.lua:27: attempt to call method 'RegisterEarlyEvents' (a nil value)

**Comment by seakoria** [comment]
Nop,disabled all addons but Questie and bugsack+buggrabber, those error still pop out.

1x Questie\Questie-7.1.1.lua:27: attempt to call method 'RegisterEarlyEvents' (a nil value)
[string "@Questie\Questie-7.1.1.lua"]:27: in function <Questie\Questie.lua:23>
[string "=[C]"]: ?
[string "@Questie\Libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <...ceQuestie\Libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Questie\Libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:498: in function `InitializeAddon'
[string "@Questie\Libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:623: in function <...ceQuestie\Libs\AceAddon-3.0\AceAddon-3.0.lua:615>

**Comment by MyTechnoHunter** [comment]
make sure you clear the bugsack and are dealing with new shiny errors and not the previous ones..

**Comment by BreakBB** [comment]
Oh I see. You've got some strange broken Questie installation @seakoria 

No clue why, but your `Questie.lua` file is named `Questie-7.1.1.lua`. That is completely wrong :sweat_smile:

Grab a fresh [latest version](https://github.com/Questie/Questie/releases/latest).

**Comment by BreakBB** [comment]
Hey @seakoria I am assuming this is fixed. Feel free to open up a new issue if you still have issues.
