### ISSUE TITLE
Completed Dailies in Quest Log, show on Map as though it's not completed

### ISSUE THREAD

**Issue by Jorvanus** [Questie/Questie#4095]
## Bug description
So i've had some quests in my log for WOTLK, and i've had them for a bit.  Periodically they appear back on they map, and they go again.  They have stayed this time since last update. They aren't all showing up back on they map, but they all have at some time.  Here is a picture of the Isle for example. 
![image](https://user-images.githubusercontent.com/89010934/189515594-f4827782-781c-448c-a613-98e1d5d2c013.png)
 And here is outland.  All of these quests are done. 

![image](https://user-images.githubusercontent.com/89010934/189515611-647f0398-6223-42a0-957f-f8407aa017e1.png)

Questied 7.1.1 - WOTLK 3.4.0.45506
-->

**Comment by Cabro** [comment]
Should be fixed
