### ISSUE TITLE
Questie not showing on minimap

### ISSUE THREAD

**Issue by jw18522** [Questie/Questie#4096]
I've got the latest version v7.1.1 but when i open the game, I can't see any quests when I open the map. I do get the reminder questie: hiding drop=down menus on the world map when i log in. And when i type /questie, nothing comes up. I've tried resintalling through the curseforge app and also on the website itself, nothing seems to be working.

**Comment by slzn** [comment]
Same here, and I found some error shows in World of Warcraft\_classic_\Logs\FrameXML.log 
`
9/12 20:34:50.537  Loading add-on Questie
9/12 20:34:50.537  ** Loading table of contents Interface\AddOns\Questie\Questie-WOTLKC.toc
9/12 20:34:50.537  (null)
`

**Comment by BreakBB** [comment]
@jw18522 @slzn did you try to recompile the database?

`/questie` -> Advanced -> Recompile database

**Comment by slzn** [comment]
> @jw18522 @slzn did you try to recompile the database?
> 
> `/questie` -> Advanced -> Recompile database

/questie can not pop-up setting menu, just like no questie installed.
no mini icon, no setting menu and no any quest hint on screen,
BUT it shows that hide and show questie button on map('M') screen. click on it nothing happened.

**Comment by BreakBB** [comment]
> > @jw18522 @slzn did you try to recompile the database?
> > `/questie` -> Advanced -> Recompile database
> 
> /questie can not pop-up setting menu, just like no questie installed. no mini icon, no setting menu and no any quest hint on screen, BUT it shows that hide and show questie button on map('M') screen. click on it nothing happened.

Try `Questie.db.global.dbIsCompiled = false` and then do a `/reload`

**Comment by slzn** [comment]
> Try `Questie.db.global.dbIsCompiled = false` and then do a `/reload`

/Questie.db.global.dbIsCompiled = false  and /reload,  questie still not working

**Comment by BreakBB** [comment]
> > Try `Questie.db.global.dbIsCompiled = false` and then do a `/reload`
> 
> /Questie.db.global.dbIsCompiled = false and /reload, questie still not working

Do you see any message/icon from Questie or just nothing? Is Questie listed in your ingame Addons list?

**Comment by slzn** [comment]
> Do you see any message/icon from Questie or just nothing? Is Questie listed in your ingame Addons list?

No any message show up after input command line above. 
Questie is in addon list and is checked.
After character selected, chat message shows
`
Questie: Hiding drop-down menus on the World Map. This is currently necessary as a workaround for a bug in the default Blizzard UI related to drop-down menus.
`
but no questie function working~

**Comment by BreakBB** [comment]
Alright two things:

1. I screwed up the command before. It should have been `/run Questie.db.global.dbIsCompiled = false` and then the `/reload`
2. If that still does not work disable all addons except Questie, Reset Questie in the Advanced options and see if that helps.

**Comment by slzn** [comment]
1. Nothing change after '/run Questie.db.global.dbIsCompiled = false' and '/reload'
2. Disable all other addons but Questie, still not working.

**Comment by BreakBB** [comment]
Could you share a screenshot of your General settings @slzn ?

**Comment by slzn** [comment]
> Could you share a screenshot of your General settings @slzn ?

Sure, but where the general setting is?

**Comment by slzn** [comment]
![image](https://user-images.githubusercontent.com/23331716/189676390-3fbe7745-a7cb-4eee-a04f-73c95dcf30eb.png)
![image](https://user-images.githubusercontent.com/23331716/189676657-56fec831-780b-4dbd-a038-20e60c6405d0.png)

**Comment by BreakBB** [comment]
@slzn `/questie`

**Comment by slzn** [comment]
> @slzn `/questie`

/questie can not pop-up settings menu.

**Comment by BreakBB** [comment]
Oh right you wrote that @slzn , sorry.

Close your game and search for all `Questie.lua` and `Questie.lua.bak` files in your WTF folder and delete them. Then start up the game again.

**Comment by slzn** [comment]
> Close your game and search for all `Questie.lua` and `Questie.lua.bak` files in your WTF folder and delete them. Then start up the game again.

I deleted all Questie.lua and Questie.lua.bak, still not working.

**Comment by finn0** [comment]
Facing same issue like you @slzn

**Comment by finn0** [comment]
The content in the `Questie.lua` is `QuestieConfigCharacter = nil`, nothing else.
More details from me,
1. Questie is actually taking almost 100MB.
2. Not working after I deleted all the other interfaces leaving Questie only.
3. Delete all files/folders under WTF, not working.

**Comment by slzn** [comment]
> /dump Questie.db.global.dbCompiledOnVersion
shows
> Dump: value=Questie.db.global.dbCompiledOnVersion
empty result

> /run Questie.db.global.dbCompiledOnVersion = nil + /reload (you should then see Questie compiling the database (7 steps running).
shows
> Questie: Hiding drop-down menus on the World Map. This is currently necessary as a workaround for a bug in the default Blizzard UI related to drop-down menus.

**Comment by slzn** [comment]
> That means the database is not even loaded 🙈 You should delete the Questie folder, startup the game, verify Questie is not in the addon list anymore and then grab a new copy of the [latest version of Questie](https://github.com/Questie/Questie/releases/latest)

Questie is installed via CurseForge app, I have done remove Questie and deleted all *Questie* named file in WTF folder, and then install latest version of Questie(via CurseForge), but no luck.

**Comment by MyTechnoHunter** [comment]
> > That means the database is not even loaded see_no_evil You should delete the Questie folder, startup the game, verify Questie is not in the addon list anymore and then grab a new copy of the [latest version of Questie](https://github.com/Questie/Questie/releases/latest)
> 
> Questie is installed via CurseForge app, I have done remove Questie and deleted all _Questie_ named file in WTF folder, and then install latest version of Questie(via CurseForge), but no luck.
open your bnet desktop app and verify the install location for your game.. make sure curseforge is set for that path (not running classic or retail in curseforge..) 
manually go to your wow folder _classic_\interface\addons folder and verify that there is no questie folder in it, then either add it again via curseforge or by grabbing the install file from the discord and installing it that way you should end up with a Questie folder with contents including the .toc files DIRECTLY in the questie folder.. not a sub folder.

**Comment by finn0** [comment]
> You are installting your addons manually or are you using an addon manager @finn0 ?

CurseForge, installed version is v7.1.1

> What language is your WoW client? 

Traditional Chinese.

> 100MB is more than Questie should take, especially since it doesn't really load for you as it seems.

It seems loaded, it shows that Questie is taking 90+MB when the mouse hovers over the game menu button.

> Could you try the following and report the output: `/dump Questie.db.global.dbCompiledOnVersion`

The output is `=> [1]="v7.0.2"`

> `/run Questie.db.global.dbCompiledOnVersion = nil` + `/reload` (you should then see Questie compiling the database (7 steps running).

Not working for me.

**Comment by finn0** [comment]
Good news everyone! @BreakBB @slzn 
After I changed the client language to English, it worked!
One change I spotted is that the memory taken by Questie is lower down to 30+MB.
However later on I changed the language back to Traditional Chinese, Questie is not working again, and the memory grows back to 90+MB.

**Comment by BreakBB** [comment]
Oh wow, @finn0 that is a great finding! We will look into it what exactly is going on with the Chinese clients, thanks! :Muscle:

**Comment by finn0** [comment]
Hi @BreakBB, I think the issue is automatically solved by updating to v7.1.2, it works for me.

**Comment by BreakBB** [comment]
Great, thanks for the feedback @finn0 We found the issue and tested it ourself to be fixed, but it's good to get feedback it's working for you as well :+1:
