### ISSUE TITLE
Tracker not working with latest build 7.1.1

### ISSUE THREAD

**Issue by samwow412** [Questie/Questie#4097]
## Bug description
Quest tracker isnt showing up

## Questie & WoW version
questie 7.1.1
wow 3.4.0.45435

**Comment by morgan35543** [comment]
I'm also experiencing this, despite the usual method of unchecking & rechecking auto track quests. The tracker cannot be moved either.

**Comment by BreakBB** [comment]
Did you guys make sure you are tracking quests in your quest log and also tried to reset the Trackers position?

**Comment by morgan35543** [comment]
Did both of those too. It randomly started working about an hour after I gave up on it. I'd done multiple ui reloads messing about with a weakaura so I'm not sure how/why it fixed itself.

**Comment by Velocitas1977** [comment]
I seem to have exact the same issue. On version 7.1.1. Also tried to downgrade one version, to 7.1.0 but the same problem. When I reset Questie (options - advanced) it does show the tracker one time, but after relogging it's gone again.

**Comment by Velocitas1977** [comment]
New finding: When I 'reset tracker position' (optione - tracker) the tracker is visible again, in the lower middle part of the screen (normally it's on the right, just below the minimap). So there seems to be something wrong with the position?

**Comment by Velocitas1977** [comment]
And my final entry: This action seems to have fixed it. After 'reset tracker position' I relog, and I notice in the chatbox Questy is building everything up again (7 steps). After that, the tracker is visible again, and as well after relogging.

**Comment by disillusion3** [comment]
I've been having this same issue and finally came here to report it when I found this thread. I haven't had my tracker pop up at all since the update, and I used the "reset tracker position" which put the tracker in the middle of my screen. I then tried moving it and it would not move to any 'normal' position. I put it back to Auto and did a reload and it's back on the right side where it belongs.

**Comment by BreakBB** [comment]
@samwow412 @morgan35543 @Velocitas1977 @disillusion3 if the Tracker is still not showing up for you or ocasionally vanishes, could you run the following command and share the output?

`/dump Questie.db[Questie.db.global.questieTLoc].TrackerLocation`

**Comment by asgvard** [comment]
@BreakBB I've experienced the same issue, Tracker randomly disappears after changing zones, or entering an instance/dungeon, or relogging. After I do "reset position", it appears in the middle, I can move it with Ctrl+drag. Sometimes it keeps position even if I relog, however after changing zones it disappears again.
Output of the command is:
```
Dump: value=Questie.db[Questie.db.global.questieTLoc].TrackerLocation 
[1]={ 
  [1]="BOTTOMRIGHT", 
  [3]="BOTTOMRIGHT", 
  [4]=0, 
  [5]=-0 
}
```
However I can't see its header in the bottom-right corner.

v7.1.1

**Comment by asgvard** [comment]
Btw when I drag it to where I want it (below minimap), it gets "stick to right" I guess:
```
Dump: value=Questie.db[Questie.db.global.questieTLoc].TrackerLocation 
[1]={ 
  [1]="RIGHT", 
  [3]="RIGHT", 
  [4]=0, 
  [5]=-23.999816894531 
}
```

However as soon as the bottom tracked quest in the list is close to the bottom, it gets "stick to bottom" and I can only see the Header at the very bottom of the screen, the quests list gets outside the screen down, tracker location gets the value as in my comment above.

**Comment by finn0** [comment]
`/dump Questie.db[Questie.db.global.questieTLoc].TrackerLocation`
I get `empty result` from this command. BTW, even the Questie options manual doesn't show up for me.

**Comment by BreakBB** [comment]
Hey @finn0 okay that means you didn't move the Tracker at all (obviously if it doesn't show up).

Did you as well try to disable all other addons? Does `/questie` brings up the settings?

**Comment by BreakBB** [comment]
Thanks @asgvard that will be helpful for my next debugging session!

**Comment by BreakBB** [comment]
@asgvard @finn0 @disillusion3 @Velocitas1977 @morgan35543 @samwow412 Is this still an issue for you guys with v7.1.3?

**Comment by asgvard** [comment]
> @asgvard @finn0 @disillusion3 @Velocitas1977 @morgan35543 @samwow412 Is this still an issue for you guys with v7.1.3?

Will check as soon as I'm back from vacation! Thanks for the update 😀

**Comment by asgvard** [comment]
@BreakBB Seems to be fixed with the latest update! Thanks a lot 😄

**Comment by BreakBB** [comment]
Thanks for reporting back @Velocitas1977 @asgvard ! I'll close this issue then.
