### ISSUE TITLE
The tracker moves automatically

### ISSUE THREAD

**Issue by YimenLeong** [Questie/Questie#4098]
Click on the tracker, it will move automatically, and it cannot move to the original position

**Comment by YimenLeong** [comment]
This problem occurred in the last version 7.11

**Comment by YimenLeong** [comment]
I know the reason for automatic movement!
We can't set the font size of the title of the tracker! If we set it, the background box of the tracker will automatically increase, so it seems to move automatically! Because the background frame is enlarged, we can't reset it back to its original position

**Comment by BreakBB** [comment]
Merging this with #4015 and fixed in 719b604e6e127ab394be970908b4eefa1992f158
