### ISSUE TITLE
The tracker tracking the tracking of tasks disappeared

### ISSUE THREAD

**Issue by Landate** [Questie/Questie#4114]
It disappears and may appear if it reset its position, it will appear in the center of the screen and can be moved, but it will disappear again after you re -end the game.

**Comment by scottcreynolds** [comment]
also disappears on reloadui, have to reset tracker position and then manually drag it back to where i want it several times a day across several characters

**Comment by ericlytle** [comment]
+1 to this. this issue is very annoying and happens alot.

**Comment by martinfry111** [comment]
Also having this problem. I tried deleting questie and all data references which worked for a short while but bug came back.

**Comment by BreakBB** [comment]
@Landate @scottcreynolds @ericlytle @martinfry111 Could you grab v7.1.3 and report if you still experience this issue?
