### ISSUE TITLE
Partially Digested Hand quest is Missing (Netherwing Rep)

### ISSUE THREAD

**Issue by Extort713** [Questie/Questie#4117]
## Description
 The NPC which drops this item does not have the quest on their tooltip, nor does the map show the quest.

## Wowhead link

https://tbc.wowhead.com/quest=11041/a-job-unfinished
https://tbc.wowhead.com/npc=23267/arvoar-the-rapacious
https://tbc.wowhead.com/item=32621/partially-digested-hand

## Questie & WoW version
 Questie (7.1.1)/ Wotlk Classic Pre Patch (3.4.0)

**Comment by Cabro** [comment]
Should be fixed
