### ISSUE TITLE
Monogrammed Sash not showing

### ISSUE THREAD

**Issue by BreakBB** [Questie/Questie#4120]
## Screenshots

One of these:
https://www.wowhead.com/wotlk/quest=620/the-monogrammed-sash
https://www.wowhead.com/wotlk/quest=8552/the-monogrammed-sash

## Questie & WoW version

v7.1.1

**Comment by Yttrium-tYcLief** [comment]
Not sure what was going on with this one, but can confirm it works fine now?
![image](https://user-images.githubusercontent.com/1037011/198531891-83166cc2-9320-44d8-86a3-be1500ae91de.png)
