### ISSUE TITLE
Tracker populating from bottom to top and not honoring Tracker SetPoint setting.

### ISSUE THREAD

**Issue by mfassaie** [Questie/Questie#4124]
I have my Questie tracker positioned below my minimap. Since a recent update (not sure which one) it has started to populate quests from the bottom up.

I've tried changing the Tracker SetPoint option from Auto to Top Left or Top Right and it doesn't make any difference. Bottom Left and Bottom Right work correctly.

One behaviour I noticed was that when setting it to either Top Left or Top Right the tracker resets to the middle of the screen where it behaves correctly. It stops working as soon as it is moved into position below the minimap.

I also confirmed that this issue occurs even when all other addons are disabled.

- Questie 7.1.1
- Wrath Classic

**Comment by BreakBB** [comment]
Thanks for the detailled report @mfassaie I am merging this with #4076

We are currently working in this to be fixed (along with other Tracker issues)!
