### ISSUE TITLE
[The Undercity (12787)] - Incorrect NPC location in tracker discription

### ISSUE THREAD

**Issue by A11ectis** [Questie/Questie#4130]
[Screenshot](https://i.imgur.com/D37Ql7U.png)

Quest log states to find Master Apothecary Faranell in the Undercity, but Questie tracker states to he is at "Lordamere Lake in Alterac Mountains.  Map quest marker is correct.

Using Questie 7.1.1

**Comment by drejjmit** [comment]
Ender of that quest is **Master Apothecary Faranell** at **48.82,69.28** in **Undercity**.
That looks like default Blizzard tracker on your screenshot. You should report that to Blizzard.

[**12787**] = {"The Undercity",{{28318,},nil,nil,},{{**2055**,},nil,},65,-1,16,nil,{"**Grand Apothecary Putress wants you to give the Dual-plagued Brain to Master Apothecary Faranell in the Undercity.**",}

[**2055**] = {'Master Apothecary Faranell',2215,2215,50,50,0,{[**1497**]={{**48.82,69.28**}
[**1497**] = "Undercity",
