### ISSUE TITLE
"Champion..." and Kara quests in Shat are Messed up

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#4133]
All the Champion... quests are off in the latest build I have them, and they show as available from Adal. Already did a re-load.

![image](https://user-images.githubusercontent.com/55365231/190531080-cc034b18-74b6-4b81-b2cc-a5135f83b943.png)

Also it shows a quest for kara that isn't available. 

![image](https://user-images.githubusercontent.com/55365231/190531133-56b31e88-1f6a-47d2-ae69-a2f7331b7261.png)

**Comment by Yttrium-tYcLief** [comment]
I am fairly certain Entry Into Karazhan was a race condition, or something wrong with Questie at the time. The data in our Wrath DB is identical to TBC and shows `preQuestSingle` and `nextQuestInChain` correctly.

The other ones will be fixed, they're quests that are no longer available in WotLK (but are still valid if you had them already).

**Comment by Gogo1951** [comment]
> The other ones will be fixed, they're quests that are no longer available in WotLK (but are still valid if you had them already).

@Yttrium-tYcLief the quests are still there, just with different IDs. The old ones can't be picked up, but haven't been removed if people had them before.

Still possible to get "Hand of Adal" title.

**Comment by Yttrium-tYcLief** [comment]
Yes - I only blacklisted the old versions of them, not the new IDs.
