### ISSUE TITLE
since pre patch questie does not work

### ISSUE THREAD

**Issue by yoyeyoyo** [Questie/Questie#4136]
I have the most current version 1.14.3, ever since the pre patch questie has not worked at all. I have deleted and reloaded it, loaded older version of it, had done /questie. but nothing pops up, I cant access anything with it, it is for sure installed and like i said everything was working fine until pre patch, now nothing works and I cant bring up an menus for it, and the little icon on the mini map is gone.

**Comment by BreakBB** [comment]
Hey @yoyeyoyo The most recent Questie version is v7.1.2 :sweat_smile: Maybe you want to try again installing Questie?

**Comment by BreakBB** [comment]
This seems to be fixed. Feel free to open another issue if not.
