### ISSUE TITLE
Create an Alpha or Beta Release Channel for Questie

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#4137]
There are quite a few bugs going into prod. May be worth have things go to beta for a day or two before going out to everyone. I know you guys had talked about this years ago, still a good idea to have a beta channel that your early adopters can use and test on and give feedback before the bugs go out to more users.

**Comment by Muehe** [comment]
Alpha and Beta releases are usually only distributed on Discord, but the [tags are pushed to Github](https://github.com/Questie/Questie/tags).

You can just clone the repo and use `git pull` to update. I suggest cloning it once and creating soft-links to all the installed expansions, so you can update them all with a single pull.

If you want to test a specific version you can do `git checkout tags/v1.2.34` and later `git checkout master` to return to development state.

Or download the zips from the site I linked above.
