### ISSUE TITLE
Quest tracker moves on its own, when i get a quest or turn the quest in

### ISSUE THREAD

**Issue by flash-fox** [Questie/Questie#4145]
## Bug description
This problem happens in the [v7.1.2](https://github.com/Questie/Questie/releases/tag/v7.1.2) and the previouse versions.
Each time, i get a new quest, or turn a completed quest in, the quest tracker moves a few pixels to the left.
Even if it reached the left side, the mouse starts to open quests, even if you click on the right side of the quests.

## Screenshots
![questieMoves](https://user-images.githubusercontent.com/15526476/190857781-77a370b6-b7f9-4e7e-ac1d-b2f61c730792.gif)

## Other UI Addons:
(just in case, its a conflict with other addons)

- Atlas_BurningCrusade-v1.51.02
- Atlas_ClassicWoW-v1.51.02
- Atlas_WrathoftheLichKing-v1.51.02
- AtlasLootClassic-v3.0.2
- Atlas-v1.51.06
- elvui-12.87
- GatherMate2-1.46.3-classic
- gathermate2_data_wowhead_classic_v2022-08-31
- HealBot_22.09.09
- Maekor-Overpower-Alert
- PowerAuras+4.32.4-Classic
- Questie-v7.1.2
- TitanPanelClassic-1.5.3.30400
- TradeSkillMaster_AppHelper-Classic
- TradeSkillMaster-Classic

## Questie & WoW version
Questie Version: [v7.1.2](https://github.com/Questie/Questie/releases/tag/v7.1.2)
Wow TBC

**Comment by holypalaswe** [comment]
Same issue. Easy to replicate by moving the questie tracke, it makes the questie-window a tiny bit bigger every time and if you have it to your right it forcibly moves it to remain on screen.

**Comment by Lawdie** [comment]
Also happens for me, however my quest bar goes up and eventually off screen 
![questie](https://user-images.githubusercontent.com/16335903/190873388-8a687ec8-d896-4342-bdf7-0d48f44ba83d.gif)

**Comment by SteveEbey73742** [comment]
changing font size did not stop the right side creep to the point I have to reload before I can target anything.

**Comment by MitchellTFord** [comment]
I can confirm that I'm getting the exact same issue. Additionally, I'm unable to manually resize the tracker.

For the others facing this issue, it helps to put the tracker on the left side of the screen and set it to grow to the right so the text doesn't move into the center of the screen

**Comment by flash-fox** [comment]
> For the others facing this issue, it helps to put the tracker on the left side of the screen and set it to grow to the right so the text doesn't move into the center of the screen

Have you also tried: /reloadui
This resets the position where it was bevor it starts to move

**Comment by SteveEbey73742** [comment]
As stated above, in my post, i use reload to reset the tracker,

**Comment by BreakBB** [comment]
Hey @SteveEbey73742 @flash-fox @MitchellTFord @Lawdie @holypalaswe Can you grab v7.1.3 and test this issue again?

**Comment by SteveEbey73742** [comment]
will do, once i get home from work

**Comment by MitchellTFord** [comment]
@BreakBB After updating to v7.1.3, both the issue of not being able to manually resize the tracker and the issue of the tracker growing on its own are resolved! You're the best!

**Comment by flash-fox** [comment]
Can confirm.
It's now working as intended. Thank you.

**Comment by BreakBB** [comment]
Nice, thanks for the feedback @MitchellTFord and @flash-fox
