### ISSUE TITLE
[[66] To The Master's Lair (10279)] - Missing from Map & Missing Turn In

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#4148]
Title. Quest doesn't show as available, and doesn't have a turn-in on the map when you pick it up.

**Comment by Logonz** [comment]
Are you sure something else isn't wrong?

```
[10279] = {"To The Master's Lair",{{20142,},nil,nil,},{{20130,},nil,},66,66,0,nil,{"Speak to Andormu at the Caverns of Time.",},nil,{nil,nil,nil,nil,},nil,nil,nil,nil,nil,nil,1941,nil,nil,nil,nil,10277,136,nil,nil,{{989,0},},},
```
Starter is 20142 and finisher is 20130 which seems to be correct according to wowhead https://www.wowhead.com/wotlk/quest=10279/to-the-masters-lair

But we'll investigate it

**Comment by Yttrium-tYcLief** [comment]
Looks fine to me. Not sure what was going wrong for you, but it's not a data issue.
![image](https://user-images.githubusercontent.com/1037011/198512485-9149bc38-bbe2-490b-820b-db0084c29bdf.png)
![image](https://user-images.githubusercontent.com/1037011/198513504-4e181416-2480-4fc1-9198-2d1c6c448820.png)
