### ISSUE TITLE
Tracking tasks is replaced by standard tracking Blizzard

### ISSUE THREAD

**Issue by Landate** [Questie/Questie#4150]
When tracking tasks from the list of tasks, it breaks and is replaced by standard tasks tracking. This problem appeared in the latest version of the addon

**Comment by Landate** [comment]
UPD The inclusion of the function in the interface interception settings was decided Blizzard

**Comment by BreakBB** [comment]
Hey @Landate could you share a screenshot of your Tracker settings? It is important you have "Enable Tracker Hooks" active.

**Comment by BreakBB** [comment]
Assuming this is no longer an issue.
