### ISSUE TITLE
Map Still Shows Quest Giver Patrol Lines When "Available Quests" is Disabled.

### ISSUE THREAD

**Issue by MettleRook** [Questie/Questie#4158]
## Bug description
When playing with "Available Quests" disabled on the tracker, lines for the quest giver's patrol still appear on the map and still reveal information when the mouse is hovered above the lines.

## Screenshots
![Untitled](https://user-images.githubusercontent.com/28746449/191148330-0047b317-f9fe-4ebf-a00e-77378bbf690c.png)

## Questie & WoW version
Questie V 7.1.2 for WotLK Classic

**Comment by kautella** [comment]
Also seeing this on Classic Era v8.8.2.
Might be worth looking into this together with https://github.com/Questie/Questie/pull/5150?
Seems related and looks like a simple condition being ignored by the patrol drawing.
