### ISSUE TITLE
Tracker frame too big when no quests are tracked

### ISSUE THREAD

**Issue by BreakBB** [Questie/Questie#4160]
## Screenshots

No Quests tracked:
![grafik](https://user-images.githubusercontent.com/33514570/191595204-3d717cad-e5f3-41ad-ba47-a36f79f92426.png)

One Quest tracked:
![grafik](https://user-images.githubusercontent.com/33514570/191595278-9bd37155-2886-438e-b6dd-acba1f89a4da.png)

## Questie & WoW version

v7.1.3

**Comment by Dyaxler** [comment]
This has been fixed with Questie v8
