### ISSUE TITLE
[The Captain's Chest (8551)] Quest is not visible on the map

### ISSUE THREAD

**Issue by ohryk** [Questie/Questie#4164]
## Description

The quest [8551](https://www.wowhead.com/wotlk/quest=8551/the-captains-chest) is not visible on the map for Alliance players.
When use Questie search you can find both of them in the list - 614 and 8551 but 614 is specified only for Alliance and 8551 for Horde.

614 is blacklisted as duplicate, so I guess this is the reason why I can't see it on the map.

## Wowhead link

https://www.wowhead.com/wotlk/quest=614/the-captains-chest
https://www.wowhead.com/wotlk/quest=8551/the-captains-chest

## Questie & WoW version

v 7.1.3
WoW 3.4.0

**Comment by Gogo1951** [comment]
![image](https://user-images.githubusercontent.com/55365231/192121064-7e52c0d3-c296-47e2-8271-0fc6d579187d.png)

What's going on with this quest? Just stood out because it keeps coming up.

**Comment by ohryk** [comment]
UPD: after completing this quest for Alliance player both commands outputs TRUE
```
/run print(C_QuestLog.IsQuestFlaggedCompleted(614))
/run print(C_QuestLog.IsQuestFlaggedCompleted(8551))
```
