### ISSUE TITLE
[WotLK] Goblin Engineer quest  "Show Your Work" is showing up for Gnome Engineers

### ISSUE THREAD

**Issue by Kolmarwow** [Questie/Questie#4165]
## Description
The quest "Show Your Work" is showing up on the map for Gnome Engineers, which isn't possible to do as it's the quest to become a Goblin Engineer. 

## Wowhead link
https://www.wowhead.com/wotlk/quest=3639/show-your-work

## Questie & WoW version
Questie: 7.1.3
WoW: 3.4.0 (45704)

**Comment by Yttrium-tYcLief** [comment]
If memory serves, Questie is not yet able to track specializations, so it can't filter quest availability based on that. This is likely? coming in the future.

**Comment by BreakBB** [comment]
@Yttrium-tYcLief can you handle this one?
