### ISSUE TITLE
MH Ring Quests not Available until you complete [[70] The Vials of Eternity (13432)]

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#4166]
![image](https://user-images.githubusercontent.com/55365231/192113629-b309b765-0db2-470d-a0ce-21fd58e9065f.png)

MH Ring Quests not Available until you complete [[70] The Vials of Eternity (13432)]

**Comment by Gogo1951** [comment]
![image](https://user-images.githubusercontent.com/55365231/192113649-ac5a4b22-ce2f-49e5-9ac9-e87c6eb8b9b3.png)

 Show's on the map but unavailable until you do Vashj and KT.

**Comment by Cabro** [comment]
There are 2 versions of quest that opens up these chains for rings: "Vials of Eternity" id 10445 and 13432

**Comment by Cabro** [comment]
Should be fixed
