### ISSUE TITLE
Questie Map tracking bugged

### ISSUE THREAD

**Issue by DareRickRick** [Questie/Questie#4167]
I keep having this issue where trails of quests happen. 
![QUESTIE](https://user-images.githubusercontent.com/114313197/192116678-7df4ace3-5fb7-48d6-b519-e03c477a25ce.jpg)
![questie1](https://user-images.githubusercontent.com/114313197/192116688-44620541-f652-46fc-9235-59da25b353e0.jpg)

**Comment by Gogo1951** [comment]
Hey @DareRickRick ,

Those are pats for quest givers, or mobs that drop the item. It's not really a bug, but arguably it shouldn't appear when a bunch of mobs all drop the item. It does look messy. Anyway they're are paths. Very useful to have a path when looking for a mob that walks around... when it's just one dude. But really ugly when he's part of a group. Totally agree.

**Comment by BreakBB** [comment]
Gogo is completely right on this. The lines are intended to show mob pathings.
