### ISSUE TITLE
7.1.3 - Failed to initialize - New Character

### ISSUE THREAD

**Issue by SvenskNavi** [Questie/Questie#4169]
Hello, it looks like version 7.1.3 is having issues with brand new characters. I just created a character, logged in, got this error:
`Error during initialization! <path>\QuestieStream.lua:268: attempt to perform arithmetic on local 'a' (a nil value)`
Re-installed 7.1.3, same error. Downgraded to 7.1.2 worked fine, and now 7.1.3 is fine now that everything is initialized.

**Comment by BreakBB** [comment]
Assuming this was fixed.
