### ISSUE TITLE
WoTLK Missing Quest

### ISSUE THREAD

**Issue by HaggardxGaming** [Questie/Questie#4171]
## Description
 Missing quest # 70865

## Wowhead link
 https://www.wowhead.com/wotlk/quest=70865/to-shattrath-city

## Screenshots
 
![image](https://user-images.githubusercontent.com/108308912/192191962-9e79d5e3-a768-4041-b273-64176c5e176f.png)

## Questie & WoW version
 WoTLK Classic

**Comment by Yttrium-tYcLief** [comment]
Known issue, the 70 boost quests are not yet implemented.

**Comment by syswis** [comment]
there are a lot of quest objective missing, the same one as Carbonite. Wondering why lol

**Comment by Yttrium-tYcLief** [comment]
Closing in favor of #4351
