### ISSUE TITLE
Error with New Version

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#4174]
![image](https://user-images.githubusercontent.com/55365231/192351104-89248c30-2afe-46d0-895c-cb3aa8049ef1.png)

**Comment by BreakBB** [comment]
This is a really rare issue, you shouldn't worry too much about. Thanks for the report though, it's on our list to be fixed soon :tm: Merging with #4132

**Comment by Gogo1951** [comment]
![image](https://user-images.githubusercontent.com/55365231/192352222-13eda847-d8c9-4b80-ac5e-dc14d301137e.png)

2 people messaged me about this.

**Comment by Gogo1951** [comment]
@BreakBB I don't think it's a rare issue.
