### ISSUE TITLE
No quests in the Tracker tab

### ISSUE THREAD

**Issue by konradkonek** [Questie/Questie#4178]
My Questie is not showing quets on the tracker.

So far I did:
-reinstal Questie
-reloaded addons
-disabled/enables addon
-clicked the Auto Track Quest option multiple times
-Disable / enable The Tracker

I have tried to do above in version 7.2.1 (newest) as well as 7.2.0

![issue](https://user-images.githubusercontent.com/64707494/192407822-04e69605-796e-4cdc-afd3-cf74ef4b931e.PNG)

**Comment by BreakBB** [comment]
@konradkonek if you have this quest in your quest log, abandon it https://www.wowhead.com/wotlk/quest=12918/gem-perfection

It currently breaks the Tracker

**Comment by konradkonek** [comment]
Nice! It worked!

Thanks for quick help!

**Comment by Possum63** [comment]
No need to abandon the quest.  After reading the above, I tried just untracking the quest and that immediately resolved my Questie Tracker issue.

**Comment by lanigan55** [comment]
Issue seems to happen with quests under the Jewelcrafting category - the JC daily causes the same problem

**Comment by BreakBB** [comment]
@lanigan55 update to v7.2.2 to fix this problem
