### ISSUE TITLE
When login or /reload

### ISSUE THREAD

**Issue by d4kir92** [Questie/Questie#4181]
6x ...ceQuestie\Modules\Tracker\QuestieTracker.lua:816: attempt to concatenate local 'zoneName' (a nil value)
[string "@Questie\Modules\Tracker\QuestieTracker.lua"]:816: in function `Update'
[string "@Questie\Modules\Tracker\QuestieTracker.lua"]:180: in function <...ceQuestie\Modules\Tracker\QuestieTracker.lua:145>

Locals:
self = <table> {
 HookBaseTracker = <function> defined @Questie\Modules\Tracker\QuestieTracker.lua:1124
 MoveDurabilityFrame = <function> defined @Questie\Modules\Tracker\QuestieTracker.lua:455
 Enable = <function> defined @Questie\Modules\Tracker\QuestieTracker.lua:481
 Unhook = <function> defined @Questie\Modules\Tracker\QuestieTracker.lua:1110
 Update = <function> defined @Questie\Modules\Tracker\QuestieTracker.lua:695
 UntrackQuestId = <function> defined @Questie\Modules\Tracker\QuestieTracker.lua:1249
 _GetNumQuestWatches = <function> defined =[C]:-1
 private = <table> {
 }
 CheckDurabilityAlertStatus = <function> defined @Questie\Modules\Tracker\QuestieTracker.lua:469
 Untrack = <function> defined @Questie\Modules\Tracker\QuestieTracker.lua:1105
 UpdateQuestProximityTimer = <function> defined @Questie\Modules\Tracker\QuestieTracker.lua:1435
 started = true
 _alreadyHooked = true
 _IsQuestWatched = <function> defined =[C]:-1
 _alreadyHookedSecure = true
 ResetDurabilityFrame = <function> defined @Questie\Modules\Tracker\QuestieTracker.lua:450
 AQW_Insert = <function> defined @Questie\Modules\Tracker\QuestieTracker.lua:1276
 RemoveQuest = <function> defined @Questie\Modules\Tracker\QuestieTracker.lua:1204
 Collapse = <function> defined @Questie\Modules\Tracker\QuestieTracker.lua:515
 Initialize = <function> defined @Questie\Modules\Tracker\QuestieTracker.lua:79
 Expand = <function> defined @Questie\Modules\Tracker\QuestieTracker.lua:521
 Toggle = <function> defined @Questie\Modules\Tracker\QuestieTracker.lua:507
 Disable = <function> defined @Questie\Modules\Tracker\QuestieTracker.lua:495
 ResetLocation = <function> defined @Questie\Modules\Tracker\QuestieTracker.lua:435
}
order = <table> {
 1 = 11888
 2 = 11611
 3 = 12486
 4 = 11606
 5 = 11598
 6 = 11574
 7 = 12616
 8 = 13002
}
firstQuestInZone = true
zoneCheck = "Karazhan"
line = <unnamed> {
 0 = <userdata>
 ZoneId = "Unknown Zone"
 label = <unnamed> {
 }
 expandZone = <unnamed> {
 }
 SetZone = <function> defined @Questie\Modules\Tracker\LinePool.lua:70
 SetVerticalPadding = <function> defined @Questie\Modules\Tracker\LinePool.lua:84
 SetMode = <function> defined @Questie\Modules\Tracker\LinePool.lua:530
 expandQuest = <unnamed> {
 }
 mode = "zone"
 SetQuest = <function> defined @Questie\Modules\Tracker\LinePool.lua:75
 SetObjective = <function> defined @Questie\Modules\Tracker\LinePool.lua:80
}
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = 11888
 2 = 11611
 3 = 12486
 4 = 11606
 5 = 11598
 6 = 11574
 7 = 12616
 8 = 13002
}
(for control) = 8
_ = 8
questId = 13002
quest = <table> {
 startedBy = <table> {
 }
 Sort = 373
 questFlags = 136
 level = 70
 requiredSkill = <table> {
 }
 nextQuestInChain = 0
 IsRepeatable = false
 requiredClasses = 0
 questLevel = -1
 Id = 13002
 specialFlags = 0
 parentQuest = 0
 name = "Edelsteine perfektionieren"
 IsComplete = <function> defined @Questie\Database\QuestieDB.lua:649
 requiredLevel = 70
 objectives = <table> {
 }
 Description = <table> {
 }
 reputationReward = <table> {
 }
 Color = <table> {
 }
 requiredRaces = 690
 trackTimedQuest = false
 sourceItemId = 0
 IsTrivial = <function> defined @Questie\Database\QuestieDB.lua:654
 LocalizedName = "Edelsteine perfektionieren"
 SpecialObjectives = <table> {
 }
 objectivesText = <table> {
 }
 finishedBy = <table> {
 }
 ObjectiveData = <table> {
 }
 Finisher = <table> {
 }
 zoneOrSort = -373
 exclusiveTo = <table> {
 }
 Starts = <table> {
 }
 Objectives = <table> {
 }
}
complete = 0
zoneName = nil
remainingSeconds = nil
(*temporary) = <function> defined @Questie\Modules\Tracker\LinePool.lua:53
(*temporary) = <unnamed> {
 _

**Comment by 16abradley** [comment]
Same error here

**Comment by d4kir92** [comment]
i think everyone has that error

**Comment by drejjmit** [comment]
Untrack/abandon the Jewelcrafting quest "Gem Perfection" for now. We're working on a fix

**Comment by d4kir92** [comment]
ahh thanks for the info, thx
