### ISSUE TITLE
Lua Errors

### ISSUE THREAD

**Issue by smithdws1** [Questie/Questie#4182]
## Bug description

I was just accepting quests in howling fjord.
Message: ...ce\AddOns\Questie\Modules\Tracker\QuestieTracker.lua:816: attempt to concatenate local 'zoneName' (a nil value)
Time: Mon Sep 26 22:52:40 2022
Count: 1
Stack: ...ce\AddOns\Questie\Modules\Tracker\QuestieTracker.lua:816: attempt to concatenate local 'zoneName' (a nil value)

Locals: 

## Screenshots

![Uploading image.png…]()

## Questie & WoW version
Wrath of the Lich King Classic.

**Comment by drejjmit** [comment]
Untrack/abandon the Jewelcrafting quest "Gem Perfection" for now. We're working on a fix

**Comment by BreakBB** [comment]
This got fixed in 38a0622796d945bd372905bafab1cf1ef49e7f28 Feel free to open up a new issue @smithdws1 if the issue persists for you
