### ISSUE TITLE
questie not showing quests on map

### ISSUE THREAD

**Issue by albanianmage** [Questie/Questie#4187]
questie not showing quests on map for me. tried reloading reinstalling. turning off all addons. nil change

**Comment by Yttrium-tYcLief** [comment]
What quests specifically are having this issue? By "not showing quests on map" do you mean the objective icons (when quest is active) are not showing, or the quest pickup icons (exclamation points) are not showing for eligible-but-not-yet-active quests?

**Comment by Glaphen** [comment]
Let Them Not Rise! 
https://wowhead.com/wotlk/quest=12211

This one is not showing up
