### ISSUE TITLE
Questie not working on only one character others not affected

### ISSUE THREAD

**Issue by Persefonee** [Questie/Questie#4189]
Questie is not showing any quests for one of my characters, it works properly on all other characters, they are all running the same addons. I have disabled all other addons on the affected char and reinstalled questie to no avail
![Capture](https://user-images.githubusercontent.com/28729277/192523780-00aca4d4-bc17-4790-aa52-94179fbc6fea.PNG)

**Comment by drejjmit** [comment]
You are not tracking any quests.
There's an option in settings to auto track new quest.
You can also manually track by holding shift and clicking the quests you want to track.

**Comment by Persefonee** [comment]
I have auto track new quests selected

**Comment by drejjmit** [comment]
Try enabling and disabling that option. This will only track new quests you pick up. If you want to track your old quests you need to manually track them again

**Comment by Persefonee** [comment]
I've disabled and enabled it again still nothing showing, how do you manually track a quest in questie?

**Comment by drejjmit** [comment]
Also, update your Questie to v7.2.2 (released 2 hours ago), since you have a Jewelcrafting quest that was causing issues on previous version. 
Manually track quests by holding shift and clicking them in your quest log

**Comment by Persefonee** [comment]
I'll update it I'm running 7.2.1

**Comment by Persefonee** [comment]
Thank you so much all fixed :)

**Comment by drejjmit** [comment]
No worries. Feel free to report if you notice any other issues/quest issues
