### ISSUE TITLE
Quest advancement lua error

### ISSUE THREAD

**Issue by Elvara26** [Questie/Questie#4195]
Hello,
I'm running Questie 7.2.2 and I've had a problem with one quest each time I would advance the quest goal by 1, I would get an lua error in chat. This is the quest in question.
[https://www.wowhead.com/wotlk/quest=11246/gruesome-but-necessary](url)

I was sure I made a screenshot of the error in chat but I must have messed up so I can't show the exact error.

Hoping it's enough for you to fix/check.
Thanks

**Comment by Yttrium-tYcLief** [comment]
Definitely an issue but already fixed in #4186 with [c1de598](https://github.com/Questie/Questie/pull/4186/commits/c1de59866ca9576278752bf80e06c3d68d9c2fe4), should be included in a new version soon
