### ISSUE TITLE
Missing objective locations for "You Can Run, But You Can't Hide"

### ISSUE THREAD

**Issue by BreakBB** [Questie/Questie#4197]
## Description

"Gooey Ghoul Drool" is not showing

## Wowhead link

https://www.wowhead.com/wotlk/quest=12629/you-can-run-but-you-cant-hide

**Comment by Yttrium-tYcLief** [comment]
Fixed in https://github.com/Questie/Questie/commit/25785f591061763ff44345962cb0bc2969fbbd14
