### ISSUE TITLE
Quest Log Cache "not ok" after latest update

### ISSUE THREAD

**Issue by wlfbck** [Questie/Questie#4198]
## Bug description
See the error message in the screenshot. 

## Screenshots
![grafik](https://user-images.githubusercontent.com/1621804/192703646-7b70004c-e8cb-42b0-bb09-1194ed7d87c3.png)

## Questie & WoW version
It looks something like this: "v5.9.0" or "## Version: 5.9.0".
The Questie.toc does not state any game version. But i literally updated it 1min ago, and the Curseforge client identifies it as 7.2.3. This is on WotLK.

**Comment by BreakBB** [comment]
Hey @wlfbck thanks for reporting this. It's on our list to be fixed, don't worry about it.

Merging this with #4086
