### ISSUE TITLE
WoTLK Dungeon Map Overlay

### ISSUE THREAD

**Issue by ZoZo20** [Questie/Questie#4201]
Hello,

In dungeons when bringing the full map up you cannot see locations for dungeon quests.
Neither on mini map.

Thank you !

**Comment by BreakBB** [comment]
This issue slipped through @ZoZo20 - Do you mean in Wotlk dungeons?

**Comment by BreakBB** [comment]
This is actually many issues in one, since our database is simply lacking the exact spawn data for inside the dungeons. Also we won't be able to show the objectives on the minimap iirc, since the API is limited on that end.

**Comment by BreakBB** [comment]
I think @Cabro fixed all of the Wotlk dungeon quests?

**Comment by Cabro** [comment]
As far as i know, only things that should be added are P4 quests and world event quests

**Comment by BreakBB** [comment]
Closing this for now then 👍🏻
