### ISSUE TITLE
Error on tracking achievements if Questie Tracker is hidden

### ISSUE THREAD

**Issue by BalurPoco** [Questie/Questie#4204]
Lua error when picking up quests like "Bomb Them Again!" or "Fires Over Skettis"

Message: ...nterface\AddOns\Questie\Modules\Tracker\LinePool.lua:430: attempt to index field '?' (a nil value)
Time: Wed Sep 28 11:31:54 2022
Count: 1
Stack: ...nterface\AddOns\Questie\Modules\Tracker\LinePool.lua:430: attempt to index field '?' (a nil value)
[string "@Interface\AddOns\Questie\Modules\Tracker\LinePool.lua"]:430: in function `HideUnusedAchievementLines'
[string "@Interface\AddOns\Questie\Modules\Tracker\AchievementTracker.lua"]:62: in function `LoadAchievements'
[string "@Interface\AddOns\Questie\Modules\Tracker\AchievementTracker.lua"]:90: in function <...ddOns\Questie\Modules\Tracker\AchievementTracker.lua:87>
[string "=[C]"]: ?
[string "@Interface\AddOns\Questie\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29: in function <...tie\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Interface\AddOns\Questie\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface\AddOns\Questie\Libs\AceEvent-3.0\AceEvent-3.0.lua"]:120: in function <...ce\AddOns\Questie\Libs\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: <none>

**Comment by BalurPoco** [comment]
I think it has something to do with these quest have achievements. Questie Tracker is disabled at me btw.

**Comment by BalurPoco** [comment]
If the Questie Tracker is hidden I get this error message when I track or untrack an achievement, I'm on v7.2.4.

`Message: ...ddOns\Questie\Modules\Tracker\AchievementTracker.lua:63: attempt to index upvalue 'baseFrame' (a nil value)
Time: Fri Sep 30 05:15:12 2022
Count: 1
Stack: ...ddOns\Questie\Modules\Tracker\AchievementTracker.lua:63: attempt to index upvalue 'baseFrame' (a nil value)
[string "@Interface\AddOns\Questie\Modules\Tracker\AchievementTracker.lua"]:63: in function `LoadAchievements'
[string "@Interface\AddOns\Questie\Modules\Tracker\AchievementTracker.lua"]:90: in function `Update'
[string "@Interface\AddOns\Questie\Modules\Tracker\AchievementTracker.lua"]:200: in function <...ddOns\Questie\Modules\Tracker\AchievementTracker.lua:197>
[string "=[C]"]: ?
[string "@Interface\AddOns\Questie\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29: in function <...tie\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Interface\AddOns\Questie\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface\AddOns\Questie\Libs\AceEvent-3.0\AceEvent-3.0.lua"]:120: in function <...ce\AddOns\Questie\Libs\AceEvent-3.0\AceEvent-3.0.lua:119>
[string "=[C]"]: in function `RemoveTrackedAchievement'
[string "@Interface\AddOns\Blizzard_AchievementUI\Blizzard_AchievementUI.lua"]:988: in function <...ns\Blizzard_AchievementUI\Blizzard_AchievementUI.lua:986>
[string "=(tail call)"]: ?
[string "*:OnClick"]:6: in function <[string "*:OnClick"]:1>

Locals: <none>`

**Comment by BreakBB** [comment]
Fixed in #4664
