### ISSUE TITLE
[Culling the Damned (12264)] - Mixed NPC's in tooltip

### ISSUE THREAD

**Issue by henkethebenke** [Questie/Questie#4205]
## Description
When hovering a Smoldering Construct (27362) it shows the tooltip for Smoldering Geist (27363) and vice versa. 

## Wowhead link
https://www.wowhead.com/wotlk/quest=12264/culling-the-damned

## Screenshots
![deb26a43cc166850ae3372faafe50c51](https://user-images.githubusercontent.com/1814513/192758917-0bff3c96-a891-457f-8934-020395e2223d.png)
![f907ae9452248b9e90b88c2fefbc54b0](https://user-images.githubusercontent.com/1814513/192758923-aa444d67-3445-4227-a9b1-d7b310a02036.png)

## Questie & WoW version
Questie v7.2.2
WoW Classic WotLK

**Comment by henkethebenke** [comment]
I would like to help but I can't find the documentation for `killCreditObjective` and `baseCreatureID` . It appears both 33017 and 27362 are the same NPC. Shouldn't 27362 be listed under `creatureObjective` as well?

**Comment by henkethebenke** [comment]
Fixed 8 hours ago in [here](https://github.com/Questie/Questie/pull/4186).

**Comment by BreakBB** [comment]
Thanks @henkethebenke for the report and also for noting this is already fixed 😁 👍🏻
