### ISSUE TITLE
Disabled MiniMap objectives?

### ISSUE THREAD

**Issue by robertzak** [Questie/Questie#4206]
## Question
I'm no longer seeing quest objectives on my mini-map. They are just on the full map. I still see quests, but I'm not sure if that's questie or just part of the WotLK UI now.

I'm not sure if this is a Bug, but it doesn't appear to be widespread. The other people in my guild I've asked aren't having it, so I assume it's either a configuration issue on my end or possibly a conflict from another mod I'm running they are not.

Is there a setting for disabling mini-map objectives? I see it listed (and checked) on the minimap pop-up menu, but I have it checked and still nothing. I checked in the mini-map section of the Mod configuration and I didn't see anything obvious that would lead to it being disabled.

I know this was working for me in the past, but it's been awhile since I did a lot of questing in Classic.

I apologize if this is a duplicate, I tried searching to see if this was an open issue, but searching for `minimap` is bringing back 151 open issues and none of the first few pages seemed relevant.

**Comment by BreakBB** [comment]
Hey @robertzak in the "General" section of the Questie settings there are options for "Enable Map Icons" and "Enable Minimap Icons". Make sure these are active.

You could also check if you have the "rotating minimap" option active in the WoW settings (not Questie settings). If yes, try to deactivate it.

**Comment by robertzak** [comment]
Yup. that was totally it. Sorry I should have looked through all of the settings. Thanks so much!
