### ISSUE TITLE
[BUG] Quest doesnt show

### ISSUE THREAD

**Issue by Morimx** [Questie/Questie#4207]
## Questie & WoW version

Questie doesnt show up the quest in minimap or the map in general, started to happen in dragonblight more specifically in venomspite but happen a lot doesnt show objectives.

I reinstaled it and updated the latest version but nothing.

**Comment by Yttrium-tYcLief** [comment]
Please list every quest with missing objectives. Fixing them is a manual process, and it's very helpful to have a specific list to work from.

**Comment by Jokaleth** [comment]
> Please list every quest with missing objectives. Fixing them is a manual process, and it's very helpful to have a specific list to work from.

I've only progressed through Borean Tundra and Dragonblight and although I didn't notice it much in Borean, it feels like a quarter to a third of the quests in Dragonblight the icons just aren't showing up. The quests that I'm on right now [Messy Business](https://www.wowhead.com/wotlk/quest=12076/messy-business) and [No Place to Run](https://www.wowhead.com/wotlk/quest=12261/no-place-to-run) are not showing up.

**Comment by BreakBB** [comment]
Closing this in favor of #3735 and #4222 - @Morimx feel free to open up a new issue with the information we need to provide useful feedback!
