### ISSUE TITLE
Quests by Zone in Borean Tundra fails to populate the dropdown menu.

### ISSUE THREAD

**Issue by Cabro** [Questie/Questie#4208]
This happens only if you are in Borean Tundra. If you are in a different zone, it will show.

There was a similar bug with #3229 #4059

**Comment by Elvara26** [comment]
having the same problem it was fine in Dragonblight but in Borean Tundra, I'm getting lua error and it shows no quest by zone.
`6x ...dOns\Questie\Modules\Journey\QuestieJourneyUtils.lua:14: bad argument #1 to 'pairs' (table expected, got nil)
[string "=[C]"]: in function `pairs'
[string "@Questie\Modules\Journey\QuestieJourneyUtils.lua"]:14: in function `GetSortedZoneKeys'
[string "@Questie\Modules\Journey\tabs\QuestsByZone\QuestsByZoneTab.lua"]:86: in function <...odules\Journey\tabs\QuestsByZone\QuestsByZoneTab.lua:77>
[string "@Questie\Modules\Journey\tabs\QuestsByZone\QuestsByZoneTab.lua"]:44: in function `DrawTab'
[string "@Questie\Modules\Journey\QuestieJourneyPrivates.lua"]:72: in function `HandleTabChange'
[string "@Questie\Modules\Journey\QuestieJourney.lua"]:89: in function <...ceQuestie\Modules\Journey\QuestieJourney.lua:89>
[string "=[C]"]: ?
[string "@Atlas\Libs\AceGUI-3.0\AceGUI-3.0-41.lua"]:72: in function <Atlas\Libs\AceGUI-3.0\AceGUI-3.0.lua:70>
[string "@Atlas\Libs\AceGUI-3.0\AceGUI-3.0-41.lua"]:306: in function `Fire'
[string "@Bartender4\libs\AceGUI-3.0-41\widgets\AceGUIContainer-TabGroup.lua"]:342: in function `SelectTab'
[string "@Bartender4\libs\AceGUI-3.0-41\widgets\AceGUIContainer-TabGroup.lua"]:200: in function <...libs\AceGUI-3.0\widgets\AceGUIContainer-TabGroup.lua:197>`

**Comment by BreakBB** [comment]
This is no longer an issue.
