### ISSUE TITLE
Lua error QuestieMap.lua:836

### ISSUE THREAD

**Issue by Padparadscha** [Questie/Questie#4213]
Every time I get an Item from the NPC who gives me the quest I get following LUA error

Message: Interface\AddOns\Questie\Modules\Map\QuestieMap.lua:836: bad argument #1 to 'next' (table expected, got nil)
Time: Wed Sep 28 17:48:17 2022
Count: 1
Stack: Interface\AddOns\Questie\Modules\Map\QuestieMap.lua:836: bad argument #1 to 'next' (table expected, got nil)

Locals:

**Comment by Padparadscha** [comment]
Nearly every Quest in Kaltarra

**Comment by BreakBB** [comment]
@Padparadscha could you try to recompile your database? `/questie` -> Advanced -> Recompile Database.

And also make sure you are running the latest version v7.2.3 atm

**Comment by Padparadscha** [comment]
version is 7.2.3. recompiling the Database did not work. Tested with the same quest.
I tried a little bit more. The Fault is in combination with Arkinventory (version 3.09.68)

**Comment by khan8037** [comment]
v7.3 didn't work for me either. I don't think it's related to Arkinventory specifically because I also get the error with Bagnon or different map addons like Leatrix and Mapster

**Comment by red13dotnet** [comment]
I just wanted to chime in to confirm I am seeing this as well, Wrath classic, Version 7.3.  Bagnon and leatrix plus in use.
There are several similar errors to this cropping up and the other similarity beyond map/bag mods seems to be addons that modify/ add to tooltips.

**Comment by matthewmb** [comment]
I have also seen this bug regularly in WOTLK Classic. Here's what I tried:

Tested with quest "Cheese for Glowerfield" in Dalaran, but it occurs randomly on other quests too.

1. Disable all addons, abandon quest, reload UI - still get error

2. Disable all addons, abandon quest, recompile Questie database, reload UI - still get error

3. Disable all addons, abandon quest, reset Questie, reload UI - no error

4. All addons enabled, abandon quest, reset Questie, reload UI - no error

So resetting Questie seems to fix the issue, but I have done this previously and had the issue re-occur.

**Comment by Padparadscha** [comment]
> I have also seen this bug regularly in WOTLK Classic. Here's what I tried:
> 
> Tested with quest "Cheese for Glowerfield" in Dalaran, but it occurs randomly on other quests too.
> 
> 1. Disable all addons, abandon quest, reload UI - still get error
> 2. Disable all addons, abandon quest, recompile Questie database, reload UI - still get error
> 3. Disable all addons, abandon quest, reset Questie, reload UI - no error
> 4. All addons enabled, abandon quest, reset Questie, reload UI - no error
> 
> So resetting Questie seems to fix the issue, but I have done this previously and had the issue re-occur.

Tested it. Did not work for me. Problem is still there

**Comment by matthewmb** [comment]
> Tested it. Did not work for me. Problem is still there

One thing I forgot to note was this was the only quest in my quest log, perhaps that made a difference.

**Comment by matthewmb** [comment]
The main thing I'm finding with this bug is that it's intermittent. I can pick up a quest, it'll trigger the LUA error, then I abandon it and reload UI, and it doesn't trigger the LUA error. Repeat process - sometimes I'll get the error, sometimes I won't.

This makes me think it's some sort of server lag. To try and fix it, I've modified this function in `Questie\Modules\Map\QuestieMap.lua`:

`function QuestieMap:GetNearestSpawn(objective)
    if not objective then
        return nil
    end
    local playerX, playerY, playerI = HBD:GetPlayerWorldPosition()
    local bestDistance = 999999999
    local bestSpawn, bestSpawnZone, bestSpawnId, bestSpawnType, bestSpawnName

	C_Timer.After(2, function() -- ADDED THIS LINE 
		if next(objective.spawnList) then
			for id, spawnData in pairs(objective.spawnList) do
				for zone, spawns in pairs(spawnData.Spawns) do
					for _,spawn in pairs(spawns) do
						local uiMapId = ZoneDB:GetUiMapIdByAreaId(zone)
						local dX, dY, dInstance = HBD:GetWorldCoordinatesFromZone(spawn[1]/100.0, spawn[2]/100.0, uiMapId)
						local dist = HBD:GetWorldDistance(dInstance, playerX, playerY, dX, dY)
						if dist then
							if dInstance ~= playerI then
								dist = 500000 + dist * 100 -- hack
							end
							if dist < bestDistance then
								bestDistance = dist
								bestSpawn = spawn
								bestSpawnZone = zone
								bestSpawnId = id
								bestSpawnType = spawnData.Type
								bestSpawnName = spawnData.Name
							end
						end
					end
				end
			end
		end
	end) -- ADDED THIS LINE
	
    return bestSpawn, bestSpawnZone, bestSpawnName, bestSpawnId, bestSpawnType, bestDistance
end`

I only tested for a few minutes, but it seems to help by delaying the code that is triggering the error. Feel free to replace the same function in your file to test.

**Comment by khan8037** [comment]
I tested out your change and it does seem to resolve the problem. I tried the sons of hodir dailies which provide quest items and they didn't error. They consistently errored prior to the changes.
