### ISSUE TITLE
WotLK Constant Underwater Disconnects

### ISSUE THREAD

**Issue by marius366** [Questie/Questie#4214]
We are almost confident Questie has to do something with underwater disconnects.
Would it be possible to change something in Questie options before going into the water ? or you don't know why it may cause DC's, and I will have to turn it off completely
Thank you

**Comment by BreakBB** [comment]
Hey @marius366 this sounds connected to #3987

The only explanation we have is, that Questies performance is not good enough for **some** users and they are therefore disconnected. We are constantly working to improve the performance, but it's not as easy as it might sound 🙈 

Feel free to keep investigating (`/etrace` might be of use), but Questie doesn't do anything specific when entering/leaving water.

**Comment by marius366** [comment]
BreakBB #3987 this issue is well know because of Auto accept and Turn Quest option in Questie
We play Hardcore mode and ive seen a few people in my guild chat they get DC's only when UNDERWATER.
Please take a look at these two posts which is clearly not just a coincidence:
https://us.forums.blizzard.com/en/wow/t/disconnected-when-underwater-for-using-spells-or-being-hit-by-a-spell/1342547
https://us.forums.blizzard.com/en/wow/t/underwater-frostbolt-disconnection/1277981

Thank you very much

**Comment by BreakBB** [comment]
Hey @marius366 

I am still quite sure this is a concidence. We don't listen to anything related to a character being submerged 🤔

I assume you already tested that this error does not happen without any addon active and also happens when just Questie is active?

**Comment by BreakBB** [comment]
Assuming this is no longer an issue.
