### ISSUE TITLE
Quest "Of Traitors and Treason" appearing on minimap, but unavailable

### ISSUE THREAD

**Issue by Elleden** [Questie/Questie#4215]
## Description
 The quest "[My Daughter](https://www.wowhead.com/wotlk/quest=11175/my-daughter#comments)" started by [Old Man Stonemantle](https://www.wowhead.com/wotlk/npc=23831/old-man-stonemantle) shows up on the map/minimap even if I can't accept it. I'm assuming it's because I already completed the quest that this quest(s) leads to ([See to the Operations](https://www.wowhead.com/wotlk/quest=11176/see-to-the-operations) and [Where is Explorer Jaren?](https://www.wowhead.com/wotlk/quest=11393/where-is-explorer-jaren)).

## Wowhead link
 https://www.wowhead.com/wotlk/quest=11175/my-daughter#comments

## Screenshots
 
![image](https://user-images.githubusercontent.com/86515140/192892544-cf3366b6-4770-45fe-9404-08ce2523c0d9.png)

## Questie & WoW version
 WotLK Classic

**Comment by Elleden** [comment]
The same thing, for the same reason happens with the "[Of Traitors and Treason](https://www.wowhead.com/wotlk/quest=12171/of-traitors-and-treason#comments)" quest.

**Comment by BreakBB** [comment]
My Daugther got fixed in 96de1a756d4991a6e2b0ba5569d97a0012ea55ae

**Comment by BreakBB** [comment]
Hey @Elleden can you run the following commands and report the output?

`/dump C_QuestLog.IsQuestFlaggedCompleted(12297)`
`/dump C_QuestLog.IsQuestFlaggedCompleted(12157)`

**Comment by Elleden** [comment]
"false" for both.

**Comment by BreakBB** [comment]
Fixed in 191c5a2f7d53f0bb5328da5a527bc82bfc6a05db
