### ISSUE TITLE
Tracker Layout Issue

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#4217]
Still an issue with the tracker...

The icon overlaps the text, and there's a bit of red broken character in the tracker now since the latest patch.

![image](https://user-images.githubusercontent.com/55365231/192918464-fd56d73e-74a9-4272-a9ab-5e318371e097.png)

**Comment by Gogo1951** [comment]
Also the quest descriptions truncate too soon... the tracker is twice as wide as where the text truncates.

![image](https://user-images.githubusercontent.com/55365231/192918704-07954d8a-8b77-4ecb-bcc1-67de593887cb.png)

**Comment by Gogo1951** [comment]
![image](https://user-images.githubusercontent.com/55365231/193143009-eebe43d9-b5ce-464f-ab0e-ed3380794ea6.png)

FYI, font scaling on a 4k monitor.

**Comment by Gogo1951** [comment]
Font sizes still suck for 4k. An 18 on 4k is a 9 on 1080p. Fonts can't be scaled right or manually adjusted.

Closing as stale. Will never get worked on by the current team.

**Comment by BreakBB** [comment]
You should be able to see that this issue is already linked to a PR and also **know** about that PR since you commented on it.
