### ISSUE TITLE
Tracker Achievement Tracking LUA error with tracker disabled

### ISSUE THREAD

**Issue by Dosmod** [Questie/Questie#4225]
## Bug description

When loading the game with the tracker DISABLED while tracking an achievement, questie gives lua errors everytime the achievement text is updated (Getting achievement progress, earning the achievement, tracking, stop tracking) and when completing quests.
No error if no achievement is tracked. Also no error if I enter the game with the tracker enabled.
The errors stop if I enable and then disable the tracker until next ui reload.

I can reproduce the lua errors everytime by reloading the UI (or relogging) with an ach already tracked and then by just tracking/untracking an achievement

As a workaround every login I enable then disable the tracker (I prefer the blizzard tracker) which lasts until next reload.

## Screenshots

Message: ...nterface\AddOns\Questie\Modules\Tracker\LinePool.lua:430: attempt to index field '?' (a nil value)
Time: Thu Sep 29 11:24:17 2022
Count: 4
Stack: ...nterface\AddOns\Questie\Modules\Tracker\LinePool.lua:430: attempt to index field '?' (a nil value)
[string "@Interface\AddOns\Questie\Modules\Tracker\LinePool.lua"]:430: in function `HideUnusedAchievementLines'
[string "@Interface\AddOns\Questie\Modules\Tracker\AchievementTracker.lua"]:79: in function `LoadAchievements'
[string "@Interface\AddOns\Questie\Modules\Tracker\AchievementTracker.lua"]:90: in function `Update'
[string "@Interface\AddOns\Questie\Modules\Tracker\AchievementTracker.lua"]:197: in function <...ddOns\Questie\Modules\Tracker\AchievementTracker.lua:194>

## Questie & WoW version
7.2.3
3.4.0 45772

**Comment by Gogo1951** [comment]
Similar issue.

2x [ADDON_ACTION_BLOCKED] AddOn 'Questie' tried to call the protected function '<unnamed>:SetWidth()'.
[string "@!BugGrabber\BugGrabber.lua"]:480: in function <!BugGrabber\BugGrabber.lua:480>
[string "=[C]"]: in function `SetWidth'
[string "@Questie\Modules\Tracker\LinePool.lua"]:55: in function `SetText'
[string "@Questie\Modules\Tracker\QuestieTracker.lua"]:813: in function `Update'
[string "@Questie\Modules\Quest\QuestieQuest.lua"]:374: in function `val'
[string "@Questie\Modules\TaskQueue.lua"]:8: in function <Questie\Modules\TaskQueue.lua:6>

**Comment by BreakBB** [comment]
Merging this with #4204
