### ISSUE TITLE
[Error] [Wrath] Quest 70411 is missing from the database 

### ISSUE THREAD

**Issue by Goldpaw** [Questie/Questie#4226]
## Bug description
Quest 70411 is missing from the database, and the addon told me to report it. This is in Wrath classic. A few more in the same chain are missing too, but I never thought to screenshot or write down until I had /reloaded and forgot what it said. 

I would like to add that these aren't breaking quests to be missing, as they are part of the tiny questline you get after receiving a level 70 boost with the heroic or epic northrend wow upgrades. And the quests are all of the type "equip a weapon" or "select a talent". There really is nothing that needs explaining or directions there. 

But the addon told me to report it, so...! :D

## Questie & WoW version

Questie for Wrath Classic v7.2.3

**Comment by BreakBB** [comment]
Merging this with #4351
