### ISSUE TITLE
Argent Vanguard quests showing as available when they are not

### ISSUE THREAD

**Issue by BreakBB** [Questie/Questie#4229]
## Screenshots

![grafik](https://user-images.githubusercontent.com/33514570/193050413-a75378d1-c507-42d1-ba82-40a7ca914c01.png)

## Questie & WoW version

v7.2.3

**Comment by Gogo1951** [comment]
![image](https://user-images.githubusercontent.com/55365231/194733368-24f28349-2967-4136-93b5-1aaa6eab4b51.png)

**Comment by Yttrium-tYcLief** [comment]
These have all been fixed over the past month through various commits.
