### ISSUE TITLE
Quest pickup locations no longer show up on the map or minimap at all

### ISSUE THREAD

**Issue by Jokaleth** [Questie/Questie#4230]
## Bug description
As the title says, the location to pickup new quests do not show up on the map or minimap at all after the most recent update
Quest objectives and turn-in locations still show up correctly

## Screenshots
![image](https://user-images.githubusercontent.com/87456827/193050379-af0fa590-334a-438b-9f44-f1069bfbed23.png)
![image](https://user-images.githubusercontent.com/87456827/193050466-58cc9e68-cef9-46f0-809a-434bb5f09700.png)

## Questie & WoW version

Questie v7.2.3
WoW 3.4.0.45772

**Comment by Bengejd** [comment]
Did you accidentally click "Hide Questie"?

**Comment by Jokaleth** [comment]
> Did you accidentally click "Hide Questie"?

No, like I said every other map icon is properly showing up. Quest turn-ins, quest objectives, all trackable icons like repairs, innkeeper, etc. are all showing up. The only thing not showing up are quest pickup icons.

**Comment by Jokaleth** [comment]
Never mind I figured it out at some point the "Enable absolute level range" got turned on and it was at a range lower then the quests in Northrend
