### ISSUE TITLE
Tracker collapse from top to bottom

### ISSUE THREAD

**Issue by dameinsinner** [Questie/Questie#4235]
I don't know if this was something that should be working this way or if it was removed but the tracker used to be able to collapse from top to bottom in older version. Now when the anchor point is set to bottom right, one it does not collapse from top to bottom and 2 the quest growth still sometimes to grown down word when it should grow upwards. Also there is now an achievement header that is in the way and cannot be removed in the settings from what I can see. Is there a way to try to fix this. I keep my tracker on the bottom right of my screen above my dps meter and when I want to collapse the tracker it it collapses upwards which is super annoying.

**Comment by BreakBB** [comment]
Hey @dameinsinner yes you are absolutely correct. The Trkacer had this functionality and will get this again as well, it's on our list.

For the release of Wotlk we were forced to rewrite main parts of the Tracker and scratched some functionality temporarily, to get something done for Wotlk release.

**Comment by Gogo1951** [comment]
Just another bug with this... when you have more quests than will fit on the screen, the "anchor point" isn't respected. No matter how many quests I have, the anchor point should never move.
