### ISSUE TITLE
[[71] Mimicking Nature's Call (11281)] - objective in the wrong place

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#4236]
![image](https://user-images.githubusercontent.com/55365231/193104250-f4885327-37ab-4b4e-b5ad-4d61280be80a.png)

The spot on the bridge is wrong.

Should only have one spot for this quest.

**Comment by Yttrium-tYcLief** [comment]
This bug should have already been fixed, are you on the latest version?

**Comment by Yttrium-tYcLief** [comment]
Oh, my bad. I fixed this one locally and forgot to push it. Should be included in the next release!
