### ISSUE TITLE
Falsely showing "A disturbance in the west" as available

### ISSUE THREAD

**Issue by BreakBB** [Questie/Questie#4239]
## Wowhead link

https://www.wowhead.com/wotlk/quest=12439/a-disturbance-in-the-west

## Questie & WoW version

v7.2.4

**Comment by vonyn** [comment]
quest is only available if you have not done rifle the bodies. would be great to see a warning to pick up and complete a disturbance in the west from questie seeing how bliz will never do anything about the fact you can start this quest chain from the middle.

**Comment by BreakBB** [comment]
Closing in favor of #4335
