### ISSUE TITLE
[[71] Brains! Brains! Brains! (11301)] - missing objectives in nameplates

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#4240]
![image](https://user-images.githubusercontent.com/55365231/193144908-11958f1c-d307-400a-af9e-0dd21f1b2778.png)

Other places where there are "prerequisite" items / kills... we generally have shown them on nameplates in the past.

**Comment by Yttrium-tYcLief** [comment]
Perhaps there's something going on with your nameplate addon? At least using default Plater, they're still showing for me (on quests with working objective data, of which Brains Brains Brains is now one):
![image](https://user-images.githubusercontent.com/1037011/193345046-1cce183e-2246-46d6-80ce-236e2078d9a8.png)
![image](https://user-images.githubusercontent.com/1037011/193345077-0d09621d-9a74-4a1c-ad75-d1434a9fcfaa.png)

**Comment by Gogo1951** [comment]
It's the quest data for the quest I cited. Not an issue with the nameplate add-on. 

You can look at these quests as examples for what needs to be fixed here.

https://classic.wowhead.com/quest=882/ishamuhale
https://classic.wowhead.com/quest=1136/frostmaw
