### ISSUE TITLE
Classic Wrath - Guide says to pick up a quest at wrong level.

### ISSUE THREAD

**Issue by nixxo84** [Questie/Questie#4241]
## Description

Following the guide for Dragonblight, it says to pick up the quest "The Call of The Crusade" but you're only about half way through level 73, even after I've done a few dungeons and all elite quests along the way, and the quest requires level 74 to pick up.

## Wowhead link

https://www.wowhead.com/wotlk/quest=12542/the-call-of-the-crusade

## Questie & WoW version

v7.2.4 on Wrath Classic

**Comment by BreakBB** [comment]
Hey @nixxo84 Questie doesn't tell you anything and is not a guide. Our data is correct to show this quest only available on level 74+. So you must be mistaken Questie with some other addon.
