### ISSUE TITLE
Quest 70734 is missing from the database...followed by errors accepting the quests following it. WoLK Classic

### ISSUE THREAD

**Issue by brokenlion** [Questie/Questie#4242]
I received the error Quest 70734 is missing on character that I already had. Currently, I am on the quest chain you receive after boosting a character. It requires to you to equip your weapon, and other items. I will continue to move thru the chain and update here if it carries on after this chain has been completed. Playing WoLK Classic.

## Bug description
Quest 70734 is missing from the database

## Screenshots
This was the error log in the window:
Date: 2022-09-29 16:10:38
ID: -1
Error occured in: Global
Count: 1
Message: ...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua line 997:
   attempt to index local 'quest' (a nil value)
Debug:
   [string "@Questie\Modules\Quest\QuestieQuest.lua"]:997: PopulateObjectiveNotes()
   [string "@Questie\Modules\Quest\QuestieQuest.lua"]:373: val()
   [string "@Questie\Modules\TaskQueue.lua"]:8:
      Questie\Modules\TaskQueue.lua:6
Locals:
self = <table> {
 autoBlacklist = <table> {
 }
 ShouldShowQuestNotes = <function> defined @Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:337
 AcceptQuest = <function> defined @Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:360
 HideQuest = <function> defined @Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:349
 ToggleNotes = <function> defined @Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:95
 PopulateQuestLogInfo = <function> defined @Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:1035
 AbandonedQuest = <function> defined @Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:410
 SmoothReset = <function> defined @Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:235
 PopulateObjectiveNotes = <function> defined @Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:996
 availableQuests = <table> {
 }
 UnhideQuest = <function> defined @Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:354
 GetAllQuestIdsNoObjectives = <function> defined @Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:529
 DrawDailyQuest = <function> defined @Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:1373
 GetAllQuestIds = <function> defined @Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:496
 PopulateObjective = <function> defined @Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:659
 CompleteQuest = <function> defined @Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:386
 AddFinisher = <function> defined @Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:569
 ResetAutoblacklistCategory = <function> defined @Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:86
 UpdateObjectiveNotes = <function> defined @Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:554
 CalculateAndDrawAvailableQuestsIterative = <function> defined @Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:1268
 UpdateQuest = <function> defined @Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:454
 Initialize = <function> defined @Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:77
 GetAllLeaderBoardDetails = <function> defined @Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:1125
 SetObjectivesDirty = <function> defined @Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:486
 ClearAllNotes = <function> defined @Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:194
 private = <table> {
 }
}
quest = nil
(*temporary) = <function> defined @Interface\AddOns\Questie\Questie.lua:104
(*temporary) = <table> {
 SetDefaultModuleLibraries = <function> defined @Interface\AddOns\Questie\Libs\AceAddon-3.0\AceAddon-3.0.lua:367
 _sessionWarnings = <table> {
 }
 modules = <table> {
 }
 CancelTimer = <function> defined @Interface\AddOns\Questie\Libs\AceTimer-3.0\AceTimer-3.0.lua:147
 DEBUG_DEVELOP = "|cff7c83ff[DEVELOP]|r"
 UnregisterComm = <function> defined @Interface\AddOns\SlideBar\Libs\LibDataBroker\CallbackHandler\CallbackHandler-1.0.lua:153
 Warning = <function> defined @Interface\AddOns\Questie\Questie.lua:98
 Printf = <function> defined @Interface\AddOns\Questie\Libs\AceConsole-3.0\AceConsole-3.0.lua:69
 SetDefaultModulePrototype = <function> defined @Interface\AddOns\Questie\Libs\AceAddon-3.0\AceAddon-3.0.lua:409
 defaultModuleState = true
 IsEnabled = <function> defined @Interface\AddOns\Questie\Libs\AceAddon-3.0\AceAddon-3.0.lua:451
 ScheduleTimer = <function> defined @Interface\AddOns\Questie\Libs\AceTimer-3.0\AceTimer-3.0.lua:94
 DisableModule = <function> defined @Interface\AddOns\Questie\Libs\AceAddon-3.0\AceAddon-3.0.lua:350
 RegisterMessage = <function> defined @Interface\AddOns\SlideBar\Libs\LibDataBroker\CallbackHandler\CallbackHandler-1.0.lua:90
 GetArgs = <function> defined @Interface\AddOns\Questie\Libs\AceConsole-3.0\AceConsole-3.0.lua:144
 RegisterBucketEvent = <function> defined @Interface\AddOns\Questie\Libs\AceBucket-3.0\AceBucket-3.0.lua:184
 DEBUG_CRITICAL = "|cff00f2e6[CRITICAL]|r"
 SendCommMessage = <function> defined @Interface\AddOns\Questie\Libs\AceComm-3.0\AceComm-3.0.lua:87
 db = <table> {
 }
 UnregisterAllComm
AddOns:
  Swatter, v3.4.6817 (SwimmingSeadragon)
  AucAdvanced, v3.4.6825 (SwimmingSeadragon)
  AucFilterBasic, v3.4.6803 (SwimmingSeadragon)
  AucScanData, v3.4.6804 (SwimmingSeadragon)
  AucStatHistogram, v3.4.6805 (SwimmingSeadragon)
  AucStatiLevel, v3.4.6809 (SwimmingSeadragon)
  AucStatPurchased, v3.4.6806 (SwimmingSeadragon)
  AucStatSimple, v3.4.6807 (SwimmingSeadragon)
  AucStatStdDev, v3.4.6808 (SwimmingSeadragon)
  AucUtilFixAH, v3.4.6810 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v9.2.2
  BeanCounter, v3.4.6811 (SwimmingSeadragon)
  DBMCore, v6b283f7
  DBMStatusBarTimers, v6b283f7
  DBMVPVEM, v1b93adf
  Enchantrix, v3.4.6821 (SwimmingSeadragon)
  EnchantrixBarker, v3.4.6813 (SwimmingSeadragon)
  Informant, v3.4.6814 (SwimmingSeadragon)
  Questie, v7.2.4
  SlideBar, v3.4.6815 (SwimmingSeadragon)
  Stubby, v3.4.6816 (SwimmingSeadragon)
  TomTom, vv3.1.4
  WeakAuras, v4.1.4
  WeakAurasOptions, v4.1.4
  BlizRuntimeLib_enUS v3.4.0.30400 <none>
  (ck=3c0)

## Questie & WoW version
WoLK Classic

**Comment by BreakBB** [comment]
Merging this with #4351
