### ISSUE TITLE
Map Missing Locations of Quests Started by an Item

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#4244]
https://www.wowhead.com/wotlk/items?filter=6:166;1:3;0:0#0+2+19

In the past any item dropped only by on 1 mob was listed.

**Comment by Yttrium-tYcLief** [comment]
Fixed with https://github.com/Questie/Questie/commit/ef5af8f1faa0bc5bafb0d6ca41d37d572b5a94c6
