### ISSUE TITLE
Windseer Grayhorn's Quests Show Before they are Available

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#4248]
![image](https://user-images.githubusercontent.com/55365231/193179347-3b0e445a-2b14-4131-9af4-ab701cb9b382.png)

**Comment by Gogo1951** [comment]
![image](https://user-images.githubusercontent.com/55365231/193179417-b7d02514-4ce5-4c9d-b652-b4b45fed7991.png)

**Comment by Yttrium-tYcLief** [comment]
`12453` "[Eyes Above](https://www.wowhead.com/wotlk/quest=12453/eyes-above)" pre-req: `12412` "[My Enemy's Friend](https://www.wowhead.com/wotlk/quest=12412/my-enemys-friend)"
