### ISSUE TITLE
Grennix Shivwiggle's Quests show before they are available

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#4249]
![image](https://user-images.githubusercontent.com/55365231/193179589-13dea9eb-0655-4067-881a-633e11e9226e.png)

https://www.wowhead.com/wotlk/npc=27719/grennix-shivwiggle

**Comment by Yttrium-tYcLief** [comment]
`12427` "[The Conquest Pit: Bear Wrestling!](https://www.wowhead.com/wotlk/quest=12427/the-conquest-pit-bear-wrestling)" pre-req: `12413` "[Attack on Silverbrook](https://www.wowhead.com/wotlk/quest=12413/attack-on-silverbrook)"
