### ISSUE TITLE
Vessels of Power (10028) - Missing objective display

### ISSUE THREAD

**Issue by Muehe** [Questie/Questie#4252]
https://www.wowhead.com/wotlk/quest=10028/vessels-of-power

**Comment by dscreet** [comment]
Can you give more info? What objective is missing exactly? Looking at the db, I can see the item "Draenei Vessel" as the objective.

**Comment by Muehe** [comment]
Nope, sorry. There are some reports like this by me, which are reports that are ported from Discord so they don't get lost in the chat, I always try to port all the information that is given.

**Comment by BreakBB** [comment]
Closing this after checking the DB. This quest looks fine.
