### ISSUE TITLE
Soup for the Soul (11381) - Missing obective info

### ISSUE THREAD

**Issue by Muehe** [Questie/Questie#4255]
```
[04:40:08] Questie: [ERROR] [QuestieQuest]: [SpecialObjectives] There was an error populating objectives for Soup for the Soul 11381 0 No error
```

https://www.wowhead.com/wotlk/quest=11381/soup-for-the-soul

Was supposedly fixed in [v6.3.15](https://github.com/Questie/Questie/releases/tag/v6.3.15), we should probably check why this correction doesn't apply anymore.

Report from v7.0.2

**Comment by Yttrium-tYcLief** [comment]
Don't think this is a database error with this quest - this particular one seems to be a widespread issue with Questie lately.

Specifically, something wrong with the "update" function, proceeded by the "Error populating objectives" and finally ending in "No error". I've seen it happening with plenty of quests whose objectives are basic and solid.

**Comment by Muehe** [comment]
@Yttrium-tYcLief Hmm, could be that we introduced some bug recently, but the reports on Discord are from a few weeks ago, so it might actually be missing or incorrectly loaded correction data.

**Comment by Yttrium-tYcLief** [comment]
> @Yttrium-tYcLief Hmm, could be that we introduced some bug recently, but the reports on Discord are from a few weeks ago, so it might actually be missing or incorrectly loaded correction data.

The thing is, if you drop the quest and pick it back up again, you don't get the error. If you /reload, you don't get the error. Also, when you get this error, it you check, the objectives ARE actually present on the map. I am *fairly* certain it's an actual Questie issue.

**Comment by Yttrium-tYcLief** [comment]
As with #4256, not sure exactly what we did to fix it but I haven't seen this issue popping up in quite some time now.
