### ISSUE TITLE
The Air Strikes Must Continue (11533) - Missing objective info

### ISSUE THREAD

**Issue by Muehe** [Questie/Questie#4256]
```
The Air Strikes Must Continue 11533 0 No error
```
https://www.wowhead.com/wotlk/quest=11533/the-air-strikes-must-continue

Was supposedly fixed in [v6.10.2](https://github.com/Questie/Questie/releases/tag/v6.10.2), we should probably check why this correction doesn't apply anymore.

Report from v7.0.2

**Comment by Yttrium-tYcLief** [comment]
The `No error` prompts were a race condition - not sure if (or when) it's been fixed, but it's not quest specific. I personally haven't noticed it happening in quite some time.
