### ISSUE TITLE
Yellow text on screen quest progression not showing?

### ISSUE THREAD

**Issue by unie92** [Questie/Questie#4258]
Hello! I'm in a bit of need for help! My friend told me this was questie releated and I'v been googling and searching like a madman but can't find anything about it.

So my issue is! 
The on screen progression for quests that pops up everytime you kill a mob or loot a quest objective isnt showing at all.
(Not the quest tracker, but the text that normaly pops up on the center of the screen in yellow).
![unknown](https://user-images.githubusercontent.com/114732119/193229505-7001e4b9-9e1f-45be-9a0f-da71b3fd5439.png)

As can see on this image taken from my friends game ^ I'v tried doing full reset on UI, uninstalled all addons and reinstalled them.
Tho still I cannot see the text. 

Is this questie related?

**Comment by Cabro** [comment]
As far as i know, that yellow text is Blizzard UI

**Comment by BreakBB** [comment]
@Cabro is right on this @unie92 - That text is not something Questie adds, but is the regular wow UI. Not sure if there is a setting or something though 🤔

**Comment by unie92** [comment]
Ah alright ye I thought as much, Have made a post to blizzard support! 
Do any of you know perhaps what it's called? or if there is any addons that does the same thing that could be a "Fix"?

**Comment by BreakBB** [comment]
Hey @unie92 another user also opened up an issue for this, which you might want to follow: #4402
