### ISSUE TITLE
After installing questie no UI settings save

### ISSUE THREAD

**Issue by Campollia** [Questie/Questie#4262]
## Bug description

Every time i install questie i can no longer change settings and have them stick after a UI reload, or relog, or exit the game and restart. It always reverts to the way the UI and settings were before the addon was installed. Only way i could fix it was by deleting my WTF folder and starting fresh with all my settings. 

## Questie & WoW version

I've been messing with addons trying to narrow down which one is causing the issue for the past week. CurseForge was set to auto update, so i've had this issue at least since v7.2.0

**Comment by BreakBB** [comment]
Hey @Campollia is this still an issue for you? Any by "change settings" you mean the default Blizzard UI settings?

You are the only one reporting such an issue, so I fear it must be something on your side. Did you try to disable all addons except Questie and see if this issue persists?

It might be a rare conflict with another addon.

**Comment by BreakBB** [comment]
Assuming this is no longer an issue.
