### ISSUE TITLE
Boosted Shaman Quests

### ISSUE THREAD

**Issue by klassey** [Questie/Questie#4268]
## Bug description
Logged in and Questie popped this error: [ERROR] The quest 70398 is missing from Questie's database

When I turned in the quest and picked up the next in the series I encouterd LUA errors:

Message: ...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:1036: attempt to index local 'quest' (a nil value)
Time: Fri Sep 30 11:32:24 2022
Count: 1
Stack: ...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:1036: attempt to index local 'quest' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua"]:1036: in function `PopulateQuestLogInfo'
[string "@Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua"]:372: in function `val'
[string "@Interface\AddOns\Questie\Modules\TaskQueue.lua"]:8: in function <Interface\AddOns\Questie\Modules\TaskQueue.lua:6>

Locals:

Message: ...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:1036: attempt to index local 'quest' (a nil value)
Time: Fri Sep 30 11:32:24 2022
Count: 1
Stack: ...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:1036: attempt to index local 'quest' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua"]:1036: in function `PopulateQuestLogInfo'
[string "@Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua"]:372: in function `val'
[string "@Interface\AddOns\Questie\Modules\TaskQueue.lua"]:8: in function <Interface\AddOns\Questie\Modules\TaskQueue.lua:6>

Locals:

## Questie & WoW version
Questie v7.2.4
Wow Version.  /run print((select(4, GetBuildInfo()))) = 30400

**Comment by BreakBB** [comment]
Merging this with #4351
