### ISSUE TITLE
[[75] An Intriguing Plan (12165)] - prerequisite objectives missing from mob tooltips & nameplates

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#4277]

**Comment by Gogo1951** [comment]
@Yttrium-tYcLief 

![image](https://user-images.githubusercontent.com/55365231/193413049-2ffe4319-98a4-4e51-a885-fc1bdb3aa0c6.png)

Just so you're across this, Threat Plates has always worked with Questie. It's one of the most common nameplate add-ons in Classic WoW. Basically anyone who tanks uses it.

> https://www.curseforge.com/wow/addons/tidy-plates-threat-plates

**Comment by Yttrium-tYcLief** [comment]
I can confirm this one is working for me, tooltips and all. I'm not sure exactly what was going wrong for you, but I can clearly see the objective icon (loot bag) to the left of your nameplate, although the nameplate's threat warning is covering it a bit.
