### ISSUE TITLE
Error - Missing Objective Victory in Wintergrasp 13183

### ISSUE THREAD

**Issue by Jorvanus** [Questie/Questie#4281]
Message comes up in chat.  The message in Chat references the quest title of Victory in Lake Wintergrasp, but it's called Victory in Wintergrasp.  Shows the below error. 

(https://www.wowhead.com/wotlk/quest=13181/victory-in-wintergrasp#:~:text=Win%20a%20Wintergrasp%20battleground%20match,be%20credited%20for%20the%20victory.)

## Screenshots
![image](https://user-images.githubusercontent.com/89010934/193405696-b2479d16-5443-4cae-9674-921146037a3c.png)

WOTLK & 7.2.4

**Comment by BreakBB** [comment]
Thanks @Jorvanus fixed in 23dd8bad625007e83e38083bd480ac2a4b278271 and will be in the next release!
