### ISSUE TITLE
[[74] Keep 'Em on Their Heels (12284)] - Horde NPC are shown as targets

### ISSUE THREAD

**Issue by Cryces** [Questie/Questie#4288]
Horde NPC got the sword mark and whenever you hover over them the first time, they show the quests objective in the tooltip. Interestingly enough, the objective disappears if you hover over the same unit repeatedly, but will reappear if you ve hovered over some other NPC in between

**Comment by MyTechnoHunter** [comment]
Tooltips.. the game loves to screw with em.. can hover the mini map too to reset it and have it show again..

**Comment by BreakBB** [comment]
Hey @Cryces can you share a screenshot of this behaviour? 🤔

**Comment by Cryces** [comment]
@BreakBB Sadly, i'll be in another country for the next 3 days. But i'll follow up on it once i'm back. Since it's a daily, any other player could confirm this for you as well.

To describe a bit better: 
The nameplates have the sword marker next to it, and the tooltip behaves as described above. Meaning it shows the unit as a quest objective, but only the first you hover over it. So if you hover over the same one repeatedly without hovering over anything else in between, the message disappears.

**Comment by Cryces** [comment]
@BreakBB here's a demo: https://youtu.be/U6sQqCLBemQ
Not going to claim I understand the condition. It's definitely not as consistent as I thought it was.
