### ISSUE TITLE
Quest hidden from tracker, but not marked as hidden in the journey

### ISSUE THREAD

**Issue by Cryces** [Questie/Questie#4291]
I accidentally hid a quest. Went into the journey to unhide it. Turns out the "hidden" checkbox is unchecked, and checking/unchecking it doesnt make the quest reappear.

![image](https://user-images.githubusercontent.com/2063902/193426134-3d624361-e315-488c-a3d0-b65b2dbdccf8.png)

**Comment by Cryces** [comment]
Disabling and enabling auto track quests fixed it.
Meaning if I now hide the quest with shift left click it will not be flagged as hidden, but still disappear until I reset the auto track quests feature.
Right click -> untrack quest, behaves the same

**Comment by Cryces** [comment]
@BreakBB  Here is a demo of the issue https://youtu.be/C5vFy9ZW5mM

But I already found the reason. Since I still had the tracker hooks disabled it didn't update the quest tracking state in the quest log. Which I assume is probably a very obvious behaviour without the hooks.

**Comment by drejjmit** [comment]
Untracking a quest in your quest log and ``Hidden`` in Questie options is not the same thing.
If you hide it in Questie, it hides the available icon on the map/minimap. 
That's all that option does.

**Comment by Cryces** [comment]
Yes, only understood that part after recording the vid.

**Comment by BreakBB** [comment]
Can this be closed @Cryces ?

**Comment by Cryces** [comment]
Hey, sure. I feel like I did find some actual odd behaviour back then. But I've been inactive again for a while now, and can't really remember any useful details anymore.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
