### ISSUE TITLE
Location of NPC Tua'kea is off

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#4301]
![image](https://user-images.githubusercontent.com/55365231/193433564-b70e7deb-d389-439a-bf45-cff373c681a9.png)

**Comment by Yttrium-tYcLief** [comment]
In this case, the NPC has a path that they wander - both points are valid and the path is valid. This path is already included in Questie, but paths are only drawn on the world map, not the minimap.

```lua
[26245] = {
name = 'Tua\'kea',
spawns = {[65]={{47.99,76.11}}},
waypoints = {[65]={{{47.99,76.11},{47.69,76.64}}}},
},
```

If anything is misbehaving here, it's simply that we don't draw paths on the minimap, but that's more of a feature request and not a data issue.

![image](https://user-images.githubusercontent.com/1037011/198498225-00a2b51c-2ca9-40cf-b84b-f7090c4b5f79.png)
