### ISSUE TITLE
Agamar's Hammer don't have the right pre-requisites.

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#4303]
![image](https://user-images.githubusercontent.com/55365231/193433941-36f50bfa-310b-41cd-8f84-d730199e6a0b.png)

Bunch of quests in Agamar's Hammer don't have the right pre-requisites.

All showed as available, but none were.

![image](https://user-images.githubusercontent.com/55365231/193433948-ff66ab05-5c41-44a1-98c1-6bb2f6100bb5.png)

![image](https://user-images.githubusercontent.com/55365231/193433953-bce62974-30f1-4284-858e-1f25194c673d.png)

![image](https://user-images.githubusercontent.com/55365231/193433962-800f038a-cdca-4c1e-bba3-2d71981aa0ec.png)

![image](https://user-images.githubusercontent.com/55365231/193433971-7a266eb8-627e-450b-bfcc-019339d0fafe.png)

![image](https://user-images.githubusercontent.com/55365231/193433977-befcaa43-ba10-401b-8069-4d531c5349e5.png)

**Comment by Gogo1951** [comment]
Basically every quest I picked up today had bugs. Man... I don't know what to say, it feels like it's going to be impossible to fix all of these manually. Like I'd wager there are 500 bugs left to find, based on what I saw today.

What happened to trying to merge data from Quest Helper? Or use that data instead of Cmangos?

**Comment by Yttrium-tYcLief** [comment]
I will be completing every quest accessible to me. Every time I run into a broken quest, I fix it before completing it.

The fact of the matter is that there is no existing flawless database for this data. We are basically making our own at this point, and it takes time, but it's really the only solution there is.

**Comment by elphaeba** [comment]
The pre-requisite for the quests was the quest to go to argmar's hammer named "Agmar's Hammer" from the refuge place to the west. It then gives you a quest called "Victory Nears" once i turned that in all quests became available.

**Comment by Yttrium-tYcLief** [comment]
This is fixed on my local branch, will be in the main version soon
