### ISSUE TITLE
Abandoning quests is broken

### ISSUE THREAD

**Issue by Mastametz** [Questie/Questie#4315]
Abandoning quests is broken. If you select a quest at the top of your quest list and abandon it, as far as you can see, the next quest from the top is auto-selected, but when you abandon that quest, it actually goes to abandon the quest at the bottom of your list. I accidentally abandoned all my Class Specific quests that I was partially done with this way (Warlock being alphabetically bottom of the list). This was last night, and I just replicated it again just now and took a screenshot.

![Untitled12](https://user-images.githubusercontent.com/7686424/193648873-73a384d0-c753-4c88-b561-ccf6a94ed113.png)

Questie 7.3.0
Classic WOTLK 3.4.0

**Comment by Yttrium-tYcLief** [comment]
Can you confirm it behaves normally when Questie is disabled/uninstalled?

**Comment by Mastametz** [comment]
Just disabled Questie and yes it behaves correctly (by properly showing that the quest at the bottom of the list is selected after abandoning a quest, rather than the top).

**Comment by BreakBB** [comment]
I can't reproduce this @Mastametz Did you try to disable all addon except Questie and see if this issue persists?

**Comment by Mastametz** [comment]
Seems like this is some sort of conflict between Questie and ElvUI. I can run one or the other without problems but both at the same time is when this problem manifests.

**Comment by BreakBB** [comment]
Thanks for reporting back @Mastametz - Does this happen only with the first quest in the quest log or with every quest?

Thing is: Questie doesn't touch/change the quest log in any way, so it's kind of strange this is an issue. Will try to get information from other ElvUI users.

**Comment by maxheyn** [comment]
I use both Questie and ElvUI and I have been experiencing this.

**Comment by Mastametz** [comment]
> Thanks for reporting back @Mastametz - Does this happen only with the first quest in the quest log or with every quest?
> 
> Thing is: Questie doesn't touch/change the quest log in any way, so it's kind of strange this is an issue. Will try to get information from other ElvUI users.

If I abandon a quest in the middle of the quest log it results the same way - appears to auto-select top of list but actually has focus on bottom of list and if I click abandon again, it tries to abandon bottom of list while appearing to have top selected.

**Comment by BreakBB** [comment]
Merging with #4799
