### ISSUE TITLE
Disconnections

### ISSUE THREAD

**Issue by StarkSyrup** [Questie/Questie#4318]
Latest versions (v7.3.0) is causing my character to disconnect every 10-20 mins. As soon as I disable Questie, it stops.

**Comment by BreakBB** [comment]
Hey @StarkSyrup can you try to run just Questie and see if this is still an issue?

**Comment by StarkSyrup** [comment]
Yep.. just did it and was disconnected twice within 30 mins. Turned it off again and no disconnects. Very odd..

**Comment by Yttrium-tYcLief** [comment]
Questie has had disconnect issues in the past - especially with the WotLK prepatch launch - so it's not unheard of, we just need to find out exactly what's responsible that's still causing it to happen for you.

As far as I know there were no under-the-hood changes to Questie for 7.3.0, can you try an older version and see if it still happens?

**Comment by Wookieegoat** [comment]
I get disconnected by questie within 30 seconds every time, no matter what version, no matter which character.
I had v7.0.2 finally work for a while, but after todays wow update… crash.
Ive tried several versions, and ive tried all other addons disabled.  I love questie and cant imagine playing without it, but the constant crashing (disconnects) make me not want to play any more

**Comment by Yttrium-tYcLief** [comment]
[Questie-v7.3.0_100ms.zip](https://github.com/Questie/Questie/files/9709708/Questie-v7.3.0_100ms.zip)
@Wookieegoat @StarkSyrup Can you remove your currently installed Questie and install this version instead, and report back on the frequency of disconnects?

**Comment by BreakBB** [comment]
Assuming this is fixed. Feel free to open a new issue when the issue still persists.
