### ISSUE TITLE
Issue happens when I start combat

### ISSUE THREAD

**Issue by Bacrdimike** [Questie/Questie#4319]
## Bug description

I was on my hunter testing dps on a target dummy. Every time I start combat the issue happens.

## Questie & WoW version

Issue is for Wrath Classic

3x [ADDON_ACTION_BLOCKED] AddOn 'Questie' tried to call the protected function 'Questie_BaseFrame:SetHeight()'.
[string "@!BugGrabber\BugGrabber.lua"]:480: in function <!BugGrabber\BugGrabber.lua:480>
[string "=[C]"]: in function `SetHeight'
[string "@Questie\Modules\Tracker\QuestieTracker.lua"]:1041: in function `Update'
[string "@Questie\Modules\Tracker\QuestieTracker.lua"]:1453: in function <...ceQuestie\Modules\Tracker\QuestieTracker.lua:1438>
[string "@SharedXML\C_TimerAugment.lua"]:16: in function <SharedXML\C_TimerAugment.lua:14>

**Comment by BreakBB** [comment]
I am merging this with #4323 - Even if it's not the same error message, it has the same cause.
