### ISSUE TITLE
Plague Quests Showing Up

### ISSUE THREAD

**Issue by Midnight1443** [Questie/Questie#4320]
## Description
I saw a plague quest show up in Orgrimmar, and they're no longer active, because WOTLK classic is live.

## Screenshots

![WoWScrnShot_100322_152323](https://user-images.githubusercontent.com/114959648/193696802-dfd6de13-4910-49e9-b18d-8663969226e6.jpg)

Which version of Questie are you using? 3.4.0

**Comment by Yttrium-tYcLief** [comment]
This should have been fixed over the last couple versions.
