### ISSUE TITLE
Cache Not OK error

### ISSUE THREAD

**Issue by icywind1980** [Questie/Questie#4321]
![image](https://user-images.githubusercontent.com/36376716/193702291-ef7c6bcd-2359-408a-aa20-5c43c9f84f7e.png)

Just updated this morning on curseforge. Version 3.4.0 WOTLK classic

**Comment by BreakBB** [comment]
Hey @icywind1980 thanks for reporting this. It's on our list to be fixed, don't worry about it.

Merging this with #4086

**Comment by icywind1980** [comment]
Thanks for letting me know!
