### ISSUE TITLE
questie 7.3.0 wow classic quest list missing right margin

### ISSUE THREAD

**Issue by karlsirotkin** [Questie/Questie#4322]
## Bug description

questie 7.3.0 wow classic quest list missing right margin

## Questie & WoW version
wow classic/SOM

**Comment by karlsirotkin** [comment]
![questie 7 3 0 missing quest list](https://user-images.githubusercontent.com/114969825/193725521-da5b2497-09c0-4d77-b7f7-bcf02e08b96e.jpg)

Did not add to description, so here is what the screen looks like.  Normally right side has quest list.

**Comment by MyTechnoHunter** [comment]
Reset your tracker to default position

**Comment by karlsirotkin** [comment]
Where is that setting?  I do not knew if that is in the system interface, or where?  Can you please expand a bit.

**Comment by karlsirotkin** [comment]
OMG! that is so helpful.  X 1,000 !!!!
I wondered how to bring up addon options, and somehow even though I am IT (for decades), I missed this hook.

In this case, after update, they had to be enabled with the TRACKER-tab -> BIG RED "ENABLE TRACKER" button.

So, I wonder if update disabled it, so they MIGHT still be a bug to fix?????
