### ISSUE TITLE
Questie_TrackedAchievements:SetHeight()

### ISSUE THREAD

**Issue by Raulfin** [Questie/Questie#4323]
Error spams constantly in CoS when a zombie is killed for 'Zombiefest!" (kill 100 zombie in 1min). The tracker will also periodicly track everything 2 or 3 times during combat, but only in CoS. Friend with 7.2.4 doesn't have the issue.
## Bug description

Message: ADDON_ACTION_BLOCKED: Questie tried to call the protected function 'Questie_TrackedAchievements:SetHeight()'.
```
Time: Tue Oct  4 02:40:27 2022
Count: 283
Stack: ADDON_ACTION_BLOCKED: Questie tried to call the protected function 'Questie_TrackedAchievements:SetHeight()'.
[string "@Interface\AddOns\ElvUI\Libraries\Core\Ace\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29: in function <...Core\Ace\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Interface\AddOns\ElvUI\Libraries\Core\Ace\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface\AddOns\ElvUI\Libraries\Core\Ace\AceEvent-3.0\AceEvent-3.0.lua"]:120: in function <...vUI\Libraries\Core\Ace\AceEvent-3.0\AceEvent-3.0.lua:119>
[string "=[C]"]: in function `SetHeight'
[string "@Interface\AddOns\Questie\Modules\Tracker\AchievementTracker.lua"]:67: in function `LoadAchievements'
[string "@Interface\AddOns\Questie\Modules\Tracker\AchievementTracker.lua"]:96: in function <...ddOns\Questie\Modules\Tracker\AchievementTracker.lua:89>
[string "=[C]"]: ?
[string "@Interface\AddOns\ElvUI\Libraries\Core\Ace\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29: in function <...Core\Ace\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Interface\AddOns\ElvUI\Libraries\Core\Ace\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface\AddOns\ElvUI\Libraries\Core\Ace\AceEvent-3.0\AceEvent-3.0.lua"]:120: in function <...vUI\Libraries\Core\Ace\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: <none>
```

## Questie & WoW version
7.3 Questie
3.4.0.45854 WoW

**Comment by GregoryGH** [comment]
same issue

1x [ADDON_ACTION_BLOCKED] AddOn 'Questie' tried to call the protected function 'Questie_TrackedAchievements:SetHeight()'.
[string "@!BugGrabber\BugGrabber.lua"]:480: in function <!BugGrabber\BugGrabber.lua:480>
[string "=[C]"]: in function `SetHeight'
[string "@Questie\Modules\Tracker\AchievementTracker.lua"]:67: in function `LoadAchievements'
[string "@Questie\Modules\Tracker\AchievementTracker.lua"]:96: in function <...ddOns\Questie\Modules\Tracker\AchievementTracker.lua:89>
[string "=[C]"]: ?
[string "@Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:24: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:20>
[string "@Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:59: in function `Fire'
[string "@Ace3\AceEvent-3.0\AceEvent-3.0-4.lua"]:120: in function <Ace3\AceEvent-3.0\AceEvent-3.0.lua:119>
