### ISSUE TITLE
Missing objective data for quest 12979 and objective Dark Armor Sample

### ISSUE THREAD

**Issue by basdehaan** [Questie/Questie#4325]
Missing objective data for quest 12979 and objective Dark Armor Sample
Quest started by https://www.wowhead.com/wotlk/item=42203/dark-armor-plate
Item dropped by https://www.wowhead.com/wotlk/npc=29380/stormforged-war-golem

Questie version 7.3.0 - no updates pending
Wow version: wotlk classic - 3.4.0.45854

**Comment by dscreet** [comment]
What exactly is missing?

**Comment by basdehaan** [comment]
Theres no objective shown at all. Also no markers on the map for where to go.
The title of the issue is the error I got picking up the item.
