### ISSUE TITLE
Quest Tracker duplicating quests

### ISSUE THREAD

**Issue by theoriginalmre** [Questie/Questie#4327]
Questie v7.3.0 Wrath Classic

In Culling of Stratholme dungeon, the questie tracker visually duplicates the tracked quests repeatedly until they fill the column to the edges of the screen. 

This happens throughout the dungeon, especially when killing the weak zombies in the streets, whilst accompanying the Arthas NPC. As you continue to stay in combat, the quests just keep duplicating. When out of combat, you can disable/enable the tracker to reset the visual bug, but the duplication continues the next time you go into combat.

**Comment by red13dotnet** [comment]
I can confirm the same behavior ocurring in the open world.  With no obvious cause.  So its not limited to CoS.  Getting out of combat does restore the tracker to normal.

**Comment by cbunting99** [comment]
I noticed this too. Such as Icecrown, Everfrost chip shows the quest like 15 times where there is only one location. I've seen it in various different areas, as well as quests that aren't even there, or showing exclamation point for a quest that isn't available yet.

**Comment by red13dotnet** [comment]
If it helps any, I just saw the same behavior in another addon Skillet-classic.   
There, the List of recipes got duplicated in what seemed to be an identical fashion.  
The only commonality I saw was ACE3 libraries.  Hope that helps provide a clue.
