### ISSUE TITLE
quest marker shows prematurely

### ISSUE THREAD

**Issue by tap3ah** [Questie/Questie#4330]
[To Dragon's Fall] was offered to me only after I finished [Wanted: Dreadtalon], although it's safe to assume that all three wanted poster quests are required. However, Questie's quest marker was visible for me before I turned [Wanted: Dreadtalon].

https://www.wowhead.com/wotlk/quest=12095/to-dragons-fall
https://www.wowhead.com/wotlk/quest=12091/wanted-dreadtalon
https://www.wowhead.com/wotlk/quest=12090/wanted-gigantaur
https://www.wowhead.com/wotlk/quest=12089/wanted-magister-keldonus

v7.3.0
WotLK classic

**Comment by Yttrium-tYcLief** [comment]
this should be fixed in 7.3.1 which literally *just* released
