### ISSUE TITLE
[[80] Retest Now (13356)] Missing mark on npcs

### ISSUE THREAD

**Issue by basdehaan** [Questie/Questie#4334]
Which mobs you have to kill is not marked on the nameplates. this should be these three as far as i can tell
https://www.wowhead.com/wotlk/npc=32290/cult-alchemist
https://www.wowhead.com/wotlk/npc=32289/damned-apothecary
https://www.wowhead.com/wotlk/npc=32276/cult-blackguard

questie version: 7.3.0

**Comment by Yttrium-tYcLief** [comment]
This should be fixed as of #4411 with https://github.com/Questie/Questie/pull/4411/commits/246bbc6a988249fddc5e21e88827607ef325d055.

**Comment by Yttrium-tYcLief** [comment]
Looking into this further - the mobs that needed to be killed should show up correctly without database corrections, and they do on my client, as they are listed as dropping a requiredItem for the quest (44301).

https://github.com/Questie/Questie/commit/246bbc6a988249fddc5e21e88827607ef325d055 was an incomplete fix however - I'll finish it off and extend it to the other versions of this quest (horde and alliance both have initial and repeatable/daily versions).
