### ISSUE TITLE
Questie showing a starting quest impossible to pick up if you do a middle quest from the chain quest.

### ISSUE THREAD

**Issue by aromagnoli** [Questie/Questie#4335]
## Description
Questie shows a quest I can't pick up because the NPC is not giving it. It is the starting quest for a chain quest that spans 3 others. It seems there is a way to pick up the 3rd quest, making it impossible to pick up the 1st and 2nd. I ran the C function to check what quests I have done and the results are:
1. A Disturbance In The West. FALSE
2. Your Presence is Required at Stars' Rest. FALSE.
3. Rifle the Bodies. TRUE
4. Prevent the Accord. TRUE.

## Wowhead link
https://www.wowhead.com/wotlk/quest=12439/a-disturbance-in-the-west

## Screenshots
Not needed for this particular issue.

## Questie & WoW version
v7.3.1 and 3.4.0

**Comment by BreakBB** [comment]
Thanks @aromagnoli for this detailled report! Will be easy to fix for us 👍🏻

**Comment by Yttrium-tYcLief** [comment]
Fixed with https://github.com/Questie/Questie/commit/1984ce5f6a605e95ba92016861df65bf7a6691ea
