### ISSUE TITLE
[[80] Before the Gate of Horror (13329)] Objective marks missing on map and nameplates

### ISSUE THREAD

**Issue by basdehaan** [Questie/Questie#4337]
No location is marked on the map and the nameplates arent marked either. 
These mobs should be marked: https://www.wowhead.com/wotlk/npc=32467/skeletal-reaver

questie version: 7.3.1 - updated just now
wow version: 3.4.0.45942

**Comment by Yttrium-tYcLief** [comment]
This one should have been fixed in 7.4.0 with https://github.com/Questie/Questie/commit/b109c7d93ce74e516419551861436327b8bb66d6 - forgot to close the issue.
