### ISSUE TITLE
Changing exclamation and question marks of dailies to blue in the gossip window

### ISSUE THREAD

**Issue by tehKD** [Questie/Questie#4339]
How about changing the color of the exclamation and question marks of dailies to blue in the gossip window.
Right now you can't see if the quest is a daily or the one before it becomes a daily. Or maybe add a text to the title. 
If that is possible at all ;)

**Comment by Yttrium-tYcLief** [comment]
On this note, I use a separate addon for turning incomplete quests to gray icons in the chat window, it'd be cool if Questie could just taken over that whole function with color coordination for daily, incomplete, PvP, etc.

**Comment by BreakBB** [comment]
Hey @Yttrium-tYcLief can you share the addon you are using for this? I was quite sure, it's not really easy (or possible at all) to manipulate the texts in the Gossip window of an NPC/object.

**Comment by tehKD** [comment]
I think he's talking about Quest Icon Desaturation

https://www.curseforge.com/wow/addons/quest-icon-desaturation

**Comment by Stanzilla** [comment]
Blizzard hotfixed that on October 4th though, "Incomplete quests will now appear with a gray ‘?’ in gossip windows."

**Comment by Yttrium-tYcLief** [comment]
Ah yes - I was (am) using Quest Icon Desaturation but I guess that's a vanilla feature now. Still, I can confirm QID works in WotLKC so we can look at that addon for hints on implementing blue icons.

**Comment by Yttrium-tYcLief** [comment]
Literally the day after I made the above comment, the original developer for Quest Icon Desaturation updated a different one of his addons to do *exactly* this for WotLK: https://github.com/fusionpit/QuestFrameFixer

Perhaps we could look into including this code as an option in Questie? It's licensed under MIT and looks incredibly simple. @BreakBB

**Comment by Yttrium-tYcLief** [comment]
It's worth noting that https://github.com/Questie/Questie/commit/0f612eed3395de3930c6ebf89a1da1cb97ecb264 (#4415) will implement blue icons for *gossip* windows. There are a few questgivers that use *greeting* windows, which this commit does *not* implement blue icons for. Those questgivers are fairly rare though, and we're looking into ways to fix that in the future. One example of a greeting window questgiver is [Fringe Engineer Tezzla](https://www.wowhead.com/wotlk/npc=32430/fringe-engineer-tezzla).
