### ISSUE TITLE
Questie showing a starting quest that's impossible to pick if you've done a different starting quest (Betrayal Questline Zul'Drak)

### ISSUE THREAD

**Issue by ghost** [Questie/Questie#4342]
Questie is showing a quest 'Close Call' (https://www.wowhead.com/wotlk/quest=12638/close-call) which is the follow up to 'Darkness Calling' (https://www.wowhead.com/wotlk/quest=12633/darkness-calling) that I can't pick up as I've done 'An Invitation, of Sorts...' (https://www.wowhead.com/wotlk/quest=12631/an-invitation-of-sorts) which leads into 'Near Miss' (https://www.wowhead.com/wotlk/quest=12637/near-miss). It seems there are two different starting quests for this questline depending on whether or not you've done a different questline in Grizzly Hills (https://www.wowhead.com/wotlk/quest=12238/cleansing-draktharon).
 
I've ran the C function to double check:

12638: False
12633: False
12631: True
12637: True
12238: False

Questie & WoW version:

7.3.1 & 3.4.0

**Comment by Yttrium-tYcLief** [comment]
Literally *just* (mere minutes ago) fixed this one on my local branch, will be included in the next version of Questie.

https://github.com/Questie/Questie/commit/cdfcd46570b3be09c392ad108cb2f4c3a0cfc12e
