### ISSUE TITLE
Blood of a Dead God - Incorrect Turn In Marker

### ISSUE THREAD

**Issue by Pastasalad1** [Questie/Questie#4347]
## Description

There are two completion points marked for the quest Blood of a Dead God. The correct one is at the Altar of Har'koa.

I assume this is happening because Har'koa spawns at Zim'Torga after completing the next quest in the chain, but it's not a valid turn in point for Blood of a Dead God.

## Wowhead link

https://www.wowhead.com/wotlk/quest=12684/blood-of-a-dead-god

## Screenshots

![image](https://user-images.githubusercontent.com/113238479/194258445-2fd4f192-8799-42fe-903a-6dac18db3a6c.png)

## Questie & WoW version

Wrath Classic; Questie version 7.3.1

**Comment by Yttrium-tYcLief** [comment]
Fixed with https://github.com/Yttrium-tYcLief/Questie/commit/84e5fe6adad6613980fb9891d673b80a2dac45fb, will be included in a new version soon

**Comment by BreakBB** [comment]
Hey @Yttrium-tYcLief this is actully not a good fix. That NPC indeed has multiple spawn points and also hands out quests at both locations. In later phases of Zul'Drak the spawn that is wrong in the screenshot above is the correct one.

I was thinking about splitting that NPC into a real one and a fake one, but I fear that will not work with tooltips atm. We might need a new way to adjust NPC locations based on quest phases.

**Comment by BreakBB** [comment]
@Cabro is this not fixed yet? 🤔
