### ISSUE TITLE
[WoTLK Classic] To the Dockmaster (70411) missing from Questie

### ISSUE THREAD

**Issue by Shadpwness** [Questie/Questie#4349]
Quest which is received after purchasing a level boost _(please don't hate me for purchasing one, it was for a gatherer alt!)_ also comes with a quest which isn't available normally in-game, called:
- "To the Dockmaster"
- ID: 70411
- WoWHead URL: N/A

is not available on Questie.
![image](https://user-images.githubusercontent.com/30314855/194274236-617abb59-5488-436f-9851-249c17cefeb5.png)

**Comment by Yttrium-tYcLief** [comment]
Going to close this in favor of #4351, which we'll use for tracking all of the boost quests. Thank you for reporting it!
