### ISSUE TITLE
Wotlk Level 70 Boost quests are missing

### ISSUE THREAD

**Issue by BreakBB** [Questie/Questie#4351]
## Description

All of the newly added quests for the level 70 boosted characters are missing from the database.

## Wowhead link

https://www.wowhead.com/wotlk/quest=70395/a-new-beginning (Alliance)
https://www.wowhead.com/wotlk/quest=70396/a-new-beginning (Horde)
https://www.wowhead.com/wotlk/quest=70762/a-new-beginning (Tauren)

## Questie & WoW version

v7.3.2

**Comment by Yttrium-tYcLief** [comment]
A full list of boost quests can be found with this Wowhead search filter:
https://www.wowhead.com/wotlk/quests/min-req-level:70/max-req-level:70?filter=30;1;70000
