### ISSUE TITLE
13233 No Mercy! 13234 Make Them Pay!

### ISSUE THREAD

**Issue by drejjmit** [Questie/Questie#4353]
## Description
Questie: [ERROR] Missing objective data for quest 13233 and objective Players slain: 0/15

## Wowhead link
https://www.wowhead.com/wotlk/quest=13233/no-mercy
https://www.wowhead.com/wotlk/quest=13234/make-them-pay

**Comment by drejjmit** [comment]
Dupe of #4361

**Comment by Yttrium-tYcLief** [comment]
> Dupe of https://github.com/Questie/Questie/issues/4361

Not a dupe, my issue was actually regarding a different aspect, but this can be closed since those fixes are already in (on the quest-fixes branch)
