### ISSUE TITLE
Bug on log in

### ISSUE THREAD

**Issue by Nanzilla** [Questie/Questie#4358]

**Comment by Nanzilla** [comment]
Game's quest log cache is not OK. This shouldn't happen. Questie may malfunction.

**Comment by Nanzilla** [comment]
Received this message upon logging in on low level character in Wotlk Classic.

**Comment by Nanzilla** [comment]
Relogged and its ok now, no message.  Just wanted to let you know.

**Comment by Muehe** [comment]
We are aware that it happens (#4086), but thank you for the report anyway. :+1:

If it happens again you can do a `/reload` in chat to get rid of it. Please do let us know if you find a way to reproduce the problem.
