### ISSUE TITLE
[[80] Free Your Mind (12893)] - NPC location markers missing on the map

### ISSUE THREAD

**Issue by Cryces** [Questie/Questie#4364]

**Comment by dscreet** [comment]
The coordinates of the npcs are missing in the questie db, as well as in wowhead and other databases.

Can you get this data for me? Then I can add it.

**Comment by Cryces** [comment]
Vile: 44.40, 26.92
Lady Nightswood: 41.73, 24.47
The leaper: Runs around in a semi circle on top the tower 
![image](https://user-images.githubusercontent.com/2063902/194763802-ccd156de-96a9-44dc-b870-87a744d02392.png)
My coordinates on the pic are 43.36, 23.76
The other end of the semi circle is at 42.73, 20.57

**Comment by Yttrium-tYcLief** [comment]
This one is fixed already on the quest-fixes branch and will be included in the next release

**Comment by dscreet** [comment]
> This one is fixed already on the quest-fixes branch, including Leaper's path, and will be included in the next release

Can you assign yourself to ones your going to fix so we don't waste time?

**Comment by Yttrium-tYcLief** [comment]
> Can you assign yourself to ones your going to fix so we don't waste time?

Sorry, I meant to open a PR for that merge but have been very busy the past few days. For what it's worth, there's a list of quest fixes that are already done here: https://github.com/Questie/Questie/compare/master...quest-fixes
