### ISSUE TITLE
Quess that do not exist show up on both mini map and map

### ISSUE THREAD

**Issue by xucaen** [Questie/Questie#4371]
## Bug description
Quests that do not exists show up in both the mini map and the map.
My example case is in front of the bank in Darnassus on Maladath realm.

## Screenshots

![Screenshot 2022-10-08 120812](https://user-images.githubusercontent.com/17462261/194717273-fb04d112-206c-44cc-b34c-44b309463ea3.png)

![Screenshot 2022-10-08 120916](https://user-images.githubusercontent.com/17462261/194717275-7b1c98c8-a9c6-44d9-9e7e-3a322afce791.png)

![Screenshot 2022-10-08 121011](https://user-images.githubusercontent.com/17462261/194717287-44a956c1-8edb-4061-93e9-cd73611b1aff.png)

![Screenshot 2022-10-08 121105](https://user-images.githubusercontent.com/17462261/194717292-9ce1f552-6220-441d-957a-eb84bb73156e.png)

![Screenshot 2022-10-08 121332](https://user-images.githubusercontent.com/17462261/194717297-10e9b1f7-a02c-427e-b5c3-dda2c93cb392.png)

## Questie & WoW version

Questie v7.3.2
Wrath of the Lich King Classic v3.4.0.45942

**Comment by Yttrium-tYcLief** [comment]
The quest I'm seeing you show off is Light's Hope Chapel, which should have been [fixed with this commit](https://github.com/Questie/Questie/commit/699e87643d987678638191ecb4d29cd79e5aec7a) in v7.3.3. Please open a new issue if you find another quest showing when it shouldn't be.
