### ISSUE TITLE
How to activate "!" Icons on top of NPC Heads for trivial Quests? (WotlK Classic)

### ISSUE THREAD

**Issue by Mirco1502** [Questie/Questie#4373]
I'm trying to figure this out now for a while. It would be super helpful, since the markers on the Minimap and Worldmap are sometimes not so easy to spot or easy to miss when a lot of NPC's are in close range.

I hope you know which option I mean, it's like the normal Quest markers on the head, but those that are slightly opaque for low level Quests.

Regards!

**Comment by BreakBB** [comment]
Hey @Mirco1502 I am sorry to tell you, but there is no real way for addons to add such things to the game. The icons above NPCs are the default Blizzard one and the game simply hides them at certain level differences.

**Comment by Mirco1502** [comment]
Hello BreakBB and thank you very much for your answer!

I'm still wondering, because when I play Retail and activate the tracking of trivial Questions on the Minimap, all NPC's with trivial Quests available have an opaque "!" above their head, no matter the Level I am (well at least, obviously higher then the actual quest demands, otherwise it's not "trivial")

So when I understand you right, this is simply something that wasn't implemented in WotlK back the days and thus can't be added by an addon? (Because in Retail, like said, it is possible, no matter how "high" your lvl is, as long as it is above the max for the Quest, if you know what I mean?)

Kind regards :)

**Comment by Mirco1502** [comment]
Edit: I have to apologize here. The feature I'm looking for is allready implemented in WotlK Classic and doesn't need any interactions by the Addon Questie.

My problem was that I was missing the "Magnifying Glass" Icon on the minimap, where you were able to pick "Trivial quests". This Icon wasn't showing up for me, only the Icon for detecting Ores. And ye, it's the same, by clicking on this Icon I was able to activate "detect Trivial Quests" and now all NPC's have their nice opaque "!" Icon above their head in addition to Questies Marks on the Minimap and Worldmap :)

So sry again for confusing you! And thank you for this great addon, it's a big help! =)
