### ISSUE TITLE
Questie not detecting Jewelcrafting Daily Quest progress.

### ISSUE THREAD

**Issue by aromagnoli** [Questie/Questie#4376]
## Bug description
Questie not detecting Jewelcrafting Daily Quest progress.

## Screenshots
![image](https://user-images.githubusercontent.com/4464751/194735071-11bc9a17-64c1-441c-a91b-3744cf5faeb4.png)

## Questie & WoW version
v7.3.2 & 3.4.0

**Comment by Cabro** [comment]
Ah this is a "You receive " string fix that was fixed a while ago
