### ISSUE TITLE
[[72] The End of the Line (12110)] - Objective Shows Even After Completed

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#4378]
![image](https://user-images.githubusercontent.com/55365231/194735355-a83fa9f1-1974-49b2-b859-2779669e30c1.png)

**Comment by Yttrium-tYcLief** [comment]
These were added as extraObjectives for this quest; we do not yet have the capability to hide extraObjectives when their relevant primary Objective is completed. The only time extraObjectives get hidden is when the quest itself is marked complete.

That may all seem a bit verbose but the eventual point of me saying that is that this is not so much a bug, as much as a feature request. This could maybe be resolved at the same time as #4270, when we tie extraObjectives more closely to their root Objectives.
