### ISSUE TITLE
[[72] Speak with your Ambassador (12767)] - NPC Location Off

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#4379]
![image](https://user-images.githubusercontent.com/55365231/194735501-6ce5414d-998a-48cb-a150-131ee969661e.png)

![image](https://user-images.githubusercontent.com/55365231/194735520-f030f505-e1f5-4dde-b9f9-59a84a007b87.png)

**Comment by BreakBB** [comment]
Nothing to fix, this NPC is patrolling
