### ISSUE TITLE
Untrack Quests on Map & Minimap?

### ISSUE THREAD

**Issue by Hjodir** [Questie/Questie#4380]
Hello, I was just wondering if there's a setting that will remove the tracking icons for a particular quest or number of quests from the Map and Minimap?  It becomes very hard to use the Map & Minimap tracking effectively when it's just cluttered with icons.  Thank you!

**Comment by Yttrium-tYcLief** [comment]
I would recommend using the "Hide icons of untracked quests" feature, located in the main Questie settings page (type `/questie` )
![image](https://user-images.githubusercontent.com/1037011/195992443-3b81866d-4475-4331-b6fa-f25838423942.png)

Once that's enable, simply untrack the quests you want to hide the icons of.

**Comment by BreakBB** [comment]
Hey @Hjodir what also helps when you feel like "the map is cluttered with icons" is to increase the "Objective icon cluster amount" in the General section of the Questie settings. That option combined multiple icons which are close together so the objective locations are not as detailled on the map, but still give enough information about the locations you need to go.
