### ISSUE TITLE
quest marker shows prematurely

### ISSUE THREAD

**Issue by tap3ah** [Questie/Questie#4388]
[Lakeside Landing] was offered to me only after I finished [Crocolisk Mastery: The Ambush]. However, Questie's quest marker was visible for me before I turned [Crocolisk Mastery: The Ambush].

https://www.wowhead.com/wotlk/quest=12651/lakeside-landing
https://www.wowhead.com/wotlk/quest=12569/crocolisk-mastery-the-ambush

v7.3.2
WotLK classic

**Comment by Yttrium-tYcLief** [comment]
This one will take a bit of research on the beta - I wasn't able to figure out its exact pre-reqs as part of https://github.com/Questie/Questie/commit/4944054a83ea8decb1347391ea2ce40368e81509 because it's just a breadcrumb and I accidentally completed its next quest in chain beforehand.
