### ISSUE TITLE
[[80] Battling the Elements (12967)] - Snorri isnt marked (he's right behind the quest giver)

### ISSUE THREAD

**Issue by Cryces** [Questie/Questie#4390]

**Comment by Cryces** [comment]
The snow piles near the fire elementals should prob be marked to be picked up. And the elementals should be marked with a kill marker.

**Comment by Yttrium-tYcLief** [comment]
Fixed with https://github.com/Questie/Questie/commit/0d2fd4037df43b80b89fba97a21feb3c55b8ee4a
