### ISSUE TITLE
[[37] Survey Alcaz Island] - Questie Error Message

### ISSUE THREAD

**Issue by Ragonfana** [Questie/Questie#4391]
## Description
Upon picking up the "Survey Alcaz Island" quest as an Alliance player, Questie throws an error in chat reading "Missing objective data for quest 11142 and objective Survey Alcaz Island." In the quest log, the quest shows two objective which both read "Survey Alcaz Island". Upon completing the quest normally (speaking to the apprentice flight master and taking the flight tour around alcaz island), the second objective is marked complete. Attempting the flight a second time does not complete the first objective. Questie considers the quest incomplete and no question mark is found on the map or minimap. However, returning to Jaina shows the quest considered complete and is able to be turned in as normal.
Unfortunately I did not get any screenshots of the quest completion, minimap, etc. before just attempting to turn in the quest as recommended by a user on the WoW Forums: https://us.forums.blizzard.com/en/wow/t/survey-alcaz-island-bugged/1325490
I was able to complete the quest without disabling Questie or reloading/relogging the game.
(Not entirely sure if this is a questie-related bug, but since there is an error I wanted to post to be sure.)

## Wowhead link
https://www.wowhead.com/wotlk/quest=11142/survey-alcaz-island

## Screenshots
![image](https://user-images.githubusercontent.com/13308218/194783863-206f59eb-c627-4df7-9f22-672869819e3d.png)

## Questie & WoW version
Questie ver: v7.2.3
WoW ver: 3.4.0.45942 (WotLK)

**Comment by Yttrium-tYcLief** [comment]
With the beta closed and myself being on Horde this time around, this one will be hard to look into, but I've got a 62 Draenei mage on another server that looks to be eligible to do this chain. This one will likely need some *very* manual review but it should be fixable once those variables are in place.

**Comment by Yttrium-tYcLief** [comment]
Documenting:
![image](https://user-images.githubusercontent.com/1037011/198407693-0fac1c61-27a6-4354-b73d-02feb8bc9067.png)
![image](https://user-images.githubusercontent.com/1037011/198407715-d255ecea-076c-44d2-8dc1-1d32fb37e697.png)
