### ISSUE TITLE
Questie stop tracking progress of daily quests when you do them again after the reset.

### ISSUE THREAD

**Issue by Cabro** [Questie/Questie#4396]
So this happened to me just now. I did some daily quests before the reset in the morning, and i took them again to do them... again. This time Questie is not tracking any sort of quest progress, i still have 0 progress on any quest that i already completed before reset, even though the quests are complete. Will check if quests that haven't been tracked exhibit same behavior. LE: only quests that have been completed before the reset timer exhibit this untracking behavior

**Comment by BreakBB** [comment]
Yeah this is already described in #3848

We know about it, but it has a low priority since that is not happening for that many players. It will still be possible for us to fix this though.
