### ISSUE TITLE
Long quest objectives truncated instead of word wrapped. [wotlk]

### ISSUE THREAD

**Issue by RangerFrank** [Questie/Questie#4397]
Long quest objectives are truncated instead of word wrapped, partially obfuscating the objective text and completely hiding the progression tracker, which negates any benefit to having on screen tracking as the quest log needs to be manually referenced to obtain this information.

**Comment by Gogo1951** [comment]
This is an old issue... there's no great way to wrap the objectives. You'll need to make your tracker wider. Just re-posting from the last few times this was brought up. (=

https://github.com/Questie/Questie/issues?q=is%3Aissue+is%3Aopen+text+wrap

**Comment by RangerFrank** [comment]
That seems like a weak excuse. I don't see any reason that a character limit setting couldn't be added and that line breaks could be implemented at the players chosen limit.

**Comment by BreakBB** [comment]
No worries @RangerFrank it is totally possible and @Logonz already started on a solution.

So it's on our list (just like many other Tracker improvements/fixing of regressions). Atm we are full focus on quest fixes though, as that is the core of Questie and hence has the highest priority! We are making good progress so I hope we can start working on other things again soon ™️

**Comment by zekeflynn** [comment]
@BreakBB hey sorry to butt in, but may I suggest an alternative? I was playing around with "Kaliel's Tracker" and it has a toggle that moves the N/N (number counter) part of the text to the beginning of the string. I found it quite nice to read and would tangentially alleviate the issue mentioned here.

**Comment by Dyaxler** [comment]
This has been fixed with Questie V8
