### ISSUE TITLE
Unwelcome Guests - Fix Prequest Requirement

### ISSUE THREAD

**Issue by Pastasalad1** [Questie/Questie#4404]
## Description

The quest Unwelcome Guests is showing as available in Questie before it is available in game. The quest Fervor of the Frostbourne needs to be completed first.

## Wowhead link

https://www.wowhead.com/wotlk/quest=12876/unwelcome-guests

## Questie & WoW version

Questie 7.3.3, Wrath Classic

**Comment by drejjmit** [comment]
This fix will be included in next release. Thanks for the report 
d0c44b8541353f3f7d2490a9f04744abde6ff7fd
