### ISSUE TITLE
Few of the Dropped Item Start Quests are missing Prerequsites

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#4407]
![image](https://user-images.githubusercontent.com/55365231/195258585-b589d7d9-babd-49bf-921a-f2edb404b0ef.png)

This wasn't actually available, need to do the quest to kill the guy. Or at least be on it. Please keep this open, I'll update as I go through the zone on my DK.

**Comment by drejjmit** [comment]
I haven't done the zone myself. But what quest is "quest to kill the guy". Do you have a name or quest id?

**Comment by BreakBB** [comment]
"A Strange Device" was already fixed in 16645c343b43372afe9cf1e9d1c18f6983d2d23d
