### ISSUE TITLE
Tracker not updating in real time..

### ISSUE THREAD

**Issue by Oneirogenic** [Questie/Questie#4416]
Over the last 2 days I've encountered the same issue on nearly every quest, where the tracker-text on screen that shows quest progress won't update along with your actual progress. The maps and everything else work great and update just fine, and when you open your quest log it's of course completed correctly - but when you kill a monster or a mob for a quest it doesn't update the on screen tracker. So if you don't realize you've killed enough mobs already or picked up enough of the required quest items it'll still show "8/10" or "so and so killed: 0/1" and I'll stay running around trying to finish the quest only to realize 5-10 minutes later after pressing "L" that the quest is already complete. I actively noticed this happening over 20 times yesterday on 10/15/2022.

**Comment by asmeralt** [comment]
Also it happens to me. When the tracker freezes it even stops showing new taken quests. The only thing that helps is /reload.

**Comment by asmeralt** [comment]
I debug a little bit this issue and found out that QuestieTracker:Update from QuestieTracker.lue is not invoked properly so that tracker is not updated. Still working on finding a root cause. BTW @Oneirogenic what is your quest sorting order?

**Comment by BreakBB** [comment]
Hey @Oneirogenic yes the Tracker does not update "in real time", but rather every time the combat ended. That behaviour has been the same for the entirety of Questie. But still is something we really need to improve and it's quite high on my personal list of stuff to tackle. Did it also not correctly update after the combat ended?

**Comment by BreakBB** [comment]
Hey @asmeralt I know it's quite late as response, but can you shed some more light on the debug session you did? Anything we can take away from it to speed up improving/fixing stuff? You are right about `QuestieTracker:Update` as that is the heart of the Tracker logic.

**Comment by Muehe** [comment]
@BreakBB Not sure how to proceed on this one, bar @asmeralt or @Oneirogenic having a method of reproduction. Never saw this happening, and there haven't been any recent reports about this problem best I can tell.
