### ISSUE TITLE
Questie tracker position keeps changing position after logging out and back in. 

### ISSUE THREAD

**Issue by HarryBotter1138** [Questie/Questie#4417]
I had this issue when I first leveled my Warlock but it eventually stopped. Now I am leveling a priest and it is happening again. The tracker just randomly shifts position. No rhyme or reason and no changes made to my ui. I am running the latest version of the addon and this issue happens with or without my other addons running. I have no UI addons like elvui or anything.

**Comment by BreakBB** [comment]
Hey @HarryBotter1138 did you try to use the "Reset Position" option in the Tracker settings? Sometimes the Tracker just positions itself weirdly and it keeps getting worse as you progress through the game. It's a shot in the blue though

**Comment by BreakBB** [comment]
Closing this as I think #4664 fixed all possible issues on this.
