### ISSUE TITLE
Desperate Research

### ISSUE THREAD

**Issue by Elesario** [Questie/Questie#4421]
## Description
The "[80] Desperate Research" quest shows in multiple locations across cities on map and minimap, but it just isn't available to me at all. I'm not entirely sure what it's tied to, it's possible I did the linked follow up quest already, but didn't do the starter quest. The Blood Elf commoners and the like just aren't visible to me also. Was this part of the pre-release content for wotlk?

## Wowhead link
https://www.wowhead.com/wotlk/quest=12752/desperate-research

## Screenshots
![WoWScrnShot_101722_155159](https://user-images.githubusercontent.com/60847546/196210182-5cc3db39-bd8d-495d-8aa7-51543ed6030c.jpg)

## Questie & WoW version
Wotlk Questie v7.4.1

**Comment by BreakBB** [comment]
Hey @Elesario thanks for the report. Looks like we missed another quest of the Scourge Invasion event which was active as Wotlk pre event. We will blacklist this quest for the next release.
