### ISSUE TITLE
Quest items not working from tracker interface.

### ISSUE THREAD

**Issue by Mivoc** [Questie/Questie#4422]
## Bug description
Unable to use quest items for Sons of Hodir quests (Dailies) from the Questie quest tracker. Getting an error "Questie has been blocked from an action only available to the Blizzard UI. You can disable this addon and reload the UI."

## Screenshots

![Questie Error](https://user-images.githubusercontent.com/27261777/196241175-a671caa8-840a-42e3-9393-e22939bccff9.jpg)
![Quest Tracker](https://user-images.githubusercontent.com/27261777/196241183-485c9f51-087a-44d1-aec2-336fa682bd56.jpg)

## Questie & WoW version
Questie vv7.3.3
Wrath Classic

**Comment by BreakBB** [comment]
This was fixed with Questie v8 and the major Tracker overhaul
