### ISSUE TITLE
Close Call quest 

### ISSUE THREAD

**Issue by Teasta97** [Questie/Questie#4425]
Having completed the quest line from the Unliving Choker in Zuldrak, I've now got Questie suggesting that I should pick up the quest from Stefan for the opposing choker that I can't pick up. I know it's minor, but is it worth fixing?

**Comment by Yttrium-tYcLief** [comment]
This should have been fixed awhile ago - what version of Questie are you running?

**Comment by Teasta97** [comment]
7.2.4. If it's just because I've not updated, then I'm gonna feel like a right eejit...

**Comment by Yttrium-tYcLief** [comment]
Yep, definitely update. Pretty sure this one was fixed around 7.3-ish.

**Comment by Teasta97** [comment]
Sorry, only just got around to checking. That fixed it, thank you!
