### ISSUE TITLE
"Candy Bucket" quests show on map in Northrend when "Enable Event Quest Icons" is turned off.

### ISSUE THREAD

**Issue by CaraleTheGnome** [Questie/Questie#4433]
## Description
See title.

## Screenshots
<img width="834" alt="image" src="https://user-images.githubusercontent.com/24671315/197336924-72a571a8-50f0-4c81-8b9c-f184777b0b3f.png">

## Questie & WoW version
v7.4.2 for Wrath.

**Comment by Carcoza** [comment]
This is still an issue sadly. I just updated questie to 7.4.3 but still has these "candy buckets" on my map? Is there any other way to get rid of these than unticking the "show event quests"?

![candy buckets](https://user-images.githubusercontent.com/117351862/199690715-a46fe6a2-200c-4f96-beff-c0963b243a01.jpg)

**Comment by BreakBB** [comment]
Hey @Carcoza could you verify this by recompiling the database? `/questie` -> Advanced -> Recompile Database

**Comment by Carcoza** [comment]
> Hey @Carcoza could you verify this by recompiling the database? `/questie` -> Advanced -> Recompile Database

Hallo @BreakBB this worked perfectly, thank you so much <3 No more Candy Buckets on my map with or without the event enabled or disabled. Thank you <3

**Comment by Carcoza** [comment]
![candy bucket 2](https://user-images.githubusercontent.com/117351862/199695071-e11d8a70-02ba-4b9a-a0e7-5c83d7b951a3.jpg)

Sorry at first glance they dissapeared but appeared again within seconds :/

**Comment by BreakBB** [comment]
Thanks @Carcoza for the fast response. Are all Northrend candy buckets showing for you or just this one?

Could you also enable the questIds `/questie` -> Advanced -> Show Quest IDs

**Comment by Carcoza** [comment]
@BreakBB they show upp all over Northrend
![candy buckets northrend](https://user-images.githubusercontent.com/117351862/199696669-6f2a537d-a27b-40a1-a577-8d86566aed7e.jpg)

**Comment by Yttrium-tYcLief** [comment]
Worth noting @BreakBB I think what's happening right now is part of the performancefix regressions. These quests are definitely now flagged as Event quests, and you can see in the screenshot they aren't marked that way. They *also* shouldn't even be showing right now, because that event is over.

**Comment by Carcoza** [comment]
It seems that it is just the Northrend ones that still shows, just logged a low level and checked my map. And the candy bucket quests just shows up in ye Northrend, not anywhere else.
![candy buckets northrend low lvl](https://user-images.githubusercontent.com/117351862/199702755-4353b56d-c3ec-4e7e-8aed-f7719ce328e4.jpg)
