### ISSUE TITLE
Questie FPS dip stutter example

### ISSUE THREAD

**Issue by Feper24** [Questie/Questie#4444]
Hi, I think I managed to recreate a stutter with Questie enabled vs. disabled (ceteris paribus every other variable) in a small test around Stormwind:

https://www.youtube.com/watch?v=FgASpJPd3hc

Is there any tool I can run while perfoming this to help you out finding the root cause? I could only pinpoint this stutter to Questie after disabling and enabling every other addon involved.

**Comment by Yttrium-tYcLief** [comment]
You can load up the Questie profiler by going to `/questie` > Advanced > Open Profiler, posting those results will help us narrow it down

**Comment by Feper24** [comment]
> e

![image](https://user-images.githubusercontent.com/60163442/197893210-c7e18e6f-cb1c-478c-9bf8-7d1a437361ad.png)

Hi, this are the result of such process.

**Comment by Feper24** [comment]
Seems fixed now, thanks for the update which fixed it!
