### ISSUE TITLE
Questie error messages

### ISSUE THREAD

**Issue by Iceplague** [Questie/Questie#4448]
Hi getting these error messages when using Questie.

"Message: Interface_Wrath\FrameXML\QuestLogFrame.lua:210: attempt to index local 'questLogTitle' (a nil value)
Time: Sat Oct 29 00:01:19 2022
Count: 106
Stack: Interface_Wrath\FrameXML\QuestLogFrame.lua:210: attempt to index local 'questLogTitle' (a nil value)

Locals: "

and 

"Message: Interface_Wrath\FrameXML\QuestLogFrame.lua:210: attempt to index local 'questLogTitle' (a nil value)
Time: Fri Oct 28 23:59:41 2022
Count: 1
Stack: Interface_Wrath\FrameXML\QuestLogFrame.lua:210: attempt to index local 'questLogTitle' (a nil value)
[string "@Interface_Wrath\FrameXML\UIParent.lua"]:2214: in function `SetUIPanel'
[string "@Interface_Wrath\FrameXML\UIParent.lua"]:2059: in function `ShowUIPanel'
[string "@Interface_Wrath\FrameXML\UIParent.lua"]:1927: in function <Interface_Wrath\FrameXML\UIParent.lua:1923>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface_Wrath\FrameXML\UIParent.lua"]:2733: in function `ShowUIPanel'
[string "@Interface_Wrath\FrameXML\QuestLogFrame.lua"]:48: in function `ToggleQuestLog'
[string "TOGGLEQUESTLOG"]:1: in function <[string "TOGGLEQUESTLOG"]:1>

Locals: self = <unnamed> {
 0 = <userdata>
 ShowUIPanel = <function> defined @Interface_Wrath\FrameXML\UIParent.lua:1951
 UpdateUIPanelPositions = <function> defined @Interface_Wrath\FrameXML\UIParent.lua:2292
 left = QuestLogFrame {
 }
 HideUIPanel = <function> defined @Interface_Wrath\FrameXML\UIParent.lua:2240
 UIParentManageFramePositions = <function> defined @Interface_Wrath\FrameXML\UIParent.lua:2417
 UpdateScaleForFit = <function> defined @Interface_Wrath\FrameXML\UIParent.lua:2407
 MoveUIPanel = <function> defined @Interface_Wrath\FrameXML\UIParent.lua:2220
 ShowUIPanelFailed = <function> defined @Interface_Wrath\FrameXML\UIParent.lua:2150
 SetUIPanel = <function> defined @Interface_Wrath\FrameXML\UIParent.lua:2156
 GetUIPanel = <function> defined @Interface_Wrath\FrameXML\UIParent.lua:2284
}
key = "left"
frame = QuestLogFrame {
 0 = <userdata>
 MAIThink = <function> defined @Interface\AddOns\D4KiR MoveAndImprove\core.lua:852
 maialpha = 1
 UpdateValues = <function> defined @Interface\AddOns\D4KiR MoveAndImprove\core.lua:773
 setpoint = false
 SetPoint = <function> defined =[C]:-1
 selectedButtonID = 2
}
skipSetPoint = nil" 

Wotlk Classic, v7.4.2

**Comment by BreakBB** [comment]
Hey @Iceplague this is not an issue from Questie. The error originates in "D4KiR MoveAndImprove" as it seems

**Comment by Iceplague** [comment]
> Hey @Iceplague this is not an issue from Questie. The error originates in "D4KiR MoveAndImprove" as it seems

I uninstalled MoveAndImprove. I still get these error messages when opening the Quest window with questie. 

Error Message 1:

Message: Interface_Wrath\FrameXML\QuestLogFrame.lua:210: attempt to index local 'questLogTitle' (a nil value)
Time: Thu Nov  3 17:13:33 2022
Count: 1
Stack: Interface_Wrath\FrameXML\QuestLogFrame.lua:210: attempt to index local 'questLogTitle' (a nil value)
[string "@Interface_Wrath\FrameXML\UIParent.lua"]:2214: in function `SetUIPanel'
[string "@Interface_Wrath\FrameXML\UIParent.lua"]:2059: in function `ShowUIPanel'
[string "@Interface_Wrath\FrameXML\UIParent.lua"]:1927: in function <Interface_Wrath\FrameXML\UIParent.lua:1923>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface_Wrath\FrameXML\UIParent.lua"]:2733: in function `ShowUIPanel'
[string "@Interface_Wrath\FrameXML\QuestLogFrame.lua"]:48: in function `ToggleQuestLog'
[string "TOGGLEQUESTLOG"]:1: in function <[string "TOGGLEQUESTLOG"]:1>

Locals: self = <unnamed> {
 0 = <userdata>
 ShowUIPanel = <function> defined @Interface_Wrath\FrameXML\UIParent.lua:1951
 UpdateUIPanelPositions = <function> defined @Interface_Wrath\FrameXML\UIParent.lua:2292
 left = QuestLogFrame {
 }
 HideUIPanel = <function> defined @Interface_Wrath\FrameXML\UIParent.lua:2240
 UIParentManageFramePositions = <function> defined @Interface_Wrath\FrameXML\UIParent.lua:2417
 UpdateScaleForFit = <function> defined @Interface_Wrath\FrameXML\UIParent.lua:2407
 MoveUIPanel = <function> defined @Interface_Wrath\FrameXML\UIParent.lua:2220
 ShowUIPanelFailed = <function> defined @Interface_Wrath\FrameXML\UIParent.lua:2150
 SetUIPanel = <function> defined @Interface_Wrath\FrameXML\UIParent.lua:2156
 GetUIPanel = <function> defined @Interface_Wrath\FrameXML\UIParent.lua:2284
}
key = "left"
frame = QuestLogFrame {
 0 = <userdata>
 selectedButtonID = 2
}
skipSetPoint = nil


Error Message 2: 

Message: Interface_Wrath\FrameXML\QuestLogFrame.lua:210: attempt to index local 'questLogTitle' (a nil value)
Time: Thu Nov  3 17:17:19 2022
Count: 4
Stack: Interface_Wrath\FrameXML\QuestLogFrame.lua:210: attempt to index local 'questLogTitle' (a nil value)

Locals:

**Comment by Iceplague** [comment]
Hmm.. I may have found what caused the issue. 
Wide Quest Log Addon. 
Seems to be some conflict there with Questie.

**Comment by BreakBB** [comment]
Not sure if it is in conflict with Questie or if the addon is just broken. You can use Leatrix Plus to widen the quest log iirc

**Comment by Iceplague** [comment]
Questie itself widens the questlog, so I guess the two addons just have a conflict of interest. :)
But by removing wide questlog addon solved the issue.
