### ISSUE TITLE
Remove the questmarkers for the WotLk Prepatch event

### ISSUE THREAD

**Issue by Isilrond** [Questie/Questie#4449]
![grafik](https://user-images.githubusercontent.com/42411053/198833474-9aef64d1-773a-47c4-a07a-52b5189ecb86.png)

This is Darnassus - but same in every other capital
no more NPCs - no longer need the questmarkers

**Comment by Yttrium-tYcLief** [comment]
This is fixed already on `quest-fixes` and will be in the next release.

**Comment by Isilrond** [comment]
all right
