### ISSUE TITLE
Missing tracking add Ons

### ISSUE THREAD

**Issue by Ozzicks609** [Questie/Questie#4451]
## Bug description
As I entered Hills brad foothills and accepted the quest my icons for the locations of bears and spiders and so on did not appear and now the rest of my quests are not popping up as I track them. I have no clue about why it happened but I'd like to let someone know. 
## Screenshots
7.3.3 is my Questie version

**Comment by Ozzicks609** [comment]
updated it and issue has not been resolved and checked the in addon feature to enable map icons.

**Comment by Yttrium-tYcLief** [comment]
Do you have the "hide icons for untracked quests" (or roughly that name) option enabled in Questie's settings?

**Comment by Ozzicks609** [comment]
No I switched it and tried both ways nothing happened

**Comment by BenNightHawk** [comment]
So how did you fix it?

**Comment by Ozzicks609** [comment]
I havent fixed it yet I uninstalled it and re installed it and the issue is
still here

**Comment by BenNightHawk** [comment]
Yeah same.

**Comment by Ozzicks609** [comment]
Is it working now?

**Comment by Ozzicks609** [comment]
Delete it and re install go to inter face. addons. Questie in general
select enable map icons okay.close open click to make the box checked again
and it worked for me

**Comment by BreakBB** [comment]
I am closing this for now. Feel free to open up a new issue, if you still have problems.
