### ISSUE TITLE
Quest not appearing on map for tracking quests

### ISSUE THREAD

**Issue by BenNightHawk** [Questie/Questie#4452]

**Comment by BenNightHawk** [comment]
None of my quests are appearing on my map of the location of said things I need. However, I can still see quest around the world which I can grab.

**Comment by Yttrium-tYcLief** [comment]
Can you try:

1. Updating Questie to the latest version (7.4.2 as of posting this comment)
2. Going to `/questie` > Advanced, and pressing Reset Questie

**Comment by Muehe** [comment]
@BenNightHawk Closing here because I assume this is resolved. Feel free to create a new issue or ask for help on Discord if you are still having problems.
