### ISSUE TITLE
Emerald Dragon Tears wrong quest source

### ISSUE THREAD

**Issue by Firehex12** [Questie/Questie#4454]
## Description

For quest Emerald Dragon Tears quest items can be grabbed only from quest objects while addon shows like Emerald Lasher can drop them, which is wrong

## Wowhead link

https://www.wowhead.com/wotlk/quest=12200/emerald-dragon-tears

## Questie & WoW version

7.4.2, Wrath classic

**Comment by Yttrium-tYcLief** [comment]
Already fixed with https://github.com/Questie/Questie/commit/f23ab6cc1ce2f304a93cdda97115b92c81cbfb98, will be included in the next Questie release
