### ISSUE TITLE
Show correct daily

### ISSUE THREAD

**Issue by Iowerth** [Questie/Questie#4456]
Hi. Questie shows all kinds of dailies:
![1](https://user-images.githubusercontent.com/10152411/198868075-c0d7ce8d-3824-450d-b1e3-26e762954799.jpg)
If it possible please make showing of only available daily as it already made in Nova World Buffs:
![2](https://user-images.githubusercontent.com/10152411/198868108-0a0cdb8e-471b-4a87-9587-9aabe59e5249.jpg)

**Comment by BreakBB** [comment]
Hey @Iowerth that is on our list and we track the progress in this issue: #4106

It also has high priority so once I have time I'll starting tackling this.
