### ISSUE TITLE
Invalid Quest ID's (Icecrown) copied from discord

### ISSUE THREAD

**Issue by MyTechnoHunter** [Questie/Questie#4457]
silverhawke — 10/13/2022
lemme write down all the quest IDs up there...
Unavailable quests that are marked as available in "Quests by Zone", Horde side
[ Borean Tundra ]
11621 - The Tablet of Leviroth
11622 - Secrets of Riplash
12490 - Veehja's Revenge
[ Dragonblight ]
12015 - Test Quest for Craig
12021 - A Letter Home
12051 - Rustling Some Feathers
[ Grizzly Hills ]
12233 - [Depricated]Sewing Your Seed
12163 - The Evil Below
12162 - Solstice Village
12426 - DEPRECATED
11997 - REUSE
[ Sholazar Basin ]
12682 - [Uncharted Territory (DEPRECATED)
12586 - In Search of Bigger Game
[ The Storm Peaks ]
12835 - All Grown Up
12837 - Tore's Got the Goods
12834 - Not Rain, Nor Snow, Nor Exploding Plane
12825 - Expressions of Gratitude
12890 - If Size Matters...
[ Icecrown ]
13184 - Outliving Usefulness
13176 - Preparing the Delivery
13173 - Amidst the Confusion
13175 - Regaining Control
---
This quest is not available yet, as it should be part of the Quel'Delar quest line
24554 - The Battered Hilt

**Comment by BreakBB** [comment]
Thanks @MyTechnoHunter for creating this issue 👍🏻
