### ISSUE TITLE
Da Perfect Spies (25444)

### ISSUE THREAD

**Issue by Arccai** [Questie/Questie#4458]
**Misplaced in the Journey**
────────────────

**Incorrection**
• Placed in **Durotar**

**Correction**
• Doesn't exist

**Wowhead Link** ⭐
https://www.wowhead.com/wotlk/quest=25444/da-perfect-spies

**Comment by Yttrium-tYcLief** [comment]
This quest does technically exist in 3.3.5 data, but is part of the Cata pre-prepatch events, so it's not available. Will be fixed in the next release.
