### ISSUE TITLE
Missing quest Ribbly Screwspigot

### ISSUE THREAD

**Issue by gabbsmo** [Questie/Questie#4459]
## Description
Quest exclamation mark is visible on the starting NPC but it is not shown on world map and the NPC has no tooltip. I am a level 57 paladin.

## Wowhead link
https://www.wowhead.com/classic/quest=4136/ribbly-screwspigot

## Questie & WoW version
Questie: 4.7.2
WoW Classic Era: 1.14.3

**Comment by Yttrium-tYcLief** [comment]
Just to clarify - you've listed Questie as 4.7.2 but are you actually on 7.4.2?

**Comment by Yttrium-tYcLief** [comment]
Oh yeah, sure enough, this quest is wrong in our DB (and on Wowhead, but corrected in Wowhead comments) - it does *not* require its breadcrumb `4324` [Yuka Screwspigot](https://www.wowhead.com/classic/quest=4324/yuka-screwspigot) to be completed beforehand. This will be fixed in the next release.

**Comment by gabbsmo** [comment]
> Just to clarify - you've listed Questie as 4.7.2 but are you actually on 7.4.2?

Yes that was a typo. 

Thanks for fixing so quickly.
