### ISSUE TITLE
TomTom waypoints broken for incomplete quests in 7.4.3

### ISSUE THREAD

**Issue by ThaDanus** [Questie/Questie#4465]
## Bug description
Updated to the latest version today (7.4.3), and it seems I cannot set waypoints anymore in the context menu (right-click quest in the Questie Tracker, Set TomTom Target). Don't have a lot of open quests to test anymore, but it seems all incomplete quests fail to set a TomTom waypoint, but completed quests still work with a TomTom waypoint as for now.
Made a new toon to test this, and yep, all incomplete quests do not set a waypoint, but completed quests do. Something seems to have broken as it worked this morning with the previous version.

## Questie & WoW version
Playing WotLK classic, Questie version 7.4.3

**Comment by Yttrium-tYcLief** [comment]
Can you confirm if it still works when you re-install the older version (7.4.2)?

**Comment by ThaDanus** [comment]
Yes, downgrading to 7.4.2 enables the TomTom waypoint for incomplete quests again.

**Comment by BreakBB** [comment]
Fixed in 842bca98ad9347fb46d09998fea3b9fad6510739
