### ISSUE TITLE
Wrong number of available quests in Journey Log

### ISSUE THREAD

**Issue by ohryk** [Questie/Questie#4471]
## Bug description

After today update (7.4.3) I have wrong number of available quests in Journey Log for Northrend locations.
For example for **Borean Tundra** I have only **74** quests available and for **Dragonblight** only **59**.

## Questie & WoW version

Questie Version: v7.4.3
WoW version 3.4.0

**Comment by Yttrium-tYcLief** [comment]
We blacklisted a *lot* of non-implemented or unavailable quests in the last version - while blacklisting these specific quests was correct in every instance, there may be a few instances where *available* quests are not showing up in Journey. Will look into it.

**Comment by ohryk** [comment]
UPD: it's not only Northrend but for all locations.
For Hellfire Peninsula only 24 quests available (but should be 80 at least)
and for Elven Forest only 2 quests available

**Comment by BreakBB** [comment]
This is related to this commit https://github.com/Questie/Questie/commit/8084db4f86bceb183152d40ce6dff1cfdca4351b
