### ISSUE TITLE
Townsfolk icons no longer work in Questie 7.4.3

### ISSUE THREAD

**Issue by gouletr** [Questie/Questie#4472]
## Bug description
Can't see townsfolk icons anymore on map. Works again when reverting to 7.4.2.

## Questie & WoW version
Wow WotLK Classic 3.4.0
Questie 7.4.3

**Comment by Yttrium-tYcLief** [comment]
What do you mean by townsfolk?

**Comment by gouletr** [comment]
Like, reagent vendors, innkeepers, etc.

**Comment by Yttrium-tYcLief** [comment]
I probably did something wrong when adding the Inscription trainers. Will investigate shortly

**Comment by Yttrium-tYcLief** [comment]
My icons are working but I can't change them - I'm stuck with whatever I had prior (reagent, mailbox, meeting stones). Digging further.

**Comment by Yttrium-tYcLief** [comment]
#4115 seems to be what's at fault here, which was included in 7.4.3. It features a lot of performance improvements, but they seem to also cause database instability.

**Comment by BreakBB** [comment]
There is definately something up. Some townfork icons can no longer be shown (Repair, Flight Master, Banker, Auctioneer, Spirit Healer and Innkeeper). All other icons are working for me (can be shown/hidden).

This might be connected to reading the "sub name" of the NPCs.

**Comment by BreakBB** [comment]
Fixed in 37ba12136a7e9793eb1a55c4993af683ace0cac1

**Comment by gouletr** [comment]
Looking at the performance fixes done in #4115, I am wondering if it really makes a difference to move away from colon syntax. Sure if the function doesn't need `self`, then that's one less parameter on the stack, but I doubt it really makes a difference, since we are not dealing with heavy userdata here.
