### ISSUE TITLE
Amphitheater of Anquish Quest isn't showing up on Map

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#4475]
![image](https://user-images.githubusercontent.com/55365231/199767280-c9f9c7bf-d864-4f69-9117-c635d22f0299.png)

https://www.wowhead.com/wotlk/quest=12932/the-amphitheater-of-anguish-yggdras

There is a breadcrumb quest to go to the Amphitheater, but it's not required to do the first quest.

**Comment by Cabro** [comment]
Should be fixed
