### ISSUE TITLE
The Brothers Bronzebeard (12881)

### ISSUE THREAD

**Issue by DreadedDruid** [Questie/Questie#4477]
Wowhead shows 3 quests of the same name. Two seem identical with same rewards and everything (12973, and 13417), and the WoW API seems to show I have both completed. The third one, 12881, has no info on Wowhead (a few comments but appear to be referring to the other quests of the same name). Since this one is listed as an autocompletion quest, maybe it is a part of the same quest and the API is not flagging it as complete, or perhaps a not implemented version of the quest.

(12881)
https://www.wowhead.com/wotlk/quest=12881/the-brothers-bronzebeard

(12973)
https://www.wowhead.com/wotlk/quest=12973/the-brothers-bronzebeard

(13417)
https://www.wowhead.com/wotlk/quest=13417/the-brothers-bronzebeard

**Comment by Yttrium-tYcLief** [comment]
Most likely a non-implemented duplicate, there's a LOT of those. Will be blacklisted in next version.

**Comment by BreakBB** [comment]
@Yttrium-tYcLief did you find the time yet to fix this?

**Comment by Cabro** [comment]
Should be fixed
