### ISSUE TITLE
Attack on Camp Narache - 24857

### ISSUE THREAD

**Issue by Isilrond** [Questie/Questie#4492]
Is an horde-only quest - but it's on my map as alliance player (maybe you can loot or interact with the questitem?)

https://www.wowhead.com/wotlk/quest=24857/attack-on-camp-narache

![grafik](https://user-images.githubusercontent.com/42411053/200039938-35ec28f8-b05b-4022-bbc3-d53729c6477a.png)

**Comment by Muehe** [comment]
Fixed in bf6a6b74f90c2ff4e2777f9542193f25f6655649 , thanks for the report. :+1:
