### ISSUE TITLE
Vahlarriel's Search - 1437

### ISSUE THREAD

**Issue by Isilrond** [Questie/Questie#4493]
Missing objective on worldmap:

https://www.wowhead.com/wotlk/quest=1437/vahlarriels-search

Desolace:
![grafik](https://user-images.githubusercontent.com/42411053/200044474-80b71b98-8b6b-4672-954c-ac87fe40fcd4.png)

![grafik](https://user-images.githubusercontent.com/42411053/200044385-0c55fe51-9a70-45bd-bfd4-f3df75761f68.png)

**Comment by BreakBB** [comment]
This was fixed with the introduction of the QuestLogCache
