### ISSUE TITLE
questie tracker maximum bugged  makes angry 

### ISSUE THREAD

**Issue by kandaret** [Questie/Questie#4494]
Hello my englisch is very bad , i hope im here right.  

my problem ist the questie tracker in wow classic wotlk.

my problem is the stupid quest tracker.....i put a lot out there, and yet every time i log in, quests are being tracked that aren't actually trackable.
something is wrong here.
Every time I have to randomly click on things in the tracker and then click away again so that it is set and remains the way I want it....I hardly log out and back in again and quests are tracked that I didn't mark at all, etc. ka what's wrong here but it sucks atomically.
![WoWScrnShot_110422_215300](https://user-images.githubusercontent.com/117484391/200073189-e8cb2d43-4027-4ce2-b41c-6c6ad2b8a6de.jpg)

**Comment by BreakBB** [comment]
Hey @kandaret yes, the Tracker needs to be improved further. It's on our list to fix issues like this, but we are quite limited in time and personnel-wise 🙈

**Comment by Muehe** [comment]
@kandaret Wir haben am Tracker seit November einiges repariert. Es gibt zwar noch ein paar Probleme, aber die sind entweder in anderen Reports oder wir arbeiten schon dran. Wenn dir noch was konkretes auffällt mit der neuesten Version mach ruhig eine neue Issue auf.
