### ISSUE TITLE
Helboar, the Other White Meat (9361)

### ISSUE THREAD

**Issue by meyverick** [Questie/Questie#4495]
## Description
Mobs aren't marked as "dropper" for a quest.

## Wowhead link
[Helboar, the Other White Meat](https://www.wowhead.com/wotlk/quest=9361/helboar-the-other-white-meat)

## Screenshots
![image](https://user-images.githubusercontent.com/101877847/200110698-70fed1d4-394a-41a0-b179-c1747a55b314.png)
![image](https://user-images.githubusercontent.com/101877847/200110706-3ea5785c-1e0b-4398-bc32-002beb3f48e1.png)

## Questie & WoW version
7.4.4
WotLK

**Comment by BreakBB** [comment]
Fixed in e213bd9daaceba4df36c58c547440b69badeb1f3
