### ISSUE TITLE
Npc Xarantaur

### ISSUE THREAD

**Issue by Firehex12** [Questie/Questie#4502]
## Description

When you come to here he marked like should give 4 quests at once, but he gives only The Witness and the Hero, when you visit him first time

## Wowhead link

https://www.wowhead.com/wotlk/npc=30381/xarantaur

## Questie & WoW version

7.4.4, Wrath classic,

**Comment by BreakBB** [comment]
Hey @Firehex12 thanks for the report. Yesterday v7.4.5 was released which contains fixes for these quests.
