### ISSUE TITLE
Learn to Ride (unavailable)

### ISSUE THREAD

**Issue by Arccai** [Questie/Questie#4505]
**Misplaced in the Journey**
────────────────

**The Riding Series are unavailable, and therefore should be removed.**
_Item that begins the quests isnt given to the player_

**Wowhead Link** ⭐
https://www.wowhead.com/wotlk/quest=14086/learn-to-ride-in-orgrimmar
https://www.wowhead.com/wotlk/quest=14081/learn-to-ride-in-the-eversong-woods
https://www.wowhead.com/wotlk/quest=14079/learn-to-ride-in-elwynn-forest
https://www.wowhead.com/wotlk/quest=14083/learn-to-ride-in-dun-morogh
https://www.wowhead.com/wotlk/quest=14082/learn-to-ride-at-the-exodar
https://www.wowhead.com/wotlk/quest=14085/learn-to-ride-in-darnassus
https://www.wowhead.com/wotlk/quest=14089/learn-to-ride-in-tirisfal-glades
https://www.wowhead.com/wotlk/quest=14088/learn-to-ride-in-durotar
https://www.wowhead.com/wotlk/quest=14084/learn-to-ride-in-dun-morogh
https://www.wowhead.com/wotlk/quest=14087/learn-to-ride-in-mulgore

**Comment by MyTechnoHunter** [comment]
Yes, got a mail, got the quest.  Learned riding

**Comment by Cabro** [comment]
I got 14081 on 2 test chars where I waited to train riding, while on a char where i went and trained as soon as i hit 20 i didn't get the mail. Seems there's a timer after you hit level 20 after which it checks if you have riding or not, to know whether to send you the mail or not.
