### ISSUE TITLE
Hover item should tell which quest it's from

### ISSUE THREAD

**Issue by lasseedsvik** [Questie/Questie#4508]
Usually most have like 20+ quests in log...... and it would be useful to see which quest the item in bag belongs to.

Trying to keep tracking to a minimal. So knowing like....... having "Gore Bladder" in bags... knowing you need it for Icecrown quest. And you could: 1. Shift click the 15 quests you have for Icecrown till you see that icon next to a quest. OR 2: Google the item in Wowhead

So it would be nice if you could just hover your mouse over an item and it would tell what quest it belongs to.

I just deleted 2 quest items from bags that were from Winterspring and I'm level 80...... and I didn't have those quests obviously....

**Comment by BreakBB** [comment]
Hey @lasseedsvik Questie _should_ already do that for quests you currently have in your quest log.

And I totally agree that this would be great information to show for quest items belonging to a quest you already completed.

**Comment by Yttrium-tYcLief** [comment]
Just a note: Questie only displays those tooltips for quests that are currently being tracked, *not* all quests in your quest log.

**Comment by BreakBB** [comment]
Somewhat related to #2777

**Comment by Cabro** [comment]
This should be fixed
