### ISSUE TITLE
Error During Initialization bad argument #1 to bitband number expected, got nil

### ISSUE THREAD

**Issue by Dreginkt** [Questie/Questie#4509]
## Bug description

Logged in today to this error. Already reinstalled, tried deleting folder entirely and redownloading through curse. Still the same error, unsure the solution at this point. 

## Questie & WoW version

<img width="522" alt="questie dead" src="https://user-images.githubusercontent.com/117958421/201244061-2f67af68-dfec-4a77-8bca-fe47499a5d5b.png">

**Comment by BreakBB** [comment]
Hey @Dreginkt please try the following:

`/dump Questie.db.global.dbIsCompiled = false`
`/reload`

If that doesn't help it would be good to know what version you are using and what class/race your character has.

**Comment by Dreginkt** [comment]
Hi BreakBB,

I tried that in game and got the attached error in response. It happens on all my toons, so BE paladin, tauren druid, undead rogue, ect. 

<img width="495" alt="new error" src="https://user-images.githubusercontent.com/117958421/201501499-d1b6ae44-7e5f-4e16-90b4-59e2dc70822a.png">

**Comment by Dreginkt** [comment]
It's version 7.4.5, the latest on curse. I've also tried disabling all other addons and still, same issue. 

While I'm getting this error and nothing loads on my maps because of it, if I go and accept a quest it freezes my game for 20 seconds and spams me with hundreds of lines of  the attached screenshot. 
![wtf](https://user-images.githubusercontent.com/117958421/201532345-11298be2-87e2-4861-8b64-7dedbc301eb6.jpg)

**Comment by drejjmit** [comment]
Try this command and report back
``/run Questie.db.global.dbIsCompiled = false;ReloadUI()``

**Comment by Dreginkt** [comment]
> Try this command and report back `/run Questie.db.global.dbIsCompiled = false;ReloadUI()`

That did the trick, thank you!

**Comment by drejjmit** [comment]
Glad it worked 👍
