### ISSUE TITLE
Alot of quests that no longer exist in Wotlk Classic are still listed in the "Quests by Zone" section.

### ISSUE THREAD

**Issue by jackrabbit6669** [Questie/Questie#4510]

**Comment by Yttrium-tYcLief** [comment]
Can you give a list of which quests specifically? Blacklisting them is a manual quest-by-quest process.

Also, please ensure you're on the latest version, as we've been blacklisting a lot of unimplemented quests with the most recent releases.

**Comment by BreakBB** [comment]
I am closing this, as we need more details and blacklisting quests is an ongoing process.
