### ISSUE TITLE
Add "Only track quests of current zone" option

### ISSUE THREAD

**Issue by mnejing** [Questie/Questie#4511]
Hi,

I know quite a few people have asked for various things on the tracker, and I have also seen comments as recent as a couple of days ago that the tracker is actively being worked on. So I figure now is a relatively good time to ask for 2 specific things.

First. Can we have some granular control over the size of the tracker? I can generally keep the tracker looking how I like by anchoring it correctly, but that's kind of a wonky way to do it (and confusing for people who don't understand what the anchors actually mean). What I'd like to see is an option to just set a fixed width/height. Scroll as necessary. While I'm quite familiar with Lua and WoW development, I'm NOT familiar enough with the Questie codebase to do a PR on this myself, but the work should be fairly trivial (though the action icon frames...).

Second, and this is one that has been requested a few times, and usually it's marked resolved with a feature that's more of a companion than a resolution, or it's being solved by other addons. I don't feel either of those is necessarily appropriate, so I'll throw my hat in for a suggestion:

I'd like some filter granularity. At minimum I feel like per-zone tracking would appease most people. The closest we got was added to 6.0, but was related to collapsible quests/headers. Which is fine. But isn't the full solution, imo. Ideally, a zone filter would just only show quests for the zone you're currently in. I started working on my own take of an addon to do it, but then realized the Questie hooks some stuff, and stopped when I realized I'd have to essentially write it twice (obviously using the exposed Questie functions, or standard Blizzard API). 

I hate to refer to other addons, but perhaps some filter inspiration could be taken from Kaliel's or somesuch. I'll be entirely honest, I'd prefer to use Kaliel's, but it's pretty broken and the author is mostly checked out of Classic, is more focused on DF, and has gotten kind of combative over fixing it. I realize it sounds mean to sound like I'm "settling" for Questie, but honestly, if I had a fixed size and auto-zone filtering, Questie tracker would be absolutely ideal. 

Again, I may attempt to familiarize myself with the code and add it myself. However, if it's something already being worked on, or a plan in place, or someone just really wants to tackle it.... 

In any case, I appreciate the hard work, Classic would be unplayable without everything you all do. Thanks for considering!

**Comment by Gogo1951** [comment]
Hey @mnejing ,

Try this for now. They may get things fixed, but I've learned not to hold my breath with this add-on.

https://www.curseforge.com/wow/addons/kaliels-tracker-classic

![image](https://user-images.githubusercontent.com/55365231/226153782-e98d40e6-ed77-4914-bbab-93513179ac35.png)
