### ISSUE TITLE
No side quest display

### ISSUE THREAD

**Issue by alharristh** [Questie/Questie#4513]
Questie version 7.4.5

## Bug description
 I have no side quest display on the main screen.  It was there when I logged in about an hour ago and now it is gone and I can't get it back.  I have uninstalled and reinstalled it several times to no avail.  No patch has came out from blizzard in the last several days either.  I haven't added any new addon's.

## Questie & WoW version
This is occuring in classic Wotlk

**Comment by MyTechnoHunter** [comment]
Questie options, tracker section, reset tracker position (make sure you have it enabled and are tracking at least one quest)
