### ISSUE TITLE
Finkle Einhorn, At Your Service!

### ISSUE THREAD

**Issue by ShockMonkey69** [Questie/Questie#4529]
## Description
"Finkle Einhorn, At Your Service!" is removed from WOW but quest indicator is still present on map that it can be taken inside dungeon.

## Wowhead link
Only relevant data from this quest points that its been removed - https://www.wowhead.com/quest=5047/finkle-einhorn-at-your-service

## Screenshots
![image](https://user-images.githubusercontent.com/118683657/202917106-6fe843f5-b965-4a19-ac5b-f7a5b71a837b.png)

## Questie & WoW version

Questie 7.4.5
WOTLK Classic 3.4.0.46368

**Comment by Arccai** [comment]
I believe only the name got changed, thats it.

https://www.wowhead.com/wotlk/quest=5047/pip-quickwit-at-your-service

**Comment by ShockMonkey69** [comment]
Apparently The Beast needs to be skinned for NPC to appear.
