### ISSUE TITLE
Tracker SetPoint Resets when Tracker is Movd

### ISSUE THREAD

**Issue by Barlender** [Questie/Questie#4533]
## Bug description
The "Tracker SetPoint" setting in the Tracker section of the Questie Options resets the tracker to the center of the screen when changed; as intended. But when the setting is set to either "Bottom Left" or "Bottom Right", the growth direction functions as intended (growing from the bottom upwards). Though when the tracker is moved away from the default position, its behavior functions as the auto setting again, growing from top to bottom. The setting itself does not change from the last selected one, but its behavior does. This means that I cannot have the tracker grow from the bottom upwards once I move it into position.

## Questie & WoW version
Questie v7.4.5
WotLK Classic v3.4.0.46368

**Comment by BreakBB** [comment]
Merging this with #4076
