### ISSUE TITLE
Troll Necklace Bounty (2881)

### ISSUE THREAD

**Issue by Arccai** [Questie/Questie#4548]
**Misplaced in the Journey**
────────────────

**Incorrection**
• Visible for **Horde**
• Placed in **The Hinterlands**

**Correction**
• Faction Required : **Alliance**
• Should only be visible for **Alliance** 
• Should be placed in **Repeatable**

**Wowhead Link** ⭐
https://www.wowhead.com/wotlk/quest=2881/troll-necklace-bounty

**Comment by smitgerard** [comment]
This quest also shows up for Alliance in WoTLK Classic, while Wildhammer Clan reputation is disabled.
So should only show up as repeatable quest, not "normal" quest.

**Comment by Arccai** [comment]
Are you sure its the same quest id?
Theres also https://www.wowhead.com/wotlk/quest=2880/troll-necklace-bounty , maybe you referred to that one?

Because (2881) is the one thats shown in the journey, for horde atleast, while its a alliance quest.

**Comment by smitgerard** [comment]
Yes, 2881.

![image](https://user-images.githubusercontent.com/3764277/205082274-c2c5f952-d222-4269-96ca-2b6531d9a718.png)

**Comment by Arccai** [comment]
Ah i see, i didnt check as Alliance, but yeah if its repeatable it should indeed be put in repeatable section, i will edit my report.
Thanks for finding that!
