### ISSUE TITLE
Quest Borders/Icons

### ISSUE THREAD

**Issue by d4kir92** [Questie/Questie#4549]
## Description
is it possible to draw lines around the icons for each quest?
![image](https://user-images.githubusercontent.com/23246564/203751477-6b5f8962-b28e-49d2-8dc1-bf0111379e76.png)

or/and ability to show icons on map/minimap only when its "Tracked"

why i ask for this?
because when i get all quests in a zone and try to find a specific one i cant find it on the map because it has 1000 icons or so and i need to hover over each one to find the right one, also i am colorblind and cant see it if they are colored
i hope its possible to add this :D

**Comment by BreakBB** [comment]
Hey @d4kir92 this is currently not possible, but actually we are kind of working on this. What you can do atm is, that you "focus" on a quest in the Tracker (right click the quest in the Tracker) which hopefully makes it easier for you to see specific quests.

**Comment by d4kir92** [comment]
ok good to know that this is being worked on, i tried the focus thing and it didn't helped enough :D
hope you guys have a solution for that in the future :D

**Comment by BreakBB** [comment]
We can't give any ETA though 🙈
