### ISSUE TITLE
[80] Rejek: First Blood (All three markers are incorrect)

### ISSUE THREAD

**Issue by tparrott** [Questie/Questie#4553]
## Description
This quest has you go kill mobs at three locations. There are only two markers, and they are in the wrong spots, completely wrong spots.

Correct markers from wowhead and confirmed ingame:
Sapphire Hive Wasp: 55, 75
Hardknuckle Charger: 60, 70
Mistwhisper members: 45, 35

## Wowhead link
https://www.wowhead.com/wotlk/quest=12734/rejek-first-blood

## Questie & WoW version
Interface: 30400
Title: Questie|cFF00FF00 v7.4.5|r
Author: Aero/Logon/Muehe/TheCrux(BreakBB)/Drejjmit/Dyaxler/Schaka/Zoey/Everyone else
Notes: A standalone Classic QuestHelper
Version: 7.4.5

Please also state if your quest issue is about Classic Era/SoM or TBC.
WOTLK

**Comment by BreakBB** [comment]
Thanks for reporting this @tparrott 

Funny enough, if you check the wowhead NPCs linked in the quest, these are also completely wrong 😅
