### ISSUE TITLE
Waterlogged Recipe (24431) duplicate?

### ISSUE THREAD

**Issue by DreadedDruid** [Questie/Questie#4554]
Under Dalaran quests, it shows Waterlogged Recipe quest under available (quest id 24431), however under repeatable quests is another Waterlogged Recipe quest (this time quest id is 14203) not sure if this is just a duplicate quest in the database or if there are two versions of this quest. All info appears to be identical between them so I am guessing just a duplicate

**Comment by Arccai** [comment]
Havent done it yet but i strongly believe that the first one (that offers 5 cooking tokens) is a regular quest, after thats been completed you unlock the daily/repeat versions.

**Comment by BreakBB** [comment]
Closing this in favor of #4563
