### ISSUE TITLE
this whole stuff popped when i hit lvl 32

### ISSUE THREAD

**Issue by Warriorfall** [Questie/Questie#4555]
https://i.gyazo.com/affd7659dfff5ef6a28f3e9bf576ff6e.png
https://i.gyazo.com/734e4599161699d00d598f16da83c81f.png
https://i.gyazo.com/332e2a2e5a798b50796ff0ddd22e8066.png
https://i.gyazo.com/183c6d47b10a06eca896346c62b2fae4.png
https://i.gyazo.com/7cc22a30beefaa840f0a63c0faa4acae.png
https://i.gyazo.com/feec8e1d1b0a5175e32c9db1510590fa.png
https://i.gyazo.com/cf466eedb1132ecab14bb83d88e9aa3b.png
https://i.gyazo.com/8b3532e94f7b22879db403c8675fdd33.png

lol. it said to post it here so there u go. no clue what it means. i am a draenei shaman if that means anything

**Comment by BreakBB** [comment]
Hey @Warriorfall thanks for reporting this. Yeah this is an issue in Questie which is around for quite some time now, sorry. A simple `/reload` should fix it.
