### ISSUE TITLE
Questie not registering with the app.

### ISSUE THREAD

**Issue by MarrowLX** [Questie/Questie#4556]
I'm able to view this mod on the website, but it doesn't show up in the app either by searching for questie or by attempting to download from my browser. Any advice?

I'm not using any version because the curseforge app isn't recognizing the download or showing it in app.

**Comment by MyTechnoHunter** [comment]
Make sure that you have the correct version of the game selected in the curseforge app

**Comment by MarrowLX** [comment]
https://gyazo.com/1ad581a4b737c6be6e700180d197174e
Do you mean here?

**Comment by MyTechnoHunter** [comment]
nope, thas release type.. i mean in the upper right corner where you choose retail, classic or WoTLK

**Comment by MyTechnoHunter** [comment]
![image](https://user-images.githubusercontent.com/55214545/205782200-15d43f9f-1930-412c-9e37-e6d79cb9fbcd.png)

**Comment by BreakBB** [comment]
I hope you were able to solve this @MarrowLX. If not, feel free to open a new issue!
