### ISSUE TITLE
Har'Koa quest line has 2 turn in locations marked

### ISSUE THREAD

**Issue by Raulfin** [Questie/Questie#4557]
## Bug description

All quests that pick-up/turn-in to Har'Koa (28401) at Alter of Har'Koa or Zim'Torga in Zul'Drak are indicating his location at both Zim'Torga and Alter of Har'Koa. Har'Koa does appear at Zim'Torga later in the questline, but is at Alter of Har'Koa initially.

-_Initially Har'Koa is at Alter of Har'Koa_-
To Speak With Har'koa (12628)
But First My Offspring (12632)
Back to Har'koa (12653) 
I Sense a Disturbance (12665)
Preparations for the Underworld (12666)
One Last Thing (12675)
Blood of a Dead God (12684)

-_At this point Har'Koa moves to Zim'Torga_-
The Key of Warlord Zol'Maz (12712)
The Gods Have Spoken (12729)
Convocation at Zol'Heb (12730)

## Screenshots

![WowClassic_OSY5usFHKv](https://user-images.githubusercontent.com/7994405/206364675-cb336af3-b60d-4ef3-9a36-c0f356104204.png)
![WowClassic_3Y04d3ZJfb](https://user-images.githubusercontent.com/7994405/206364651-791ed0c5-e7ce-4023-b494-eb409bdad9a5.png)

## Questie & WoW version

Questie 7.4.5
Wrath   3.4.0

**Comment by Zedseayou** [comment]
Can confirm at least for the first two (to speak with har'koa and but first my offspring) this issue causes Guidelime and the Questie set TomTom target functions to point to Zim'Torga instead of the altar, where she is at this stage in the quests.

**Comment by BreakBB** [comment]
Hey @Raulfin and @Zedseayou we currently have no easy way around this. The NPC has indeed two locations and hands out quests in both locations. So Questie simply shows all locations of the NPC even though for specific quests the NPC has a specific location.
