### ISSUE TITLE
table index is nil?

### ISSUE THREAD

**Issue by Zephurith** [Questie/Questie#4558]
Starting up Wow Classic. I use Curseforge as the general install, I've also tried downloading from GitHub to verify it's the same on both sides.

## Bug description
I keep getting a starting text from Questie, and I've noted the tracking does not seem to be working anymore. The text is in a picture I'll upload below, but I've gone down to just using bartender, and even no other addon's and getting the same error message.

Questie: [ERROR] Error during initilization!
Interface\AddOns\Questie\Database\Zones\zoneDB.lua:163: table index is nil

## Screenshots
![Error](https://user-images.githubusercontent.com/120495528/207389859-0f2d80ba-3d0c-400b-8493-4439352ea5e9.PNG)

**Comment by Zephurith** [comment]
Loading the prior install, 7.4.4 version made it work again. Just as an FYI

**Comment by MyTechnoHunter** [comment]
a DB recompile should fix the issue, or the brute force method of removing the questie saved variables from the WTF folder

**Comment by Zephurith** [comment]
I had done a uninstall and reinstall a few times.. also had removed from the profile for the character. I'll look on the saved variables.

**Comment by Zephurith** [comment]
and... a deletion of the saved variables worked perfectly. thank you
