### ISSUE TITLE
Into The Frozen Heart Of Northrend (13139)

### ISSUE THREAD

**Issue by Firehex12** [Questie/Questie#4559]
## Description

Npc Father Gustav marked with addon as available quest giver, but he doesn't offer this quest yet. Wowhead says you need to complete "pre-requisite quests at The Argent Vanguard".

## Wowhead link

https://www.wowhead.com/wotlk/quest=13139/into-the-frozen-heart-of-northrend#comments

## Questie & WoW version

7.4.5, Wrath of Lich King Classic

**Comment by BreakBB** [comment]
Hey @Firehex12 we already have these quests listed as pre quests. Do you know which we are missing?

- [The Air Stands Still](https://www.wowhead.com/wotlk/quest=13125)
- [The Stone That Started A Revolution](https://www.wowhead.com/wotlk/quest=13130)
- [It Could Kill Us All](https://www.wowhead.com/wotlk/quest=13135)
