### ISSUE TITLE
Quest level in quest log

### ISSUE THREAD

**Issue by AnywhereR2** [Questie/Questie#4561]
Please will add quest level to Quest log in Wrath of The Lich King (classic)

https://us.forums.blizzard.com/en/wow/t/quest-levels-in-quest-log-classic/275526/6
![widequestlog_screenshot](https://user-images.githubusercontent.com/60425198/208268887-ed44f4af-e594-4846-9f6b-1b808614675b.png)

**Comment by Iowerth** [comment]
You may use Leatrix Plus addon for this.

**Comment by BreakBB** [comment]
Hey @AnywhereR2 as already suggested, use [Leatrix Plus](https://www.curseforge.com/wow/addons/leatrix-plus-wrath) for this. Questie tries to avoid touching the default UI as much as possible, as it is bound to break and therefore pretty time consuming. So it is not planned to add the quest level to the default quest log at this point.
