### ISSUE TITLE
Disable the inscription about the threat.

### ISSUE THREAD

**Issue by AnywhereR2** [Questie/Questie#4562]
Add a function to disable the inscription of the threat in battle in the tooltip in Wrath of The Lich King (classic).
![WoWScrnShot_121822_015603](https://user-images.githubusercontent.com/60425198/208269049-b174551c-86bd-4512-852c-1c3ca99b94fc.jpg)

**Comment by BreakBB** [comment]
Hey @AnywhereR2 this is not a Questie feature.
