### ISSUE TITLE
Waterlogged Recipe (24431)

### ISSUE THREAD

**Issue by Arccai** [Questie/Questie#4563]
**Misplaced in the Journey**
────────────────

**Incorrection**
• Shown as **Available** after being completed

**Correction**
• Should be placed in **Completed** after being completed

**Wowhead Link** ⭐
https://www.wowhead.com/wotlk/quest=24431/waterlogged-recipe

**Comment by drejjmit** [comment]
Isn't this a rare repeatable drop from the Bag of Fishing Treasures? 
Repeatable will never be flagged as completed by the API, since you might as well get another one the next day that will be completeable.
I assume this should be tagged as repeatable

**Comment by MyTechnoHunter** [comment]
> 

correct! 

![image](https://user-images.githubusercontent.com/55214545/208636120-cf993915-340e-4deb-af45-3fb8994e0ed6.png)

**Comment by Arccai** [comment]
Ive got a blue one in repeatble section aswell, different id.

**Comment by BreakBB** [comment]
@Arccai there are many quests in WoW which are replaced by a repeatable version once you complete them. I think it is the same for this quest.

So once you completed the non repeatable version, the repeatable version becomes available. This might be something we need to correct in Questie and that should also clear your confusion, right?

**Comment by Arccai** [comment]
Hmm im aware of the typical, (completed the 1-time quest in order to unlock the repeat version) but in this case it seems that the yellow one is the repeatable version, ive completed it a few times now :p and ive never seen the blue id one once, So what does that say? The Yellow should be placed in the repeat section and the blue should be removed
