### ISSUE TITLE
Call of water (9504)

### ISSUE THREAD

**Issue by SassyBeard** [Questie/Questie#4564]
## Description
The quest Call of Water [9504] shows the wrong location for filling the bota bag. I just wasted a bunch of time following this waypoint. The real quest location is around 69,65. 

## Wowhead link
https://www.wowhead.com/wotlk/quest=9504/call-of-water

## Questie & WoW version
v7.4.5
WotLK

**Comment by BreakBB** [comment]
Hey @SassyBeard thanks for the report. Looks like Blizzard was clever enough to change this quest with Wotlk, so it is less of a hassle.
