### ISSUE TITLE
Attack on Camp Narache visible to Alliance

### ISSUE THREAD

**Issue by alexanderchekanov** [Questie/Questie#4566]
## Description
Quest 24857 Attack on Camp Narache is a horde-only quest in Mulgore, but is visible to alliance. It should be marked as horde-only.

## Wowhead link
https://www.wowhead.com/wotlk/quest=24857/attack-on-camp-narache

## Questie & WoW version
Questie 7.4.5 Wotlk classic live

**Comment by BreakBB** [comment]
Fixed in bf6a6b74f90c2ff4e2777f9542193f25f6655649
