### ISSUE TITLE
Missing map quest in Borean Tundra: What the Cold Wind Brings...

### ISSUE THREAD

**Issue by Aurheim** [Questie/Questie#4567]
QUESTIE V7.4.5

Classic WotLK

I just got the quest "What the Cold Wind Brings..." and while it does show where to turn it in, there's no indication whatsoever that the quest exists in the first place. This may be intentional due to it not being available at all times but I doubt that since quest "I'm Saved!" in Nagrand shows up just fine. 

The quest is obtained by killing the Sky Darkeners outside of Warsong Hold, which will eventually spawn Ith'rix the Harvester, and once you kill him he will drop a carapace on the ground that is lootable by everyone. Quest seems to be Horde only. 

https://www.wowhead.com/wotlk/quest=11632/what-the-cold-wind-brings

**Comment by BreakBB** [comment]
Hey @Aurheim this is a good hint and we will look into fixing this. I also doubt it will harm to show this quest, even though Questie does this for other quests which have LOTS of possible starting places/drop locations.
