### ISSUE TITLE
The Magister's Apprentice quest shows as being available.

### ISSUE THREAD

**Issue by Verlash** [Questie/Questie#4569]
The Magister's Apprentice quest shows as being available. It is not. I checked wowhead, turns out it's a breadcrumb quest. This quest leads you to the Apprentice Loralthalis NPC to start that quest hub. If, however you go and do the Apprentice Loralthalis quests first, then The Magister's Apprentice is no longer obtainable.

![WoWScrnShot_122922_024128](https://user-images.githubusercontent.com/35006735/209926119-98ac29fb-68e3-47ff-acb9-b58f4a6ea856.jpg)

**Comment by BreakBB** [comment]
Thanks for the report @Verlash. This will be easy to fix
