### ISSUE TITLE
[3.3.5a] Cannot work on it

### ISSUE THREAD

**Issue by Th3AnG3L** [Questie/Questie#4570]
Hello,
I have try from curseforge the link where it says For Lich King download it put it in Addons,
but when i go to Addons to enable it it shows incompatible even if i try load out of updates and enter its not working.
How can i use it for 3.3.5a client any help?
Thank you

**Comment by drejjmit** [comment]
Not planned, we are currently only supporting >3.4. There are some historic Addons for 3.3.5 though, like Carbonite.
