### ISSUE TITLE
Cardinal Ruby is from P3

### ISSUE THREAD

**Issue by Zereges** [Questie/Questie#4571]
## Description
Alchemy quest *Cardinal Ruby* is available from Phase 3 on, but is being shown on the map.

## Wowhead link
https://www.wowhead.com/wotlk/quest=14151/cardinal-ruby

## Screenshots
![image](https://user-images.githubusercontent.com/7399594/210166741-d214e213-fea8-44ab-ab9b-9a52f703b274.png)

## Questie & WoW version
WotLK classic
## Version: 7.4.5

**Comment by BreakBB** [comment]
Hey @Zereges no idea how this quest wasn't reported earlier. Thanks for doing so and it will be easy to fix 👍🏻

**Comment by Zereges** [comment]
For some reason, even after this quest is completed it still shows as uncompleted by `/run print(C_QuestLog.IsQuestFlaggedCompleted(14151))`

**Comment by Cabro** [comment]
That's blizzard spaghetti. It's an edge case we already have on our mind.
