### ISSUE TITLE
Gearing Up To Ride (13908)

### ISSUE THREAD

**Issue by Arccai** [Questie/Questie#4577]
**Misplaced in the Journey**
────────────────

**Incorrection**
• Shown as **Available** after being completed

**Correction**
• **Unavailable**, and should be removed

**Wowhead Link** ⭐
https://www.wowhead.com/wotlk/quest=13908/gearing-up-to-ride

![WoWScrnShot_010323_171127](https://user-images.githubusercontent.com/16717146/210396033-3f2f2074-132b-4bf8-9807-7b77ce0db563.jpg)

**Comment by BreakBB** [comment]
That is strange indeed 🤔 

Can you run the following command and report the output @Arccai ?

`/dump C_QuestLog.IsQuestFlaggedCompleted(13908)`

**Comment by Arccai** [comment]
[1]=false
