### ISSUE TITLE
cant get rid of questie frame extend icon

### ISSUE THREAD

**Issue by sharpwg1337** [Questie/Questie#4579]
On the questie frame, there is an "extend" button on the bottom right that won't go away no matter what I do. I am fine locking the frame in place and never being able to move it or adjust it, so why is this there and why won't it go away? I have tried everything. I'm playing wotlk classic with version 7.4.5

![image](https://user-images.githubusercontent.com/83383138/210625731-ab4a697e-9ff3-4242-bb07-5460b59622f7.png)

**Comment by sharpwg1337** [comment]
Seems that it shows up randomly, and hovering over the frame then back off the frame makes it go away again. However, it will randomly reappear and require me to again, hover over the questie frame and back to get rid of it.

**Comment by BreakBB** [comment]
Thanks for reporting this @sharpwg1337 - The Tracker is in a pretty rough shape since the Wotlk release and it's high on our list to fix issues like this.

**Comment by BreakBB** [comment]
Fixed in #4664
