### ISSUE TITLE
The Dread Citadel - Naxxramas (9121 + 9122 + 9123)

### ISSUE THREAD

**Issue by Arccai** [Questie/Questie#4582]
**Misplaced in the Journey**
────────────────

**Incorrection**
• **Isn't visible anywhere**

**Correction**
• Should be placed in **Eastern Plaguelands**

**Wowhead Link** ⭐
https://www.wowhead.com/wotlk/quest=9123/the-dread-citadel-naxxramas **(Exalted)**
https://www.wowhead.com/wotlk/quest=9122/the-dread-citadel-naxxramas **(Revered)**
https://www.wowhead.com/wotlk/quest=9121/the-dread-citadel-naxxramas **(Honored)**

**Comment by drejjmit** [comment]
Are these even available in wotlk after the revamp of Naxx?

**Comment by Arccai** [comment]
Yeah, i just completed it.
It unlocked **Echoes of War (9033)**
https://www.wowhead.com/wotlk/quest=9033/echoes-of-war

Based on the comments below, it should also be doable on wotlks classic naxx.

I assume **The Dread Citadel - Naxxramas** is counted as a raid quest (but its a zone quest really) while Echos of War is actually a raid quest while it also has (Raid) next to its name in the quest list.
