### ISSUE TITLE
I Sense a Disturbance multiple completion icon on map

### ISSUE THREAD

**Issue by JackArcher2** [Questie/Questie#4589]
"I Sense a Disturbance" quest completion icon "?" is showing up at BOTH Zim'torga **and** Altar of Har'Koa on the map. The latter is the correct one.
also if I remember correctly the previous step also showed up at the wrong location as well.

**Comment by BreakBB** [comment]
Hey @JackArcher2 I am closing this in favor of #4557. The problem with these quests are, that the NPC actually has both of these spawn points and Questie does not handle it quite right yet. We'll fix this in a future update, thanks a lot for reporting it 👍🏻
