### ISSUE TITLE
Elders of Northrend Missing

### ISSUE THREAD

**Issue by Jorvanus** [Questie/Questie#4611]
The Quest Markers for the elders in Northrend are missing.

![image](https://user-images.githubusercontent.com/89010934/213831804-057b3af4-9a86-4e02-86d0-1c153887abdf.png)

https://www.wowhead.com/wotlk/guide/achievements/lunar-festival-to-honor-ones-elders

**Comment by Muehe** [comment]
Fixed in 0ffa2ea3c002e64377664954cdb67938011ba74d will be included in next release. Thanks for the report. :+1:
