### ISSUE TITLE
7.4.9 release.json parsing error

### ISSUE THREAD

**Issue by tseufert1** [Questie/Questie#4613]
There is a comma after the last member of a list on line 14 of release.json.  Trailing commas are not legal JSON, and this is breaking some tools - I use CurseBreaker to update addons and it's throwing a parse error here.

**Comment by BreakBB** [comment]
Thanks for the hint @tseufert1 will fix that as well in a minute. The release is broken entirely.

**Comment by BreakBB** [comment]
Fixed in https://github.com/Questie/Questie/commit/e8543bdd54f1efc8a9a72ad13c032cc0b713dd18

Thanks again for the fast notice @tseufert1 <3
