### ISSUE TITLE
error during initialization 7.4.9 WotlK Classic through CurseForge

### ISSUE THREAD

**Issue by DaymianWoW** [Questie/Questie#4614]
## Bug description

Got the latest version of Questie from CurseForge ~15 min ago. Upon login to WotlK Classic I receive:
[ERROR] Error during initialization! .../Questie/Database/Corrections/QuestieCorrections.lua:220 attempt to call method 'Load' (a nil value)

**Comment by BreakBB** [comment]
Hey @DaymianWoW I just released a v7.4.10 which fixes this! It should be available soon on CurseForge 👍🏻

**Comment by DaymianWoW** [comment]
You are *very* quick! can confirm it fixed the issue. Thank you so much!
