### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by Jmarm0311** [Questie/Questie#4616]
## Questie & WoW version

Hey Good Morning,

i am on classic era, wowtlk, and questie is giving issues by not populating any quest or any items for that matter. I have installed the newest updated and still nothing. anything helps. 

V/r

**Comment by Muehe** [comment]
@Jmarm0311 Please check the Questie options to see if it disabled itself. This happens for some people sometimes when updating, we are unsure why. There is a "Reset Questie" option in the advanced settings if you just want to reset to defaults.

**Comment by BreakBB** [comment]
Assuming this is fixed. Feel free to open up a new issue :)
