### ISSUE TITLE
Quest link tooltip shows wrong color for Daily quests

### ISSUE THREAD

**Issue by Cabro** [Questie/Questie#4619]
World of Warcraft\_classic_\Interface\AddOns\Questie\Modules\QuestLinks\Link.lua:126
Change from 
>titleColor = "blizzardBlue"

to

>titleColor = "blue"

**Comment by Muehe** [comment]
Of course I picked the wrong way to fix this issue. :see_no_evil: Thanks for the report, will fix soon™. :+1:
