### ISSUE TITLE
No quest icons showing up in the map on Mac for WoW Classic?

### ISSUE THREAD

**Issue by Noelani27** [Questie/Questie#4620]
## Questie & WoW version

<img width="1440" alt="Screen Shot 2023-01-25 at 5 28 41 PM" src="https://user-images.githubusercontent.com/123603701/214716393-dde3821e-85b9-4301-8cb8-02a94096b6a3.png">

**Comment by BreakBB** [comment]
Hey @Noelani27 is this for Wotlk or something else?

Also are you sure you are on the latest Questie version?

**Comment by Plueschtigersalat** [comment]
Had the same problem, it was Z-Perl. Even when it was deactivated, cause of the already mentioned errors, Questi wasnt loading. After Questi loads the database you have to relog. Doing a /reload is not enough. Using Windows btw.

**Comment by BreakBB** [comment]
Closing this as it seems to be solvable by either updating Questie and/or disabling Z-Perl for a moment.

Thanks @Plueschtigersalat
