### ISSUE TITLE
Glacial Cloak (9237)

### ISSUE THREAD

**Issue by Arccai** [Questie/Questie#4623]
**Misplaced in the Journey**
────────────────

**Incorrection**
• Placed in **Dungeons > Naxxramas**

**Correction**
• **No longer available, and should be removed**
_Quest-Giver isn't even in this version of naxxramas, he is inside a cage from the old Naxx40_

**Wowhead Link** ⭐
https://www.wowhead.com/wotlk/quest=9237/glacial-cloak

**Comment by Arccai** [comment]
Yeah, it got removed along with the npc that suppose to give it.
He was only placed in the old naxx, he is gone, and so is the quest.

**Comment by BreakBB** [comment]
Good point @Yttrium-tYcLief so we should fix our blacklisting of these

**Comment by Arccai** [comment]
Yepp you are correct, you can pick up the quest from the Blacksmith there if you have one of the 3 professions.
Otherwise it could only be learnt by the npc in naxx.
Meaning this isnt even a zone quest but a profession required one. And therefore it shouldn't be shown in eastern plaguelands either way

**Comment by BreakBB** [comment]
I mean the Glacial Cloak quest (along others) should not be blacklisted, but the pre quest should. That will still show them in the Journey, but not on the map.
