### ISSUE TITLE
gettting spammed by lua errors

### ISSUE THREAD

**Issue by knasen88** [Questie/Questie#4624]
## Bug description

Message: .../AddOns/Questie/Modules/Tracker/TrackerBaseFrame.lua:192: attempt to perform arithmetic on local 'yOff' (a nil value)
Time: Fri Jan 27 19:46:04 2023
Count: 1
Stack: .../AddOns/Questie/Modules/Tracker/TrackerBaseFrame.lua:192: attempt to perform arithmetic on local 'yOff' (a nil value)
[string "@Interface/AddOns/Questie/Modules/Tracker/TrackerBaseFrame.lua"]:192: in function `ShrinkToMinSize'
[string "@Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua"]:728: in function `Update'
[string "@Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua"]:447: in function `func'
[string "@Interface/AddOns/Questie/Modules/Libs/QuestieCombatQueue.lua"]:25: in function <...e/AddOns/Questie/Modules/Libs/QuestieCombatQueue.lua:17>

Locals: minSize = 10
xOff = nil
yOff = nil
(*temporary) = <function> defined =[C]:-1
(*temporary) = Questie_BaseFrame {
 0 = <userdata>
 OnBackdropLoaded = <function> defined @Interface/SharedXML/Backdrop.lua:152
 TopLeftCorner = Texture {
 }
 Center = Texture {
 }
 GetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.lua:390
 SetupTextureCoordinates = <function> defined @Interface/SharedXML/Backdrop.lua:214
 OnBackdropSizeChanged = <function> defined @Interface/SharedXML/Backdrop.lua:182
 HasBackdropInfo = <function> defined @Interface/SharedXML/Backdrop.lua:278
 SetBackdropBorderColor = <function> defined @Interface/SharedXML/Backdrop.lua:422
 RightEdge = Texture {
 }
 backdropInfo = <table> {
 }
 BottomEdge = Texture {
 }
 GetEdgeSize = <function> defined @Interface/SharedXML/Backdrop.lua:188
 BottomLeftCorner = Texture {
 }
 BottomRightCorner = Texture {
 }
 TopEdge = Texture {
 }
 ApplyBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:294
 SetBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:329
 ClearBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:282
 TopRightCorner = Texture {
 }
 GetBackdropBorderColor = <function> defined @Interface/SharedXML/Backdrop.lua:409
 GetBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:347
 sizer = Questie_Sizer {
 }
 SetupPieceVisuals = <function> defined @Interface/SharedXML/Backdrop.lua:246
 SetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.lua:399
 LeftEdge = Texture {
 }
 SetBorderBlendMode = <function> defined @Interface/SharedXML/Backdrop.lua:266
}
(*temporary) = "TOPLEFT"
(*temporary) = UIParent {
 0 = <userdata>
 firstTimeLoaded = 1
 variablesLoaded = true
}
(*temporary) = nil
(*temporary) = 1080.016846
(*temporary) = "attempt to perform arithmetic on local 'yOff' (a nil value)"
baseFrame = Questie_BaseFrame {
 0 = <userdata>
 OnBackdropLoaded = <function> defined @Interface/SharedXML/Backdrop.lua:152
 TopLeftCorner = Texture {
 }
 Center = Texture {
 }
 GetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.lua:390
 SetupTextureCoordinates = <function> defined @Interface/SharedXML/Backdrop.lua:214
 OnBackdropSizeChanged = <function> defined @Interface/SharedXML/Backdrop.lua:182
 HasBackdropInfo = <function> defined @Interface/SharedXML/Backdrop.lua:278
 SetBackdropBorderColor = <function> defined @Interface/SharedXML/Backdrop.lua:422
 RightEdge = Texture {
 }
 backdropInfo = <table> {
 }
 BottomEdge = Texture {
 }
 GetEdgeSize = <function> defined @Interface/SharedXML/Backdrop.lua:188
 BottomLeftCorner = Texture {
 }
 BottomRightCorner = Texture {
 }
 TopEdge = Texture {
 }
 ApplyBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:294
 SetBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:329
 ClearBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:282
 TopRightCorner = Texture {
 }
 GetBackdropBorderColor = <function> defined @Interface/SharedXML/Backdrop.lua:409
 GetBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:347
 sizer = Questie_Sizer {
 }
 SetupPieceVisuals = <function> defined @Interface/SharedXML/Backdrop.lua:246
 SetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.l

newest version, wotlk classic

**Comment by MyTechnoHunter** [comment]
details please.. happened when? doing what? combat? turning in a quest?

**Comment by knasen88** [comment]
doing anything, mouse over mob, join bg, in combat
like literally no "source"

**Comment by BreakBB** [comment]
Hey @knasen88 open up the Questie settings /questie -> Tracker and try the "Reset Tracker position"

**Comment by BreakBB** [comment]
Assuming this is fixed. Feel free to open a new issue :)
