### ISSUE TITLE
Lua Error On Quest Turn In / Interact with NPC

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#4626]
1x Questie/Modules/Auto/Privates.lua:41: attempt to concatenate local 'title' (a boolean value)
[string "@Questie/Modules/Auto/Privates.lua"]:41: in function `CompleteQuestFromGossip'
[string "@Questie/Modules/Auto/QuestieAuto.lua"]:78: in function `GOSSIP_SHOW'
[string "@Questie/Modules/QuestieEventHandler.lua"]:77: in function <...rfaceQuestie/Modules/QuestieEventHandler.lua:76>
[string "=[C]"]: ?
[string "@ArkInventory/Libs/CallBackHandler/CallbackHandler-1.0-8.lua"]:24: in function <...ventory/Libs/CallBackHandler/CallbackHandler-1.0.lua:20>
[string "@ArkInventory/Libs/CallBackHandler/CallbackHandler-1.0-8.lua"]:59: in function `Fire'
[string "@ArkInventory/Externals/Ace3/AceEvent/AceEvent-3.0-4.lua"]:120: in function <...rkInventory/Externals/Ace3/AceEvent/AceEvent-3.0.lua:119>

**Comment by Gogo1951** [comment]
May be bleed over from Elv.

**Comment by Gogo1951** [comment]
![image](https://user-images.githubusercontent.com/55365231/215241564-1c1b1cf2-bf3f-47cb-9d23-e329ce31db86.png)

Got a few bugs I think.

**Comment by MyTechnoHunter** [comment]
> May be bleed over from Elv.

not may be, is :) that is not the font questie uses..
test with elvUI disabled?

**Comment by Gogo1951** [comment]
Questie uses whatever font you set chat frames to use.

Getting these errors, and getting the error where you get a Lua error if you pick up or try and turn in a quest while in combat.

**Comment by Gogo1951** [comment]
![image](https://user-images.githubusercontent.com/55365231/215250494-a3c8e675-9ef6-4f16-a711-f4b65230e169.png)

4x Questie/Modules/Auto/Privates.lua:41: attempt to concatenate local 'title' (a boolean value)
[string "@Questie/Modules/Auto/Privates.lua"]:41: in function `CompleteQuestFromGossip'
[string "@Questie/Modules/Auto/QuestieAuto.lua"]:78: in function `GOSSIP_SHOW'
[string "@Questie/Modules/QuestieEventHandler.lua"]:77: in function <...rfaceQuestie/Modules/QuestieEventHandler.lua:76>
[string "=[C]"]: ?
[string "@ArkInventory/Libs/CallBackHandler/CallbackHandler-1.0-8.lua"]:24: in function <...ventory/Libs/CallBackHandler/CallbackHandler-1.0.lua:20>
[string "@ArkInventory/Libs/CallBackHandler/CallbackHandler-1.0-8.lua"]:59: in function `Fire'
[string "@ArkInventory/Externals/Ace3/AceEvent/AceEvent-3.0-4.lua"]:120: in function <...rkInventory/Externals/Ace3/AceEvent/AceEvent-3.0.lua:119>

**Comment by MyTechnoHunter** [comment]
tracing it back into the stack seems like the table is triggering an invalid title? its supposed to be a string and is sending a boolean value instead?
is anything else set to auto scan available quests? (other addon?)

i imagine we can debug print it  and validate the incoming data to the function as to type before letting the function advance..

**Comment by BreakBB** [comment]
I am quite sure this is caused by the latest API changes. I encountered this when developing as well, but was quite sure I fixed it.

@Gogo1951 is this on Wotlk?

@MyTechnoHunter Gogo is correct about fonts. If addons change the chat font, all addons are more or less bound to that font.

**Comment by Gogo1951** [comment]
The API changes seem designed just to fuck people over. I don't understand the goals of the changes this time around. Broke a lot of shit.

**Comment by Gogo1951** [comment]
@MyTechnoHunter happened on a mob without a title. Got it on a few NPCs though. None of them had a title.

**Comment by MyTechnoHunter** [comment]
Hrm.. so it could be a valid NPC just without a title in the table wait no, the title in this case is the title of the quest so that makes no sense

Screwy api changes..

**Comment by Gogo1951** [comment]
Prob have to check and build an exception for NULLs. Dunno, but that seems to happen a lot.

**Comment by BreakBB** [comment]
We will look into it and fix the issue. It certainly is a problem on our side and connected to the latest API changes.

**Comment by BreakBB** [comment]
My first tests showed that the API changes made by the Dragonflight client on Classic seems to work differently than the original API.

The API in question for this issue is [C_GossipInfo.GetActiveQuests](https://wowpedia.fandom.com/wiki/API_C_GossipInfo.GetActiveQuests) which _should_ return `isComplete=true` for quests which are complete in your quest log and can therefore be turned in at the NPC you are currently talking with. Questie relies on this information to determine if a quest from the NPCs list should be clicked and then turned in or if it is not worth clicking on it.

This should also be just a problem on NPCs which offer multiple quests.

**Comment by MyTechnoHunter** [comment]
there are many MANY addons that purport to auto (accept/complete) quests.. i wonder if the list is being munged cause another addon clicked and it changes mid loop?
