### ISSUE TITLE
Error: Number of the objectives of the quest changed

### ISSUE THREAD

**Issue by phild8** [Questie/Questie#4640]
WOTLK

Questie: [ERROR] Please report on Github or Discord! Number of the objectives of the quest changed. questId, oldNum, newNum 13204 1 0 
Questie: [ERROR] Please report on Github or Discord! Number of the objectives of the quest changed. questId, oldNum, newNum 7081 1 0 
Questie: [ERROR] Please report on Github or Discord! Number of the objectives of the quest changed. questId, oldNum, newNum 6982 1 0 
Questie: [ERROR] Please report on Github or Discord! Number of the objectives of the quest changed. questId, oldNum, newNum 7162 1 0 
Questie: [ERROR] Please report on Github or Discord! Number of the objectives of the quest changed. questId, oldNum, newNum 7102 1 0 
Questie: [ERROR] Please report on Github or Discord! Number of the objectives of the quest changed. questId, oldNum, newNum 4866 1 0 
Questie: [ERROR] Please report on Github or Discord! Number of the objectives of the quest changed. questId, oldNum, newNum 13413 1 0 
Questie: [ERROR] Please report on Github or Discord! Number of the objectives of the quest changed. questId, oldNum, newNum 13253 1 0 
Questie: [ERROR] Please report on Github or Discord! Number of the objectives of the quest changed. questId, oldNum, newNum 13091 1 0 
Questie: [ERROR] Please report on Github or Discord! Number of the objectives of the quest changed. questId, oldNum, newNum 13071 1 0 
Questie: [ERROR] Please report on Github or Discord! Number of the objectives of the quest changed. questId, oldNum, newNum 13243 1 0 
Questie: [ERROR] Please report on Github or Discord! Number of the objectives of the quest changed. questId, oldNum, newNum 12855 2 0 
Questie: [ERROR] Please report on Github or Discord! Number of the objectives of the quest changed. questId, oldNum, newNum 236 1 0 
Questie: [ERROR] Please report on Github or Discord! Number of the objectives of the quest changed. questId, oldNum, newNum 13538 1 0 
Questie: [ERROR] Please report on Github or Discord! Number of the objectives of the quest changed. questId, oldNum, newNum 64845 1 0 
Questie: [ERROR] Please report on Github or Discord! Number of the objectives of the quest changed. questId, oldNum, newNum 8867 2 0 
Questie: [ERROR] Please report on Github or Discord! Number of the objectives of the quest changed. questId, oldNum, newNum 3861 1 0 
Questie: [ERROR] Please report on Github or Discord! Number of the objectives of the quest changed. questId, oldNum, newNum 7624 1 0

**Comment by BreakBB** [comment]
Hey @phild8 thanks for reporting this.

Are you able to reproduce this or was this a one time thing?

**Comment by phild8** [comment]
One time thing. I also have Kaliel tracker installed.

I'll try to repeat some of the steps that led to the error tomorrow.

Which was:
Toggle questie on map
Accept a summon.
Then zone into nax (errors were then generated)
