### ISSUE TITLE
Messy addition in new Questie

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#4646]
You know how I really know you guys don't give a shit any more and are just milking this for Amazon Gift Cards?

You'd ride me so hard for putting in data like this. Long rants, and stripping out my PRs, and making me re-do things just because you could... and now you don't give shit if people add them in sloppy.

Cool. Cool, cool, cool.

The rule was, "Only show these for uniquely named mobs, not for the commodity mobs that have 300 spawn points." I think you should keep to that rule.

We had that old issue in for showing quests that dropped in a zone. It's fallen by the wayside.

![image](https://user-images.githubusercontent.com/55365231/216838860-4a2f652f-564c-4500-bbc2-dad58a5b57ff.png)

**Comment by BreakBB** [comment]
This change was definitely not intentional and you are right about this violating our rule about not cluttering the map with drop quests like this. You know mistakes can happen, nothing you should feel personal offended of 🤷🏻
