### ISSUE TITLE
[ERROR] Missing objective data for quest 13482

### ISSUE THREAD

**Issue by camperdad** [Questie/Questie#4665]
## Bug description

I did the escort father kamaros quest in ice crown.  questie didn't have a mark for where it ended.  Since then I see the following error message every time I login.

[ERROR] Missing objective data for quest 13482 and objective Escort Father Kamaros to safety

## Screenshots

![image](https://user-images.githubusercontent.com/125707444/219817039-4dab29f0-6426-49a8-a31f-80b3027d4eef.png)

## Questie & WoW version

wotlk

**Comment by BreakBB** [comment]
@Cabro this you do this quest? I can not find a correction for 13482 or 13481

**Comment by BreakBB** [comment]
Will you look into it again @Cabro and close this issue, if appropriate?

**Comment by Cabro** [comment]
I believe this https://github.com/Questie/Questie/commit/5183187cdcc900ef5026c3412bc570a87954df38 should have the fixes for this. I hope :D
