### ISSUE TITLE
Abandoning a quest abandons random other quests instead

### ISSUE THREAD

**Issue by ZookCloak** [Questie/Questie#4668]
## Bug description
While Questie v7.4.14 is enabled, clicking [Abandon] on a quest in the Quest Log causes a different, random quest to be abandoned instead of the one currently selected. Closing/reopening the Quest Log, ensuring the proper quest is highlighted, and trying again continues to cause other, seemingly random quests from the log to be abandoned instead of the currently selected quest. It will even abandon (Complete) quests, which is especially irritating.

Disabling the Questie v7.4.14 addon entirely allows the currently highlighted quest to be abandoned as normal.

## Questie & WoW version
Questie v7.4.14
Wrath of the Lich King Classic

**Comment by BreakBB** [comment]
Hey @ZookCloak can you verify this happens with just Questie enabled? This might be a conflict with another addon.

**Comment by MyTechnoHunter** [comment]
might be a problem with savedvariables (stupider things have happened with blizz)

i will say that with questie, leatrix +, and dugi guides, all of which in some way shape or form mess with the quest log i havent been able to get behavior like you mentioned..

**Comment by Dyaxler** [comment]
This was a bug that was in Questie a LONG time ago. We have built in sanity checks to make SURE the right quest is selected in the Quest Log before Questie runs AbandonQuest().

I personally run both Questie and Dugi Guides together all the time and have never had an issue with this.

**Comment by Raulfin** [comment]
i had this happen a time or 2, and noticed that essentially the game didn't recognize that i had selected a quest in the list, and it would always try to abandon the top quest in my list.
