### ISSUE TITLE
questie classic - questie tracker background solid black

### ISSUE THREAD

**Issue by sharpwg1337** [Questie/Questie#4672]
i have background disabled on the questie tracker in the classic version, specifically i am playing classic era, however after fighting one enemy it turns to a black background like the picture

![2023-02-24 12_35_59-192 168 86 207 - Remote Desktop Connection](https://user-images.githubusercontent.com/83383138/221263221-dab8155f-962d-410e-8f34-8b01eda7d6f7.png)

how do i resolve?

**Comment by BreakBB** [comment]
Hey @sharpwg1337 there are Tracker specific settings to change this behaviour. Check `/questie` -> Tracker.

Also sorry for the late response on this, your report slipped by.
