### ISSUE TITLE
QUesties seems not to be working on one of my characters, works on every other one.

### ISSUE THREAD

**Issue by Jmatt990** [Questie/Questie#4673]
## Bug description

Questie does not show quests that are available in a region. But shows trails of mobs but no quests. But questie works for other character on the same server. I have uninstalled questie and re installed and still the same issue. To my knowledge I updated questie and the fact that it works for every other character except one of them is kinda weird. Thanks for the help! 

## Screenshots

https://1drv.ms/b/s!AuhdcmZj00V6nWrfpGlmzVoTYhxM?e=GtDjQD

![WoWScrnShot_022523_114542](https://user-images.githubusercontent.com/126345496/221369999-a2407c75-1b7f-4b5a-abeb-991491f0e03a.jpg)

**Comment by drejjmit** [comment]
Press Show Questie in the top right

**Comment by Jmatt990** [comment]
Lol i feel like a ding dong. it fixed it, not sure why it disappeared on me. Thanks Drejjmit!

**Comment by drejjmit** [comment]
Haha. No worries. Maybe it got accidentally clicked at some point on that character.
