### ISSUE TITLE
Report to Lord Devrestrasz misnamed in questie

### ISSUE THREAD

**Issue by Raulfin** [Questie/Questie#4675]
## Description

The quest 'Report to Lord Devrestrasz'(12435) appears on the minimap, tooltip, and in the My Journey as 'Report to Lord Afrasastrasz'.
A quick check of wowhead shows no quest or npc with that name.

## Wowhead link

https://www.wowhead.com/wotlk/quest=12435/report-to-lord-devrestrasz

## Screenshots

The npc to turn in the quest, showing it as Dev in the dialog box, left, and quest tracker, right, and as Afra in the tooltip.
![WowClassic_rx0qIt9uIi](https://user-images.githubusercontent.com/7994405/221472946-c396f4ea-7630-456b-a078-e0796d9d998b.jpg)

My Journey, shown as middle quest:
![WowClassic_qhRXkur6si](https://user-images.githubusercontent.com/7994405/221473379-35254834-2f4e-4f4e-82dc-28463ad69437.png)
## Questie & WoW version

Questie 7.4.14
Wrath 3.4.1.48120

**Comment by Muehe** [comment]
This is another one of the names changed following the "Afrasiabi" scandal at Blizzard. It's hard to get an exhaustive list of these, thanks for the report @Raulfin :+1:

**Comment by Raulfin** [comment]
ahh yeah, had forgotten that guys name and that they had purged any ref to him from the games.
