### ISSUE TITLE
Super Strong Metal Plates!

### ISSUE THREAD

**Issue by Firehex12** [Questie/Questie#4681]
## Description

Quest item [Super Strong Metal Plate] can be picked ONLY from objects, but addon shows like i can get them from Kvaldir npc

## Wowhead link

https://www.wowhead.com/wotlk/quest=11644/super-strong-metal-plates

## Questie & WoW version
7.4.14, wrath classic

**Comment by Muehe** [comment]
Fix will be in next release, thanks for the report. :+1:
