### ISSUE TITLE
Tracker Settings Reset with Latest Update

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#4683]
![image](https://user-images.githubusercontent.com/55365231/223797845-235a40dc-eeaf-450d-a29d-1a5f46034e3f.png)

Only reset this setting.

Seems like it wasn't intentional.

**Comment by BreakBB** [comment]
Similar reports were made in the past. Some settings changing after a release even though we did no migration of the settings or touched them in any way. Might be connected to a dependency issue or a conflict with another addon.

**Comment by Gogo1951** [comment]
I've had this issue 5-6 times with Questie in Wrath alone. Something is breaking.

As I've said before, this is the only add-on that has this problem.

Feels like, again just a hunch, you have some process that get scuffed if you update and log out right away. I'd start with that. Questie DB updates take a long time, and if I just log into check out an auction I generally log out right away. Some sort of "Don't log out while Quesite is updating" is likely needed. Again, just a gut feeling.

**Comment by BreakBB** [comment]
Merging with #4365
