### ISSUE TITLE
QuestieStream.lua:268

### ISSUE THREAD

**Issue by yiliqi78** [Questie/Questie#4684]
Questie:[ERROR] Error during initialization! Interface/AddOns/Questie/Modules/ QuestieStream.lua:268: attempt to perform arithmetic on local 'c'(a nil value)

**Comment by BreakBB** [comment]
Ouch, that's not something good @yiliqi78 

Did a `/reload` fix this issue or is it persistent for you?

**Comment by Muehe** [comment]
Might be problem with outdated DB, try copying this command to ingame chat:

`/run Questie.db.global.dbIsCompiled = false; ReloadUI();`

**Comment by BreakBB** [comment]
Any news on this @yiliqi78 ?

**Comment by BreakBB** [comment]
Closing as this is stale.
