### ISSUE TITLE
quest non-existent

### ISSUE THREAD

**Issue by sickolovespokemon** [Questie/Questie#4685]
## Description
 

there is a quest marker for '[23] Uncommon Scents' that leads me to nothing. i tried getting to lvl 23, because i thought that was the problem, but it turns out to be an error between questie & wotlk classic. 

## Wowhead link

there are no results when i search for the quest on WoWhead.
## Screenshots

![IMG20230309131435](https://user-images.githubusercontent.com/127445399/224147836-06fef4e9-a46f-473b-b3b9-f367a19
![WoWScrnShot_030923_133512](https://user-images.githubusercontent.com/127445399/224151285-630ec8a6-0b45-4314-ab56-64878cdf35e8.jpg)
e660c.jpg)
![Screenshot 2023-03-09 134126](https://user-images.githubusercontent.com/127445399/224152490-23019785-4eb4-4889-a6f7-256efc88b0ef.png)

## Questie & WoW version

TBC

**Comment by sickolovespokemon** [comment]
here is another picture that didn't get uploaded for some reason: 
![IMG20230309131435](https://user-images.githubusercontent.com/127445399/224153792-a0f61645-9850-4161-96be-42c5728d8594.jpg)

**Comment by BreakBB** [comment]
Hey @sickolovespokemon thanks for reporting this! We will fix this for the next release and I will merge your report with #4678
