### ISSUE TITLE
Lua error still happening when you talk to NPCs without <Titles>

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#4688]
38x Questie/Modules/Auto/Privates.lua:41: attempt to concatenate local 'title' (a boolean value)
[string "@Questie/Modules/Auto/Privates.lua"]:41: in function `CompleteQuestFromGossip'
[string "@Questie/Modules/Auto/QuestieAuto.lua"]:78: in function `GOSSIP_SHOW'
[string "@Questie/Modules/QuestieEventHandler.lua"]:77: in function <...rfaceQuestie/Modules/QuestieEventHandler.lua:76>
[string "=[C]"]: ?
[string "@ArkInventory/Libs/CallBackHandler/CallbackHandler-1.0-8.lua"]:24: in function <...ventory/Libs/CallBackHandler/CallbackHandler-1.0.lua:20>
[string "@ArkInventory/Libs/CallBackHandler/CallbackHandler-1.0-8.lua"]:59: in function `Fire'
[string "@ArkInventory/Externals/Ace3/AceEvent/AceEvent-3.0-4.lua"]:120: in function <...rkInventory/Externals/Ace3/AceEvent/AceEvent-3.0.lua:119>

**Comment by BreakBB** [comment]
Merging this with #4626

We are working on a fix.
