### ISSUE TITLE
The Call To Command... ID is Off

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#4690]
Few issues... this quest showed up for Horde before it should have, and then once I picked it up, it still showed on the map.

Guessing IDs have shifted.

![image](https://user-images.githubusercontent.com/55365231/224530595-13cbe7e2-ec68-4ee3-8f9d-ebc9f84f5fc1.png)

**Comment by BreakBB** [comment]
Could you enable "Show Quest IDs" in the Advanced settings so we know which ID the new one is and which should be blacklisted?
