### ISSUE TITLE
Hunter and Shaman trainer tracking reversed on alliance toon. 

### ISSUE THREAD

**Issue by KokaneeSavage** [Questie/Questie#4703]
So Im on WoW Classic WOTLK, I only noticed this issue on my alliance toons, when using the tracker option from Questie looking for Class trainers on the hunter it shows me shaman trainers, and the shaman shows me hunter trainers

WoW Version: 4.5.1.48503
Questie version: v7.4.14.zip

Love this addon couldnt imagine life without it. I hope this is a sufficient bug report its my first one. I didnt inculde screen shots because i dont think they will add much value. but i can get them upon request.

**Comment by Cabro** [comment]
Did the 2 chars had the names changed at the start? Like between them?
