### ISSUE TITLE
Pre-requisites not taken into account for the Suspicious Hoofprints, The Black Shield, and Lieutenant Paval Reethe quests

### ISSUE THREAD

**Issue by nickdotwav** [Questie/Questie#4713]
## Description

Questie shows the quest indicator for these quests:

Lieutenant Paval Reethe
The Black Shield
Suspicious Hoofprints

But I can't accept any of these quests due to not completing the pre-requisite quest "James Hyal" and "James Hyal" OR "They Call Him Smiling Jim." The indicators for these quests shouldn't be showing yet. 

**EDIT:** For alliance at least, you also have to do the quest "Inspecting the Ruins" **after** turning in "James Hyal" (part 2).

## Wowhead links

https://www.wowhead.com/wotlk/quest=1284/suspicious-hoofprints
https://www.wowhead.com/wotlk/quest=1253/the-black-shield
https://www.wowhead.com/wotlk/quest=1252/lieutenant-paval-reethe

**PRE-REQS:**
https://www.wowhead.com/wotlk/quest=1301/james-hyal

https://www.wowhead.com/wotlk/quest=1302/james-hyal (part 2)
OR
https://www.wowhead.com/wotlk/quest=1282/they-call-him-smiling-jim

**EDIT:** https://www.wowhead.com/wotlk/quest=11123/inspecting-the-ruins

## Screenshots
![image](https://user-images.githubusercontent.com/91393313/226212127-8db59ca9-f9d4-4f0c-a9c9-d0f005844b49.png)
![image](https://user-images.githubusercontent.com/91393313/226212182-119b38c5-a7e2-47eb-9c78-8940d501ebbe.png)

## Questie & WoW version

Questie version 7.4.14

WoW WotLK version 3.4.1.48503

**Comment by Gogo1951** [comment]
There are probably a dozen or more bugs with Dustwallow Marsh Quests since Wrath hit. The whole zone is really buggy, data-wise. Good to keep reporting these @nickdotwav thanks!
