### ISSUE TITLE
A few issues with Blood Elf Paladin class quests.

### ISSUE THREAD

**Issue by Cabro** [Questie/Questie#4714]
Some quests in this chain have been completely changed for WOTLK from TBC versions. 
1 - As such, some NPCs are not present anymore in WOTLK: M'uru (id 17544) removed, no replacement; Magister Astalor Bloodsworn (id 178420) replaced with id 17718.
2 - https://www.wowhead.com/wotlk/quest=64319/a-study-in-power replaced with https://www.wowhead.com/wotlk/quest=9681/a-study-in-power . Different NPC to turn in at.
3 - https://www.wowhead.com/wotlk/quest=63866/claiming-the-light replaced with https://www.wowhead.com/wotlk/quest=9684/claiming-the-light . Different NPC where you accept (you get it from 17718 in wotlk), different NPCs to use quest item on (instead of M'uru you have Blood Elf Magisters (id 17845)).

7.4.14

**Comment by BreakBB** [comment]
Fixed in #4740
