### ISSUE TITLE
The Fate of the Kingdom is not actually available

### ISSUE THREAD

**Issue by mazerakham** [Questie/Questie#4715]
Source: https://www.wowhead.com/quest=4362/the-fate-of-the-kingdom#:~:text=This%20quest%20was%20marked%20obsolete,clutches%20of%20Emperor%20Dagran%20Thaurissan.

And also, I cannot get the quest in-game (WOTLK).

**Comment by BreakBB** [comment]
Hey @mazerakham could you run the commands above?
