### ISSUE TITLE
The Crimson Courier

### ISSUE THREAD

**Issue by Firehex12** [Questie/Questie#4721]
## Description

On map courier position marked with single bag icon while it should be marked with red line showing his patrol route from Stratholme.

## Wowhead link

https://www.wowhead.com/wotlk/quest=14350/the-crimson-courier

## Questie & WoW version
7.4.14, Wrath classic

**Comment by Gogo1951** [comment]
I'm 99% sure it used to have a pat... but I noticed this as well last time I was leveling.

**Comment by BreakBB** [comment]
Closing in favor of #4691
