### ISSUE TITLE
Marshal Windsor (4241)

### ISSUE THREAD

**Issue by Marvy936** [Questie/Questie#4722]
QUEST IS NO MORE OBTAINABLE!
3.4.1   WotLK
7.4.14 Questie 

WOWHEAD:
https://www.wowhead.com/classic/quest=4241/marshal-windsor

**Comment by MyTechnoHunter** [comment]
make sure you use the right version of wowhead.. 
https://www.wowhead.com/wotlk/quest=4241/marshal-windsor

you sure its not obtainable?

**Comment by Marvy936** [comment]
Hey, Im pretty sure.

I read and try to search everything about that. All of that Q was part of
Onyxia preQ for Amulet and this is no more needed. So Im pretty sure its
not obtainable anymore since Wotlk.

"
This quest is no longer in the game due to the fact that there will be no
requirement for Onyxia. Patch 3.0.2


ne 26. 3. 2023 o 22:14 MyTechnoHunter ***@***.***> napísal(a):

**Comment by BreakBB** [comment]
Fixed in https://github.com/Questie/Questie/commit/e4923133d29938dcdc5cd9edd4965a99447e549d
