### ISSUE TITLE
Dragonkin Menace (4182)

### ISSUE THREAD

**Issue by Marvy936** [Questie/Questie#4733]
QUEST IS NO MORE OBTAINABLE!
3.4.1 WotLK
7.4.14 Questie

WOWHEAD:
https://www.wowhead.com/classic/quest=4182/dragonkin-menace

**Comment by BreakBB** [comment]
Hey @Marvy936 yes you are totally right. The entire Onyxia pre quest is no longer available in Wotlk, we'll hide them if that didn't happen yet 👍🏻
