### ISSUE TITLE
inding the Antidote

### ISSUE THREAD

**Issue by Firehex12** [Questie/Questie#4747]
## Description

Npc, which starts quest was moved in Wrath. "After the barbershops were added in the last patch, Kor'ghan was moved to 43.3, 50.5".
But we still have his blue marker at old map position.

## Wowhead link

https://www.wowhead.com/wotlk/quest=813/finding-the-antidote
https://www.wowhead.com/wotlk/npc=3189/korghan#comments
## Questie & WoW version
7.5.0, Wrath Classic

**Comment by BreakBB** [comment]
Great findings @Firehex12 Thanks for these reports 👍🏻
