### ISSUE TITLE
Quest tracker still does not collapse downward when anchor point is set to bottom right

### ISSUE THREAD

**Issue by dameinsinner** [Questie/Questie#4762]
When the anchor point is set to bottom right the quests do not grow from bottom to top and it does not collapse downward like you would expect if something is anchored to the bottom. The paper doll for broken gear also does not show on the left side of the tracker as you would expect if it is anchored to the right. I reported this bug after the launch of Wrath and was told it was being worked. There have been many updates but still this is not fixed. What is the point of setting anchor points if it is not going to effect how different things work for the quest tracker? This functionality was working fine in Classic and TBC, it broke with Wrath and would be greatly appreciated if it was fixed seeing how we are in Phase 2 already.

**Comment by Dyaxler** [comment]
This will be resolved in the up-and-coming Tracker update... along with TONS of other fixes.

Ohhh... you just reminded me to look at the Durability stuff. That hasn't been updated since the early days of Classic WoW. *ducks*
