### ISSUE TITLE
Questie Nameplate Target Frame Quest Objectives

### ISSUE THREAD

**Issue by BalurPoco** [Questie/Questie#4765]
Questie Nameplate **Target** Frame Quest Objectives icon is not visible until the Nameplate Objectives are turned on. I think they should operate independetly. Target Frame Objectives are on, but I don't need the Nameplate one.

I changed line 127 in QuestieNameplate.lua to "if (not Questie.db.global.nameplateTargetFrameEnabled) then".
Seems working for now, please consider it for your next version.

Addon version: Questie 7.5.2
Game version: WoW WotLK Classic

![with_the_line_fix](https://user-images.githubusercontent.com/13569942/233256436-8028154d-b5f8-48ff-8fd5-c6c7566a1a91.png)

**Comment by BreakBB** [comment]
Oh wow, thanks @BalurPoco that is a good catch and also the proper solution! You are totally right that Nameplates and TargetFrames should work independently! 👍🏻 We'll see to get this fix out into our next release and also credit you for it 🥳

**Comment by BalurPoco** [comment]
Cheers! Thank you for the quick respond. 👍
