### ISSUE TITLE
Take Their Rear! (12216) is not putting loot icones on nameplates

### ISSUE THREAD

**Issue by Cabro** [Questie/Questie#4767]
This is a weird one, tooltip shows just fine the # of Grizzly Flanks, but it's not populating the nameplate with loot icon.

**Comment by BreakBB** [comment]
Hey @Cabro do you remember if you checked multiple mobs for this? This could be related to #3048

**Comment by Cabro** [comment]
The bears were all spread around, you had to run distances longer than visible nameplate range, so i don't know how it was related. That bug is for not applying nameplate icons to nameplates already in visible range.

**Comment by BreakBB** [comment]
Yeah then it's not related. Strange though 🤔

**Comment by Cabro** [comment]
Fixed in https://github.com/Questie/Questie/pull/5080/commits/7662471c62f3a675a56e08b53e07d30fbea01a45
