### ISSUE TITLE
Questie Tracker Save Globally LUA error

### ISSUE THREAD

**Issue by EvilMerc** [Questie/Questie#4777]
On version 8.0

Changing the option to Save Tracker (Global) results in the following LUA error, and the Tracker disappearing:

2x Questie/Modules/Tracker/TrackerBaseFrame.lua:262: attempt to index field '?' (a nil value)
[string "@Questie/Modules/Tracker/TrackerBaseFrame.lua"]:262: in function `SetSafePoint'
[string "@Questie/Modules/Tracker/QuestieTracker.lua"]:273: in function `ResetLocation'
[string "@Questie/Modules/Options/TrackerTab/QuestieOptionsTracker.lua"]:499: in function <...Modules/Options/TrackerTab/QuestieOptionsTracker.lua:491>
[string "=[C]"]: ?
[string "@Altoholic/libs/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:45: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:43>
[string "@Altoholic/libs/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:836: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:658>
[string "=[C]"]: ?
[string "@AI_VoiceOver/Libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:66: in function <...eAI_VoiceOver/Libs/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@AI_VoiceOver/Libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@AI_VoiceOver/Libs/AceGUI-3.0-41/widgets/AceGUIWidget-Button.lua"]:22: in function <...Over/Libs/AceGUI-3.0/widgets/AceGUIWidget-Button.lua:19>

Using /questie tracker to enable tracker then reloads the game (not sure if this is intended)

**Comment by BreakBB** [comment]
Hey @EvilMerc thanks for reporting this. Looks like we didn‘t test the global/per character option enough. We‘ll look into a fix!

**Comment by Dyaxler** [comment]
Wait... sounds like there are two "askes" here.

The error message... and the Enable/Disable button?

I can't repro the error to save my life... unless it's a migration issue only for users who are upgrading to the new version.

As far as the slash handler (/questie tracker) - @BreakBB I thought the Enable/Disable button and the slash handler were tied together?

I just need to know what the expected behavior is... because technically both were broken. The button in Questie Config --> Tracker never really disabled the tracker properly. It sort of hid the tracker but that was an unintended side effect. When I reviewed the code, both were basically doing the same thing, so I assumed they were the same option or resulted in the same behavior.

I can separate the two and make the slash handler simply hide the tracker completely without disabling it.

**Comment by Dyaxler** [comment]
@EvilMerc in case you missed it, I fixed the slash handler for you.

Are you able to repro this issue? Is this WotLK or Classic WoW?

**Comment by EvilMerc** [comment]
Hi @Dyaxler thanks for looking in.

This is in WOTLK.

Still receiving this error upon toggling Save Tracker between Character and Global:

.../AddOns/Questie/Modules/Tracker/TrackerBaseFrame.lua:262: attempt to index field '?' (a nil value)
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "@Interface/AddOns/Questie/Modules/Tracker/TrackerBaseFrame.lua"]:262: in function `SetSafePoint'
[string "@Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua"]:254: in function `ResetLocation'
[string "@Interface/AddOns/Questie/Modules/Options/TrackerTab/QuestieOptionsTracker.lua"]:499: in function <...Modules/Options/TrackerTab/QuestieOptionsTracker.lua:491>
[string "=[C]"]: ?
[string "@Interface/AddOns/Altoholic/libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:45: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:43>
[string "@Interface/AddOns/Altoholic/libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:836: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:658>
[string "=[C]"]: ?
[string "@Interface/AddOns/AI_VoiceOver/Libs/AceGUI-3.0/AceGUI-3.0.lua"]:66: in function <...e/AddOns/AI_VoiceOver/Libs/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@Interface/AddOns/AI_VoiceOver/Libs/AceGUI-3.0/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@Interface/AddOns/AI_VoiceOver/Libs/AceGUI-3.0/widgets/AceGUIWidget-Button.lua"]:22: in function <...Over/Libs/AceGUI-3.0/widgets/AceGUIWidget-Button.lua:19>

**Comment by EvilMerc** [comment]
Can confirm the slash command no longer forces UI reset though.

**Comment by Dyaxler** [comment]
Do me a favor... when the error comes back up. Type this into chat...

`/dump Questie.db[Questie.db.global.questieTLoc].trackerSetpoint`

**Comment by EvilMerc** [comment]
[01:37:12] Dump: value=Questie.db.global.questieTLoc
[01:37:12] [1]="char"

[01:37:48] Dump: value=Questie.db[Questie.db.global.questieTLoc].trackerSetpoint
[01:37:48] [1]="AUTO"

**Comment by Dyaxler** [comment]
"AUTO" there it is....

Okie... for some reason the migration function didn't run for you when you upgraded to the new version. Not sure why...

To fix your issue, run this...

'/script Questie.db[Questie.db.global.questieTLoc].trackerSetpoint = "TOPLEFT"`

If the error persists, then you have something going on with your SavedVariables file. The above script SHOULD correct it. If not then you'll need to exit the game entirely. Find the file in: `.\World of Warcraft\_classic_\WTF\Account\%YOURACCOUNTNAME%\SavedVariables\Questie.lua` - you can open it with just Notepad. Do a search for `["trackerSetpoint"] = "AUTO",` and replace it with `["trackerSetpoint"] = "TOPLEFT",` (this is the default value).

Log back in and the button should toggle back and forth without error.

**Comment by EvilMerc** [comment]
This has sorted it, thanks!
