### ISSUE TITLE
Tracker text outline no longer working as of new release

### ISSUE THREAD

**Issue by theoriginalmre** [Questie/Questie#4779]
v8.0.0 WotLK Classic version

The text outline/monochrome feature on the quest tracker no longer does anything. All quests are appearing with no outline.

**Comment by Dyaxler** [comment]
Hmm... sorry about that. I WAS working a week ago. I'll take a look.

**Comment by Dyaxler** [comment]
Fix submitted:
https://github.com/Questie/Questie/commit/eb6287b2da75519d0cc69618dea5ccbea38213b0
