### ISSUE TITLE
Hide completed achieve objectives setting should probably be turned on by default

### ISSUE THREAD

**Issue by Offroads** [Questie/Questie#4780]
## Description
Questie Options --> Tracker, "Hide Completed Achieve Objectives" setting should probably be turned on by default.
I was about to submit a bug report because the tracker was showing completed objectives, then I found this setting.
Doesn't make much sense to list completed objectives if you want to track your progress in an achievement.

## Questie & WoW version
Questie v8.0.0
Wotlk classic eu client 3.4.1.48632

**Comment by Dyaxler** [comment]
Some people would want that turned on by default. This is why it's an option to hide it. :)

**Comment by Offroads** [comment]
An example, working on the Bloody Rare achievement:
![image](https://user-images.githubusercontent.com/28876369/233854013-04686827-fb05-4c0c-b184-df8c4d9df08f.png)
vs 
![image](https://user-images.githubusercontent.com/28876369/233854021-c5a810e8-d2d5-43f8-af18-88653704afca.png)
![image](https://user-images.githubusercontent.com/28876369/233854040-e57720e8-80bb-48c9-8e62-861e2c496498.png)

**Comment by Cabro** [comment]
Hey, I thought there were different options for achievements and quests completed objectives?

**Comment by Offroads** [comment]
> Hey, I thought there were different options for achievements and quests completed objectives? In your original bug report you say Quest Objectives, and then you show Achievement Objectives?

I meant Questie Options --> Tracker, "Hide Completed Achieve Objectives". Copypasted the wrong part from changelog.

**Comment by Dyaxler** [comment]
For consistency's sake the team feels that this option should remain off by default to match the Hide Completed Quest Objectives default option.
