### ISSUE TITLE
Latest version of questie hides item numbers

### ISSUE THREAD

**Issue by TonyJanx** [Questie/Questie#4781]
Classic WoW

I am running 7.5.2 as the latest version has a bug where the objectives show but not the number (below image shows what is missing from the latest version
This issue came about after I installed another addon (I have forgotten what I added).
![image](https://user-images.githubusercontent.com/131610054/233854010-d63a55f7-be59-4160-84d3-544d4d4a4031.png)

**Comment by BreakBB** [comment]
Hey @TonyJanx this should only be the case for items where you need just 1 item. But personally I forgot that not all users are coloring their objectives and therefore leaving out 0/1 and 1/1 is not clear.

**Comment by TonyJanx** [comment]
Ah, I see. So is this a fix I need to do on my side or yours?

Best Regards
T.N.
Head Financial Analyst
www.financialjuice.com/home
FinancialJuice

**Comment by Dyaxler** [comment]
Oh... right. There is a color profile where the objectives don't get "colored" based on completion percentage. Hmmmm... I could force it to turn green for that color profile specifically. Thoughts?

**Comment by BreakBB** [comment]
@Dyaxler I think we should either start showing `0/1` again or only when the coloring is the default "white". For consistency we should just start showing it again.

**Comment by TonyJanx** [comment]
Start showing the 0/1 again, visually it's very useful 😀

Best Regards
T.N
***@***.***
FinancialJuice Ltd

**Comment by BreakBB** [comment]
This should be the place to change:

https://github.com/Questie/Questie/blob/master/Modules/Tracker/QuestieTracker.lua#L1257

Removing the `or quantityNeeded == 1` should make it behave like before.

**Comment by Dyaxler** [comment]
The issue I have with this is that it'll also show the tags for achievements. It just plain looks HORRIBLE.

However, I do have a proposed fix that'll look nice but ONLY for those using this one specific color profile. Instead of a [1/1] or [0/1] tag... We can add a nice little Green ✓ next to the completed objective.

**Comment by TonyJanx** [comment]
The green tick is good to replace "quest complete", but I also want the
numbers as well so I know how far I am on a quest, or which quest to
prioritize if I have less items or enemies slayed on one

Best Regards
T.N
***@***.***
FinancialJuice Ltd

**Comment by BreakBB** [comment]
Hmmm… On Achievements this might actually looks quite bad because most have `0/1`.

I am not sure what to think about the green checkmark next to it. Most users using the white coloring want the Tracker to look like the Blizzard one. Therefore `0/1` seems quite important to me.

I think we should at least first reintroduce the numbers for quests and then think about a solution for Achievements.

**Comment by TonyJanx** [comment]
What's the difference between the colour profiles? I've never come across
that.

Best Regards
T.N
***@***.***
FinancialJuice Ltd

**Comment by Dyaxler** [comment]
![image](https://user-images.githubusercontent.com/17400948/234048379-c33d3a4f-68c3-4656-b38b-674a1712827a.png)

Quest Titles are always colored by difficulty
White =  Objectives are always White
Red to Green = Objectives fade from Red --> Green
White to Green = Objectives fade from White --> Green
White and Green = Objectives DON'T fade but incomplete Objectives are White and Complete Objectives are Green

**Comment by Dyaxler** [comment]
The White profile is the only one without a color transition. So instead of [1/1] meaning that Objective is complete... replace it with a Green ✓ or White. I have no preference on that. For Objectives with more than one "count" the numbers will always be there.

**Comment by TonyJanx** [comment]
[image: image.png]

A rough idea of what I would like to see

Best Regards
T.N.
Head Financial Analyst
www.financialjuice.com/home
FinancialJuice

**Comment by MyTechnoHunter** [comment]
pic not  attached.. try again?

**Comment by TonyJanx** [comment]
![WowClassic_5w8iyuMHib](https://user-images.githubusercontent.com/131610054/234070771-55695e85-1c8b-4f28-927a-c85ede7a2f00.png)

So this is a rough idea, of course the ticks would be smaller, and it keeps the numbers

**Comment by MyTechnoHunter** [comment]
so, as mentioned.. it  _should_ show any objectives with more than one required. the only part that would be changed is a checkmark (at the end of the objective) when the objective is complete

numbers still show on objectives that have more than one required

**Comment by TonyJanx** [comment]
Nice, thank you for your help.

So I should be able to update it to the latest version with these changes?

Best Regards
T.N.
Head Financial Analyst
www.financialjuice.com/home
FinancialJuice

**Comment by Dyaxler** [comment]
@MyTechnoHunter exactly!

The Check Mark won't be THAT big but you guys get the general idea. I think it looks kind of cool actually. But only for that color profile. It's kind of redundant for the color profiles that changes color as the player completes the Objective.

**Comment by Dyaxler** [comment]
@TonyJanx Just hammering out the details. I'm not the "final say" on these matters. @BreakBB is essentially our Product Manager.

**Comment by MyTechnoHunter** [comment]
work is in progress to fix it :) the newest release (hotfix) _when_ it's released, should address it

**Comment by BreakBB** [comment]
> @BreakBB is essentially our Product Manager.

@Dyaxler hahaha, I am not and I also don't want to be 😛 This is a community project, I am just one of the _regulars_ handing around and trying to keep things in the best shape possible 😬

**Comment by BreakBB** [comment]
> This should be the place to change:
> 
> https://github.com/Questie/Questie/blob/33db92ac3dbb1bb5a8428e793f8eb2fc065f6cfc/Modules/Tracker/QuestieTracker.lua#L1257
> 
> Removing the `or quantityNeeded == 1` should make it behave like before.

That part is for the Achievements and shouldn't be changed. I'll propse a fix as PR.
