### ISSUE TITLE
Tracker is Not Expanding Horizontally

### ISSUE THREAD

**Issue by AugustEverywhere** [Questie/Questie#4782]
## Bug description
I updated to latest Questie this morning and the bottom of the tracker is cutting off and not expanding down completely .  I've added a screenshot to show what I mean.  Also You guys to great work and it is greatly appreciated.

## Screenshots
![questie](https://user-images.githubusercontent.com/91682702/233854544-46e413e5-bc17-40d7-8c82-b2e149d4d862.png)

## Questie & WoW version
This is in WotLK

**Comment by BreakBB** [comment]
Hey @AugustEverywhere you should be able to scroll down that list 🤔

**Comment by MyTechnoHunter** [comment]
Horizontally is wide, vertically is up/down.. did you want it taller or wider?

**Comment by Dyaxler** [comment]
Don't forget there is also a new "Height Ratio" option in Questie Config --> Tracker tab. It's at the bottom of the settings. Might have to scroll down to see it. You can make the tracker higher if you want but at some point, it'll get locked, and scrolling will automatically be enabled.

**Comment by Rock48** [comment]
I believe OP meant vertically. I'm also not able to adjust the height any more using the corner. I found the new setting and adjusted it there but it's quite out of the way.

**Comment by MyTechnoHunter** [comment]
running into non drag taller myself, question. do you guys have bugsack/buggrabber installed? if so, are there any bugs reported? if not.. can you get them (both addons are in the curseforge client)

**Comment by Dyaxler** [comment]
> I believe OP meant vertically. I'm also not able to adjust the height any more using the corner. I found the new setting and adjusted it there but it's quite out of the way.

The Sizer was never able to adjust the height. It has and always will be hardcoded to only move right. However, it might "appear" that it adjusts the height when making the tracker narrower or wider and the trackers height might get pushed vertically during each update.

**Comment by MyTechnoHunter** [comment]
> I believe OP meant vertically. I'm also not able to adjust the height any more using the corner. I found the new setting and adjusted it there but it's quite out of the way.

for those wondering, the setting mentioned lives here 
![image](https://user-images.githubusercontent.com/55214545/233863276-c9da9176-cf54-4965-9fba-ce39b70d908a.png)

**Comment by AugustEverywhere** [comment]
So yes I meant vertically grow automatically.  Previous version you could NOT scroll and it would grow down and shrink up as you opened and closed quests.  I lock the tracker in place and when I updated the bottom was cutoff but now I see I can scroll which didn't used to happen so I guess there's no bug but I hate having to scroll.

**Comment by BreakBB** [comment]
You should still be able to set a fixed height, right @Dyaxler ?

Maybe we should also add an option to disable the scrolling 🤔

**Comment by Dyaxler** [comment]
The Tracker Height Ratio does allow you to make the tracker taller. Min = 20% of the players vertical screen resolution and Max is 100%.

In order to allow a "Disable Scrolling" option, I'd have to code in a limiter to not allow adding anymore Quests and Achieves to be added to the tracker... or just silently not display them like the Blizzard Quest Watch frame does.

However, if a player sets the Ratio to 100%... then they can decide to not add anymore Quests or Achieves to the tracker when their screen fills up. If they stay under the height, then scrolling won't be enabled at all.
