### ISSUE TITLE
Extra line feeds in quest objectives makes spacing large

### ISSUE THREAD

**Issue by MyTechnoHunter** [Questie/Questie#4783]
## Bug description
As the title says, quests with (clues) that have extra line feeds in the text make the tracker spacing larger than it should be

## Screenshots
![image](https://user-images.githubusercontent.com/55214545/233859874-e20bedf8-c819-4eab-8d91-d01037081b5b.png)

## Questie & WoW version
Latest release (8.0) for Questie and Wrath client for WoW

**Comment by Dyaxler** [comment]
Actually, this is a DB issue. Yes, we pulled the data from Blizzard but if you look at the three DB files for this Quest:
.\Questie\Database\Classic\classicQuestDB.lua
.\Questie\Database\TBC\tbcQuestDB.lua
.\Questie\Database\Wotlk\wotlkQuestDB.lua

...you'll see that the extra lines are in the DB.

`[453] = {"Finding the Shadowy Figure",{{273}},{{288}},20,25,1101,nil,{"Find the Shadowy Figure. Your clues:","","He is not native to Darkshire.","","He is a nervous, jittery person.","","He left Darkshire and headed west."},nil,nil,2161,nil,{266},nil,nil,nil,10,nil,nil,nil,nil,268,nil,nil,nil,{{72,75}}},`

You could dress it up a bit more and add some * before each clue to simulate bullet points.

**Comment by drejjmit** [comment]
I assume this quest is complete and shows up on the map as complete? 
So that text would be the new "complete" text? 
And since you don't have green complete text it's not very clear that it's completed.
Maybe we should add (Complete) in the quest title when default "Quest complete" text isn't shown? 
To make it clearer

**Comment by MyTechnoHunter** [comment]
so then, how to fix it? db change or handling it via tracker complete things?

**Comment by Dyaxler** [comment]
Yeah... let's not fool with the DB data then. That would screw up the tooltips. I'll fix it on the Tracker side.

**Comment by Dyaxler** [comment]
Got it... :)

![image](https://user-images.githubusercontent.com/17400948/235310158-a9dbdb65-c82e-4a53-8e3d-c454e2d8771a.png)
