### ISSUE TITLE
It's a Mistake to turn Questie Branding off by Default

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#4786]
I had to turn this back on, by default it was off. That's a mistake long-term.

How many hundreds of thousands have you guys made on this? Come on, respect the brand.

Tracker should just say "Questie" and that should be on by default. "Tracker" is redundant here.

![image](https://user-images.githubusercontent.com/55365231/233889311-0f9192fc-6508-453f-a6d2-a2e75085fe51.png)

**Comment by Dyaxler** [comment]
Hmmm... good point about tooltips in general. I really should put a Tooltip on the Sizer nub and if the Header is disabled, then maybe add a note about the other stuff. I dunno... we'll have to discuss that internally.

As far as the header is concerned... I agree with @BreakBB but I need a little clarification. Which default value are you referring to that we need to revert?

"Tracker should just say "Questie" and that should be on by default. "Tracker" is redundant here."

This label has been titled "Questie Tracker" for as long as I can remember... it's never been changed. Unless you're referring to the Tracker Header being off by default?

I just looked at the QuestieOptionsDefaults table to make sure but the trackerHeaderEnabled key is flagged true. But the new option "Always Show Tracker" is flagged false so it's off by default. This new option will not affect the behavior of the header unless the player disables the Tracker Header option.

**Comment by BreakBB** [comment]
@Dyaxler the option that we switched to `false` as default is `Questie.db.global.currentHeaderEnabledSetting` which refers to the "Enable Active Quests Header".

https://github.com/Questie/Questie/blob/dd4b24e392e5bdd5d04d6dfb0c5c201e9de3d876/Modules/Options/QuestieOptionsDefaults.lua#L88

and

https://github.com/Questie/Questie/blob/dd4b24e392e5bdd5d04d6dfb0c5c201e9de3d876/Modules/Migration.lua#L203-L205

**Comment by Dyaxler** [comment]
Oh yes... please don't touch that. That will flip the header on and off and it's tied to the "Always Show Tracker" option.

In short, if the header is disabled by the player and "Always Show Tracker" is enabled then it'll "remember" the players original option to have the header disabled. So it knows to switch it back off when the player tracks a quest.

**Comment by MyTechnoHunter** [comment]
> Oh yes... please don't touch that. That will flip the header on and off and it's tied to the "Always Show Tracker" option.
> 
> In short, if the header is disabled by the player and "Always Show Tracker" is enabled then it'll "remember" the players original option to have the header disabled. So it knows to switch it back off when the player tracks a quest.

don't touch which? both? 

the default needs to be on not off for people that had it on.. saving state for other people that hide things is fine.. changing default isn't
