### ISSUE TITLE
Limit Proximity Tracking by Zone

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#4787]
This would be perfect it it just limited the listed objectives local to the zone the player was currently in.

![image](https://user-images.githubusercontent.com/55365231/233889687-861077e8-09a5-4bff-ae3c-c988b917e6b2.png)

**Comment by Dyaxler** [comment]
Hmmm... I'll look into it.

**Comment by Dyaxler** [comment]
@Gogo1951 not 100% what you asked for BUT... it will sort the Objectives by Proximity in the Zone you're currently in. Outside your current Zone, it acts just like it would if you just simply used the By Zone Option. But, it will switch Zones when your Zone changes and begin sorting those Quests by Proximity without having to change any settings.

**Comment by Gogo1951** [comment]
Proximity is OK, but still tends to be cluttered.

I want it so only show...

* Quests with objectives in the Zone.
* Quests with turn-ins in the Zone.

Ideally sorted by proximity so I know what to do next based on what's close, OR if that's complicated with mixed turn-in vs. complete proximity... sort the list based on what's left to do up top, and completed quests at the bottom.
