### ISSUE TITLE
Repeating Lua Error when in Dungeons

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#4789]
17x ...faceQuestie/Modules/Tracker/TrackerUtils.lua:460: Usage: local continentID, worldPosition = C_Map.GetWorldPosFromMapPos(uiMapID, mapPosition)
[string "=[C]"]: in function `GetWorldPosFromMapPos'
[string "@Questie/Modules/Tracker/TrackerUtils.lua"]:460: in function <...faceQuestie/Modules/Tracker/TrackerUtils.lua:456>
[string "@Questie/Modules/Tracker/TrackerUtils.lua"]:490: in function <...faceQuestie/Modules/Tracker/TrackerUtils.lua:488>
[string "@Questie/Modules/Tracker/TrackerUtils.lua"]:670: in function `GetSortedQuestIds'
[string "@Questie/Modules/Tracker/QuestieTracker.lua"]:431: in function `Update'
[string "@Questie/Modules/Quest/QuestieQuest.lua"]:559: in function `func'
[string "@Questie/Modules/Libs/QuestieCombatQueue.lua"]:25: in function <...eQuestie/Modules/Libs/QuestieCombatQueue.lua:17>

Locals:
(*temporary) = 302
(*temporary) = nil

**Comment by Gogo1951** [comment]
![image](https://user-images.githubusercontent.com/55365231/233896215-29e3187b-67c2-45c4-a280-37b55c555f1b.png)

Happened over 2k times in On Run.

**Comment by BreakBB** [comment]
Which dungeon was it @Gogo1951 ?

**Comment by drejjmit** [comment]
Was this with the "By Proximity" tracker option enabled?

**Comment by Gogo1951** [comment]
> Was this with the "By Proximity" tracker option enabled?

Probably. I was playing with that setting at the time.
