### ISSUE TITLE
Ghost tracker due to combat starting before Questie finishes initializing.

### ISSUE THREAD

**Issue by Cabro** [Questie/Questie#4793]
Not 100% sure that this is what causes this bug. Logged inside a dungeon and combat started before Questie finished initializing.
Noticed some achievements were not tracked anymore, and when i tracked one, then this mess happened.

![img](https://imgur.com/OPzm8cK.png)

8.0.0

**Comment by Dyaxler** [comment]
Sigh... looks like I'll be playing in the Stockades today.
