### ISSUE TITLE
Achievement tracking is not helpful on default "white" coloring for single objectives

### ISSUE THREAD

**Issue by BreakBB** [Questie/Questie#4798]
## Bug description

All objectives with just 1 quantity needed are shown as plain text, in contrast to `0/1` or `1/1`. This is only an issue when the Tracker coloring is set to "white".

## Screenshots

![grafik](https://user-images.githubusercontent.com/33514570/234102880-53550984-47f2-4a72-af4c-3b59fd10dfbb.png)

## Questie & WoW version

v8.0.0

**Comment by Dyaxler** [comment]
Update - awaiting final approval from team. :)

![image](https://user-images.githubusercontent.com/17400948/234350851-5cfeeaa2-2853-482c-92ab-18efc909be4e.png)

**Comment by Dyaxler** [comment]
The Check marks will only appear when a player is using the "White" Objective Color profile AND Hide Complete Achievement Objectives is Disabled (unchecked - showing both complete and incomplete objectives).
