### ISSUE TITLE
Lua Error while Questing

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#4800]
1x ...ceQuestie/Modules/Tracker/QuestieTracker.lua:1464: attempt to perform arithmetic on a nil value
[string "@Questie/Modules/Tracker/QuestieTracker.lua"]:1464: in function `UpdateFormatting'
[string "@Questie/Modules/Tracker/QuestieTracker.lua"]:1381: in function `Update'
[string "@Questie/Modules/Tracker/TrackerUtils.lua"]:760: in function `func'
[string "@Questie/Modules/Libs/QuestieCombatQueue.lua"]:25: in function <...eQuestie/Modules/Libs/QuestieCombatQueue.lua:17>

Locals:
self = <table> {
 UpdateAchieveTrackerCache = <function> defined @Questie/Modules/Tracker/QuestieTracker.lua:1834
 MoveDurabilityFrame = <function> defined @Questie/Modules/Tracker/QuestieTracker.lua:266
 Enable = <function> defined @Questie/Modules/Tracker/QuestieTracker.lua:339
 Expand = <function> defined @Questie/Modules/Tracker/QuestieTracker.lua:387
 IsTrackedAchievement = <function> defined =[C]:-1
 UIPanelScrollBar_OnValueChanged = <function> defined @SharedXML/SecureUIPanelTemplates.lua:63
 RemoveQuestWatch = <function> defined @Questie/Modules/Tracker/QuestieTracker.lua:1695
 started = true
 alreadyHooked = true
 AQW_Insert = <function> defined @Questie/Modules/Tracker/QuestieTracker.lua:1748
 UntrackAchieveId = <function> defined @Questie/Modules/Tracker/QuestieTracker.lua:1866
 Initialize = <function> defined @Questie/Modules/Tracker/QuestieTracker.lua:65
 GetNumTrackedAchievements = <function> defined =[C]:-1
 Disable = <function> defined @Questie/Modules/Tracker/QuestieTracker.lua:351
 GetNumQuestWatches = <function> defined =[C]:-1
 RemoveTrackedAchievement = <function> defined @Questie/Modules/Tracker/QuestieTracker.lua:1819
 Unhook = <function> defined @Questie/Modules/Tracker/QuestieTracker.lua:1518
 RemoveQuest = <function> defined @Questie/Modules/Tracker/QuestieTracker.lua:1680
 UntrackQuestId = <function> defined @Questie/Modules/Tracker/QuestieTracker.lua:1719
 QuestItemLooted = <function> defined @Questie/Modules/Tracker/QuestieTracker.lua:301
 private = <table> {
 }
 CheckDurabilityAlertStatus = <function> defined @Questie/Modules/Tracker/QuestieTracker.lua:282
 alreadyHookedSecure = true
 last_aqw = 26
 HookBaseTracker = <function> defined @Questie/Modules/Tracker/QuestieTracker.lua:1549
 UpdateFormatting = <function> defined @Questie/Modules/Tracker/QuestieTracker.lua:1429
 Update = <function> defined @Questie/Modules/Tracker/QuestieTracker.lua:394
 HasQuest = <function> defined @Questie/Modules/Tracker/QuestieTracker.lua:319
 Toggle = <function> defined @Questie/Modules/Tracker/QuestieTracker.lua:368
 Collapse = <function> defined @Questie/Modules/Tracker/QuestieTracker.lua:379
 TrackAchieve = <function> defined @Questie/Modules/Tracker/QuestieTracker.lua:1873
 UpdateWidth = <function> defined @Questie/Modules/Tracker/QuestieTracker.lua:1496
 IsQuestWatched = <function> defined =[C]:-1
 ResetDurabilityFrame = <function> defined @Questie/Modules/Tracker/QuestieTracker.lua:259
 ResetLocation = <function> defined @Questie/Modules/Tracker/QuestieTracker.lua:244
}
trackerVarsCombined = 305
(*temporary) = <function> defined =[C]:-1
(*temporary) = Frame {
 0 = <userdata>
}
(*temporary) = 305
(*temporary) = nil
(*temporary) = nil
(*temporary) = Button {
 0 = <userdata>
 SetVerticalPadding = <function> defined @Questie/Modules/Tracker/TrackerLinePool.lua:151
 SetQuest = <function> defined @Questie/Modules/Tracker/TrackerLinePool.lua:95
 SetMode = <function> defined @Questie/Modules/Tracker/TrackerLinePool.lua:920
 expandZone = Button {
 }
 SetZone = <function> defined @Questie/Modules/Tracker/TrackerLinePool.lua:86
 label = FontString {
 }
 SetObjective = <function> defined @Questie/Modules/Tracker/TrackerLinePool.lua:113
 SetOnClick = <function> defined @Questie/Modules/Tracker/TrackerLinePool.lua:165
 expandQuest = Button {
 }
 mode = "zone"
 OnUpdate = <function> defined @Questie/Modules/Tracker/TrackerLinePool.lua:117
}
(*temporary) = "attempt to perform arithmetic on a nil value"
allowFormattingUpdate = true
TrackerLinePool = <table> {
 GetLine = <funct

**Comment by Gogo1951** [comment]
Looting a quest object while in combat?

**Comment by Dyaxler** [comment]
Classic wow?

**Comment by Gogo1951** [comment]
Wrath Classic.

**Comment by Dyaxler** [comment]
Based on your debug stack `[string "@Questie/Modules/Tracker/TrackerUtils.lua"]:760: in function `func'`

This line in within the questProximityTimer where QuestieTracker:Update() is called. It's also wrapped in the CombatQueue so it wouldn't have fired an update while in combat.

I goofed with this on a new toon for several quests while using the Proximity sort feature. No issues...

**Comment by Dyaxler** [comment]
There was another bug I just fixed that pertained to the Sort by Proximity. Maybe my fix fixes this one too. I can't tell how it was triggered simply by looking at the debug stack. There was also an issue where the tracker was being updated and WHILE it was updating, player enters combat, and the tracker goes nuts. I.E. starts painting duplicate entries. I just fixed this one too. It looked like one issue, but it was in fact two separate issues.

**Comment by Gogo1951** [comment]
Thanks!

**Comment by Dyaxler** [comment]
@Gogo1951 new version of Questie is out. Please retest. :)

**Comment by Gogo1951** [comment]
I didn't seen this bug yesterday. Cheers!
