### ISSUE TITLE
The Corrupter Icon Spam

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#4801]
![image](https://user-images.githubusercontent.com/55365231/234138775-278f94f9-7b64-4ca0-9b75-80c61426f0b7.png)

**Comment by Gogo1951** [comment]
I had all the non-spammy quests that dropped added. There are 2 that are spammy even. =P But now it seems someone added all the spammy ones... it was not an accident that these were avoided.

**Comment by BreakBB** [comment]
Actually this quest is shown on purpose.

**Comment by Gogo1951** [comment]
![image](https://user-images.githubusercontent.com/55365231/235205871-fd93d1ba-cd16-4e3c-87f2-e0d19622b834.png)

Really?

**Comment by BreakBB** [comment]
I actually didn't check all available spawns, just the git history on this. You are right, these are way too many icons to show.
