### ISSUE TITLE
Tracker excessive space to the right

### ISSUE THREAD

**Issue by Cabro** [Questie/Questie#4805]
This change is 100% with the new tracker.
There is excessive space on the right side of the tracker when using the autosizer nub.
There used to be a few pixels so you don't have stuff on the edge outline, but now there's like a third of the text as empty space.

![image](https://user-images.githubusercontent.com/1155017/234228023-252eb7de-8da5-41d7-a0a7-5da4e1f45622.png)

 8.0.1

**Comment by Dyaxler** [comment]
I have those two Drak'Tharon Keep quests too. They both contain very verbose completion text and are wrapped. Untrack those two quests. Does the tracker shrink back to normal?

**Comment by Dyaxler** [comment]
I thought it was that... I think I put the "minTrackerWidth" var in the wrong place. :D I'll fix it.

**Comment by Cabro** [comment]
Good thing you fix it, because i think that extra space carries over to other chars when using global settings.
