### ISSUE TITLE
Prerequsite Items Don't Show in Name Plate Icon

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#4808]
![image](https://user-images.githubusercontent.com/55365231/234376935-cbf2a446-0672-4ac9-939c-9b0efc38bf2d.png)

![image](https://user-images.githubusercontent.com/55365231/234376979-cd2f86f4-42e3-4e6e-a291-d3ef0835bc19.png)

**Comment by MyTechnoHunter** [comment]
did it ever? i know objective type like a bag for loot showed.. a sword for killing, so on, so forth..

**Comment by Gogo1951** [comment]
Yes, it did.

**Comment by Cabro** [comment]
This should be fixed after the extraObjective fixes dyaxler did a while ago
