### ISSUE TITLE
What's Next?

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#4811]
Hey Guys,

This is going to be a long post, feel free to close it.

It's about the future, and planning for the future. With Cata Classic being almost a guarantee, you have a TON of changes on the horizon. Supporting Cata Classic, but also most likely Classic Era, and Wrath Classic. (And... while you're at it, why not expand to Retail?)

I worry that you're still relying on sort of unplanned, ad-hoc work to get this stuff done. Doesn't feel like you have a plan in place to ensure success.

And it's disingenuous to say Questie is still a "hobby project" -- it's something a lot of people rely on (just look at all the comments when they open the PTR!), but Questie still needs a lot of TLC. You get what, something like $0.05 per download... with over 60M downloads... you can do the math, but there should be budget and priority to get this right, y'know? Candidly, most of the time it feels like you're just coasting.

Questie is the best add-on for WoW. Period. And it still has a very high usage rate, but along with that comes the responsibility to make questing as fun and efficient as it can be. Give people that confidence they can go out and clear a zone fast and have fun doing it... that's what you've been struggling to deliver. It feels like you guys are saying, "Oh we built this thing, and we don't really care if it works (see the huge amount of open bugs), and we don't even really play or level much... so it just sort of is what it is. Deal with it." That's what it feels like.

But what experience do you want people in the WoW community to have? How do you want to shape the game we all love? You have the opportunity. Do you want people to enjoy questing? Leveling alts? Keeping the game alive? Do you want them to race to 85? Or complete Loremaster? Quest in a group? You can build all those tools! And what you build influences how people play.

So take that as you will, but here's a bunch of stuff that needs to get done to keep Questie healthy.

## Questie Needs More Testing

- The new tracker was buggy at launch. And not to harp, but Questie at WotLK Launch was abysmal for data quality. Just unusable really. I know that a few people on the team have been updating quests, and it's gotten a lot better, but man... these rough launches really damage the reputation. It feels like you aren't putting this stuff through adequate testing.

- It's good to see the new tracker was in code review for a long time, but please remember that code review isn't a replacement for manual testing.

- Setting up the Beta Release Channel would really help. Feels like that effort to automate releases died on the vine. What is going on with the BigWigs Packager?

- Having a team of testers, and releasing a version to them to test for a week before you release it to the public, that would help too.

- Having a dedicated team of testers, assigned a class or a zone, would help. Get 20 people, have everyone be responsible for a class + faction combo... like I did for TBC, that would really help. You have a community of people who you can pull from.

- Having everyone on the team level a new toon... I don't get the sense that any of you actively quest... the number of bugs per zone is still high, I'd estimate 5-15 bugs per zone just in data, pathing, missing quests.

- You should all be playing more on the PTR. Once a week. Log in, do 1 quest, you'll catch more bugs.

## Questie Needs Better UX Design & Planning

- It doesn't feel like you're experimenting with all the other add-ons out there. Kaliel's Tracker would be a good place to start. RestedXP, Dugi, Zygor, Immersion, and VoiceOver all have good ideas. Questie should pull more inspiration from the best and brightest. Even the questing interface in Retail -- out of the box Retail -- has stuff you can pull from.

> Aero even built the prototype for something like VoiceOver in June of 2022! (= 
> [testquest.zip](https://github.com/Questie/Questie/files/11326921/testquest.zip)

- Suggest people use [Whimsical](https://whimsical.com/) or Figma to mock something up before they build it... float those designs out, and get feedback. Those can be free tools, and the cost of building and tweaking -- that's the least efficient / most expensive way to develop anything. Working with layout in the game is hard, I get that, but a lot of the stuff seems like it was built in a silo, or built the "easiest way" and not the correct way for most users.

- As much work as you do on Code Review... try just doing 1/2 that in UX Design. (=

- Developers make the WORST designers. Why? Because they have to understand everything to build it... but what gets built should be simple enough to use that nobody has to understand anything to use it. People do a horrible job of understanding things that they don't understand, and I get that once you understand things the Options Interface makes sense... but I'm telling you it's REALLY REALLY bad for most users. Everything about it is confusing.

- I don't mean for this to sound negative, I know it was a lot of work to re-do the tracker. And that's sort of my point... It's really a shame that the new tracker hasn't had any significant features added to it. The default tracker in WoW supports all the stuff you just added, in terms of achievements. It even handles "clickable" items better. Given Aero build a dynamic tracker in the Routes branch, at least a partial one, I wonder what the target for the rebuild was... was it just to add achievement tracking? Dunno, feels like with as much dev time as went into it, the goals could have been more ambitious. I don't really see any meaningful changes that would make me switch back.

- Specifically, it'd be great to have the option to filter to only show objectives in the current zone, or automatically showing achievements for the current zone... giving the users focus... that'd be really cool. Focus makes users think less about finding what to track... let's them focus on having fun.

## Preparing for Cata

- When I went to get people access to the beta for Wrath, it came back that very few of you had active subscriptions. My suggestion would be to use some of the money you get from CurseForge to make sure everyone has a subscription, yeah? And build your own connections so you get early Beta Access. (I'm pretty sure Blizzard would even spot you guys subscriptions if you asked nicely.)

- Cata will be a huge reset. That means replacing all of your data. You need to find better sources, and a better way to sync multiple sources so you can automate some of the cleanup, and a better way to manually clean up data. CMANGOS is crap, we all know this. You can't rely on it alone. I'd hit up WoWHead, and Blizzard, and start seeing if you can build partnerships to get access to better data.

- It would be a total shame if you go into Cata Classic and have a launch anywhere near as bad as it was for Wrath. Wrath just felt like you didn't care, didn't play it yourselves, hadn't tested anything, everyone felt it.

## Global Profiles / Local Profiles

- The Options Interface is so confusing, buggy, and doesn't take into account things like 4k monitors, or users who want larger fonts / play at a non-default UI Scale. And it's just all over the place.

- Profiles are so buggy. This has been buggy since Classic. You don't use the "standard" way of doing profiles that other add-ons like Elv or DBM use. Moving to a format where you have global settings, and character-specific data would be good.

- Nobody with alts wants to set things up on a per character basis. Set it up once, have it inherit. The default should be "Global" and if someone wants a local profile, they can set that up -- instead of making someone navigate the settings, and push a button (which follows no UX convention) to toggle between Local and Global (it should be a drop down, not a button).

- An example of "buggy" -- the new tracker turned itself on for all users in the last release. That's fair, new functionality should be defaulted on so people can learn about it. But even with the tracker set to "global" you have to go character-by-character to disable it. Oof. And Questie load times are painful.

## Working With Others

- I get you don't want to make this your day jobs... but how about reaching out to other add-on devs and asking them to join the team, or license their work. 

- DoubleWide was a great example of code that would have fit perfectly into Questie. Kaliel's Tracker would have fit in nicely too... curious if you guys ever bother to reach out to other devs... seems like it'd be a good move. "Hey, we have a user base, you have a great add-on... let's merge your code in..."

- Setting up some tiers on the Discord would even help... "Tier 1... you donated $50 a month, or closed 5 bugs / month" ... "Tier 2... you donated $100 / month or closed 10 bugs / month..." -- and then just give people some in-game recognition in the form of a thank you page, or in-game tooltip. Easy wins. Easy to build some pretty cool rewards for people engaging with you... "Questie Tester" would be a great tag-line on a player tooltip, no? Doesn't cost you anything other than maintaining a list. Many hands make light work.

## Tracker / Misc...

- Tracker Drag Corner should resize, not just adjust width

- The "Use Icons" still interfere with a quest being able to be minimized.

- Adding 2+ items to the list look bad. Take a look at how Kaliel's Tracker does it.

- Game Load Time is getting out of control. Questie adds like 8-12 seconds? My saved variables are 80+ MB. That's batshit. It's 10x larger than anything else I have... and I have a very complex TSM, and Details logs every raid. I suspect most of that is to support the Journey, a feature I would love the ability to turn off because I don't use it. Questie needs optimization.

![image](https://user-images.githubusercontent.com/55365231/234412322-bf5a7c34-76d2-460d-a33f-b8f53c23c896.png)

- Would be great to have the ability to Play Sound on Quest Complete... like Dugi, Zygor, RestedXP, and Kaliel's Tracker have all built in.

### Here are some screenshots around Kaliel's tracker. Hope you can use them for ideas.

Questie & Kaliel side by side in RFC

![image](https://user-images.githubusercontent.com/55365231/234401088-0e66e479-61c7-4299-bb86-647f90377442.png)

Actually... this is how Questie looks.

![image](https://user-images.githubusercontent.com/55365231/234401482-952ecfb1-2aba-416d-a4c3-5f1f3d514d99.png)

Questie & Kaliel side by side in Zul'Drak

![image](https://user-images.githubusercontent.com/55365231/234401232-d4bb9c60-a697-4183-b514-7fda871972de.png)

Questie & Kaliel side by side in Storm Peaks.. you get the idea... 

![image](https://user-images.githubusercontent.com/55365231/234401696-09cb0183-f5b3-46a5-8b56-96ed1def8786.png)

Kaliel's in Dalaran

Note this is all auto-displayed, 0 config out of the box. Instantly tracks stuff you can do.

![image](https://user-images.githubusercontent.com/55365231/234401565-2771427e-2db1-45a1-9b9a-21915739cd38.png)

@AeroScripts
@BreakBB
@drejjmit
@Dyaxler
@Muehe
@MyTechnoHunter
@Yttrium-tYcLief

**Comment by Muehe** [comment]
Look, I'm not going to dignify the entirety of this rant with a reply, because we have been over all this again and again. But this one?

> You get what, something like $0.05 per download... with over 60M downloads... you can do the math, but there should be budget and priority to get this right, y'know? Candidly, most of the time it feels like you're just coasting.

This has to be the epitome of all your harebrained assumptions so far. Let me get this straight, you go to the [Cursforge support page](https://support.curseforge.com/en/support/solutions/articles/9000197902-reward-program-faq) to get this $0.05 figure, fail to see that is says per point and not per download, never stop to think "wait 3 million dollars for Questie alone from CF, that can't be right", and then close your bullshit with yet another passive aggressive insult of our laziness.

Epitomic.

FYI, it's more like 3k$ per year, spread over several people. Which certainly covers a bit more than subscriptions, which is nice, but that's about it.

**Comment by BreakBB** [comment]
Same topic different time...

**IF** we would want Questie to be a great product and earn money with it, then you would be right and we should think about introducing all kind of professionality into the team and workflow.

**BUT** that is not the motivation for the team. We are not investing all of this time in development, support, issue maintenance, etc. for money. Whatever CurseForge is "paying" it would make a shit wage and not close to being enough for a living of a regular person.

Look, we actually want Questie to be a hobby project, something we can hop on and hop off, no responsibility, just having a bit of fun. We love Questie and are happy to work on this fantastic addon, but it is not meant to feel like a real job.

That being said, next time instead of writing up a wall of text like this (again), spin up your IDE to fix a quest issue or two, put your ideas into new feature requests or just leave us be and enjoy the current state of WoW and Questie.
