### ISSUE TITLE
Questie Trackers "Sizer" needs a tooltip

### ISSUE THREAD

**Issue by Dyaxler** [Questie/Questie#4815]
## Description
If the Active Quests Header is disabled by the Player then we lose the "info" tooltip in the ? icon. Additionally, most Players are unaware of the Right-Click feature on the Sizer (resets width back to auto width after manually resizing).

## Add Feature
While the Active Quests Header is disabled, move the tooltip info embedded in the ? icon over to the Sizer and insert additional tooltip info on the Sizers features. If the Active Quests Header is enabled, then the Sizers tooltip will only contain use info pertaining to the Sizers features.

The Sizer tooltip will also tell you if you're in Manual mode or Auto mode.

Another idea I've been playing with is to make a small 5 pixel "bar" at either the top or the bottom of the Tracker (for those that prefer to always hide the Active Quests Header). It'll turn Gold when hovered over (otherwise transparent) and the Tooltip that's embedded in the ? Icon (on the Active Quests Header) will appear there instead of the Sizer. This would give you guys the ability to Min/Max the tracker and have a tool tip and it would be at the top to indicate that Quests are being filled Top --> Down. And vis versa...

**Comment by MyTechnoHunter** [comment]
one thing might be a problem.. most users are setup to hover the top of the tracker for that tooltip.. not many will look in the lower right corner for a tooltip (where the sizer is by default)

**Comment by Dyaxler** [comment]
To clarify... I'm not going to move the "features" the ? icon provided... I.E. Left-Click opens Questie Options and Right-Click opens Journey. Just the info about Left-Click + Hold: Drag while Unlocked and CTRL + Left-Click + Hold: Drag while Locked.

Might have to change the wording a bit to not imply that you have to do all this while hovering over the Sizer. :D

**Comment by BreakBB** [comment]
I already said this at a different place: Moving the `?` icon, when the header is disabled into the first Tracker row and make it stick to the right can also be solution. As an addition to the tooltip for the sizer which explains the sizer only features/shortcuts.

**Comment by Dyaxler** [comment]
![Screenshot 2023-05-04 091700](https://user-images.githubusercontent.com/17400948/236264779-a730236d-78fb-42dc-9236-870feb8c3009.png)

**Comment by Dyaxler** [comment]
Doesn't look HORRIBLE

**Comment by Starlynk1** [comment]
Header is hidden by default with Classic from what I've seen. And it cannot be enabled unless you first uncheck 'Always Show Tracker'. After you 'Enable Active Quests Header' then you can re-enable 'Always Show Tracker'. This seems a bit odd why it doesn't show as default and why you have to disable 'Always Show Tracker' to turn the header on/off.

**Comment by Starlynk1** [comment]
And as a side note, the tooltip "?" could be in the upper right corner whether the header is on or off. This way it is always in the same spot and easily found.

**Comment by Dyaxler** [comment]
I've noticed that some are misinterpreting the "?" icon. It's not a "help" icon in the traditional sense. It's our logo. Same logo we use for the Minimap widget. Sure, it serves as an anchor for a tooltip with helpful info but it's not a "help" menu.
