### ISSUE TITLE
Questie giving repeated tracker LUA errors when using provided quest items left of tracked quests in tracker list

### ISSUE THREAD

**Issue by Erukani** [Questie/Questie#4817]
## Bug description
Since Questie version 8.0.0 and 8.0.1, I have been getting sporadic LUA error popups while doing quests that involve using the item buttons attached to the tracker list for quests. Any other quests seem to be fine for the most part with tracking and completion, but this primarily happens when using one of the item buttons either already in or going into combat as a result of using the quest item. When this happens, in addition to getting the LUA error, it also seems to duplicate any currently tracked quests in the tracker list.

Some of the errors which I received are as follows:

Message: [ADDON_ACTION_BLOCKED] AddOn 'Questie' tried to call the protected function 'Questie_ItemButton4:SetAttribute()'.
Time: Wed Apr 26 13:59:28 2023
Count: 1
Stack: [ADDON_ACTION_BLOCKED] AddOn 'Questie' tried to call the protected function 'Questie_ItemButton4:SetAttribute()'.
[string "@Interface/AddOns/Questie/Modules/Tracker/TrackerLinePool.lua"]:450: in function `SetItem'
[string "@Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua"]:613: in function `Update'
[string "@Interface/AddOns/Questie/Modules/Quest/QuestEventHandler.lua"]:303: in function <...e/AddOns/Questie/Modules/Quest/QuestEventHandler.lua:302>

Locals: <none>

---------------------------------

Message: ...ce/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:1464: attempt to perform arithmetic on a nil value
Time: Wed Apr 26 14:27:57 2023
Count: 4
Stack: ...ce/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:1464: attempt to perform arithmetic on a nil value

Locals: 

-----------------------------------

Message: [ADDON_ACTION_BLOCKED] AddOn 'Questie' tried to call the protected function 'Questie_ItemButton4:Hide()'.
Time: Wed Apr 26 14:32:39 2023
Count: 1
Stack: [ADDON_ACTION_BLOCKED] AddOn 'Questie' tried to call the protected function 'Questie_ItemButton4:Hide()'.
[string "@Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua"]:649: in function `Update'
[string "@Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua"]:313: in function <...ce/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:312>

Locals: <none>

## Screenshots

![Questie_LUA_Error](https://user-images.githubusercontent.com/103777650/234672207-d3d58dc4-6d52-4835-8979-5a55449018fe.jpg)

## Questie & WoW version
Questie v8.0.1 WotLK Classic

**Comment by BreakBB** [comment]
Merging this with #4813 - Thanks for reporting this @Erukani we are already looking for a solution.

**Comment by Dyaxler** [comment]
Gogo's issue and Erukani's issue are two separate issues. :D I'm in the process of fixing this one right now.
