### ISSUE TITLE
trackerQuestFrame LUA Error

### ISSUE THREAD

**Issue by EvilMerc** [Questie/Questie#4818]
WOTLK Classic

Receiving this error on logging into the game/reloading, happens every time:

4x ...ceQuestie/Modules/Tracker/QuestieTracker.lua:1563: attempt to index upvalue 'trackerQuestFrame' (a nil value)
[string "@Questie/Modules/Tracker/QuestieTracker.lua"]:1563: in function <...ceQuestie/Modules/Tracker/QuestieTracker.lua:1561>
[string "=[C]"]: ?

Locals:
(*temporary) = nil
(*temporary) = nil
(*temporary) = "|cff7c83ff[DEVELOP]|r"
(*temporary) = "QuestieTracker:ScrollFrame_OnScrollRangeChanged"
(*temporary) = "attempt to index upvalue 'trackerQuestFrame' (a nil value)"
trackerQuestFrame = nil

This also causes all the minimised quest zones on the tracker to expand out again.

**Comment by MyTechnoHunter** [comment]
Are you fully updated? Daxter fixed this with https://github.com/Questie/Questie/commit/d0fd13708d15ab7ccf2a33bc1b00a29699c379e6

Which should be in 8.0.1 ( pretty sure )

**Comment by EvilMerc** [comment]
Hey yeah I am fully updated on 8.0.1.

I did run the following command as mentioned by Dyaxler to resolve an issue with the tracker:

/script Questie.db[Questie.db.global.questieTLoc].trackerSetpoint = "TOPLEFT"

This error started occuring after that happened.

**Comment by BreakBB** [comment]
The commit you linked is not in v8.0.1 @MyTechnoHunter - But I want to ship another release later today.

**Comment by Dyaxler** [comment]
@EvilMerc Thank you for confirming that my other tip fixed your issue in that other bug...

This bug you're experiencing has been fixed and will be included in the next patch.
