### ISSUE TITLE
The quest "The Heartblood's Strength" is missing an indicator.

### ISSUE THREAD

**Issue by RoanSythen** [Questie/Questie#4824]
## Description

In the Frenzyheart Tribe daily, The Heartblood's Strength, there should be a microscope or whatever icon to fill your vial on top of The Suntouched Pillar in Scholazar Basin. The second part of the quest is marked properly, where you collect the blood.

## Questie & WoW version
 

WotLK Classic

**Comment by RoanSythen** [comment]
> What version of Questie are you running?

It was 8.0.1 when I encountered this. I updated to 8.1.0 today so if that daily is available I will see if it was fixed.

**Comment by BreakBB** [comment]
Any update on this @RoanSythen ?

**Comment by RoanSythen** [comment]
> Any update on this @RoanSythen ?

I've been checking daily, waiting for them to offer this quest again. They offer 2 random ones of a possible.. I dunno like 5 or 6? Just bad luck lol.

**Comment by RoanSythen** [comment]
> Any update on this @RoanSythen ?

![image](https://github.com/Questie/Questie/assets/132086624/3d6d0d2f-8dc6-4a26-95d4-e9b30beedbaa)

I am currently using Questie 8.2.1 and confirmed, it is not showing up.

**Comment by BreakBB** [comment]
Thanks for coming back to this @RoanSythen - This will be fixed in the next release 👍🏻
