### ISSUE TITLE
Questie Log Stacking Visual Bug

### ISSUE THREAD

**Issue by TheHulkingMango** [Questie/Questie#4826]
When Questie collapses and expands repeatedly while going in and out of combat, it causes the quest log overlay to stack on itself multiple times. Generally collapsing and expanding once more outside of combat fixes the visual bug.

Questie Version: 8.0.1

WoW Version: Wrath of the Lich King Classic

![image](https://user-images.githubusercontent.com/132087348/235212840-081ae9c2-c9f5-4d1e-8c72-027067b5e95a.png)

**Comment by Dyaxler** [comment]
This should be fixed in the next update.

**Comment by BreakBB** [comment]
Closing this for now. If this pops back up after the next release, please report back @TheHulkingMango
