### ISSUE TITLE
Disable Event/Holiday quests on map

### ISSUE THREAD

**Issue by datgrl** [Questie/Questie#4827]
I've followed the faq and installed it as recommended.  I double checked and the version is supposedly the latest.  I am seeing event quest !'s like the one for Peddlefoot in Crossroads or the xmas quests in Org.

**Comment by MyTechnoHunter** [comment]
Try this command to rebuild the database:

/run Questie.db.global.dbIsCompiled = false;ReloadUI()

**Comment by nanderson11** [comment]
I also see the Gift Giving quest from Kwee Q. Peddlefeet available now in TB, Org and UC, even though it's not. I don't see one in Crossroads specifically, or the Xmas quests that OP mentioned, so it's possible it's not the same issue although seems pretty close.

Running the command that @MyTechnoHunter suggested didn't change anything.

Game version: 1.14.3
Question version: 8.1.1 (also saw it back when I was on 7.5.2)

**Comment by BreakBB** [comment]
Fixed in b83634935682c2b5e05051b9e093bd5734673633
