### ISSUE TITLE
[[36D] An Unholy Alliance (6521)] - shows as available even after you pick it up

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#4830]
Wrath.

**Comment by Gogo1951** [comment]
![image](https://user-images.githubusercontent.com/55365231/235374634-3db9d7c1-8260-4c54-8443-f3e403583e43.png)

Quest still shows on turn in too. (=

**Comment by BreakBB** [comment]
We really need the quest IDs on these kind of reports. It could be there are two different "An Unholy Alliance" and you picked up version A, but version B is still shown.

**Comment by MyTechnoHunter** [comment]
uh.. -points at the title-

the quest id is there?
unless there's a way to get quest id's in the tooltip for the marker on the npc?

**Comment by BreakBB** [comment]
Well there are four different "An Unholy Alliance":

https://www.wowhead.com/wotlk/search?q=an+unholy+alliance

Most likely we show the wrong one on the map, but the quest that can actually be accepted is a different one.

**Comment by MyTechnoHunter** [comment]
can we add (or is there already) an option to show quest ids (like the levels) in the tooltip for the questgiver?
