### ISSUE TITLE
[37] Recover the Cargo! - Dustwallow Marsh

### ISSUE THREAD

**Issue by TheHulkingMango** [Questie/Questie#4832]
Questie displays Repaired Diving Gear as a hotbutton next to the quest instead of Salvage Kit when Repaired Diving Gear is equipped. Salvage Kit is the usable item to recover Shipwreck Debris. Repaired Diving Gear allows wearer to breathe underwater.

![image](https://user-images.githubusercontent.com/132087348/235284776-abd6cd68-0109-4b65-abfd-94bc6b2c00b1.png)

![image](https://user-images.githubusercontent.com/132087348/235284787-216bfbd3-7e2f-45ff-9a18-ccbd1511ae89.png)

![image](https://user-images.githubusercontent.com/132087348/235284828-8eb3ad12-544f-4b1b-a43f-03be4794bb17.png)

![image](https://user-images.githubusercontent.com/132087348/235284836-e4f8e892-53a5-4b0d-be63-ed9de6a5516f.png)

Questie Version: 8.0.1

WoW Version: Wrath of the Lich King Classic

Attached are multiple Snips to assist in clarifying description above.

**Comment by TheHulkingMango** [comment]
Adding Snip of Repaired Diving Gear Tool Tip (Displayed in first snip and snip of paper doll showing it equipped)

![image](https://user-images.githubusercontent.com/132087348/235285017-f546ff9e-8055-43ad-a07b-c1d6b8734905.png)

**Comment by Dyaxler** [comment]
Let me see if I get this correctly. Sorry, I honestly don't remember this quest.

1. Obtain quest - NPC gives Repaired Diving Gear [This item appears as a button in the Tracker and is Useable]
2. First Objective is to obtain Salvage Kit and this is used to retrieve Salvaged Strong Boxes from Shipwreck Debris [Button for Salvage Kit does NOT appear after picking it up] <--- Correct?
