### ISSUE TITLE
Need Feedback - Tell us what you think. Achievements [quantityProgress  / quantityNeeded]

### ISSUE THREAD

**Issue by Dyaxler** [Questie/Questie#4834]
## Description
All the number criteria-based Achievements all indicate a `quantityNeeded` in the Objective Text. What I propose is to trim the `quantityNeeded` tag off of the Objective Tags. So instead of having something like "Loot 1000 Gold: 456/1000" the tag would simply be "Loot 1000 Gold: 456".

Old:
![image](https://user-images.githubusercontent.com/17400948/235320739-40237cf1-15d9-4177-9640-40680e4788e5.png)

New:
![image](https://user-images.githubusercontent.com/17400948/235320577-767732b2-0854-492e-9f93-62686dc5b6b6.png)

The above example is only for Money and the modification only exists for me currently on my local build. I can apply this same method for all other number criteria-based Achievements.

Thoughts?

**Comment by MyTechnoHunter** [comment]
maybe make it an option and default to normal?

people will complain else..

**Comment by Gogo1951** [comment]
![image](https://user-images.githubusercontent.com/55365231/235323885-dd39122f-0c2b-4c61-b573-8e612e22599d.png)

Keep the formatting consistent.

So like, if the objective is "Complete 50 Quests" or "Unarmed Skill to 400"...
don't use the little >, just indent the objective and have it be the same as quest objectives.

> Quests Complete : 49 / 50 

> Unarmed Skill : 374 / 400

**Comment by BreakBB** [comment]
I also think we should try to keep it consistent with other objectives.

The money string format looks nice but is a bit verbose, that's the downside 🤷 

But it's also quite the edge case because there aren't many money objectives and I guess even less people actively tracking these outside of the few quests.

**Comment by Dyaxler** [comment]
I thought I implied that this change would be applied to all achievements to keep things consistent... if everyone liked the idea.

@Gogo1951 To keep the tracker code as slim as possible we try and avoid any massive text formatting modifications. In short, we try and use the raw text from the DB as much as possible. Tweaking the spacing has been on my mind but I'm more focused on getting the tracker stable for now. The idea above just popped into my head and I wanted to get it on paper and let everyone chew on it. Something I want to do more of in the future instead of surprising everyone with something new.

**Comment by eTzmNcbkrng** [comment]
I like this change but with all the legibility modifications that @Gogo1951 mentioned.

**Comment by Dyaxler** [comment]
After some internal discussion... I'm not going to pursue this.
