### ISSUE TITLE
Objective Announce isn't working right in parties

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#4835]
Wrath Classic.

Playing with a friend today. I did a quest where we both got credit for the action I took. In his quest log, shows "complete" but it didn't announce.

However, the next time he did something that completed a quest, it announced both objectives were complete.

![image](https://user-images.githubusercontent.com/55365231/235324234-53cae822-7ada-4b93-ad07-951791e6022c.png)
 [P] [Aggromonster]: ty all bb 
 [P] [Gogowarlock]: what does "ty all bb" mean? 
 [P] [Gogowarlock]: thank you all baby? 
 [P] [Gogowarlock]: fuck  
 [P] [Gogowarlock]: i hate twitter 
 [P] [Nargor]: lol 
 [Sheenyteeds] has come online. 
 [P] [Gogowarlock]: thnak you all, baby! 
 [P] [Gogowarlock]: ha 
 You receive item: [Thalanaar Moonwell Water]. 

 **[P] [Gogowarlock]: {star} Questie : 1/1 Thalanaar Moonwell Water for [[28] A Dip in the Moonwell (Complete)]!** 

> -- We both got credit. Were talking in Discord, buddy was like, "That's odd, it didn't announce for me but it's done."

 Gigatron leaves the party. 
 [P] [Nargor]: Hey Gogo, you know what day it is today? 
 [P] [Gogowarlock]: ramen day! 
 [P] [Nargor]: its FRAKING ramen day!!!!! 
 You receive loot: [Rock Chip]. 
 Exmage receives loot: [Bright Eyeball]. 
 Your skill in Skinning has increased to 217. 
 You receive loot: [Medium Leather]. 
 Your skill in Skinning has increased to 218. 
 You receive loot: [Medium Leather]. 
 Your skill in Skinning has increased to 219. 
 You receive loot: [Medium Leather]. 
 Galak Stormer attempts to run away in fear! 
 Exmage receives loot: [Silk Cloth]x2. 
 Exmage receives loot: [Silk Cloth]x2. 
 Your skill in Skinning has increased to 220. 
 You receive loot: [Medium Leather]. 
 You receive loot: [Heavy Leather]. 
 Exmage receives loot: [Steelsnap's Rib]. 

 **[P] [Exmage]: {star} Questie : 1/1 Thalanaar Moonwell Water for [[28] A Dip in the Moonwell (Complete)]!** 

> -- 1-2 minutes later.

 [P] [Exmage]: {star} Questie : 1/1 Steelsnap's Rib for [[30] Steelsnap]! 
 You receive loot: [Steelsnap's Rib]. 
 [P] [Gogowarlock]: {star} Questie : 1/1 Steelsnap's Rib for [[30] Steelsnap (Complete)]! 
 Your skill in Skinning has increased to 221. 
 You receive loot: [Medium Hide].

**Comment by MyTechnoHunter** [comment]
interesting.. can you enable timestamps in chat and reproduce?

**Comment by Gogo1951** [comment]
That chat is long since past. Sorry.

**Comment by Gogo1951** [comment]
I do have my buddy's screenshot from right after it happened.

He's got Elv, but he's not a huge add-on junkie.

![image](https://user-images.githubusercontent.com/55365231/235324856-5f898b78-4228-4bec-9206-946c87599f7c.png)

**Comment by MyTechnoHunter** [comment]
did they verify they have todays questie update? i know one of the issues was the tracker update being fixed

**Comment by Gogo1951** [comment]
Got it to bug out again... it's bugging on quests that don't have a kill / loot objective.

So like "Use the dynamite to blow up the plane." One player does that, gets credit. The other player in the party gets credit, but Questie doesn't announce it until they do something else that gets them credit -- then it announces both.

**Comment by Dyaxler** [comment]
It almost sounds like we're missing a Tracker Update somewhere?

@Gogo1951 When an update happens again on one players screen and everyone else in the party gets credit in their Quest Log but it's not showing on the Tracker, get one of them to Minimize their Tracker and then Maximize it... does their update and show the objective complete?

**Comment by Dyaxler** [comment]
This might also be related to the "perf issue" we found this morning. Try the new update please.

**Comment by Gogo1951** [comment]
I'll keep an eye out. Haven't been questing as much in a party lately.

**Comment by Gogo1951** [comment]
Hey @Dyaxler, had the issue today.

I created the quest item, but nothing happened. (Through use to generate.)

Then we killed another few mobs, and when I looted a quest item again a minute or two later, the announce went off.

 You receive loot: [Greater Healing Potion]. 
 Quest accepted: Legends of Maraudon 
 **You receive item: [Filled Cerulean Vial].** 
 Vaneleroth performs Mining on Truesilver Deposit. 
 Vaneleroth receives loot: [Truesilver Ore]x2. 
 You receive item: [Soul Shard]. 
 You receive loot: [Gem of the Third Khan]. 
 You receive loot: [Theradric Crystal Carving]. 
 **[P] [Gogowarlock]: {star} Questie : 1/1 Filled Cerulean Vial for [[47D] Vyletongue Corruption]!** 
 You receive loot: [Squishy Basilisk Eye]. 
 You receive loot: [Curved Basilisk Claw]. 
 You receive loot: [Smooth Stone Chip].

**Comment by Cabro** [comment]
This has 100% happened to me too, and it usually happens with quest items that blizzard themselves don't give you a yellow text.
I could also be wrong, but i know that bug

**Comment by Dyaxler** [comment]
I didn't write the QuestieAnnounce module. I don't recall any changes to it between v7'ish and now. Maybe Blizzard is f'ing with the item caches again. It's happened before.

**Comment by Dyaxler** [comment]
I might have a possible fix for this in PR #4886 

More info here: https://github.com/Questie/Questie/pull/4886/commits/9e203f0a4e82919bcda684535cec1c70bef8bc0d

**Comment by Gogo1951** [comment]
I think there is a bug for the quests where you use an item to create another. I think the new item often goes on top of the old item in your bag, and it's fair that maybe it doesn't trigger the update at the right time thanks to some issue with Blizzard. But... I quest a lot, and this sort of bug just started showing up fairly recently.

The thing that gets me is that the in-game quest log shows it's complete, but the tracker doesn't. I think the tracker and the quest announce probably use the same logic. And my guess is there's a missing update instruction somewhere.

Once another item is looted, then the alert seems to go off fine. From what I can tell it's just when you use an item they give you for the quest, and it spawns another item. That's the only time I see this issue happening.

![Pasted_Image_5_15_23__1_38_PM](https://github.com/Questie/Questie/assets/55365231/e4f4505e-df3d-4ede-aac8-fb94049fb353)

**Comment by BreakBB** [comment]
Closing this and assuming it is no longer an issue for now.
