### ISSUE TITLE
8.1.0 base objective tracker not working

### ISSUE THREAD

**Issue by legoman60** [Questie/Questie#4837]
## Bug description
Something about the new update to 8.1.0 either directly broke the base objective tracker or has had a bad interaction with another of my addons that resulted in a broken base objective tracker. When I disabled questie 8.1.0 then the base objective tracker reappeared. I tried deleting and re-installing questie 8.1.0 completely but the base objective tracker didn't reappear. After that, I tried using the reset button in the config menu but got no change. When I back patched to 8.0.1, then the base objective tracker reappeared. I turned on LUA errors when I started all of this, but none appeared.

Here is a list of my other enabled addons:
Advanced interface options
Atlas
Atlasloot classic
Attune
Auctionator
BadBoy (w/ CCleaner and Ignore modules)
Bartender
Details
Elvui                            (<== the likely suspect for a bad interaction lol)
FakeAchievement
HandyNotes
ItemRack
Leatrix Maps
Masque
MaxCam
Nova World Buffs
OmniCC
Prat
Quartz
RareScanner
RCLootCounil
SexyMap
Simple Item Level
Skillet
Spy
TacoTip
TomTom
WeakAuras
AddonSkins (for Elvui)
DBM
Bagnon

## Questie & WoW version

WotLK Classic Questie version 8.1.0

**Comment by Dyaxler** [comment]
Duplicate bug: https://github.com/Questie/Questie/issues/4836

Fixed in: https://github.com/Questie/Questie/releases/tag/v8.1.1
