### ISSUE TITLE
tooltip missing with no quests in log and header always shown

### ISSUE THREAD

**Issue by MyTechnoHunter** [Questie/Questie#4845]
## Bug description
start a new character, or log in to a character that has 0 quests. if the header is shown, there is no tooltip or clickable ? mark to open the options

## Screenshots

![WoWScrnShot_043023_221109](https://user-images.githubusercontent.com/55214545/235510154-03d59180-49ed-4492-82dc-644b7a7f6ffb.jpg)

## Questie & WoW version
v8.1.1 (latest release) and this affects both versions of the game

**Comment by Dyaxler** [comment]
Correction to "if the header is shown..." == "Always Show Tracker" option in Questie Config --> Tracker.

...also I found another bug... 

If "Always Show Tracker" is enabled and you have only one quest in your log, if you turn in that quest it results in a blank Tracker with the header showing and sized to exactly what it was when the quest was populated before turning in said quest. Turning in the quest fires the appropriate quest finishers but never triggers a tracker update.
