### ISSUE TITLE
Wrong objective locations for "Relics of the Snow Leopard Goddess"

### ISSUE THREAD

**Issue by BreakBB** [Questie/Questie#4849]
## Description

Another one where Questie lists items dropping from NPCs while they only drop from objects.

## Wowhead link

https://www.wowhead.com/wotlk/item=38677/harkoan-relic
https://www.wowhead.com/wotlk/quest=12635/relics-of-the-snow-leopard-goddess

## Questie & WoW version

v8.1.1

**Comment by Cabro** [comment]
Wasn't this fixed?
