### ISSUE TITLE
QuestId doesn't exist in Game's Quest Log

### ISSUE THREAD

**Issue by BarristanSelmy** [Questie/Questie#4858]
![image](https://user-images.githubusercontent.com/8889302/235939858-c05ac6e6-a640-41ee-9d0e-112b5625c49b.png)

**Comment by BarristanSelmy** [comment]
I don't have any other info for this.

**Comment by BreakBB** [comment]
Hey @BarristanSelmy can you remember when this error popped up? Right after handing in a quest?

**Comment by BreakBB** [comment]
I am merging this with #4842 - Would be nice if you could answer on the other issue.
