### ISSUE TITLE
Problem initializating, probably an Easy fix

### ISSUE THREAD

**Issue by JDude2020** [Questie/Questie#4862]
![Screenshot 2023-05-03 at 9 31 42 PM](https://user-images.githubusercontent.com/132538616/236113266-12444d55-ee48-4cbe-b71a-b73d7980eca7.png)

Hello, just need help resolving this issue on initialization. I'm sure its an easy fix but I am not too experienced with this stuff and nothing quick and simple was working from my search. inlcuding deleting the files in the WTF folder. Any suggestions

**Comment by MyTechnoHunter** [comment]
you are using either a damaged install of questie or one that is OLD.. please remove Questie from your Addons folder and use either the link in the discord downloads (if manually installing) or the addon client of your choice.. lots use the CurseForge client.
grab it from curseforge making sure to choose your game flavor you are playing.. (dont try to update wrath if you play vanilla)

if it still errors after a clean re-install yell!

**Comment by JDude2020** [comment]
I have tried resintalling several times and I am using curseforg. what do you mean by don't update wrath? I am trying to play WOTLK.

**Comment by MyTechnoHunter** [comment]
just mean make sure the addon you update is for the game you are trying to play.. if you update wrath and play vanilla.. it wont help..

ok.. open curseforge, rightclick questie and delete settings, then right click and delete the addon.. open your \_classic\_\Interface\Addons folder and make sure the Questie folder is gone.. if its not, delete it
go up to the \_classic\_ folder and delete the Cache folder (the game will re-create it)

go back to curseforge and getmoreaddons Questie

once installed go in game and see if it still errors

**Comment by JDude2020** [comment]
I changed the WOW file location and Curseforg updated my folders once I did that and it works now. Thanks for you replies.
