### ISSUE TITLE
Dalaran Cooking Daily - [80] Sewer Stew

### ISSUE THREAD

**Issue by TheHulkingMango** [Questie/Questie#4864]
Stew Cookpot in Questie Tracker is replaced by Crystalsong Carrot count next to the quest making it unable to be one-click made with required Basic Campfire/Cooking Fire nearby. Inventory has to be opened and Stew Cookpot used from there.

Stew Cookpot:
![image](https://user-images.githubusercontent.com/132087348/236577984-5c3c8b25-1b58-4b5d-822d-c9e838f07595.png)

Crystalsong Carrot in inventory:
![image](https://user-images.githubusercontent.com/132087348/236578081-993826fb-55ff-479a-b2b8-973da28aa0c3.png)

Questie Tracker Issue (With Crystalsong Carrots in Inventory):
![image](https://user-images.githubusercontent.com/132087348/236578224-c0975efc-faf0-43bd-bd7e-b9dfd2623c5e.png)

Questie Tracker (When Crystalsong Carrots are removed from Inventory):
![image](https://user-images.githubusercontent.com/132087348/236578507-0def4f78-4a85-4446-8835-abed85e97dd1.png)

Questie Version: 8.1.2

WoW Version: Wrath of the Lich King Classic 3.4.1.49345

**Comment by Dyaxler** [comment]
Fix was checked into master... just hasn't made it into a release yet.
