### ISSUE TITLE
[Gol'dir (503)] - Missing Objective Location

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#4869]
Item is https://www.wowhead.com/classic/item=3704/rusted-iron-key

Dropped by https://www.wowhead.com/classic/npc=2431/jailor-borhuin

Note WoWHead doesn't have locations either. Lame.

He's in one of the houses in that little village.

This looks like good data: https://wowclassicdb.com/wotlk/npc/2431

**Comment by BreakBB** [comment]
Something doesn't seem right. That quest has the objective for looting the key in our database, the key is linked to that NPC and the NPC has multiple spawns as well. No correction is overwriting these 🤔

**Comment by BreakBB** [comment]
![grafik](https://github.com/Questie/Questie/assets/33514570/d9030864-cfb6-4fbf-82ae-893b6f630dd7)

Looks good to me. The only issue I found was that "Find where Gol'dir is being held" was located in Alterac Valley, not Alterac Mountains... And that since some time since TBC 😅
