### ISSUE TITLE
[Battle of Hillsbrad (550)] - Quest still shows after you pick it up

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#4870]
![image](https://user-images.githubusercontent.com/55365231/236655642-dadadf12-2690-4005-b637-ffaa8c7ba518.png)

I think the IDs are off...

**Comment by Gogo1951** [comment]
![image](https://user-images.githubusercontent.com/55365231/236655662-51bee804-9e9b-4d0d-8cc4-a10856fd5f12.png)

**Comment by Gogo1951** [comment]
Blood elf, Wrath.

**Comment by BreakBB** [comment]
Can you enable questIDs to share which you accepted and which is still showing @Gogo1951 ?

**Comment by Gogo1951** [comment]
No, sorry. It's been long since turned in. 

It's a series chain though, I think it just doesn't have the dependencies set up correctly. The quests in this chain all have the same name.

<img width="251" alt="image" src="https://github.com/Questie/Questie/assets/55365231/dbd72215-7ab4-4338-85b4-28c01ffa2561">

**Comment by BreakBB** [comment]
@Gogo1951 can you run the following commands and report the output?

`/dump C_QuestLog.IsQuestFlaggedCompleted(550)`
`/dump C_QuestLog.IsQuestFlaggedCompleted(14351)`

**Comment by Gogo1951** [comment]
![image](https://github.com/Questie/Questie/assets/55365231/2b9c632c-64fc-482b-8bea-df34e87f3e8a)

I've done a bunch of questing since however. Not sure if this would still show the same way at the time when I reported the bug.
