### ISSUE TITLE
Feature Request:  Additions to Quest Sounds

### ISSUE THREAD

**Issue by rbpaiett** [Questie/Questie#4873]
## Description

I love that you added the quest sounds to your addon, it's nearly perfect (for me anyway), but I have a few enhancements to it:

1.  Please add the standard in-game QUESTCOMPLETE sound to the 'Quest completed' section along with the voices.  I just prefer the music cue instead of a voice one.
2. Please add a 3rd section that makes a sound when you are making progress (like when you pick up a quest item, e.g.: 1/3, 2/3).  Then when you get all 3, the quest objective completed sound goes off.

An example addon is SmartQuest.  I use it but it is incompatible so I've had to massage the programming.

So an example of functionality, take the quest [78] Know No Fear (12822):

1.  When the Garm Watcher progress updates upon each tick (1/6, 2/6, 3/6, etc.) the sound "window opens" goes off.  
2.   The same goes for Snowblind Devotee (1/8, 2/8, 3/8 ...) the sound "window opens" goes off. 
3.   If either one of the quest objectives is complete, the sound "window closes" goes off.
4.   When both are done, the Quest Completed event fires and the generic 'QUESTCOMPLETE' sound goes off.

That would be perfect for me if you can program in these additions.

I hope my description was clear enough.

Much Thanks!

**Comment by MyTechnoHunter** [comment]
> 1. Please add the standard in-game QUESTCOMPLETE sound to the 'Quest completed' section along with the voices.  I just prefer the music cue instead of a voice one.

point me in the right direction.. what sound are you talking about? (i have used addons that put sounds in the game so long i have no clue the default anything)

> An example addon is SmartQuest. I use it but it is incompatible so I've had to massage the programming.

i am TechnoHunter on the discord, dm me the thing you are talking bout and i will try to see what can be added :)

**Comment by rbpaiett** [comment]
Thanks so much!

**Comment by MyTechnoHunter** [comment]
no worries, there is a lot of overlap in the sound choices(as in most of the list be duplicated) for objective progress, but the options are there, and work.. i also was able to track down the correct sound file and name for the quest complete you had linked (619) so that is in the quest complete choices now.

all this is predicated on passing the review process for the PR but it should be fine

**Comment by rbpaiett** [comment]
I added the master to the game and the sounds part work perfectly, thanks soooo much!
Can the settings, just for the sounds, be global, like a toggle so I don't need to do it for all chars I have?
I understand why you have per character settings for things like the darkmoon faire but how about 'just' for the sound alerts?
