### ISSUE TITLE
Issue 881 is back!

### ISSUE THREAD

**Issue by nicklaskittelmann** [Questie/Questie#4875]
The issue https://github.com/Questie/Questie/issues/881 is a problem once again.

I'm using questie 7.5.2

**Comment by MyTechnoHunter** [comment]
first off.. update.. the latest is 8.2.1 if i recall.. is there a reason you are using an older version? we cant verify issues being back or not if you are using outdated addons

**Comment by Cabro** [comment]
Current Questie is 8.2.1, maybe try upgrade and check again?

**Comment by nicklaskittelmann** [comment]
Sorry, I should have noticed. Didn't pick up on that questie hadn't been included in the Curseforge app. But now that I added it there, it auto-updated, and now the issue is fixed!
Thanks for the quick reply - just close this issue!
