### ISSUE TITLE
Questie tracker disappears at seemingly random

### ISSUE THREAD

**Issue by Nyarantes** [Questie/Questie#4876]
Seemingly at random, the tracker disappears.
I've noticed that it often happens when I'm tracking 4 or 5 quests at a time, though the tracker shows normally if I'm tracking only 3 quests, or 6 quests or more. There doesn't seem any rhyme or rhythm about it, and it doesn't seem relevant to quest IDs at all.

I'm playing on the latest version of classic wotlk wow, using the latest version of questie (being 8.2.1, though the issue has persisted for almost a week now, ever since 8.1.2 was launched)

I've attempted to reinstall the addon to no avail, but I suspect it's to do with the achievement tracker which is a newly added feature.

**Comment by MyTechnoHunter** [comment]
i would be interested in your tracker height.. sounds like  the number of quests when low is not enough to trigger scrolling and when higher for sure is scrolling.. the in between might be right on the cusp.. can we get screenshots? feel free to join the discord to make the help cycle faster in responses

**Comment by Nyarantes** [comment]
![image](https://github.com/Questie/Questie/assets/118824584/ecb1164b-f002-4c17-9da1-71ca30f07e10)
![image](https://github.com/Questie/Questie/assets/118824584/b0bbbbc3-baf9-4b0d-92a1-e9d750f3a397)
Pretty sure the tracker settings are plain default

Though I've made it a little wider for quest text
![image](https://github.com/Questie/Questie/assets/118824584/04667c79-6ca7-402e-9692-05d2f10a5ad8)
Enabled background to show width, it's usually disabled

**Comment by Dyaxler** [comment]
If you're "manually" setting the tracker's width, you're also "manually" setting its height. While in Manual mode the Tracker Height Ratio is ignored. So, if it's too short and you add more Quests, they won't show because Scrolling is enabled. Use your middle mouse button to Scroll through the Trackers tracked quests. You can manually make it higher. Auto sizing mode can be re-enabled by Right Clicking the Sizer.

**Comment by Nyarantes** [comment]
Currently, pressing the "Reset Tracker" button in the settings seems to have fixed it with 4 quests in the tracker.
This hasn't changed the size of it at all, only it's position on the screen.
![image](https://github.com/Questie/Questie/assets/118824584/27fc7456-5a30-47e7-a133-f77158dfbd1b)
Accepting additional quests past this doesn't seem to kill the tracker either, so I'm not sure I can reproduce it anymore. But it's still weird that it happened at all.

**Comment by Dyaxler** [comment]
@Nyarantes have you had a chance to check out the new version yet to see if you issue is still present? If it's not happening anymore, please close this Issue. :)

**Comment by Nyarantes** [comment]
I've downloaded it and trying to recreate it. If I see no issues by saturday, I'll close it :)

**Comment by Dyaxler** [comment]
Thank you very much! You rock...

**Comment by Nyarantes** [comment]
Issue seems solved!
