### ISSUE TITLE
Quest ID missing 4244

### ISSUE THREAD

**Issue by Zermavis** [Questie/Questie#4887]
## Description
Quest The Mighty U'cha throws a bunch of console errors
![image](https://github.com/Questie/Questie/assets/53433657/88271042-280e-4c43-a0fd-3e3199d44d4a)

## Wowhead link
https://www.wowhead.com/classic/quest=4301/the-mighty-ucha

## Screenshots
![image](https://github.com/Questie/Questie/assets/53433657/514f4c9c-f9fe-4144-8000-49c045f51c67)

## Questie & WoW version
Questie 8.2.1
Classic Era

Sry I probably picked the wrong label, and cant see how to change it

**Comment by BreakBB** [comment]
Merging with #4842
