### ISSUE TITLE
Questie is no longer working for me

### ISSUE THREAD

**Issue by jacquesyves9** [Questie/Questie#4888]
I have been using Questie since I first started playing WoW a few years ago. I was playing WoTLK Classic when Questie stopped working on one of my low-level characters. I tried reinstalling it multiple times and searched online for similar problems, but it's not listed in my Add-ons anymore. It seems like no one else has reported this issue. I use CurseForge for my add-ons and everything else works just fine.

![Screenshot (1)](https://github.com/Questie/Questie/assets/133479642/50c89cc2-a083-494e-bd22-8cbbcbcdb544)
In the image you can clearly see that I have Questie Installed, it is up-to-date, and listed under WoTLK Classic Add-ons.

![WoWScrnShot_051323_015228](https://github.com/Questie/Questie/assets/133479642/e3e042b9-c894-4042-969e-40b3bcbf7598)
In this image, you can now see that under the Addons list in-game, Questie is not shown anywhere. 

Under the files in my computer: This PC > Program Files (x86) > World of Warcraft > _classic_era_ > Interface > Addons 
Questie is listed in the files.

What I find very weird however is that Questie is still working for Vanilla Hardcore.

Any help is appreciated.

**Comment by MyTechnoHunter** [comment]
Wotlk = _classic_
Vanilla = _classic_era_

**Comment by drejjmit** [comment]
Curse is installing all your addons for Wrath. Change the upper right option
![image](https://github.com/Questie/Questie/assets/15526476/626973a8-8b08-4e2a-83df-8bb58c9de189)

**Comment by MyTechnoHunter** [comment]
> Curse is installing all your addons for Wrath. Change the upper right option ![image](https://user-images.githubusercontent.com/15526476/238121616-626973a8-8b08-4e2a-83df-8bb58c9de189.png)

i think you mis understood the OP.. they play wrath classic, it is installed via curseforge (pic shows wrath classic for verification) but.. its not there..

instead its only in \_classic\_era\_

> In the image you can clearly see that I have Questie Installed, it is up-to-date, and listed under WoTLK Classic Add-ons.

goto your gear symbol in curseforge, lower left.. click it and click the wow game in the menu on the left.. in the right side check the drop down for wrath to make sure its pointing at the right folder
![image](https://github.com/Questie/Questie/assets/55214545/eb4920ca-b67b-4392-bbe1-c25abd8d964c)

**Comment by jacquesyves9** [comment]
It is listed under the correct instance and under the /_classic_/ file as well.

**Comment by Cabro** [comment]
My man, is the addon loaded in the game addons menu?
![image](https://github.com/Questie/Questie/assets/1155017/a80ea5a5-38f5-41cf-a429-98ed18a8c278)

**Comment by BreakBB** [comment]
Any update on this @jacquesyves9 ? Can we close this?

**Comment by jacquesyves9** [comment]
Still not working but I discovered only on that character. I have decided
to just play a new character. I appreciate those that checked in. Thank you.

**Comment by BreakBB** [comment]
That is really strange 🙈 So on one character in Wotlk Classic Questie shows up in your addon list and on the same account but different character it does not @jacquesyves9 ?

**Comment by MyTechnoHunter** [comment]
you can start a fresh char if you want to BUT never let an addon force that decision.. to clear questie, goto your game folder and into the WTF folder, then search for Questie*.*
delete any that show in the results, both .lua and .bak.. (this will kill ALL alts journey!)

once done, log into your character and it should be there..

the only other thing i can think of is somehow its being blocked from only that character.. in the WTF folder is your Account folder, and in that is your actual account# folder,  with a server folder and a alt folder inside it.. goto that folder for your alt and look for the addons file.. if you delete it it will create the list again on first login and should need all your addons enabled/disabled as per your character choises on the addon menu.

**Comment by Cabro** [comment]
Most likely Questie was not checked in the addon list. User error i'd say
