### ISSUE TITLE
Tracker doesn't expand correctly

### ISSUE THREAD

**Issue by Ivikdor** [Questie/Questie#4891]
Tracker doesn't expand correctly, every time I get a new quest added the bottom-most quest gets it's text cut off because Questie won't expand and I have to fight with the resize window EVERY TIME I get a new quest to fix it.

Classic Era, Questie 8.2.1

**Comment by Dyaxler** [comment]
We have a PR (branch) that should address this issue.
https://github.com/Questie/Questie/pull/4886
