### ISSUE TITLE
Failed timed quests and tracker.

### ISSUE THREAD

**Issue by Cabro** [Questie/Questie#4893]
Failed timed quests exhibit these bugs in the tracker:
 - the timer stops at 1 second and the timer line is removed only if you move the tracker. It stays indefinitely visible otherwise or until another quest has an objective update.
 - It is missing the `Failed` text on objective
 - both the map and NPC icons/tooltips are not removed if you untrack this quest in the Failed state, they are forcibly shown

![image](https://github.com/Questie/Questie/assets/1155017/b007bea3-53d3-4ee2-9942-a957342ac6b6)
![image](https://github.com/Questie/Questie/assets/1155017/bfc1140a-39c7-4607-ba5d-2cbf5d11a4e2)
![image](https://github.com/Questie/Questie/assets/1155017/01c12c91-3e7b-45ca-9d78-a5f7c8161055)

Wotlk 8.2.1

**Comment by Dyaxler** [comment]
Hmmm... a timer with more than one objective. I wonder if that might be it. I'll look into it.
