### ISSUE TITLE
Quest tracker disappears when leaving an instance such as a dungeon.

### ISSUE THREAD

**Issue by 002Zero002** [Questie/Questie#4894]
## Bug description

I'm almost certain the questie tracker disappears when you leave an instance. When I enter a dungeon it's fine, but when I leave the tracker is gone and I have to keep going into questie and resetting the tracker.

## Screenshots

I don't really see the need for the image because it's just a screen with no quest tracker on the side.

## Questie & WoW version
 I'm playing on wotlk classic.

**Comment by Dyaxler** [comment]
Sorry about that. I'm almost certain it pertains to an issue that I fixed in this PR:
https://github.com/Questie/Questie/pull/4886

Will merge that and release soon.
