### ISSUE TITLE
QuestId doesn't exist in Game's quest log: 13396 & 13297

### ISSUE THREAD

**Issue by JoSSte** [Questie/Questie#4904]
## Description

I got two messages repeatedly while picking up  [Whelp Bone Dust]
>     Questie: [ERROR] Please report on github or Discord. QuestId doesn't exist in Game's quest log: 13396 (and 13297) 
while doing [Sindragosa's Fall (13397)][Futility(13396)]

i had abandoned https://www.wowhead.com/wotlk/quest=13297/neutralizing-the-plague

## Screenshots

![billede](https://github.com/Questie/Questie/assets/12601673/c391e1bb-d418-4858-8c08-bc408cef2276)
![billede](https://github.com/Questie/Questie/assets/12601673/c258074c-42f2-4f3b-8e30-ac9319fe5562)
I had abandoned neutralizing-the-plague ( see QL below) but the items still appear on the map
![billede](https://github.com/Questie/Questie/assets/12601673/fe773332-9fd3-492e-994d-6ba32c3ed940)
![billede](https://github.com/Questie/Questie/assets/12601673/79c592df-0fc1-4dd4-a794-c95a6a9904dd)

## Questie & WoW version

v8.2.1 (classic wotlkl)

**Comment by BreakBB** [comment]
Merging with #4842
