### ISSUE TITLE
Bug with Commit e17fd88

### ISSUE THREAD

**Issue by Starlynk1** [Questie/Questie#4909]
## Bug description

Using the merge commit e17fd88 I got the following error caught by bugsack. I changed the tracker quest padding from the default 4 to 2.

```
3x ...Modules\Options\TrackerTab\QuestieOptionsTracker.lua:759: attempt to call global 'GetNumTrackedAchievements' (a nil value)
[string "@Interface\AddOns\Questie\Modules\Options\TrackerTab\QuestieOptionsTracker.lua"]:759: in function <...Modules\Options\TrackerTab\QuestieOptionsTracker.lua:756>
[string "=[C]"]: ?
[string "@Interface\AddOns\Bartender4\libs\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-86.lua"]:45: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:43>
[string "@Interface\AddOns\Bartender4\libs\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-86.lua"]:836: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:658>
[string "@Interface\AddOns\Bartender4\libs\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-86.lua"]:888: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:876>
[string "=[C]"]: ?
[string "@Interface\AddOns\Bartender4\libs\AceGUI-3.0\AceGUI-3.0-41.lua"]:66: in function <...ace\AddOns\Bartender4\libs\AceGUI-3.0\AceGUI-3.0.lua:64>
[string "@Interface\AddOns\Bartender4\libs\AceGUI-3.0\AceGUI-3.0-41.lua"]:300: in function `Fire'
[string "@Interface\AddOns\Bartender4\libs\AceGUI-3.0-41\widgets\AceGUIWidget-Slider.lua"]:65: in function <...der4\libs\AceGUI-3.0\widgets\AceGUIWidget-Slider.lua:56>
```
## Questie & WoW version
Which version of Questie are you using? 8.2.1 (commit e17fd88)

Please also state if your quest issue is about Classic Era/SoM or Wotlk.
Classic Era

**Comment by MyTechnoHunter** [comment]
uh.. couple questions.. how is it even _seeing_ anything to do with achievements in era?
next.. what does changing the padding have to do with the error above which is dealing with 
> 3x ...Modules\Options\TrackerTab\QuestieOptionsTracker.lua:759: attempt to call global 'GetNumTrackedAchievements' (a nil value)

**Comment by MyTechnoHunter** [comment]
> Which version of Questie are you using? 8.2.1 (commit https://github.com/Questie/Questie/commit/e17fd889139fa1ca50a58278f3c81156fad83fd7)

this makes no sense, the only change for that commit was in the Modules/Tracker/QuestieTracker.lua file.. the error you mentioned is in QuestieOptionsTracker..

**Comment by Starlynk1** [comment]
no idea, I just changed the padding and bam... bug registered.

**Comment by Dyaxler** [comment]
Oh! Opps! :D LOL... yeah forgot to wrap that in IsWotLK

**Comment by Starlynk1** [comment]
That's why we test it and let ya know... can't always catch everything :)
