### ISSUE TITLE
Further issues with clicks/modifier and map zoom levels and actions

### ISSUE THREAD

**Issue by Cabro** [Questie/Questie#4914]
These are issues present with https://github.com/Questie/Questie/commit/9b329426ca41e09a062c00ed7c3a6061d7c38fc1 present.

1 - if you simply Rclick on a map icon at a zoomed out level of the map, it will zoom IN, which is opposite to the blizzard map zoom logic. Expected behavior : it should zoom out.

2 - shift + Lclick without chatbox open (so you want to hide quest) it will also zoom in while showing popup to hide. Expected behavior : it should not also zoom in.

3 - shift + Rclick without chatbox open has no action linked to this key combo anymore. It still does what regular Rclick does - zoom IN. Is this by design?

4 - shift + Lclick with chabox open (you want to link quest) is still zooming in. Expected behavior : it should not also zoom in.

8.3.0

**Comment by Cabro** [comment]
Wow, this is awesome! Works great!

**Comment by Dyaxler** [comment]
Thanks, dude, for confirming this fix!
