### ISSUE TITLE
A Little Dash of Seasoning - Incorrectly shows objectives in Stonetalon Mountains

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#4928]
![image](https://github.com/Questie/Questie/assets/55365231/bd3d272f-8cf3-4632-9c0e-4d1ec0acc70b)

https://www.wowhead.com/wotlk/quest=9275/a-little-dash-of-seasoning

Quest from Bloodelf Start Zones incorrectly shows objectives in Stonetalon Mountains.

Reported by friend.

**Comment by Gogo1951** [comment]
But in looking at screenshot... not sure if Rested XP does tooltips on items...

**Comment by BreakBB** [comment]
Looks like Blizzard placed the same object in Stonetalon and Ghostlands, therefore the objectId is exactly the same and Questie shows a tooltip.

The location data for this object is correct in Questie and you can see in the screenshot the map does not show an icon.

Nothing to fix for us, but thanks for the report.
