### ISSUE TITLE
Add actual "Profiles" to Questie

### ISSUE THREAD

**Issue by BreakBB** [Questie/Questie#4930]
## Description

The settings have always been chaos and there still is no way to tell which settings are "per character" and which are "global".
To tackle this Questie needs actual "Profiles" and should allow to handle _all_ settings via Profiles.

The [Ace docs](https://www.wowace.com/projects/ace3/pages/api/ace-db-3-0) are quite clear about it and we have most things already in place since we already use AceDB for our config.

So instead of `Questie.db.char` and `Questie.db.global` we will use `Questie.db.profile` for all profile related settings. This will need a big migration.

Taken from GatherMate2:
![grafik](https://github.com/Questie/Questie/assets/33514570/f8695e53-769c-4481-b30c-d83376821555)

The "Profiles" tab is added by:

```diff
    return {
        name = "Questie",
        handler = Questie,
        type = "group",
        childGroups = "tab",
        args = {
            general_tab = general_tab,
            social_tab = social_tab,
            minimap_tab = minimap_tab,
            map_tab = map_tab,
            dbm_hud_tab = dbm_hud_tab,
            tracker_tab = tracker_tab,
            nameplate_tab = nameplate_tab,
            tooltip_tab = tooltip_tab,
            advanced_tab = advanced_tab,
+           profiles = LibStub("AceDBOptions-3.0"):GetOptionsTable(Questie.db)
        }
    }
```

**Comment by MyTechnoHunter** [comment]
there should also be a "use global" option for those that don't want the hassle of configuring per character.. once and done :)

**Comment by BreakBB** [comment]
That should be "Default" then. When you don't set up a profile, everything will be stored in the exact same profile.

**Comment by MyTechnoHunter** [comment]
its an actual clickable option in most addons.. including the ability to choose the profile to use as the default, and the ability to copy profiles to your current char, and delete stale profiles..

**Comment by BreakBB** [comment]
This is how it looks in GatherMate2 for example. I think this is somewhat what it looks like in most addons.

![grafik](https://github.com/Questie/Questie/assets/33514570/e5a6d454-3696-4fe2-ba2b-225c8e4463e1)

**Comment by MyTechnoHunter** [comment]
yup, that be the "normal" profile options.. with the addition of auto created profiles  based on name-server if i recall..

**Comment by Gogo1951** [comment]
Finally.

**Comment by Starlynk1** [comment]
Please implement this. Having to redo Questie each time in HC is a major pain.

**Comment by BreakBB** [comment]
We'll wait for @Yttrium-tYcLief to finish the settings restructure before doing this.
