### ISSUE TITLE
Unholy Alliance still shows as available on map after both being accepted and completed

### ISSUE THREAD

**Issue by ludvigrosenqvist** [Questie/Questie#4935]
## Description
The quest is showing as acceptable even though it has already been accepted or completed.

## Wowhead link
https://www.wowhead.com/wotlk/quest=14353/an-unholy-alliance

## Questie & WoW version
Questie version 8.3.0
WOTLK

**Comment by MyTechnoHunter** [comment]
Please update to 8.4.0 and report back if still an issue

**Comment by ludvigrosenqvist** [comment]
> Please update to 8.4.0 and report back if still an issue

This seems to have fixed it, thank you.
