### ISSUE TITLE
Quest tracker not updating for Mithril casing, for quest Chasing A-Me 01 in Un'Goro Crater.

### ISSUE THREAD

**Issue by MelchiorGaspar** [Questie/Questie#4939]
## Description

I purchased a Mithril Casing on the Orgimmar's auction house but its not updating in the tracker after I fetched it from the mailbox.
fixable? but the quest log does show that quest as ready for turn in. 

## Wowhead link

https://www.wowhead.com/classic/quest=4244/chasing-a-me-01

## Screenshots

![image](https://github.com/Questie/Questie/assets/1712842/35d08c81-706f-44e5-9330-a9681b5f33c9)

## Questie & WoW version

Questie = (v8.4.1)
WoW-classic-WotLK (v3.4.1)

**Comment by MelchiorGaspar** [comment]
a quick /reload command caused the tracker to update...
might be a bug not sure.

**Comment by MelchiorGaspar** [comment]
sorry I wasn't sure if it was database issue or not.. thx for correcting it.

That is how I fixed/work-around the issue..
I did a /reload
here are the addons I use..
![image](https://github.com/Questie/Questie/assets/1712842/8b62d3a2-892a-47b5-9e0c-fbaffec93582)

all are up to date as far as CurseForge addon manager says so.

**Comment by MyTechnoHunter** [comment]
> Definitely not database related - this is either a tracker error or something wrong with QuestieQuest where it doesn't watch mailbox updates for new items. A reload would force a full re-check of completion status for each quest, which would alleviate the issue.
> 
> It's also possible that we do have code established for watching the mailbox but it didn't fire because of other addon lag.

we just added mailbox code, next release will have it
