### ISSUE TITLE
Tracker resized automatically

### ISSUE THREAD

**Issue by Pengukeks** [Questie/Questie#4944]
WotLK Classic Questie v8.4.1

Tauren Druid Quest "Great Bear Spirit" 5930 [https://www.wowhead.com/wotlk/quest=5930/great-bear-spirit](url) resized my tracker to where it was showing the entire quest objective 
"Seek out the Great Bear Spirit and learn what it has to share with you about the nature of the bear."
in a single line.

"Lock Tracker" in Tracker options was and still is enabled if that even matters outside of manual resizing.

**Comment by MyTechnoHunter** [comment]
hover the sizer.. part of the update process reset your tracker to auto mode,

**Comment by MyTechnoHunter** [comment]
that being said.. i think it should have wrapped? specially singleton objectives.. 
@Dyaxler can we verify?

**Comment by Pengukeks** [comment]
I already manually made it smaller again. When I hover now it says Manual but idk if it said auto before. I didnt change any setting except resizing the tracker.

**Comment by Pengukeks** [comment]
regarding wrapping objective
[https://www.wowhead.com/wotlk/quest=6002/body-and-heart](url) doesnt wrap it cuts off with "...".

[https://www.wowhead.com/wotlk/quest=886/the-barrens-oases](url) wraps.
[https://www.wowhead.com/wotlk/quest=5722/searching-for-the-lost-satchel](url) wraps.
[https://www.wowhead.com/wotlk/quest=773/rite-of-wisdom](url) wraps.

**Comment by Dyaxler** [comment]
You'll have to be more specific. Quest Titles do not wrap. Only single Objectives with no number criteria... mostly Blizzard Completion text which is usually a body of text to tell you where to finish a quest or who to hand it in or the next step. No number tabs... items to be gathered ect.

**Comment by Pengukeks** [comment]
As of the main issue here it was the quest objective as stated causing the width resize. 
(Unless by some astronomical coincidence it resized to exactly the same width as that for another reason at the time of accepting the quest)

> "Seek out the Great Bear Spirit and learn what it has to share with you about the nature of the bear."

**Comment by Pengukeks** [comment]
I can't say if it was in Manual Mode at that time but Techno said it definitely reset to Auto Mode, I assume with 8.4.1 as I stated, which was released 29th, then 8.4.2 released on 30th already. I was on 8.4.1 at the time and I'm pretty sure I only just updated from 8.4.0->8.4.1 just before I started that session. But yes it resized to half my screens width to fit that text in one single line.

**Comment by MyTechnoHunter** [comment]
still got the quest?
would love a screenshot with you hovering the sizer nub, showing that quest and how wide it is..

**Comment by Pengukeks** [comment]
I don't have the quest anymore but I did take a screenshot of the width.
The usual place for my tracker is docked on the right side of the screen below the default minimap.
![RO9q9zb](https://github.com/Questie/Questie/assets/51298544/42b9dca0-1fc2-4549-98a5-a8a552b3332f)

**Comment by MyTechnoHunter** [comment]
yup, auto mode and for some reason that has a number at the end meaning its not completion it is different.. 
@Dyaxler you seeing this?

wth is with that quest?

**Comment by Dyaxler** [comment]
Yeah, that's NOT "Blizzard Completion Text"! That is the longest Objective I've NEVER seen! And it's got a "Number Criteria"... so yeah, unfortunately that is by design. :(

If you untrack "Great Bear Spirit" and if the Sizer Mode is in Auto, it'll shrink the Tracker width down to one of the other Objectives and wrap the two Quests that ARE "Blizzard Completion" test - Rite of Wisdom and The Barrens Oases.
