### ISSUE TITLE
Item quest tooltips are lost when zoning.

### ISSUE THREAD

**Issue by Cabro** [Questie/Questie#4946]
Before zoning:

![image](https://github.com/Questie/Questie/assets/1155017/231ddc7c-e699-46f3-8c3e-bc6461884508)

After zoning:

![image](https://github.com/Questie/Questie/assets/1155017/2056669d-653e-4728-b73d-d79afd17be83)

LE: this only seems to happen (so far) to quests without objectives. The quest shown in example, along with several other of similar type (give X item to Y npc, without objective, complete in quest log from accept) don't have the tooltips anymore on said items, but quests that have at least 1 objective still have the tooltips. Dry Times for example still has tooltips on the objective items

![image](https://github.com/Questie/Questie/assets/1155017/b66a0af7-b494-4ed4-af64-5907fe0897f2)
![image](https://github.com/Questie/Questie/assets/1155017/bd92c955-fe01-4097-819e-d4379ada5e48)

8.4.2

**Comment by MyTechnoHunter** [comment]
weird..

**Comment by Cabro** [comment]
Double checked, works!
