### ISSUE TITLE
Option to set Max Width for Tracker Frame

### ISSUE THREAD

**Issue by Starlynk1** [Questie/Questie#4956]
## Description
For the Tracker frame, would like to see the option to set a maximum width. This would help keep it from taking over quite a bit of screen space. Figure it could be coded similarly to the way the height is done and we can adjust the percentage. Also, this way we can use Auto mode and still have it set the way we want. Thanks!

**Comment by Dyaxler** [comment]
Auto Mode for the width has been around for over 4+ years and we've gotten a lot of feedback from players who want Auto Mode to automatically set the width to the widest line. This was the whole reason we created Manual Mode, so you can adjust the height and width to what you want which honestly, pretty much does the same thing as adding a slider to set a max width in Auto Mode. I only recently added Height into the mix to support scrolling. The only reason there is a slider in Tracker Options for the Height Ratio is so the player can decide how high they want the Tracker to Auto Size to before kicking in Scrolling. "Auto Height" doesn't affect wrapped text and Quest Titles getting truncated. Players don't want to see truncated text while using Auto Mode. Adding a slider for width JUST for Auto Mode would just add another layer of complexity and confusion for that feature. As it stands right now... the Height Ratio slider confused a lot of players at first.

**Auto Mode:** Set it and forget it. Width will keep the Tracker as SLIM as possible without text truncation. "Blizzard Completion" Objective text is automatically wrapped (along with a VERY select few Achievement Objectives). Height Ratio is used to turn on scrolling when the number of Tracked Quests exceeds the set height.

**Manual Mode:** Set a custom height and width. While actively sizing, everything in the Tracker goes blank except for the border and background (the border and background comes on if it's in a hidden state). This will allow you to clearly see where the Tracker will reside in your UI. Once you let go of the mouse button (if border and background were once hidden, they will return to your desired state) the width and height are set. If you track any quests that are "wider" than your desired width, the text is truncated. If you track a bunch of quests and they exceed your desired height, then scrolling kicks in automatically.

I'm not against adding more options to make the Tracker as customizable as possible but right now, we have WAY too many options to choose from in the Questie Config --> Tracker tab. We're in the midst of discussing a redesign/reorganization of how those options are laid out and I have a few ideas on how to trim those options even further and move them to a new area. I've been toying with the idea of putting them into a "Right Click" menu on the Tracker itself, so you don't have to open Questie Config.

Stay tuned!

**Comment by Starlynk1** [comment]
I had been using Manual Mode for width control, but it wasn't working correctly since the height couldn't be dragged down to where you want it to max out. Only option then was to use Auto so it would adjust height correctly. Just set it to manual mode tonight and it appears I missed some update notes that it was fixed for manual mode and dragging down the height. So going to close this one. Thanks!
