### ISSUE TITLE
Missing Quests on Map for Westfall

### ISSUE THREAD

**Issue by TheHulkingMango** [Questie/Questie#4965]
Missing Quests on Map for Westfall: 

The Following quests appear to be missing when they should be displayed: Attached is a snip of the map location where the quests are picked up/turned in.

[16] Keeper of the Flame
[19] The Coast Isn't Clear
[20] The Coastal Menace

Map Location:
----------------------
![image](https://github.com/Questie/Questie/assets/132087348/217cc720-48a0-402b-ab77-3f7892844d3d)

Quests:
-------------------------------
![image](https://github.com/Questie/Questie/assets/132087348/26091728-1b9a-4e33-ad59-1ca290a88cde)

**Comment by MyTechnoHunter** [comment]
i am not sure what i should be seeing.. the map shows targets for the quests? the path is the scale one.. the murlocs are the sword icons?
the keeper of the flame says complete and shows the ? mark where your circle is..
what am i missing?

**Comment by Cabro** [comment]
You already have the quests. The icons are objectives for those quests. What is the problem again?

**Comment by TheHulkingMango** [comment]
The problem is that Questie didn't show the quests initially as able to be grabbed so it appeared as though there weren't any quests on that side of the zone/no reason to go down to the Lighthouse. Only reason I have then was I saw them on the minimap.

**Comment by Cabro** [comment]
What race are you playing as?

**Comment by MyTechnoHunter** [comment]
> What race are you playing as?

those should be open to any alliance.. i dont think they are race locked?

**Comment by MyTechnoHunter** [comment]
i lied.. wowhead (if its still accurate ) says they are doable by horde too..

**Comment by TheHulkingMango** [comment]
I'm playing as a Human

**Comment by TheHulkingMango** [comment]
Human Warlock

**Comment by Muehe** [comment]
@TheHulkingMango Just checked this with a lvl 60 on the Era PTR, and they show for me there. Not sure what's going on. :shrug: 

![Screenshot_20230824_191802](https://github.com/Questie/Questie/assets/8838573/848bcbeb-e092-47a1-9d85-7d689bfc7266)

Could it be that you checked the map immediately after login/reload? It takes some time for the map to be populated with all the icons.

**Comment by BreakBB** [comment]
Assume this is no longer an issue, as neither Muehe not me were able to reproduce it.
