### ISSUE TITLE
New lua error with the latest update (today)

### ISSUE THREAD

**Issue by Pocokk** [Questie/Questie#4972]
1x Questie/Modules/Quest/QuestieQuest.lua:746: attempt to get length of a nil value
[string "@Questie/Modules/Quest/QuestieQuest.lua"]:746: in function `AddFinisher'
[string "@Questie/Modules/Quest/QuestieQuest.lua"]:1245: in function `PopulateObjectiveNotes'
[string "@Questie/Modules/Quest/QuestieQuest.lua"]:656: in function `GetAllQuestIds'
[string "@Questie/Modules/Quest/QuestEventHandler.lua"]:508: in function <...eQuestie/Modules/Quest/QuestEventHandler.lua:507>

Locals:
self = <table> {
 autoBlacklist = <table> {
 }
 ShouldShowQuestNotes = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:347
 AcceptQuest = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:370
 HideQuest = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:359
 ToggleNotes = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:100
 PopulateQuestLogInfo = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:1274
 AbandonedQuest = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:493
 SmoothReset = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:240
 PopulateObjectiveNotes = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:1235
 availableQuests = <table> {
 }
 _isResetting = true
 _resetNeedsAvailables = false
 UnhideQuest = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:364
 GetAllQuestIdsNoObjectives = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:669
 DrawDailyQuest = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:1636
 GetAllQuestIds = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:634
 PopulateObjective = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:866
 CompleteQuest = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:469
 AddFinisher = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:718
 ResetAutoblacklistCategory = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:91
 UpdateObjectiveNotes = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:694
 CalculateAndDrawAvailableQuestsIterative = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:1625
 UpdateQuest = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:535
 Initialize = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:82
 GetAllLeaderBoardDetails = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:1369
 SetObjectivesDirty = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:624
 ClearAllNotes = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:199
 private = <table> {
 }
}
quest = <table> {
 WasComplete = true
 startedBy = <table> {
 }
 IsTrivial = <function> defined @Questie/Database/QuestieDB.lua:677
 questFlags = 0
 level = 60
 requiredSpell = 0
 nextQuestInChain = 0
 IsRepeatable = false
 requiredClasses = 2
 questLevel = 60
 Id = 7501
 specialFlags = 0
 parentQuest = 0
 name = "The Light and How To Swing It"
 IsComplete = <function> defined @Questie/Database/QuestieDB.lua:672
 requiredLevel = 54
 objectives = <table> {
 }
 requiredSpecialization = 0
 Description = <table> {
 }
 Zone = 2557
 requiredRaces = 0
 trackTimedQuest = false
 sourceItemId = 18359
 reputationReward = <table> {
 }
 LocalizedName = "The Light and How To Swing It"
 finishedBy = <table> {
 }
 objectivesText = <table> {
 }
 ObjectiveData = <table> {
 }
 SpecialObjectives = <table> {
 }
 isComplete = true
 zoneOrSort = 2557
 Finisher = <table> {
 }
 Starts = <table> {
 }
 Objectives = <table> {
 }
}
questId = 7501
finisher = <table> {
 spawns = <table> {
 }
 type = "monster"
 minLevel = 60
 friendlyToFaction = "AH"
 id = 14382
 questEnds = <table> {
 }
 friendly = true
 factionID = 32
 name = "Lorekeeper Mykos"
 minLevelHealth = 2442
 maxLevel = 60
 maxLevelHealth = 2442
 npcFlags = 2
 zoneID = 2557
 rank = 1
}
key = "m_14382"
(*temporary) = nil
(*temporary) = <table> {
 lastGametooltipCount = 0
 lookupKeyByQuestId = <table> {
 }
 lastGametooltipType = "object"
 lookupByKey = <table> {
 }
 lastGametooltip = ""
 GetTooltip = <function> defined @Questie/Modules/Tooltips/Tooltip.lua:162
 RemoveQuest = <function> defined @Q

**Comment by Cabro** [comment]
What quest causes this error?

**Comment by Pocokk** [comment]
I don't know, I logged in and happened out of nowhere.

**Comment by Pocokk** [comment]
I didn't pick up any (new) quest in the last week or so.

**Comment by Pocokk** [comment]
Same error again, I just used my HS and when the loading screen was complete, got the error.

**Comment by Pocokk** [comment]
Unfortunately it wasn't fixed with the latest update.

**Comment by Dyaxler** [comment]
Hmmm... I think that line needs a nil check. It's quite possible that table can be nil.

REF: https://github.com/Questie/Questie/commit/864278f2bf0a77bba40ca1daaf8ae0881a6c6748

```lua
if #QuestieTooltips:GetTooltip(key) > 1 then
```
