### ISSUE TITLE
questKeys.parentQuest has to be table. There are quests with more than 1 parentQuest

### ISSUE THREAD

**Issue by Cabro** [Questie/Questie#4973]
https://www.wowhead.com/wotlk/quest=3375/replacement-phial <--- this quest is child quest for 2201 and 2204. I cannot assign it as childquest to both of them.
I can fix the correction files and turn the int into tables, but can't fix the way it reads the questKeys.parentQuest

8.6.0

**Comment by Dyaxler** [comment]
Check out this: https://github.com/cmangos/issues/wiki/Quest_template#examples

I'm not sure you're using `parentQuest` and `childQuests` keys correctly.

Might have to put the whole quest chain into a flow chart to figure it out. But there is some useful hints in some of the comments:
https://www.wowhead.com/wotlk/quest=3375/replacement-phial#comments:id=3154153

**Comment by Cabro** [comment]
OK, tell me how i can put one quest to be childquest for 2 other quests :)

**Comment by Dyaxler** [comment]
```lua
-- Start of Quest Chain --

['The Shattered Necklace' (2198)]
`startedBy` = `itemStart` = 'Shattered Necklace' (7666)
`finishedBy` = `creatureEnd` = 'Talvash del Kissel' (6826)
`preQuestSingle` = nil

['Lore for a Price' (2199)]
`startedBy` = `creatureStart` = 'Talvash del Kissel' (6826)
`finishedBy` = `creatureEnd` = 'Talvash del Kissel' (6826)
`preQuestSingle` = 2198

['Back to Uldaman' (2200)]
`startedBy` = `creatureStart` = 'Talvash del Kissel' (6826)
`finishedBy` = `creatureEnd` = 'Remains of a Paladin' (6912)
`sourceItemId` = 7667 -- <-- sourceItemId is first provided by the quest giver (should you loose this item - do repeatable quest: Replacement Phial (3375))
`preQuestSingle` = 2199

['Replacement Phial' (3375)]
`startedBy` = `creatureStart` = 'Talvash del Kissel' (6826)
`finishedBy` = `creatureEnd` = 'Talvash del Kissel' (6826)
`preQuestSingle` = 2199 -- <-- This key should be added in a quest correction so that it doesn't appear available until 2199 is complete
`nextQuestInChain` = 2361 -- <-- This key should be added in a quest correction so that it no longer shows as available once 2361 is complete

['Find the Gems' (2201)]
`startedBy` = `creatureStart` = 'Remains of a Paladin' (6912)
`finishedBy` = `objectEnd` = 'Talvashs Scrying Bowl' (112877) -- <-- spawned from using Talvash's Phial of Scrying (7667)
`sourceItemId` = 7667 -- <-- sourceItemId is first provided by the quest giver from 2200 (should you loose this item - do repeatable quest: Replacement Phial (3375))
`preQuestSingle` = 2200

['Restoring the Necklace' (2204)]
`startedBy` = `objectStart` = 'Talvashs Scrying Bowl' (112877) -- <-- spawned from using Talvash's Phial of Scrying (7667)
`finishedBy` = `creatureEnd` = 'Talvash del Kissel' (6826)
`preQuestSingle` = 2201

['Restoring the Necklace' (2361)]
`startedBy` = `creatureStart` = 'Talvash del Kissel' (6826)
`finishedBy` = `creatureEnd` = 'Talvash del Kissel' (6826)
`preQuestSingle` = 2204

-- End of Quest Chain --
```

The only thing that looks needing to be fixed is the quest: Replacement Phial (3375) notated above and how those keys affect visibility. 

Remove all the `parentQuest` & `childQuest` keys you added... they aren't needed.

**Comment by Cabro** [comment]
Yes, this is close enough of a fix. Quest 'Replacement Phial' would show as available when it's not (between quests), which is why i didn't want to go this route and asked for table for parentQuest.

**Comment by Dyaxler** [comment]
Not sure I fully understand what you're trying to do. 

Replacement Phial (3375) shouldn't show as available on the Map/Minimap for Questie unless you're done with Lore for a Price (2199) because upon accepting Back to Uldaman (2200) you're given a Phial. You need to do the quest Replacement Phial (3375) to replace it if you lose it for some reason. If you abandon Back to Uldaman (2200) then you won't get another Phial (at least if memory serves). You can't complete the next quest Find the Gems (2201) and you can't start Restoring the Necklace (2204) without the Phial. Once you finish Restoring the Necklace (2361) then Replacement Phial (3375) should no longer show as available. We have to do this because there is a specialFlag in the DB for 3375 that says that it's repeatable.

**Comment by Dyaxler** [comment]
@Cabro - need anymore help with this?
