### ISSUE TITLE
Not seeing quest markers/givers in dungeons on minimap

### ISSUE THREAD

**Issue by Rastahunden** [Questie/Questie#4974]
Like the title says, im not seeing markers for quest objectives or givers inside dungeons. All my options are as they should. 
The one quest im specifically thinking of is https://www.wowhead.com/classic/quest=6561/blackfathom-villainy

8.6.0
Classic Era

**Comment by BreakBB** [comment]
This is how the game is and Questie (or any other addon) can not work around this. The game does not allow to get the position of the player inside a dungeon, sorry.

For Wotlk Blizzard changed this a bit, so it’s possible to draw on the new dungeon maps at least.

**Comment by xenoterracide** [comment]
could questie work with atlas which has dungeon maps?

**Comment by BreakBB** [comment]
That would be a huge task to complete @xenoterracide - I fear there is too little to gain for this to be some high priority. Feel free to open up a new Feature request though.
