### ISSUE TITLE
'The Mark of Vashj'-quest incorrectly showing

### ISSUE THREAD

**Issue by TheMEFFER** [Questie/Questie#4979]
## Description
The quest 'The Mark of Vashj' (obtained from heroic Slave Pens, from mob "Skar'this the Heretic" is shown (for Death Knights, at least) on the map as being an available quest in WotLK Classic at level 80.
According to a comment from 'DuggyDale' on the Wowhead comment section of the quest, from patch 3.1.3 (original WotLK, dated 2009/07/11): "I could pick up the quest at level 70 but as soon as I hit 71 I could no longer get the quest. Better get it while you can before 71."
As such, this quest should not be available post-70, and definitely not showing as available at 80.
- Can also confirm that it is not available for pickup, as I was just 30 minutes ago in Slave Pens heroic to try and pick it up. I'm a perfectionist who decided to do all available quests, and with about 20 left total I obviously also went for this one, but to no avail.

## Wowhead link
https://www.wowhead.com/wotlk/quest=10900/the-mark-of-vashj

## Screenshots
![WoWScrnShot_062023_220511](https://github.com/Questie/Questie/assets/36070686/536af47a-58b2-4471-97eb-310bf41a9c49)

## Questie & WoW version
Questie v8.6.0
WotLK Classic

**Comment by Cabro** [comment]
This one should also be fixed when the PVP quests will be fixed. Soon™

**Comment by BreakBB** [comment]
Yeah Cabro is right on this one. @TheMEFFER Questie currently can't hide quests because of a "max level" requirement. It's on our list, not really high priority though.
