### ISSUE TITLE
Bug/Error After Update

### ISSUE THREAD

**Issue by aristoblis** [Questie/Questie#4996]
After updating to v8.7.1 I keep getting this error:

[string "=[C]"]: in function `next'
[string "@Questie/Modules/Quest/QuestieQuest.lua"]:303: in function `?'
[string "@Questie/Modules/Quest/QuestieQuest.lua"]:330: in function <Questie/Modules/Quest/QuestieQuest.lua:329>

Locals:
(*temporary) = <table> {
 13288 = <table> {
 }
}
(*temporary) = 13392

**Comment by Dyaxler** [comment]
Possibly related to #4970 

@aristoblis need more details on when this error popped. Were you logging in, reloadUI? In a Battleground group or Raid group. Before or after you entered an instance?

**Comment by aristoblis** [comment]
Were you logging in, reloadUI? Of course I, otherwise the addon wouldn't have been loaded.  I did relaod UI also, still kept happening.  I use Bugsack to capture all my addon errors and it just kept counting up and up.
In a Battleground group or Raid group. No group, just as soon as I logged in the errors started ticking up.  It ticked 2-3 times p[er second.  By the time I stopped the addon and reloaded my UI it had ticked up to 14k+.
Before or after you entered an instance? While I was in Dalaran

**Comment by Necro87** [comment]
this the same issue? 

Questie/Modules/Quest/QuestieQuest.lua:751: attempt to index a nil value
[string "@Questie/Modules/Quest/QuestieQuest.lua"]:751: in function `AddFinisher'
[string "@Questie/Modules/Quest/QuestieQuest.lua"]:557: in function `UpdateQuest'
[string "@Questie/Modules/Quest/QuestieQuest.lua"]:301: in function `?'
[string "@Questie/Modules/Quest/QuestieQuest.lua"]:330: in function <Questie/Modules/Quest/QuestieQuest.lua:329>

Locals:
self = <table> {
 autoBlacklist = <table> {
 }
 ShouldShowQuestNotes = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:347
 AcceptQuest = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:371
 HideQuest = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:359
 ToggleNotes = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:100
 PopulateQuestLogInfo = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:1279
 AbandonedQuest = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:494
 SmoothReset = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:240
 PopulateObjectiveNotes = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:1240
 availableQuests = <table> {
 }
 _isResetting = true
 _resetNeedsAvailables = true
 _nextRestQuest = 13823
 UnhideQuest = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:365
 GetAllQuestIdsNoObjectives = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:674
 DrawDailyQuest = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:1651
 GetAllQuestIds = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:637
 PopulateObjective = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:871
 CompleteQuest = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:470
 AddFinisher = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:723
 ResetAutoblacklistCategory = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:91
 UpdateObjectiveNotes = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:699
 CalculateAndDrawAvailableQuestsIterative = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:1640
 UpdateQuest = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:536
 Initialize = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:82
 GetAllLeaderBoardDetails = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:1384
 SetObjectivesDirty = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:627
 ClearAllNotes = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:199
 private = <table> {
 }
}
quest = <table> {
 startedBy = <table> {
 }
 IsTrivial = <function> defined @Questie/Database/QuestieDB.lua:677
 questFlags = 72
 level = 80
 requiredSpell = 0
 nextQuestInChain = 0
 IsRepeatable = false
 requiredClasses = 0
 questLevel = 80
 Id = 13823
 specialFlags = 0
 preQuestSingle = <table> {
 }
 name = "Heroic: Thorim's Sigil"
 IsComplete = <function> defined @Questie/Database/QuestieDB.lua:672
 requiredLevel = 80
 objectives = <table> {
 }
 requiredSpecialization = 0
 Description = <table> {
 }
 Zone = 4273
 requiredRaces = 0
 trackTimedQuest = false
 SpecialObjectives = <table> {
 }
 sourceItemId = 0
 Finisher = <table> {
 }
 LocalizedName = "Heroic: Thorim's Sigil"
 inGroupWith = <table> {
 }
 objectivesText = <table> {
 }
 parentQuest = 0
 ObjectiveData = <table> {
 }
 isComplete = true
 zoneOrSort = 4273
 Starts = <table> {
 }
 finishedBy = <table> {
 }
 Objectives = <table> {
 }
}
questId = 13823
finisher = <table> {
 subName = ""
 questEnds = <table> {
 }
 maxLevel = 80
 maxLevelHealth = 75600
 npcFlags = 2
 zoneID = 4657
 type = "monster"
 friendlyToFaction = "AH"
 id = 33957
 friendly = true
 factionID = 35
 minLevel = 80
 minLevelHealth = 75600
 spawns = <table> {
 }
 questStarts = <table> {
 }
 name = "Prospector Loren"
 rank = 1
}
key = "m_33957"
(*temporary) = nil
(*temporary) = <table> {
 RegisterQuestStartTooltip = <function> defined @Questie/Modules/Tooltips/Tooltip.lua:52
 lastGametooltipType = "item"
 lastGametooltip = ""
 lookupKeyByQuestId = <table> {
 }
 GetTooltip = <function> defined @Int

**Comment by Dyaxler** [comment]
@Necro87 No... different issue.

REF: #4999 

This fix has been checked into Master but hasn't made it into a release yet.
