### ISSUE TITLE
New lua error upon accepting summon in raid group

### ISSUE THREAD

**Issue by Pocokk** [Questie/Questie#4999]
1x Questie/Modules/Quest/QuestieQuest.lua:751: attempt to index a nil value
[string "@Questie/Modules/Quest/QuestieQuest.lua"]:751: in function `AddFinisher'
[string "@Questie/Modules/Quest/QuestieQuest.lua"]:1250: in function `PopulateObjectiveNotes'
[string "@Questie/Modules/Quest/QuestieQuest.lua"]:659: in function `GetAllQuestIds'
[string "@Questie/Modules/Quest/QuestEventHandler.lua"]:542: in function <...eQuestie/Modules/Quest/QuestEventHandler.lua:539>        

Locals:
self = <table> {
 autoBlacklist = <table> {
 }
 ShouldShowQuestNotes = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:347
 AcceptQuest = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:371
 HideQuest = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:359
 ToggleNotes = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:100
 PopulateQuestLogInfo = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:1279
 AbandonedQuest = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:494
 SmoothReset = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:240
 PopulateObjectiveNotes = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:1240
 availableQuests = <table> {
 }
 _isResetting = true
 _resetNeedsAvailables = false
 UnhideQuest = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:365
 GetAllQuestIdsNoObjectives = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:674
 DrawDailyQuest = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:1651
 GetAllQuestIds = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:637
 PopulateObjective = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:871
 CompleteQuest = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:470
 AddFinisher = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:723
 ResetAutoblacklistCategory = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:91
 UpdateObjectiveNotes = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:699
 CalculateAndDrawAvailableQuestsIterative = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:1640
 UpdateQuest = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:536
 Initialize = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:82
 GetAllLeaderBoardDetails = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:1384
 SetObjectivesDirty = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:627
 ClearAllNotes = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:199
 private = <table> {
 }
}
quest = <table> {
 requiredSourceItems = <table> {
 }
 startedBy = <table> {
 }
 IsTrivial = <function> defined @Questie/Database/QuestieDB.lua:677
 questFlags = 136
 level = 75
 requiredSpell = 0
 nextQuestInChain = 12152
 IsRepeatable = false
 extraObjectives = <table> {
 }
 questLevel = 75
 Id = 12137
 specialFlags = 0
 parentQuest = 0
 name = "Chill Out, Mon"
 IsComplete = <function> defined @Questie/Database/QuestieDB.lua:672
 requiredLevel = 73
 objectives = <table> {
 }
 requiredSpecialization = 0
 Description = <table> {
 }
 Zone = 394
 WasComplete = true
 requiredRaces = 0
 trackTimedQuest = false
 SpecialObjectives = <table> {
 }
 sourceItemId = 0
 Starts = <table> {
 }
 LocalizedName = "Chill Out, Mon"
 preQuestSingle = <table> {
 }
 finishedBy = <table> {
 }
 ObjectiveData = <table> {
 }
 Finisher = <table> {
 }
 isComplete = true
 zoneOrSort = 394
 objectivesText = <table> {
 }
 requiredClasses = 0
 Objectives = <table> {
 }
}
questId = 12137
finisher = <table> {
 subName = ""
 questEnds = <table> {
 }
 maxLevel = 70
 maxLevelHealth = 10329
 npcFlags = 3
 zoneID = 394
 type = "monster"
 friendlyToFaction = "AH"
 id = 26886
 friendly = true
 factionID = 35
 minLevel = 70
 minLevelHealth = 10329
 spawns = <table> {
 }
 questStarts = <table> {
 }
 name = "Kraz"
 rank = 0
}
key = "m_26886"
(*temporary) = nil
(*temporary) = <table> {
 RegisterQuestStartTooltip = <function> defined @Questie/Modules/Tooltips/Tooltip.lua:52
 lookupKeyByQuestId = <table> {
 }
 lastGametooltipType = "item"
 lastGametooltip = ""
 lastFrameName = "GameTool

**Comment by Pocokk** [comment]
Latest version, every quest is the same as before yesterday/last week etc.

**Comment by Dyaxler** [comment]
This was my bugger... I was checking a sub-key before checking to make sure the table itself wasn't nil.

This was erroring on the new "duplicate tooltip check" code.

**Comment by Pocokk** [comment]
thank you
