### ISSUE TITLE
Add toggle to restore previous completed quest functionality in tracker

### ISSUE THREAD

**Issue by celerium3000** [Questie/Questie#5000]
Previously Questie showed 'Completed' in the quest objectives for the completed quest, and the word Completed was in a different color too.

Now questie is showing 'Return to X' for completed quests.  It is also in the same color as all the other quest objectives.  This makes it difficult to differentiate completed quests from in progress quests.

My preference is that knowing what is completed is more important than where to go to turn in the quest; if I need to know where to go I can just open the map or click the quest in the tracker to open the quest log.

Please add a toggle to optionally restore the old functionality for completed quests in the tracker.

**Comment by toemas625** [comment]
Questie does not show "Completed" under the quests for me anymore in version 8.7.1 - is it a toggle now?

**Comment by MyTechnoHunter** [comment]
not that i know of.. need to dig into this..

**Comment by Dyaxler** [comment]
Sooo... not a "TOGGLE" option @celerium3000.

Read the Pull Request linked above. I included screenshots and detailed notes.

**Comment by Cabro** [comment]
I will play the devil's advocate here, because this is what people what: to show "Quest Complete" when the quest is complete. If you want to make a toggle to instead say completion text, by all means. But we want the old way, simple and good. Oh, and available for all coloring types, not only minimalistic :P you can hate me

**Comment by toemas625** [comment]
> I will play the devil's advocate here, because this is what people what: to show "Quest Complete" when the quest is complete. If you want to make a toggle to instead say completion text, by all means. But we want the old way, simple and good. Oh, and available for all coloring types, not only minimalistic :P you can hate me

Yep this is what I would personally like, thank you!

**Comment by toemas625** [comment]
I wanted to say thank you - this was fixed perfectly!
