### ISSUE TITLE
Quest zone error Quest 1133

### ISSUE THREAD

**Issue by Nerillida** [Questie/Questie#5005]
Quest 1133 Journey to Astranaar

In Classic Era - the quest giver is in Theramore. Blizzard's quest ;log shows this as a Dustwallow Marsh quest.

In TBC - the quest giver is in Auberdine. Blizzard's quest log shows this as a Darkshore quest quest.

Questie shows this as a Darkshore quest in Classic Era.

**Comment by BreakBB** [comment]
Hey @Nerillida does Questie show the icon correct on the map and just the zone in the Tracker is wrong? Or are the icons also positioned wrong?

**Comment by Nerillida** [comment]
On Classic Era, position on map is fine, it's just the tracker that's "wrong".

Not played tbc for a while, person who mentioned that to me didn't say that there was a problem.

**Comment by BreakBB** [comment]
Thanks for the fast response, should be easy to fix 👍🏻
