### ISSUE TITLE
(10) Desperate Prayer (priests)

### ISSUE THREAD

**Issue by linda535** [Questie/Questie#5006]

**Comment by linda535** [comment]
Sorry if this is disjointed. I am at Goldshire inn and Questie shows (10) Desperate Prayer is available. My priest is lvl 10. I do not have Desperate Prayer so I assume she hasn't done it yet. She won't talk to me. I will go back to SW to check if it's only available on that priest trainer, but please check this. Someone in 2008 said it'd been removed by Blizz... Thanks!

**Comment by BreakBB** [comment]
Hey @linda535 which of these quests is it?

https://www.wowhead.com/wotlk/quest=5635/desperate-prayer (I assume this one)
https://www.wowhead.com/wotlk/quest=5637/desperate-prayer
https://www.wowhead.com/wotlk/quest=5634/desperate-prayer
https://www.wowhead.com/wotlk/quest=5639/desperate-prayer

You can enable the questIds in the advanced settings of Questie. `/questie` -> Advanced -> Show Quest IDs

Knowing the ID would help us a lot.

**Comment by BreakBB** [comment]
Oh also @linda535 are you playing Classic Era or Wotlk?

**Comment by linda535** [comment]
It’s WotLK Classic. I don't know if that's Classic Era or not. And I just discovered why I can't get it. It requires 10 talent points in HOLY before you can get it. I have no idea how that works (Blizz!!!) because you only get one point per level starting at lvl 10.
Yes, https://www.wowhead.com/wotlk/quest=5635/desperate-prayer 
It also shows available with the SW priest trainer.

**Comment by BreakBB** [comment]
Ouch... That is a quest requirement Questie doesn't cover really atm.

Any idea @Yttrium-tYcLief

**Comment by linda535** [comment]
Yes, I know it's NOT Questie, but is there any way you can note this?  Blizz has several conundrums like this. Like cooking recipes you can use the product of, but you can't cook it because of level blocking, or unless you buy the mats, you can't make gear for your own alt that has that profession because there's no way to gather fast enough.
Thanks for an excellent addon!

**Comment by BreakBB** [comment]
Well from the API perspective there is a way, but this is a big edge case. Meaning only a few (or just this one) requires a certain amount of skill points spent in a skill tree. Therefore Questie just doesn't cover it atm.

It is possible for us to add, but not _that_ easy.

**Comment by MyTechnoHunter** [comment]
er.. out of curiosity where are you seeing 10 in holy? i dont see it in either comments or the quest info..
![image](https://github.com/Questie/Questie/assets/55214545/f51eaaa5-5318-418e-aa76-53a367e51bc0)

**Comment by MyTechnoHunter** [comment]
this quest is for a racial dwarf/human quest... but the comments do show its been removed?

**Comment by linda535** [comment]
Ok, so I guess the only way to get Desperate Prayer is to put those 10 points - AT LVL 20 MINIMUM! - into Holy...
Thanks so much for checking.

**Comment by linda535** [comment]
![desp prayer](https://github.com/Questie/Questie/assets/54631734/3bf440f2-dcfc-4542-be0b-5362b1c26c81)
And since you don't start accruing talent points until lvl 10...

**Comment by Cabro** [comment]
I doubt that's the trigger for the quest. 10 talent points.
You need to be correct race and level and expansion.

**Comment by linda535** [comment]
I don't think it's the trigger. I think it's a requirement.

**Comment by linda535** [comment]
Thanks for looking at it.

**Comment by Cabro** [comment]
> I don't think it's the trigger. I think it's a requirement.

Prior to wotlk you had to do quest for it (if memory is not rusty). In wotlk it's a talent.

**Comment by linda535** [comment]
Exactly. I just leveled a couple of priests, so it's pretty fresh in my mind. I just didn't realize the talents had changed so much, dangit. I still think it stinks that it requires essentially lvl 20 AND Holy spec exclusively.

**Comment by BreakBB** [comment]
Oh I see. Well then we should hide these quests in Wotlk 🤷🏻‍♂️

**Comment by Cabro** [comment]
I see there are 6 IDs for Desperate Prayer quests

**Comment by linda535** [comment]
> Oh I see. Well then we should hide these quests in Wotlk 🤷🏻‍♂️
That could save some players a lot of time - going (running, not riding, lol) to the trainers (in my case, Goldshire and SW) and looking up on wowhead AND seeing conflicting info. I don't know about the 6 IDs.

**Comment by BreakBB** [comment]
Fixed in b16a36d9ac3761246b5d8f64e98a8562a92858de and 9a80cabdcb5a629eb7b487e87870bbeec9b8012e
