### ISSUE TITLE
"Quest Complete!" text is not hidden when using "Auto Minimize Completed Quests".

### ISSUE THREAD

**Issue by Cabro** [Questie/Questie#5010]
I honestly didn't have time to test it. You must hate me by now <3
This only happens for quests without objectives - aka "go talk to that NPC over there"-kind of quests

![image](https://github.com/Questie/Questie/assets/1155017/f4edd290-f535-49c4-b41c-0a550cf64a0a)

8.8.0

**Comment by Dyaxler** [comment]
Sigh... I was afraid of that.

I forgot to check that logic path because "Blizzard Completion Text" was immune to the "Auto Minimize Completed" quests. I didn't want that text hidden.

I'll get a PR going...

**Comment by Dyaxler** [comment]
That should do it...

**Comment by Cabro** [comment]
Fix confirmed 👍

**Comment by suPROman64** [comment]
Hi. I have downloaded the most recent version of Questie (v8.8.1) for WoW Classic and am still experiencing this issue. Toggling "Auto Minimize Completed Quests" in the Questie settings does not minimize completed quests for talking to an NPC. Please let me know how to resolve this issue as this forum says it's fixed already. Thank you

**Comment by Dyaxler** [comment]
@suPROman64 - The fix for this issue hasn't made it into a release yet.
