### ISSUE TITLE
Is there gonna be an option to have quests completed show as they did in 8.7.2?

### ISSUE THREAD

**Issue by Rastahunden** [Questie/Questie#5012]
I want to see the text when i have a completed quest or if there's no quest objective to keep track of as it were in 8.7.2 instead of just "Quest Complete!" Is that gonna be possible or do i have to roll back to 8.7.2?

**Comment by Dyaxler** [comment]
This option was merged and released in v8.8.0: https://github.com/Questie/Questie/pull/5004

**Comment by Muehe** [comment]
@Rastahunden From how I understand the new options, setting "Objective color" to anything but "Minimalistic" should display the old text.

**Comment by Dyaxler** [comment]
If you click the link above, it'll show you exactly which option does... with screenshots. But... the

`Based on user feedback we've added a new toggle to Questie Config --> Tracker. "Hide Blizzard Completion Text" this will allow you to use the old Questie Tags for completed or failed quests vs the "Blizzard Completion Text" in any Objective Color profile.`

...bullet point seems to have been missed by some folks.

**Comment by Rastahunden** [comment]
Yeah i got it all from the first answer. I probably didn't have any completed quests open at the time when i first tried out those "Objective color" options, so i didn't see exactly what it did. It's all good now, thought this issue was closed so i didn't report back. Thanks for the help
