### ISSUE TITLE
What happened to the "Compress" option for completed quests (tracker)?

### ISSUE THREAD

**Issue by Painstormx** [Questie/Questie#5020]
v8.8.1 - Classic Era
In previous versions there used to be an option for the tracker to show the completed quests in "compressed" mode, i.e. a completed quests were shown as "xxxxxxx (Completed)" in one line.
Can't see that option any more and now every completed quest shows with an extra line with a green "Quest Complete!" text.

**Comment by MyTechnoHunter** [comment]
Tracker option,  check "auto minimize completed quests"

**Comment by Painstormx** [comment]
I thought it was that, but that option doesn't do anything at all. Tried disabling/enabling/reloading, but nothing changed.

**Comment by Painstormx** [comment]
Some options, like  "Hide Blizzard Completion Text" are disabled like you can see in my screenshot.
I don't know what controls that option, but it seems permanently disabled, so I can't change it.
Tried flipping all the other options, but it stays disabled.

**Comment by Painstormx** [comment]
Tried again, but the extra "Quest Complete!" line is not going away, no matter the combination of "Hide Blizzard Completion Text" and "Auto Minimize Completed Quests".
![image](https://github.com/Questie/Questie/assets/41920633/4070d0a0-efb0-4e4d-bfff-9cf4b7d478bf)

**Comment by Dyaxler** [comment]
Hmmm... must have some of the flags set wrong. I'll look into it.

**Comment by MyTechnoHunter** [comment]
![WoWScrnShot_070523_132231](https://github.com/Questie/Questie/assets/55214545/d6991d42-3cd0-4b5c-9758-3abf34a29dac)

i tried to match their settings? seems to work fine on my end..

**Comment by Cabro** [comment]
I think he has the quests without objectives. Those are special, i'm not sure if the fix is on live or not.

**Comment by MyTechnoHunter** [comment]
er.. d'oh!
