### ISSUE TITLE
The Legend of Stalvan shows complete even though it is not

### ISSUE THREAD

**Issue by Painstormx** [Questie/Questie#5021]
v8.8.1 - Classic Era
More specifically this quest in the questline:
https://www.wowhead.com/classic/quest=67/the-legend-of-stalvan

It shows in the tracker as complete, even though it is not.
It is not complete in the Blizzard quest log either.
Same issue with the next quest in the questline.

**Comment by Cabro** [comment]
This is how Questie deals with quests without objectives. They are labeled as complete, because... they are.

**Comment by BreakBB** [comment]
Then this seems to be one of these quests without a real objective, but still has one.

So you interact with the chest and then the quest will be complete and you can turn it back in at the NPC that you got the quest from, right @Painstormx ?

**Comment by Painstormx** [comment]
If the chest is actually both the hidden objective and the finisher, then @Cabro is correct and Questie is handling it fine.
I just checked a char on this quest and Questie does show a yellow '?' in the Moonbrook Schoolhouse.
