### ISSUE TITLE
Quest: Cardinal Ruby shows not-completed

### ISSUE THREAD

**Issue by rgeraads** [Questie/Questie#5024]
## Description
The quest Cardinal Ruby whos as available even though I have completed it. I ran the command `/run print(C_QuestLog.IsQuestFlaggedCompleted(14151))` to see if it registered as completed but it returned `false`. So I'm not sure if this is a questie related quest issue, but maybe the quest id is different from what is stated on wowhead?

## Wowhead link
https://www.wowhead.com/wotlk/quest=14151/cardinal-ruby

## Screenshots
![image](https://github.com/Questie/Questie/assets/6044164/d3d4c9d3-92f9-4587-a160-7befb5c79151)

## Questie & WoW version
Questie version: 8.8.1
WoW: WotLK

**Comment by Cabro** [comment]
This should have been fixed in https://github.com/Questie/Questie/pull/5016/commits/a124f71eb54db8a6e2d9b4c892b7db55aed54a21 . Only waiting for the green light to be pushed to live.
