### ISSUE TITLE
Questie showing breadcrumb quest as available

### ISSUE THREAD

**Issue by Davyd2400** [Questie/Questie#5025]
The breadcrumb quest Blackwatch (https://www.wowhead.com/wotlk/quest=13106/blackwatch) is shown as available on the map, but cannot be picked up as follow-up quests have already been completed.

**Comment by Cabro** [comment]
Run this command, do you get `true` or `false`?
/run print(C_QuestLog.IsQuestFlaggedCompleted(12897))

**Comment by Cabro** [comment]
I also noticed something erroneous with those quests, Where Are They Coming From? and some other
Those quest chains need to be polished, and i didnt get to that zone yet :(

**Comment by Davyd2400** [comment]
I got true.

**Comment by Cabro** [comment]
Should be fixed
