### ISSUE TITLE
Tooltips for items that are part of quests without objectives are completely gone.

### ISSUE THREAD

**Issue by Cabro** [Questie/Questie#5027]
This quest is just accept now:
![image](https://github.com/Questie/Questie/assets/1155017/6ed4c04e-e50c-4f59-8a7a-c89073573988)

8.8.1 wotlk

**Comment by Dyaxler** [comment]
Run `/dump QuestieDB:GetQuest(QuestID).Objectives` ... you'll find that there is no data because it's in a completed state.

`/dump QuestieDB:GetQuest(QuestID):IsComplete()` returns 1.

We can't build tooltips if the Objective table is empty.

**Comment by Cabro** [comment]
But it was working in the past.

**Comment by Dyaxler** [comment]
If you go back to those quests... if you have them and run those dumps above they will return Objectives. There are a LOT of quests that "appear" to be complete but are flagged = 0 not 1. The ones that are flagged 0 will still have valid Objectives in the QuestDB return. Those will have tooltips.

**Comment by Cabro** [comment]
OK, but in the past, the other quests were also showing tooltips. Was easier to notice if an item was for an active quest or was leftover from a quest that had been turned in. Blizzard's spaghetti code.

**Comment by Dyaxler** [comment]
I didn't change the way tooltips were created with all the bug fixes... even the Blizzard API's return blank info when a quest is in a complete state. There really is nothing I can do. Maybe you're more aware of the tooltips because you're hyper focused on looking for things out of whack here recently. :D

**Comment by Cabro** [comment]
They stopped showing just recently. They were showing fine until a few days ago :(

**Comment by Cabro** [comment]
https://github.com/Questie/Questie/assets/1155017/410f767e-ccbd-49c8-ab22-8de5ea80c3f7

The tooltip was showing before, it's not me that is crazy, and it would be better to prevent these situations, since it's hard enough as it is for Questie to detect quests without objectives as complete. As shown in this video, it completely fails to detect once you delete the sourceitemid.

**Comment by Cabro** [comment]
Fix confirmed

**Comment by Cabro** [comment]
Fix confirmed
