### ISSUE TITLE
Quests are not re-maximized after toggle of "Hide Blizzard Completion Text" when "Auto Minimize Completed Quests" is active.

### ISSUE THREAD

**Issue by Cabro** [Questie/Questie#5030]
Small case. When you have "Auto Minimize Completed Quests" checked, and you toggle on/off "Hide Blizzard Completion Text", the quests remain minimized in tracker instead of being maximized to show back the Blizzard completion text.

8.8.1 wotlk

**Comment by Dyaxler** [comment]
I was not able to repro this... in Classic Era or Wrath.

**Comment by BreakBB** [comment]
Is this still an issue @Cabro ?

**Comment by Cabro** [comment]
Not an issue anymore
