### ISSUE TITLE
LUA error upon opening of minimap

### ISSUE THREAD

**Issue by wowplayer420** [Questie/Questie#5036]
## Bug description

get an lua error when opening minimap

## Screenshots

Date: 2023-07-16 09:40:41
ID: 1
Error occured in: Global
Count: 1
Message: ...erface/AddOns/Questie/Modules/QuestieCoordinates.lua line 86:
   attempt to index a nil value
Debug:
   [string "=[C]"]: ?
   [string "@Interface/AddOns/Questie/Modules/QuestieCoordinates.lua"]:86: WriteCoords()
   [string "@Interface/AddOns/Questie/Modules/QuestieCoordinates.lua"]:113:
      ...erface/AddOns/Questie/Modules/QuestieCoordinates.lua:106
Locals:
(*temporary) = <function> defined =[C]:-1

AddOns:
  Swatter, v3.4.6921 (SwimmingSeadragon)
  AtlasLootClassic, vv3.1.3
  AtlasLootClassicData, vv3.1.3
  AtlasLootClassicDungeonsAndRaids, vv3.1.3
  Attune, v312
  AucAdvanced, v3.4.6931 (SwimmingSeadragon)
  AucFilterBasic, v3.4.6941 (SwimmingSeadragon)
  AucStatHistogram, v3.4.6928 (SwimmingSeadragon)
  AucStatiLevel, v3.4.6913 (SwimmingSeadragon)
  AucStatPurchased, v3.4.6910 (SwimmingSeadragon)
  AucStatSimple, v3.4.6911 (SwimmingSeadragon)
  AucStatStdDev, v3.4.6912 (SwimmingSeadragon)
  AucUtilFixAH, v3.4.6914 (SwimmingSeadragon)
  BeanCounter, v3.4.6933 (SwimmingSeadragon)
  DBMCore, ve923f8a
  DBMStatusBarTimers, ve923f8a
  DBMVPVEM, vb201a88
  Details, v#Details.20230713.11701.154
  DetailsCompare2, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  Enchantrix, v3.4.6942 (SwimmingSeadragon)
  EnchantrixBarker, v3.4.6917 (SwimmingSeadragon)
  GW2UI, v2.2.1-Wrath
  Informant, v3.4.6934 (SwimmingSeadragon)
  LoonBestInSlot, v4.8.0
  ProfessionMaster, v1.6.4
  Questie, v8.8.2
  Scrap, v10.1
  SilverDragon, vv2023.6.1
  SilverDragonOverlay, vv2023.6.1
  SilverDragonRangeExtender, vv2023.6.1
  SimpleItemLevel, vv30
  SlideBar, v3.4.6919 (SwimmingSeadragon)
  SpellActivationOverlay, v0.9.2
  Stubby, v3.4.6920 (SwimmingSeadragon)
  TacoTip, v0.4.2
  ThreatClassic2, v2.48
  VendorPrice, v1.6.5
  BlizRuntimeLib_enUS v3.4.2.30402 <none>
  (ck=590)

## Questie & WoW version

WotLK Classic

**Comment by MyTechnoHunter** [comment]
Opening minimap? That should be always visible.. do you perchance mean Opening world map?

Can you screenshot and upload?

**Comment by BreakBB** [comment]
Also try to verify this also happens with just Questie active @wowplayer420 

Also what zone were you in when this happened?

**Comment by BreakBB** [comment]
Closing this issue, due to lack of information.
