### ISSUE TITLE
The color for available quests on map is slightly skewed to green when mouseovering.

### ISSUE THREAD

**Issue by Cabro** [Questie/Questie#5040]
![image](https://github.com/Questie/Questie/assets/1155017/9384a2e4-1c8e-40f4-b99e-93c19cb4ab42)

This seems very unnecessary, if intended.
If not intended, obviously a bug.

8.8.2

**Comment by Dyaxler** [comment]
Bug confirmed

**Comment by Cabro** [comment]
Fix confirmed.
