### ISSUE TITLE
Recent changes affect how icons are displayed for Hide unexplored area Icons and Hide icons of untracked quests.

### ISSUE THREAD

**Issue by Cabro** [Questie/Questie#5042]
https://github.com/Questie/Questie/assets/1155017/32d5d976-8055-4d2c-bd31-eda7b0522a86

8.8.2 wotlk

**Comment by Cabro** [comment]
Nothing seems to be changed after the fix.

**Comment by Dyaxler** [comment]
@Cabro You're flipping through the toggle's way too fast. When you toggle and untoggle the pfquest icons you have to wait for the draw queue to finish. Takes about 20-30 seconds to fully redraw all the icons. Don't shoot me... I didn't write SmoothReset() and there is nothing I can do about it unfortunately. 

All works just fine in my client.

**Comment by MyTechnoHunter** [comment]
@Dyaxler that makes the kind of sense that doesnt.. if the first click (toggle pfIcons on) is instant.. stands to reason the un toggle should be too..

**Comment by Cabro** [comment]
They are highlighted after i unchecked pfquest, so theoretically it should run normal questie icons + force defaults. But since you can't see questie icons, you see the pfquest icons instead. With glow. Without random colors. With clutter 50. Hate pfquest, i won't test that anymore.

**Comment by Dyaxler** [comment]
Copying testing results from Discord to here. In summary, it takes 20-30 seconds for the redraw queue to complete when you flip on the option (Part 1 and Part 2 below). 

However, if you start flipping on/off other options before the process completes then it resets and takes longer for things to show up properly (Part 3 & Part 4 below).

Forgive the slightly degraded resolution... it only allows videos under 10mb per file.

Part 1 - Enable pfIcons
https://github.com/Questie/Questie/assets/17400948/e0950119-e007-467e-b015-49f424d2afcb

Part 2 - disable pfIcons
https://github.com/Questie/Questie/assets/17400948/f8e43593-cff4-4870-b547-7471e5ec3460

Part 3 - Weird highlighting
https://github.com/Questie/Questie/assets/17400948/e791f648-6e04-4dec-92b3-7bea2957045e

Part 4 - Self-correcting.
https://github.com/Questie/Questie/assets/17400948/c23438a5-3bbc-4ed7-83d2-9834d98e3e67
