### ISSUE TITLE
Lua Error while initialising 

### ISSUE THREAD

**Issue by Xrasnolud** [Questie/Questie#5049]
## Bug description

Every time I open wow client i get a lua error: Addons/Questie/Modules/Opitions/QuestieOptions.lua:33: attempt to call method 'SetMinResize' (a nil value)
It's been happening for months now, I wasn't bothered as I didn't play classic and hoped it would be fixed. I have reinstalled Questie using Curseforge client multiple times during those months

## Questie & WoW version

v7.3.2 Wotlk

**Comment by MyTechnoHunter** [comment]
> v7.3.2 Wotlk

that there is your problem.. flat out..

not sure how you are trying to install with curseforge client and getting _that_ but the latest is 8.8.2

please attempt to get _that_ version

**Comment by Xrasnolud** [comment]
I have no idea how curse client kept downloading the outdated version. Got it from curse website. Thanks for info it works now.
