### ISSUE TITLE
Item objective tooltips are not re-created after tracking an untracked quest.

### ISSUE THREAD

**Issue by Cabro** [Questie/Questie#5050]
I'll post the video to see the bug in action:

https://github.com/Questie/Questie/assets/1155017/b7327677-91f1-4b71-a892-3cd47350f301

In the case where you're in a group with more players on the same quest, the item is again missing your character in the tooltips, and what's what made me notice this bug. Notice it's missing the tooltip for the priest in the video above:

![image](https://github.com/Questie/Questie/assets/1155017/ef11352d-0659-44da-865d-6b7ab8eb1bd3)

8.8.2 wotlk

**Comment by stako** [comment]
I've noticed that in some cases, the tooltip only updates after a quest objective has been progressed (e.g. killed an enemy or collected an item). I've also noticed that the tooltips do not display at all for untracked quests since 8.8.2 and can't find a way to revert that behavior.

**Comment by Dyaxler** [comment]
> I've also noticed that the tooltips do not display at all for untracked quests since 8.8.2 and can't find a way to revert that behavior.

If the option "Hide icons of untracked quests" is enabled, then all icons and their corresponding tooltips are also hidden. This has always been the intended behavior in Questies spec and has been broken quite a few times over the years.

If you're not using this option and it's currently not checked then that is a bug.

@Cabro Is this bug on Master or in my PR?

**Comment by Cabro** [comment]
To answer to your question, i had the option enabled.
![image](https://github.com/Questie/Questie/assets/1155017/3b4c004f-5dcf-475c-b8d7-e26e0ada826f)
What the bug is, that it is not re-created once you retrack the quest.
