### ISSUE TITLE
Lua error when highlighting quest reward in quest log

### ISSUE THREAD

**Issue by remathes** [Questie/Questie#5052]
It takes a second for the error to show, so it will show the tooltip for your reward but once you close the log and open again it will show this error.  You might have to close the log open it a few times before it shows

Message: Interface_Wrath/FrameXML/QuestInfo.lua:1013: Invalid quest item in SetQuestLogItem("type", index [, questID])
Time: Tue Jul 25 02:10:06 2023
Count: 1
Stack: Interface_Wrath/FrameXML/QuestInfo.lua:1013: Invalid quest item in SetQuestLogItem("type", index [, questID])
[string "=[C]"]: ?
[string "=[C]"]: in function `SetQuestLogItem'
[string "@Interface_Wrath/FrameXML/QuestInfo.lua"]:1013: in function <Interface_Wrath/FrameXML/QuestInfo.lua:1009>

Locals: (*temporary) = <function> defined =[C]:-1

**Comment by remathes** [comment]
![luaerror](https://github.com/Questie/Questie/assets/1413409/d15095bc-f663-4cca-91e8-1a4c1801d418)

**Comment by remathes** [comment]
![version](https://github.com/Questie/Questie/assets/1413409/7e601fb7-68cd-462f-a6c4-4f95f64cf3fe)

**Comment by MyTechnoHunter** [comment]
whats the other error? does the error happen if you disable questie and test? i ask since the eror (1 of 2) you posted in the pic contains nothing of questie.. the stack is all blizzard functions

**Comment by remathes** [comment]
It only happens on some quest rewards like it can't show the details of the reward.  So I guess the hover details? Not all quests have this problem.  I guess if I can find the ones that do I can post them
