### ISSUE TITLE
Removed quests shown as available

### ISSUE THREAD

**Issue by Davyd2400** [Questie/Questie#5054]
The quest "The Mark of Vashj" which is unavailable to characters over lvl 70 is shown as available to pick up, and the quest "Imprisoned in the Citadel" which has been removed from the game is shown as available as well.

**Comment by BreakBB** [comment]
Questie currently has no way to hide a quest because of a „max level“.

The other quest will be easy to hide for us.

**Comment by Dyaxler** [comment]
@BreakBB can't we add a player level check and then blacklist the Mark of Vashj quest? If player level > 70 then blacklist quest. Or is the blacklist only for Questie Auto? I don't remember.

**Comment by BreakBB** [comment]
The entire logic lives inside `QuestieQuest.IsDoable` which is simply called for every quest in our database. Blacklisting is setup before that, which currently is really static.

The problem with blacklisting is, that the quest will be fully removed from the database, so you can't even search for it. 
But it would be possible to add such a level check to QuestieQuestBlacklist for the few quests which have a max level. 

The only quests in my mind are the PvP-quests which are available in different level brackets and "The Mark of Vashj" 🤔 

@Yttrium-tYcLief any thoughts on this idea?

**Comment by BreakBB** [comment]
Closing this in favor of #4979
