### ISSUE TITLE
LUA issue causing questie not to work

### ISSUE THREAD

**Issue by swat-ownage** [Questie/Questie#5057]
## Bug description

 Questie: [ERROR] Error during initialization! Interface\AddOns\Questie\Modules\QuestieCompat.lua:153: attempt to index local 'containerInfo' (a number value)
This is the error message I get when I load the game. Questie is no longer visible on my map or in general other than the questie icon on the mini map. I just got a new computer which is when it stopped working (1st time playing on this computer), but I tried removing the old files and downloading the newest version with no fix. 

## Questie & WoW version

Classic Era

**Comment by swat-ownage** [comment]
<img width="876" alt="image" src="https://github.com/Questie/Questie/assets/141082610/8e780187-d288-4342-ac10-a15d8bdbf076">

**Comment by MyTechnoHunter** [comment]
Questie version?

**Comment by swat-ownage** [comment]
v8.8.3

**Comment by BreakBB** [comment]
Hey @swat-ownage the latest Questie version is working just fine for me on Classic Era.

Can you do me a favor and disable all addons except Questie and see if that helps?

Also you are playing on Classic Era, not on one of the PTRs, right?

**Comment by swat-ownage** [comment]
My other computer it works just fine on, but this new one is having issues. Having just questie on makes it work just fine. I will figure out which addon is causing it issues from here thank you so much for the help. I am playing classic era not PTR

**Comment by BreakBB** [comment]
Thanks for the fast response and I am happy it seems working fine again (for now).

My guess is that any of the other addons you are using is globally creating the `C_Container.GetContainerItemInfo` function which normally does NOT exist on Classic Era. That is a potential problem for all addons.

Would be great if you can find out which addons is causing this problem.

**Comment by swat-ownage** [comment]
RC Loot Council

**Comment by BreakBB** [comment]
Interesting 🙈 

So with just Questie and RCLootCouncil active you get the error?

**Comment by BreakBB** [comment]
Oh it looks like this issue was fixed a while back in RCLootCouncil-Classic: [v0.18.4 Changelog](https://github.com/evil-morfar/RCLootCouncil_Classic/releases/tag/0.18.4). Make sure to use at least that version of RCLootCouncil-Classic

**Comment by BreakBB** [comment]
Looks like this is no longer an issue.
