### ISSUE TITLE
Crown of the Earth [ERROR]

### ISSUE THREAD

**Issue by majcarrero** [Questie/Questie#5059]
When collecting the quest "Crown of the Earth" (https://www.wowhead.com/wotlk/quest=921/crown-of-the-earth) the following error message appeared: "[ERROR] Missing objective data for quest 921 2." The same error message appeared upon completing the quest. The same error occurs throughout the sequence of this quest line.
![image](https://github.com/Questie/Questie/assets/141502466/8ee9c09e-55d6-4078-8fee-97fd092d5018)

**Comment by cbunting99** [comment]
I haven't played Wotlk much but I've noticed that quests like Crown of Earth, or any quest using a Phial, even once you fill the phial, the tracker doesn't update anymore. Still shows 0/1 yet the item in your bag shows completed.

**Comment by MyTechnoHunter** [comment]
> I haven't played Wotlk much but I've noticed that quests like Crown of Earth, or any quest using a Phial, even once you fill the phial, the tracker doesn't update anymore. Still shows 0/1 yet the item in your bag shows completed.

can you open an issue for this? and verify that you are fully updated in questie.. this issue (the original issue) dealt with quest objectives missing.. your issue is different

**Comment by cbunting99** [comment]
Sure.

**Comment by BreakBB** [comment]
This is no longer an issue, did this quest a few days ago.
