### ISSUE TITLE
Lua error

### ISSUE THREAD

**Issue by Druidimies** [Questie/Questie#5066]
Hello, 
got this lua error after latest update ( 8.8.4) wotlk. Doing JC daily quest named Shipment: Blood jade amulet.
![kuva](https://github.com/Questie/Questie/assets/133516389/94e70503-81a9-407d-9691-20ae0e224b01)

**Comment by Muehe** [comment]
Should be fully resolved with the latest release.

If you continue having problems please make sure that:

* You have Questie 8.8.6 or higher
* You have tried "Recompile Database" in Questie's advanced options tab

If that doesn't help please create a new issue or reopen this one.
