### ISSUE TITLE
erron on chat after loader screen

### ISSUE THREAD

**Issue by Typhosy** [Questie/Questie#5070]
## Bug description
[11:04:51] Interface/AddOns/Questie/Modules/Map/QuestieMap.lua:574: No UiMapID or fitting parentAreaId for areaId : 4277 - Forgotten Footman 
[11:04:51] [string "@Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua"]:70: in function <...erface/AddOns/Questie/Modules/Quest/QuestieQuest.lua:68>
[string "=[C]"]: in function `error'
[string "@Interface/AddOns/Questie/Modules/Map/QuestieMap.lua"]:574: in function `DrawWorldIcon'
[string "@Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua"]:1381: in function <...erface/AddOns/Questie/Modules/Quest/QuestieQuest.lua:1374>
[string "@Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua"]:1131: in function <...erface/AddOns/Questie/Modules/Quest/QuestieQuest.lua:1070>
[string "=[C]"]: in function `xpcall'
[string "@Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua"]:838: in function `UpdateObjectiveNotes'
[string "@Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua"]:554: in function `UpdateQuest'
[string "@Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua"]:1411: in function `PopulateObjectiveNotes'
[string "@Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua"]:680: in function `GetAllQuestIds'
[string "@Interface/AddOns/Questie/Modules/QuestieInit.lua"]:277: in function `?'
[string "@Interface/AddOns/Questie/Modules/QuestieInit.lua"]:354: in function <Interface/AddOns/Questie/Modules/QuestieInit.lua:352>
 
[11:04:51] Questie: [ERROR] [QuestieQuest]: [SpecialObjectives] There was an error populating objectives for Shipment: Shifting Sun Curio 12963 0 No error 

## Screenshots
![image](https://github.com/Questie/Questie/assets/114114582/c2a93b1b-1dfb-4ab5-8c1c-cece071b09eb)
![image](https://github.com/Questie/Questie/assets/114114582/b5d2d3fb-cec8-4138-99a1-bb7011cea9dc)

## Questie & WoW version
Version 8.8.4

Please also state if your quest issue is about Classic Era/SoM or Wotlk.
--> WOTLK

**Comment by Muehe** [comment]
Should be fully resolved with the latest release.

If you continue having problems please make sure that:

* You have Questie 8.8.6 or higher
* You have tried "Recompile Database" in Questie's advanced options tab

If that doesn't help please create a new issue or reopen this one.
