### ISSUE TITLE
Gear Quest Icons missing in V.8.8.4

### ISSUE THREAD

**Issue by Shadowdragon86** [Questie/Questie#5071]
## Bug description
Quest Icons for Items to collect are missing in v8.8.4 but the Glow on Map/Minimap is showing
I think its always quests that would show the Gear Icon.
Installing the older version 8.8.3 fixed it
For Example Quest in Terokkar Forest "The Shadow Tomb" "https://wowhead.com/wotlk/quest=10881"

## Screenshots
v.8.8.4
<img width="136" alt="image" src="https://github.com/Questie/Questie/assets/56504685/e293f06d-f79c-4091-b219-7402fd405966">

v.8.8.3
<img width="136" alt="image" src="https://github.com/Questie/Questie/assets/56504685/b4a518c4-2726-4141-a1bc-6bbee4cec85b">

## Questie & WoW version
Questie v8.8.4 Classic WOTLK

**Comment by Muehe** [comment]
This bug is fixed in v8.8.5 which has just been released. Should appear on Curseforge in a bit.

Thanks for reporting. :+1:
