### ISSUE TITLE
Of Traitors and Treason quest showing on map still.

### ISSUE THREAD

**Issue by tylerbrown47** [Questie/Questie#5072]
## Description

Quest marker for quest 12171 is showing on map even though it is not available.
Looking at old posts it seems this was an issue and the past but marked as fixed, and it is not fixed for me.  It has been bugged for a while and it just sort of annoyed me enough for me to do some reading on this and make this post.  It seems like this is a breadcrumb for a quest chain in Dragonblight that you can skip and grab a later part of that disables this quest.

## Wowhead link

https://www.wowhead.com/wotlk/quest=12171/of-traitors-and-treason

## Screenshots

![image](https://github.com/Questie/Questie/assets/8635256/f71d68b0-a6bc-49b3-a982-a7dc7f74ae5b)

## Questie & WoW version

Questie v8.8.5
Classic WotLK

**Comment by Cabro** [comment]
Should be fixed
