### ISSUE TITLE
[Classic Era] Stormwind City Map Coordinates

### ISSUE THREAD

**Issue by raethkcj** [Questie/Questie#5077]
## Bug description
For all map icons in Stormwind City, Questie appears to be using coordinates that would match the WOTLK map of Stormwind (which includes the Harbor) rather than the Vanilla version of the map.

## Screenshots
For these screenshots, my Player icon is at the location the relevant NPC is actually at, while my cursor is hovering over Questie's icon for the NPC. Note that the Mailbox icons are similarly offset.
![image](https://github.com/Questie/Questie/assets/7716908/58dcbb3a-01e2-4fa2-9585-e35825ca9fd1)
![image](https://github.com/Questie/Questie/assets/7716908/87717e23-37d0-41c4-9c24-07dcb88ecd72)

## Questie & WoW version
Questie v8.8.7
Classic Era v1.14.4.51056

**Comment by BreakBB** [comment]
Thanks for pointing this out @raethkcj 

For the team: I bet we need another HBD update, because the client version bump now makes HBD uses the wrong base coordinates.

**Comment by BreakBB** [comment]
Hey @raethkcj the map is looking fine for me 🤔 

Could you do me a favor and Recompile your database? `/questie` -> Advanced -> "Recompile Database" (it's a button)

![grafik](https://github.com/Questie/Questie/assets/33514570/c4eee071-04f0-47d3-839b-e3a8110dd52b)

**Comment by raethkcj** [comment]
Thanks, that did fix it. Unsure what happened but I guess it was just something on my end, thanks for looking into it!
