### ISSUE TITLE
Classic Era - Quest complete sound firing on teleporting

### ISSUE THREAD

**Issue by Painstormx** [Questie/Questie#5078]
Questie is a little bit broken after the big update to Classic Era.
When you use hearthstone or zone into a dungeon, the quest complete sound is played when screen loads.

**Comment by BreakBB** [comment]
Looks like every teleport also fires a `QUEST_LOG_UPDATE` event which results in Questie playing the "quest complete sound".

@Dyaxler @Muehe anyone of you have an idea what's going on here or if this is a bug on Blizzards side? No clue yet, if we can work around it.

**Comment by BreakBB** [comment]
I didn't test this for a while, but I think it was a hick up on Blizzards side and no longer happens. Can someone prove this?

**Comment by BreakBB** [comment]
This is still an issue. We need to detect this invalid `QUEST_LOG_UPDATE` in some way.
