### ISSUE TITLE
World map icons for dungeon objectives only show 1 objective for 1 quest, instead of showing all of the objectives.

### ISSUE THREAD

**Issue by Cabro** [Questie/Questie#5084]
I will show the bug, as it is easier to notice it than to explain it:
![image](https://github.com/Questie/Questie/assets/1155017/e5c06d61-d969-4cb8-99ef-5c0e07212363)
It only shows the Deed to Tarren Mill as being objective, but there are 4. The other 3 are not shown. This is a general bug and it affects all quests.

8.8.7

**Comment by BreakBB** [comment]
Is this fixed with #5096?

**Comment by Cabro** [comment]
![image](https://github.com/Questie/Questie/assets/1155017/c6f1032a-aa78-4c35-adc7-c4132bac30d7)
👍
