### ISSUE TITLE
Lua error when opening Mini map and zooming out. 

### ISSUE THREAD

**Issue by Thirdeyesharp07** [Questie/Questie#5088]
## Bug description

Lua Error pops up after zooming out on the map. Does not do anything initially but as soon as you zoom out it just pops up lua error

Message: ...erface/AddOns/Questie/Modules/QuestieCoordinates.lua:86: attempt to index a nil value
Time: Tue Sep  5 21:33:02 2023
Count: 1799
Stack: ...erface/AddOns/Questie/Modules/QuestieCoordinates.lua:86: attempt to index a nil value
[string "=[tsm error check]"]:1: in main chunk
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "@Interface/AddOns/Questie/Modules/QuestieCoordinates.lua"]:86: in function `WriteCoords'
[string "@Interface/AddOns/Questie/Modules/QuestieCoordinates.lua"]:113: in function <...erface/AddOns/Questie/Modules/QuestieCoordinates.lua:106>

Locals:  

## Screenshots

![image](https://github.com/Questie/Questie/assets/144189785/3d60bf2a-737a-41fe-89f6-dc0dcc7a3cbc)

## Questie & WoW version

A) Wotlk

**Comment by MyTechnoHunter** [comment]
questie version is? what other addons are you using?
please try disabling ALL other addons except for Questie and perform your test again

**Comment by Thirdeyesharp07** [comment]
> questie version is? what other addons are you using? please try disabling ALL other addons except for Questie and perform your test again

My apologies, 

I had it all typed in the post. Not sure where it went. 

V8.8.7

I think an old addon "Attune" May have been the issue.
