### ISSUE TITLE
Deeprun Rat Roundup (6661) not showing up

### ISSUE THREAD

**Issue by BreakBB** [Questie/Questie#5091]
## Description

The quest is not showing up on the map even though it should show up in SW and IF at the Deeprun Tram entry, just like with other dungeons.

## Wowhead link

https://www.wowhead.com/classic/quest=6661/deeprun-rat-roundup

## Questie & WoW version

v8.9.0

**Comment by Cabro** [comment]
This is my change, i made them not show up in SW/IF anymore, as deeprun tram is not a dungeon from a player point of view (not listed in LFG tool).

**Comment by MyTechnoHunter** [comment]
it may not be a dungeon but it _is_ an instance.. 
maybe make it show in the instance?never did make sense to show it in the city to me..

**Comment by Cabro** [comment]
And it would show if it had an actual map :D

**Comment by MyTechnoHunter** [comment]
wut? if it doesnt have a map.. how does it load?

**Comment by Cabro** [comment]
only wotlk dungeons/raids have maps. era + tbc don't

**Comment by MyTechnoHunter** [comment]
hrm.. nothing for tram in herebedragons?

**Comment by BreakBB** [comment]
> This is my change, i made them not show up in SW/IF anymore, as deeprun tram is not a dungeon from a player point of view (not listed in LFG tool).

Why would we hide the quest though? 🤔 As you already said: The Deeprun Tram has no map and is an instanciated area, so we have no other way then showing the quest on the entries to it.

**Comment by Cabro** [comment]
It just looks out of place and is misleading tbh

**Comment by BreakBB** [comment]
> At least it will show the quest tooltip on the NPC when you mouseover it?

Yes, that's correct.

**Comment by BreakBB** [comment]
@Cabro let's show these quest again.

**Comment by MyTechnoHunter** [comment]
seconded, even if its not a dungeon its the only way to show em.. stupid blizz..

**Comment by BreakBB** [comment]
Fixed in 7a131a5df43be00d1a822a66c968c4be3ab879ae
