### ISSUE TITLE
Quest 6131 is missing from database

### ISSUE THREAD

**Issue by fffrtzhr** [Questie/Questie#5093]
I get a message in WOW Classic, that the quest 6131 is missing.

**Comment by BreakBB** [comment]
Hey @fffrtzhr do you have the actual error message?

**Comment by fffrtzhr** [comment]
Hey @BreakBB, i updated Questie to the latest version yesterday using CurseForge and still get the Message:
Questie: [ERROR] The quest 6131 is missing from Questie's database. Please report this on GitHub or Discord!

**Comment by MyTechnoHunter** [comment]
when you say wow classic, do you mean Era or wrath?

i ask because the quest 6131 is in the blacklisted quests for era..

![image](https://github.com/Questie/Questie/assets/55214545/74218c7f-f3c9-4264-94ea-3d6165152088)

**Comment by BreakBB** [comment]
@MyTechnoHunter hidden quests should still be considered as "in the database" as you can also still search for them in Advanced Search 🤔 

It is really strange though, as that used to be a regular quest and we hid it on purpose.

@fffrtzhr are you playing Classic Era or Wotlk?

**Comment by BreakBB** [comment]
Hey @fffrtzhr would be great to know if you are playing Classic Era, Hardcore or Wotlk!

**Comment by BreakBB** [comment]
Can't reproduce and also are missing information.
