### ISSUE TITLE
[Wotlk] Storm Peaks breadcrumb quest 'The Earthen of Ulduar' stuck as 'available'

### ISSUE THREAD

**Issue by Fishdumpster** [Questie/Questie#5095]
I've completely cleared Storm Peaks of quests and this breadcrumb 'The Earthen of Ulduar' (ID: 12929) slipped through the cracks and is no longer available to accept and complete. It doesn't appear on my map but doesn't seem to get correctly shuffled into the 'completed' or 'unobtainable' categories for the Storm Peaks zone.

## Wowhead link
https://www.wowhead.com/wotlk/quest=12929/the-earthen-of-ulduar

## Questie & WoW version
Questie v8.9.0
Wotlk Classic

**Comment by Cabro** [comment]
Fixed in https://github.com/Questie/Questie/pull/5094/commits/bdf044134acae11ebe35c12f3a39e74e268c7997
