### ISSUE TITLE
Questie thinks I'm on the big map.

### ISSUE THREAD

**Issue by John3061** [Questie/Questie#5097]

**Comment by John3061** [comment]
This is my first post and I'm not sure how this works. I have the latest version of questie and I'm using windows 11. The problem is questie thinks I'm on the bigger map when I go into zones on the map. This forces me to use questie in the big map and not in the zone map. I don't know how to take a screen shot. I tried to google it and I don't have a command key or a F13 key. But when in a zone map like the map in a zone it thinks I am on the continent map and shows the quests on the continent map in stormwind  as an example. This forces me to use questie in the continent map only. I don't know if I will ever be able to get back to this web sight because it was so hard to get here. But I just thought you should know.

**Comment by John3061** [comment]
![WoWScrnShot_090923_223230](https://github.com/Questie/Questie/assets/144577635/36b8ad86-bf01-4516-a57f-745754e3bb26)
![WoWScrnShot_090923_223112](https://github.com/Questie/Questie/assets/144577635/25b90ee1-eb1f-4213-8a3a-450d88aeb3ad)
![WoWScrnShot_090923_223120](https://github.com/Questie/Questie/assets/144577635/d6ccde48-122f-46f6-b8da-e6873726394c)
![WoWScrnShot_090923_223139](https://github.com/Questie/Questie/assets/144577635/4f4f47f8-5ffa-4cde-8b7f-9cb43cea919f)
![WoWScrnShot_090923_223204](https://github.com/Questie/Questie/assets/144577635/03b768e6-d477-4ae9-b9cb-a44c916c2455)
![WoWScrnShot_090923_223221](https://github.com/Questie/Questie/assets/144577635/c999d076-8240-481e-9699-7b699d14c226)

**Comment by Cabro** [comment]
You map doesnt look like your usual map. Disable that map addon and see if it still interferes with Questie

**Comment by John3061** [comment]
> You map doesnt look like your usual map. Disable that map addon and see if it still interferes with Questie

I didn't know what to delete so I just deleted everything and started over. It worked. Thank you very much.
