### ISSUE TITLE
QuestieTracker.lua:1817: attempt to perform arithmetic on a nil value

### ISSUE THREAD

**Issue by CMDWarlord** [Questie/Questie#5099]
## Bug description

I was out of date in questie went to update then did the update and it broken the addon. After disabling all my other addons to make sure they were interfering with Questie I still get the error. 

"Message: ...ce/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:1817: attempt to perform arithmetic on a nil value
Time: Sun Sep 10 14:51:36 2023
Count: 1
Stack: ...ce/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:1817: attempt to perform arithmetic on a nil value
[string "@Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua"]:1817: in function `UpdateHeight'
[string "@Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua"]:1742: in function `UpdateFormatting'
[string "@Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua"]:1651: in function `Update'
[string "@Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua"]:1692: in function `func'
[string "@Interface/AddOns/Questie/Modules/Libs/QuestieCombatQueue.lua"]:25: in function <...e/AddOns/Questie/Modules/Libs/QuestieCombatQueue.lua:17>

Locals: self = <table> {
 UpdateAchieveTrackerCache = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:2162
 Enable = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:502
 Expand = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:553
 IsTrackedAchievement = <function> defined =[C]:-1
 UpdateWidth = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:1758
 UpdateDurabilityFrame = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:318
 RemoveQuestWatch = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:2026
 started = true
 alreadyHooked = true
 AQW_Insert = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:2071
 UntrackAchieveId = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:2196
 Initialize = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:75
 GetNumTrackedAchievements = <function> defined =[C]:-1
 Disable = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:514
 HasQuest = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:463
 RemoveTrackedAchievement = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:2147
 Unhook = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:1860
 RemoveQuest = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:2004
 UntrackQuestId = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:2050
 QuestItemLooted = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:438
 UpdateFormatting = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:1698
 ResetVoiceOverFrame = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:364
 HookBaseTracker = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:1888
 GetNumQuestWatches = <function> defined =[C]:-1
 UpdateVoiceOverFrame = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:386
 IsQuestWatched = <function> defined =[C]:-1
 Update = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:561
 UpdateHeight = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:1801
 alreadyHookedSecure = true
 Collapse = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:544
 TrackAchieve = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:2203
 private = <table> {
 }
 Toggle = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:532
 ResetDurabilityFrame = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:288
 ResetLocation = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:271
}
trackerHeaderFrameHeight = 51.999990
trackerHeightByRatio = 451.764709
trackerHeightByManual = 0
trackerHeight"

## Questie & WoW version
WOTLK

[Questie.zip](https://github.com/Questie/Questie/files/12570856/Questie.zip)

**Comment by MyTechnoHunter** [comment]
juuuust to satisfy my sense of the absurd.. use curseforge to re-install questie (right click questie in your addon list and re-install)

inquiring minds want to know.. 

so this while out of the game please..

**Comment by CMDWarlord** [comment]
I don't use curseforge for my addons.

**Comment by MyTechnoHunter** [comment]
same principle.. re-install manually if needed then..

**Comment by BreakBB** [comment]
Did you try to reset the Trackers location? You can do so in the Questie settings for "Tracker"

**Comment by CMDWarlord** [comment]
I did that and it seemed to fix my issue so far no error codes.

**Comment by BreakBB** [comment]
@mooonstone does that help you as well?

> Did you try to reset the Trackers location? You can do so in the Questie settings for "Tracker"

**Comment by CMDWarlord** [comment]
> Did you try to reset the Trackers location? You can do so in the Questie settings for "Tracker"

The same error popped up tried the fix and still don't work.
