### ISSUE TITLE
The "Complete" tag is not removed from repeatable quests after turning them in.

### ISSUE THREAD

**Issue by Cabro** [Questie/Questie#5101]
https://github.com/Questie/Questie/assets/1155017/b089b528-7b2d-4094-82ce-fa0d19d22ef2

8.9.0

**Comment by BreakBB** [comment]
What does `/dump QuestieDB.IsComplete(questId)` return after turn in?

**Comment by Cabro** [comment]
```[12:24:58] Dump: value=QuestieDB.IsComplete(8507)
[12:24:58] [1]=0```

**Comment by BreakBB** [comment]
Then this is a bug in the `QuestLogCache` not recognizing the quest was removed from the quest log.

**Comment by Cabro** [comment]
QuestLogCache seems to cause quite a few problems lately :(

**Comment by BreakBB** [comment]
If you didn't do a `/reload` yet, can you do:

`/dump QuestLogCache.questLog_DO_NOT_MODIFY[8507]`

**Comment by Cabro** [comment]
```
[13:14:01] Dump: value=QuestLogCache.questLog_DO_NOT_MODIFY[8507]
[13:14:01] empty result
```

**Comment by BreakBB** [comment]
Oh wait, isComplete = 0 means incomplete, so the `QuestLogCache` is correct.

**Comment by BreakBB** [comment]
What does `/dump QuestieDB:GetQuest(8507).isComplete` return?

**Comment by Cabro** [comment]
```
[13:21:25] Dump: value=QuestieDB:GetQuest(8507).isComplete
[13:21:25] [1]=true
```
Which is curious, since i don't have that quest in log anymore. 

I also ran additionally the `/run print(C_QuestLog.IsQuestFlaggedCompleted(8507))` and it returned `false`, so this is a Questie issue.

**Comment by BreakBB** [comment]
Can you also report the output of: `/dump QuestieDB:GetQuest(questId):IsComplete()`?

**Comment by Cabro** [comment]
```
[16:16:46] Dump: value=QuestieDB:GetQuest(8507):IsComplete()
[16:16:46] [1]=0
```

**Comment by BreakBB** [comment]
Alright. Looks like `quest.isComplete` flag is not reset correctly and/or we get a cached value.

Can you add the following lines to the following place and try again?

https://github.com/Questie/Questie/blob/b83f73bb89517a1bb5cb93fe969fdd223cb9ad04/Modules/Quest/QuestieQuest.lua#L486

```diff
function QuestieQuest:CompleteQuest(questId)
+   QuestiePlayer.currentQuestlog[questId].WasComplete = nil
+   QuestiePlayer.currentQuestlog[questId].isComplete = nil
    QuestiePlayer.currentQuestlog[questId] = nil;

    -- Only quests that are daily quests or aren't repeatable should be marked complete,
    -- otherwise objectives for repeatable quests won't track correctly - #1433
    Questie.db.char.complete[questId] = QuestieDB.IsDailyQuest(questId) or (not QuestieDB.IsRepeatable(questId));
    QuestieMap:UnloadQuestFrames(questId)

    if (QuestieMap.questIdFrames[questId]) then
        Questie:Error("Just removed all frames but the framelist seems to still be there!", questId)
    end

    QuestieTooltips:RemoveQuest(questId)
    QuestieTracker:RemoveQuest(questId)
    QuestieCombatQueue:Queue(function()
        QuestieTracker:Update()
    end)

    --This should probably be done first, because DrawAllAvailableQuests looks at QuestieMap.questIdFrames[QuestId] to add available
    QuestieQuest.CalculateAndDrawAvailableQuestsIterative()

    Questie:Debug(Questie.DEBUG_INFO, "[QuestieQuest] Completed Quest:", questId)
end
```

**Comment by Cabro** [comment]
It works!

**Comment by BreakBB** [comment]
Perfect, will push the change soon.
