### ISSUE TITLE
LUA error when turning in feathers for Timbermaw Hold on client 1.14.4 hardcore server using Questie 8.9.1

### ISSUE THREAD

**Issue by Theguyxd** [Questie/Questie#5106]
## Bug description
LUA error when turning in the repeatable quests for Timbermaw Hold rep in Felwood. The quest that is next to the tunnel to Moonglade and Winterspring.

## Questie & WoW version
Classic Era 1.14.4 on hardcore server. Using Questie version 8.9.1

## LUA error:

Message: ...erface/AddOns/Questie/Modules/Quest/QuestieQuest.lua:488: attempt to index field '?' (a nil value)
Time: Wed Sep 13 09:16:02 2023
Count: 1
Stack: ...erface/AddOns/Questie/Modules/Quest/QuestieQuest.lua:488: attempt to index field '?' (a nil value)
[string "@Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua"]:488: in function `CompleteQuest'
[string "@Interface/AddOns/Questie/Modules/Quest/QuestEventHandler.lua"]:309: in function `QuestTurnedIn'
[string "@Interface/AddOns/Questie/Modules/Quest/QuestEventHandler.lua"]:543: in function <...e/AddOns/Questie/Modules/Quest/QuestEventHandler.lua:539>

Locals: self = <table> {
 autoBlacklist = <table> {
 }
 ShouldShowQuestNotes = <function> defined @Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua:401
 AcceptQuest = <function> defined @Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua:424
 HideQuest = <function> defined @Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua:412
 ToggleNotes = <function> defined @Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua:100
 PopulateQuestLogInfo = <function> defined @Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua:1435
 AbandonedQuest = <function> defined @Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua:514
 SmoothReset = <function> defined @Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua:295
 ClearAllToolTips = <function> defined @Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua:232
 availableQuests = <table> {
 }
 DrawDailyQuest = <function> defined @Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua:1843
 GetAllQuestIds = <function> defined @Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua:656
 UnhideQuest = <function> defined @Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua:418
 GetAllQuestIdsNoObjectives = <function> defined @Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua:802
 UpdateQuest = <function> defined @Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua:548
 PopulateObjectiveNotes = <function> defined @Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua:1407
 PopulateObjective = <function> defined @Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua:1074
 AddFinisher = <function> defined @Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua:901
 CheckQuestSourceItem = <function> defined @Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua:857
 ResetAutoblacklistCategory = <function> defined @Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua:91
 UpdateObjectiveNotes = <function> defined @Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua:831
 CalculateAndDrawAvailableQuestsIterative = <function> defined @Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua:1832
 CompleteQuest = <function> defined @Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua:486
 Initialize = <function> defined @Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua:82
 GetAllLeaderBoardDetails = <function> defined @Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua:1548
 SetObjectivesDirty = <function> defined @Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua:645
 ClearAllNotes = <function> defined @Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua:203
 private = <table> {
 }
}
questId = 8467
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field '?' (a nil value)"
QuestiePlayer = <table> {
 GetLocalizedClassName = <function> defined @Interface/AddOns/Questie/Modules/QuestiePlayer.lua:68
 SetPlayerLevel = <function> defined @Interface/AddOns/Questie/Modules/QuestiePlayer.lua:42
 GetPartyMemberByName = <function> defined @Interface/AddOns/Questie/Modules/QuestiePlayer.lua:134
 GetPartyMembers = <function> defined @Interface/AddOns/Questie/Modules/QuestiePlayer.lua:117
 private = <table> {
 }
 GetGroupType = <function> defined @Interface/AddOns/Questie/Modules/QuestiePlayer.lua:72
 currentQuestlog = <table> {
 }
 GetPlayerLevel =

**Comment by BreakBB** [comment]
Thanks for reporting this @Theguyxd - This was introduced with the latest release indeed, with a fix for turning in repeatable quests ( e13b6093111e9b5e17c6ad63da17259fdf352958 ).

I'll make sure to fix this very soon.
