### ISSUE TITLE
Quest 70411 is missing from database

### ISSUE THREAD

**Issue by SimonDlgs** [Questie/Questie#5108]
## Description
Quest 70411 is missing from database

## Wowhead link
Link : https://www.wowhead.com/wotlk/quest=70411/to-the-dockmaster

## Questie & WoW version
Questies v8.9.1
Wow Wotlk

![image](https://github.com/Questie/Questie/assets/57448240/83b41a4d-1ff8-4692-b9d3-f00e583830c1)

**Comment by BreakBB** [comment]
Thanks for your report @SimonDlgs 👍🏻 

We are aware the character boost quests for level 70 are missing in the Questie DB. This issue is tracked here: #4351

It is quite tedious to add these quests, but it is on our list 🙈
