### ISSUE TITLE
Lua Error  Quest: Gaining Accepptance

### ISSUE THREAD

**Issue by ferndaky** [Questie/Questie#5109]
## Bug description
Hi, 
I use Questie v8.9.1 in Classic Era Version: 1.14.4.51311.
Turned off all other Addons but still get this error when i turn in the repeatable Quest: Gaining Accepptance from Master Smith Burninate. (https://www.wowhead.com/classic/quest=7737/gaining-acceptance)
After I Complete the Quest i get everytime this Error:

Lua Error:

Message: ...erface/AddOns/Questie/Modules/Quest/QuestieQuest.lua:488: attempt to index field '?' (a nil value)
Time: Wed Sep 13 23:40:52 2023
Count: 1
Stack: ...erface/AddOns/Questie/Modules/Quest/QuestieQuest.lua:488: attempt to index field '?' (a nil value)
[string "@Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua"]:488: in function `CompleteQuest'
[string "@Interface/AddOns/Questie/Modules/Quest/QuestEventHandler.lua"]:309: in function `QuestTurnedIn'
[string "@Interface/AddOns/Questie/Modules/Quest/QuestEventHandler.lua"]:543: in function <...e/AddOns/Questie/Modules/Quest/QuestEventHandler.lua:539>

Locals: self = <table> {
 autoBlacklist = <table> {
 }
 ShouldShowQuestNotes = <function> defined @Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua:401
 AcceptQuest = <function> defined @Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua:424
 HideQuest = <function> defined @Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua:412
 ToggleNotes = <function> defined @Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua:100
 PopulateQuestLogInfo = <function> defined @Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua:1435
 AbandonedQuest = <function> defined @Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua:514
 SmoothReset = <function> defined @Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua:295
 ClearAllToolTips = <function> defined @Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua:232
 availableQuests = <table> {
 }
 DrawDailyQuest = <function> defined @Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua:1843
 GetAllQuestIds = <function> defined @Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua:656
 UnhideQuest = <function> defined @Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua:418
 GetAllQuestIdsNoObjectives = <function> defined @Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua:802
 UpdateQuest = <function> defined @Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua:548
 PopulateObjectiveNotes = <function> defined @Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua:1407
 PopulateObjective = <function> defined @Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua:1074
 AddFinisher = <function> defined @Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua:901
 CheckQuestSourceItem = <function> defined @Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua:857
 ResetAutoblacklistCategory = <function> defined @Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua:91
 UpdateObjectiveNotes = <function> defined @Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua:831
 CalculateAndDrawAvailableQuestsIterative = <function> defined @Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua:1832
 CompleteQuest = <function> defined @Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua:486
 Initialize = <function> defined @Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua:82
 GetAllLeaderBoardDetails = <function> defined @Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua:1548
 SetObjectivesDirty = <function> defined @Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua:645
 ClearAllNotes = <function> defined @Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua:203
 private = <table> {
 }
}
questId = 7737
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field '?' (a nil value)"
QuestiePlayer = <table> {
 GetLocalizedClassName = <function> defined @Interface/AddOns/Questie/Modules/QuestiePlayer.lua:68
 SetPlayerLevel = <function> defined @Interface/AddOns/Questie/Modules/QuestiePlayer.lua:42
 GetPartyMemberByName = <function> defined @Interface/AddOns/Questie/Modules/QuestiePlayer.lua:134
 GetPartyMembers = <function> defined @Interface/AddOns/Questie/Modules/QuestiePlayer.lua:117
 private = <table> {
 }
 GetGroupType = <function> defined @Interface/AddOns/Questie/Modules/QuestiePlayer.lua:72
 currentQuestlog = <table> {
 }
 GetPlayerLevel =

**Comment by Cabro** [comment]
Fixed with https://github.com/Questie/Questie/pull/5107/commits/4bc0e8aa1ede0167a761843e26b1ab7b5614c7eb
