### ISSUE TITLE
Classic Era 1.14.4 AV Turn In Quests Bug

### ISSUE THREAD

**Issue by maddhacker24** [Questie/Questie#5110]
Getting this error every time I turn in armor scraps, blood, etc... in Alterac Valley BG on the horde.

211x Questie/Modules/Quest/QuestieQuest.lua:488: attempt to index field '?' (a nil value)
[string "@Questie/Modules/Quest/QuestieQuest.lua"]:488: in function `CompleteQuest'
[string "@Questie/Modules/Quest/QuestEventHandler.lua"]:309: in function `QuestTurnedIn'
[string "@Questie/Modules/Quest/QuestEventHandler.lua"]:543: in function <...eQuestie/Modules/Quest/QuestEventHandler.lua:539>

Locals:
self = <table> {
 autoBlacklist = <table> {
 }
 ShouldShowQuestNotes = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:401
 AcceptQuest = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:424
 HideQuest = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:412
 ToggleNotes = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:100
 PopulateQuestLogInfo = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:1435
 AbandonedQuest = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:514
 SmoothReset = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:295
 ClearAllToolTips = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:232
 CheckQuestSourceItem = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:857
 CompleteQuest = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:486
 GetAllQuestIds = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:656
 _resetNeedsAvailables = false
 UnhideQuest = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:418
 GetAllQuestIdsNoObjectives = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:802
 PopulateObjectiveNotes = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:1407
 private = <table> {
 }
 PopulateObjective = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:1074
 availableQuests = <table> {
 }
 DrawDailyQuest = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:1843
 ResetAutoblacklistCategory = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:91
 UpdateQuest = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:548
 CalculateAndDrawAvailableQuestsIterative = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:1832
 UpdateObjectiveNotes = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:831
 Initialize = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:82
 GetAllLeaderBoardDetails = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:1548
 SetObjectivesDirty = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:645
 ClearAllNotes = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:203
 AddFinisher = <function> defined @Questie/Modules/Quest/QuestieQuest.lua:901
}
questId = 8387
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field '?' (a nil value)"
QuestiePlayer = <table> {
 GetLocalizedClassName = <function> defined @Questie/Modules/QuestiePlayer.lua:68
 SetPlayerLevel = <function> defined @Questie/Modules/QuestiePlayer.lua:42
 GetPartyMemberByName = <function> defined @Questie/Modules/QuestiePlayer.lua:134
 GetPartyMembers = <function> defined @Questie/Modules/QuestiePlayer.lua:117
 private = <table> {
 }
 GetGroupType = <function> defined @Questie/Modules/QuestiePlayer.lua:72
 currentQuestlog = <table> {
 }
 GetPlayerLevel = <function> defined @Questie/Modules/QuestiePlayer.lua:50
 numberOfGroupMembers = 0
 GetPartyMemberList = <function> defined @Questie/Modules/QuestiePlayer.lua:158
 IsMaxLevel = <function> defined @Questie/Modules/QuestiePlayer.lua:57
 GetCurrentContinentId = <function> defined @Questie/Modules/QuestiePlayer.lua:99
 Initialize = <function> defined @Questie/Modules/QuestiePlayer.lua:27
 HasRequiredRace = <function> defined @Questie/Modules/QuestiePlayer.lua:83
 GetCurrentZoneId = <function> defined @Questie/Modules/QuestiePlayer.lua:94
 HasRequiredClass = <function> d

**Comment by BreakBB** [comment]
Fixed with #5107 I'll push a release today. Thanks for reporting this @maddhacker24
