### ISSUE TITLE
14th update

### ISSUE THREAD

**Issue by mooonstone** [Questie/Questie#5114]

**Comment by mooonstone** [comment]
Message: ...ce/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:1817: attempt to perform arithmetic on a nil value
Time: Thu Sep 14 19:00:36 2023
Count: 1
Stack: ...ce/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:1817: attempt to perform arithmetic on a nil value
[string "@Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua"]:1692: in function `func'
[string "@Interface/AddOns/Questie/Modules/Libs/QuestieCombatQueue.lua"]:25: in function <...e/AddOns/Questie/Modules/Libs/QuestieCombatQueue.lua:17>

Locals: allowFormattingUpdate = true
QuestieTracker = <table> {
 UpdateAchieveTrackerCache = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:2162
 Enable = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:502
 Expand = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:553
 IsTrackedAchievement = <function> defined =[C]:-1
 UpdateWidth = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:1758
 UpdateDurabilityFrame = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:318
 RemoveQuestWatch = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:2026
 started = true
 alreadyHooked = true
 AQW_Insert = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:2071
 UntrackAchieveId = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:2196
 Initialize = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:75
 GetNumTrackedAchievements = <function> defined =[C]:-1
 Disable = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:514
 HasQuest = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:463
 RemoveTrackedAchievement = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:2147
 Unhook = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:1860
 RemoveQuest = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:2004
 UntrackQuestId = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:2050
 QuestItemLooted = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:438
 UpdateFormatting = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:1698
 ResetVoiceOverFrame = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:364
 HookBaseTracker = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:1888
 GetNumQuestWatches = <function> defined =[C]:-1
 UpdateVoiceOverFrame = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:386
 IsQuestWatched = <function> defined =[C]:-1
 Update = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:561
 UpdateHeight = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:1801
 alreadyHookedSecure = true
 Collapse = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:544
 TrackAchieve = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:2203
 private = <table> {
 }
 Toggle = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:532
 ResetDurabilityFrame = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:288
 ResetLocation = <function> defined @Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:271
}

**Comment by mooonstone** [comment]
Message: ...ce/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:1817: attempt to perform arithmetic on a nil value
Time: Thu Sep 14 19:02:41 2023
Count: 2
Stack: ...ce/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:1817: attempt to perform arithmetic on a nil value

Locals:

**Comment by BreakBB** [comment]
Hey @mooonstone I am merging this with #5099
