### ISSUE TITLE
Douple complete map icon tooltip

### ISSUE THREAD

**Issue by BreakBB** [Questie/Questie#5117]
## Bug description

This persists throughout `/reload`

## Screenshots

![grafik](https://github.com/Questie/Questie/assets/33514570/7ed0df8c-5cdd-482d-a9e3-e076152cb4e3)

## Questie & WoW version

v8.9.2

**Comment by MyTechnoHunter** [comment]
wth?  i dont recall that happening before.. and its not decorating the second entry (no icon) 
problem with linepool? if you roll back to 8.7 (pre 8.9.0) does it have that issue?

**Comment by Cabro** [comment]
FIrst time i see it also.

**Comment by BreakBB** [comment]
According to `git bisect` #5104 introduced this bug.
