### ISSUE TITLE
Error during initialazation after recent update on curseforge

### ISSUE THREAD

**Issue by Northernviking96** [Questie/Questie#5122]
Playing Classic Hc and addon stopped working after I updated on Curseforge
Error:  Interdface/AddOns/Questie/Modules/Migration.lua:321: attempt to index field 'townsfolk config' (a nil value)
![WoWScrnShot_091523_212818](https://github.com/Questie/Questie/assets/145164710/7f2b583e-7dea-457e-b21a-f12ca435ba48)

**Comment by BreakBB** [comment]
Hey @Northernviking96 thanks a lot for repoting it so fast. Our tests missed that, but the next release will be available in a few minutes and fixes this.
