### ISSUE TITLE
zhTW Translations

### ISSUE THREAD

**Issue by class2u** [Questie/Questie#5124]
Hi, Thank you for making this great addon. Here are the [zhTW Translations](https://drive.google.com/file/d/1dOorAZ39nZpCGgTBHdmkQxQg0lyhg9kr/view?usp=sharing) I made them complete and optimized. I do not know how to use pull request so I put it in google drive. Please feel free to use it. :)

**Comment by MyTechnoHunter** [comment]
thanks!

**Comment by BreakBB** [comment]
That is awesome, thank you very much @class2u

**Comment by BreakBB** [comment]
Hey @class2u thank you SO MUCH for adding all of these translations, that is a HUGE change for the Taiwan players using Questie ❤️ 💪🏻 

I fixed a few indents and left two-three questions, which would be good to get another bit of information from you 👍🏻

**Comment by class2u** [comment]
Thank you. I'm glad it helped!

**Comment by BreakBB** [comment]
Fixed with #5125
