### ISSUE TITLE
LUA error when clicking a quest link in chat

### ISSUE THREAD

**Issue by Theguyxd** [Questie/Questie#5126]
## Bug description

I was inside BRD on the 1.14.4 client and got a LUA error when clicking a quest link in chat. Does not seem to happen whilst outside in the open world.

## Questie & WoW version
Questie version 8.10.1
WoW classic 1.14.4 on a hardcore server.

## LUA error
Message: ...face/AddOns/Questie/Modules/Tracker/TrackerUtils.lua:339: attempt to index field '?' (a nil value)
Time: Sun Sep 17 21:08:13 2023
Count: 4
Stack: ...face/AddOns/Questie/Modules/Tracker/TrackerUtils.lua:339: attempt to index field '?' (a nil value)
[string "@Interface/AddOns/Questie/Modules/Tracker/TrackerUtils.lua"]:339: in function <...face/AddOns/Questie/Modules/Tracker/TrackerUtils.lua:333>
[string "@Interface/AddOns/Questie/Modules/Tracker/TrackerUtils.lua"]:358: in function `GetZoneNameByID'
[string "@Interface/AddOns/Questie/Modules/QuestLinks/Link.lua"]:271: in function <Interface/AddOns/Questie/Modules/QuestLinks/Link.lua:263>
[string "@Interface/AddOns/Questie/Modules/QuestLinks/Link.lua"]:101: in function `CreateQuestTooltip'
[string "@Interface/AddOns/Questie/Modules/QuestLinks/Link.lua"]:41: in function `SetHyperlink'
[string "@Interface/FrameXML/ItemRef.lua"]:421: in function <Interface/FrameXML/ItemRef.lua:1>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Interface/AddOns/Blizzard_CombatLog/Blizzard_CombatLog.lua"]:3535: in function `SetItemRef'
[string "@Interface/FrameXML/ChatFrame.lua"]:3795: in function <Interface/FrameXML/ChatFrame.lua:3794>
[string "=[C]"]: in function `ChatFrame_OnHyperlinkShow'
[string "*ChatFrame.xml:15_OnHyperlinkClick"]:1: in function <[string "*ChatFrame.xml:15_OnHyperlinkClick"]:1>

Locals: zoneId = 1585
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 0 = <table> {
 }
 599 = <table> {
 }
 369 = <table> {
 }
 631 = <table> {
 }
 33 = <table> {
 }
 389 = <table> {
 }
 34 = <table> {
 }
 544 = <table> {
 }
 552 = <table> {
 }
 36 = <table> {
 }
 37 = <table> {
 }
 150 = <table> {
 }
 600 = <table> {
 }
 608 = <table> {
 }
 616 = <table> {
 }
 624 = <table> {
 }
 632 = <table> {
 }
 449 = <table> {
 }
 529 = <table> {
 }
 43 = <table> {
 }
 469 = <table> {
 }
 585 = <table> {
 }
 489 = <table> {
 }
 601 = <table> {
 }
 47 = <table> {
 }
 617 = <table> {
 }
 48 = <table> {
 }
 641 = <table> {
 }
 649 = <table> {
 }
 530 = <table> {
 }
 546 = <table> {
 }
 13 = <table> {
 }
 562 = <table> {
 }
 602 = <table> {
 }
 618 = <table> {
 }
 450 = <table> {
 }
 650 = <table> {
 }
 230 = <table> {
 }
 547 = <table> {
 }
 555 = <table> {
 }
 571 = <table> {
 }
 1 = <table> {
 }
 619 = <table> {
 }
 129 = <table> {
 }
 532 = <table> {
 }
 540 = <table> {
 }
 70 = <table> {
 }
 556 = <table> {
 }
 572 = <table> {
 }
 451 = <table> {
 }
 533 = <table> {
 }
 169 = <table> {
 }
 557 = <table> {
 }
 565 = <table> {
 }
 90 = <table> {
 }
 2118 = <table> {
 }
 189 = <table> {
 }
 673 = <table> {
 }
 672 = <table> {
 }
 668 = <table> {
 }
 642 = <table> {
 }
 560 = <table> {
 }
 542 = <table> {
 }
 550 = <table> {
 }
 558 = <table> {
 }
 576 = <table> {
 }
 289 = <table> {
 }
 575 = <table> {
 }
 574 = <table> {
 }
 598 = <table> {
 }
 109 = <table> {
 }
 559 = <table> {
 }
 554 = <table> {
 }
 553 = <table> {
 }
 548 = <table> {
 }
 545 = <table> {
 }
 229 = <table> {
 }
 531 = <table> {
 }
 543 = <table> {
 }
 409 = <table> {
 }
 30 = <table> {
 }
 349 = <table> {
 }
 329 = <table> {
 }
}
(for control) = 0
_ = 0
zone = <table> {
 1 = "Dun Morogh"
 2 = "Longshore"
 4 = "Blasted Lands"
 8 = "Swamp of Sorrows"
 1021 = "Thelgen Rock"
 32 = "The Cemetary"
 64 = "The Maclure Vineyards"
 128 = "Ziata'jai Ruins"
 1023 = "Saltspray Glen"
 4090 = "The Dawning Square"
 1024 = "Sundown Marsh"
 1025 = "The Green Belt"
 129 = "Mizjah Ruins"
 1036 = "Angerfang Encampment"
 130 = "Silverpine Forest"
 1038 = "Dragonmaw Gates"
 1039 = "The Lost Fleet"
 131 = "Kharanos"
 2098 = "Dawning Wood Catacombs"
 33 = "Stranglethorn Vale"
 2102 = "Thunderbrew Distillery"
 132 = "Coldridge Valley"
 1056 = "Darrow Hill"
 1057 = "Thoradin's Wall"
 2118 = "Brill Town Hall"
 133 = "Gnomeregan"
 267 = "Hillsbrad Foothills"
 134 = "Gol'Bolar Quarry"
 536 = "Addle's Stead"
 269 = "Dun Algaz"
 135 = "Frostmane Hold"
 271 = "Southshore"
 34 = "Echo Ridge Mine"
 68 = "Lake Everstill"
 136 = "The Grizzled Den"

**Comment by BreakBB** [comment]
Hey @Theguyxd thanks for reporting this! Can you tell in which part (like actual position inside the dungeon) of BRD you've been? 🤔 I ask because it seems Questie can not differentiate between two different versions of BRD.

**Comment by BreakBB** [comment]
For the team: Questie is looking for a zoneId `1585` as seen just below the stacktrace in the OP. But `l10n.zoneLookup` has no hint about that ID, we only properly handle `1584` for BRD. I think we just need to add the second one, but that'll require testing imo.

**Comment by MyTechnoHunter** [comment]
@BreakBB 
![image](https://github.com/Questie/Questie/assets/55214545/1a4e05f4-832b-45f1-bc69-e5a8a148ba5d)
 there is already one?

**Comment by Theguyxd** [comment]
We had just entered the dungeon. A bit to the right just when you enter the dungeon. I believe there are boxes and stuff there. I was not standing on top of any boxes or anything tho.

**Comment by Theguyxd** [comment]
I was standing to the right just as you enter the dungeon. Close to were there are boxes and stuff. Not all the way to the corner or anything. Just slightly to the right of where you end up after entering BRD. 

I don't know if it matters but I had been jumping around on top of stuff while waiting for the other people to arrive. A friend of mine was also there close to me and he did not have the same error. He has not updated the addon in a while tho from what he told me. When I come to think of it, I think you have to enable LUA error pop-ups in Classic Era since it's off by default. So maybe he did get it but it didn't show up? In either case some of the elements in regard to quest information that you usually get when clicking a linked quest in chat was broken. I don't know how to explain it other than the tooltip that pops up looking "off".

I'm sure I'll do BRD again here shortly since I just hit 60 on my warrior. I'll see if I can reproduce it.

**Comment by MyTechnoHunter** [comment]
screenshots please :)

**Comment by BreakBB** [comment]
Thank you very much for the fast response @Theguyxd 👍🏻 

If it right next to the entrance then it will be easy to verify this our self as well. Especially since the PTR is still up and we can just go to BRD with a level 80 character on Wrath 😁 The issue _should_ also happen in Wotlk, not Era/HC alone.

**Comment by Theguyxd** [comment]
Hey again. Small update to this thread. Today I was in a group preparing to do a dungeon when someone linked a quest that takes place inside BRD. I got an error when clicking this quest, just the same way I did before. The funny thing is that I was standing inside the SW bank this time. I haven't checked if the error is the exact same or not but I'll post it here.


## LUA error
Message: ...face/AddOns/Questie/Modules/Tracker/TrackerUtils.lua:339: attempt to index field '?' (a nil value)
Time: Tue Sep 19 00:23:43 2023
Count: 1
Stack: ...face/AddOns/Questie/Modules/Tracker/TrackerUtils.lua:339: attempt to index field '?' (a nil value)
[string "@Interface/AddOns/Questie/Modules/Tracker/TrackerUtils.lua"]:339: in function <...face/AddOns/Questie/Modules/Tracker/TrackerUtils.lua:333>
[string "@Interface/AddOns/Questie/Modules/Tracker/TrackerUtils.lua"]:358: in function `GetZoneNameByID'
[string "@Interface/AddOns/Questie/Modules/QuestLinks/Link.lua"]:271: in function <Interface/AddOns/Questie/Modules/QuestLinks/Link.lua:263>
[string "@Interface/AddOns/Questie/Modules/QuestLinks/Link.lua"]:101: in function `CreateQuestTooltip'
[string "@Interface/AddOns/Questie/Modules/QuestLinks/Link.lua"]:41: in function `SetHyperlink'
[string "@Interface/FrameXML/ItemRef.lua"]:421: in function <Interface/FrameXML/ItemRef.lua:1>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Interface/AddOns/Blizzard_CombatLog/Blizzard_CombatLog.lua"]:3535: in function `SetItemRef'
[string "@Interface/FrameXML/ChatFrame.lua"]:3795: in function <Interface/FrameXML/ChatFrame.lua:3794>
[string "=[C]"]: in function `ChatFrame_OnHyperlinkShow'
[string "*ChatFrame.xml:15_OnHyperlinkClick"]:1: in function <[string "*ChatFrame.xml:15_OnHyperlinkClick"]:1>

Locals: zoneId = 1585
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 0 = <table> {
 }
 599 = <table> {
 }
 369 = <table> {
 }
 631 = <table> {
 }
 33 = <table> {
 }
 389 = <table> {
 }
 34 = <table> {
 }
 544 = <table> {
 }
 552 = <table> {
 }
 36 = <table> {
 }
 37 = <table> {
 }
 150 = <table> {
 }
 600 = <table> {
 }
 608 = <table> {
 }
 616 = <table> {
 }
 624 = <table> {
 }
 632 = <table> {
 }
 449 = <table> {
 }
 529 = <table> {
 }
 43 = <table> {
 }
 469 = <table> {
 }
 585 = <table> {
 }
 489 = <table> {
 }
 601 = <table> {
 }
 47 = <table> {
 }
 617 = <table> {
 }
 48 = <table> {
 }
 641 = <table> {
 }
 649 = <table> {
 }
 530 = <table> {
 }
 546 = <table> {
 }
 13 = <table> {
 }
 562 = <table> {
 }
 602 = <table> {
 }
 618 = <table> {
 }
 450 = <table> {
 }
 650 = <table> {
 }
 230 = <table> {
 }
 547 = <table> {
 }
 555 = <table> {
 }
 571 = <table> {
 }
 1 = <table> {
 }
 619 = <table> {
 }
 129 = <table> {
 }
 532 = <table> {
 }
 540 = <table> {
 }
 70 = <table> {
 }
 556 = <table> {
 }
 572 = <table> {
 }
 451 = <table> {
 }
 533 = <table> {
 }
 169 = <table> {
 }
 557 = <table> {
 }
 565 = <table> {
 }
 90 = <table> {
 }
 2118 = <table> {
 }
 189 = <table> {
 }
 673 = <table> {
 }
 672 = <table> {
 }
 668 = <table> {
 }
 642 = <table> {
 }
 560 = <table> {
 }
 542 = <table> {
 }
 550 = <table> {
 }
 558 = <table> {
 }
 576 = <table> {
 }
 289 = <table> {
 }
 575 = <table> {
 }
 574 = <table> {
 }
 598 = <table> {
 }
 109 = <table> {
 }
 559 = <table> {
 }
 554 = <table> {
 }
 553 = <table> {
 }
 548 = <table> {
 }
 545 = <table> {
 }
 229 = <table> {
 }
 531 = <table> {
 }
 543 = <table> {
 }
 409 = <table> {
 }
 30 = <table> {
 }
 349 = <table> {
 }
 329 = <table> {
 }
}
(for control) = 0
_ = 0
zone = <table> {
 1 = "Dun Morogh"
 2 = "Longshore"
 4 = "Blasted Lands"
 8 = "Swamp of Sorrows"
 1021 = "Thelgen Rock"
 32 = "The Cemetary"
 64 = "The Maclure Vineyards"
 128 = "Ziata'jai Ruins"
 1023 = "Saltspray Glen"
 4090 = "The Dawning Square"
 1024 = "Sundown Marsh"
 1025 = "The Green Belt"
 129 = "Mizjah Ruins"
 1036 = "Angerfang Encampment"
 130 = "Silverpine Forest"
 1038 = "Dragonmaw Gates"
 1039 = "The Lost Fleet"
 131 = "Kharanos"
 2098 = "Dawning Wood Catacombs"
 33 = "Stranglethorn Vale"
 2102 = "Thunderbrew Distillery"
 132 = "Coldridge Valley"
 1056 = "Darrow Hill"
 1057 = "Thoradin's Wall"
 2118 = "Brill Town Hall"
 133 = "Gnomeregan"
 267 = "Hillsbrad Foothills"
 134 = "Gol'Bolar Quarry"
 536 = "Addle's Stead"
 269 = "Dun Algaz"
 135 = "Frostmane Hold"
 271 = "Southshore"
 34 = "Echo Ridge Mine"
 68 = "Lake Everstill"
 136 = "The Grizzled Den"

**Comment by Theguyxd** [comment]
On a different note. I don't know if this is a bug or not but I do remember it being mentioned somewhere that Questie hides PvP related quests when on hardcore servers. This seems to be the case at least. Just wanted to add that this quest which is completed by doing AV still shows up in all the locations you can grab it when not playing hardcore. https://www.wowhead.com/classic/quest=8375/remember-alterac-valley

Thanks for all the great work you're doing! Cheers.

**Comment by Theguyxd** [comment]
Okay, so the LUA error happens when clicking any quest that takes place inside BRD. No matter where I happen to be located.
