### ISSUE TITLE
Quest Removed - 10900 / the-mark-of-vashj

### ISSUE THREAD

**Issue by SaintKatherine** [Questie/Questie#5128]
## Description

Skar'this the Heretic does not offer [70+] The Mark of Vashj if you are higher level than 70, the quest is in the game if you pick it up before 71, but removed after. Can the quest be hidden if you are level 71+? It makes my map look messy.

## Wowhead link

https://www.wowhead.com/quest=10900/the-mark-of-vashj

https://www.wowhead.com/quest=10900/the-mark-of-vashj#comments:id=529420:reply=128387

## Questie & WoW version

Questie 8.1.1

**Comment by MyTechnoHunter** [comment]
fixed with https://github.com/Questie/Questie/pull/5127 stay tuned for it in the next release (hopefully)

**Comment by BreakBB** [comment]
Also merging this with #4979 - thanks for reporting this @SaintKatherine 👍🏻
