### ISSUE TITLE
Hide quest icons no longer functions

### ISSUE THREAD

**Issue by nitroinferno** [Questie/Questie#5133]
## Bug description

Ever since HC classic era blizz patch, Latest versions of questie do not hide or fade any icons when hiding quest icons or focusing quests.

## Questie & WoW version

Latest version of questie on curseforge as of this posting date.

I have tried deleting my questie addon and reinstalling and issue persists.

**Comment by Muehe** [comment]
Same bug as #5086 so closing here. Thanks anyway for reporting. :+1:

**Comment by nitroinferno** [comment]
Thanks! Figured so just wanted to make sure it was also captured regarding the 'hide icon' function in addition to focus.
