### ISSUE TITLE
Completed task data loss, can it still be recovered?

### ISSUE THREAD

**Issue by Dcryfm** [Questie/Questie#5134]
## Question

Because there was a problem with the game client, I directly deleted the entire client and then reinstalled it. I did not keep the plugin's configuration file. After reinstalling Questie, I found that the completed tasks still appear as accessible. Can we customize whether the task is completed or any other way to solve this problem? thanks!

**Comment by BreakBB** [comment]
Hey @Dcryfm
Are completed quests showing on the map for you? Or do you mean your „Journey“ which you access by right clicking the minimap icon?

**Comment by Dcryfm** [comment]
Hello @BreakBB 
Thank you for your reply. I don't use GitHub very much. I'm sorry for replying to you so late. I have no further questions now. Thank you again

**Comment by BreakBB** [comment]
@Dcryfm no worries 😃 👍🏻
