### ISSUE TITLE
Using Focus Quest option in the tracker doesn't hide the patrol paths of NPCs related to other quests.

### ISSUE THREAD

**Issue by Cabro** [Questie/Questie#5139]
![image](https://github.com/Questie/Questie/assets/1155017/36372de5-3c04-46aa-9553-99aa4c240434)

From my understanding, this is happening since the beginning.

Might be worth to make sure the patrol paths are added back after unfocusing quest.

8.10.3

**Comment by BreakBB** [comment]
I think @Logonz already had a fix for this somewhere?
