### ISSUE TITLE
The quest "totem of affliction" (101) is marked as lvl 25 but has lvl 30 mobs

### ISSUE THREAD

**Issue by capangel** [Questie/Questie#5141]
All in the title. This cause players to enter the area thinking they can deal with the mobs that are in fact much stronger than suggested (ghoul lvl 30). Big problem for hardcore mode.

**Comment by Cabro** [comment]
This is a blizzard thing. I think there were other mobs of lower level also somewhere

**Comment by BreakBB** [comment]
Questie tries to be as close to the Blizzard data as possible. Blizzard marked this quest as level 25, so we do the same.
