### ISSUE TITLE
Not Showing Completed Quest Icon WotLK

### ISSUE THREAD

**Issue by HenryGus8854** [Questie/Questie#5142]
## Bug description
The Completed Quest Icon in not showing up on the mini map nor the regular map. This is affecting every Quest That I complete. I can see all available Quests and all the Icons for where and what type of quest it is but once it is done it no longer shows on the map. It will show on the mini map once I get into the render distance of the NPC with quest. 

## Screenshots
In this Screenshot you can see in the Mini map that I have the Icon for a complete quest but as you can see you can not see it in the main map.
![image](https://github.com/Questie/Questie/assets/54637690/65b40595-7d11-4979-b053-e1d5a74ab410)

## Questie & WoW version
Questie Version: V8.10.3
Wow WotLK Classic Version:  3.4.2.50664

**Comment by BreakBB** [comment]
Hey @HenryGus8854 did you check your settings? In the "General" section you should verify "Enable Completed Quest Icons" is checked

**Comment by HenryGus8854** [comment]
> Hey @HenryGus8854 did you check your settings? In the "General" section you should verify "Enable Completed Quest Icons" is checked.
> 
> A screenshot of your General settings would be good if that doesn't help

Thank you so Much I spent so long looking in the tracker and map settings but didn't see anything. I feel incredibly stupid because it was right Infront of me. Again Thank you so much!

**Comment by HenryGus8854** [comment]
Closed

**Comment by BreakBB** [comment]
No worries @HenryGus8854 

We are currently restructuring our settings to keep these kind of problems at a minimum. You are not the first one, not finding a specific setting 😅
