### ISSUE TITLE
[OUTDATED] Quest x2 - Winterspring

### ISSUE THREAD

**Issue by SimonDlgs** [Questie/Questie#5143]
## Description

Error with an marker on the map. The marker is named « [OUTDATED] » .
All quest is from [Winterspring](https://www.wowhead.com/classic/fr/zone=618/berceau-de-lhiver-winterspring) region.

## Wowhead link

Wowhead link (Quest 1) : https://www.wowhead.com/wotlk/fr/quest=5085/gel%C3%A9e-myst%C3%A8re
Wowhead link (Quest 2) : https://www.wowhead.com/wotlk/fr/quest=5245/les-esprits-troubl%C3%A9s-de-keltheril

## Screenshots

_Quest1:_
![WoWScrnShot_100223_201232](https://github.com/Questie/Questie/assets/57448240/5c862bfb-50a4-4246-a950-3b9a3acc4857)

_Quest2:_
![WoWScrnShot_100223_201943](https://github.com/Questie/Questie/assets/57448240/ed85b9d4-bebf-4780-9220-ec02663c14a2)

## Questie & WoW version

**Questies version**: 8.10.3
**Wow version**: WOTLK

**Comment by SimonDlgs** [comment]
So, that cannot be fixed on futur update?
And the strangest thing is that I can't speak with npc for the quest.

**Comment by MyTechnoHunter** [comment]
we can certainly look at it, what other addons are you using? can you test with just questie enabled?

**Comment by BreakBB** [comment]
This looks indeed like a Blizzard issue, not something releated to Questie 😅

**Comment by SimonDlgs** [comment]
> From what i see, that is on PTR. Since that's the blizzard quest helper. I checked the database for questie, those quests are not named "périmé" in it.
> 
> frFR is the only locale that uses French language, right?

Yes, it's french translation. Search keyword « OUTDATED ».

**Comment by SimonDlgs** [comment]
> This looks indeed like a Blizzard issue, not something releated to Questie 😅

Nope, I disabled all my addons, and the marker error not showing. I continue my tests

**Comment by BreakBB** [comment]
@SimonDlgs Can you disable the new Blizzard objectives and see if there is a Questie icon underneath? There are check boxes on the map for it.

**Comment by BreakBB** [comment]
These are our translations for the quests you posted above:

https://github.com/Questie/Questie/blob/d8b7dd611a18b0f1af472b943e9702750c700c9a/Localization/lookups/Wotlk/lookupQuests/frFR.lua#L2427

https://github.com/Questie/Questie/blob/d8b7dd611a18b0f1af472b943e9702750c700c9a/Localization/lookups/Wotlk/lookupQuests/frFR.lua#L2523

**Comment by SimonDlgs** [comment]
After lot of desabling on my addons, I found the problem and it's not questies but « **Dugi Questing Essential** » .

Sorry for this post... ^^

**Comment by SimonDlgs** [comment]
> These are our translations for the quests you posted above:
> 
> https://github.com/Questie/Questie/blob/d8b7dd611a18b0f1af472b943e9702750c700c9a/Localization/lookups/Wotlk/lookupQuests/frFR.lua#L2427
> 
> > "Gelée mystère"
> 
> https://github.com/Questie/Questie/blob/d8b7dd611a18b0f1af472b943e9702750c700c9a/Localization/lookups/Wotlk/lookupQuests/frFR.lua#L2523
> 
> > "Les esprits troublés de Kel'Theril"

Translations are good!
