### ISSUE TITLE
Rogue - Reagent Vendors Not Showing?

### ISSUE THREAD

**Issue by Nevicar** [Questie/Questie#5145]
## Bug description
When playing my character that is a rogue and turning on reagent tracking within Questie, no poison vendors are shown on the map. 

I have attached a screenshot where my character is interacting with a poison vendor, with the map open, and the Questie minimap settings showing reagents selected. 

I have done a full reset from the Questie settings to reset everything to default, tried again, still does not show. Reagent vendor tracking works correctly when playing other classes like paladin and druid.

## Screenshots
![image](https://github.com/Questie/Questie/assets/5368799/af0f6fff-ec7c-4c22-aa66-e6b1ba4028b1)

## Questie & WoW version
Questie 8.10.3 
WoW 3.4.2.50664

**Comment by Cabro** [comment]
Right, we need a poisons section :D

**Comment by BreakBB** [comment]
> Right, we need a poisons section :D

The "Reagents" section is updated with a poison icon for Rogues, since most vendors sell both. I think, we are just missing that vendor.

**Comment by Nevicar** [comment]
This was just an example, to be clear, I went from 1-78 over the last 2 weeks and did not encounter a single poison vendor via Questie. I had to use the in game tracking. I can go to the full map view and see no poison vendors either.

![image](https://github.com/Questie/Questie/assets/5368799/bbc3f3bf-6ac1-4f12-8d71-f8db6af4cbb2)

**Comment by Cabro** [comment]
I can confirm Nevicar, poison vendors simply dont show

**Comment by BreakBB** [comment]
Alright, I'll look into it. Thanks for reporting it @Nevicar  👍🏻

**Comment by BreakBB** [comment]
![grafik](https://github.com/Questie/Questie/assets/33514570/7760ddff-5fa5-48ca-88c0-4977be01830a)

Working now, will be part of the next release 👍🏻
