### ISSUE TITLE
Completed Quest Icons Not Showing on Main Map

### ISSUE THREAD

**Issue by KoopaDude** [Questie/Questie#5147]
## Bug description
Version 8.10.3 on WOTLK Classic. Completed quest icons do not show up on main map, but do on minimap when you're close enough. It doesn't seem effect all quests, but at least some.

## Screenshots
![Screenshot 2023-10-05 195038](https://github.com/Questie/Questie/assets/147115778/8ce47c47-30b1-4d5f-9073-9d0e2ecf7a90)

Settings image here, and I have Enable Completed Quest Icons checked.

![Screenshot 2023-10-05 195110](https://github.com/Questie/Questie/assets/147115778/b8239b17-da4e-4df6-aade-15210f9d8307)

You'll see on the minimap that I'm near a completed quest, but it's not showing on the main map. However, you'll see on the northeast corner that another quest does show.

## Questie & WoW version
Which version of Questie are you using? You can find it by:
8.10.3

Please also state if your quest issue is about Classic Era/SoM or Wotlk.
WOTLK Classic

**Comment by MyTechnoHunter** [comment]
disable any addon other than questie and test again please.. i see a button for mapster?

**Comment by KoopaDude** [comment]
![Screenshot 2023-10-05 201955](https://github.com/Questie/Questie/assets/147115778/4c2a0860-a616-41e8-9159-ce478042a0fe)

Disabled All But Questie

![Screenshot 2023-10-05 201943](https://github.com/Questie/Questie/assets/147115778/ad79efe9-7ba4-4ca2-823b-f6dd593df67c)

No completed quest on main map

**Comment by MyTechnoHunter** [comment]
togle the setting please and thanks.. now you have _nothing_ on the main map.. not even available quests..

**Comment by KoopaDude** [comment]
I had completed all available quests...the only thing left was the Bandits! quest to turn on. All settings were set correctly.

**Comment by MyTechnoHunter** [comment]
was just noticing the difference tween first map pic and last..

the reason for the toggle is that it is possible the setting didnt "take" after the update..

**Comment by BreakBB** [comment]
Hey @KoopaDude can you disable the "Hide unexplored area Icons" and see if that helps?

If it doesn't you can try to recompile the database. There is a button in the "Advanced" section of the settings.

**Comment by KoopaDude** [comment]
I have since updated to 8.10.4, and without changing any settings from my last session it appears to be working. Completed quests are showing on the main map now. I'll report back with any exceptions. Thanks everyone.

**Comment by KoopaDude** [comment]
Scratch that.  Still broke. See screenshot.

![Screenshot 2023-10-07 142937](https://github.com/Questie/Questie/assets/147115778/3c700efb-1b4a-4bd6-8aa5-89210260515f)

On version 8.10.4 now.

**Comment by Cabro** [comment]
What quest is that? That yellow qustion mark is blizzard

**Comment by KoopaDude** [comment]
Quest is "On the Wings of a Hippogryph"

**Comment by KoopaDude** [comment]
Disabled all addons except Questie, and it still persists.

![Screenshot 2023-10-07 143355](https://github.com/Questie/Questie/assets/147115778/487f9422-1b09-4554-b932-b8e2e637e8cb)
![Screenshot 2023-10-07 143412](https://github.com/Questie/Questie/assets/147115778/a71dd04e-5361-4e01-b3a0-eec65a35c4bc)

**Comment by Cabro** [comment]
What exactly is the issue?

**Comment by KoopaDude** [comment]
Completed quest icon is not on the main map, as pictured above. So without reading the quest text thoroughly, or luckily being near the turn in the point, you don't know where to turn in quests.

**Comment by Cabro** [comment]
Do other quest icons show when you complete other quests or is it only this one?

**Comment by KoopaDude** [comment]
This issue is with most quests. A few seemed to work in the earlier levels, but most did not. Am I missing a setting or something?

**Comment by KoopaDude** [comment]
Good example here. Two completed quests. One showing on main map, the other isn't.

The one showing is Vindicator Boros. The one now showing is Return to Topher Loaal. Both are showing on minimap as seen in screenshot below. 

![Screenshot 2023-10-07 145410](https://github.com/Questie/Questie/assets/147115778/218dca47-3958-405c-b94b-a62fc3bb59f3)

**Comment by Cabro** [comment]
Was this during the event where you turn in the quest to save the isle?

**Comment by KoopaDude** [comment]
No event was going on. Typical quest.

**Comment by BreakBB** [comment]
> Hey @KoopaDude can you disable the "Hide unexplored area Icons" and see if that helps?

Did you try this @KoopaDude ?

**Comment by KoopaDude** [comment]
I did try, yes. Sorry, forgot to mention that. I'm in an explored area anyway, but yes I did try that and it had no effect.

**Comment by Cabro** [comment]
On the Wings of a Hyppogryph, by my accounts, should show. It has all the required info in DB.

Same with Return to Topher Looal. It has all the info in DB. Quest finishers are at those spots in DB for both quests.

I remember Dyaxler saying something about "hide unexplored area icons", and it was something like it is very hit and miss on the ones close to unexplored areas.

Also, if you uncheck that option, do give it a few seconds to repop all the icons on maps, that takes a while.
Let me know

**Comment by KoopaDude** [comment]
Since updating to 8.10.4, uncheck the HIDE UNEXPLORED AREA ICONS seems to have fixed it. Must be because it's too close to a border or something? Weird. This didn't fix while using 8.10.3, but since updating it does. So I suppose we are once again in the "resolved" phase. LOL. Thanks @Cabro and everyone. Appreciate all the help. 
![Screenshot 2023-10-07 173121](https://github.com/Questie/Questie/assets/147115778/d106b6ac-d51a-49f8-a8cc-bbb05c165167)

**Comment by Cabro** [comment]
Happy to have found the source for this!
