### ISSUE TITLE
The map button "Hide Questie" is visible during recompile with the option to hide the button active.

### ISSUE THREAD

**Issue by Cabro** [Questie/Questie#5151]
The button is hidden according to the options after the DB recompile is finished, which can take some minutes, and it makes a mess out of the map UI.
![image](https://github.com/Questie/Questie/assets/1155017/efc116eb-9872-4962-a7af-ae71544418a3)

8.10.3

**Comment by BreakBB** [comment]
This was fixed in b73343c8818e3e64041cba73c770f29fadeaa7f9
