### ISSUE TITLE
lua error in classic wow (addon version 8.10.4)

### ISSUE THREAD

**Issue by yourapple** [Questie/Questie#5154]
7x ...ceQuestie/Modules/FramePool/QuestieFrame.lua:137: attempt to index field 'data' (a nil value)
[string "@Questie/Modules/FramePool/QuestieFrame.lua"]:137: in function <...ceQuestie/Modules/FramePool/QuestieFrame.lua:126>

Locals:
self = QuestieFrame162 {
 FakeShow = <function> defined @Questie/Modules/FramePool/QuestieFrame.lua:412
 FadeLogic = <function> defined @Questie/Modules/Map/QuestieMap.lua:631
 frameId = 162
 loaded = true
 FakeHide = <function> defined @Questie/Modules/FramePool/QuestieFrame.lua:395
 0 = <userdata>
 glow = QuestieFrame162Glow {
 }
 SetFade = <function> defined @Questie/Modules/Map/QuestieMap.lua:620
 FadeOut = <function> defined @Questie/Modules/FramePool/QuestieFrame.lua:366
 MMA_FRAME_STRATA = "LOW"
 MMA_FRAME_LEVEL = 9
 texture = Texture {
 }
 MMA_VISIBLE = true
 BaseOnShow = <function> defined @Questie/Modules/FramePool/QuestieFrame.lua:236
 BaseOnHide = <function> defined @Questie/Modules/FramePool/QuestieFrame.lua:260
 ShouldBeHidden = <function> defined @Questie/Modules/FramePool/QuestieFrame.lua:427
 UpdateTexture = <function> defined @Questie/Modules/FramePool/QuestieFrame.lua:264
 glowTexture = Texture {
 }
 Unload = <function> defined @Questie/Modules/FramePool/QuestieFrame.lua:299
 GlowUpdate = <function> defined @Questie/Modules/FramePool/QuestieFrame.lua:218
 FadeIn = <function> defined @Questie/Modules/FramePool/QuestieFrame.lua:380
}
(*temporary) = nil
(*temporary) = GameTooltip {
 0 = <userdata>
 GetBackdropColor = <function> defined @SharedXML/SharedTooltipTemplates.lua:290
 SetHyperlink = <function> defined =[C]:-1
 SetGuildBankItem = <function> defined =[C]:-1
 _owner = QuestieFrame162 {
 }
 SetBackdropBorderColor = <function> defined @SharedXML/SharedTooltipTemplates.lua:294
 manualOrder = <table> {
 }
 questOrder = <table> {
 }
 SetCraftItem = <function> defined =[C]:-1
 comparing = false
 TopOverlay = Texture {
 }
 GetBackdropBorderColor = <function> defined @SharedXML/SharedTooltipTemplates.lua:298
 SetUnitDebuff = <function> defined =[C]:-1
 SetItemByID = <function> defined =[C]:-1
 SetLootItem = <function> defined =[C]:-1
 SetQuestItem = <function> defined =[C]:-1
 SetBorderBlendMode = <function> defined @SharedXML/SharedTooltipTemplates.lua:302
 FadeOut = <function> defined =[C]:-1
 BottomOverlay = Texture {
 }
 SetInboxItem = <function> defined =[C]:-1
 layoutType = "TooltipDefaultLayout"
 shoppingTooltips = <table> {
 }
 SetMerchantItem = <function> defined =[C]:-1
 SetQuestLogItem = <function> defined =[C]:-1
 ShownAsMapIcon = false
 SetTradeTargetItem = <function> defined =[C]:-1
 npcAndObjectOrder = <table> {
 }
 SetTradePlayerItem = <function> defined =[C]:-1
 SetSendMailItem = <function> defined =[C]:-1
 updateTooltip = 0.150000
 SetInventoryItem = <function> defined =[C]:-1
 SetUnitBuff = <function> defined =[C]:-1
 NineSlice = Frame {
 }
 TooltipBackdropOnLoad = <function> defined @SharedXML/SharedTooltipTemplates.lua:271
 SetUnitAura = <function> defined =[C]:-1
 SetBuybackItem = <function> defined =[C]:-1
 SetTradeSkillItem = <function> defined =[C]:-1
 SetBagItem = <function> defined =[C]:-1
 needsReset = true
 miniMapIcon = true
 SetBackdropColor = <function> defined @SharedXML/SharedTooltipTemplates.lua:286
 SetLootRollItem = <function> defined =[C]:-1
 SetAuctionItem = <function> defined =[C]:-1
}
(*temporary) = <userdata>
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'data' (a nil value)"

7x ...eQuestie/Modules/Tooltips/MapIconTooltip.lua:78: attempt to index field 'data' (a nil value)
[string "@Questie/Modules/Tooltips/MapIconTooltip.lua"]:78: in function <...eQuestie/Modules/Tooltips/MapIconTooltip.lua:38>

Locals:
self = QuestieFrame162 {
 FakeShow = <function> defined @Questie/Modules/FramePool/QuestieFrame.lua:412
 FadeLogic = <function> defined @Questie/Modules/Map/QuestieMap.lua:631
 frameId = 162
 loaded = true
 FakeHide = <function> defined @Questie/Modules/FramePool/QuestieFrame.lua:395
 0 = <userdata>
 glow = QuestieFrame162Glow {
 }
 SetFade = <function> defined @Questie/Modules/Map/QuestieMap.lua:620
 FadeOut = <function> defined @Questie/Modules/FramePool/QuestieFrame.lua:366
 MMA_FRAME_STRATA = "LOW"
 MMA_FRAME_LEVEL = 9
 texture = Texture {
 }
 MMA_VISIBLE = true
 BaseOnShow = <function> defined @Questie/Modules/FramePool/QuestieFrame.lua:236
 BaseOnHide = <function> defined @Questie/Modules/FramePool/QuestieFrame.lua:260
 ShouldBeHidden = <function> defined @Questie/Modules/FramePool/QuestieFrame.lua:427
 UpdateTexture = <function> defined @Questie/Modules/FramePool/QuestieFrame.lua:264
 glowTexture = Texture {
 }
 Unload = <function> defined @Questie/Modules/FramePool/QuestieFrame.lua:299
 GlowUpdate = <function> defined @Questie/Modules/FramePool/QuestieFrame.lua:218
 FadeIn = <function> defined @Questie/Modules/FramePool/QuestieFrame.lua:380
}
_ = 1
_ = 1
_ = 1
alpha = 1
Tooltip = GameTooltip {
 0 = <userdata>
 GetBackdropColor = <function> defined @SharedXML/SharedTooltipTemplates.lua:290
 SetHyperlink = <function> defined =[C]:-1
 SetGuildBankItem = <function> defined =[C]:-1
 _owner = QuestieFrame162 {
 }
 SetBackdropBorderColor = <function> defined @SharedXML/SharedTooltipTemplates.lua:294
 manualOrder = <table> {
 }
 questOrder = <table> {
 }
 SetCraftItem = <function> defined =[C]:-1
 comparing = false
 TopOverlay = Texture {
 }
 GetBackdropBorderColor = <function> defined @SharedXML/SharedTooltipTemplates.lua:298
 SetUnitDebuff = <function> defined =[C]:-1
 SetItemByID = <function> defined =[C]:-1
 SetLootItem = <function> defined =[C]:-1
 SetQuestItem = <function> defined =[C]:-1
 SetBorderBlendMode = <function> defined @SharedXML/SharedTooltipTemplates.lua:302
 FadeOut = <function> defined =[C]:-1
 BottomOverlay = Texture {
 }
 SetInboxItem = <function> defined =[C]:-1
 layoutType = "TooltipDefaultLayout"
 shoppingTooltips = <table> {
 }
 SetMerchantItem = <function> defined =[C]:-1
 SetQuestLogItem = <function> defined =[C]:-1
 ShownAsMapIcon = false
 SetTradeTargetItem = <function> defined =[C]:-1
 npcAndObjectOrder = <table> {
 }
 SetTradePlayerItem = <function> defined =[C]:-1
 SetSendMailItem = <function> defined =[C]:-1
 updateTooltip = 0.150000
 SetInventoryItem = <function> defined =[C]:-1
 SetUnitBuff = <function> defined =[C]:-1
 NineSlice = Frame {
 }
 TooltipBackdropOnLoad = <function> defined @SharedXML/SharedTooltipTemplates.lua:271
 SetUnitAura = <function> defined =[C]:-1
 SetBuybackItem = <function> defined =[C]:-1
 SetTradeSkillItem = <function> defined =[C]:-1
 SetBagItem = <function> defined =[C]:-1
 needsReset = true
 miniMapIcon = true
 SetBackdropColor = <function> defined @SharedXML/SharedTooltipTemplates.lua:286
 SetLootRollItem = <function> defined =[C]:-1
 SetAuctionItem = <function> defined =[C]:-1
}
maxDistCluster = 1
mapId = 1419
r = 0.930000
g = 0.460000
b = 0.130000
a = 0.800000
(*temporary) = <function> defined =[C]:-1
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'data' (a nil value)"
lastTooltipShowTimestamp = 19509.940000
_MapIconTooltip = <table> {
 GetEventObjectiveTooltip = <function> defined @Questie/Modules/Tooltips/MapIconTooltip.lua:471
 GetAvailableOrCompleteTooltip = <function> defined @Questie/Modules/Tooltips/MapIconTooltip.lua:444
 GetObjectiveTooltip = <function> de

**Comment by BreakBB** [comment]
Hey @yourapple can you explain when exactly did this happen?

On login?
On quest accept?
On hovering something?

**Comment by BreakBB** [comment]
Any news on this @yourapple ?
