### ISSUE TITLE
HELP，My game character can't use questie.

### ISSUE THREAD

**Issue by eloichui** [Questie/Questie#5158]
My character couldn't use questie. I clicked on the question mark icon in the top right corner and nothing happened. Typing "/questie" didn't happen either. I have re-installed the game client, the "WTF" and "interface" directories have also been deleted, and the game version and addon version are correct. But the problem remains the same. However, when I tried to re-create a new Level 1 character under this account, the addon worked fine, but I switched to my level 67 character plugin and it didn't work.I tried it from version 7.1.0 to 8.10.4 and it didn't work at this level.
game version  : WOTLKC    3.4.2
addin version :questie 8.10.2
![image](https://github.com/Questie/Questie/assets/147460814/45703d3c-9124-4286-a363-613a1e8e2e4d)
![image](https://github.com/Questie/Questie/assets/147460814/53193be0-e1dd-4af6-8785-ee9516ffec09)

**Comment by MyTechnoHunter** [comment]
please update questie. 8.10.4 is the latest

**Comment by MyTechnoHunter** [comment]
wait, your pic didnt match your text.. nvm updating.. can you try using curseforge to delete settings?

**Comment by BreakBB** [comment]
> wait, your pic didnt match your text.. nvm updating.. can you try using curseforge to delete settings?

If the WTF folder has been deleted this shouldn't be necessary 🤔 

Can you run this command @eloichui `/run Questie.db.global.dbIsCompiled = false;ReloadUI()`?

**Comment by eloichui** [comment]
> > wait, your pic didnt match your text.. nvm updating.. can you try using curseforge to delete settings?
> 
> If the WTF folder has been deleted this shouldn't be necessary 🤔
> 
> Can you run this command @eloichui `/run Questie.db.global.dbIsCompiled = false;ReloadUI()`?

Thank you for your reply, the command can run normally, but the result is still not displayed.
![image](https://github.com/Questie/Questie/assets/147460814/daaf98c3-372e-45aa-b074-5cd58cdc3f68)
However, other lower-level roles are normal, and clicking the question mark icon left and right will display the window in the image.
![image](https://github.com/Questie/Questie/assets/147460814/f4d239e2-1d35-4d12-ac5d-197859b79fd7)

**Comment by BreakBB** [comment]
Does the command run on your level 67 character and report any output?

Also is that character on the same server/account?

**Comment by eloichui** [comment]
> /run Questie.db.global.dbIsCompiled = false;ReloadUI()

Yes, the output is the same. Both roles are on the same server under the same account.

**Comment by BreakBB** [comment]
Yet you can not open the Questie settings with `/questie`?
If you can share a screenshot of the „General“ settings.

Also did you try to disable all addons except Questie?

**Comment by eloichui** [comment]
> Yet you can not open the Questie settings with `/questie`? If you can share a screenshot of the „General“ settings.
> 
> Also did you try to disable all addons except Questie?
I repeated the test for two days, and finally I described the process again. At first, as described above, typing "/questie" did not respond. Then, I cleaned up the game Settings, the plugin configuration, and then I changed the game language to "english" on Battle.net, and finally entered the game, and found that "questie" was running properly, so I guess it must be my language version of the system and the language version of the game and the plugin is not compatible. Thank you very much for your patient answer.
![image](https://github.com/Questie/Questie/assets/147460814/6cfb34c8-7338-45b8-9e48-a04fab309eb8)

**Comment by BreakBB** [comment]
But you also said it is just one character having this problem and new characters do not have the problem 🤔 

What language did you use, that did not work? Also now switching back to that language now also doesn't help?

Can you do us a favor and install both of these addons and log in again with a broken state?

https://www.curseforge.com/wow/addons/bug-grabber
https://www.curseforge.com/wow/addons/bugsack

You'l then get a green/red bag symbol on your minimap. Maybe there are errors which are simply not showing up for you, which would help us a ton!

**Comment by BreakBB** [comment]
Hey @eloichui what is the state on this?
