### ISSUE TITLE
QueryItemSingle error on wotlk

### ISSUE THREAD

**Issue by aglarcz** [Questie/Questie#5159]
![image](https://github.com/Questie/Questie/assets/17107410/d591f990-e18c-4dec-81bd-d640cf1736bb)
On new patch of Wotlk Classic

**Comment by BreakBB** [comment]
Hey @aglarcz are you on the latest version of Questie - v8.10.5?

And are you using an addon manager to update your addons or are you doing it manually?

**Comment by aglarcz** [comment]
Yes, i am on v8.10.5 via curseforge. Also tried to remove it manually with all the settings and reinstall but still the error occurs.

**Comment by BreakBB** [comment]
Please disable all addons except Questie and see if that helps.

**Comment by aglarcz** [comment]
Looks like fixed after disabling and reenabling Auctionator. No idea why but will continue to monitor.

**Comment by BreakBB** [comment]
Sometimes the order in which addons are loaded confuses some of the addons and break things... 🤷🏻 Glad it's working now 👍🏻 Feel free to report back if something comes up again!
