### ISSUE TITLE
Blizzard's new quest tracker keeps overlaying the questie icons

### ISSUE THREAD

**Issue by jebo80** [Questie/Questie#5167]
## Bug description
Blizzard's new quest tracker keeps overlaying the questie icons. At the beginning I set that I want to have the symbols of Questie and after a relog the symbols of Blizzard are again on the world map

## Screenshots

![Questie](https://github.com/Questie/Questie/assets/114264088/4cf72932-5f97-4dce-9c32-6d93b747e93c)

## Questie & WoW version

newest Questie updated by Curse Client 8.10.6 
and newest WoW Version updated by Bnet Launcher

Please also state if your quest issue is about Classic Era/SoM or Wotlk.
-->
Wotlk

**Comment by BreakBB** [comment]
Update Leatrix Maps, they delivered a somewhat strange release. The latest version added an option to disable the Blizzard objectives:

![grafik](https://github.com/Questie/Questie/assets/33514570/4f16ab1d-fd42-45f8-9bbb-28ee0ccfafe9)
