### ISSUE TITLE
Cannot get this addon to work for Retail... can you fix it?

### ISSUE THREAD

**Issue by Xpatro** [Questie/Questie#5168]
This addon doesnt work for retail, love that it says the "zone" over each quest or that its warrior-quest only.
but it doesnt work on retail, somehow it works in classic but i want it in retail!...

Help!

**Comment by MyTechnoHunter** [comment]
Questie is not compatible with the Retail client, as far as I know,  there is no plan to do so either 

The client/API/Quest data is too different

**Comment by BreakBB** [comment]
Questie does not support retail and most likely never will as the amount of work required to get all the data is just too big.
