### ISSUE TITLE
WotLK -  Questie: [ERROR] Missing objective data for quest  24873   Return with two strains of Blight.

### ISSUE THREAD

**Issue by RoanSythen** [Questie/Questie#5169]
## Bug description

Questie: [ERROR] Missing objective data for quest  24873   Return with two strains of Blight.

Getting this message. It's one of the raid quests inside ICC.

## Questie & WoW version
WotLK

**Comment by RoanSythen** [comment]
Questie Version: 8.10.6
WoW: 3.4.3

**Comment by BreakBB** [comment]
Fixed in 89d9ef33b00743e6bf8cdeaec1e2afa5ccaee332

Will be in the next release, thanks for the report @RoanSythen
