### ISSUE TITLE
Questie not working interface "table index is nill"

### ISSUE THREAD

**Issue by aeraiba** [Questie/Questie#5176]
Hello,

For some reason my questie is not working at all. I deleted it and reinstalled it, I still get the same error- /AddOns/Questie/Database/Zones/zoneDB.lua.172 table index is nill. Please some help me fix this issue. 

Thank you.

**Comment by BreakBB** [comment]
Hey @aeraiba are you using an addon manager like CurseForge to install your addons? What version are you installing? Are you playing WotLK or something else?

Did you check your addons folder if you have more than one version of Questie installed?

**Comment by MyTechnoHunter** [comment]
Also, questie version and game version please

**Comment by aeraiba** [comment]
Hi all,

I am using CurseForge. The version is 3.4.3. I am currently playing WOTLK.

> Hey @aeraiba are you using an addon manager like CurseForge to install your addons? What version are you installing? Are you playing WotLK or something else?
> 
> Did you check your addons folder if you have more than one version of Questie installed?

**Comment by MyTechnoHunter** [comment]
> Hi all,
> 
> I am using CurseForge. The version is 3.4.3. I am currently playing WOTLK.
> 
> > Hey @aeraiba are you using an addon manager like CurseForge to install your addons? What version are you installing? Are you playing WotLK or something else?
> > Did you check your addons folder if you have more than one version of Questie installed?

3.4.3 is game version.. questie version (latest) is 8.10.9

**Comment by aeraiba** [comment]
> > Hi all,
> > I am using CurseForge. The version is 3.4.3. I am currently playing WOTLK.
> > > Hey @aeraiba are you using an addon manager like CurseForge to install your addons? What version are you installing? Are you playing WotLK or something else?
> > > Did you check your addons folder if you have more than one version of Questie installed?
> 
> 3.4.3 is game version.. questie version (latest) is 8.10.9

Oh okay yea my questie is up to date (v 8.10.9)

**Comment by MyTechnoHunter** [comment]
ok, make sure your curseforge is updating the right game version (upper right corner, wrath not retail or era)

make sure you are logged out of the game then, click questie in the list of addons, right click it and delete settings (saved variables)
then right click the addon again and click re-install

start the game again and see if the error still exists

**Comment by aeraiba** [comment]
> ok, make sure your curseforge is updating the right game version (upper right corner, wrath not retail or era)
> 
> make sure you are logged out of the game then, click questie in the list of addons, right click it and delete settings (saved variables) then right click the addon again and click re-install
> 
> start the game again and see if the error still exists

this worked! thank you!
