### ISSUE TITLE
Disable Questie Settings Reset Reminder Note

### ISSUE THREAD

**Issue by salt-mountain** [Questie/Questie#5181]
## Question

Is there a way to disable the Questie `Please Note` that shows upon login reminding users that, at some point, their settings will reset? 

I apologize if this is a duplicate question, I tried searching the issues but either my search skills aren't great and I didnt catch someone else asking this or I'm possibly just blind.

**Comment by BreakBB** [comment]
Hey @salt-mountain 

Yeah, we totally get this message starts to be annoying. Our remaining work on that topic takes longer than expected and will still need a bit. We are quite limited in time on the team, but it’s actively worked on.

For now you can remove this line in your Questie installation:

https://github.com/Questie/Questie/blob/master/Modules/Migration.lua#L240

You‘ll find you mr Questie installation in your `Interface/AddOns` folder.

**Comment by salt-mountain** [comment]
Much appreciated for the manual change and totally understand !
