### ISSUE TITLE
How to reset Available Quests tracking under Quests by Zone tab

### ISSUE THREAD

**Issue by cboschindeed** [Questie/Questie#5186]
## Question

Greetings!  I've been playing Vanilla Hardcore on the Everlook private server, and my character recently died so I deleted it from my list of characters and recreated that character using the same name as before.  When I loaded up Questie, I noticed that Questie was still keeping track of the quests I had completed for the previous same-named character.  This surprised me because I figured Questie could tell if the current character had completed the quest in the game or not.  I've tried several things to try and reset this by deleting/modifying certain files and folders, but it doesn't seem to reset the Available Quests list for the new character.  Is there some way to reset this, or am I going to have to create a new character name every time?

Thank you in advance for the help!

**Comment by cboschindeed** [comment]
I was able to get this problem addressed in the Questie Discord... I had to go to:
`hermes-proxy\AccountData\ <account_name>\Everlook\ <character_name>`
Then delete the "completed_quests.csv".  I also confirmed that that's all you need to do to reset the quests... You don't have to mess with the luas at all.

yttrium hypothosized that it was either Questie caching completions after getting invalid API responses about completed quests, or HermesProxy caching them.  Vanilla servers don't actually support this kind of API call, so Hermes has to either not support it (old behavior) or fake it (current behavior).

**Comment by cboschindeed** [comment]
I was able to get this problem addressed in the Questie Discord... I had to go to:
`hermes-proxy\AccountData\ <account_name>\Everlook\ <character_name>`
Then delete the "completed_quests.csv".  I also confirmed that that's all you need to do to reset the quests... You don't have to mess with the luas at all.

yttrium hypothosized that it was either Questie caching completions after getting invalid API responses about completed quests, or HermesProxy caching them.  Vanilla servers don't actually support this kind of API call, so Hermes has to either not support it (old behavior) or fake it (current behavior).

**Comment by antonjakovlev** [comment]
Thank you!
