### ISSUE TITLE
LUA errors on quest completion, acceptance and abandon.

### ISSUE THREAD

**Issue by damonsmithies** [Questie/Questie#5187]
## Bug description
**Upon ANY quest completion**
_Message: ...ce/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:2011: attempt to index field 'AutoUntrackedQuests' (a nil value)
Time: Thu Nov  2 12:15:13 2023
Count: 2
Stack: ...ce/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:2011: attempt to index field 'AutoUntrackedQuests' (a nil value)
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "@Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua"]:2011: in function `RemoveQuest'
[string "@Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua"]:525: in function `CompleteQuest'
[string "@Interface/AddOns/Questie/Modules/Quest/QuestEventHandler.lua"]:309: in function `QuestTurnedIn'
[string "@Interface/AddOns/Questie/Modules/Quest/QuestEventHandler.lua"]:543: in function <...e/AddOns/Questie/Modules/Quest/QuestEventHandler.lua:539>

Locals: (*temporary) = <function> defined =[C]:-1_

**Upon ANY quest acceptance**
_Message: ...erface/AddOns/Questie/Modules/Quest/QuestieQuest.lua:471: attempt to index field 'AutoUntrackedQuests' (a nil value)
Time: Thu Nov  2 12:15:28 2023
Count: 4
Stack: ...erface/AddOns/Questie/Modules/Quest/QuestieQuest.lua:471: attempt to index field 'AutoUntrackedQuests' (a nil value)
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "@Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua"]:471: in function `val'
[string "@Interface/AddOns/Questie/Modules/TaskQueue.lua"]:8: in function <Interface/AddOns/Questie/Modules/TaskQueue.lua:6>

Locals: (*temporary) = 0.003000
(*temporary) = <function> defined =[C]:-1_

**Upon ANY quest abandon**
**Message: ...ce/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:2011: attempt to index field 'AutoUntrackedQuests' (a nil value)
Time: Thu Nov  2 12:24:14 2023
Count: 1
Stack: ...ce/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:2011: attempt to index field 'AutoUntrackedQuests' (a nil value)
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "@Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua"]:2011: in function `RemoveQuest'
[string "@Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua"]:572: in function `AbandonedQuest'
[string "@Interface/AddOns/Questie/Modules/Quest/QuestEventHandler.lua"]:356: in function `MarkQuestAsAbandoned'
[string "@Interface/AddOns/Questie/Modules/Quest/QuestEventHandler.lua"]:339: in function <...e/AddOns/Questie/Modules/Quest/QuestEventHandler.lua:338>

Locals: (*temporary) = <function> defined =[C]:-1**

## Questie & WoW version
Questie version: v8.10.10
WoW Version: Wotlk Classic

**Comment by BreakBB** [comment]
Hey @damonsmithies sorry for the late response on this. Is this still an issue for you? Iirc other reported this went away after a short time.

We have yet to figure out what is causing it.

**Comment by damonsmithies** [comment]
HI @BreakBB - I will check tonight. I had it disabled for a while because of the issue but pretty sure I noticed it on an ALT last night. Let me check when I am home and I will come back to you with an answer and see if I can help in any way.

**Comment by BreakBB** [comment]
Hey @damonsmithies any news on this?
