### ISSUE TITLE
Missing objective data for quest 24749

### ISSUE THREAD

**Issue by RoanSythen** [Questie/Questie#5189]
## Bug description

Shadowmourne quest line, first infusion giving this error.

## Screenshots

![image](https://github.com/Questie/Questie/assets/132086624/f6b3091d-3af3-47d3-88bb-925f033c6477)

## Questie & WoW version

WotLK Classic
Questie version 8.10.10

**Comment by BreakBB** [comment]
Fixed in da4c6e58c5952827798755a88e435c91fbc82545
