### ISSUE TITLE
[ERROR] The quest 78136 is missing from Questie's Database...

### ISSUE THREAD

**Issue by Kamehadouken** [Questie/Questie#5190]
## Bug description
I boosted a Warrior to level 80, and the quest they give you to talk to the Warrior trainer is not in Questie yet. I assume there's different quests for each class/race - this was a Human Warrior.

## Screenshots
![image](https://github.com/Questie/Questie/assets/88213465/e6c8680a-80e3-411a-a678-b03e49b94681)

## Questie & WoW version
v8.10.10
WotLK

**Comment by BreakBB** [comment]
Thanks @Kamehadouken for the report. I'll merge this with #5195
