### ISSUE TITLE
Minimize Hides, No Way to Restore

### ISSUE THREAD

**Issue by dailytabs** [Questie/Questie#5194]
"Minimize In Combat" is misleading. I needed a quest item and expected it to be restorable. It wasn't. It wasn't actually minimized, but it was closed/hidden entirely.

I expected it to work as if I had clicked on the "Active Quests Header", which would allow me to restore it during combat.

If we aren't going to get an actual minimize, can we at least get the text changed?

Is there a way to actually minimize, without hiding completely, when in combat - as the text says it's supposed to do?

**Comment by BreakBB** [comment]
Hey @dailytabs

Questie is doing the same with "Minimize in Combat" active, as clicking the "Active Quests Header" - both are calling the same functionality. But Questie simply can't expand the Tracker during combat (API limitation from Blizzard).

Questie is also not "hiding" the Tracker entirely, as you can at least still see the "Active Quests Header", but this is mostly a definition/wording thing I guess.

You suggest to change the checkbox text to actually be "Hide in Combat"?

**Comment by BreakBB** [comment]
Any news on this @dailytabs ?
