### ISSUE TITLE
Mennet Carkad Quest is only available Undead Rogue's pls check this quest

### ISSUE THREAD

**Issue by Mehmetikbaldundar** [Questie/Questie#5197]

**Comment by Mehmetikbaldundar** [comment]
[10]Mennet Carkad - Brill - Tristfal Glades /// Quest is only available Undead Rogue's pls check this quest

**Comment by BreakBB** [comment]
Hey @Mehmetikbaldundar are you playing Wotlk or Era or HC?

**Comment by Mehmetikbaldundar** [comment]
Wotlk
