### ISSUE TITLE
LUA every time I turn a quest in - WOTLK

### ISSUE THREAD

**Issue by volostyle** [Questie/Questie#5198]
21x Questie/Modules/Quest/QuestieQuest.lua:471: attempt to index field 'AutoUntrackedQuests' (a nil value)
[string "@Questie/Modules/Quest/QuestieQuest.lua"]:471: in function `val'
[string "@Questie/Modules/TaskQueue.lua"]:8: in function <Questie/Modules/TaskQueue.lua:6>

Locals:
(*temporary) = nil
(*temporary) = 783
(*temporary) = "attempt to index field 'AutoUntrackedQuests' (a nil value)"
questId = 783

**Comment by Muehe** [comment]
It sounds like something went wrong with your saved variables, you can try if the "Reset Questie" button on the Advanced tab of the Questie options solves the problem. Be aware this will reset all of your Questie settings.

**Comment by volostyle** [comment]
So the issue seems to be related to the tracker. For some reason the tracker was disabled, which caused the LUA to trigger. I just enabled it and it seems to have resolved the issue.

**Comment by Muehe** [comment]
Well that shouldn't happen. Thanks for the report and tracking down the cause. :+1:
