### ISSUE TITLE
Custom translation support

### ISSUE THREAD

**Issue by Jakanis** [Questie/Questie#5199]
There's several addons that translate WoW to some languages (Polish, Ukrainian, Czech and some more)
It would be awesome if we could use these translations in Questie in a way similar to Auctionator - https://www.curseforge.com/wow/addons/turkish-translations-module-for-auctionator
So we'd create addon that contains our version of your lookups and translation folders and add more languages to Questie.
Could we have something like that?

**Comment by Muehe** [comment]
It is technically possible to refactor the translation module (called l10n) to support more languages and it shouldn't be all that hard to do. But there are currently around 2000 strings only for the Questie UI to be translated. And that doesn't include quests, items, and so forth, for which we currently don't have a way of overwriting them in the default Blizzard UI. So refactoring that would be a lot harder, and those strings would number in the tens of thousands probably.

I wouldn't be opposed to the change if anybody wants to work on it, but it's not really a priority for us right now.

That said if you want to do it regardless of the problems outlined above we can provide guidance on how to go about it here or on our Discord.

**Comment by Jakanis** [comment]
Well, we already try to handle default Blizzard UI, and so do other translators, so no worries about that :) 
We just need to translate strings used by Questie. And, if I understood correctly, these took from 'Localization' folder, which we could translate.
