### ISSUE TITLE
Next Quest pointer

### ISSUE THREAD

**Issue by cjoyner66** [Questie/Questie#5201]

**Comment by BreakBB** [comment]
Hey @cjoyner66 
if you install [TomTom](https://www.curseforge.com/wow/addons/tomtom) you will be able to right click on a quest in the Tracker to set the TomTom arrow guide you there.

Do you need more than that?

**Comment by MyTechnoHunter** [comment]
it sounded like they wanted a route? might be better with something like restedXP or GuideL:ime, Dugi guides?

**Comment by voidtype** [comment]
@BreakBB I actually just came here looking for the same thing. It would be great if questie had the ability to automatically queue the next objective somehow.

Closest distance objective as the crow flies is a good dumb algorithm, i think this is guaranteed to be some constant factor of the actual fastest route

**Comment by BreakBB** [comment]
Closing this in favor for #3208
