### ISSUE TITLE
Error during initalization

### ISSUE THREAD

**Issue by SirJorb** [Questie/Questie#5205]
## Bug description
Upon login and /reload, I get the error "Questie: [ERROR] Error during initalization! Interface/AddOns/Questie/Modules/QuestieStream.lua:244: attempt to perform arithmetic on local 'a' (a nil value)

## Screenshots
![image](https://github.com/Questie/Questie/assets/23423782/14d26409-b096-4fd0-8409-82b81f4dbbc0)

## Questie & WoW version
Questie v8.10.12
Classic Era

**Comment by SirJorb** [comment]
Sometimes the error is instead "Questie: [ERROR] Error during initialization! Interface/AddOns/Questie/Database/Zones/zoneDB.lua:172 table index is nil

I also forgot to mention that these still occur after reinstalling the addon.

![image](https://github.com/Questie/Questie/assets/23423782/2dc863bf-1842-41a4-a484-2f4795f80602)

**Comment by BreakBB** [comment]
Hey @SirJorb
Can you run the following command in the chat and do a `/reload` afterwards?

`/run Questie.db.global.dbIsCompiled = false`
