### ISSUE TITLE
option to turn off start-up messages

### ISSUE THREAD

**Issue by Jakel666** [Questie/Questie#5208]
![Skærmbillede 2023-11-29 kl  09 04 01](https://github.com/Questie/Questie/assets/118360798/04925c2a-c1f3-4a87-ab42-050cec1c146a)

I would love to be able turn off these messages. I am inundated with them on startup from various add-ons.

Thank you for the great work!

**Comment by BreakBB** [comment]
Hey @Jakel666
This message will be removed with the next release, which will be published very soon. Together with it, other messages will also be removed.

I'll merge this with #4612 - We'll look into adding one, for the few other messages remaining.

**Comment by Jakel666** [comment]
awesome!
