### ISSUE TITLE
questie wants this quest for sod

### ISSUE THREAD

**Issue by supernicky22** [Questie/Questie#5220]
Quest in dialog not present in QuestDB!

Quest ID: 77571
Quest Name: Relikte der Kaldorei
Quest Text: Die Kaldorei sind ein uraltes Volk und unsere verlorenen Relikte können auf ganz Azeroth gefunden werden. Mithilfe dieser Relikte können die Geister Euch beibringen, wie Ihr Eure Verbindung zum Traum stärken könnt.

Die Grellkin haben ein solches Relikt gestohlen. Tötet sie und bergt das Relikt. Dann folgt seiner Führung und erlernt eine neue Kampftechnik. Kehrt zu mir zurück, wenn Ihr fertig seid.
Objective Text: Bergt das Relikt von den Grellkin in Shadowglen. Folgt der Führung des Relikts und lernt eine neue Fähigkeit, dann erstattet Mardant Strongoak Bericht.
Reward Text: 
Reward XP: 85
Character: Lvl 3 NIGHTELF DRUID
Questgiver: Creature-0-5250-1-780-3597-0000698243
Player Coords:  [1438]  (58.631, 40.348)
QuestLog: 459, 916, 4495, 
Client: 1.15.0 SoD
Questie: v9.0.2

**Comment by BreakBB** [comment]
Fixed in eb55343c25820ff6a22a3f0a04120ac1bf122b00
