### ISSUE TITLE
Hiding map icons still shows NPC patrol paths for available quests

### ISSUE THREAD

**Issue by bioandroid** [Questie/Questie#5238]
## Bug description
Unable to hide the available quest markers for patrolling NPCs. For example the quest "[Demon Scarred Cloak](https://www.wowhead.com/quest=770/the-demon-scarred-cloak)" in Mulgore still shows the path for Ghost Howl even when "Enable Icons" is unchecked.

## Screenshots
![2023-12-04 17_03_30-Greenshot](https://github.com/Questie/Questie/assets/31831713/210a7c4d-af66-4e2b-b7b8-f2bd09968100)

## Questie & WoW version
Questie v.9.0.4
WoW Classic - SoD - v 1.15.0

Please also state if your quest issue is about Classic Era/SoM or Wotlk.
Classic Season of Discovery

**Comment by BreakBB** [comment]
Thanks for reporting this @bioandroid 

There were similar cases before v9.0.0, where the waypoint lines were not removed. Looks like you found another case which we will look into 👍🏻

**Comment by bioandroid** [comment]
Thanks for the response! This prompted me to try:

- Checking "Enable Icons"
- Checking "Available Normal Quests"
- Unchecking "Available Normal Quests"

This resolved the issue! All quests are now properly hidden, including paths of quest givers.
