### ISSUE TITLE
Quest: 1789/1790 Not repeatable

### ISSUE THREAD

**Issue by Leviasan** [Questie/Questie#5239]
## Description
The next quests are not repeatable: "The Symbol of Life".

## Wowhead link
[the-symbol-of-life dwarf](https://www.wowhead.com/classic/quest=1789/the-symbol-of-life)
[the-symbol-of-life human](https://www.wowhead.com/classic/quest=1790/the-symbol-of-life)

## Screenshots
![image](https://github.com/Questie/Questie/assets/50718918/68f12a1e-e251-48c8-bd6a-c82f2adba0b9)

## Questie & WoW version
Questie: 9.0.4
WoW: 1.15.0 (52409)
State: Classic Era
-->

**Comment by Zardilann** [comment]
I just turned in the quest https://www.wowhead.com/classic/quest=1788/the-tome-of-divinity
I no longer have the quest item needed and have learned the Redemption spell.
I can no longer pick up the repeatable quest.

**Comment by Cabro** [comment]
So these quests should only be repeatable until you learn Redemption?

**Comment by Cabro** [comment]
Fixed in https://github.com/Questie/Questie/commit/92ed39bb3e748d19343596f294f953529ec329ce
