### ISSUE TITLE
Shaman Class Rune Quest 76156 - Stalk With The Earthmother

### ISSUE THREAD

**Issue by XiconQoo** [Questie/Questie#5250]
Quest in dialog not present in QuestDB!

Quest ID: 76156
Quest Name: Stalk With The Earthmother
Quest Text: I sense in you a hidden talent for the subtle arts, shaman.  Use this mask to infilrate the nearby Venture Company mine and steal their supplies.  It may not seem like a convincing disguise, but a skilled rogue can slip past any guard with naught but a winning smile and a cunning distraction.  I believe this capability lies within you as well.
Objective Text: Sneak into the Venture Company mine southeast of Thunder Bluff and collect 5 Seaforium Mining Charges from carts of blasting supplies, then return them to Boarton Shadetotem in Thunder Bluff.
Reward Text: 
Reward XP: 40
Questgiver: Creature-0-5211-1-27523-205729-0000710263
Character: Lvl 18 TAUREN SHAMAN
Player Coords:  [1456]  (39.524, 66.249)
QuestLog: 865, 894, 903, 3281, 877, 853, 891, 1061, 855, 6541, 962, 4921, 899, 821, 867, 8368, 850, 896, 
Client: 1.15.0 SoD
Questie: v9.0.4
Locale: enUS

**Comment by MyTechnoHunter** [comment]
Thank you for the report

**Comment by EmilLindegaard** [comment]
If I were to help adding some Season of Discovery quests like this one, should I add a correction in Database/Correction/sodQuestFixes.lua or are you going to be updating the main database so corrections like this are not needed?

**Comment by BreakBB** [comment]
Fixed in 6aca4148494935159d969b6c152a3e1ae7c3e2c8
