### ISSUE TITLE
Missing quest "Repelling Invaders"

### ISSUE THREAD

**Issue by leojo** [Questie/Questie#5280]
Quest in tracker not present in QuestDB!

Quest ID: 79090
Quest Name: Repelling Invaders
Quest Text: Some of the Warsong Outriders lie defeated, but the battle still rages...
Objective Text: Bring the Warsong Outrider Mark to Felore Moonray, Priestess of the Moon, at the Moonwell base in Ashenvale.
Character: Lvl 25 HUMAN WARRIOR
Player Coords:  [1440]  (56.255, 60.155)
QuestLog: 79090, 303, 8399, 1701, 
Client: 1.15.0 SoD
Questie: v9.2.1
Locale: enUS

**Comment by BreakBB** [comment]
Fixed in a47018d97ceba19f9221f7f83f66b104df0cc789
