### ISSUE TITLE
SOD | Questie-v9.2.1 -  DC every 30 seconds (and use of Way of Earth rune ?)

### ISSUE THREAD

**Issue by Piloof** [Questie/Questie#5289]
Hi,

Since I got my "Way of Earth" rune as a shaman, I noticed that once I equip it, the game crashes (WOW51900319).
This occurs approximatively every 30 seconds once I reconnect again (I timed it with my phone).

I tried unistall / reinstall.

Am I the only one ?
Regards,

**Comment by BreakBB** [comment]
Hey @Piloof did you disable all addons and see if the issue still happens? Also what if you only run Questie?

It is VERY unlikely for an addon to cause a game crash.

Also out of curiosity: What makes you think Questie is causing it?

**Comment by Piloof** [comment]
I just made a small video (sorry for the bad quality) : 
https://www.dropbox.com/scl/fi/p1l8y7anhjg3tavl0ck66/IMG_3185.MOV?rlkey=6wc98vtbuxwf5xgrtgv6wn69r&dl=0

Test procedure 
- Launch game with no addon
- Enable Questie
- Wait a little bit (to show the game doesn't crash)
- Activate the "Way of Earth Rune"
- Wait for Crash ==> occurs
- Launch the game
- Wait for the next crash (approx. 30 seconds later) ==> occurs
- Launch the game
- Remove the Way of Earth rune
- Wait a little bit to show that there is no crash

**Comment by BreakBB** [comment]
This really does not look related to Questie tbh. We are not checking any buff or Rune you equip 🤔 Also you are not accepting any quest or so.

So if you play without any addon and use the "Way of Earth" Rune, there will be no crash? Even if you engage in the world in any way?

I guess it is worth to enable all addons except Questie and see if the crash still happens.

**Comment by Piloof** [comment]
> So if you play without any addon and use the "Way of Earth" Rune, there will be no crash? Even if you engage in the world in any way?
>

No problem at all, sir. 

> This really does not look related to Questie tbh. We are not checking any buff or Rune you equip 🤔 Also you are not accepting any quest or so.

This ONLY occurs when I enable Questie. No matter what I do, I get DC'ed every 30sec.

> I guess it is worth to enable all addons except Questie and see if the crash still happens.

Already did, no problem.

**Comment by BreakBB** [comment]
Can you do me a favor and reproduce the crash while you have the "Profiler" of Questie active?

When ingame type `/questie` go to "Advanced" and click the "Open Profiler" button. Then wait for the crash.

I guess recording it in a video would be good again. If you are on a Windows system you can press the windows key + `G` to find a recording button. That should increase the quality and will limit the recording to the screen (no sound needed 👍🏻 )

**Comment by Piloof** [comment]
> I guess recording it in a video would be good again. If you are on a Windows system you can press the windows key + `G` to find a recording button. That should increase the quality and will limit the recording to the screen (no sound needed 👍🏻 )

Thanks for the tip :D 

I recorded a new video : https://www.dropbox.com/scl/fi/45b4aizd1fhgq08tswrv5/World-of-Warcraft-2023-12-13-16-59-09.mp4?rlkey=swyxv9s10537es0s8sgiwfl74&dl=0

The video is 11 minutes long (sorry for that). I open the Profiler from 9:50 onwards.

Test procedure 

- 0:00 : Lauch game with no addon
- 0:29 : Enable "Way of Earth" rune (0:29) - Wait to check whether the game crashes ==> the game doesn't crash after 1 minute
- 1:30 : Repeat the same test with all addons enabled, but not Questie ==> the game doesn't crash
- 3:08 : Reload UI with all addon and Questie
- 3:18 : Remove "Way of Earth" to check whether the game crashes ==> the game crashes before I manage to do that
- 3:30 : Reload game and remove "Way of Earth" to check whether the game crashes ==> the game doesn't crash
- 5:05 : Use "Way of Earth" rune to check whether the game crashes
- 5:14 : The game crashes
- 5:29 : Game reloaded and wait
- 6:02 : The game crashes
- 6:10 : Reload game and remove "Way of Earth" rune (6:38) ==> the game doesn't crash
- 7:12 : Redo the same test procedure with only Questie on and no other addon ==> the same happens
- 9:55 : Make several crashes occur with "Open Profiler"
- 11:10 : Open Profiler with "Way of Earth" removed and then use "Way of Earth" rune

The profiler seems to get crazy when I activate the "Way of Earth" rune (12:18) ==> looks like some infinite loop or something ?

I hope this helps :)

**Comment by Piloof** [comment]
Screenshot of Profiler with no "Way of Earth" rune :
![Capture 1](https://github.com/Questie/Questie/assets/153747601/24436e78-9e57-4282-8005-1c093c553182)

Screenshot of Profiler with "Way of Earth" rune and right before crash :
![Capture 2](https://github.com/Questie/Questie/assets/153747601/16391797-761b-4a86-adf5-b26fe63d4ce8)

**Comment by PepGames** [comment]
I am having this same issue

**Comment by BreakBB** [comment]
Thank you very much @Piloof 

Can you do me a favor and also try the following:

- only Questie enabled
- no crashing rune
- reload and wait for like a minute (no crashes should appear)
- then open the profiler
- then add the rune (you should be able to move the profiler window out of the way for that)


The profiler only showed the regular "Questie is starting up after login", nothing unusual :/

**Comment by BreakBB** [comment]
@Piloof @PepGames 

Can you do me a favor and enable logging in Questie and then enable the rune?

Logging can be done in `/questie` -> Advanced ->
<img width="754" alt="image" src="https://github.com/Questie/Questie/assets/33514570/8e41a2fc-1632-4bd4-8b5f-254e50da797e">


For me it seems like the Blizzard API is either sending too many events while the rune is active or some really strange ones, which might result in this weird behaviour of Questie.

**Comment by BreakBB** [comment]
Hey @Piloof 

No, there is no file written for the logs, sorry.

But I had another look at the code. Could you only check the "DEBUG_DEVELOP" checkbox and share a screenshot of your chat? Maybe a small video if the chat gets flooded immediately. I have a trace that could explain this behavior.

**Comment by Piloof** [comment]
It keeps looping this message, until it crashes :
![image](https://github.com/Questie/Questie/assets/153747601/5a18c9a8-ee59-4448-b200-ea637237ed70)

It makes Questie go crazy when I activated the rune with Rockbiter, not when I put the rune in my legs.

Small Video : 
https://www.dropbox.com/scl/fi/zxh3e4hdpw5m0vp2o476x/World-of-Warcraft-2023-12-14-13-30-27.mp4?rlkey=jt4kwln7l2fubuft7ks0fuzao&dl=0

**Comment by BreakBB** [comment]
Thank you very much @Piloof !

That is what I expected. I'll provide a fix for it very soon and will also try to forward this issue to Blizzard.

**Comment by Piloof** [comment]
Awsome, thank you @BreakBB

**Comment by Piloof** [comment]
Thanks a lot @BreakBB.

Definitely stable now, awsome work.
I check with everything you taught me here ^^ The debug information are still indefinitely looping, but I bet this is a Blizzard issue now.

**Comment by BreakBB** [comment]
> The debug information are still indefinitely looping, but I bet this is a Blizzard issue now.

What do you mean by that? Are you still getting constant Questie chat messages in v9.2.2?

**Comment by Piloof** [comment]
> > The debug information are still indefinitely looping, but I bet this is a Blizzard issue now.
> 
> What do you mean by that? Are you still getting constant Questie chat messages about `SPELLS_CHANGED` in v9.2.2?

Still do, yes. But the game doesn't crashes anymore, so it doesn't really matter to me as far as I'm concerned as a WoW player ^^.

I made another video to see what happens now (with DEBUG info & Profiler Open), when I activate the rune :
https://www.dropbox.com/scl/fi/bnu0m02czltebhqoi8445/World-of-Warcraft-2023-12-14-15-15-01.mp4?rlkey=o445lk05j3u764n0swyalexm0&dl=0

**Comment by BreakBB** [comment]
Alright yeah. The following version will also fix this _ugly_ behavior. You can disable all the debug stuff now and should be able to play normally 👍🏻 

Thanks again for helping out on this and providing that much information ❤️

**Comment by Piloof** [comment]
You're welcome, you guys made the best addon ever ^^

**Comment by PepGames** [comment]
Thank you both!
