### ISSUE TITLE
ERROR Quest shown in photo

### ISSUE THREAD

**Issue by RaizDD** [Questie/Questie#5294]
My Issue is in Wow Wrath Of The Lich King Classic

**Comment by BreakBB** [comment]
Hey @RaizDD there is no photo attached

**Comment by RaizDD** [comment]
here is the picture sorry

Op vr 15 dec 2023 om 11:19 schreef Björn Böing ***@***.***>:

**Comment by RaizDD** [comment]
![image_2023-12-15_130118801](https://github.com/Questie/Questie/assets/153908310/b9ef095f-f80b-49e9-8b4a-a651f79fc8a2)

**Comment by BreakBB** [comment]
Thanks @RaizDD I am merging this with #5195
