### ISSUE TITLE
Missing Quest for Undead Rogues

### ISSUE THREAD

**Issue by elphaeba** [Questie/Questie#5298]
## Description
Quest in tracker not present in QuestDB!

Quest ID: 77669
Quest Name: The Scarlet Rune
Quest Text: Who were you in life, <playername>? A spy? A thief? A cook who was especially handy with a knife? Whatever your past, it's time to embrace new tactics. The rogues of the Forsaken seize every advantage offered to them.

The Scarlet Converts to the east fight like they've never seen combat, but the Crusade has issued them mystical runes to enhance their abilities. Steal one of these runes and learn its magic, then return to me.
Objective Text: Pickpocket or kill Scarlet Converts to find a rune, then use it to learn a new ability. Afterwards, return to David Trias in Deathknell.
Character: Lvl 12 SCOURGE ROGUE
Player Coords:  [1420]  (32.561, 64.922)
QuestLog: 5723, 8368, 408, 356, 360, 5724, 357, 371, 369, 7024, 77669, 450, 
Client: 1.15.0 SoD
Questie: v9.2.2
Locale: enUS

## Questie & WoW version
Season of Discovery
Questie 9.2.2

**Comment by Sommos** [comment]
Should be fixed in - https://github.com/Questie/Questie/pull/5325
