### ISSUE TITLE
SoD Quests showing in Era / HC

### ISSUE THREAD

**Issue by Hyrelia** [Questie/Questie#5301]
## Description

Season of Discovery quests are also showing on Hardcore servers (relic quest for human Paladin for example).

## Wowhead link

https://www.wowhead.com/classic/quest=77617/relics-of-the-light

## Questie & WoW version

Classic Era / HC

**Comment by Cabro** [comment]
Can you run `/dump Questie.IsSoD` ?

**Comment by Zepheron49** [comment]
I have the same issue. I ran /dump Questie.IsSoD and it gave me the result of:
[1]=false

**Comment by Zepheron49** [comment]
Also, completed question marks do not show up on the map anymore, and show as a resource node (gold dot) on the mini map when you get close.

**Comment by MyTechnoHunter** [comment]
In the icon selection screen make sure that you have the question mark selected for completion
 it sounds like you have one of the icons for the pfQuest chosen

**Comment by Zepheron49** [comment]
No, I don't use the pfQuest stuff. This only started with the update that was pushed today.
![image](https://github.com/Questie/Questie/assets/154289001/3390bd40-51c3-4c1f-8a9a-9bab34c3c265)

**Comment by MyTechnoHunter** [comment]
Are you using any other icon add-ons or map add-ons?

**Comment by Zepheron49** [comment]
I don't think so, but here's a everything I'm using:
![image](https://github.com/Questie/Questie/assets/154289001/1e742022-b10a-419e-b67a-8eafdad88741)
![image](https://github.com/Questie/Questie/assets/154289001/8756681a-23b2-4473-ac57-9c833a1a1c12)
![image](https://github.com/Questie/Questie/assets/154289001/d7977399-4b97-4d92-b958-e1c1ff22d803)
![image](https://github.com/Questie/Questie/assets/154289001/aecd0727-b882-47f4-8c06-037ffdf698d5)

**Comment by Zepheron49** [comment]
I just removed the current install and installed v9.2.2 and I don't have the issue of all the SoD points showing on the map, but I still don't see any of the quest completed question marks on quests that should show. I made no setting changes. Also, I'm playing on a warlock, if that helps.

**Comment by BreakBB** [comment]
In order to hide the SoD quests in Era (at least for now, till we have a proper fix), you need to "Recompile Database" @Zepheron49 @Hyrelia 

You do so in the "Advanced" section of the Questie settings: `/questie` -> Advanced -> Recompile Database

We're already looking into this issue.

**Comment by BreakBB** [comment]
Fixed in f78b4ce1076c4667353bf9255e2ed962b244ad4d and released in v9.2.10
