### ISSUE TITLE
Quest error.

### ISSUE THREAD

**Issue by jcmgamer** [Questie/Questie#5303]
Bug description:
Get an error that spams my chat every time I log in, reload, zone into an instance, or zone out of an instance.

Error Text:
Questie: [ERROR] [QuestieQuest]: [Tooltips] There was an error populating objectives for Summoner's Salt 78091 0 No error 
 [04:46:21 PM] ...erface/AddOns/Questie/Modules/Quest/QuestieQuest.lua:1126: bad argument #1 to 'next' (table expected, got nil) 
 [04:46:21 PM] [string "@Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua"]:72: in function <...erface/AddOns/Questie/Modules/Quest/QuestieQuest.lua:70>
[string "=[C]"]: in function `next'
[string "@Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua"]:1126: in function <...erface/AddOns/Questie/Modules/Quest/QuestieQuest.lua:1097>
[string "=[C]"]: in function `xpcall'
[string "@Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua"]:873: in function `UpdateObjectiveNotes'
[string "@Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua"]:1446: in function `PopulateObjectiveNotes'
[string "@Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua"]:715: in function `GetAllQuestIds'
[string "@Interface/AddOns/Questie/Modules/QuestieInit.lua"]:269: in function `?'
[string "@Interface/AddOns/Questie/Modules/QuestieInit.lua"]:351: in function <Interface/AddOns/Questie/Modules/QuestieInit.lua:349>

Questie Version:
9.2.5

Wow version:
Season of Discovery
1.15.0.52409

**Comment by BreakBB** [comment]
Oh wow, ouch. Thanks @jcmgamer we'll fix that!
