### ISSUE TITLE
The Sprouted Fronds (already done?)

### ISSUE THREAD

**Issue by jamvaru** [Questie/Questie#5310]
## Questie & WoW version

hmm, ok, so this quest is in Teldrassil, i'll include the screenshot.  I'm level 12 druid, already done it, afaik.
![Screenshot 2023-12-19 011820](https://github.com/Questie/Questie/assets/55780985/de3ba15e-2ebb-4ff7-bea9-991d1974a5b6)

**Comment by jamvaru** [comment]
oh, i'm doing classic hc on defias pillager server

**Comment by BreakBB** [comment]
Hey @jamvaru can you run the following command in the chat to verify you completed the quest?

`/dump C_QuestLog.IsQuestFlaggedCompleted(2399)`

**Comment by jamvaru** [comment]
actually i can't complete the quest now, because it is a glitch; just looked it up; not a questie problem
here's the wowhead link with relevant comment:  
https://www.wowhead.com/classic/quest=2399/the-sprouted-fronds

**Comment by BreakBB** [comment]
I know about the glitch and therefore asked 👍🏻 

Thanks for coming back to this. I'll close this issue then, but feel free to report anything else that pops up here on GitHub.
