### ISSUE TITLE
Questie lua Error

### ISSUE THREAD

**Issue by KitTCo1992** [Questie/Questie#5316]
## Bug description

The bug occurs on startup after loading a character into the world. Do not have access to any Questie functionality, including quest icons on the map/mini-map or right-clicking on the Questie AddOn icon next to the mini-map to go into the Settings. Tried uninstalling/reinstalling the AddOn, didn't work.

## Screenshots

![Questie](https://github.com/Questie/Questie/assets/72954507/eaf79fc7-7b05-40b5-b980-d33803b8fdc2)

## Questie & WoW version

Questie v9.2.8
Classic SoD

**Comment by BreakBB** [comment]
Hey @KitTCo1992 can you run the following command and see if that helps?

`/run Questie.db.global.dbIsCompiled = false; ReloadUI()`

**Comment by KitTCo1992** [comment]
@BreakBB That did work. Is that a permanent thing, or do I need to add that to the code somewhere?

**Comment by BreakBB** [comment]
It looks more like some addon/weird edge case broke your Questie installation. It should be a one time thing. If not, please come back and report it 👍🏻

**Comment by Guruhat** [comment]
Good Morning I am having the exact same error with Questie, but i do not know how to implement the fix you provided.  Thanks for your help.
* I have uninstalled and removed the folder and reinstalled to no avail.

**Comment by BreakBB** [comment]
Hey @Guruhat the command above is something you simply paste into the chat and send it. It will reset the Questie database and reload your UI.

**Comment by Guruhat** [comment]
Fantastic, will try that and let you know . Thanks very much!!

Guru

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
