### ISSUE TITLE
Questie: [ERROR] Error during initialization! Interface/AddOns/Questie/Database/QuestieDB.lua:925: attempt to index local 'startedBy' (a nil value)

### ISSUE THREAD

**Issue by Ewizzle** [Questie/Questie#5329]
Hey,

I am unable to use questie on my SOD character since latest update.

I have uninstalled/reinstalled questie.

Deleted Questie.lau file with no success.

![Screenshot 2023-12-20 114839](https://github.com/Questie/Questie/assets/154431786/dfef3ce6-d546-462d-8c7b-925117ed7ed9)

Any ideas on how to fix?

**Comment by BreakBB** [comment]
Hey @Ewizzle we had the same report in #5316 

Can you also try to run the following command and see if that helps?

`/run Questie.db.global.dbIsCompiled = false; ReloadUI()`

**Comment by Ewizzle** [comment]
@BreakBB that worked!!

Thank for the quick response!

**Comment by BreakBB** [comment]
Very good @Ewizzle 

Can you tell me if you are also playing Era/HC and switch between these WoW versions?

**Comment by Ewizzle** [comment]
I also play HC and frequently switch between the two.
