### ISSUE TITLE
Questie: [ERROR] Error during initialization! 

### ISSUE THREAD

**Issue by Corner4Real** [Questie/Questie#5353]
Reloaded UI and now this happened, cannot use Questie at all anymore tried reinstalling and deleting folders.
------------------------------------------------------------------------------------------------------------------------------------------------------
Questie: [ERROR] Error during initialization! Interface/AddOns/Questie/Database/QuestieDB.lua:925 attempt to index local 'startedBy' (a nil value)
------------------------------------------------------------------------------------------------------------------------------------------------------
Running SoD Classic wow.

**Comment by BreakBB** [comment]
Checkout #5333 - the command there will work for you as well.

A proper fix will be included in the next release!
