### ISSUE TITLE
Error during Initialization 

### ISSUE THREAD

**Issue by arekkosa** [Questie/Questie#5356]
Error during Initialization! Interface/Addons/Questie/Database/QuestieDB/lua:952: attempt to index local 'startedBy' (a nil value)
idk what to do...

**Comment by MyTechnoHunter** [comment]
Questie version?

**Comment by BreakBB** [comment]
Checkout https://github.com/Questie/Questie/issues/5329#issuecomment-1864449685

**Comment by BreakBB** [comment]
Will be fixed with #5338

**Comment by arekkosa** [comment]
thanks a lot guys <3
