### ISSUE TITLE
[quest]: 'Ruuzel' Has Incorrect Pathing

### ISSUE THREAD

**Issue by Sommos** [Questie/Questie#5375]
## Description

The quest 'Ruuzel' is currently showing the NPCs path incorrectly. It should be on the island (6,13) in Ashenvale, instead of on the coast.

## Wowhead link

https://www.wowhead.com/classic/quest=1009/ruuzel

## Screenshots

![image](https://github.com/Questie/Questie/assets/28623479/69c9da91-5603-4b2d-9412-5d30ae156e11)

## Questie & WoW version

v9.2.9
WoW Classic SoD - v1.15.052409

**Comment by BreakBB** [comment]
I guess [Lady Vespia](https://www.wowhead.com/classic/npc=10559/lady-vespia) is also listed as source of the required quest item and therefore the waypoint line shows up.

Removing that rare mob from the item `npcDrops` should be sufficient to fix this.

Do you want to take care of it @Sommos ?

**Comment by Sommos** [comment]
Yeah, I'll pick it up. Looks like a really simple change, but a review will be required if I have missed something.
