### ISSUE TITLE
Always performes Databse update on login

### ISSUE THREAD

**Issue by Aergernis** [Questie/Questie#5388]
## Bug description
Questie always performes a Database update on login or reload

## Questie & WoW version

WotLK
Questie 9.2.11

Edit:
Already tried with reinstalling Questie and removing WTF folder
Questie 9.2.10 is working fine

**Comment by BreakBB** [comment]
Hey @Aergernis did you disable all addons except Questie and see if that helps?

**Comment by Aergernis** [comment]
I'll try , but no other Adon was updatetd since then and only Questie was.

**Comment by Aergernis** [comment]
Strange, after disableing all other Addons and enable them again it's not updating anymore. Also tried to remove WTF again to see which Addon (disable one Addon at a time) was causing the problem, but still it's loading normaly. Don't know what was the probelm in first place.

**Comment by Cabro** [comment]
Maybe you didnt let it finish the database update?

**Comment by BreakBB** [comment]
Interesting 🤔 So something prevented writing to the Saved Variables aka the WTF folder. Maybe Windows itself or so 🤔
