### ISSUE TITLE
Objective map icons are not redrawn after a zone in/out

### ISSUE THREAD

**Issue by Cabro** [Questie/Questie#5392]
The icons for quest objectives that are located in dungeons are not redrawn after a zonein/zoneout. They are only drawn on world enter.
The object/npc tooltips are not redrawn either.
Before:
![image](https://github.com/Questie/Questie/assets/1155017/a1b34274-463b-46a1-83c2-e77dc089672c)

After:
![image](https://github.com/Questie/Questie/assets/1155017/9b263614-d0b9-41a4-bb67-6c3732ccf5b7)

Questie 9.2.12 wotlk

**Comment by Cabro** [comment]
This is a new bug.

**Comment by MyTechnoHunter** [comment]
Revert to pre completion sound fix and see if working

**Comment by BreakBB** [comment]
Other objectives are redrawn?

I also think this could be connected to the completion sound fix.

**Comment by Cabro** [comment]
> Other objectives are redrawn?
Negative on that

**Comment by BreakBB** [comment]
Can you test to revert this commit and see if that helps?

https://github.com/Questie/Questie/commit/382a73f289403f4103b41bd9381c54ba99ef3c02

**Comment by Cabro** [comment]
100% that's the root of the bug. The icons are redrawn without that commit

**Comment by BreakBB** [comment]
Can you also test by only re-adding the `Objectives = {}` part in QuestieQuest?

**Comment by Cabro** [comment]
Works
