### ISSUE TITLE
Questie Error - boosted quests

### ISSUE THREAD

**Issue by Frostvalk** [Questie/Questie#5395]
## Questie & WoW version
 WoW Classic 
Boosted Char from 5 -> 80
![WoWScrnShot_010124_132235](https://github.com/Questie/Questie/assets/155365832/69f9131e-a88e-4d61-a728-1b875db0187e)

**Comment by Cabro** [comment]
Boosted quests. I guess i'll add these after i'm done with ICC quests

**Comment by BreakBB** [comment]
Merging with #5195
