### ISSUE TITLE
Missing quest objective icons and Daily Icons on maps

### ISSUE THREAD

**Issue by pickynames** [Questie/Questie#5400]

**Comment by BreakBB** [comment]
Hey @pickynames did you check your settings? Also do I understand you correctly that the objectives are not drawn on the map?

**Comment by MrGamble2** [comment]
I've ran into the same issue starting yesterday. It works for a bit then randomly stops showing objectives on the map and only a questie reset makes it work until it stops working again. Even a relaunch doesnt fix the issue, and I make no setting changes after resetting so its not like I'm disabling anything.

**Comment by Cabro** [comment]
There is a fix incoming, next release soon™

**Comment by BreakBB** [comment]
Fixed in d269eb3cda22c5aea9c9493c13e988dac1ccd41d
