### ISSUE TITLE
The Corrupter

### ISSUE THREAD

**Issue by valkar221** [Questie/Questie#5408]
## Description
The quest The Corrupter has a minimum level of 26, but is showing on the map at level 25 (may have been updated for SoD).

## Wowhead link
https://www.wowhead.com/classic/quest=1488/the-corrupter

## Questie & WoW version
Questie v9.2.13, Client 1.15.0 SoD

Please also state if your quest issue is about Classic Era/SoM or Wotlk.
--> SoD

**Comment by BreakBB** [comment]
Yeah, you are right. This quest seems to have been updated for SoD to not being available.

[This version](https://web.archive.org/web/20210509102125/https://classic.wowhead.com/quest=1488/the-corrupter) of 2021 shows it's a level 25 quest.

**Comment by BreakBB** [comment]
Were you be able to do the pre quests @valkar221 ?

**Comment by valkar221** [comment]
Yes, just not the one linked.

**Comment by BreakBB** [comment]
Perfect. Thanks for the quick answer 👍🏻
