### ISSUE TITLE
[quest] Horde Druid Rune Quest Showing For Alliance Druids 

### ISSUE THREAD

**Issue by Sommos** [Questie/Questie#5421]
## Description

The SoD rune quest 'Lifebloom' (Tauren & Troll) is currently showing for Night Elf Druids when they will need to be hidden. 

## Wowhead link

https://www.wowhead.com/classic/item=206970/rune-of-life

https://www.wowhead.com/classic/npc=204827/adventurers-remains
https://www.wowhead.com/classic/npc=204937/adventurers-spirit

## Screenshots

![image](https://github.com/Questie/Questie/assets/28623479/e37b14ad-8cbe-43e3-8801-0edab04177e5)

![image](https://github.com/Questie/Questie/assets/28623479/cdc56295-8480-459f-acd1-72d1db7e7434)

## Questie & WoW version

v9.2.13
WoW Classic SoD - v1.15.052409

**Comment by BreakBB** [comment]
I don't think we should hide them. Technically Alliance players can get this rune in Mulgore as well as in Durotar as the NPC is always the same and friendly to both factions.

**Comment by Sommos** [comment]
After our discussion about showing all runes to players regardless of the likelyhood of a player going to an enemy faction zone for it, I agree that this can be kept as is and the issue resolved.
