### ISSUE TITLE
[quest] 'Sunfire' Druid Rune Fake Quest Missing From QuestDB

### ISSUE THREAD

**Issue by Sommos** [Questie/Questie#5446]
## Description

The SoD Druid fake rune quest 'Sunfire' is not currently in the QuestDB. 

## Wowhead link

https://www.wowhead.com/classic/guide/season-of-discovery/druid-class-runes-discovery-location
https://www.wowhead.com/classic/spell=414684/sunfire
https://www.wowhead.com/classic/spell=416044/engrave-gloves-sunfire

## Screenshots

N/a

## Questie & WoW version

v9.2.14
WoW Classic SoD - v1.15.052409

**Comment by BreakBB** [comment]
Already added with 240dd00748bf2ea027aca555ff52b3901f3cbc00
