### ISSUE TITLE
[quest] 'Void Plague' Durotar Priest Rune Fake Quest Missing From QuestDB

### ISSUE THREAD

**Issue by Sommos** [Questie/Questie#5483]
## Description

The SoD Priest fake rune quest 'Void Plague' Durotar is not currently in the QuestDB. 

## Wowhead link

https://www.wowhead.com/classic/guide/season-of-discovery/priest-class-runes-discovery-location
https://www.wowhead.com/classic/spell=425216/engrave-chest-void-plague
https://www.wowhead.com/classic/npc=3128/kul-tiras-sailor
https://www.wowhead.com/classic/npc=3129/kul-tiras-marine

## Screenshots

N/a

## Questie & WoW version

v9.2.14
WoW Classic SoD - v1.15.052409

**Comment by BreakBB** [comment]
Fixed in #5484
