### ISSUE TITLE
[quest] 'Serendipity' Priest Rune Quest Missing From QuestDB

### ISSUE THREAD

**Issue by Sommos** [Questie/Questie#5489]
## Description

The SoD Priest rune quest 'Serendipity' is not currently in the QuestDB. 

## Wowhead link

https://www.wowhead.com/classic/guide/season-of-discovery/priest-class-runes-discovery-location
https://www.wowhead.com/classic/spell=415995/engrave-chest-serendipity
https://www.wowhead.com/classic/npc=211653/grizzby

## Screenshots

N/a

## Questie & WoW version

v9.2.14
WoW Classic SoD - v1.15.052409

**Comment by BreakBB** [comment]
Was added in 4f29f88d0a78d00a6d4a7b5d30219cff2ee8f0d7
