### ISSUE TITLE
Tooltips of child quests are not removed

### ISSUE THREAD

**Issue by BreakBB** [Questie/Questie#5515]
## Bug description

I just did the quest [Return to Onu](https://www.wowhead.com/classic/quest=950/return-to-onu) and handed it in. Afterwards both of the "Onu is meditating" quests still show in the tooltip of Onu. A `/reload` removed them properly.

## Questie & WoW version

v9.2.16

**Comment by BreakBB** [comment]
I just did this quest a second time and the tooltips were removed properly.

**Comment by Sommos** [comment]
Just did this on SoD and was unable to replicate it.

**Comment by BreakBB** [comment]
I'll close this then, as "hick up", which shouldn't happen really rarely.
