### ISSUE TITLE
progress not showing

### ISSUE THREAD

**Issue by seppelinchen** [Questie/Questie#5620]
hi questie team,
is it possible that the quest progress is not shown, when people in group are on different servers?
this screenshot is me (everlook) and a friend (lakeshire)
![image](https://github.com/Questie/Questie/assets/96299043/325697c6-251e-4db0-ade3-691b585baeec)

this screenshot is me and same friend with char on everlook
![image](https://github.com/Questie/Questie/assets/96299043/6276a12c-f343-432f-bed3-52e9f595d6db)

everything else like quest accepted, quest finished aso, is shown
thanks and keep on with this great addon :)

**Comment by BreakBB** [comment]
Hey @seppelinchen which game version are you playing?
It is totally possible that this case isn't working yet and need investigation.

**Comment by seppelinchen** [comment]
hi breakBB,
sorry, forgot to say that ;)
it's wow classic

**Comment by BreakBB** [comment]
@seppelinchen but it is "WotLK" or "Era" or "HC" or "Season of Discovery"? 😅

**Comment by seppelinchen** [comment]
it's era

**Comment by seppelinchen** [comment]
hi BreakBB,
first of all, sorry for the bad problem report. i should know better ;)
to sum it up:
both of us, me Herhighness-Everlook and friend Sonja-Lakeshire, use the latest update of Questie and play the latest update of WoW Classic-Era.
the issue should be clear from the screenshots. what might be helpful: everything Sonja-Lakeshire picks up from wherever (flowers, boxes, corpses aso) is shown in the chat. questie messages about quests are shown too, except progress messages.
thanks for any help here :)

**Comment by BreakBB** [comment]
Hey @seppelinchen not a problem at all, your initial report was fine!

I honestly didn't know cross server play (outside of WotLK RDF) is possible in Classic 😅 That's why I was asking for more information.

Are you seeing your friends progress in the tooltips on the mobs/objects?

**Comment by seppelinchen** [comment]
no. i don't see more as what i described in my latest comment. and friend sonja doesn't see my progress ;)

**Comment by BreakBB** [comment]
Alright thanks @seppelinchen that gives us enough information to look into the issue 👍🏻

**Comment by seppelinchen** [comment]
sound's good ;)

**Comment by seppelinchen** [comment]
hi breakBB,
it looks like the events are not fired cross realm :(
i wrote a litte eventhandler and events of my friend are not fired :(
![image](https://github.com/Questie/Questie/assets/96299043/c03e2ef4-82af-4498-bcba-4e2994eb23be)

this is my litle handler:

local frame, events = CreateFrame("Frame"), {};
function events:QUEST_LOG_UPDATE(...)
 print("log update ");
end
function events:QUEST_ITEM_UPDATE(...)
 print("item update ");
end
frame:SetScript("OnEvent", function(self, event, ...)
 events[event](self, ...); -- call one of the functions above
end);
for k, v in pairs(events) do
 frame:RegisterEvent(k); -- Register all events for which handlers have been defined
end

so it's a issue to be handled by blizzard. but do they care?
 have a nice WE...

**Comment by seppelinchen** [comment]
hi breakBB,
did you had already the time to have a look at this issue?
if my findings and guessings are correct, it probably will take a while. if it's fixable at all ;)
thanks for a short info and have a nice day :)

**Comment by BreakBB** [comment]
Hey @seppelinchen no time yet, sorry. With SoD phase 2 just released, we're focussing on that atm.

**Comment by BreakBB** [comment]
Fixed in 64d73fc12893bf22d022917b20b82b4370da251e

Sorry @seppelinchen for taking sooooo long to fix this 🙈
