### ISSUE TITLE
Ratchet Wanted poster showing wrong tooltip

### ISSUE THREAD

**Issue by Pyrois81** [Questie/Questie#5623]
## Description

Hovering over the Wanted poster in Ratchet shows "WANTED: Syndicate Personnel" (quest ID 549) in the tooltip instead of the correct "WANTED: Baron Longshore" (ID 895).

## Wowhead link

https://www.wowhead.com/classic/quest=549/wanted-syndicate-personnel
https://www.wowhead.com/classic/quest=895/wanted-baron-longshore

## Screenshots

![wanted](https://github.com/Questie/Questie/assets/93115559/efa3ec4b-2bae-4dea-ba60-c2e007c899b2)

## Questie & WoW version

Questie v9.3.0, WoW SoD 1.15.0.52610

**Comment by BreakBB** [comment]
Realted to #5163
