### ISSUE TITLE
[quest] P2 SoD Gnomeregan Quests Missing From QuestDB

### ISSUE THREAD

**Issue by Sommos** [Questie/Questie#5663]
## Description

The P2 SoD quests for Gnomeregan are not currently in the QuestDB. 

## Questie Debug Reports

Quest in dialog not present in QuestDB!

Quest ID: 80137
Quest Name: Save Techbot's Brain!
Quest Text: When our beloved city Gnomeregan fell, a rogue spark must have jolted my poor creation, Techbot.  It once aided me and my associates with its countless gizmos and limitless store of information, but its positronic brain has polarized.  Now it's negatronic... and Techbot's behaviors are reversed.  It roams Gnomeregan in a frenzy!

But perhaps it can be salvaged.  Perhaps, if you can retrieve Techbot's memory core and bring it to me, I can discover the cause of the polarization and fix my poor Techbot.

Objective Text: Bring Techbot's Memory Core to Tinkmaster Overspark in Ironforge.
Reward Text: 
Reward XP: 0
Questgiver: Creature-0-5253-0-20340-7944-0000467E8E
Character: Lvl 40 HUMAN WARRIOR
Player Coords:  [1455]  (69.959, 50.147)
QuestLog: 1053, 1701, 4581, 1791, 7905, 
Client: 1.15.1 SoD
Questie: v9.3.6
Locale: enUS

Quest in dialog not present in QuestDB!

Quest ID: 80180
Quest Name: The Grand Betrayal
Quest Text: I trusted Thermaplugg, human. Never did I expect that he would betray me and the entire gnomish people. And for what? Power? Wealth? All things that he would have had in time. Now we have been displaced from our home and that madman is in charge. The king of nothing....

We will retake Gnomeregan, <playername>. We will not stop until the city is back in our control. If you wish to join in our fight, a simple task I ask of you: Kill the betrayer. Destroy Mekgineer Thermaplugg.
Objective Text: Venture to Gnomeregan and kill Mekgineer Thermaplugg. Return to High Tinker Mekkatorque when the task is complete.
Reward Text: 
Reward XP: 0
Questgiver: Creature-0-5253-0-20340-7937-0000467E8E
Character: Lvl 40 HUMAN WARRIOR
Player Coords:  [1455]  (69.090, 49.055)
QuestLog: 1053, 1701, 4581, 1791, 80137, 7905, 
Client: 1.15.1 SoD
Questie: v9.3.6
Locale: enUS

Quest in dialog not present in QuestDB!

Quest ID: 80143
Quest Name: Data Rescue
Quest Text: When we fled Gnomeregan, we left so much data behind!  Vitally important data!

I need the data on a prismatic punch card, from a Matrix Punchograph 3005-D high security terminal, deep in Gnomeregan.  You must access the terminal, but to do that you first need clearance... and to get that you must access lower security terminals-- models -A, -B and -C.  And to do THAT you need security punch cards, starting with white... and we left all the punch cards in the city.

It's a catastrophe!  Can you help?
Objective Text: Bring a Prismatic Punch Card to Master Mechanic Castpipe in Ironforge.
Reward Text: 
Reward XP: 0
Questgiver: Creature-0-5253-0-20340-7950-0000467E8E
Character: Lvl 40 HUMAN WARRIOR
Player Coords:  [1455]  (69.727, 48.626)
QuestLog: 4581, 80137, 1701, 1053, 1791, 80180, 7905, 
Client: 1.15.1 SoD
Questie: v9.3.6
Locale: enUS

Quest in dialog not present in QuestDB!

Quest ID: 80136
Quest Name: Essential Artificials
Quest Text: A nigh-universal mechanical component--the essential artificial--was of great use to the tinkers and smiths of Gnomeregan.  But during the frantic exodus from our city, no one remembered to take any of these devices with them!  And I need a large supply of them for work I will soon undertake.

Please, go into Gnomeregan and get me some essential artificials.  You'll find them in the deeper areas of our city, held in containers called artificial extrapolators.

Thank you, <playername>, and please hurry!
Objective Text: Bring 12 Essential Artificials to Klockmort Spannerspan in Ironforge.
Reward Text: 
Reward XP: 0
Questgiver: Creature-0-5253-0-20340-6169-0000467E8E
Character: Lvl 40 HUMAN WARRIOR
Player Coords:  [1455]  (68.552, 46.000)
QuestLog: 4581, 80137, 1701, 1053, 1791, 80180, 80143, 7905, 
Client: 1.15.1 SoD
Questie: v9.3.6
Locale: enUS

## Screenshots

N/a

## Questie & WoW version

v9.3.6
WoW Classic SoD - v1.15.1.53247

**Comment by BreakBB** [comment]
There are far more https://www.wowhead.com/classic/quests/dungeons/gnomeregan?filter=8;2;11501

We should also make sure to only add them with proper `objectives`
