### ISSUE TITLE
GetQuest: The quest doesn't exist in GetQuestLogCache. 4987

### ISSUE THREAD

**Issue by jmurchr** [Questie/Questie#5680]
Questie asked me to report an error, so here I am. I'm such a good boy.

![image](https://github.com/Questie/Questie/assets/49569785/266f4a60-0098-4452-afee-6e4ca38d02ef)

Running Questie v9.4.0. on classic wotlk.

Hope the helps.

**Comment by BreakBB** [comment]
Thanks @jmurchr

This is a known problem, which only happens occasionally. It's on our list 👍🏻
