### ISSUE TITLE
Questie not working at all after disabling tracker (SOD)

### ISSUE THREAD

**Issue by Jaxrs** [Questie/Questie#5684]
## Bug description
Last night in Gnomer I disabled the Questie tracker so I could track some of the Gnomer quests. After re-enabling it, not only is it still using the default Blizzard tracker, but no quests or any other questie functionality is working. I've tried uninstalling/resintalling as well as deleting my cache and savedvariables in conjunction. 

Upon logging in, I do see the questie DB messages, that seem to succeed, but nothing ever shows on the world map.

## Screenshots
![WoWScrnShot_021324_123320](https://github.com/Questie/Questie/assets/35275062/ab428cc6-e269-40c8-be1d-081b0ee1527c)
![WoWScrnShot_021324_123328](https://github.com/Questie/Questie/assets/35275062/0e435a16-f277-49b3-8ad7-c7cab23b7d75)
![WoWScrnShot_021324_123339](https://github.com/Questie/Questie/assets/35275062/2b4fc092-1176-42c2-9844-0b874b81edc6)

## Questie & WoW version
9.4.0

Please also state if your quest issue is about Classic Era/SoM or Wotlk.
SOD

**Comment by MyTechnoHunter** [comment]
Quest quadrangulation borks it.. workaround in progress

**Comment by Jaxrs** [comment]
> Quest quadrangulation borks it.. workaround in progress

ok cool. good to know! thanks

**Comment by BreakBB** [comment]
These two commits are related (and most likely a fix for this)

dbd8c16089182a6901fa2e5bb319eafbf6fdb1ba
a9e6dd2399bc15e7d96827f0fcc384a0940d0a8d

**Comment by BreakBB** [comment]
Are you still on that quest @Jaxrs ?

**Comment by BreakBB** [comment]
Confirmed to be fixed with the two commits mentioned and release in v9.4.1
