### ISSUE TITLE
Wrong hunter rune indication

### ISSUE THREAD

**Issue by Pixelatex** [Questie/Questie#5688]
## Description
Questie marks "lurkmane" in muglore as the npc to kill to get the rune for explosive shot, this is incorrect.

## Wowhead link
https://www.wowhead.com/classic/npc=207515/lurkmane

## Screenshots

<img width="510" alt="Screenshot 2024-02-14 at 20 42 29" src="https://github.com/Questie/Questie/assets/12593377/d480c4f8-f6d4-4ab7-9273-0afd728fc26e">

## Questie & WoW version
Classic version SOD
Questie v9.4.1
Wow classic v1.15.1.53247

**Comment by Sommos** [comment]
Thanks for catching this! There is now a PR up to rectify this issue.
