### ISSUE TITLE
 Quadrangulation tracking mismatch

### ISSUE THREAD

**Issue by Sognus** [Questie/Questie#5719]
## Bug description

For SoD quest Quadrangulation, all the markers on minimap are wrongly tracker. It seems that it can be random for everyone, in that case wouldnt it be better to show all markers until quest is done.  

## Screenshots

No screen

## Questie & WoW version
WoW: 1.15.1 SoD
Questie: 9.4.4 (latest available on Curse platform)
Side: Horde

**Comment by BreakBB** [comment]
Fixed in 5ebccb266de6489a023e3f36d06c21004390b61a
