### ISSUE TITLE
WoW Classic: Quest icon visble in unexplored area, even though setting to hide icons in unexplored areas is set.

### ISSUE THREAD

**Issue by Luke1410** [Questie/Questie#5726]
## Bug description
Steps to reproduce:
1. Enable the setting to hide quest icons in unexplored areas in Questie.
2. Open the map for the Stonetalon Mountain area.
3. Meet the prerequisite for the quests offered in Sunrock Retreat.

Actual result:
Even though the area around Sunrock Retreat, there's a part of the yellow exclamation icon slightly visible south of the hidden Sunrock Retreat area and mousing over that icon, shows the tooltip for the available quests there (see screenshot below).

Expected behavior:
The quest icon is not visible, since the area has not yet been revealed.

## Screenshots
![image](https://github.com/Questie/Questie/assets/15809174/fe79f705-ccae-495c-ab59-dd58041cd99e)
![image](https://github.com/Questie/Questie/assets/15809174/10be1d24-22be-4a57-a288-ba0b23c9bae0)

## Questie & WoW version
Questie 9.4.5, WoW Classic (Hardcore): Version 1.15.1 (build from 2024-02-23)

**Comment by MyTechnoHunter** [comment]
You dure? Looks like the red square was them pointing out where the bottom of the icon is?

**Comment by BreakBB** [comment]
Closing this in favor of #5786
