### ISSUE TITLE
Holiday dates wrong on Classic Era

### ISSUE THREAD

**Issue by SirJorb** [Questie/Questie#5737]
## Bug description
When running Classic Era, I'm getting a notification saying that the Lunar Festival is active, and showing Lunar Festival quests on the map. However, those NPCs are not currently present, as the Lunar Festival is not active currently in Classic Era.

From what I've been able to tell from Wowhead guides, it's possible that [Classic Era](https://www.wowhead.com/classic/guide/lunar-festival-wow-classic) and [Wrath Classic](https://www.wowhead.com/wotlk/guide/lunar-festival-event-holiday) have different holiday dates (with Wrath's still ongoing, and Classic Era's having ended), and Questie is pulling from the wrong one.

## Screenshots
![image](https://github.com/Questie/Questie/assets/23423782/f0112cbd-ce39-4001-a332-5b6d86f5469c)
![image](https://github.com/Questie/Questie/assets/23423782/2a1bc21b-157c-4d58-87b3-ef5a53a93e0e)

## Questie & WoW version
v9.4.5
Classic Era

**Comment by MyTechnoHunter** [comment]
Sorta, in reality, its us guessing.. every client _but_ era has a calendar api with info from the servr...  era has the api.. but no server event info so we guess.. 

 We will include turning off this event in the next hotfix!

**Comment by BreakBB** [comment]
Fixed in 26b35ab9999c0ca3c1efb4cb7dfdbf3b61381b79
