### ISSUE TITLE
Hilary's Necklace

### ISSUE THREAD

**Issue by QuadrozZz** [Questie/Questie#5751]
https://www.wowhead.com/classic/quest=3741/hilarys-necklace
Questie say this quest available for horde, but shouldn't. This quest are only for Alliance.
![screen](https://github.com/Questie/Questie/assets/18114545/be2fa257-b56b-4f7e-ac32-be5fececc575)

**Comment by BreakBB** [comment]
This Quest can be completed as Horde player as well.

References:
#840
#1057
#1254
#1934
