### ISSUE TITLE
Code incorrect to display runes as quests.

### ISSUE THREAD

**Issue by builtlikebuu** [Questie/Questie#5774]
SoD, issue with correction of code showing the rune locations 

the code is as written

---@param questId number
---@return boolean
function QuestieDB.IsSoDRuneQuest(questId)
    return runeQuestsInSoD[questId] ~= nil
end

---@param questId number
---@return boolean Returns true if the quest should be hidden, false otherwise
function QuestieDB.IsRuneAndShouldBeHidden(questId)
    if (not QuestieDB.IsSoDRuneQuest(questId)) then
        return false
    end

    if (not Questie.db.profile.showSoDRunes) then
        return true
    end

    local showPhase1Runes = Questie.db.profile.showRunesOfPhase["phase1"]
    local showPhase2Runes = Questie.db.profile.showRunesOfPhase["phase2"]

    local phaseOfRuneQuest = runeQuestsInSoD[questId]

    if (phaseOfRuneQuest == 1) then
        return (not showPhase1Runes)
    elseif (phaseOfRuneQuest == 2) then
        return (not showPhase2Runes)
    end

    return false
end

in order for this to correctly work, the code needs to be change to remove the "not" in front of the showpahse1runes and showphase2runes spot respectfully.

**Comment by BreakBB** [comment]
Hey @builtlikebuu without looking at the code: Can you explain what wrong behavior you noticed?

**Comment by MyTechnoHunter** [comment]
Logic flow
Options say user wants to see phase1
Is quest phase1? Check if should show (user options/current phase)
Yes, user show, return not showphase1 ( don't hide)
No, user hide, return not showphase1 ( not not =true, hide)

Make sense?

**Comment by builtlikebuu** [comment]
> Hey @builtlikebuu without looking at the code: Can you explain what wrong behavior you noticed?

Hey @BreakBB basically in game once the update had completed all other questie functions were working but the runes being displayed on the map, were not being able to be seen so locations of runes, how to start their quests were all hidden and unknown basically it just did not show anything to do with SoD runes.

**Comment by MyTechnoHunter** [comment]
> > Hey @builtlikebuu without looking at the code: Can you explain what wrong behavior you noticed?
> 
> Hey @BreakBB basically in game once the update had completed all other questie functions were working but the runes being displayed on the map, were not being able to be seen so locations of runes, how to start their quests were all hidden and unknown basically it just did not show anything to do with SoD runes.

It should have had a pop-up asking if you wanted to view the runes, we show em a phase behind so phase 1 would be visible. 
If you missed the pop-up,  open options and look on the icons tab? I think.. 
Once enabled,  they should show on your map

**Comment by BreakBB** [comment]
@builtlikebuu it was expected to NOT see the phase 2 related runes after the update. You need to enable them in the settings. And for everything phase 1 related, it would only show them, if you had shown them before the update.

Check your settings `/questie` -> Icons -> lookout for the "Season of Discovery Runes", "Phase 1" and "Phase 2" checkboxes.

**Comment by BreakBB** [comment]
I am closing this, as I think there was a misunderstanding of what the code looks like vs. what it actually does.
