### ISSUE TITLE
ERROR during initialization - bad argument #1 to "bitband"

### ISSUE THREAD

**Issue by hafel89** [Questie/Questie#5783]
## Bug description

When logging into a character i get an error on the questie initialization. On every charackter regardless of the class or race. After that questie just does not work.

## Screenshots
![image](https://github.com/Questie/Questie/assets/163297420/e7120035-5168-4a0e-8c38-42d363d8ad8f)

## Questie & WoW version
WoW: SoD
Questie Version: v9.4.9

Re-installing questie or deleting WTF/Cache Folder did not help

**Comment by BreakBB** [comment]
Hey @hafel89 please try the following:

`/run Questie.db.global.sod.dbIsCompiled = false;ReloadUI()`

That should reload your UI and re-compile the database.

**Comment by hafel89** [comment]
> Hey @hafel89 please try the following:
> 
> `/run Questie.db.global.sod.dbIsCompiled = false;ReloadUI()`
> 
> That should reload your UI and re-compile the database.

That fixed the problem! Thank you very much :)
