### ISSUE TITLE
Waypoint lines visible in unexplored areas for completed quests with hideUnexploredMapIcons

### ISSUE THREAD

**Issue by Luke1410** [Questie/Questie#5786]
## Bug description
When you have a quest completed which leads to an NPC in an not yet discovered area of the map and that NPC is presented with a waypoint line, the line is visible even if you have the setting 'hideUnexploredMapIcons' enabled.

To me this seems like a bug/unintended behavior, because normal quest icons to NPCs for completed quests are hidden, if that setting is enabled.

An example for this case is with quest 414: https://www.wowhead.com/classic/quest=414/stout-to-kadrell where you have to hand in the item to the NPC (Kadrell) in Loch Modan. As shown on the screenshot, the waypoint of the NPC is visible (note: there's a second line for yet another quest presumably the same issue on the right side).

## Screenshots
![image](https://github.com/Questie/Questie/assets/15809174/ac265fd3-2a50-4833-92f3-0474920b77ea)

## Questie & WoW version
Classic WOW (Hardcore): 1.15.1 (2024-03-14) / Questie: 9.4.9

**Comment by BreakBB** [comment]
Argh, another waypoint lines issue 🙈 Thanks for reporting this
