### ISSUE TITLE
Questie makes my loading screen lag because it spends a lot of time compiling localizations

### ISSUE THREAD

**Issue by emmericp** [Questie/Questie#5801]
I tried to track down why my login/reload loading screen feels slow, here is a flame graph of CPU time used by addons: https://emmericp.github.io/Perfy/perfy-cpu-loadingscreen.svg (created using https://github.com/emmericp/Perfy)

Questie is an interesting case here because the reason why it's slow is somewhat unique: most of the time is spent *loading and compiling* localization files. Sure, almost all of the files execute as just immediately returning, but by the time they execute the time spent on compiling them is already lost.

I wonder if it would be worthwhile to put the translations into a huge string similar to how the database files are handled to avoid this problem?

**Comment by BreakBB** [comment]
Hey @emmericp 

That is an interesting tool you built 👏🏻 

To be honest: We don't have much time atm to look into big performance improvements, as Cataclysm is around the corner and there is much to do for us 😅 

In the long run, it is totally worth it to investigate this further, as the load time of Questie can definitely be improved!

We were also thinking about moving the language code into sub-addons, so they can be loaded entirely on demand. But loading them from a big string, might be a good first step.

You are absolutely welcome to dig into this, if you want to.

**Comment by emmericp** [comment]
awesome, thank you!

**Comment by BreakBB** [comment]
Feel free to dig into this again @emmericp - Your initial review was very helpful 🙏🏻
