### ISSUE TITLE
WOW SOD bug

### ISSUE THREAD

**Issue by Velarax** [Questie/Questie#5832]
## Bug description

Despite selecting show all quests, any quest lower than my toon does not display an (!) over the quest giving NPC's head.

Formerly this selection turned on yellow (!) even for grey quests.  Now, even green quests below my level do not show up.

**Comment by BreakBB** [comment]
Hey @Velarax 

Neither Questie nor any other addon can place these `!` above NPCs. This is the default behaviour of the game, sorry 🤷🏻

**Comment by Cabro** [comment]
Just track low level quests:
![image](https://github.com/Questie/Questie/assets/1155017/dd230b82-e8e1-4913-a1cd-57cebd3abda7)

**Comment by Velarax** [comment]
LOL.  If that solved my problem I wouldn't have posted it.  Apparently, Questie is not responsible for whether the (!) shows on NPCs regardless of how tracking is set.

**Comment by Cabro** [comment]
It is literally the blizzard tracking that enables the question marks on low level quests on NPCs.
