### ISSUE TITLE
SOD (Misplaced / Barrens / Pro-Required)

### ISSUE THREAD

**Issue by Arccai** [Questie/Questie#5871]
**Misplaced in the Journey**
────────────────
_Zone_
**The Barrens**

**Inaccurate**
• Placed in **Available** Section

**Requires one of the following**
Tailoring, Leatherworking, Blacksmith
_(With a minimum level of 100)_

[**(78909)** Shifting Scale Talisman](https://www.wowhead.com/classic/quest=78909/shifting-scale-talisman)

**Accurate**
• Place in **Unobtainable** Section

_Should not be placed in profession.
Better sticking to Barrens as Unobtainable untill it meets the requirements,
just like any reputation-required quest._

**Comment by BreakBB** [comment]
Closing this in favor of #5397 - We need a database change to handle quests which require one out of multiple possible professions.
