### ISSUE TITLE
quest log tracker is in the middle of my screen

### ISSUE THREAD

**Issue by gunthenator** [Questie/Questie#5890]

**Comment by gunthenator** [comment]
my quest log tracker is in the middle of my screen it is very very annoying and I do not know how to move it.

**Comment by MyTechnoHunter** [comment]
Hover the header with your mouse,  it will tell how to drag and drop it, to resize it there is a corner anchor with its own tooltip and instructions 

Good luck

**Comment by BreakBB** [comment]
Were you able to fix this @gunthenator ?

**Comment by BreakBB** [comment]
Assuming this is fixed.
