### ISSUE TITLE
SOD (Misplaced / Gnomeregan / Not Shown)

### ISSUE THREAD

**Issue by Arccai** [Questie/Questie#5896]
**Misplaced in the Journey**
────────────────
_Zone_
**Gnomeregan**

**Inaccurate**
• Currently isn't shown anywhere

[**(81974)** More Junk for Ziri](https://www.wowhead.com/classic/quest=81974/more-junk-for-ziri)

**Accurate**
• Place in **Gnomeregan** Section

**Comment by BreakBB** [comment]
There are way more quests with ID `819XX` which don't have any `zoneOrSort` field applied.
