### ISSUE TITLE
Blizzard's quest tracker gets hidden by Questie on Cata Classic

### ISSUE THREAD

**Issue by Ropid** [Questie/Questie#5900]
## Bug description
On the Cata Classic client, Blizzard's quest tracker gets hidden by Questie when Questie's own tracker is disabled.

The tracker feature in Questie is disabled. After doing a `/reload`, the Blizzard quest tracker shows up at first. After a few seconds, it gets hidden.

There are no script errors showing up in BugSack when this happens.

## Questie & WoW version
* Questie v10.0.3
* WoW Cata Classic client version from the login screen:
```
Version 4.4.0 (54525) (Release x64)
May 1 2024
```

**Comment by BreakBB** [comment]
Thanks for reporting this @Ropid I'll look into this right away.

**Comment by BreakBB** [comment]
Found the issue @Ropid the next release will contain the fix.
