### ISSUE TITLE
Database mismatch

### ISSUE THREAD

**Issue by jelmerj** [Questie/Questie#5901]
## Bug description
[15:43:16] Questie: [ERROR] Database mismatch! No entries found that match quest name. Please report this on Github or Discord!
[15:43:16] Questie: [ERROR] Questender is: Creature 35094
[15:43:16] Questie: [ERROR] Quest name is: Get Kraken!
[15:43:16] Questie: [ERROR] Client info is: 4.4.0; v10.0.3

[15:43:16] Questie: [ERROR] Database mismatch! No entries found that match quest name. Please report this on Github or Discord!
[15:43:16] Questie: [ERROR] Questender is: Creature 35094
[15:43:16] Questie: [ERROR] Quest name is: Identifying the Remains
[15:43:16] Questie: [ERROR] Client info is: 4.4.0; v10.0.3

Got these while handing in Argent Crusader dailies 

## Screenshots
![image](https://github.com/Questie/Questie/assets/1116119/b49c9e90-4433-4bb5-8a92-5f9a0c0429f8)

## Questie & WoW version
Questie 10.0.3
Wotlk / cata pre-patch

**Comment by Cabro** [comment]
![image](https://github.com/Questie/Questie/assets/1155017/4f98a390-58d1-4c75-8e64-31981ca4d22b)
How are you getting those errors?

**Comment by BreakBB** [comment]
Did you talk to https://www.wowhead.com/npc=35094/crusader-silverdawn @Cabro ?

**Comment by Cabro** [comment]
Yes, there were no errors on quest starting item receival, quest accept, quest abandon, retake quest starting item, reaccept quest, turn in quest.

**Comment by jelmerj** [comment]
Yes, pretty sure I got these errors as I was handing in the quests with Crusader Silverdawn

**Comment by BreakBB** [comment]
Also make sure you have this enabled @Cabro `Questie.db.profile.enableQuestFrameIcons`

**Comment by jelmerj** [comment]
This happened to me again today

![image](https://github.com/Questie/Questie/assets/1116119/84dec05b-15de-4784-b439-aa9df0aeb474)

I received the Kraken tooth while doing the "Get Kraken" quest, accepted the quest while still flying on the bird, then proceeded straight to the questgiver "Crusader Silverdawn" and the errors popped up as soon as i opened the dialog window.

**Comment by jelmerj** [comment]
![image](https://github.com/Questie/Questie/assets/1116119/bd4bdab4-a2f1-4548-969f-67c62a7e7979)

With debugging options enabled

**Comment by BreakBB** [comment]
Thanks @jelmerj these are simply data mismatches, so Questie will continue to work as expected. It's great you are reporting this!

**Comment by BreakBB** [comment]
Fixed in edb2a7cdd50b222ead67db4094465d67de749b13
