### ISSUE TITLE
Error about missing objective data in Timely Arrival (Darkshore, Cataclysm Classic)

### ISSUE THREAD

**Issue by renodr** [Questie/Questie#5903]
## Bug description

Hey folks! I'm working through Darkshore in Classic Cataclysm right now, and got an error from Questie about missing objective data for Escort Sentinel Aynasha to safety. The quest is called Timely Arrival, and has the ID of 13510. The bug can be reproduced by picking this quest up in Darkshore, at the far northern reaches of the map.

## Screenshots

(Screenshot of error)

![image](https://github.com/Questie/Questie/assets/11901488/82fed29c-2d21-434a-9805-e9823c5f8719)

(Quest description)

![image](https://github.com/Questie/Questie/assets/11901488/e9db3fc7-3d66-47e9-acea-78ae41fd5c01)

## Questie & WoW version

Questie Version: 10.0.3
WoW Version: 4.4.0.54525 (Cataclysm Classic)

Thank you for all that you do!

**Comment by BreakBB** [comment]
Fixed in 9ac25a259af94233c9b491a4c55449f121a8d743
