### ISSUE TITLE
Cataclysm Quest UI break: Northshire Valley quest Fear No Evil

### ISSUE THREAD

**Issue by calebsdaddy** [Questie/Questie#5904]
## Bug description
The `Fear No Evil` quest cannot be completed once accepted from `Brother Paxton` in Northshire Valley. Quest behavior:
- Upon accepting the quest, `Injured Stormwind Infantry` cannot be right clicked to be "revived".
- Reload of the user interface causes the quest dialogue to open and won't close upon accepting again.
- Abandon and reaccept the request repeats the pattern.

To resolve, I had to disable Questie and reload the UI again. This allowed me to finish the quest. I did not turn Questie back on until after I had handed the quest in.

Human Paladin, Level 3

Screenshots were not taken but this can be quickly and easily replicated.

## Questie & WoW version
Version: v10.0.3

**Comment by BreakBB** [comment]
Hey @calebsdaddy did you test if it helps to have only Questie active, no other addon?

We will look into this.

**Comment by BreakBB** [comment]
Hey @calebsdaddy sorry, but I can not reproduce this issue:

![image](https://github.com/Questie/Questie/assets/33514570/2487b633-2518-44d2-a9c3-2c0561622c01)

The quest is working just fine for me.

**Comment by calebsdaddy** [comment]
I only tested disabling Questie. Perhaps it's conflict with another addon. Thanks for checking!

**Comment by BreakBB** [comment]
No worries, thanks for reporting!

**Comment by JulianLutz84** [comment]
Commenting here over a year later to say I just experienced this exact same issue and got around it the exact same way. If I had to guess, yeah, it's some sort of conflict with another addon. Potentially ELVUI or Immersion.

**Comment by Cabro** [comment]
This is Blizzard spaghetti, you need to go out of the area so it changes the title on your screen and they suddenly become interactable.

**Comment by BreakBB** [comment]
> Potentially ELVUI or Immersion.

Hey @JulianLutz84 iirc I also had trouble doing that quest when using Immersion and auto questing from Questie. Overall this is indeed some weird Blizzard spaghetti, because addons should never be able to break default UI/interaction things 🙈
