### ISSUE TITLE
Error about missing objective data on The Last Refugee (Darkshore, Cataclysm Classic)

### ISSUE THREAD

**Issue by renodr** [Questie/Questie#5905]
## Bug description

Hey folks! I'm working through Darkshore in Classic Cataclysm right now, and got an error from Questie about missing objective data for "Archaeologist Hollee escorted to safety". The quest is called The Last Refugee, and has the ID of 13605. The bug can be reproduced by picking this quest up in Darkshore.

## Screenshots

(Screenshot of error)

![image](https://github.com/Questie/Questie/assets/11901488/4eb03acb-0a5d-40cf-bd72-39a0f36e2c4d)

(Quest description)

![image](https://github.com/Questie/Questie/assets/11901488/aa3185a8-7f34-4222-b15f-fa7be46d6f09)

## Questie & WoW version

Questie Version: 10.0.3
WoW Version: 4.4.0.54525 (Cataclysm Classic)

Thank you for all that you do!

**Comment by BreakBB** [comment]
Fixed in 9ac25a259af94233c9b491a4c55449f121a8d743
