### ISSUE TITLE
 Error about missing objective data in Call Down The Thunder (Darkshore, Cataclysm Classic)

### ISSUE THREAD

**Issue by renodr** [Questie/Questie#5906]
## Bug description

Hey folks! I'm working through Darkshore in Classic Cataclysm right now, and got an error from Questie about missing objective data for getting Aetherion's Essence. The quest is called Call Down the Thunder, and has the ID of 13558. The bug can be reproduced by picking this quest up in Darkshore.

## Screenshots

![image](https://github.com/Questie/Questie/assets/11901488/0d14c6f1-b0e9-4014-950e-ef3a71cd3547)

## Questie & WoW version

Questie Version: 10.0.3
WoW Version: 4.4.0.54525 (Cataclysm Classic)

Thank you for all that you do!

**Comment by BreakBB** [comment]
Fixed in 9ac25a259af94233c9b491a4c55449f121a8d743
