### ISSUE TITLE
alot of errors, i copyed everything for missing NPC names and tooltips.

### ISSUE THREAD

**Issue by Darxay** [Questie/Questie#5907]
**Questie: [ERROR] Missing objective data for quest  26907   Aggem Thorncurse**

**Questie: [ERROR] Missing objective data for quest  26907   Aggem Thorncurse**

**Questie: [ERROR] Name missing for NPC: 75001 - Please report this error on Discord or GitHub.**

**Questie: [ERROR] [QuestieQuest**]: [Tooltips] There was an error populating objectives for Agathelos the Raging 26907 0 No error
...erface/AddOns/Questie/Modules/Quest/QuestieQuest.lua:1180: bad argument #1 to 'next' (table expected, got nil)
[string "@Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua"]:63: in function <...erface/AddOns/Questie/Modules/Quest/QuestieQuest.lua:61>
[string "=[C]"]: in function `next'
[string "@Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua"]:1180: in function <...erface/AddOns/Questie/Modules/Quest/QuestieQuest.lua:1179>
[string "@Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua"]:1107: in function <...erface/AddOns/Questie/Modules/Quest/QuestieQuest.lua:1086>
[string "=[C]"]: in function `xpcall'
[string "@Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua"]:862: in function `UpdateObjectiveNotes'
[string "@Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua"]:578: in function `UpdateQuest'
[string "@Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua"]:1424: in function `PopulateObjectiveNotes'
[string "@Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua"]:704: in function `GetAllQuestIds'
[string "@Interface/AddOns/Questie/Modules/QuestieInit.lua"]:307: in function `?'
[string "@Interface/AddOns/Questie/Modules/QuestieInit.lua"]:389: in function <Interface/AddOns/Questie/Modules/QuestieInit.lua:387>

**Questie: [ERROR] Name missing for NPC: 74462 - Please report this error on Discord or GitHub.**

**Questie: [ERROR] [QuestieQuest**]: [Tooltips] There was an error populating objectives for Overlord Ramtusk 26907 0 No error
...erface/AddOns/Questie/Modules/Quest/QuestieQuest.lua:1180: bad argument #1 to 'next' (table expected, got nil)
[string "@Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua"]:63: in function <...erface/AddOns/Questie/Modules/Quest/QuestieQuest.lua:61>
[string "=[C]"]: in function `next'
[string "@Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua"]:1180: in function <...erface/AddOns/Questie/Modules/Quest/QuestieQuest.lua:1179>
[string "@Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua"]:1107: in function <...erface/AddOns/Questie/Modules/Quest/QuestieQuest.lua:1086>
[string "=[C]"]: in function `xpcall'
[string "@Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua"]:862: in function `UpdateObjectiveNotes'
[string "@Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua"]:578: in function `UpdateQuest'
[string "@Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua"]:1424: in function `PopulateObjectiveNotes'
[string "@Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua"]:704: in function `GetAllQuestIds'
[string "@Interface/AddOns/Questie/Modules/QuestieInit.lua"]:307: in function `?'
[string "@Interface/AddOns/Questie/Modules/QuestieInit.lua"]:389: in function <Interface/AddOns/Questie/Modules/QuestieInit.lua:387>

**Questie: [ERROR] Name missing for NPC: 74948 - Please report this error on Discord or GitHub.**

**Questie: [ERROR] [QuestieQuest**]: [Tooltips] There was an error populating objectives for Death Speaker Jargba 26907 0 No error
...erface/AddOns/Questie/Modules/Quest/QuestieQuest.lua:1180: bad argument #1 to 'next' (table expected, got nil)
[string "@Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua"]:63: in function <...erface/AddOns/Questie/Modules/Quest/QuestieQuest.lua:61>
[string "=[C]"]: in function `next'
[string "@Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua"]:1180: in function <...erface/AddOns/Questie/Modules/Quest/QuestieQuest.lua:1179>
[string "@Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua"]:1107: in function <...erface/AddOns/Questie/Modules/Quest/QuestieQuest.lua:1086>
[string "=[C]"]: in function `xpcall'
[string "@Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua"]:862: in function `UpdateObjectiveNotes'
[string "@Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua"]:578: in function `UpdateQuest'
[string "@Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua"]:1424: in function `PopulateObjectiveNotes'
[string "@Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua"]:704: in function `GetAllQuestIds'
[string "@Interface/AddOns/Questie/Modules/QuestieInit.lua"]:307: in function `?'
[string "@Interface/AddOns/Questie/Modules/QuestieInit.lua"]:389: in function <Interface/AddOns/Questie/Modules/QuestieInit.lua:387>

**Comment by BreakBB** [comment]
Fixed in 43887cae9824599db1df24d7dff2314c0b5ecd05
