### ISSUE TITLE
Bathed In Light/Finding Teronis Quest Database Mismatch (Ashenvale, Cataclysm Classic)

### ISSUE THREAD

**Issue by renodr** [Questie/Questie#5913]
## Bug description

Hey folks! While questing in Ashenvale and obtaining the quest from Orendil Broadleaf, I got an error.

## Screenshots

![image](https://github.com/Questie/Questie/assets/11901488/31b8108a-95c8-48fc-8193-dcaf5ef9cfbf)
![image](https://github.com/Questie/Questie/assets/11901488/2510ac22-55f0-4de9-bdd3-476986004e6b)

## Questie & WoW version

Questie 10.0.5
WoW 4.4.0

**Comment by BreakBB** [comment]
Fixed in edb2a7cdd50b222ead67db4094465d67de749b13
