### ISSUE TITLE
Error about missing objective data on A Trip to the Moonwell (Ashenvale, Cataclysm Classic) 

### ISSUE THREAD

**Issue by renodr** [Questie/Questie#5914]
## Bug description

Hey folks! I'm running into an error about missing objective data for quest 13919, which I believe is "A Trip to the Moonwell". It says

"Questie: [ERROR] Missing objective data for quest 13919 Tear Of Elune Cleansed."

## Screenshots

![image](https://github.com/Questie/Questie/assets/11901488/fc045f4e-c0d5-4504-ac31-8f5a5cef28c3)

![image](https://github.com/Questie/Questie/assets/11901488/39b0abe7-8ece-473d-92a3-094dc4171e9b)

## Questie & WoW version

Questie 10.0.5
WoW 4.4.0 (Cataclysm Classic)

**Comment by BreakBB** [comment]
Fixed in 0b792b36f27ac76781a08f9af5c16982705144e5
