### ISSUE TITLE
Error about missing objective data on True Power of the Rod (Ashenvale, Cataclysm Classic)

### ISSUE THREAD

**Issue by renodr** [Questie/Questie#5916]
## Bug description

Hey folks! While questing through Ashenvale, I'm getting an error about missing objective data for Quest 26482 (True Power of the Rod). The objective data should be "Furbolg uprising started."

## Screenshots

![image](https://github.com/Questie/Questie/assets/11901488/1a567d42-fcea-4787-a966-94addb529e99)

![image](https://github.com/Questie/Questie/assets/11901488/adab434b-c55f-4c40-bcfb-fe7fa8228ecf)

## Questie & WoW version

Questie 10.0.6
WoW 4.4.0 (Cataclysm Classic)

**Comment by BreakBB** [comment]
Fixed in dc620733b62b2499152936dc48279b502caea1c2
