### ISSUE TITLE
UI quest turn ins are not working. 

### ISSUE THREAD

**Issue by Cagomei** [Questie/Questie#5917]
## Bug description

The UI pop up to turn in certain quests is not currently working. 

## Questie & WoW version
 Classic Cata. I am using the most current version of the GIT HUB copy as of 11:14pm 5/5/24

**Comment by BreakBB** [comment]
Hey @Cagomei

> 11:14pm 5/5/24
Is not as specific as it seems, as it depends on the timezone you are in 😅 It would be helpful to know the actual version: `v10.0.5` or `v10.0.6`?

Can you tell on which quest(s) you encountered this? That will be helpful to reproduce the issue.

**Comment by Cagomei** [comment]
I do apologize. It is version 10.0.6.  it looks like the last PR was from Cabro black listing brewfest. A couple of the quests i experienced this on are the kill quests in northern stranglethorn vales for nessingwary camp. The tigers and the panther.

**Comment by BreakBB** [comment]
It would be great if you can double check the pop up is indeed not showing. Atm there is a potential issue with the positioning of it, so it might be off screen. It is attached to the Tracker, so if you move that a bit further away from the edge of your screen you might see it.

![image](https://github.com/Questie/Questie/assets/33514570/7aec1078-93bf-4168-80f0-7b82867d7877)

If you have this option to something else than what it is showing in the screen, then it might be off screen.

As these pop ups are something entirely new to the game (and therefore Questie), we might miss some edge cases as well, so thank you for reporting this.

**Comment by entroscopy** [comment]
> It would be great if you can double check the pop up is indeed not showing. Atm there is a potential issue with the positioning of it, so it might be off screen. It is attached to the Tracker, so if you move that a bit further away from the edge of your screen you might see it.

This was the issue for me. Until an update or so ago, the remote-complete popup appeared anchored to the left edge of the tracker. Now it appears anchored to the right side, and if your tracker is on the right side of the screen, the popup will be off-screen. Had to move the tracker way to the left for the popup to become visible.
![image](https://github.com/Questie/Questie/assets/30931739/37b89927-9ca1-4e24-b6e2-088f855ac0dc)

**Comment by BreakBB** [comment]
> most of the arborcide chain starting from "Runaway Shredder!" to "Defend the Gates!" showed the popup anchored to the right side of the tracker.

Thank you @entroscopy that is very helpful for us to test it. We are also already working on a fix for the location of that pop up. For now you should be good to set the setting in post above to "Down & Right" if your Tracker is on the right side of the screen and to "Down & Left" if the Tracker is on the left side of the screen.

**Comment by Cagomei** [comment]
![image](https://github.com/Questie/Questie/assets/55269647/9200782f-2e15-46e3-82a3-cfae834e5906)
That is in fact the case. It seems to be anchored to the right. Thank you for the quick responces
