### ISSUE TITLE
Name missing for NPC and Tooltips error when doing They Took Our Gnomes and The Goblin Braintrust (Ashenvale/Cataclysm Classic)

### ISSUE THREAD

**Issue by renodr** [Questie/Questie#5920]
## Bug description

Hey folks! I'm questing through Ashenvale some more and got the following errors when picking up "They Took Our Gnomes" and what I think is "The Goblin Braintrust":

[ERROR] Name missing for NPC: 130931 - Please report this error on Discord or Github.
[ERROR] [QuestieQuest]: [Tooltips] There was an error populating objectives for Boog and Minx Freed 13913 0 No error

## Screenshots

![image](https://github.com/Questie/Questie/assets/11901488/4b4fdbe5-97bd-4a1d-932d-94420137d501)

## Questie & WoW version

Questie 10.0.6
WoW 4.4.0 (Catacylsm Classic)

**Comment by renodr** [comment]
I killed Painmaster Thundrak and just got an error trace:

![image](https://github.com/Questie/Questie/assets/11901488/0f443b3f-c722-4553-a6cd-d394ff145c76)
![image](https://github.com/Questie/Questie/assets/11901488/df177d72-2722-45b6-b3e4-9e54fa697227)

The quest has been marked as "Quest Complete!" in the tracker though

**Comment by BreakBB** [comment]
Fixed in eb90310765013f8e09de9670987885d65b48e36e
