### ISSUE TITLE
Quests Showing on Map that are not Available

### ISSUE THREAD

**Issue by Eysiaa** [Questie/Questie#5921]
Description
I am experiencing a bug in which quests are showing on the map and mini map, but are not actually available to start or grab. When interacting with the NPC, it shows no "!" above their head or options in their dialogue. This is happening very often. In the screenshot attached, you can see the NPC does not actually have a quest available but the map says this specific NPC does (confirmed this by hovering over the quest icon on the map). In the screenshot, all other quests shown on the mini map are experiencing the same issue.

![Capture](https://github.com/Questie/Questie/assets/169109633/c4b1f611-9b09-4711-bc73-9a7b298ed617)

I am playing with Questie 10.0.06 for Classic Cata.

Thanks for taking the time to look into this!

**Comment by MyTechnoHunter** [comment]
This is a known (and being worked on) issue, the DB for cata has to be corrected/built just like any previous game version 

That being said,  if you like you can enable IDs in questie options advanced tab and report anything that you find wrong, details help!

Thanks for reporting

**Comment by BreakBB** [comment]
Merging this with #5990
