### ISSUE TITLE
Questie: [ERROR] Missing objective data for  quest

### ISSUE THREAD

**Issue by Gantrithor666** [Questie/Questie#5922]
Several inherited quests from WotLK in Silithus are returing Error after log in (see screenshot)

![image](https://github.com/Questie/Questie/assets/141342834/e97d2591-00f4-488f-b4cf-445c16c7f9ae)
![image](https://github.com/Questie/Questie/assets/141342834/890b781f-0ee4-4928-862d-7d2c9b9cb61f)

Questie v10.0.6
Cataclysm Classic 4.4.0

**Comment by BreakBB** [comment]
Ouh yeah, absolutely something we need to fix. Thanks @Gantrithor666 for letting us know.
