### ISSUE TITLE
Ruuzel quest is shown evem without prerequisite

### ISSUE THREAD

**Issue by Magikh42** [Questie/Questie#5938]
[Ruuzel](https://www.wowhead.com/quest=26466/ruuzel)
Prerequisite: [The Ancient Statuettes](https://www.wowhead.com/quest=26465/the-ancient-statuettes)
Tested on Cataclysm Classic
[Wowhead comment](https://www.wowhead.com/quest=26466/ruuzel#comments:id=1992504) mentionning the prerequisite

**Comment by BreakBB** [comment]
Fixed in 28c96c65ddcd8aeb6f7182f72c007f16828c3d73
