### ISSUE TITLE
[Missing objective] Of Their Own Design

### ISSUE THREAD

**Issue by Magikh42** [Questie/Questie#5939]
For [Of Their Own Design](https://www.wowhead.com/cata/quest=13595/of-their-own-design) the [Bottle of Wildfire](https://www.wowhead.com/cata/item=44967/bottle-of-wildfire) objective is not indicated
The bottle is located at 32;23 (sorry I don't have the location with more decimals) in Ashenvale

**Comment by BreakBB** [comment]
Fixed in 0b792b36f27ac76781a08f9af5c16982705144e5 and 58f0d371e2e44f697a53765834b8416f1563178d
