### ISSUE TITLE
[Missing objective] Bathed in Light

### ISSUE THREAD

**Issue by Magikh42** [Questie/Questie#5941]
[Bathed in Light](https://www.wowhead.com/cata/quest=13642/bathed-in-light)
Light of Elune is at 18 ; 41 according to [this comment](https://www.wowhead.com/cata/quest=13642/bathed-in-light#comments:id=1279564)

**Comment by BreakBB** [comment]
Fixed in 0b792b36f27ac76781a08f9af5c16982705144e5
