### ISSUE TITLE
[Missing Prerequisite] Astranaar Bound

### ISSUE THREAD

**Issue by Magikh42** [Questie/Questie#5942]
[Astranaar Bound](https://www.wowhead.com/cata/quest=13646/astranaar-bound)
[Warcraft Wiki](https://warcraft.wiki.gg/wiki/Astranaar_Bound)
I dont't know the prerequisite

**Comment by BreakBB** [comment]
Fixed in 9595469e2f8e5d94b79372832d2fbb7e292e13c9
