### ISSUE TITLE
[Missing Prerequisite] Too Far Gone

### ISSUE THREAD

**Issue by Magikh42** [Questie/Questie#5943]
[Too Far Gone](https://www.wowhead.com/cata/quest=13876/too-far-gone) requires [A Not-So-Charmed Life](https://www.wowhead.com/cata/quest=13874/a-not-so-charmed-life) but is shown even when teh prerequisite is not completed

**Comment by BreakBB** [comment]
Fixed in dc620733b62b2499152936dc48279b502caea1c2
