### ISSUE TITLE
Questie [ERROR] Database mismatch!

### ISSUE THREAD

**Issue by Gantrithor666** [Questie/Questie#5948]
Picking Swamp of Sorrow Quests returning Error
![image](https://github.com/Questie/Questie/assets/141342834/af24e662-8129-40b4-bd12-a2617e42b23d)

Questie v10.0.6
Cataclysm Classic 4.4.0

**Comment by Gantrithor666** [comment]
And also probably all the Quests from NPC https://wowpedia.fandom.com/wiki/Dispatch_Commander_Ruag return the same Error

![image](https://github.com/Questie/Questie/assets/141342834/b2b03329-1d03-4df0-9111-937eeecb58b7)

**Comment by BreakBB** [comment]
Fixed in edb2a7cdd50b222ead67db4094465d67de749b13
