### ISSUE TITLE
Disconnected from server 

### ISSUE THREAD

**Issue by Cheykan** [Questie/Questie#5949]
Questie causes server disconnects frequently in Cataclysm pre-patch. I use 10.0.7 from curseforge.. the reason why i "blame" questie is no disconnects after disabling it.

I hope it's sorted quick cause you guys spoiled me rotten with this addon.

**Comment by BreakBB** [comment]
Hey @Cheykan 

we just received a similar report to yours in #5947 - Check it out, maybe that is something helping you as well.

Feel free to share more information in that issue.
