### ISSUE TITLE
[ERROR] Quests in Whisperwind Grove

### ISSUE THREAD

**Issue by sideh** [Questie/Questie#5950]
## Description
When I went to start a quest after arriving in Whisperwind Grove every quest I accepted had the following errors and still show on the minimap as not accepted.

## Wowhead link
https://classic.wowhead.com/quest=28361
https://classic.wowhead.com/quest=28360
https://classic.wowhead.com/quest=28359
https://classic.wowhead.com/quest=28358
https://classic.wowhead.com/quest=28341
https://classic.wowhead.com/quest=28342

## Screenshots
![questie-error-1](https://github.com/Questie/Questie/assets/2169918/3b40d9cd-34a8-4243-8423-f3cf9fdfacff)
![questie-error-2](https://github.com/Questie/Questie/assets/2169918/4d6babab-72c2-452f-82ef-6bdb2e1e9796)
![questie-error-3](https://github.com/Questie/Questie/assets/2169918/d06181e5-2555-4607-9526-a0c01d991607)
![questie-error-4](https://github.com/Questie/Questie/assets/2169918/e5ceb1c9-e4b1-4b73-8ed9-6e01a3bd967d)

## Questie & WoW version
Version 10.0.7 - Cata
![image](https://github.com/Questie/Questie/assets/2169918/22111a04-a345-4f74-931f-2e5ef0ca4c7a)

**Comment by BreakBB** [comment]
Fixed in edb2a7cdd50b222ead67db4094465d67de749b13
