### ISSUE TITLE
Questie: [ERROR] Missing objective data for quest

### ISSUE THREAD

**Issue by Gantrithor666** [Questie/Questie#5957]
Quest: A Hello to Arms
Objective: Azsharite Core Delivered

![image](https://github.com/Questie/Questie/assets/141342834/d8ab2a15-2248-4823-86bd-3b0d95269bbb)

Questie v10.0.6
Cataclysm Classic 4.4.0

**Comment by BreakBB** [comment]
Fixed in 6d3e3ff8bbb878c41ecfd1e7dc772b9d87306c5a
