### ISSUE TITLE
SOD (Misplaced / Blackrock Depths/ Not Shown)

### ISSUE THREAD

**Issue by Arccai** [Questie/Questie#5959]
**Misplaced in the Journey**
────────────────
_Zone_
****

**Inaccurate**
• Currently isn't shown anywhere

[**(82062)** Ever After](https://www.wowhead.com/classic/quest=82062/ever-after)

**Accurate**
• Place in **Blackrock Depths** Section

**Comment by BreakBB** [comment]
There are also more quests starting without `zoneOrSort`:

https://github.com/Questie/Questie/blob/master/Database/Corrections/Automatic/sodBaseQuests.lua#L3880-L4000
