### ISSUE TITLE
Quest Mismatch Cata Classic Error, Quest - The Zevra and Hunting the Huntress

### ISSUE THREAD

**Issue by Aussiewoolf** [Questie/Questie#5960]
Quests ID 
https://www.wowhead.com/cata/quest=845/the-zhevra
https://www.wowhead.com/cata/quest=903/hunting-the-huntress

![WoWScrnShot_051024_101523 Questie Error](https://github.com/Questie/Questie/assets/33771952/4f3c879a-54ee-4bb1-b990-8d41aca9fb08)

**Comment by Sommos** [comment]
Fixed in: e94d5993c084f9f690598a9835aa49269499892c
