### ISSUE TITLE
Quest Mismatch Cata Classic Error, Quest-Deviate Hides and Preemptive Methods

### ISSUE THREAD

**Issue by Aussiewoolf** [Questie/Questie#5961]
Quests-
https://www.wowhead.com/cata/quest=26872/deviate-hides
https://www.wowhead.com/cata/quest=26873/preemptive-methods

![WoWScrnShot_051024_101523 Questie Error 002](https://github.com/Questie/Questie/assets/33771952/ab94f55e-af37-44cc-a5d0-f27147dae048)

**Comment by BreakBB** [comment]
Fixed in edb2a7cdd50b222ead67db4094465d67de749b13
