### ISSUE TITLE
Quest Mismatch Cata Classic Error, Quest- In Fungus we Trust

### ISSUE THREAD

**Issue by Aussiewoolf** [Questie/Questie#5962]
Quest- https://www.wowhead.com/cata/quest=13998/in-fungus-we-trust
![WoWScrnShot_051024_111752 003](https://github.com/Questie/Questie/assets/33771952/da95bba2-1619-4a97-a472-4e808e3e90fe)

**Comment by BreakBB** [comment]
Fixed in 3e5efadace9f2bade3bb8843d0925008e925ef1c - Thanks for reporting this @Aussiewoolf
