### ISSUE TITLE
Some quests are being auto accepted with option disabled

### ISSUE THREAD

**Issue by coneone** [Questie/Questie#5965]
## Bug description
Some quests are being auto accepted by questie.

- Auto accept option is disabled
- Questie was the only addon enabled.
- Tried in Spanish, Portuguese and English with the same results.

Example of quests that trigger the auto accept: 24475 All the Other Stuff, 24486 Make Hay While the Sun Shines (both are trivial quests).

**Important detail**: the quests are accepted when you click the specific quest, NOT when talking to the NPC as would with the auto accept option enabled.

## Screenshots
![imagen](https://github.com/Questie/Questie/assets/5948571/df6a2aa0-fb32-4132-94f2-013724b8e4f2)

## Questie & WoW version
Cataclysm Version 10.0.8.
Happened since prepatch in all 10.0.x versions.

**Comment by MyTechnoHunter** [comment]
If the quest that you mentioned are in starting zones it's most likely blizzard forcing an auto accept especially using the cataclysm game client

**Comment by coneone** [comment]
You're absolutely right. Sorry about this!
