### ISSUE TITLE
[ERROR] Fehlende Ziel-Daten für Quest 24723

### ISSUE THREAD

**Issue by Prideland** [Questie/Questie#5969]
Quest:  [Der Westpylon (24723)]

![grafik](https://github.com/Questie/Questie/assets/138702513/4b26739d-2586-41cb-8eba-b3e87c679ec4)

Questie v10.0.8
Cataclysm Classic 4.4.0

**Comment by coldpasta123** [comment]
@BreakBB my German sucks but I think this is fixed in https://github.com/Questie/Questie/commit/a831c933ad50fe52e252067cd7afa3b7b7969b6c :)
