### ISSUE TITLE
Auto quest accept issue

### ISSUE THREAD

**Issue by turtleturtle04** [Questie/Questie#5970]
Everytime I try to get a new quest and read it first, questie is just auto accepting it. I am in Cata classic when this happens. on one character I was able to just reset questie back to defaults and it fixed it, but now its not working. I don't exactly have a picture, but I don't have any of the auto quest accept turned on. I have tried toggling that setting on then off, and it still doesn't work. If I disable questie, It works normal, so I know it isn't one of my blizz settings

**Comment by MyTechnoHunter** [comment]
If this is in a starting zone, blame blizzard for this.. they force accept quest in there

That being said, can you test with no addons but questie enabled?

**Comment by Cabro** [comment]
He's going to have the same outcome. The starting zone quests have been force-autoaccept by blizzard since they first released Cata ptr.

**Comment by MyTechnoHunter** [comment]
> He's going to have the same outcome. The starting zone quests have been force-autoaccept by blizzard since they first released Cata ptr. If anything, try the same without ANY addons whatsoever. The Blizzard force-autoaccept happens as soon as you click the first time on the quest in the window.

Was more hoping to confirm the last part of the report, that it works normal with questie off..
