### ISSUE TITLE
Era quests showing on map in Cata Questie

### ISSUE THREAD

**Issue by Todbobsen** [Questie/Questie#5971]
Having an issue Cataclysm Questie showing all (or most) of the Era quests that have been removed in Cataclysm, causing me to travel to locations to pick up a quest that doesn't exist from an NPC that at times also doesn't exist. I am running the current version of Questie. I tried re-installing Questie, re-installing Cata Classic, deleting my Era Questie in case it was somehow interfering. If the issue if on my end somehow, please contact me at Todbobsen@gmail.com. If this is an issue others are also experiencing, I would guess it will be resolved soon enough, but if not I may need a little help finding a solution. 
![WoWScrnShot_051324_143146](https://github.com/Questie/Questie/assets/86893626/3b5258ed-083c-4fb5-a52a-0f4f2861bbbe)
![WoWScrnShot_051324_143211](https://github.com/Questie/Questie/assets/86893626/26bc4c9e-64f0-4206-a9de-6252eb5fd85a)

**Comment by BreakBB** [comment]
Hey @Todbobsen unfortunately this is not something we "just fix like that".

With all the changes to the world (and quests) brought by the Cataclysm, our database is not in a good state atm. Every quest needs manual attention to figure out when it should show and what to show.

What you can do to help us, is to report every single issue you encounter and provide as many details as possible.

For this report we will hide "Tools for Steelgrill" and "Rejold's New Brew", as both seem to have been removed with Cataclysm.

**Comment by coldpasta123** [comment]
@Cabro please close this
