### ISSUE TITLE
 Questie: [ERROR] Missing objective data for quest  25476   Escort OOX-22/FE to safety

### ISSUE THREAD

**Issue by snoutmate** [Questie/Questie#5975]
Questie: [ERROR] Missing objective data for quest  25476   Escort OOX-22/FE to safety

https://www.wowhead.com/cata/quest=25476/rescue-oox-22-fe

Classic Cataclysm
Questie v10.0.10

**Comment by renodr** [comment]
I can still confirm this on Questie 10.2.3 :)

**Comment by coldpasta123** [comment]
@BreakBB  fixed with https://github.com/coldpasta123/Questie/commit/6d760d5003e5957094a3c3b222b77f33513ab76b

**Comment by Cabro** [comment]
What was wrong with the existing correction?
