### ISSUE TITLE
Quest 11129 misleading objectives

### ISSUE THREAD

**Issue by SCG-Bones** [Questie/Questie#5978]
WoW Classic Cataclysm 4.4.0.54670
Questie v10.0.10 Release
https://www.wowhead.com/cata/quest=11129/kyles-gone-missing

Quest shows a wrong additional path where kyle could be roaming. He only roams around Bloodhoof Village.
Quest also keeps tracking 0 Tender Strider Meat even having the quest item in inventory, targetting Plainstriders indefinitely.

**Comment by Cabro** [comment]
Just went through this quest the other day. It had more spawns, only left one of them. I didnt see any issue with the roaming path? Questie only shows one path.
For the Tender Strider Meat, it is shown because it's not an objective, so it is treated as an extraobjective.

**Comment by coldpasta123** [comment]
@Cabro please close this
