### ISSUE TITLE
Questie Auto Accepting quests from npcs

### ISSUE THREAD

**Issue by Vallravn** [Questie/Questie#5979]

**Comment by MyTechnoHunter** [comment]
This is not question this is actually blizzard they have made it so that starting quests in most starting zones specifically for the new races as well are Auto accepted

**Comment by BreakBB** [comment]
Duplicate of #5965 and #5970

The next update will include a fix, so that the quest frame will no longer close. Accepting itself is, as TechnoHunter already said, done by Blizzard.
