### ISSUE TITLE
Questie: [ERROR] Missing objective data for quest  25379   Defeat Taerar

### ISSUE THREAD

**Issue by snoutmate** [Questie/Questie#5982]
Questie: [ERROR] Missing objective data for quest  25379   Defeat Taerar

Cataclysm Classic
Questie v10.0.10

**Comment by renodr** [comment]
I can confirm this on Questie 10.2.3 as well

**Comment by coldpasta123** [comment]
@BreakBB fixed with https://github.com/Questie/Questie/commit/bf89fac04bd20769270e2c7e6f608437005453b4
