### ISSUE TITLE
Typo disables a few things unintentionally?

### ISSUE THREAD

**Issue by KaltharUK** [Questie/Questie#5983]
https://github.com/Questie/Questie/blob/6c1f4f7049fa70a565a59b45780a28dba2f18505/Database/QuestieDB.lua#L1008

**Comment by MyTechnoHunter** [comment]
No, that line closes a comment 

The block above is pseudo (fake) code..
Can you give details of what you think is disabled that shouldn't be

**Comment by KaltharUK** [comment]
Ah, my bad.. I was browsing in GitHub and it seems to mark the following code for a fair few lines wrongly as disabled. Opened in editor and its fine.
Closing and my apologies :)

**Comment by BreakBB** [comment]
Don't worry @KaltharUK - very thoughtful of you :)
