### ISSUE TITLE
Missing Objective Data error for Quest 37239 "Survey Alcaz Island" (Cataclysm Classic/Dustwallow Marsh)

### ISSUE THREAD

**Issue by renodr** [Questie/Questie#5985]
## Description

Hey folks! I've got a Missing Objective Data error for Quest 37239, Survey Alcaz Island! The objective data should be "Survey Alcaz Island", I've attached screenshots of the error and of the quest info :)

## Wowhead link

https://www.wowhead.com/cata/quest=27239/survey-alcaz-island

## Screenshots

![image](https://github.com/Questie/Questie/assets/11901488/0574f182-e600-4376-9367-0d2363d971de)

![image](https://github.com/Questie/Questie/assets/11901488/30b0e88e-15f0-4906-a6ee-219e0ea89033)

## Questie & WoW version

Questie 10.0.10
WoW 4.4.0 (Cataclysm Classic)

**Comment by coldpasta123** [comment]
@BreakBB fixed with https://github.com/Questie/Questie/commit/6d760d5003e5957094a3c3b222b77f33513ab76b
