### ISSUE TITLE
Missing objective data for quest 27222, Take Down Tethyr! (Cataclysm Classic, Dustwallow Marsh)

### ISSUE THREAD

**Issue by renodr** [Questie/Questie#5986]
## Description

Hey folks! I'm getting a Missing Objective Data error for quest 27222, which is called Take Down Tethyr! It's in Dustwallow Marsh. The objective data is "Defend Theramore Docks from Tethyr"

## Wowhead link

https://www.wowhead.com/cata/quest=27222/take-down-tethyr

## Screenshots

![image](https://github.com/Questie/Questie/assets/11901488/76184564-115c-4931-9964-9f641ec6a915)

![image](https://github.com/Questie/Questie/assets/11901488/5b002292-b22a-4a6c-82b7-65aa0d85d08d)

## Questie & WoW version

Questie 10.0.10
WoW 4.4.0 (Cataclysm Classic)

**Comment by coldpasta123** [comment]
@BreakBB fixed with https://github.com/Questie/Questie/commit/6d760d5003e5957094a3c3b222b77f33513ab76b
