### ISSUE TITLE
Unnecessary quest marker - Shadow Priest Sarvis

### ISSUE THREAD

**Issue by eatthew** [Questie/Questie#5987]
Quest marker showing an unavailable quest.

![image](https://github.com/Questie/Questie/assets/65094360/970bfe9a-9989-4c2b-9c38-5dba4fb3bbda)

Questie v10.0.11
Game version 4.4.0.54737
Cataclysm

**Comment by eatthew** [comment]
Wrong label

**Comment by Cabro** [comment]
Fixed in https://github.com/Questie/Questie/commit/a648a55cd8fd855b119c4b4ca3ee40faa59b4242
