### ISSUE TITLE
Unnecessary quest marker - Caretaker Caice

### ISSUE THREAD

**Issue by eatthew** [Questie/Questie#5988]
Quest marker showing an unavailable quest.

![image](https://github.com/Questie/Questie/assets/65094360/7d7b6610-fc00-46db-85e2-62755d7edb2a)

Questie v10.0.11
Game version 4.4.0.54737
Cataclysm

**Comment by Cabro** [comment]
Fixed in https://github.com/Questie/Questie/commit/a648a55cd8fd855b119c4b4ca3ee40faa59b4242
