### ISSUE TITLE
Missing objective data for Quest 25798, Defend the Drill (Cataclysm Classic, Thousand Needles)

### ISSUE THREAD

**Issue by renodr** [Questie/Questie#5992]
## Description

Hey folks! I'm running through Thousand Needles right now in Cataclysm Classic and I got hit with:

"[ERROR] Missing objective data for quest 25798 Oil Drilling Rig defended"

The quest name is Defend the Drill.

## Wowhead link

https://www.wowhead.com/cata/quest=25798/defend-the-drill

## Screenshots

![image](https://github.com/Questie/Questie/assets/11901488/a78ce6c1-c604-40af-b6e5-f0b018e30b8f)

![image](https://github.com/Questie/Questie/assets/11901488/32a1c0ff-de96-48d0-909e-c3c61421b084)

## Questie & WoW version

Questie 10.0.11
WoW 4.4.0 (Cataclysm Classic)

**Comment by coldpasta123** [comment]
@BreakBB fixed with https://github.com/Questie/Questie/commit/05059fce7fd93ceb2b050e100e889f47290e639e
