### ISSUE TITLE
Grey !'s showing up for quests im the correct level for. also showing up for a quest ive already completed

### ISSUE THREAD

**Issue by TheYungDead** [Questie/Questie#5998]
classic cataclysm/questie 10.1.3
all the grey !'s say they're for the same quest of which ive already completed (captain sanders hidden treasure)
![Screenshot 2024-05-22 084645](https://github.com/Questie/Questie/assets/170511580/52bff7cb-18af-4aaa-a368-b128a3cbcdda)
showing unavailable quests as grey but are within my level (im lvl 24)
![Screenshot 2024-05-22 095308](https://github.com/Questie/Questie/assets/170511580/7a9bbecc-e096-4eff-b5cf-631f5ed43057)

**Comment by BreakBB** [comment]
Hey @TheYungDead thanks for bringing this up. Cataclysm indeed brought in a new version of "Captain Sanders' Hidden Treasure", which is the one you see. The next release will hide that one and actually show the correct one.

About the grey quests though: What color do they have in your quest log? Are they green/yellow?

**Comment by coldpasta123** [comment]
@Cabro please close this
