### ISSUE TITLE
Outdated quest names (Uldum, Cataclysm Classic)

### ISSUE THREAD

**Issue by dexorf** [Questie/Questie#6003]
## Description
With release of Cata Classic, names for some quests were changed. Questie Tracker lists them with the old names.

## Wowhead link
https://www.wowhead.com/quest=27141/exploding-through
https://www.wowhead.com/quest=27176/a-strange-disc
Perhaps more quests in the same area that I missed.

## Screenshots
The same quest listed as "A Strange Disc" in the log but "Just The Tip" in the Questie Tracker:
https://cdn.discordapp.com/attachments/1006895458989387838/1243241735954497646/image.png?ex=6650c298&is=664f7118&hm=32bfd20e96e9c6ea8df32e81a86f772efe4700e4542177e25b07ed286ac7f542&

## Questie & WoW version
Version 10.1.3. 
However I glanced through the 10.1.4 and 10.1.5 changelogs & closed issues, and didn't see this reported yet

**Comment by Cabro** [comment]
Fixed in https://github.com/Questie/Questie/commit/d1158228308e2a0e8a8e6f80f9ed0bf7bd9b5aaf
