### ISSUE TITLE
Stuck in combat

### ISSUE THREAD

**Issue by nwardoh** [Questie/Questie#6004]
## Bug description
After killing a quest mob in hyjal I am getting stuck in combat. The worst offenders were the ogres with the trolls carrying the packs but other mobs would do it as well. Disabling questie stopped it from happening again. Closing the game, reloading, etc do not drop combat. I did not test closing it for longer than maybe a minute though. Dying did drop combat.

## Questie & WoW version
10.1.5

Cata Classic

**Comment by BreakBB** [comment]
Hey @nwardoh 

I have no idea how an addon could possibly cause such behavior. Sounds more like a Blizzard bug.

Can you tell which ogre you mean so we can try to reproduce the issue?

A recording might also help. In general enabling/disabling addons caused a reload, which also forces somewhat of a sync between WoW client and server. It might be that, what is helping you. Can you try to just do a `/reload` when you are stuck in combat?

**Comment by nwardoh** [comment]
At the point that I disabled questie I had reloaded multiple times, logged
off and back on, and closed the game and launcher completely for a minute
and then logged back on and was in combat the entire time. Disabled questie
and never had it happen again. Honestly it was going on pretty much all the
time after the baron gherkin quest. If you die you drop out of combat but
after resurrecting and engaging the next mob you are just stuck. It also
happened to my daughter on launch day. Both of us had it happen in hyjal. I
had it happen in the cave where you escort the elf out and then again on
the quest you kill the ogres and the trolls drop their packs and you have
to pick them up. I don’t remember what the quest name is. It’s right before
you go over the hill to get the incense quest drops from the worgen.

**Comment by Muehe** [comment]
This quest? https://www.wowhead.com/cata/quest=25464/the-return-of-baron-geddon

Just for debugging purposes, it would be cool if you could check if the combat state persists through a map teleport (i.e. from Kalimdor to Azeroth/Northrend/Outlands). That should theoretically make whatever it is that is targeting you lose focus and evade, terminating your combat state.

**Comment by nwardoh** [comment]
Yes after that quest it seemed to be about when it started. I’ll reenable
it in the morning and see if I can test taking a portal or hearthing or
something like that.

**Comment by BreakBB** [comment]
Any news on this @nwardoh ?

**Comment by BreakBB** [comment]
Assuming this is resolved.

**Comment by nwardoh** [comment]
I don’t know if it is or not. After that point in questing it didn’t happen
again.
