### ISSUE TITLE
Modules error

### ISSUE THREAD

**Issue by EloneSK** [Questie/Questie#6026]
Hello.  

I tried to reinstall version 10.1.6. - 10.1.7. - 10.1.8. I deleted the cache folder and the WTF folder. But the Questie spam continues.
 In the screenshot, you can see what kind of errors he writes.

How should I fix it? :. ?

![Snímka obrazovky 2024-05-28 220001](https://github.com/Questie/Questie/assets/78366434/53662c4c-d55a-4693-b873-e5e6eadf91a6)

Thanks :)

**Comment by Cabro** [comment]
Can't really see anything, mate

**Comment by EloneSK** [comment]
I fixed the screen

**Comment by BreakBB** [comment]
Ah, damn that isn't released yet. This can just happen for Uldum quests. We'll ship a release right away, to address this @EloneSK

**Comment by BreakBB** [comment]
v10.1.9 fixes this and will be available on CurseForge in a few minutes.

Original fixing commit is d4dfe026b45b67c44ed20d33d8bc3fb107406768
