### ISSUE TITLE
Missing objective data for quest 24721 - The Eastern Pylon (Un'Goro Crater, Cataclysm Classic)

### ISSUE THREAD

**Issue by renodr** [Questie/Questie#6027]
## Description

Hey folks! I'm continuing along my Loremaster journey and have encountered the following error in Un'Goro Crater:

[ERROR] Missing objective data for quest 24721  Discover and examine the Eastern Crystal Pylon

## Wowhead link

https://www.wowhead.com/cata/quest=24721/the-eastern-pylon

## Screenshots

Error:

![image](https://github.com/Questie/Questie/assets/11901488/25683c0f-a437-4121-8ea4-8362ea5b766c)

Quest Description:

![image](https://github.com/Questie/Questie/assets/11901488/0121166f-323b-4078-acca-86b064d971dd)

## Questie & WoW version

Questie 10.1.9
WoW 4.4.0 (Cataclysm Classic)

**Comment by BreakBB** [comment]
Fixed in a831c933ad50fe52e252067cd7afa3b7b7969b6c
