### ISSUE TITLE
QUESTIE CPU ISSUE 

### ISSUE THREAD

**Issue by grftn** [Questie/Questie#6029]
questie cpu issues with latest patch? 
slowed down load in screens, 
checked all add ons and uninstalled questie and loading screens and cpu fans return to normal?

**Comment by BreakBB** [comment]
Hey @grftn can you share a few more details?

> latest patch
Which version exactly? Also Cata, Era, SoD?

> checked all add ons and uninstalled questie and loading screens and cpu fans return to normal?
Do you also have issues with just Questie active?

> slowed down load in screens
So only the loading screen is slow? Any other situations you have issues?

**Comment by BreakBB** [comment]
Closing this as important details are missing 🤷🏻
