### ISSUE TITLE
Cata Classic - Quest 9764 'Orders from Lady Vashj' appears on map, but was removed from game

### ISSUE THREAD

**Issue by dankewaffle** [Questie/Questie#6032]
## Description

Quest 9764 'Orders from Lady Vashj' appears on the map, but the quest was removed from game.

## Wowhead link

https://www.wowhead.com/cata/quest=9764/orders-from-lady-vashj

## Questie & WoW version

Questie v10.1.9 - Cata Classic

**Comment by Cabro** [comment]
Fixed in https://github.com/Questie/Questie/commit/9aa260a140d13d5498ef12822de25c49e3dd53b4
