### ISSUE TITLE
Cata Classic - Quest 9731 'Drain Schematics' shown on map before pre-req completed

### ISSUE THREAD

**Issue by dankewaffle** [Questie/Questie#6033]
## Description

Quest 9731 'Drain Schematics' shown on map before pre-req (9720 'Balance Must Be Preserved') completed.

## Wowhead link

https://www.wowhead.com/quest=9731/drain-schematics

## Questie & WoW version

Questie v10.1.9 - Cata Classic

**Comment by Cabro** [comment]
Fixed in https://github.com/Questie/Questie/commit/2d9c6bdfed46cb06fc1c392f53ecbce5c11ea27c
