### ISSUE TITLE
Missing objective data for An Important Lesson (Cataclysm Classic, Un'Goro Crater)

### ISSUE THREAD

**Issue by renodr** [Questie/Questie#6034]
## Description

Hey folks! I've been continuing my adventures through Un'Goro Crater tonight, and I've encountered an issue with An Important Lesson in Un'Goro Crater, given by Maximillian of Northshire:

[ERROR] Missing objective data for quest 24703 Squire Training Completed

## Wowhead link

https://www.wowhead.com/cata/quest=24703/an-important-lesson

## Screenshots

Error message:
![image](https://github.com/Questie/Questie/assets/11901488/cc582c7f-86b0-4e56-bbe2-9e7309cac1d4)

Quest details:
![image](https://github.com/Questie/Questie/assets/11901488/e7d33531-20ee-425a-b266-dd0cde06c010)

## Questie & WoW version

Questie v10.1.9
WoW 4.4.0 (Cataclysm Classic)

**Comment by coldpasta123** [comment]
@BreakBB fixed with https://github.com/Questie/Questie/commit/9b59f7fa451140f95bda8cf70bed747b4ab01dc9
