### ISSUE TITLE
Addon don't work after update (Error)

### ISSUE THREAD

**Issue by tornadoff** [Questie/Questie#6036]
This problem is not the only one.The addon does not work completely. At the loading stage, an error occurs and that's it.

## Bug description

Error after uptade on 10.2.0 and addon don't work

## Screenshots

![Error](https://github.com/Questie/Questie/assets/36474049/a411f5a8-c75b-4c8d-879e-6bb56348b62b)

## Questie & WoW version

10.2.0   form 01.06.2024

**Comment by Samaelison** [comment]
same shit

**Comment by Totox64** [comment]
Same here on classic era. Addon does not work at all

**Comment by BreakBB** [comment]
Thanks for reporting this! We are already looking into it.

**Comment by TrusterX** [comment]
the same here with de classic client. en client works.

**Comment by BreakBB** [comment]
Questie v10.2.1 will be available in a few minutes, fixing this issue. Thanks for reporting it @tornadoff @Samaelison @Totox64 and @TrusterX

**Comment by Totox64** [comment]
@BreakBB  Seems to work just fine now on french era client. Thx !
