### ISSUE TITLE
Loading DB error

### ISSUE THREAD

**Issue by Schlitzale** [Questie/Questie#6039]
During Questie DataBase loading, while initializing locale...

Error during initialization! Interface/AddOns/Questie/
Localization/10n.lua:52 attempt to call field '?' (a nil value)

![WoWScrnShot_060124_084541](https://github.com/Questie/Questie/assets/171427311/f693871f-256e-49a9-a5ba-e3ddf9bd7a42)

Questie Version:  10.2.1
WOW Classic SoD Version:    1.15.2.54902

**Comment by WolfBearTree** [comment]
Having the same issue. Tried to reinstall but did not fix. Could be a lua file issue but I haven't dealt with that in so long. Waiting to see if someone has any ideas!
