### ISSUE TITLE
Questie v10.2.1 ERROR

### ISSUE THREAD

**Issue by PacifistPete** [Questie/Questie#6040]
## Bug description

Immediately upon loading:
Questie: [ERROR] Error during initialization! Interface/AddOns/Questie/Localization/
|10n.lua:52: attempt to call field '?' (a nil value)

## Screenshots

![image](https://github.com/Questie/Questie/assets/171426902/08ea110c-9925-4335-a7e6-1d1ec3510dd7)

**Comment by wowplayer420** [comment]
I second this, just fired up WoW and upon step 4/9 got the same error.

**Comment by Kennybania123** [comment]
Getting the same error message

**Comment by BreakBB** [comment]
This is the follow up to #6036

We are looking into this. Sorry for the trouble!

**Comment by Smashmedk** [comment]
same, here is the full error msg:

|Hcpl:1 [15:36] Questie DB has updated! Data is being processed, this may take a few moments and cause some lag...
|Hcpl:1 [15:36]  [1/9] Loading database...
|Hcpl:1 [15:36]  [2/9] Applying database corrections...
|Hcpl:1 [15:36]  [3/9] Initializing townfolks...
|Hcpl:1 [15:36] ArkInventory: ERROR> ...ace/AddOns/ArkInventory/Core/ArkInventoryStorage.lua:2658: attempt to call global 'KeyRingButtonIDToInvSlotID' (a nil value)
|Hcpl:1 [15:36]  [4/9] Initializing locale...
|Hcpl:1 [15:36] Questie: [ERROR] Error during initialization! Interface/AddOns/Questie/Localization/l10n.lua:52: attempt to call field '?' (a nil value)

**Comment by Nexton86** [comment]
> This is the follow up to #6036
> 
> We are looking into this. Sorry for the trouble!

thx :) , im curently running v10.2.0-b1  , works fine until the update comes
