### ISSUE TITLE
Error during initialization

### ISSUE THREAD

**Issue by futzel** [Questie/Questie#6041]
Hi,

the most recent version of Questie released an hour ago or so fails during initializing locales, see below.

Thanks

futzel

![questie_error](https://github.com/Questie/Questie/assets/45965114/581f868f-4947-415e-8165-f6ee101b6dc6)

**Comment by BreakBB** [comment]
Hey @futzel make sure to grab Questie v10.2.2 which was released only a few minutes ago. The issue should be fixed with that version.

**Comment by futzel** [comment]
That fixed it indeed, ty.
