### ISSUE TITLE
Missing objective data for quest 24723 - The Western Pylon (Cataclysm Classic, Un'Goro Crater)

### ISSUE THREAD

**Issue by renodr** [Questie/Questie#6042]
## Description

Hey folks! I've been continuing through Un'Goro Crater and just hit an error with The Western Pylon:

[ERROR] Missing objective data for quest 24723 Discover and examine the Western Crystal Pylon

## Wowhead link

https://www.wowhead.com/cata/quest=24723/the-western-pylon

## Screenshots

Error message:
![image](https://github.com/Questie/Questie/assets/11901488/81c92e27-09d9-4244-8d53-1d22bee53e7c)

Quest description:
![image](https://github.com/Questie/Questie/assets/11901488/d50e88f2-a5d6-4929-8f4b-087d874293c1)

## Questie & WoW version

Questie v10.2.2
WoW 4.4.0 (Cataclysm Classic)

**Comment by BreakBB** [comment]
Fixed in a831c933ad50fe52e252067cd7afa3b7b7969b6c
