### ISSUE TITLE
Missing objective data for quest 14357 - To the Hilt! (Desolace, Catacylsm Classic)

### ISSUE THREAD

**Issue by renodr** [Questie/Questie#6043]
## Description

Hey folks, I'm running through Desolace right now and ran into a missing objective data error! The error is:

[ERROR] Missing objective data for quest 14357 Elune's Ritual of War Completed

## Wowhead link

https://www.wowhead.com/cata/quest=14357/to-the-hilt

## Screenshots

Error message:
![image](https://github.com/Questie/Questie/assets/11901488/8a0a2004-1d6b-4747-859e-f9764de565cf)

Quest description:
![image](https://github.com/Questie/Questie/assets/11901488/c18f1a45-a3ec-455a-b0be-b4a2e6ee2742)

## Questie & WoW version

Questie 10.2.2
WoW 4.4.0 (Cataclysm Classic)

**Comment by coldpasta123** [comment]
@Cabro please close - fixed here: https://github.com/Questie/Questie/commit/231a1d5f015b43540abee60b978b153ce0bc07ba
