### ISSUE TITLE
Ribs for Sentinels in Darnasus Quest item

### ISSUE THREAD

**Issue by LexCuteler** [Questie/Questie#6046]
## Description
Hey there, for the Cata daily cooking quest Ribs for Sentinels in Darnasus, could you please add the cooked ribs as usable item next to the quest same as the quest one?
Uncooked item ID: 69904
Cooked item ID: 69906

## Wowhead link
Wowhead: https://www.wowhead.com/cata/quest=29318

## Screenshots
![image](https://github.com/Questie/Questie/assets/171712494/9a55da25-b0bc-48d1-884f-d7493158e795)
![image](https://github.com/Questie/Questie/assets/171712494/9a599624-7b3d-4e17-9ed0-dbddefc6767f)

## Questie & WoW version
Version of Questie: v10.2.2
Version of WoW: 4.4.0.55006

**Comment by Cabro** [comment]
@BreakBB :))

**Comment by BreakBB** [comment]
@Cabro this is another example of `requiredSourceItems` not showing up when there is no `sourceItemId` in the inventory anymore, correct?

**Comment by Cabro** [comment]
Yes.

**Comment by LexCuteler** [comment]
heya! any updates?

**Comment by BreakBB** [comment]
This is not a simple thing to fix for us, sorry @LexCuteler And time is rather limited on my side atm :/
