### ISSUE TITLE
Missing objective data for quest 28218 - A Destiny Of Flame And Sorrow (Cataclysm Classic, Felwood)

### ISSUE THREAD

**Issue by renodr** [Questie/Questie#6048]
## Description

Hey folks! I'm running through Felwood in search of quests for Loremaster, and I've encountered the following error:

[ERROR] Missing objective data for quest 28128 Arthas Defeated

The name of this quest is "A Destiny of Flame and Sorrow", and I'm in Cataclysm Classic.

## Wowhead link

https://www.wowhead.com/cata/quest=28218/a-destiny-of-flame-and-sorrow

## Screenshots

Questie Error:
![image](https://github.com/Questie/Questie/assets/11901488/c1ded1e6-7178-4d06-98d5-b5da08577919)

Quest Description:
![image](https://github.com/Questie/Questie/assets/11901488/e5d7a801-5d62-417c-aa3a-168d5f0f8fac)

## Questie & WoW version

Questie 10.2.3
WoW 4.4.0 (Cataclysm Classic)

**Comment by coldpasta123** [comment]
@Cabro please close - fixed here: https://github.com/Questie/Questie/commit/4cbdd91af9f10c4fc3c99666ff6393adbe068caa
