### ISSUE TITLE
Missing objective data for quest 28256 - The Skull of Gul'dan (Catacylsm Classic, Felwood)

### ISSUE THREAD

**Issue by renodr** [Questie/Questie#6049]
## Description

Hey folks! I've been continuing through my run of Felwood and got another error for missing quest objectives:

[ERROR] Missing quest objective data for quest 28256 Skull of Gul'dan

## Wowhead link

https://www.wowhead.com/cata/quest=28256

## Screenshots

Questie Error:
![image](https://github.com/Questie/Questie/assets/11901488/a990ebc5-ad49-49e1-8ec0-29bbf7a190eb)

Quest Description:
![image](https://github.com/Questie/Questie/assets/11901488/9d06e4c4-b88c-41da-b4d5-db530257680f)

## Questie & WoW version

Questie 10.2.3
WoW 4.4.0 (Cataclysm Classic)

**Comment by coldpasta123** [comment]
@Cabro please close - fixed here: https://github.com/Questie/Questie/commit/4cbdd91af9f10c4fc3c99666ff6393adbe068caa
