### ISSUE TITLE
Missing objective data for quest 28257 - The Fall of Tichondrius (Cataclysm Classic, Felwood)

### ISSUE THREAD

**Issue by renodr** [Questie/Questie#6050]
## Description

Hey folks! I've encountered another quest that's missing objective data while questing through Felwood:

[ERROR] Missing objective data for quest 28257 Tichondrius Defeated

## Wowhead link

https://www.wowhead.com/cata/quest=28257/the-fall-of-tichondrius

## Screenshots

Questie Error:
![image](https://github.com/Questie/Questie/assets/11901488/477bbae5-e604-4159-a3d0-4e00fe3075b3)

Quest Description:
![image](https://github.com/Questie/Questie/assets/11901488/93d9222e-f726-4b0b-9620-6dae3c7636a0)

## Questie & WoW version

Questie 10.2.3
WoW 4.4.0 (Catacylsm Classic)

**Comment by coldpasta123** [comment]
@Cabro please close - fixed here: https://github.com/Questie/Questie/commit/4cbdd91af9f10c4fc3c99666ff6393adbe068caa
