### ISSUE TITLE
deepholm quests 

### ISSUE THREAD

**Issue by longchk** [Questie/Questie#6053]

**Comment by BreakBB** [comment]
Hey @longchk we need some more information to help you out on this.

What Questie version are you using? Does this only affect Deepholm? Any error or helpful screenshot?

**Comment by longchk** [comment]
version 10.2.3   and it is only deepholm that is affected. No errors
showing, just no quests showing up on maps. I tried re-installing, but does
the same thing

**Comment by BreakBB** [comment]
You should try to do the following:

`/questie` -> Advanced -> Recompile Database

Also, what faction are you playing and what level are your characters? Did you come to Deepholm by the regular introduction quests or did you get yourself ported to Deepholm?

**Comment by longchk** [comment]
lvl 84 human ret pally and by quest line and deepholm portal. I will try
the recompile

**Comment by longchk** [comment]
I tried the recompile, no change. I have 2 lvl 85's doing dailys and lvl 84
questing. I tried removing Questie all together and re-installing. Still
nothing showing up

**Comment by BreakBB** [comment]
Can you share a screenshot of you "Icons" settings?

**Comment by longchk** [comment]
resolved, questie enable icons was turned off for some reason

**Comment by BreakBB** [comment]
That's why I asked if you see quests in other areas. Glad you were able to fix it 👍🏻
