### ISSUE TITLE
Quest Timer wont show

### ISSUE THREAD

**Issue by Teax20** [Questie/Questie#6054]
Greetings, 
the quest timer from questie in the tracker wont show at all.
Tested it now with different timed quests and not once the quest timer showed in the tracker.
Activating the Blizzard Timer works fine. Tested different settings, checked for updates and disabled all other addons. 

![grafik](https://github.com/Questie/Questie/assets/16085299/37b879af-69ae-4b36-ad92-e7ef990303fa)
![grafik](https://github.com/Questie/Questie/assets/16085299/4c984a22-0c66-4558-9089-8ed61d79d1dc)

Questie v10.2.3 via Curseforge
WoW Classic Hardcore

**Edit:**
Tested now older versions , started with v10.0.5 and it worked until v10.0.10
![grafik](https://github.com/Questie/Questie/assets/16085299/41bc8fce-1383-44d7-93ed-4aeecc8ba970)

Best regards

**Comment by BreakBB** [comment]
Hey @Teax20 would you mind verifying the version below fixes this issue?

[Questie-v10.2.3-718732e14.zip](https://github.com/user-attachments/files/15811773/Questie-v10.2.3-718732e14.zip)

**Comment by BreakBB** [comment]
I was able to verify this is working. Fix will be released soon.
