### ISSUE TITLE
Quest Data Error for Quest 9563

### ISSUE THREAD

**Issue by m0repheuss** [Questie/Questie#6055]
Not sure what quest his is but I keep getting the error "Missing objective data for quest 9563 Honor Hold: Honored/Friendly

![image](https://github.com/Questie/Questie/assets/91290904/d70c8919-e0ff-4b9b-a390-764ffbaea493)

**Comment by BreakBB** [comment]
It's this quest: https://www.wowhead.com/cata/quest=9563/gaining-mirrens-trust

**Comment by Cabro** [comment]
Fixed in https://github.com/Questie/Questie/commit/57b894ffbcdcdab7ab968ffb76f89f399f2df307
