### ISSUE TITLE
Questie not support wotlk for CN server.

### ISSUE THREAD

**Issue by Loukky** [Questie/Questie#6058]
## Bug description
Questie not support wotlk for CN server.

## Screenshots
![QQ截图20240615134003](https://github.com/Questie/Questie/assets/12481807/8bb488bd-5c02-4ea0-bbd3-77c7031e05ee)

## Questie & WoW version

Which version of Questie are you using? You can find it by:
Version 10.2.4

Please also state if your quest issue is about Classic Era/SoM or Wotlk.
Game version:Wotlk 3.4.3.55161(There may be changes in the future)

**Comment by BreakBB** [comment]
I am confused. So for Chinese players there are official WotLK servers available? Do you also have Cataclysm servers available?

**Comment by Loukky** [comment]
> I am confused. So for Chinese players there are official WotLK servers available? Do you also have Cataclysm servers available?

Official server had stopped about 2 years ago,But now they continue...on Wotlk p1,so Cata maybe available in the future

**Comment by BreakBB** [comment]
Thanks, that's the information I was missing 👍🏻

**Comment by MyTechnoHunter** [comment]
Something something deal tween provider and blizzard fell apart, now back 8n place?

**Comment by BreakBB** [comment]
Hey @Loukky a Questie version supporting WotLK will be available soon (~5 minutes).

One downside is: You'll see the quests of all WotLK phases for now.

**Comment by Loukky** [comment]
> Hey @Loukky a Questie version supporting WotLK will be available soon (~5 minutes).
> 
> One downside is: You'll see the quests of all WotLK phases for now.

Thank you sir 👍,i will test later

**Comment by Loukky** [comment]
@BreakBB Tested.works fine.....Thank you sir 🙏

**Comment by BreakBB** [comment]
Thanks for checking and reporting back @Loukky !
