### ISSUE TITLE
Showing unobtainable quest

### ISSUE THREAD

**Issue by Phittoric** [Questie/Questie#6065]
## Bug description
Questie is showing quest: "[25] Let me make you an offer" but that quest is no longer available. 

## Questie & WoW version
WoW Season of Discovery
Which version of Questie are you using? You can find it by:
Questie version 10.2.5

Please also state if your quest issue is about Classic Era/SoM or Wotlk.
WoW Classic Season of Discovery

**Comment by BreakBB** [comment]
This is fixed in the latest Questie release v10.3.4
