### ISSUE TITLE
Cata: Incorrect location for "Verog" in quest, "Verog The Dervish" (The Barrens)

### ISSUE THREAD

**Issue by luciidlou** [Questie/Questie#6072]
## Description
This is in cata...
Current pinned location for Verog: 53.0X 42.0Y (Grol'dom Farm)
**_Actual_** location of Verog: 51.0X 78.8Y (Just west of The Stagnant Oasis)

## Wowhead link
https://www.wowhead.com/classic/quest=851/verog-the-dervish (It's wrong here too. The pin in the map screenshot is technically correct, but the coordinates are wrong)

## Screenshots
Incorrect questie location
![verog_the_dervish_incorrect_location](https://github.com/Questie/Questie/assets/87360583/64fe334f-c427-4433-bc35-372bcef93ea9)
Actual location
![verog_the_dervish_correct_location](https://github.com/Questie/Questie/assets/87360583/beb74fa0-04c0-4447-9661-11a57b6ca74d)

## Questie & WoW version
`10.2.5` (I realize I am a few releases behind, but I finished the quest before updating to the `10.3.1` and I didn't see anything in the changelog

**Comment by luciidlou** [comment]
@BreakBB I saw you did something similar [here](https://github.com/Questie/Questie/commit/1267192f5a754e2bf35051c16abae487bb3e27f6). If I was interested in contributing to Questie, is this something I could open a PR for? The code change seems easy enough, but I'd like to know the significance of the integers that get wrapped in brackets on the left of the assignment operator (`[3745]` for example, in your commit that I linked).

Thanks in advance!

**Comment by Cabro** [comment]
3745 is the NPC id

**Comment by luciidlou** [comment]
@Cabro Thanks! I figured it had to be something like that. What other steps need to be taken in order for me to contribute? I have a working branch with the code change, but I get the following error when attempting to push the branch up to the remote repository...
```
ERROR: Permission to Questie/Questie.git denied to luciidlou.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
