### ISSUE TITLE
[ERROR] Fehlende Ziel-Daten für Quest 26903

### ISSUE THREAD

**Issue by Prideland** [Questie/Questie#6082]
![grafik](https://github.com/Questie/Questie/assets/138702513/9de7ce08-c7cd-44c5-b7e3-2e371fb72e13)

**Comment by Sommos** [comment]
Wowhead quest link: https://www.wowhead.com/cata/quest=26903/willix-the-importer

Missing Objective Data

**Comment by coldpasta123** [comment]
@Cabro please close - fixed here: https://github.com/Questie/Questie/commit/f9a226105e68127a67044528f3600cecb7108537
