### ISSUE TITLE
Aberrations of Bone shows up as Unknown Zone (should be Scholomance) - Cataclysm Classic

### ISSUE THREAD

**Issue by renodr** [Questie/Questie#6083]
## Description

Hi folks! While picking up quests in Eastern Plaguelands at Light's Hope Chapel, I picked up "Aberrations of Bone" from Lord Raymond George behind the chapel. Now that I have it, the quest shows up as Unknown Zone, though it should be Scholomance.

## Wowhead link

https://www.wowhead.com/cata/quest=28756/aberrations-of-bone

## Screenshots

![image](https://github.com/Questie/Questie/assets/11901488/b612348a-fbbf-4822-a762-1d10b6170f24)
![image](https://github.com/Questie/Questie/assets/11901488/bc04c9d5-680d-49ea-b2ee-92729cb20962)

## Questie & WoW version

WoW 4.4.0 (Cataclysm Classic)
Questie 10.3.1

**Comment by BreakBB** [comment]
Another great report @renodr thanks!
