### ISSUE TITLE
Missing objective data error on Lunthistle's Tale in Searing Gorge (Cataclysm Classic)

### ISSUE THREAD

**Issue by renodr** [Questie/Questie#6085]
## Description

Hi folks! While running through Searing Gorge on my Loremaster adventures, I've run into an issue with quest 27984. It's one of those Missing Objective Data errors, screenshots attached 😃 

## Wowhead link

https://www.wowhead.com/cata/quest=27984/lunthistles-tale

## Screenshots

Questie Error:
![image](https://github.com/Questie/Questie/assets/11901488/86806fcd-ef9e-4179-a507-ab3b438aa3c0)

Quest information:
![image](https://github.com/Questie/Questie/assets/11901488/fb7c8bf9-62e0-4b1d-ac8e-38f4fea04604)

## Questie & WoW version

Questie 10.3.1
WoW 4.4.0 (Cataclysm Classic)

**Comment by coldpasta123** [comment]
@Cabro please close - fixed here: https://github.com/Questie/Questie/commit/6b415796d78d5e56d459eb4f5839f30e24cf9c6e
