### ISSUE TITLE
[Vanilla] Look at the Size of It! (7704) - Quest doesn't exist

### ISSUE THREAD

**Issue by JabaBr** [Questie/Questie#6088]
_Zone_
**Searing Gorge**

**Inaccurate**
• Placed in Searing Gorge after patch 10.1.1 (WotLK)

[**(7704)** Look at the Size of It!](https://www.wowhead.com/classic/quest=7704/look-at-the-size-of-it)

**Accurate**
• This Quest doesn't exist in Vanilla, and should be **Removed**

I analyzed **Database/Corrections/QuestieQuestBlacklist.lua** and found the following configuration: 
**[7704] = QuestieCorrections.CLASSIC_HIDE + QuestieCorrections.SOD_HIDE + QuestieCorrections.TBC_HIDE, -- Not implemented in Era, added in Wrath**

However this configuration isn't working.The quest is being shown in Classic Vanilla.

![Captura de tela 2024-07-05 001125](https://github.com/Questie/Questie/assets/29123718/f77ec26b-4444-4d1e-944f-d932a2ce428b)

**Comment by BreakBB** [comment]
Hey @JabaBr thanks for reporting this. You are right and the code is not filtering these quests as it should.

We'll look into it!

**Comment by BreakBB** [comment]
Fixed in 9e41ff0dcb7e515cbf6e50437750467652aa9582
