### ISSUE TITLE
Change midsummer date for China Region

### ISSUE THREAD

**Issue by Mini-Dragon** [Questie/Questie#6092]
In China Region, the midsummer date is from June 21 to July 28

![Screenshot 2024-07-05 150903](https://github.com/Questie/Questie/assets/5449312/085e4c4a-50e2-4c22-b66f-2433c5f9552d)

After today, Questie doesn't provide midsummer quest hint (include bonfire) in map and minimap.
I recommend to fix Questie/Database/Corrections/Holidays/QuestieEvent.lua

add something like

if GetCurrentRegion() == 5
 ["Midsummer"] = {startDate = "21/6", endDate = "28/7"}

**Comment by BreakBB** [comment]
Great idea @Mini-Dragon
