### ISSUE TITLE
[Cata Classic] - Quest shown is not yet available in current phase

### ISSUE THREAD

**Issue by theoriginalmre** [Questie/Questie#6093]
The level 85 quest "A Legendary Engagement" (quest = 29132) from NPC Coridormi (npc = 52408) in Stormwind is not yet available in the current phase of Cata Classic, but still shows up on the map. Please remove <3

https://www.wowhead.com/cata/quest=29132/a-legendary-engagement

Questie version 10.3.1
(Cata Classic)

**Comment by Cabro** [comment]
This is one of those quests that you can only get after you kill a boss in a raid. Questie cannot detect that, same case as with https://www.wowhead.com/cata/quest=26012/trouble-at-wyrmrest
My priest has absolutely done the quest you say is impossible to get, and also the followup.

**Comment by theoriginalmre** [comment]
Well, my bad I guess. I'll detract.
