### ISSUE TITLE
Toggling the Questie map button breaks available quest tooltips.

### ISSUE THREAD

**Issue by Cabro** [Questie/Questie#6101]
https://github.com/Questie/Questie/assets/1155017/2c6110e6-ddf6-49f7-8231-9194f98b6b63

A simple toggle on and off of the Questie map button removes all available quest tooltips from mouseover/target.
The map ones are not broken.

**Comment by BreakBB** [comment]
Did you wait for a second to have the tooltips again?

**Comment by Cabro** [comment]
I waited for way longer than a second :P tooltips are gone
