### ISSUE TITLE
Classic SoD

### ISSUE THREAD

**Issue by sharrenskunk** [Questie/Questie#6121]
while using latest version of questie on Classic SoD I've noticed after latest update to Addon that after about 30-40 minutes of gameplay the mod stops auto accepting and turning in quests, for it to reload you have to shut the entire game down as logging out doesn't reset the timer.

**Comment by BreakBB** [comment]
A `/reload` will help you as well. The auto accepting of Questie is far from perfect. I know that if you manually stop auto accepting (by holding Shift when talking to an NPC), that _can_ indeed bug out Questies auto accepting.

**Comment by BreakBB** [comment]
Closing in favor of #5061
