### ISSUE TITLE
Questie: [ERROR] 

### ISSUE THREAD

**Issue by debrnr** [Questie/Questie#6122]
Questie: [ERROR] Questie 数据库中缺少的任务 83713，请到 GitHub 或 Discord 上报告，谢谢! 
Questie: [ERROR] Questie 数据库中缺少的任务 83714，请到 GitHub 或 Discord 上报告，谢谢!

**Comment by debrnr** [comment]
CHINA WLK 3.4.3

**Comment by BreakBB** [comment]
Closing in favor of #6314
