### ISSUE TITLE
Quest in tracker not present in QuestDB! Priority Target: Duke Tectonis

### ISSUE THREAD

**Issue by konffen** [Questie/Questie#6131]
## Description
Quest in tracker not present in QuestDB!

Quest ID: 84348
Quest Name: Priority Target: Duke Tectonis
Quest Text: There's a particularly nasty elemental called Tectonis calling the shots near the base of blackrock mountain and he's just gotta go! Put an end to this pile o' rocks and report back to me when the deed is done!

You'll find Duke Tectonis in a valley to the southeast, near the entrance to Blackrock Mountain.
Objective Text: Hansel Heavyhands at Thorium Point wants you to destroy Duke Tectonis. Duke Tectonis can be found in a small valley just to the west of the Searing Gorge entrance to Blackrock Mountain.
Character: Lvl 60 ORC WARRIOR
Player Coords:  [1427]  (28.387, 75.883)
QuestLog: 5282, 84350, 6582, 5214, 6822, 5461, 5047, 84348, 5251, 84349, 8930, 84351, 6584, 5212, 84372, 6583, 84360, 4742, 
Client: 1.15.3 SoD
Questie: v10.3.3
Locale: enUS

## Wowhead link
[](https://www.wowhead.com/classic/quest=84348/priority-target-duke-tectonis)

## Questie & WoW version
Questie: v10.3.3
Client: 1.15.3 SoD

**Comment by konffen** [comment]
Link to Wowhead:
https://www.wowhead.com/classic/quest=84348/priority-target-duke-tectonis

**Comment by BreakBB** [comment]
This is already fixed in the latest release v10.3.4
