### ISSUE TITLE
Quest Issue for quest 14312 - An Introduction Is In Order (Desolace, Cataclysm Classic)

### ISSUE THREAD

**Issue by SagittaryX** [Questie/Questie#6173]
## Description
Quest appears prematurely on map

## Wowhead link
Quest: https://www.wowhead.com/cata/quest=14312/an-introduction-is-in-order
Prerequisite: https://www.wowhead.com/cata/quest=14311/taking-part

## Questie & WoW version
Questie v10.3.5 & Cataclysm Classic

**Comment by BreakBB** [comment]
Thanks for all of these reports @SagittaryX - We appreciate it!

**Comment by SagittaryX** [comment]
No problem at all @BreakBB , will try to keep it up as I go, but telling which quest is the actual prerequisite is a bit tricky for some of them

**Comment by BreakBB** [comment]
Hmmm... I'd say it's better to have the issue transparent. So if it's okay for you and not too much work, we'd appreciate reports for quests, which you can't tell how to fix, as well 👍🏻
