### ISSUE TITLE
LUA Error in Version 10.3.6

### ISSUE THREAD

**Issue by lokisilverblade** [Questie/Questie#6182]
1x ...Ons/Questie/Localization/lookups/lookupOverrides.lua:5: attempt to index field 'deDE' (a nil value)
[string "@Questie/Localization/lookups/lookupOverrides.lua"]:5: in main chunk

Locals:
l10n = <table> {
 InitializeLocaleOverride = <function> defined @Questie/Localization/l10n.lua:33
 questLookup = <table> {
 }
 zoneLookup = <table> {
 }
 objectNameLookup = <table> {
 }
 continentLookup = <table> {
 }
 SetUILocale = <function> defined @Questie/Localization/l10n.lua:178
 GetUILocale = <function> defined @Questie/Localization/l10n.lua:186
 questCategoryLookup = <table> {
 }
 translations = <table> {
 }
 Initialize = <function> defined @Questie/Localization/l10n.lua:50
 PostBoot = <function> defined @Questie/Localization/l10n.lua:103
 objectLookup = <table> {
 }
 private = <table> {
 }
 npcNameLookup = <table> {
 }
 zoneCategoryLookup = <table> {
 }
 itemLookup = <table> {
 }
}
(*temporary) = nil
(*temporary) = <table> {
 1 = "Einen Vorteil gewinnen"
 3 = <table> {
 }
}
(*temporary) = "Einen Vorteil gewinnen"
(*temporary) = nil
(*temporary) = <table> {
 1 = "Bringt dem Abgesandten Mordin in Shattrath 8 Netherrückstände."
}
(*temporary) = "Bringt dem Abgesandten Mordin in Shattrath 8 Netherrückstände."
(*temporary) = "attempt to index field 'deDE' (a nil value)"

**Comment by BreakBB** [comment]
Oh damn, this is bad. Thanks @lokisilverblade looking into it right away.

**Comment by BreakBB** [comment]
@Cabro did you not test it with another client? 🙈

**Comment by lokisilverblade** [comment]
Hey sry next time i post the client version too :(

**Comment by BreakBB** [comment]
Oh, no worries @lokisilverblade ! That wasn't meant for you 😁 

It's great you reported it right away, thanks ❤️
