### ISSUE TITLE
Quest Issue for quest 14333 - While You're Here (Desolace, Cataclysm Classic)

### ISSUE THREAD

**Issue by SagittaryX** [Questie/Questie#6186]
## Description
The item locations required for this quest do not appear on the map, and when hovering over item on the ground questie also doesn't say it's a relevant item for the quest (unsure if that's intended).

## Wowhead link
Quest: https://www.wowhead.com/quest=14333/while-youre-here
Item: https://www.wowhead.com/item=49194/defiled-relic

## Screenshots
Item not showed on map (kill marks are for other quest):
![image](https://github.com/user-attachments/assets/08508b4b-9aa7-468b-aef3-240e183046db)

Item not marked as relevant: 
![image](https://github.com/user-attachments/assets/d1b3e587-ef8d-45e2-9e0d-b7a0baeebc55)

## Questie & WoW version
Questie v10.3.7 & Cataclysm Classic

**Comment by coldpasta123** [comment]
@Cabro this issue is fixed - can you close please https://github.com/Questie/Questie/commit/6d760d5003e5957094a3c3b222b77f33513ab76b
