### ISSUE TITLE
Quest Issue for quest 25450 - Improved Quality (Feralas, Cataclysm Classic)

### ISSUE THREAD

**Issue by SagittaryX** [Questie/Questie#6223]
EDIT: The quest code might be wrong, I tried checking 7733 for the completion flag ingame but got a false, so the current code might be something else. Wowhead info for this quest doesn't seem correect at all

EDIT2: It is actually quest 25450, originally linked wrong old 7733. Wowhead info for 25450 is still wrong though, only southern yetis drop the required item.

## Description
Quest incorrectly marks where to find the mobs for the required item, putting a single mark in the north of Feralas (where you had to go for the quest before this followup). Correct mob for the quest is linked below.

Curiously it seems the quest is also not correct on Wowhead, the quest text there is different from what is ingame, and wowhead also incorrectly marks the northern yetis as dropping the quest item. I think Blizzard may have altered the quest between Cataclysm and the current retail and an error slipped in on wowhead.

## Wowhead link
Quest: https://www.wowhead.com/cata/quest=25450/improved-quality
Correct Mob: https://www.wowhead.com/cata/npc=5292/feral-scar-yeti

## Screenshots
NPC not marked as relevant for the quest: 
![image](https://github.com/user-attachments/assets/e2219a89-cf48-4473-8226-6cecd2843b7b)

## Questie & WoW version
Questie v10.3.7 & Cataclysm Classic

**Comment by coldpasta123** [comment]
Fixed in https://github.com/Questie/Questie/pull/6652

@BreakBB please close
