### ISSUE TITLE
Quest Issue for quest 25409 - Forces of Nature: Hippogryphs (Feralas, Cataclysm Classic)

### ISSUE THREAD

**Issue by SagittaryX** [Questie/Questie#6224]
## Description
Quest requires using an item on mobs. Mobs locations are not marked on the map, and the NPC is not marked as relevant for the quest in the tooltip.

## Wowhead link
Quest: https://www.wowhead.com/cata/quest=25409/forces-of-nature-hippogryphs
Mob: https://www.wowhead.com/cata/npc=5300/frayfeather-hippogryph

## Screenshots
Mob not marked as NPC relevant for the quest:
![image](https://github.com/user-attachments/assets/7733b4ff-5866-48c3-bea2-0ab12b472fc0)

## Questie & WoW version
Questie v10.3.7 & Cataclysm Classic

**Comment by coldpasta123** [comment]
@Cabro please close - fixed here: https://github.com/Questie/Questie/commit/6d760d5003e5957094a3c3b222b77f33513ab76b
