### ISSUE TITLE
Quest Issue for quest 25410 - Forces of Nature: Treants (Feralas, Cataclysm Classic)

### ISSUE THREAD

**Issue by SagittaryX** [Questie/Questie#6227]
## Description
Same issue as https://github.com/Questie/Questie/issues/6224

Quest requires using an item on mobs. Mobs locations are not marked on the map, and the NPC is not marked as relevant for the quest in the tooltip.

## Wowhead link
Quest: https://www.wowhead.com/cata/quest=25410/forces-of-nature-treants
Mob: https://www.wowhead.com/cata/npc=7584/wandering-forest-walker

## Screenshots
Mob not marked as relevent for quest in tooltip:
![image](https://github.com/user-attachments/assets/b3a6c613-7288-4681-a7cf-ddb9baaffec9)

## Questie & WoW version
Questie v10.3.7

**Comment by coldpasta123** [comment]
@Cabro please close - fixed here: https://github.com/Questie/Questie/commit/6d760d5003e5957094a3c3b222b77f33513ab76b
