### ISSUE TITLE
Quest Issue for quest 25475 - Find OOX-22/FE (Feralas, Cataclysm Classic)

### ISSUE THREAD

**Issue by SagittaryX** [Questie/Questie#6228]
## Description
Picking up the item that starts this quest from a random mob, the text that appears in the chat window says the quest is for level 45, but it is actually for a level 37 character when you accept it.

## Wowhead link
Quest: https://www.wowhead.com/cata/quest=25475/find-oox-22-fe
Item: https://www.wowhead.com/cata/item=8705/oox-22-fe-distress-beacon

## Screenshots
Text by questie indicating wrong quest level:
![image](https://github.com/user-attachments/assets/d36b04d5-dd26-4ce5-8082-399db2324d78)

Questie indicating it is a level 37 quest:
![image](https://github.com/user-attachments/assets/2732c307-129c-42e0-9dd3-7b348947739e)

## Questie & WoW version
Questie v10.3.7

**Comment by TorpedoCXC** [comment]
Interesting.

The quest exists now under the same name with a new ID. See this comment on the page of the removed quest: https://www.wowhead.com/cata/quest=2766/find-oox-22-fe#comments:id=1525914
The removed quest 2766 was indeed level 45.

The new quest is 25475: https://www.wowhead.com/cata/quest=25475/find-oox-22-fe
This new quest is level 37.

So it looks like we need to blacklist quest ID 2766 and add 25475.

**Comment by Cabro** [comment]
Fixed in https://github.com/Questie/Questie/commit/ba152cc8189ee8bf98fa874224b1fa18d9e1cdd2
