### ISSUE TITLE
Quest Issue for quest 25333 - Might of the Sentinels (Feralas, Cataclysm Classic)

### ISSUE THREAD

**Issue by SagittaryX** [Questie/Questie#6233]
## Description
No marker on the map for the location of this quest, player location in screenshot would be an accurate position for the quest marker. Position is very close to the map marker for all Dire Maul quests.

## Wowhead link
Quest: https://www.wowhead.com/cata/quest=25333/might-of-the-sentinels

## Screenshots
Player location relevant:
![image](https://github.com/user-attachments/assets/af4557d8-9ce7-4e20-a217-9c32df149c9d)

## Questie & WoW version
Questie v10.3.7 & Cataclysm Classic

**Comment by coldpasta123** [comment]
Fixed in https://github.com/Questie/Questie/pull/6652

@BreakBB please close
