### ISSUE TITLE
Quest Issue for quest 25423 - Ancient Suffering (Feralas, Cataclysm Classic)

### ISSUE THREAD

**Issue by SagittaryX** [Questie/Questie#6237]
## Description
Quest appears prematurely on map, has prerequisite

## Wowhead link
Quest: https://www.wowhead.com/cata/quest=25423/ancient-suffering
Prerequisite: https://www.wowhead.com/cata/quest=25350/the-lost-apprentice

## Questie & WoW version
Questie v10.3.7 & Cataclysm Classic

**Comment by Sommos** [comment]
https://github.com/Questie/Questie/commit/3cf9a48c457b2a7e5ee618c01cfa082f7b3de162
