### ISSUE TITLE
Questie: [ERROR] Missing quest 83713,nil during tracker update

### ISSUE THREAD

**Issue by Aober1** [Questie/Questie#6249]
## Bug description
When I accept daily quests from NPCs in Dalaran, I encounter an error with the Questie addon. The error messages are as follows:

Questie: [ERROR] Missing quest 83713,nil during tracker update
Questie: [ERROR] Missing quest 83714,nil during tracker update
This occurs when accepting the quests "Proof of Demise: Threats to Azeroth" and "Proof of Demise: Titan Rune Protocol Gamma". The NPC location and quests are shown in the attached screenshots.

## Screenshots
![20240717181712](https://github.com/user-attachments/assets/a1530c5b-c938-45f9-afbe-17de89df127e)
![20240711201320](https://github.com/user-attachments/assets/0c3eabf6-4536-471d-9cf1-ca81e836fbcf)

## Questie & WoW version
I am using Questie version 10.3.7. This issue occurs in the Wrath of the Lich King Classic server (CN) Version:3.4.3.55586.

**Comment by BreakBB** [comment]
Hey @Aober1 thanks for reporting this! It looks like Blizzard added new versions of these quests:

https://www.wowhead.com/wotlk/quest=78752/proof-of-demise-titan-rune-protocol-gamma
https://www.wowhead.com/wotlk/quest=78753/proof-of-demise-threats-to-azeroth

We'll have to add them.

@BrandonJack9 maybe this is something you want to look into?

**Comment by BrandonJack9** [comment]
I'll look into it tomorrow!

**Comment by BreakBB** [comment]
Closing in favor of #6314
