### ISSUE TITLE
Quest Issue for quest 25436 - Spiteful Sisters (Feralas, Cataclysm Classic)

### ISSUE THREAD

**Issue by SagittaryX** [Questie/Questie#6259]
## Description
Quest appears prematurely on map, has prerequisite

## Wowhead link
Quest: https://www.wowhead.com/cata/quest=25436/spiteful-sisters
Prerequisites: https://www.wowhead.com/cata/quest=25434/taming-the-tamers
https://www.wowhead.com/cata/quest=25433/sasquatch-sighting

## Questie & WoW version
Questie v10.3.7 & Cataclysm Classic

**Comment by Sommos** [comment]
https://github.com/Questie/Questie/commit/6c04976168559e49d773d890a59bed5d4e08b695
