### ISSUE TITLE
Quest Issue for quest 25437 - Ysondre's Call (Feralas, Cataclysm Classic)

### ISSUE THREAD

**Issue by SagittaryX** [Questie/Questie#6260]
## Description
Map appears on map prematurely, has prerequisite

## Wowhead link
Quest: https://www.wowhead.com/cata/quest=25437/ysondres-call
Prerequisite: https://www.wowhead.com/cata/quest=25436/spiteful-sisters

## Questie & WoW version
Questie v10.3.7

**Comment by Sommos** [comment]
https://github.com/Questie/Questie/commit/f59c71c68e1e4bb57ac8e6e1a3c4fe6c30fc20ed
