### ISSUE TITLE
Quest Issue for quest 25438 - Ysondre's Farewell (Feralas, Cataclysm Classic)

### ISSUE THREAD

**Issue by SagittaryX** [Questie/Questie#6261]
## Description
Quest appears prematurely on map, has prerequisite

## Wowhead link
Quest: https://www.wowhead.com/cata/quest=25438/ysondres-farewell
Prerequisite: https://www.wowhead.com/cata/quest=25379/taerars-fall

## Questie & WoW version
Questie v10.3.7 & Cataclysm Classic

**Comment by Sommos** [comment]
https://github.com/Questie/Questie/commit/b974c9405d9f9a29592482f4616d57f5dac94e9a
