### ISSUE TITLE
Quest Issue for quest 25562 - Circle the Wagons... er, Boats (Thousand Needles, Cataclysm Classic)

### ISSUE THREAD

**Issue by SagittaryX** [Questie/Questie#6262]
## Description
Quest appears prematurely on map, has prerequisite

## Wowhead link
Quest: https://www.wowhead.com/cata/quest=25562/circle-the-wagons-er-boats
Prerequisite: https://www.wowhead.com/cata/quest=25532/pirate-accuracy-increasing

## Questie & WoW version
Questie v10.3.7

**Comment by Sommos** [comment]
https://github.com/Questie/Questie/commit/504c0779667be9eb72978bab312c2dc4033e15b5
