### ISSUE TITLE
Quest Issue for quest 25590 - Where's Wizzle? (Thousand Needles, Cataclysm Classic)

### ISSUE THREAD

**Issue by SagittaryX** [Questie/Questie#6264]
## Description
Quest appears prematurely on map, has prerequisite

## Wowhead link
Quest: https://www.wowhead.com/cata/quest=25590/wheres-wizzle
Prerequisite: https://www.wowhead.com/cata/quest=25562/circle-the-wagons-er-boats

## Questie & WoW version
Questie v10.3.7 & Cataclysm Classic

**Comment by Sommos** [comment]
https://github.com/Questie/Questie/commit/d80c4ea3d44d60095eb4c3b1f72258a4992c9c54
