### ISSUE TITLE
Quest Issue for quest 28031 - Special Delivery for Brivelthwerp (Thousand Needles, Cataclysm Classic)

### ISSUE THREAD

**Issue by SagittaryX** [Questie/Questie#6266]
## Description
Quest appears prematurely on map, has prerequisite

I am not sure this one appeared before, more of a check to be sure

## Wowhead link
Quest: https://www.wowhead.com/cata/quest=28031/special-delivery-for-brivelthwerp
Prerequisite: https://www.wowhead.com/cata/quest=25562/circle-the-wagons-er-boats

## Questie & WoW version
Questie v10.3.7 & Cataclysm Classic

**Comment by coldpasta123** [comment]
Horde: https://www.wowhead.com/cata/quest=28042/special-delivery-for-brivelthwerp
Requires https://www.wowhead.com/cata/quest=25562/circle-the-wagons-er-boats OR https://www.wowhead.com/cata/quest=25543/circle-the-wagons-er-boats

Alliance: https://www.wowhead.com/cata/quest=28031/special-delivery-for-brivelthwerp
Requires: https://www.wowhead.com/cata/quest=25542/circle-the-wagons-er-boats OR https://www.wowhead.com/cata/quest=25561/circle-the-wagons-er-boats
