### ISSUE TITLE
Quest Issue for quest 25799 - Defend the Drill (Thousand Needles, Cataclysm Classic)

### ISSUE THREAD

**Issue by SagittaryX** [Questie/Questie#6268]
## Description
Quest appears prematurely on the map, has prerequisite

## Wowhead link
Quest: https://www.wowhead.com/cata/quest=25799/defend-the-drill
Prerequisite: https://www.wowhead.com/cata/quest=25790/back-to-crazzle

## Questie & WoW version
Questie v10.3.7

**Comment by coldpasta123** [comment]
@SagittaryX Wowhead suggests the prequest for this is Eminent Domain, not Back to Crazzle. Do you remember from when you did this to validate please?
