### ISSUE TITLE
Quest Issue for quest 25660 - Haunted (Thousand Needles, Cataclysm Classic)

### ISSUE THREAD

**Issue by SagittaryX** [Questie/Questie#6270]
## Description
Quest appears prematurely on the map, has prerequisite

## Wowhead link
Quest: https://www.wowhead.com/cata/quest=25660/haunted
Prerequisite: https://www.wowhead.com/cata/quest=25627/two-tusk-takedown

## Questie & WoW version
Questie v10.3.7 & Cataclysm Classic

**Comment by coldpasta123** [comment]
Two Tusk Takedown is the alliance prequest - need to figure out what the horde equivalent is (if there is one). Not obvious on Wowhead; will test in game

**Comment by coldpasta123** [comment]
Alliance: https://www.wowhead.com/cata/quest=25627/two-tusk-takedown
Horde: https://www.wowhead.com/cata/quest=25628/two-tusk-takedown
