### ISSUE TITLE
Quest Issue for quest 25672 - Carcass Collection (Thousand Needles, Cataclysm Classic)

### ISSUE THREAD

**Issue by SagittaryX** [Questie/Questie#6271]
## Description
Quest does not indicate the location of any objectives on the map, which are a variety of dead mobs across the salt flats of Thousand Needles. I included the mobs I looted from below, might be more.

## Wowhead link
Quest: https://www.wowhead.com/cata/quest=25672/carcass-collection
Mob: https://www.wowhead.com/cata/npc=41103/sparkleshell-snapper
https://www.wowhead.com/cata/npc=41100/scorpid-reaver
https://www.wowhead.com/cata/npc=41099/saltstone-crystalhide

## Questie & WoW version
Questie v10.3.7 & Cataclysm Classic

**Comment by coldpasta123** [comment]
@Cabro please close - fixed here: https://github.com/Questie/Questie/commit/404bbcbbc4b0d4b5b4df309cd6d42589a0961514
