### ISSUE TITLE
Quest Issue for quest 28051 - We All Scream for Ice Cream... and then Die! (Thousand Needles, Cataclysm Classic)

### ISSUE THREAD

**Issue by SagittaryX** [Questie/Questie#6272]
## Description
Quest appears prematurely on map, has prerequisite

## Wowhead link
Quest: https://www.wowhead.com/cata/quest=28051/we-all-scream-for-ice-cream-and-then-die
Prerequisite: https://www.wowhead.com/cata/quest=28031/special-delivery-for-brivelthwerp

## Questie & WoW version
Questie v10.3.7 & Cataclysm Classic

**Comment by Nerillida** [comment]
If you look at Wowhead, it seems more complex thn just adding a Prerequisite quest. Quest 28031 is an alliance quest, 28042 is the horde equivalent. Either lead to 28045 The Greatest Flavor in the World!. Only then to 28051.

**Comment by coldpasta123** [comment]
@Nerillida I've seen contradictory comments on Wowhead about whether [We All Scream for Ice Cream... and then Die!](https://www.wowhead.com/cata/quest=28051/we-all-scream-for-ice-cream-and-then-die) and [The Greatest Flavor in the World!](https://www.wowhead.com/cata/quest=28045/the-greatest-flavor-in-the-world) are available at the same time or sequentially. I will test in game.

**Comment by Nerillida** [comment]
As long as you know.

**Comment by SagittaryX** [comment]
I do believe both of those quests are available at the same time, with another followup 2 quests as I recall, but it has been a while now since I did it.

**Comment by Nerillida** [comment]
Yeah, me too.
