### ISSUE TITLE
Quest Issue for quest 28048 - That Smart One's Gotta Go (Thousand Needles, Cataclysm Classic)

### ISSUE THREAD

**Issue by SagittaryX** [Questie/Questie#6274]
## Description
Quest appears prematurely on map, has prerequisite

## Wowhead link
Quest: https://www.wowhead.com/cata/quest=28048/that-smart-ones-gotta-go
Prerequisite: https://www.wowhead.com/cata/quest=28051/we-all-scream-for-ice-cream-and-then-die
https://www.wowhead.com/cata/quest=28045/the-greatest-flavor-in-the-world

## Questie & WoW version
Questie v10.3.7 & Cataclysm Classic

**Comment by Sommos** [comment]
https://github.com/Questie/Questie/commit/9bd3af3f9bab42ea4129ce27d8d052660f25b4d0
