### ISSUE TITLE
Quest Issue - The Hunt (Cata Classic)

### ISSUE THREAD

**Issue by coldpasta123** [Questie/Questie#6279]
## Description

Showing as available before pre-quests are completed. Requires [An Unusual Patron](https://www.wowhead.com/cata/quest=9457/an-unusual-patron) 

## Wowhead link

https://www.wowhead.com/cata/quest=26340/the-hunt

## Questie & WoW version

Cata Classic
Questie 10.3.7

**Comment by Sommos** [comment]
https://github.com/Questie/Questie/commit/7bb549300eedc43d90c137167fc5a13922965b25
