### ISSUE TITLE
Quest Issue - Priestess Hu'Rala (Cata Classic)

### ISSUE THREAD

**Issue by coldpasta123** [Questie/Questie#6288]
## Description

Showing as available before pre-quests are completed. Requires [Bloodlord Mandokir](https://www.wowhead.com/cata/quest=26334/bloodlord-mandokir)

## Wowhead link

https://www.wowhead.com/cata/quest=26350/priestess-hurala

## Questie & WoW version

Cata Classic
Questie 10.3.7

**Comment by BreakBB** [comment]
Thanks you @coldpasta123 for all these issue report! They are appreciated 🙏🏻

**Comment by Sommos** [comment]
https://github.com/Questie/Questie/commit/d9c21f35c7720adb4710be20dc24204597d78e50

Yes, thank you @coldpasta123. Your reports have been so useful!
