### ISSUE TITLE
Quest Issue - Tiger Mastery (Cata Classic)

### ISSUE THREAD

**Issue by coldpasta123** [Questie/Questie#6291]
## Description

Map markers for quest targets are in the wrong place (Wowhead is also wrong) - see pic (around red circled area)

## Wowhead link

https://www.wowhead.com/cata/quest=188/tiger-mastery

## Screenshots

![image](https://github.com/user-attachments/assets/c222754d-245f-4829-9f0c-c85fd6feccfb)
## Questie & WoW version

Cata Classic
Questie 10.3.7

**Comment by coldpasta123** [comment]
@BreakBB @Sommos (sorry for tag) this issue is one of several misplaced objective quests that I want to fix. I thought this would be a simple one to start with (single NPC, no pathing), but I'm struggling to get my head around it.

cataNpcDB.lua lists the location of Sin'Dall (npc id 729) as {[5339]={{42.93,21.56}}}. However, the coords where I'm currently seeing the quest marker in the screenshot above is around {31.74,15.85}. I worry that simply changing the coords won't fix the problem, because the quest marker doesn't seem to be appearing where I think it should (regardless of whether that's the correct location or not).

I think this is something to do with the zone ID and the Cata split of STV into Northern Stranglethorn and Cape of Stranglethorn, because pre-cata the correct coords are {31.74,15.85}.

If you have any insight I'd appreciate the help please :)

**Comment by Cabro** [comment]
Try with `[33]={{32.21,17.39}}` tell me if it fixes your issue
