### ISSUE TITLE
Quest Issue - Venture Company Mining (Cata Classic)

### ISSUE THREAD

**Issue by coldpasta123** [Questie/Questie#6293]
## Description

Showing as available before pre-quests are completed. Requires [The Mosh'Ogg Bounty](https://www.wowhead.com/cata/quest=26399/the-moshogg-bounty)

## Wowhead link

https://www.wowhead.com/cata/quest=26403/venture-company-mining

## Questie & WoW version

Cata Classic
Questie 10.3.7

**Comment by BreakBB** [comment]
Let's keep this open till #6315 is merged 😁
