### ISSUE TITLE
Quest Issue - There's Somebody Out There Who Wants It (Cata Classic)

### ISSUE THREAD

**Issue by coldpasta123** [Questie/Questie#6302]
## Description

Showing as available before pre-quests are completed. Requires [If They're Just Going to Leave Them Lying Around...
](https://www.wowhead.com/cata/quest=26450/if-theyre-just-going-to-leave-them-lying-around) and [Akiris By The Bundle
](https://www.wowhead.com/cata/quest=26487/akiris-by-the-bundle)

## Wowhead link

https://www.wowhead.com/cata/quest=26493/theres-somebody-out-there-who-wants-it

## Questie & WoW version

Cata Classic
Questie 10.3.7

**Comment by Sommos** [comment]
https://github.com/Questie/Questie/commit/790a91de63d0dc9ad2f51e7bf5d2dc20d77039f9
