### ISSUE TITLE
Quest Issue - Chabal (Cata Classic)

### ISSUE THREAD

**Issue by coldpasta123** [Questie/Questie#6304]
## Description

Showing as available before pre-quests are completed. Requires [There's Somebody Out There Who Wants It
](https://www.wowhead.com/cata/quest=26493/theres-somebody-out-there-who-wants-it)

## Wowhead link

https://www.wowhead.com/cata/quest=26495/chabal

## Questie & WoW version

Cata Classic
Questie 10.3.7

**Comment by Sommos** [comment]
https://github.com/Questie/Questie/commit/07e3a8385661a7d337260df401ba1c450d3d9f6f
