### ISSUE TITLE
Quest Issue - Wailing Caverns Unavailable Quests (Cata Classic)

### ISSUE THREAD

**Issue by coldpasta123** [Questie/Questie#6306]
## Description

All quests below removed from the game in Cata

## Wowhead link

https://www.wowhead.com/cata/quest=914/leaders-of-the-fang
https://www.wowhead.com/cata/quest=1490/nara-wildmane
https://www.wowhead.com/cata/quest=1489/hamuul-runetotem
https://www.wowhead.com/cata/quest=962/serpentbloom
https://www.wowhead.com/cata/quest=1486/deviate-hides

## Questie & WoW version

Cata Classic
Questie 10.3.7

**Comment by Sommos** [comment]
https://github.com/Questie/Questie/commit/f5214d2907921c3026a48b4038b6df9b630e294b
