### ISSUE TITLE
Quest Issue for quest 27315 - Grimtotem Chiefs: Isha Gloomaxe (Thousand Needles, Cataclysm Classic)

### ISSUE THREAD

**Issue by SagittaryX** [Questie/Questie#6308]
## Description
Quest appears prematurely, has prerequisite

## Wowhead link
Quest: https://www.wowhead.com/cata/quest=27315/grimtotem-chiefs-isha-gloomaxe
Prerequisite: https://www.wowhead.com/cata/quest=27275/together-again

## Questie & WoW version
Questie v10.3.7 & Cataclysm Classic

**Comment by Sommos** [comment]
https://github.com/Questie/Questie/commit/c667a0cf4aa1a30923be0ba81e911437a78e3b6d
