### ISSUE TITLE
Quest Issue for quest 27310 - No Weapons For You! (Thousand Needles, Cataclysm Classic)

### ISSUE THREAD

**Issue by SagittaryX** [Questie/Questie#6309]
## Description
Quest appears prematurely, has prerequisite

## Wowhead link
Quest: https://www.wowhead.com/cata/quest=27310/no-weapons-for-you
Prerequisite: https://www.wowhead.com/cata/quest=27275/together-again

## Questie & WoW version
Questie v10.3.7 & Cataclysm Classic

**Comment by Sommos** [comment]
https://github.com/Questie/Questie/commit/63eeadaa9e0723a3c1e79727e2f8798d868f06af
