### ISSUE TITLE
Quest Issue for quest 27312 - Darkcloud Grimtotem (Thousand Needles, Cataclysm Classic)

### ISSUE THREAD

**Issue by SagittaryX** [Questie/Questie#6310]
## Description
Quest appears prematurely, has prerequisite

## Wowhead link
Quest: https://www.wowhead.com/cata/quest=27312/darkcloud-grimtotem
Prerequisite: https://www.wowhead.com/cata/quest=27275/together-again

## Questie & WoW version
Questie v10.3.7 & Cataclysm Classic

**Comment by Sommos** [comment]
https://github.com/Questie/Questie/commit/0a9235261b450708915b03a14a831b6b64828428
