### ISSUE TITLE
Quest Issue for quest 60980 - The Drums of War (Thousand Needles, Cataclysm Classic)

### ISSUE THREAD

**Issue by SagittaryX** [Questie/Questie#6311]
## Description
Quest appears prematurely, has prerequisite

## Wowhead link
Quest: https://www.wowhead.com/cata/item=60980/the-drums-of-war
Prerequisite: https://www.wowhead.com/cata/quest=27317/the-rattle-of-bones

## Questie & WoW version
Questie v10.3.7 & Cataclysm Classic

**Comment by Sommos** [comment]
@SagittaryX Sorry, but the quest you have linked is an item. Do you know if this affects both Alliance and Horde quests or just one?

Horde:
https://www.wowhead.com/cata/quest=27326/the-drums-of-war

Alliance:
https://www.wowhead.com/cata/quest=27325/the-drums-of-war

**Comment by SagittaryX** [comment]
@Sommos I don't know if it affects both, I only did it as Alliance. I imagine the quest tree design is the same for both factions, but again haven't checked.
