### ISSUE TITLE
Quest Issue for quest 27321 - The Writ of History (Thousand Needles, Cataclysm Classic)

### ISSUE THREAD

**Issue by SagittaryX** [Questie/Questie#6312]
## Description
Quest appears prematurely, has prerequisite

## Wowhead link
Quest: https://www.wowhead.com/cata/quest=27321/the-writ-of-history
Prerequisite: https://www.wowhead.com/cata/quest=27317/the-rattle-of-bones

## Questie & WoW version
Questie v10.3.7 & Cataclysm Classic

**Comment by Sommos** [comment]
https://github.com/Questie/Questie/commit/1c7c0b872d10a0c1db9efaf25d32e6e7d92acd0c
