### ISSUE TITLE
Quest Issue for quest 27357 - The Captive Bride (Thousand Needles, Cataclysm Classic)

### ISSUE THREAD

**Issue by SagittaryX** [Questie/Questie#6313]
## Description
Quest appears prematurely, has prerequisite

## Wowhead link
Quest: https://www.wowhead.com/cata/quest=27357/the-captive-bride
Prerequisite: https://www.wowhead.com/cata/quest=27327/grimtotem-chiefs-the-chief-of-chiefs

## Questie & WoW version
Questie v10.3.7 & Cataclysm Classic

**Comment by Sommos** [comment]
https://github.com/Questie/Questie/commit/41a4e458baf4b037601ca22b45d8966cfb208b54
