### ISSUE TITLE
 Missing Quest IDs 83713 and 83714 in Questie v3.4.3 for WoW Classic

### ISSUE THREAD

**Issue by fireplace1124** [Questie/Questie#6314]
**Description:**

Hello,

I am using Questie version 3.4.3 in World of Warcraft Classic (WoW Classic), and I have noticed that two quest IDs are missing from the addon. The specific quests are:

- Quest ID 83713
- Quest ID 83714

These quests are not appearing in the Questie database, which makes it difficult to track and complete them. Could you please add these quests to the Questie database in the next update?

Questie version:
10.3.7

Thank you for your hard work and dedication to improving the Questie addon.

Best regards,  
A player from China.

**Comment by BreakBB** [comment]
Leaving these links here:

https://www.wowhead.com/wotlk/quest=78752/proof-of-demise-titan-rune-protocol-gamma
https://www.wowhead.com/wotlk/quest=78753/proof-of-demise-threats-to-azeroth

**Comment by BreakBB** [comment]
@BrandonJack9 new issue number, same problem as with the other issue 😁

**Comment by Cabro** [comment]
I cannot read chinese. Which one is which id?

**Comment by fireplace1124** [comment]
These quests are daily quests given by Archmage Lan'dalock at the entrance of The Violet Hold. The quests require players to obtain quest items from the final bosses of the Heroic and Alpha versions of the instance.

I apologize for any confusion, as I was unaware that these quest IDs do not exist in the English client. Additionally, the weekly raid quests are functioning correctly.

**Comment by Cabro** [comment]
What is their name?

Do you still have the old version of the daily quests - the links above?

**Comment by fireplace1124** [comment]
> Leaving these links here:在此处留下以下链接：
> 
> https://www.wowhead.com/wotlk/quest=78752/proof-of-demise-titan-rune-protocol-gamma https://www.wowhead.com/wotlk/quest=78753/proof-of-demise-threats-to-azeroth

These are the two quest links. Thank you very much

**Comment by Cabro** [comment]
Do you still have the old version of the daily quests - the links above?

**Comment by fireplace1124** [comment]
I apologize, but I don't have the old version of the daily quests anymore. The missing quest IDs 83713 and 83714 in the Chinese client are the same as the ones mentioned in the two links above. It seems Blizzard has changed their quest IDs in the Chinese client.

If there's anything I can do to help with identifying the correct quest IDs or content, please let me know. I can test and provide feedback from the Chinese client.

**Comment by Cabro** [comment]
Thank you, that's all i needed :)

**Comment by Cabro** [comment]
There is one thing you can help me with.
I need the exact quest title, as it's written in your quest log, and also the exact objectives text as it's written in the quest log.

![image](https://github.com/user-attachments/assets/2f6a6711-65e1-4bc9-8821-5a55ec3ca276)
This is where you need to look.

I could really use a written text so i know what to write so it shows the title and objective in chinese, since it's only those servers that have them.

**Comment by fireplace1124** [comment]
OK.
<img width="302" alt="2024-07-25_23-18-55" src="https://github.com/user-attachments/assets/75dd64d9-9c24-4449-853c-433c3e9aafd4">
It's 83713.

## 死亡证明：泰坦符文协议阿尔法
达拉然的大法师兰达洛克要你从任意地下城的最终首领处取回污染者的勋章。

该任务必须在泰坦符文协议阿尔法难度的地下城中完成。

污染者的勋章：0/1

## 描述
不能让巫妖王的势力继续蔓延了！

六人议会已经作出决定，任何足够强大的斗士都应当拿起武器，保护艾泽拉斯的安全！

<img width="297" alt="2024-07-25_23-19-03" src="https://github.com/user-attachments/assets/28cf640c-38d5-4a0f-8fa8-e7b08ea7a086">
It's 83714.

## 死亡证明：泰坦符文协议阿尔法
达拉然的大法师兰达洛克要你从任意地下城的最终首领处取回神秘的古器。

该任务必须在英雄难度的地下城中完成。

神秘的古器：0/1

## 描述
我们必须在所有阵线上齐头并进！

六人议会已经作出决定，任何足够强大的斗士都应当拿起武器，保护艾泽拉斯的安全！

**Comment by Cabro** [comment]
Thank you, i pushed these fixes, should be up with next version
