### ISSUE TITLE
(SOD) Issued Quests Journey (remaining)

### ISSUE THREAD

**Issue by Arccai** [Questie/Questie#6317]
**_Questie Version 10.3.7_**

**Felwood**
https://www.wowhead.com/classic/quest=8467/feathers-for-nafien **(REMOVED)**
https://www.wowhead.com/classic/quest=84777/feathers-for-nafien **(REPLACED)** - Repeatable/Turn-in

**Orgrimmar**
https://www.wowhead.com/classic/quest=8276/taking-back-silithus **(NO QUEST GIVER)**
https://www.wowhead.com/classic/quest=8367/for-great-honor **(SHOULD BE IN BATTLEGROUNDS/WSG)**
https://www.wowhead.com/classic/quest=8388/for-great-honor **(SHOULD BE IN BATTLEGROUNDS/WSG/REPEATABLES)**

**Tanaris**
https://www.wowhead.com/classic/quest=8182/the-hand-of-rastakhan **(REMOVED ALONG WITH PRE-QUESTS)**

**The Barrens**
https://www.wowhead.com/classic/quest=78909/shifting-scale-talisman **(PRO-REQUIREMENT)**

**Un'Goro Crater**
https://www.wowhead.com/classic/quest=4148/bloodpetal-zapper **(REMOVED)**

**Ironforge**
https://www.wowhead.com/classic/quest=84201/saving-the-best-for-last **(SHOWN AS HORDE / WARLOCK)**

**Stranglethorn Vale**
https://www.wowhead.com/classic/quest=8183/the-heart-of-hakkar **(NOT RELEASED)**

**Swamp of Sorrows**
https://www.wowhead.com/classic/quest=3374/the-essence-of-eranikus **(REMOVED)**
https://www.wowhead.com/classic/quest=3512/in-eranikus-own-words **(REMOVED)**

**The Hinterlands**
https://www.wowhead.com/classic/quest=84016/more-moondragon-scales **(SHOULD BE IN FERALAS/REPEATABLES)**
https://www.wowhead.com/classic/quest=84015/more-greater-moonstones **(SHOULD BE IN FERALAS/REPEATABLES)**
https://www.wowhead.com/classic/quest=84014/more-moonroot **(SHOULD BE IN FERALAS/REPEATABLES)**

https://www.wowhead.com/classic/quest=84013/more-starshells **(SHOULD BE IN REPEATABLES)**
https://www.wowhead.com/classic/quest=84012/more-starsilver-ore **(SHOULD BE IN REPEATABLES)**
https://www.wowhead.com/classic/quest=84011/more-star-lotus **(SHOULD BE IN REPEATABLES)**

**Gnomeregan**
https://www.wowhead.com/classic/quest=81974/more-junk-for-ziri **(SHOULD FLAGGED AS GNOMEREGAN QUEST)**

**Blackrock Depths**
https://www.wowhead.com/classic/quest=82062/ever-after **(SHOULD FLAGGED AS BLACKROCK DEPTHS QUEST)**

**Comment by BreakBB** [comment]
> The Hinterlands
> https://www.wowhead.com/classic/quest=84016/more-moondragon-scales (SHOULD BE IN FERALAS/REPEATABLES)
> https://www.wowhead.com/classic/quest=84015/more-greater-moonstones (SHOULD BE IN FERALAS/REPEATABLES)
> https://www.wowhead.com/classic/quest=84014/more-moonroot (SHOULD BE IN FERALAS/REPEATABLES)
>
> https://www.wowhead.com/classic/quest=84013/more-starshells (SHOULD BE IN REPEATABLES)
> https://www.wowhead.com/classic/quest=84012/more-starsilver-ore (SHOULD BE IN REPEATABLES)
> https://www.wowhead.com/classic/quest=84011/more-star-lotus (SHOULD BE IN REPEATABLES)

Fixed in 9e78fcd2d629adf7fd77373b061fba1d67ba796c

> Ironforge
> https://www.wowhead.com/classic/quest=84201/saving-the-best-for-last (SHOWN AS HORDE / WARLOCK)

Fixed in 9ee8c28d923672df0e70202478c71255c5271d39

> Felwood
> https://www.wowhead.com/classic/quest=8467/feathers-for-nafien (REMOVED)
> https://www.wowhead.com/classic/quest=84777/feathers-for-nafien (REPLACED) - Repeatable/Turn-in

Fixed in 4bc6bbc216c9c67cde302c92c8ec7f3193d987b7

**Comment by BreakBB** [comment]
> Orgrimmar
> https://www.wowhead.com/classic/quest=8276/taking-back-silithus (NO QUEST GIVER)

No clue what you mean, but it has a quest giver in the DB.

> https://www.wowhead.com/classic/quest=8367/for-great-honor (SHOULD BE IN BATTLEGROUNDS/WSG)
Nope, that is a quest of Orgrimmar (as you can also see in the wowhead category).

> https://www.wowhead.com/classic/quest=8388/for-great-honor (SHOULD BE IN BATTLEGROUNDS/WSG/REPEATABLES)
Same as above and also the quest is already marked as repeatable and therefore should be placed correctly 🤔

**Comment by BreakBB** [comment]
Everything on the list is fixed except for Shifting Scale Talisman -> #5397
