### ISSUE TITLE
(SOD) BWL Quests not released yet.

### ISSUE THREAD

**Issue by Arccai** [Questie/Questie#6321]
https://www.wowhead.com/classic/quest=7784/the-lord-of-blackrock
https://www.wowhead.com/classic/quest=7783/the-lord-of-blackrock

Not yet released in SOD (phase 4)

**Comment by Sommos** [comment]
https://github.com/Questie/Questie/commit/5fd1a4efff6bdfba587e8ab6e1a0a16aea82682f
