### ISSUE TITLE
Quest Issue - Nessingwary Will Know (Cata)

### ISSUE THREAD

**Issue by coldpasta123** [Questie/Questie#6324]
## Description

Error - missing quest objective
https://www.wowhead.com/cata/quest=29223/nesingwary-will-know

There isn't actually an objective for this quest, and the turn in is correctly marked

## Wowhead link

https://www.wowhead.com/cata/quest=29223/nesingwary-will-know
Also: https://www.wowhead.com/cata/quest=29105/nesingwary-will-know

Not sure why there are 2

**Comment by coldpasta123** [comment]
![image](https://github.com/user-attachments/assets/596201c8-1725-4a3f-a796-6ee5994b75bc)

**Comment by coldpasta123** [comment]
Seems to be fixed already

**Comment by BreakBB** [comment]
Fixed in a8abb706b183477ff859a2410db30d233daa29ce
