### ISSUE TITLE
Quest Issue - To Hardwrench Hideaway (Cata)

### ISSUE THREAD

**Issue by coldpasta123** [Questie/Questie#6325]
## Description

Objective marker incorrectly placed (see pic)

## Wowhead link

https://www.wowhead.com/cata/quest=29236/to-hardwrench-hideaway

## Screenshots

![image](https://github.com/user-attachments/assets/ba1ddf20-8b1a-4f53-869c-c032b9234ef2)

**Comment by Cabro** [comment]
If you look at the bottom of the NPC fixes, you'll see something ;)

**Comment by BreakBB** [comment]
Fixed in a8abb706b183477ff859a2410db30d233daa29ce
