### ISSUE TITLE
Quest Issue - Bad Supplies (Cata)

### ISSUE THREAD

**Issue by coldpasta123** [Questie/Questie#6327]
## Description

No quest marker
## Wowhead link

https://www.wowhead.com/cata/quest=29238/bad-supplies

**Comment by Cabro** [comment]
Did you update questie?

**Comment by coldpasta123** [comment]
@Cabro I had a look and think this has been fixed now. Do you agree?

**Comment by BreakBB** [comment]
Fixed in a8abb706b183477ff859a2410db30d233daa29ce
