### ISSUE TITLE
childQuests need polishing of exclusiveTo

### ISSUE THREAD

**Issue by Cabro** [Questie/Questie#6332]
![image](https://github.com/user-attachments/assets/5ed77c02-c087-4b69-9a0c-4f3b5e81aa92)
![image](https://github.com/user-attachments/assets/cb313343-1e83-461c-a883-cde25566a93a)

This needs polishing, Questie shows a quest that is exclusiveTo another quest in quest log as available to take.

**Comment by BreakBB** [comment]
This was caused by inconsistent parent-child relations.

We added a new validation in 25cb075fe9f9c8ca2c94bc968eb0b100d04d9782 and 338c47665009fa3096f425d8b4f1caef4ef3a166. And fixed the data issue in 1c4575e83ae38182857bcd98e0eab21a8d023198
