### ISSUE TITLE
Error during Initialization!

### ISSUE THREAD

**Issue by Zexduh** [Questie/Questie#6334]
## Bug description

Well the bug itself says Error during initialization! interface/addons/questie/modules/questielnit.lua:281: attempt to call method 'initialize' ( a nil value) idk what it is, but it was working earlier then just randomly stopped.

## Screenshots

![image_2024-08-02_161353947](https://github.com/user-attachments/assets/6dc73597-3960-4698-aeda-994503be1bd7)

## Questie & WoW version
V10.3.9

**Comment by sjwoodr** [comment]
Same version for me.  Same error.  Actually updated today and the problem has now started.  Others in my guild see it, but not everyone.

**Comment by Yopie2014** [comment]
Also having this issue.

Error during installation! Interface/Addons/Questie/Modules/QuestieInit.lua:281: attempt to call method 'Initialize' (a nil value)

Updated today and have tried uninstalled, tried previous versions, launched with just questie, updated overwolf and curseforge. Not sure what the issue is.

**Comment by Sannananas** [comment]
I am having the same issue and now older versions are not working either :(

**Comment by Zexduh** [comment]
Sadness. Hope it gets fixed. Hate doing quest without it =c

**Comment by KG6211** [comment]
Bump, same issue here

**Comment by Moestifer** [comment]
Also having this same issue as of 03/08/24

**Comment by scrubnoobwow** [comment]
Additional LUA error:
`/Questie/Modules/Tracker/TrackerQuestTimers.lua:15: attempt to index global 'QuestTimerFrame' (a nil value)`

Tried slapping `_G.` in front to no avail. Not sure where to find documentation about what it is and where it might have moved

**Comment by Wheaverr** [comment]
Same issue here.

**Comment by xXdhijackXx** [comment]
same here!

**Comment by Thobos** [comment]
also having this issue. rollbacks dont work. fresh install doesn't work. fresh wtf folder doesn't work.

**Comment by olson1124** [comment]
bump, same problem here. hopefully get a fix soon !

**Comment by swearforme** [comment]
+1 same issue here after today's update

**Comment by NotShocked** [comment]
My whole guild is also broken. Seems to be a global issue

**Comment by dissidentz** [comment]
Downgrading to v10.3.8 or v10.3.7 does not fix the issue for me.

**Comment by teelolws** [comment]
To get questie to work again I added this as a workaround to Questie\Modules\Tracker\TrackerQuestTimers.lua

`local QuestTimerFrame = CreateFrame("Frame")`

![image](https://github.com/user-attachments/assets/15c6b691-4a56-4ba2-bf0e-19c3b2f0c55f)

**Comment by FedeC86-10** [comment]
I tried deleting de line 281 of the file and it works

**Comment by xXdhijackXx** [comment]
> I tried deleting de line 281 of the file and it works

tried this then got a questieinit hideblizzardtimer error

**Comment by olson1124** [comment]
> To get questie to work again I added this as a workaround to Questie\Modules\Tracker\TrackerQuestTimers.lua
> 
> `local QuestTimerFrame = CreateFrame("Frame")`
> 
> ![image](https://private-user-images.githubusercontent.com/49792789/354759046-15c6b691-4a56-4ba2-bf0e-19c3b2f0c55f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2NDI2NDgsIm5iZiI6MTcyMjY0MjM0OCwicGF0aCI6Ii80OTc5Mjc4OS8zNTQ3NTkwNDYtMTVjNmI2OTEtNGE1Ni00YmEyLWJmMGUtMTljM2IyZjBjNTVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAyVDIzNDU0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiYjA4OWU0Zjg2ZjQ0YWQ5NWJkNjg1N2MyMzE3N2QzNmMxMzJlMjc5Yzg2ZGM3ZWM2NDU4ODQ3MTE1NzRlOTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rreVSSH7oFn9vKZAHUJ9nteUkXmek3w0iJWExPAsQPA)

works. thank you!

**Comment by kmann93** [comment]
> [teelolws](/teelolws)

this worked. thanks wizard

**Comment by xXdhijackXx** [comment]
> To get questie to work again I added this as a workaround to Questie\Modules\Tracker\TrackerQuestTimers.lua
> 
> `local QuestTimerFrame = CreateFrame("Frame")`
> 
> ![image](https://private-user-images.githubusercontent.com/49792789/354759046-15c6b691-4a56-4ba2-bf0e-19c3b2f0c55f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2NDI4NTksIm5iZiI6MTcyMjY0MjU1OSwicGF0aCI6Ii80OTc5Mjc4OS8zNTQ3NTkwNDYtMTVjNmI2OTEtNGE1Ni00YmEyLWJmMGUtMTljM2IyZjBjNTVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAyVDIzNDkxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2MTE2N2RjZTdlNjhlYTEwMjNmYjMyMzQzOWFhZjU1NDFmYzgxZjBlYjk3ZWM3NDkwZDMzNTAwMGEyYjk3MGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-wKBABbLF53EBQraaiW1CZP6HGT_Vmw6ptzSrkobF5c)

thank you!

**Comment by fukcyall** [comment]
> To get questie to work again I added this as a workaround to Questie\Modules\Tracker\TrackerQuestTimers.lua
> 
> `local QuestTimerFrame = CreateFrame("Frame")`
> 
> ![image](https://private-user-images.githubusercontent.com/49792789/354759046-15c6b691-4a56-4ba2-bf0e-19c3b2f0c55f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2NDI5MTEsIm5iZiI6MTcyMjY0MjYxMSwicGF0aCI6Ii80OTc5Mjc4OS8zNTQ3NTkwNDYtMTVjNmI2OTEtNGE1Ni00YmEyLWJmMGUtMTljM2IyZjBjNTVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAyVDIzNTAxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjNTEzMTVmMzc3MDU3ZWU3MzdjNzc2ODFlMWQ4MGExMTVjNDQxZTdjNGYzNjExMWQwMGU4ZWZhZjQ0OWNiNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lNMPab1JOHUSN42fsRUXdcv7d4KDkM8bo4pMhhWuqkw)
that works! thanks!

**Comment by Bigjosh11** [comment]
Same issue for me.

**Comment by Moestifer** [comment]
> To get questie to work again I added this as a workaround to Questie\Modules\Tracker\TrackerQuestTimers.lua
> 
> `local QuestTimerFrame = CreateFrame("Frame")`
> 
> ![image](https://private-user-images.githubusercontent.com/49792789/354759046-15c6b691-4a56-4ba2-bf0e-19c3b2f0c55f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2NDMwNjksIm5iZiI6MTcyMjY0Mjc2OSwicGF0aCI6Ii80OTc5Mjc4OS8zNTQ3NTkwNDYtMTVjNmI2OTEtNGE1Ni00YmEyLWJmMGUtMTljM2IyZjBjNTVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAyVDIzNTI0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0NGY4N2VmOGFmYzNlMGQ3NGJlZGY3NWViZTc1MTc2MmUxMjNlOTc5MzgyNDI4YzEzNjg3YmJlNzk1ZjVmNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tJBz3EFm9VIVxT60BmzmrQZx4ESCoCQ53bAv0V6yqqs)




This has worked a treat. TYVM kind sir!

**Comment by Squeaksqt** [comment]
> local QuestTimerFrame = CreateFrame("Frame")

BRO TY

**Comment by Bigjosh11** [comment]
> > To get questie to work again I added this as a workaround to Questie\Modules\Tracker\TrackerQuestTimers.lua
> > `local QuestTimerFrame = CreateFrame("Frame")`
> > ![image](https://private-user-images.githubusercontent.com/49792789/354759046-15c6b691-4a56-4ba2-bf0e-19c3b2f0c55f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2NDI4NTksIm5iZiI6MTcyMjY0MjU1OSwicGF0aCI6Ii80OTc5Mjc4OS8zNTQ3NTkwNDYtMTVjNmI2OTEtNGE1Ni00YmEyLWJmMGUtMTljM2IyZjBjNTVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAyVDIzNDkxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2MTE2N2RjZTdlNjhlYTEwMjNmYjMyMzQzOWFhZjU1NDFmYzgxZjBlYjk3ZWM3NDkwZDMzNTAwMGEyYjk3MGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-wKBABbLF53EBQraaiW1CZP6HGT_Vmw6ptzSrkobF5c)
> 
> thank you!

Thanks this fixed mine!

**Comment by Wheaverr** [comment]
> To get questie to work again I added this as a workaround to Questie\Modules\Tracker\TrackerQuestTimers.lua
> 
> `local QuestTimerFrame = CreateFrame("Frame")`
> 
> ![image](https://private-user-images.githubusercontent.com/49792789/354759046-15c6b691-4a56-4ba2-bf0e-19c3b2f0c55f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2NDM0MTEsIm5iZiI6MTcyMjY0MzExMSwicGF0aCI6Ii80OTc5Mjc4OS8zNTQ3NTkwNDYtMTVjNmI2OTEtNGE1Ni00YmEyLWJmMGUtMTljM2IyZjBjNTVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAyVDIzNTgzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2NWFlNDYxMTMyZjc3NDk1YzdjYjcxYWI0Y2Q1OGZkMGEwMDY1M2FmNjRjNmRlODhkNDFiNWYwMTdjMGIyNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KOzUSAGwttu9HkPM5XplbRyfZQfpgBhj7BVXgLH25Rc)

You rock! Thanks for the fix :)

**Comment by Thobos** [comment]
> To get questie to work again I added this as a workaround to Questie\Modules\Tracker\TrackerQuestTimers.lua
> 
> `local QuestTimerFrame = CreateFrame("Frame")`
> 
> ![image](https://private-user-images.githubusercontent.com/49792789/354759046-15c6b691-4a56-4ba2-bf0e-19c3b2f0c55f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2NDM0MTEsIm5iZiI6MTcyMjY0MzExMSwicGF0aCI6Ii80OTc5Mjc4OS8zNTQ3NTkwNDYtMTVjNmI2OTEtNGE1Ni00YmEyLWJmMGUtMTljM2IyZjBjNTVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAyVDIzNTgzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2NWFlNDYxMTMyZjc3NDk1YzdjYjcxYWI0Y2Q1OGZkMGEwMDY1M2FmNjRjNmRlODhkNDFiNWYwMTdjMGIyNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KOzUSAGwttu9HkPM5XplbRyfZQfpgBhj7BVXgLH25Rc)

i used notepad to do this and am still getting the error. Suggestions? granted i had the game open.

**Comment by mykeylikesit** [comment]
questie broken
![Screenshot 2024-08-02 170100](https://github.com/user-attachments/assets/2416e202-36a3-469b-b197-e82f4b56dfd0)

**Comment by xXdhijackXx** [comment]
> > To get questie to work again I added this as a workaround to Questie\Modules\Tracker\TrackerQuestTimers.lua
> > `local QuestTimerFrame = CreateFrame("Frame")`
> > ![image](https://private-user-images.githubusercontent.com/49792789/354759046-15c6b691-4a56-4ba2-bf0e-19c3b2f0c55f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2NDM0MTEsIm5iZiI6MTcyMjY0MzExMSwicGF0aCI6Ii80OTc5Mjc4OS8zNTQ3NTkwNDYtMTVjNmI2OTEtNGE1Ni00YmEyLWJmMGUtMTljM2IyZjBjNTVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAyVDIzNTgzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2NWFlNDYxMTMyZjc3NDk1YzdjYjcxYWI0Y2Q1OGZkMGEwMDY1M2FmNjRjNmRlODhkNDFiNWYwMTdjMGIyNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KOzUSAGwttu9HkPM5XplbRyfZQfpgBhj7BVXgLH25Rc)
> 
> i used notepad to do this and am still getting the error. Suggestions? granted i had the game open.

close game first and try editing it with notepad++ or similar to make sure you don't mess up the format.

**Comment by Zexduh** [comment]
> To get questie to work again I added this as a workaround to Questie\Modules\Tracker\TrackerQuestTimers.lua
> 
> `local QuestTimerFrame = CreateFrame("Frame")`
> 
> ![image](https://private-user-images.githubusercontent.com/49792789/354759046-15c6b691-4a56-4ba2-bf0e-19c3b2f0c55f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2NDM4NDgsIm5iZiI6MTcyMjY0MzU0OCwicGF0aCI6Ii80OTc5Mjc4OS8zNTQ3NTkwNDYtMTVjNmI2OTEtNGE1Ni00YmEyLWJmMGUtMTljM2IyZjBjNTVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAzVDAwMDU0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4Yzk1NzFjNmQ5YjQ5ZTgzNTk0NWQ0NmFiNTdiZTA5Y2ZjYTBiYzUxMTljMTM3NWY1MDU4YTY2YTU3N2M0MTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OqG9P0D_cGNEBVUoiLXM5Cjyx2XaEmQndj2P_W_AiyU)

the savior. Ill try after my Tft game

**Comment by 0msa** [comment]
Xdp is also having this issue

**Comment by mykeylikesit** [comment]
yeah im not going to mess with it, i have no idea

**Comment by tcrosen** [comment]
Can also _temporarily_ fix by doing the following:

1. Comment out line 281 in `C:\Program Files (x86)\World of Warcraft\_classic_era_\Interface\AddOns\Questie\Modules\QuestieInit.lua`

   ```lua
   --TrackerQuestTimers:Initialize()
   ```

2. Comment out lines 1848-1852 in `C:\Program Files (x86)\World of Warcraft\_classic_era_\Interface\AddOns\Questie\Modules\Tracker\QuestieTracker.lua`

  ```lua
    -- if Questie.db.profile.showBlizzardQuestTimer then
    --     TrackerQuestTimers:ShowBlizzardTimer()
    -- else
    --     TrackerQuestTimers:HideBlizzardTimer()
    -- end
```

3. `/reload`

**Comment by MyTechnoHunter** [comment]
The fix is incoming.

Little patience now, lot less headache later!

**Comment by BreakBB** [comment]
Fix is pushed and will be released in a few minutes
