### ISSUE TITLE
Classic Wow + SoM: Failed to initialise

### ISSUE THREAD

**Issue by chitii33** [Questie/Questie#6342]
<img width="822" alt="Screenshot 2024-08-03 at 01 25 44" src="https://github.com/user-attachments/assets/fbfbef8e-c15a-4048-9f80-50903932da12">

I have tried downloading different versions of Questie and still the same...

**Comment by MyTechnoHunter** [comment]
Little bit of patience,  curseforge takes a minute to roll out or you can go to the latest release tag on the GitHub here and manually download it
