### ISSUE TITLE
Questie Issue

### ISSUE THREAD

**Issue by rinneh** [Questie/Questie#6343]
## Bug description

Questie is currently not loading at all. I am playing WoW Classic. I keep receiving the following LUA error:

Message: ...ddOns/Questie/Modules/Tracker/TrackerQuestTimers.lua:15: attempt to index global 'QuestTimerFrame' (a nil value)
Time: Fri Aug  2 20:28:36 2024
Count: 1
Stack: ...ddOns/Questie/Modules/Tracker/TrackerQuestTimers.lua:15: attempt to index global 'QuestTimerFrame' (a nil value)

## Screenshots

![image](https://github.com/user-attachments/assets/f1975538-3529-4031-b373-c61bf9b958c6)
![image](https://github.com/user-attachments/assets/f3022a53-31c9-499b-bfbd-1cb7307b207d)

## Questie & WoW version
 10.3.9 
Classic Era/SoD

**Comment by MyTechnoHunter** [comment]
See issue #6342
