### ISSUE TITLE
Quest Issue - The Black Shield (Classic Era)

### ISSUE THREAD

**Issue by Redwolf4345** [Questie/Questie#6346]
## Description
The tooltip for quest "The Black Shield" (ID 1322) for Horde in Dustwallow Marsh shows a requirement of 5 Acidic Venom Sacs when 6 are required for quest turnin.

## Wowhead link
https://www.wowhead.com/classic/quest=1322/the-black-shield

## Screenshots
![image](https://github.com/user-attachments/assets/d3d613fc-1195-4887-bf79-a0724537abfc)

## Questie & WoW version
V10.3.10, SOD Classic Era

**Comment by Cabro** [comment]
Fixed in https://github.com/Questie/Questie/commit/06d69ce8bbb4608ed26ce88e6a2960113ab24910
