### ISSUE TITLE
Questie error

### ISSUE THREAD

**Issue by prtyricky** [Questie/Questie#6347]
Good evening! So I have verified that I am running the most current update (v10.3.10) and am still receiving the Error During Initialization message when I log into game. I tried everything I could find online to fix it but nothings working, could really use some help. Love your product, keep up the hard work!
![Screenshot (26)](https://github.com/user-attachments/assets/3d661cac-87c3-4fa0-adb6-a249bb9a0d0c)

**Comment by MyTechnoHunter** [comment]
Game version?
Screenshot your curseforge client roo please and thanks

**Comment by ApertureBear** [comment]
I had the same issue. Looks like they pushed an update in like the last hour. Updating to v10.3.10 resolved the issue.

**Comment by MyTechnoHunter** [comment]
Er... juuuust to be sure.. actual questie version is?

**Comment by prtyricky** [comment]
![Screenshot (70)](https://github.com/user-attachments/assets/e54ec815-47a3-43b6-bbcf-ab897e976705)

This is a screenshot of the curseforge client, it is currently in version 10.3.10

**Comment by MyTechnoHunter** [comment]
Few things..
1) update curseforge client 
2) make sure path for classic (upper right corner drop-down) is not meaning cata instead of SoD
Check addon list in game for questie version

**Comment by prtyricky** [comment]
> Game version? Screenshot your curseforge client too please and thanks

![Screenshot (70)](https://github.com/user-attachments/assets/2e5cc3e6-caf2-4b64-acf1-3bcf34f68a2c)

Here's the screenshot of the curseforge app, the current version is 10.3.10

**Comment by ApertureBear** [comment]
I don't know anything about anything, I'm just saying that I had what appears to be the exact same issue, and fully deleting the questie folder and installing v10.3.10 resolved the issue for me. Good luck folks!

**Comment by prtyricky** [comment]
> Few things..
> 
> 1. update curseforge client
> 2. make sure path for classic (upper right corner drop-down) is not meaning cata instead of SoD
>    Check addon list in game for questie version

Ahhhh I had to set the path to Classic 2, worked like a charm! Thank you for the help!

**Comment by prtyricky** [comment]
> I don't know anything about anything, I'm just saying that I had what appears to be the exact same issue, and fully deleting the questie folder and installing v10.3.10 resolved the issue for me. Good luck folks!

Thanks homie, changing the path worked for me thankfully.

**Comment by MyTechnoHunter** [comment]
> > Few things..
> > 
> > 1. update curseforge client
> > 2. make sure path for classic (upper right corner drop-down) is not meaning cata instead of SoD
> >    Check addon list in game for questie version
> 
> Ahhhh I had to set the path to Classic 2, worked like a charm! Thank you for the help!

Glad you got it working

The same place that you can check the path you can actually rename that drop-down entry for clarity so you can change it from classic 2 to SoD or you can change classic to Cata
