### ISSUE TITLE
Quest Issue - Final Delivery (Cata - Stonetalon)

### ISSUE THREAD

**Issue by coldpasta123** [Questie/Questie#6378]
## Description

No quest objectives

Use https://www.wowhead.com/cata/npc=41418/kromgar-hot-air-balloon at 51.17, 45.50

## Wowhead link

https://www.wowhead.com/cata/quest=26077/final-delivery

## Questie & WoW version

Cata
Questie 10.3.12

**Comment by TorpedoCXC** [comment]
The coordinates are still missing on the map.

![grafik](https://github.com/user-attachments/assets/fda26538-6eca-4374-b4f1-fcc07b4d52ed)

Questie version 10.4.2

**Comment by coldpasta123** [comment]
Thanks - I seem to have fixed this and then unfixed it. Now fixed again :)
