### ISSUE TITLE
Error on startup, most updated version. 

### ISSUE THREAD

**Issue by Pattfour** [Questie/Questie#6380]
![image](https://github.com/user-attachments/assets/7fd4d84a-8150-4343-a2a7-c18c57fed404)

halp !

**Comment by Cabro** [comment]
Delete your Questie folder and reinstall. This is an install issue.

**Comment by Pattfour** [comment]
I've done that a few times.

**Comment by Cabro** [comment]
Delete the Questie folder in WTF folder also.

**Comment by Pattfour** [comment]
There was none, I deleted the WTF folder entirely. Same error.

**Comment by MyTechnoHunter** [comment]
> ![image](https://private-user-images.githubusercontent.com/100392244/357547548-7fd4d84a-8150-4343-a2a7-c18c57fed404.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1ODY4NTksIm5iZiI6MTcyMzU4NjU1OSwicGF0aCI6Ii8xMDAzOTIyNDQvMzU3NTQ3NTQ4LTdmZDRkODRhLTgxNTAtNDM0My1hMmE3LWMxOGM1N2ZlZDQwNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxM1QyMjAyMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNTQyOTI2YmJmODljNzQ3NTI5OTFmOGI2YjAyM2FjY2VmZTE2NDM4NzFhN2UzYTU0OTBiNTUwYjA0M2FkOTNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4DGzu6VzT7p9mM_DdWonK0MWEaBQ43SFEIUdcTfLrTk)
> 
> halp !

Questie version,  game version?

**Comment by Cabro** [comment]
> There was none, I deleted the WTF folder entirely. Same error.

Then you weren't in the right folder. Make sure you install Questie for the game flavor that you play, you can check it in Curseforge or make sure it is in `World of Warcraft\_classic_`

**Comment by Pattfour** [comment]
I'm certain i was in the right folder. I installed the overwolf app and had it update questie and it worked /shrug. I've been doing it manually since I was a kid /shrug. Thx for taking the time to post. GLHF !

**Comment by Cabro** [comment]
Glad you got it working!
