### ISSUE TITLE
The quest "The Wild Gods" are identified as a Unknown Zone

### ISSUE THREAD

**Issue by HugoBalbino** [Questie/Questie#6409]
## Description
 The quest "The Wild Gods" are identified as a Unknown Zone

## Wowhead link
 https://www.wowhead.com/classic/quest=82043/the-wild-gods

## Screenshots

![Screenshot 2024-08-19 132154](https://github.com/user-attachments/assets/b781fad1-f4f5-4cd4-9895-688b7c3e0ff0)

## Questie & WoW version
 Questie 10.3.12
Classic SoD

**Comment by BreakBB** [comment]
This was just fixed by @BrandonJack9 in 69f5e86b79f8e0a28f0bbb58eb1b3e11ff249100 and 29c966cec0e5ac04c4ba59c4d0a7a630a6f8972c

Thanks for the report @HugoBalbino it will be fixed in the next version 👍🏻
