### ISSUE TITLE
When the task log is opened, the task list cannot be expanded automatically

### ISSUE THREAD

**Issue by wewggfd** [Questie/Questie#6412]
## Bug description

When the task log is opened, the task list cannot be expanded automatically

**Comment by wewggfd** [comment]
![微信图片编辑_20240825171126](https://github.com/user-attachments/assets/0addea31-7bb5-4e2c-8e1f-7f21cf03252a)

**Comment by EKE00372** [comment]
開發者說看不太懂你要表述的問題
你要不要用中文展開詳細說一下？

**Comment by BreakBB** [comment]
Closing this as more information is required. Feel free to answer the questions above @wewggfd if this is still an issue for you.
