### ISSUE TITLE
Tracker often gets desynced with quest log.

### ISSUE THREAD

**Issue by Cabro** [Questie/Questie#6417]
![image](https://github.com/user-attachments/assets/508f32b8-f6e7-44b3-bb1f-12bf5a898b1d)

Here's a case where 1 quest is working (28130), but another quest forgets to update (29433).

**Comment by ThaDanus** [comment]
Same issue here, before updating today I managed to fix it by exiting the game and only logging in to the character I'm questing with, but today this doesn't seem to work anymore, unfortunately.
Questie tracker is not updating with the actual quest progression. Using Questie 10.3.14 on Cataclysm Classic.

![image](https://github.com/user-attachments/assets/a2b89369-abbe-4741-aef6-a08a318d3fb5)

**Comment by Cabro** [comment]
And the thing is that it's only certain quests that suffer from this bug (or feature?). Once the quest fails to update in tracker, it will stay like that while other quests will update properly.
This should be looked into.

**Comment by ThaDanus** [comment]
Yes, haven't had any issue today while questing.
I'll keep an eye out if other quests update fine when one is borked, have not noticed that yet, but I was trying to fix the broken one too hard for that.

**Comment by Cabro** [comment]
Just a shot in the dark: try to disable All The Things. I noticed i didnt get it anymore without ATT, but it could be i didnt get a quest that doesnt want to be tracked.
Let me know

**Comment by Cabro** [comment]
Call me crazy, but this seems to happen after recompiling. I think it happens until you accept/turn in a quest. Existing quests in log will be borked, but new ones will work.
Not 100% sure, but seems it's related to recompiling

**Comment by ThaDanus** [comment]
I ran a couple of dungeons yesterday while the log was borked on one character. As soon as I disabled ATT everything seemed to work good again, when I turned it on again, borked again. So yeah it's probably related in some way

**Comment by Cabro** [comment]
Absolutely this makes sense. ATT init messes with Questie init and as suck, Questie can't update the existing quests in quest log during world enter.  @BreakBB please look into this, as 90% of players use both addons and this is a thing that needs to be fixed sooner rather than later.

**Comment by BreakBB** [comment]
@ThaDanus If you are familiar with installing addons manually, would you mind testing the version below?

[Questie-v10.3.14-a7a1e1791-fix-desync.zip](https://github.com/user-attachments/files/16939989/Questie-v10.3.14-a7a1e1791-fix-desync.zip)

**Comment by ThaDanus** [comment]
Yes, installed it, will try to get some questing in this week!

**Comment by BreakBB** [comment]
Others reported the version above does not fix the issue. Here is another try to come up with something @ThaDanus 

[Questie-v10.3.14-515e6fcc7-fix-desync.zip](https://github.com/user-attachments/files/16973885/Questie-v10.3.14-515e6fcc7-fix-desync.zip)

**Comment by ThaDanus** [comment]
I did indeed get one out of sync issue, but no others. Will try the new version as well! Thanks for all the hard work.

**Comment by ThaDanus** [comment]
Nope, unfortunately it's still desyncing sometimes.
Logged into 2 banking alts first this morning before moving on to quest, and it's desynced.
![image](https://github.com/user-attachments/assets/ad6c9a95-a4cc-4b94-9d64-c0c7d02e4814)

**Comment by BreakBB** [comment]
Hey @ThaDanus we've got another version for you, which at least _improves_ the issue, when not solve it entirely. It would be great if you can test it again!

[Questie-v10.3.16-7f6634731-quest-log-init-debug.zip](https://github.com/user-attachments/files/17095190/Questie-v10.3.16-7f6634731-quest-log-init-debug.zip)

**Comment by ThaDanus** [comment]
Will do!
