### ISSUE TITLE
Can not move Quest Tracker on Screen

### ISSUE THREAD

**Issue by davidcc73** [Questie/Questie#6419]
When pressing shift+control over the tracker, the message about doing a left click to drag is displayed, but when doing it, the tracker does not move.

Classic Era v.1.15.3
Questie Version: 10.3.14

**Comment by Cabro** [comment]
Where does it say shift+control?

**Comment by davidcc73** [comment]
my bad that message is about the resizing, there is no message about the dragging, but no matter the button combination I can not drag it.

**Comment by Cabro** [comment]
Ctrl+drag works for me

**Comment by davidcc73** [comment]
It was still not working, so I tried restarting the game and now it works, so I guess it's solved XD
