### ISSUE TITLE
Bug while clicked on item

### ISSUE THREAD

**Issue by amaxcz** [Questie/Questie#6423]
while questing in eastern plaguelands, got a bug - clicked on the bottle for collecting termites in the quest list
```
1x [ADDON_ACTION_FORBIDDEN] AddOn 'Questie' tried to call the protected function 'UNKNOWN()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: ?
[string "=[C]"]: in function `UseItemByName'
[string "@Blizzard_ChatFrameBase/Classic/ChatFrame.lua"]:1179: in function `SecureCmdUseItem'
[string "@Blizzard_FrameXML/Classic/SecureTemplates.lua"]:420: in function `handler'
[string "@Blizzard_FrameXML/Classic/SecureTemplates.lua"]:633: in function <Blizzard_FrameXML/Classic/SecureTemplates.lua:577>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:491
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:491
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:491
}
event = "ADDON_ACTION_FORBIDDEN"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:557
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:557
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:551
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:566
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:511
}

```

**Comment by Gogo1951** [comment]
Also happens in Classic Era.

1x [ADDON_ACTION_FORBIDDEN] AddOn 'Questie' tried to call the protected function 'UNKNOWN()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: ?
[string "=[C]"]: in function `UseItemByName'
[string "@Blizzard_ChatFrameBase/Classic/ChatFrame.lua"]:1207: in function `SecureCmdUseItem'
[string "@Blizzard_FrameXML/Classic/SecureTemplates.lua"]:399: in function `handler'
[string "@Blizzard_FrameXML/Classic/SecureTemplates.lua"]:612: in function <Blizzard_FrameXML/Classic/SecureTemplates.lua:556>

Locals:
_ = Frame {
}
event = "ADDON_ACTION_FORBIDDEN"
events = <table> {
}

**Comment by BreakBB** [comment]
Hey @amaxcz @Gogo1951

can you tell when exactly this error happens?

Every time you click an item in the tracker?
Only when you are in combat when clicking an item?
... ?

If it happens all the time, it would be great if you could try to disable all addons except Questie and see if the error still happens. The way addons interact with one another and how the game client handles "protected function calls" can result in addons getting blamed for being an issue, while it actually is another addon.

**Comment by Gogo1951** [comment]
Every time I click on an item in Classic Era.

**Comment by Gogo1951** [comment]
Ok, so it seems like it's working again. Probably got hot-fixed on Blizzard's side. Cheers!

**Comment by BreakBB** [comment]
Looking at this again and the stacktrace clearly shows this is Blizzards UI code triggering this, but still blaming Questie.
