### ISSUE TITLE
Map Issue - 

### ISSUE THREAD

**Issue by karlwithak2** [Questie/Questie#6428]
## Questie & WoW version

v ISSUE BELOW v
This is referring to the classic WoW realm on HC mode. A huge discussion today in LFG, trade chat, etc. lead me to write this as it's a global issue with whatever bug made its way into your life-saving creation (Questie, thank you so much for the permanent pillar of cooperation you've made for millions of players).
The in-game map stays blank with nothing at all showing up when you open the interface, unless you disable the addon and /refresh. I'd hate to see other players start using an alternate add-on just because of a small fix they were too impatient to wait for <3
Hope this gets to the right eyes =)

**Comment by BreakBB** [comment]
Merging this with #6429

**Comment by karlwithak2** [comment]
Just to add, people are also having in-game issues with a number of other addons too, not just Questie

**Comment by BreakBB** [comment]
A fix for the Questie issue will be out in the next 15-30 minutes @karlwithak2
