### ISSUE TITLE
Map error after recent Classic Era/HC/SoD update

### ISSUE THREAD

**Issue by HugoBalbino** [Questie/Questie#6429]
## Bug description

465x ...aceBlizzard_MapCanvas/Blizzard_MapCanvas.lua:165: attempt to call method 'OnLoad' (a nil value)
[string "@Blizzard_MapCanvas/Blizzard_MapCanvas.lua"]:165: in function `AcquirePin'
[string "@Questie/Libs/HereBeDragons/HereBeDragons-Pins-2.0.lua"]:469: in function `HandlePin'
[string "@Questie/Libs/HereBeDragons/HereBeDragons-Pins-2.0.lua"]:766: in function `AddWorldMapIconMap'
[string "@Questie/Modules/Map/QuestieMap.lua"]:301: in function <Questie/Modules/Map/QuestieMap.lua:290>

Locals:
self = WorldMapFrame {
 expandedMapInsetsByMapID = <table> {
 }
 pinNudgingDirty = true
 ZoneDropdown = WorldMapZoneDropdown {
 }
 minimizedHeight = 712
 lockReasons = <table> {
 }
 MiniBorderFrame = Frame {
 }
 callbackTables = <table> {
 }
 pinPools = <table> {
 }
 dataProviderEventsCount = <table> {
 }
 mouseClickHandlers = <table> {
 }
 pinTemplateTypes = <table> {
 }
 maximizedWidth = 1024
 maximizedHeight = 768
 activeAreaTriggers = <table> {
 }
 MaximizeMinimizeFrame = Frame {
 }
 MinimapDropdown = WorldMapZoneMinimapDropdown {
 }
 mapArtID = 970
 areDetailLayersDirty = true
 minimizedWidth = 1024
 debugAreaTriggers = false
 pinFrameLevelsManager = <table> {
 }
 pinsToNudge = <table> {
 }
 dataProviders = <table> {
 }
 detailLayerPool = <table> {
 }
 isUndefinedEventAllowed = true
 MaxMinButtonFrame = Frame {
 }
 BorderFrame = Frame {
 }
 ScrollContainer = ScrollFrame {
 }
 BlackoutFrame = Frame {
 }
 mapID = 947
 ContinentDropdown = WorldMapContinentDropdown {
 }
}
pinTemplate = "HereBeDragonsPinsTemplateQuestie"
pin = Frame {
 owningMap = WorldMapFrame {
 }
 pinTemplate = "HereBeDragonsPinsTemplateQuestie"
}
newPin = true
(*temporary) = nil
(*temporary) = Frame {
 owningMap = WorldMapFrame {
 }
 pinTemplate = "HereBeDragonsPinsTemplateQuestie"
}
(*temporary) = "attempt to call method 'OnLoad' (a nil value)"

## Questie & WoW version
 10.3.16
Classic SoD 1.15.4

**Comment by BreakBB** [comment]
We are currently looking into this. It looks like Blizzard broke something on their side and the update didn't hit EU yet (where I am playing at).

**Comment by karlwithak2** [comment]
Just to add, people are also having in-game issues with a number of other addons too, not just Questie
