### ISSUE TITLE
Hiding icons on continent map doesn't work; they reappear

### ISSUE THREAD

**Issue by NathanHawks** [Questie/Questie#6434]
## Bug description
Very recently (past week or two) a whole slew of icons have appeared on the full-size map, both when zoomed into a zone and on the continent view. I found the options to hide icons on the continent view (Icons tab > Map Options > Hide Icons on Continent Map) and checked it. The icons disappeared but within less than a second they started reappearing, one category at a time (like, all mailboxes, then all innkeepers, etc).

## Screenshots
![image](https://github.com/user-attachments/assets/80e33c25-6314-467e-8d9f-f1abc8b2a6b8)

## Questie & WoW version
Questie 10.4.0

Cata Classic

**Comment by niklasalkin** [comment]
I get this too, in regular Classic

**Comment by BreakBB** [comment]
We'll look into this @NathanHawks @niklasalkin

**Comment by NathanHawks** [comment]
Confirmed fixed! Y'all rock, thank you!
