### ISSUE TITLE
ERA game crashed during combat. v10.4.2

### ISSUE THREAD

**Issue by Iambookz** [Questie/Questie#6436]
<1x Questie/Modules/Libs/ThreadLib.lua:39: script ran too long
[string "@Questie/Modules/Libs/ThreadLib.lua"]:39: in function <Questie/Modules/Libs/ThreadLib.lua:35>

Locals:
success = false
ret = "Questie/Modules/QuestieCleanup.lua:24: script ran too long"
(*temporary) = false
(*temporary) = "Questie/Modules/QuestieCleanup.lua:24: script ran too long"
(*temporary) = false
(*temporary) = nil
(*temporary) = "script ran too long"
thread = <no value>
errorMessage = "Error during initialization!"
callbackFunction = nil

**Comment by BreakBB** [comment]
Oh wow, how long have you been in combat right after login? 😅

**Comment by BreakBB** [comment]
I ran into this myself when doing a `/reload` while in combat and staying in combat afterwards.
