### ISSUE TITLE
Error in quest dependency

### ISSUE THREAD

**Issue by TorpedoCXC** [Questie/Questie#6437]
## Description
Questie is showing the quest "Mass production" as available even when the required prerequisite quest "Tweedle's Tiny Package" isn't completed yet.

## Wowhead link
https://www.wowhead.com/cata/quest=13977/mass-production
https://wowpedia.fandom.com/wiki/Tweedle%27s_Tiny_Package_(quest)
https://www.wowhead.com/quest=13974/tweedles-tiny-parcel

## Questie & WoW version
Questie 10.4.2
WoW Cataclysm Classic 4.4.0.56713

**Comment by coldpasta123** [comment]
Thanks - fixed in next release (plus a few others in this chain)
