### ISSUE TITLE
Quest "To Battlescar!"

### ISSUE THREAD

**Issue by TorpedoCXC** [Questie/Questie#6440]
## Description
Objective location for Krom'gar Demolisher not showing for quest "To Battlescar!".

Locations are
* 43.7 - 40.0
* 43.1 - 40.8
* 42.3 - 42.2
* 42.6 - 39.8
* 41.6 - 41.0
* 41.0 - 42.2
* 40.5 - 42.6

## Wowhead link
https://www.wowhead.com/quest=26082/to-battlescar

## Screenshots
![grafik](https://github.com/user-attachments/assets/96f1b39b-5aad-4781-9974-ebdda1f73c4e)

## Questie & WoW version
WoW 4.4.0.56713
Questie 10.4.2

**Comment by coldpasta123** [comment]
@TorpedoCXC I'm not sure I understand what you mean - Krom'gar Demolisher is not an objective of To Battlescar!

Do you mean that there's no marker to show 'get in the Demolisher'?

**Comment by TorpedoCXC** [comment]
@coldpasta123 Yes. The quest says to get into a demolisher to kill some mobs. One may be able to kill the mobs without the demolisher though. I did not test this.

**Comment by coldpasta123** [comment]
Ok thanks, fixed
