### ISSUE TITLE
Quest 14338 Ghost Walker Post shown as available when it's not

### ISSUE THREAD

**Issue by TorpedoCXC** [Questie/Questie#6442]
## Description
The quest 14338 Ghost Walker Post is shown as available when it is not. Probably missing prequest.

## Wowhead link
https://www.wowhead.com/quest=14338/ghost-walker-post

## Screenshots
![WoWScrnShot_100124_120118](https://github.com/user-attachments/assets/83cd91ea-8947-442c-a3cd-24a034be9940)

## Questie & WoW version
WoW 4.4.0.56713
Questie 10.4.2

**Comment by coldpasta123** [comment]
Fixed in https://github.com/Questie/Questie/pull/6636

@BreakBB please close
