### ISSUE TITLE
Quest 14337 Shadowprey Village is shown as available when it is not

### ISSUE THREAD

**Issue by TorpedoCXC** [Questie/Questie#6443]
## Description
The quest 14337 Shadowprey Village is shown as available when it is not. Probably missing prequest.

## Wowhead link
https://www.wowhead.com/quest=14337/shadowprey-village

## Screenshots
![WoWScrnShot_100124_120118](https://github.com/user-attachments/assets/a16ae5da-0b7d-4a20-91c9-d63ad2132daa)

## Questie & WoW version
WoW 4.4.0.56713
Questie 10.4.2

**Comment by coldpasta123** [comment]
Fixed in https://github.com/Questie/Questie/pull/6636

@BreakBB please close
