### ISSUE TITLE
Bug during lvling new gnome mage in the start location.

### ISSUE THREAD

**Issue by amaxcz** [Questie/Questie#6446]
![image](https://github.com/user-attachments/assets/48eb685e-14e4-4b5b-8c28-be57698e5be7)
![image](https://github.com/user-attachments/assets/6184d35b-a61a-4345-bfae-42e20ebeb6a6)
![image](https://github.com/user-attachments/assets/ca08f0e9-016d-48ef-af97-b1971763e5dc)

**Comment by BreakBB** [comment]
Hey @amaxcz so you are playing SoD, which Questie version are you using?

**Comment by amaxcz** [comment]
questie was 10.4.2, SoD. trying to upgrade version.
