### ISSUE TITLE
Quest 14232 Ears Are Burning showing up on map despite already being started

### ISSUE THREAD

**Issue by TorpedoCXC** [Questie/Questie#6447]
## Description
The quest 14232 Ears Are Burning is shown as being available despite already being started. This quest is started by collecting the item "Burning Blade Ear" https://www.wowhead.com/item=49008/burning-blade-ear

## Wowhead link
https://www.wowhead.com/quest=14232/ears-are-burning

## Screenshots
![WoWScrnShot_100124_123619](https://github.com/user-attachments/assets/d02b6066-b97b-46d3-b219-f2279695d8ab)

## Questie & WoW version
10.4.2
4.4.0.56713

**Comment by coldpasta123** [comment]
Fixed in https://github.com/Questie/Questie/pull/6636

@BreakBB please close
