### ISSUE TITLE
Quest 14227 Putting Their Heads Together - missing item indicator on map

### ISSUE THREAD

**Issue by TorpedoCXC** [Questie/Questie#6448]
## Description
The quest "Putting Their Heads Together" requires you to collect 100 bleached skulls (https://www.wowhead.com/item=48953/bleached-skull) to summon a mob to kill (https://www.wowhead.com/npc=35647/nazargen). The required items are found in bleached skullpiles (https://www.wowhead.com/object=195535/bleached-skullpile). These are not shown on the map.

There is an alliance version of this quest. I assume it may have the same problems.

## Wowhead link
https://www.wowhead.com/quest=14227/putting-their-heads-together
https://www.wowhead.com/item=48953/bleached-skull
https://www.wowhead.com/object=195535/bleached-skullpile
https://www.wowhead.com/npc=35647/nazargen

## Screenshots
![WoWScrnShot_100124_124016](https://github.com/user-attachments/assets/1caedc78-5f5c-4645-8c50-63a88e761873)

## Questie & WoW version
10.4.2
4.4.0.56713

**Comment by coldpasta123** [comment]
Fixed in https://github.com/Questie/Questie/pull/6636

@BreakBB please can you close
