### ISSUE TITLE
Quest 26589 The Wilds Of Feralas showing as available when it is not

### ISSUE THREAD

**Issue by TorpedoCXC** [Questie/Questie#6451]
## Description
The quest is being started by the NPC Khan Shodo, which only becomes available after you defeat Agogridon and the Shok'Thokar village becomes friendly.

## Wowhead link
https://www.wowhead.com/cata/quest=26589/the-wilds-of-feralas
https://www.wowhead.com/cata/npc=36487/khan-shodo

## Screenshots
![WoWScrnShot_100224_133855](https://github.com/user-attachments/assets/ec3758fc-47fc-44b0-b502-ecf038c526ee)

## Questie & WoW version
10.5.1
4.4.0.56713

**Comment by coldpasta123** [comment]
Fixed in https://github.com/Questie/Questie/pull/6636 

@BreakBB can you close please
