### ISSUE TITLE
Tooltips for Group Member Objectives Don't Show Up in Classic Era

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#6455]
### Description

Progress Tooltips for party members aren't showing up in Classic Era where many of the servers are merged. I assume it's checking Character, instead of Character-Server or something simple like that. I see some other add-ons, like Details, still being able to share info between servers so I assume it's not a comms issue. (But I don't really know.)

### Questie version

Latest

### Game flavor

Era/HC

**Comment by BreakBB** [comment]
Thanks for reporting this. It's a good guess that it's related to the server merge
