### ISSUE TITLE
CATA - molten front dailies - all

### ISSUE THREAD

**Issue by Raina1007** [Questie/Questie#6457]
### Description

When you turn in a molten front daily you get a Mark of the World Tree. Every time I do, I get an error message. See screenshot. I got it via WowUpHub, so directly from Github.  See Screenshot for error message. It happens for every molten front daily up to this point if Questie is enabled.
<img width="416" alt="Screenshot 2024-10-03 at 12 17 21 PM" src="https://github.com/user-attachments/assets/2f3d7fb2-d32c-4ebf-b0f5-e0de2bcf3183">

### Questie version

v10.5.1

### Game flavor

Cata

**Comment by BreakBB** [comment]
@Cabro that's something you want to look into.

**Comment by BreakBB** [comment]
Fixed in latest version.
