### ISSUE TITLE
Quest 6143 Other Fish To Fry - removed from game

### ISSUE THREAD

**Issue by TorpedoCXC** [Questie/Questie#6459]
### Description

According to this link the quest has been removed from the game. https://wowpedia.fandom.com/wiki/Other_Fish_to_Fry

### Questie version

v10.5.1

### Game flavor

Cata

**Comment by Cabro** [comment]
Fixed in https://github.com/Questie/Questie/commit/7803242190472eea84717f7a48fc8ee87a862151
