### ISSUE TITLE
Quest 6142 Clam Bait - removed from game

### ISSUE THREAD

**Issue by TorpedoCXC** [Questie/Questie#6460]
### Description

According to this link the quest was removed from the game: https://wowpedia.fandom.com/wiki/Clam_Bait

### Questie version

v10.5.1

### Game flavor

Cata

**Comment by Cabro** [comment]
Fixed in https://github.com/Questie/Questie/commit/7803242190472eea84717f7a48fc8ee87a862151

**Comment by TorpedoCXC** [comment]
Thx @Cabro. Good to know how to delete quests. Next time, I will be able to correct these issues myself. :)
