### ISSUE TITLE
Update Tracker while in combat

### ISSUE THREAD

**Issue by SilAntoine** [Questie/Questie#6467]
### Description

Hello,

Questie tracker does not update while in combat.

Chat updates and sound notifications on objectives progression and quest completion are working fine.

Thanks for the hard work!

Kind regards,
Antoine

ps: been like this for at least a week, not just with latest patch

### Questie version

v10.5.1

### Game flavor

Cata

**Comment by Dazz87** [comment]
I also have the issue where auto update quests (eg. "Those Bears Up There", "Punting Season", "Between the Trees") do not have the pup-up to allow me to complete. The sound for the completion happens when it should pop up, but nothing happens. How can this be fixed?

**Comment by BreakBB** [comment]
Hey @SilAntoine

it has been like this forever and is not something we can work around easily. I'll keep this open though.
