### ISSUE TITLE
Is the error reporting tool enabled, or something I can enable, in Classic Era?

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#6468]
### Question

There was the great tool that reported missing items or bad data. Is that something that can be turned on for Classic Era? Finding a few small issues, and it's not coming up when I pick up a Quest that Questie doesn't seem to have yet.

**Comment by BreakBB** [comment]
We still have that only active for SoD, but it's on our list for quite some time now to also find issues in other game flavors (like when a player picks up a quest which Questie thinks should not be available).

In general Era/HC is by far in the best state correction wise, but there are still minor things which would be great to find, yeah 👍🏻

**Comment by Gogo1951** [comment]
Is there a way to allow users to turn the feature on for faster bug reporting?

**Comment by BreakBB** [comment]
There is not, atm. But I started to add an option to enable it for non SoD clients as well.

Keep in mind though, that the checks currently implemented won't help _that much_ on Era, as Questie only checks for missing items/quests/NPCs and not for things like "did the player just pick up a quest that Questie thinks is not available".

**Comment by Gogo1951** [comment]
I think adding a check around "I just got a quest that I didn't expect from an NPC" would be good. It wouldn't really have to check if the NPC is in the right place (they do move around). As long as that's in there.

There are just small things wrong with Era... dunno, like when you mouse over a quest and it says you need 12 items, and then you pick up the quest and it says you only need 10. I get these aren't breaking changes, but there are a lot of these little things that pop up. 

(It's not just with Quesite, like All the Things has similar issues around their data sets for Classic Era.)

Does it matter? Meh. 

There seem to be more people playing Classic Era lately. I think SoD had some good points, but they really messed up classes. People can care about playing a class, but mostly they care about playing a role. "I'm a Tank, I'm a Healer..." and SoD jacked with all the tanks so bad, and it just wasn't fun up front when all the DPS got massive abilities, and Warrior and Druid Tanks didn't. Ok, I'll shut up now.

Glad you're still working on this! Cheers!

**Comment by Gogo1951** [comment]
Ha, like priorities wise... the broken Progress Tool Tips are more important. (=

People talk about that all the time when out questing or doing dungeons. Apparently it's been broken for about 6-7 months. 

They tips show when you are from the same server, but won't show for people from different servers. Probably how it got missed in testing. 

Cheers!

**Comment by BreakBB** [comment]
> I think adding a check around "I just got a quest that I didn't expect from an NPC" would be good.

That is absolutely something on our list.

> Ha, like priorities wise... the broken Progress Tool Tips are more important.

As usual time is limited and some things are easier to fix than others. But you are right, this is something that we should have tackled way earlier. Though the actual number reports of this is quite low 🤷🏻‍♂️

**Comment by Gogo1951** [comment]
Classic Players are used to a lot of things not working. =P

That's my take away. (=
