### ISSUE TITLE
Missing objective data for quests 29279, 29283, 29281

### ISSUE THREAD

**Issue by EZ-Mouse** [Questie/Questie#6480]
### Description

The quests 29279, 29283, 29281 have missing objective data (currency) they need 125 currency 416, but is always shown as complete

### Questie version

v10.5.1

### Game flavor

Cata

**Comment by coldpasta123** [comment]
Thanks - this was fixed in the latest version by @Cabro (please close)

**Comment by Sommos** [comment]
Fixed in: 39e6e563410244dd33224a0b5f1b18e469e06b15
