### ISSUE TITLE
Show Blizzard Timer button unchecked, Timer still showing

### ISSUE THREAD

**Issue by Techmuh** [Questie/Questie#6482]
### Description

The hide Blizzard Timer function isn't working correctly. I'm not sure if its an issue with Questie or not, but the Quest Timer frame was never visible while using Questie until today. I checked and unchecked the "Show Blizzard Timer" option to try and reset it, reloaded, and reinstalled Questie. While Show Blizzard Timer is unchecked its still present. Pic for reference.

![WoWScrnShot_100624_180448](https://github.com/user-attachments/assets/83385a3d-2008-4347-bd8c-e4e1ac9fbd07)

### Questie version

v10.5.1

### Game flavor

Season of Discovery

**Comment by BreakBB** [comment]
Thanks for reporting this @Techmuh we'll look into this.
