### ISSUE TITLE
Position for NPC 45278 is wrong

### ISSUE THREAD

**Issue by TorpedoCXC** [Questie/Questie#6486]
### Description

https://www.wowhead.com/cata/npc=45278/freewind-brave

![WoWScrnShot_100824_131120](https://github.com/user-attachments/assets/c1b4b5c8-04c3-45b5-859b-7b0c065aab0b)

### Questie version

v10.5.2

### Game flavor

Cata

**Comment by coldpasta123** [comment]
I considered this when I did these quests too. It's not straightforward because he's one of these NPCs who follows you around, but your info is a better location for where he starts and I have updated it - thanks
