### ISSUE TITLE
Quest 25591 Thunderdrome: Grudge Match! shown as available when it is not

### ISSUE THREAD

**Issue by TorpedoCXC** [Questie/Questie#6492]
### Description

https://www.wowhead.com/cata/quest=25591/thunderdrome-grudge-match

According to the comments, there seem to be multiple prequests. I will test this quest by quest and will try to fix the issue.
This quest also has an alliance version.

![WoWScrnShot_100924_133913](https://github.com/user-attachments/assets/97fede7e-deb1-4631-9341-6442e745c5d4)

### Questie version

v10.6.0

### Game flavor

Cata

**Comment by TorpedoCXC** [comment]
Completed all quests in Tanaris, but this one still does not show up. Was removed from the game maybe.

**Comment by Cabro** [comment]
Most of the times, the quests that should show up but don't, have some unexpected conditions: race, prequestgroup needs one more quest id that you just didnt think about, or is exclusiveTo some other quest. Don't be fast to blacklist :)

**Comment by coldpasta123** [comment]
I did this last week and it was fine. There is already a correction entered for the correct prequest from a few months ago (https://github.com/Questie/Questie/commit/f8b03a4556bcc75ad0f89b6bb9152e133065b10a).

There is some event/rp involved with this quest line/NPC which means that the quest is not always available like a standard NPC (e.g. it can take a bit of time to reset properly after someone else attempts the event).

Don't believe there is an issue to fix here.

**Comment by BreakBB** [comment]
Fixed in 7fa961b299c79df940ad196c266551f310ac4425

It's an improvement to the previous correction.

**Comment by TorpedoCXC** [comment]
@BreakBB I have got a general question regarding the commit.

You removed the exclusiveTo attribute from the breadcrumb quest and added the nextQuestInChain attribute instead. Am I right to assume, that this also tells Questie that if I do the quest that is marked in nextQuestInChain first, that this will disable the breadcrumb quest? So we do not need to add both attributes for one quest?

**Comment by TorpedoCXC** [comment]
@coldpasta123 Your assumptions seemed to be correct. I revisited the area today and guess what, the quest was available.

![WoWScrnShot_101424_014601](https://github.com/user-attachments/assets/a9645238-73ea-408d-833e-f8d645775dc2)
