### ISSUE TITLE
Quest 25719 Demoniac Vessel no quest markers for items to collect

### ISSUE THREAD

**Issue by TorpedoCXC** [Questie/Questie#6608]
### Description

https://www.wowhead.com/cata/quest=25719/demoniac-vessel

Also has an alliance version: https://www.wowhead.com/cata/quest=26186/demoniac-vessel

### Questie version

v10.6.1

### Game flavor

Cata

**Comment by TorpedoCXC** [comment]
Wow. This will be complicated.

1.) One has to collect 20 Nighstalker Legs: https://www.wowhead.com/cata/item=57178/nightstalker-leg These are dropped by: https://www.wowhead.com/cata/npc=42337/tainted-nightstalker

2.) Using these creates 20 Crushed Nightstalker Legs: https://www.wowhead.com/cata/item=57181/crushed-nightstalker-leg

3.) Then you have to collect 2 Screecher Brains: https://www.wowhead.com/cata/item=57179/screecher-brain These are dropped by: https://www.wowhead.com/cata/npc=42338/tainted-screecher

4.) Using these creates 2 Screecher Brain Paste: https://www.wowhead.com/cata/item=57182/screecher-brain-paste

5.) Then you have to collect 4 Tainted Hides: https://www.wowhead.com/cata/item=57177/tainted-hide These are dropped by: https://www.wowhead.com/cata/npc=42336/tainted-black-bear

6.) Using these creates a Tainted Hide Pouch: https://www.wowhead.com/cata/item=57180/tainted-hide-pouch

7.) You the use the items gained in step 2 and 4 to create a Demoniac Commixture: https://www.wowhead.com/cata/item=57183/demoniac-commixture

8.) Using the items gained in step 6 and 7 creates the required quest item: https://www.wowhead.com/cata/item=57184/demoniac-vessel

It should suffice to link the involved NPCs to the quest and check that their postions in the database are correct. I am not sure though, if we need to link anything else (like the intermediate materials created). Can anyone help? @BreakBB @Cabro

**Comment by BreakBB** [comment]
For a first improvement I would add all the items of step 1-7 to `requiredSourceItems, check the spawns of the NPCs for step 1, 3 and 5 and also make sure the intermediate items don't have any source. We do add the intermediate items so they get tooltips in the inventory.
