### ISSUE TITLE
Quest 10388 "Return to Thrallmar" assigned to wrong quest giver

### ISSUE THREAD

**Issue by TorpedoCXC** [Questie/Questie#6612]
### Description

https://www.wowhead.com/cata/quest=10388/return-to-thrallmar

It's this NPC https://www.wowhead.com/cata/npc=19273/forward-commander-toarch instead of this: https://www.wowhead.com/cata/npc=16576/overlord-hun-maimfist

![WoWScrnShot_101924_233510](https://github.com/user-attachments/assets/c8a43249-5540-4866-b8c7-c05c4a1a467a)

### Questie version

v10.6.1

### Game flavor

Cata

**Comment by Cabro** [comment]
Are you sure it's not both? All other expansions list them as both. Did you check both of them?

**Comment by TorpedoCXC** [comment]
I am pretty sure that I checked both. We need more volunteers being able to quickly check these things again in time. :)

**Comment by TorpedoCXC** [comment]
The comments on wowhead only include the other NPC as quest giver until WotLK though.

**Comment by Cabro** [comment]
I'll give you one word of advice. Dont trust wowhead. Like.. at all.
