### ISSUE TITLE
Ошибка 41 в Questie-335

### ISSUE THREAD

**Issue by YogurtiTM** [Questie/Questie#6631]
### Description

Ошибка при инициализации! ...terfaceiAddOnslQuestie- 335ModulesiQuestiePIayer.lua:41
![2024-10-24_18-38-23](https://github.com/user-attachments/assets/43801c12-bd1f-45f2-89e4-a7aab8ffc3e6)
![2024-10-24_18-39-57](https://github.com/user-attachments/assets/e7fa0d7b-2c16-482b-8410-6e35dcd91a77)
![2024-10-24_18-40-37](https://github.com/user-attachments/assets/eb203045-00ee-482a-a929-200f2bdeff00)
      У друзей все работает, а у меня выдает ошибку. 

### Questie version

v9.5.1

### Game flavor

Era/HC

**Comment by Cabro** [comment]
You might want to upgrade your Questie. We are on this version
![image](https://github.com/user-attachments/assets/e4e5c423-a445-4401-8f19-e093e264c6a4)

**Comment by YogurtiTM** [comment]
У друзей Версия v9.5.1 все работает

**Comment by Cabro** [comment]
We don't support private servers, which looks like what you're trying to do.

**Comment by BreakBB** [comment]
You are at the wrong place @YogurtiTM -> Checkout https://github.com/widxwer/Questie for v3.3.5
