### ISSUE TITLE
Questie: Error during initialization! …terface\AddOns\Questie- 335\Modules QuestiePlayer.lua:41: attempt to perform arithmetic on upvalue 'playerRaceld" (a nil value)

### ISSUE THREAD

**Issue by YogurtiTM** [Questie/Questie#6632]
### Description

Questie: Error during initialization! …terface\AddOns\Questie- 335\Modules QuestiePlayer.lua:41: attempt to perform arithmetic on upvalue 'playerRaceld" (a nil value)

### Questie version

v10.3.14

### Game flavor

Era/HC

**Comment by BreakBB** [comment]
Again @YogurtiTM this is the wrong place for Questie v3.3.5 -> https://github.com/widxwer/Questie
