### ISSUE TITLE
Questie: [ERROR] Please report this error. GetQuest: The quest doesn't exist in QuestLogCache. 401

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#6633]
### Description

Got this quesite error in Classic Era... I think I got this as I was turning or picking up a quest.

 Questie: [string "@Interface/AddOns/Questie/Modules/Quest/QuestLogCache.lua"]:311: in function `GetQuest'
[string "@Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua"]:1445: in function `PopulateQuestLogInfo'
[string "@Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua"]:453: in function `val'
[string "@Interface/AddOns/Questie/Modules/TaskQueue.lua"]:8: in function <Interface/AddOns/Questie/Modules/TaskQueue.lua:6>

### Questie version

Latest

### Game flavor

Era/HC

**Comment by BreakBB** [comment]
Are you running Questie's auto accept feature?

**Comment by Gogo1951** [comment]
Yeah. Auto accept and auto turn in. Instant quest text all that. Just tag and NPC and then get back to questing. (=
