### ISSUE TITLE
Questie v10.6.4 compatibility issues with patch 10/29/2024

### ISSUE THREAD

**Issue by Papastomper** [Questie/Questie#6645]
### Description

Questie seems to be having issues after the latest WoW patch (10/29/2024). With Questie installed you can't open the main map (granted this isn't all the time but the majority), as it seems to click a map behind it. Also, markers are not showing up on the main map, main quest area will show up - but not always. Seems to crash the game after an add-on reload - occasionally. This is happening with the WoW Cataclysm Classic game version.

### Questie version

v10.6.4

### Game flavor

Cata

**Comment by BreakBB** [comment]
Hey @Papastomper 

Did you disable all addons except Questie and see if that helps?

It's working fine for me on 4.4.1

<img width="859" alt="image" src="https://github.com/user-attachments/assets/ac297fd5-2506-42f0-8a74-69f88ab515dd">

**Comment by Papastomper** [comment]
@BreakBB - yes I did. Did the normal trouble shooting by shutting everything off (only run 4 addons, auctionator, gatherer, routes and questie) and turning them back on one by one. Questie is the only one I am having this problem with.

**Comment by BreakBB** [comment]
Alright, try the following (if you don't care about your Questie Journey data):

1. Disable all addons except Questie
2. Close the game
3. Delete these files:
> - `World of Warcraft\_classic_\WTF\Account\<yourAccount>\SavedVariables\Questie.lua`
> - `World of Warcraft\_classic_\WTF\Account\<yourAccount>\SavedVariables\Questie.lua.bak`
> 
> - `World of Warcraft\_classic_\WTF\Account\<yourAccount>\<yourServer>\<yourCharacter>\SavedVariables\Questie.lua`
> - `World of Warcraft\_classic_\WTF\Account\<yourAccount>\<yourServer>\<yourCharacter>\SavedVariables\Questie.lua.bak`

4. Start the game again

**Comment by Papastomper** [comment]
@BreakBB - followed your instructions and **Questie is now working**. also did this on my wifes computer - she had other addons active - and it worked. Thank you very much for your assistance!!

**Comment by Papastomper** [comment]
@BreakBB was/is exceptional with patience and assistance in getting this corrected for our WoW family.

**Comment by BreakBB** [comment]
Thanks for your kind words and I am happy Questie is working again @Papastomper - Addons and their setup is sometimes really weird and can get into these "fully broken" states, so a full fresh re-install as you did, is a good last resort 👍🏻
