### ISSUE TITLE
Issue to track an achievment

### ISSUE THREAD

**Issue by Bhahlou** [Questie/Questie#6648]
### Description

When I shift-click an achievment to track it, I get the following error:

11x ...ceQuestie/Modules/Tracker/QuestieTracker.lua:2096: attempt to call global 'GetMouseFocus' (a nil value)
[string "@Questie/Modules/Tracker/QuestieTracker.lua"]:2096: in function `TrackAchieve'
[string "@Questie/Modules/Tracker/QuestieTracker.lua"]:1764: in function <...ceQuestie/Modules/Tracker/QuestieTracker.lua:1764>
[string "=[C]"]: in function `AddTrackedAchievement'
[string "@Blizzard_AchievementUI/Cata/Blizzard_AchievementUI.lua"]:934: in function `AchievementButton_ToggleTracking'
[string "@Blizzard_AchievementUI/Cata/Blizzard_AchievementUI.lua"]:888: in function `AchievementButton_OnClick'
[string "*Blizzard_AchievementUI.xml:1128_OnClick"]:1: in function <[string "*Blizzard_AchievementUI.xml:1128_OnClick"]:1>

Locals:
self = <table> {
 started = true
 last_achieveId = 5871
 alreadyHooked = true
 alreadyHookedSecure = true
 private = <table> {
 }
}
achieveId = 5871
now = 402004.462000
mouseFocus = nil
frameMatch = nil
(*temporary) = nil
(*temporary) = "attempt to call global 'GetMouseFocus' (a nil value)"
QuestieTracker = <table> {
 started = true
 last_achieveId = 5871
 alreadyHooked = true
 alreadyHookedSecure = true
 private = <table> {
 }
}
l10n = <table> {
 zoneLookup = <table> {
 }
 objectNameLookup = <table> {
 }
 continentLookup = <table> {
 }
 questCategoryLookup = <table> {
 }
 translations = <table> {
 }
 private = <table> {
 }
 zoneCategoryLookup = <table> {
 }
}
lastAchieveId = 402004.462000

### Questie version

v10.6.4

### Game flavor

Cata

**Comment by Bhahlou** [comment]
If I remember correctly, I had the same issue on Firelands RPT with ItemRack, and GetMouseFocus() was removed and replaced by GetMouseFoci()

https://warcraft.wiki.gg/wiki/Patch_11.0.0/API_changes

**Comment by BreakBB** [comment]
Already fixed in 33e064979b9b7226a7459e06943e5982a312d724 and will be released in a minute.

Thanks for reporting this @Bhahlou ❤️
