### ISSUE TITLE
Shandrina in Silverwind Refuge Ashenvale wrongly identified as Cooking Trainer

### ISSUE THREAD

**Issue by 75338** [Questie/Questie#6654]
### Description

Shandrina in Silverwind Refuge Ashenvale wrongly identified as Cooking Trainer

### Questie version

v10.7.1

### Game flavor

Era/HC

**Comment by BreakBB** [comment]
She sells https://www.wowhead.com/classic/item=16072/expert-cookbook which is the reason we marked her as Cooking Trainer. Not sure if we should change this, but I agree that she is not a _real Cooking trainer_.

@Cabro @coldpasta123 @TorpedoCXC any thoughts on this?

**Comment by Cabro** [comment]
Definitely remove it from trainers. That's a vendor.

**Comment by TorpedoCXC** [comment]
I agree with @Cabro 
When she doesn't teach cooking, she is not a trainer.

**Comment by BreakBB** [comment]
There are other items as well for the same reason:

https://github.com/Questie/Questie/blob/ba862d948f58ef77bdd95a4d9debd185138a5668/Modules/QuestieMenu/Townsfolk.lua#L277-L279

Move them all to "Trade Goods"?
