### ISSUE TITLE
Lua error while zoning into a Classic Era Dungeon

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#6659]
### Description

4x Questie/Modules/Libs/QuestieLib.lua:345: attempt to perform arithmetic on local 'x' (a nil value)
[string "@Questie/Modules/Libs/QuestieLib.lua"]:345: in function `Euclid'
[string "@Questie/Modules/Libs/DistanceUtils.lua"]:150: in function <Questie/Modules/Libs/DistanceUtils.lua:147>
[string "@Questie/Modules/Libs/DistanceUtils.lua"]:28: in function `GetNearestSpawn'
[string "@Questie/Modules/Libs/DistanceUtils.lua"]:77: in function <Questie/Modules/Libs/DistanceUtils.lua:70>
[string "=(tail call)"]: ?
[string "@Questie/Modules/Tracker/TrackerUtils.lua"]:671: in function `GetSortedQuestIds'
[string "@Questie/Modules/Tracker/QuestieTracker.lua"]:606: in function `Update'
[string "@Questie/Modules/Tracker/TrackerUtils.lua"]:793: in function `func'
[string "@Questie/Modules/Libs/QuestieCombatQueue.lua"]:25: in function <...eQuestie/Modules/Libs/QuestieCombatQueue.lua:17>

Locals:
x = nil
y = nil
i = -3183.616504
e = -6091.899754
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to perform arithmetic on local 'x' (a nil value)"

### Questie version

10.8.0

### Game flavor

Era/HC

**Comment by BreakBB** [comment]
Thanks for reporting this. I'll look into this right away!
