### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by GeneralHavok101** [Questie/Questie#6660]
### Description

Got this stream of errors when I log in
![image](https://github.com/user-attachments/assets/ada12a27-5dd1-48ee-ae27-f2ddc05dbcd4)

### Questie version

v1.15.4

### Game flavor

Era/HC

**Comment by BreakBB** [comment]
Hey @GeneralHavok101 

Are you on Questie v10.8.1? And also where were you when the error happened? In a dungeon?

**Comment by GeneralHavok101** [comment]
I've been in multiple zone been going on for a few days  and yes 10.8.1

**Comment by BreakBB** [comment]
So every time you log in, that error happens? And it doesn't matter in which zone you are?

If so please share a list of the quests in your quest log.

**Comment by GeneralHavok101** [comment]
This is what login looks like.

![image](https://github.com/user-attachments/assets/280bbc5c-f03d-48c4-9a7e-953a4fd508b0)

**Comment by GeneralHavok101** [comment]
These are the only 8 quests I have.

![image](https://github.com/user-attachments/assets/63cfbe36-aeae-45fe-a92b-f19f08a20f00)
![image](https://github.com/user-attachments/assets/779bd17e-c5cb-4f0f-a081-ee2d234b452a)
![image](https://github.com/user-attachments/assets/05b711ac-d85a-46f2-b833-f9ddc7acfa80)

**Comment by hyperactivated** [comment]
I'm experiencing the same issue, had it in 10.8.0 and still happening in 10.8.1 on Season of Discovery.

Seems to be related to Three Kings of Flame (Quest ID: 8961)

**Comment by BreakBB** [comment]
Thanks @GeneralHavok101 and @hyperactivated that will help a lot to find a proper fix. I'll work on it right away and let you know when there is a version to test.

**Comment by BreakBB** [comment]
@hyperactivated and @GeneralHavok101 would you mind testing this version to validate the fix I built?

[Questie-v10.8.1-f9b92300b.zip](https://github.com/user-attachments/files/17686472/Questie-v10.8.1-f9b92300b.zip)

**Comment by hyperactivated** [comment]
@BreakBB this has resolved the issue for me. Thanks.

**Comment by BreakBB** [comment]
Awesome, thanks for validation the fix @hyperactivated - I'll ship a new release right away.

**Comment by GeneralHavok101** [comment]
Thanks for the quick turnaround.
