### ISSUE TITLE
Tracking achievement is invalid

### ISSUE THREAD

**Issue by guanke8023** [Questie/Questie#6668]
### Description

Game version: wotlk CN 3.4.3, Questie version: 10.9.1,

...ce/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:2096: attempt to call global 'GetMouseFoci' (a nil value)
Count: 5

Call Stack:
[string "=[C]"]: in function `GetMouseFoci'
[string "@Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua"]:2096: in function `TrackAchieve'
[string "@Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua"]:1764: in function <...ce/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:1764>
[string "=[C]"]: in function `AddTrackedAchievement'
[string "@Interface/AddOns/Blizzard_AchievementUI/Blizzard_AchievementUI.lua"]:1007: in function `AchievementButton_ToggleTracking'
[string "@Interface/AddOns/Blizzard_AchievementUI/Blizzard_AchievementUI.lua"]:961: in function `AchievementButton_OnClick'
[string "*Blizzard_AchievementUI.xml:1096_OnClick"]:1: in function <[string "*Blizzard_AchievementUI.xml:1096_OnClick"]:1>

### Questie version

v10.9.1

### Game flavor

WotLK

**Comment by BreakBB** [comment]
Related to #6648

**Comment by guanke8023** [comment]
> Oh boy... @guanke8023 you are playing WotLK in China I guess?

Yes, I am a CN WotLK player, 
so CN WOW API has not made the changes.... ahahaha...

**Comment by BreakBB** [comment]
Yep. Fix will be released shortly, Keep reporting if you notice more things like this!
