### ISSUE TITLE
Quest 13073 "The Keeper's Favor" missing NPC objective (talk to NPC)

### ISSUE THREAD

**Issue by TorpedoCXC** [Questie/Questie#6671]
### Description

https://www.wowhead.com/cata/quest=13073/the-keepers-favor

I am not sure if you really need to talk to this NPC for completing the quest: https://www.wowhead.com/cata/npc=30630/arch-druid-lilliandra
It may be possible to complete this quest without talking to her and instead travel to Moonglade by other means. When you talk to her, she opens a portal to allow fast travel to Moonglade.

![WoWScrnShot_111224_170640](https://github.com/user-attachments/assets/a9306d4f-8225-4dac-b6d5-277f8edeb561)

### Questie version

v10.9.1

### Game flavor

Cata

**Comment by Cabro** [comment]
That's an extraobjective.

**Comment by BreakBB** [comment]
What Cabro is trying to say: The "talk to her" objective is an extraObjective we added, so players will have it easier. Think of it as a minimal "guide".

**Comment by TorpedoCXC** [comment]
When did you add this extraObjective? I am asking because I believe my screenshot to be some days older and not using v10.9.1, but an older version of Questie.

**Comment by Cabro** [comment]
Sometime in wotlk

**Comment by TorpedoCXC** [comment]
That is strange. Because in Cata these extraObjectives were not shown on the map. The above screenshot is about 5 days old.

**Comment by TorpedoCXC** [comment]
All right then. Good to know.
