### ISSUE TITLE
Player icon isn't overriding other icons on the minimap

### ISSUE THREAD

**Issue by evascale1** [Questie/Questie#6678]
### Description

![Screenshot_6](https://github.com/user-attachments/assets/c55a39a8-46f2-475c-ba35-a6e4708e3412)
The player icon gets lost in the minimap even though "player icon fades other icons" is enabled in the option settings. Other icons are always above the player icon so when you are in a cluttered area it's hard to distinguish the player icon.

**Comment by BreakBB** [comment]
Hey @evascale1 thanks for reporting this. I was able to reproduce this bug and will see if I find a quick solution.
