### ISSUE TITLE
Quest: A Rogue's Deal doesn't disappear after completing

### ISSUE THREAD

**Issue by DatKota2** [Questie/Questie#668]

**Comment by bmeulmeester** [comment]
It actually does, it's a 2 part quest. Once you head to Brill and hand it in, a second quest appears at Calvin Montague near the gate. If you go back to the gate he has a new quest for you. This is not a bug.
[First quest](https://classic.wowhead.com/quest=8/a-rogues-deal)
[Follow up quest](https://classic.wowhead.com/quest=590/a-rogues-deal)

**Comment by vana-wow** [comment]
There are two quests called "A Rogue's Deal".
https://classic.wowhead.com/quest=8/a-rogues-deal
https://classic.wowhead.com/quest=590/a-rogues-deal

Maybe you finished the first and now the second is shown as available. You may want to talk to the npc "Calvin Montague" again and see if the second is available.

**Comment by bmeulmeester** [comment]
> I went back and didn't have another quest to pick up... :(

I had the same thing happen yesterday, it takes some time for him to show you the quest if someone else has just completed it. Check back later. It was confusing to me too, but I guarantee you, there's going to be a quest.
