### ISSUE TITLE
Error during initialization (Questie not loading)

### ISSUE THREAD

**Issue by Sebastipole** [Questie/Questie#6686]
### Description

Questie doesn't work, throwing the error;
`Error during initialization! ...ddOns/Questie/Database/Corrections/sodQuestFixes.lua:3710: table index is nil`

![image](https://github.com/user-attachments/assets/162dd768-13a2-4377-b187-cbd22f5ffb51)

Reinstalled questie, reloaded the database, still throwing the error.

### Questie version

10.9.3

### Game flavor

Season of Discovery

**Comment by BreakBB** [comment]
Damn it! Thanks for reporting this @Sebastipole 

I'll fix this right away

**Comment by BreakBB** [comment]
Fixed version will be available in the next few minutes (CurseForge might take some more time as they are usually a bit slower).

**Comment by Sebastipole** [comment]
> Fixed version will be available in the next few minutes (CurseForge might take some more time as they are usually a bit slower).

Oh woah, so fast, thank you for the speedy fix!

**Comment by BreakBB** [comment]
> Oh woah, so fast, thank you for the speedy fix!

Sorry for breaking it in the first place, but thanks for your kind words ❤️ Additional checks are in place now, to make sure _this_ failures will not happen again.
