### ISSUE TITLE
Move to BigWigsMods packager

### ISSUE THREAD

**Issue by BreakBB** [Questie/Questie#6688]
### Description

I think it is about time we move away form our manually created publishing scripts and use the standard all other addons also use.

We need to investigate if https://github.com/BigWigsMods/packager works for us and correctly bundles our different version.

**Comment by Muehe** [comment]
As mentioned [during the original PR](https://github.com/Questie/Questie/pull/4354#issuecomment-1272360444) BigWigs script has quite a lot of runtime compared to our Python ones. I guess we could check if this has changed in the last two years, but unless it has I don't really see the benefit of adding so much runtime to our CI/CD and local pipelines. So closing here for now.
