### ISSUE TITLE
Quest tracking is broken

### ISSUE THREAD

**Issue by Vitan787** [Questie/Questie#6712]
### Description

i am unable to see any of the quest turn ins or quest givers at this time. 
srry if this is unclear but my character is mid 30s so i should be see a plethora of quests here, so and its not just this zone but all of them. i have to find the quest mobs myself. on top of that i am unable to see quest Objectives either. i do have that checked as well.

![Wow hardcore quest bug](https://github.com/user-attachments/assets/7c46bd47-2722-4bdf-a0a9-7b4297710002)

### Questie version

v10.10.0

### Game flavor

Era/HC/Anniversary

**Comment by Cabro** [comment]
Clicked the Questie icon on the map by accident?

**Comment by Vitan787** [comment]
thanks, i feel dumb, XD
