### ISSUE TITLE
Anniversary editon

### ISSUE THREAD

**Issue by adamgnab** [Questie/Questie#6748]
### Question

Hi, any chance u make modyfier allowing filter quests by phase? In AE there is lot of non existing quest clues like 50 lvl class quest line or Dire Maul lines.

**Comment by BreakBB** [comment]
Hey @adamgnab 

Please report all quests that Questie shows which are not available yet. The goal is to always show only quests which are actually available.

Also make sure you are using the latest Questie version (it should be `v10.10.2` atm). You can check your version with `/questie version`.

**Comment by FlaxyDev** [comment]
One such quest is [A Troubled Spirit](https://www.wowhead.com/classic/quest=8417/a-troubled-spirit) (a class quest for warriors).

**Comment by adamgnab** [comment]
I think it is easier for devs parse database (like wowhead) and find at which patch they were added - (eg. Added in patch 1.13.3)
there are lots of them showig excl. mark on minimap nad not available
Aniversary Servers are in phase 1.1.2 atm
![image](https://github.com/user-attachments/assets/a9a1fbbe-87f7-47da-9427-000b3dffe4af)

**Comment by BreakBB** [comment]
> One such quest is [A Troubled Spirit](https://www.wowhead.com/classic/quest=8417/a-troubled-spirit) (a class quest for warriors), which will only be available starting from Phase 3.

Thanks @FlaxyDev this will be hidden in the next release 👍🏻 

> I think it is easier for devs parse database

The thing is: We are quite sure Questie is already hiding most quests which are not available yet. Therefore it's not _that_ helpful to go through "all" quests again which are becoming available at a later point. Moreover wowhead is wrong every now and then 🤷🏻

**Comment by adamgnab** [comment]
OK - for me : taking back silithus, the camp mojache, The Hunters charm, the wildlife suffers too, The darkmoon Faire,

**Comment by BreakBB** [comment]
- [Taking Back Silithus](https://www.wowhead.com/classic/quest=8275/taking-back-silithus), [Taking Back Silithus](https://www.wowhead.com/classic/quest=8276/taking-back-silithus) and [Camp Mojache](https://www.wowhead.com/classic/quest=7492/camp-mojache) are already hidden for a month. Make sure you are running the latest Questie version
- [The Hunters charm](https://www.wowhead.com/classic/quest=8151/the-hunters-charm) along with the other Sunken Temple class quests will be hidden with the next release
- [The Wildlife Suffers Too](https://www.wowhead.com/classic/quest=4984/the-wildlife-suffers-too) and [The Wildlife Suffers Too](https://www.wowhead.com/classic/quest=4985/the-wildlife-suffers-too) should already be available in P1 🤔
- All Darkmoon Faire quests will also be hidden with the next release

**Comment by adamgnab** [comment]
OK I recheck [The Wildlife Suffers Too](https://www.wowhead.com/classic/quest=4984/the-wildlife-suffers-too) being next time in EPL

**Comment by adamgnab** [comment]
I have Questie 10.10.3 - both mojache and sili are there
![image](https://github.com/user-attachments/assets/bb767b4a-4639-472f-a47f-aaeb55bb8c38)

**Comment by BreakBB** [comment]
And also verify the Questie version ingame. This is the horde version and it is currently blacklisted:
![image](https://github.com/user-attachments/assets/f050f9d8-2a10-44a2-b259-740be2eadf6d)

**Comment by adamgnab** [comment]
![image](https://github.com/user-attachments/assets/27e11d42-a0b1-4e9f-989c-da607d6d715e)

**Comment by BreakBB** [comment]
Now that is really confusing 🤔

**Comment by BreakBB** [comment]
Can you run the following ingame and report the output (it should either show "true" or "false")?

`/dump Questie.IsAnniversary`

**Comment by BreakBB** [comment]
So Questie thinks you are not playing on an Anniversary server. Are you sure you are? 😅

**Comment by BreakBB** [comment]
What does `/dump Questie.IsSoM`, `/dump Questie.IsClassic` and `7dump Questie.IsAnniversaryHardcore` print?

**Comment by adamgnab** [comment]
![image](https://github.com/user-attachments/assets/1c3d276e-f46a-4cfd-b233-0a097adc5daa)

**Comment by adamgnab** [comment]
Dump: value=Questie.IsSoM
[1]=false
Dump: value=Questie.IsClassic
[1]=true
Dump: value=Questie.IsHardcore
[1]=true
Dump: value=Questie.IsAnniversaryHardcore
[1]=true

**Comment by BreakBB** [comment]
Thank you very much @adamgnab for your patience. We now have all information to fix this.

So unlike the other game versions `Questie.IsAnniversaryHardcore` is true while `Questie.IsAnniversary` is false. We expected it to be different.

We'll fix this and ship a release rather soon. If you want the fix right now:

1. Open `Questie/Database/Corrections/QuestieQuestBlacklist.lua`
2. In line 4621 there is `elseif Questie.IsAnniversary then`
3. Replace it with `elseif Questie.IsAnniversary or Questie.IsAnniversaryHardcore then`
4. Do a `/reload`

**Comment by adamgnab** [comment]
WORKS ! - no single Q in sili 
![image](https://github.com/user-attachments/assets/109bcc6e-17f1-4504-b554-1a791025d25b)

**Comment by BreakBB** [comment]
Thanks for testing @adamgnab 🎉
