### ISSUE TITLE
Quest Tracker showing extra seconds in tracker

### ISSUE THREAD

**Issue by anon1231823** [Questie/Questie#6749]
### Description

Look at the Tracker you'll see for this timer quest it says XX minutos YY segundos ZZ seconds
![image](https://github.com/user-attachments/assets/bddc7de0-a2b1-4d10-a6b9-583321dd2ee3)

### Questie version

10.2.2

### Game flavor

Era/HC/Anniversary

**Comment by BreakBB** [comment]
Looks like you reported this already earlier this year... #5782 🙈 

I found the issue and will try to fix it.
