### ISSUE TITLE
WoW Classic (Fresh) - Darkmoon Faire shows active on the wrong week

### ISSUE THREAD

**Issue by barichr** [Questie/Questie#6750]
### Description

I'm playing Horde on the Classic Fresh PvE realm. Message from Questie at login shows Darkmoon Faire is active, yet the faire is not present. According to Wowhead Classic, the fair ended on the 8th in Mulgore and is set to start on the 16th in Elwynn Forest. So, Questie appears to be a week off?

### Questie version

v10.10.2

### Game flavor

Era/HC/Anniversary

**Comment by Nerillida** [comment]
Also read [this](https://eu.forums.blizzard.com/en/wow/t/darkmoon-faire-on-anniversary-realms/552688) although not followed it up.

**Comment by BreakBB** [comment]
Hey @barichr and @Nerillida

it would be great if you could update to Questie v10.10.3 - We just released a fix for this, since the Darkmoon Faire will not be available till P3.

**Comment by BreakBB** [comment]
c3350747456af35d70b79b2745799b6b64a8720f for reference
