### ISSUE TITLE
New "Use" Icons are ugly

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#6753]
### Description

The gear made more sense. These new square dots are really ugly. Just my 2 cents. Unsure what the purpose of changing it was.

<img width="1390" alt="image" src="https://github.com/user-attachments/assets/b57516fb-2c99-41e4-beaf-0e7b3c4dbf22" />

### Questie version

Latest

### Game flavor

Era/HC/Anniversary

**Comment by Cabro** [comment]
We both have the same feeling, however the higherups think the icon is good :D

**Comment by BreakBB** [comment]
We can treat this as feature request. The interact icons can not be configured yet:

![image](https://github.com/user-attachments/assets/b11ccc01-bd58-4eea-9969-b0d896f3fe73)

**Comment by Gogo1951** [comment]
Easy fix... for "Object" switch it to a box.

![image](https://github.com/user-attachments/assets/93555e16-55c1-4f44-bad4-e560620f2b1a)

inv_box_01

Then you can keep Gear for "Use" icons.

**Comment by BreakBB** [comment]
The gear icon matches the cursor when you interact with objects, so that should stay as it is.

Also the chest icon is in conflict to addons like GatherMate which uses it to display chest locations.

**Comment by Gogo1951** [comment]
Quest Helper, back in the day, used chests for lootable objects.

**Comment by Gogo1951** [comment]
I do like that you guys are FINALLY putting effort into the settings. Those have been awful for years. 

Like when Aero and I talked about this the solution we had was to keep lootable and "openable" as bags since the tooltip gave it away. Questie is over 5 years with the same behavior. It's a mistake to change it up now -- especially for something that's a worse design. Please sanity check this with non-devs before you launch it, it's really ugly.

**Comment by Gogo1951** [comment]
Also just on the topic of "collect" & "use" icons... 

They vary wildly.

Some "collect" icons are magnifying glasses, for "read inscription" -- some are "herbalism" or "mining pick" or "sack" or "gear." There isn't just one icon type.

But nowhere in all those icons is a diamond used. That's the hard part. The Diamond isn't any sort of "well this is close to what exists..." it's just another one that has never been used that's now introduced into the mix.

**Comment by BreakBB** [comment]
> I do like that you guys are FINALLY putting effort into the settings. Those have been awful for years.

yttrium did a major overhaul of the settings about a year ago (#4704 as example). There is still much to improve, but we are already far away from the absolutely horrible settings we had before 😅 

> But nowhere in all those icons is a diamond used.

To improve these, we need to manually override the default icon for each objective. We didn't find a way yet to make sure they are automatically consistent and correct. All "interact", "talk" and "mount up" icons are manually added, where it makes sense (and there are still many places where we need to change the icons).

I quickly scribbled a [Wiki page](https://github.com/Questie/Questie/wiki/Icons) list the Questie icons and to explain when they are used (or should be used).

Oh and about:

> "Collect" can use "herbalism" or "mining pick"

There is #5908 which started some work to show appropriate icons for mining and herbalism objectives, but there are so few quests, that is not something high on our list.
