### ISSUE TITLE
Name missing for NPC: 230302

### ISSUE THREAD

**Issue by regnerisch** [Questie/Questie#6757]
### Description

Questie: [ERROR] Name missing for NPC: 230302 - Please report this error on Discord or GitHub
Questie: [ERROR] Missing objective data for monster 'table: 000001165A675190' 230302

### Questie version

v10.10.3

### Game flavor

Season of Discovery

**Comment by BreakBB** [comment]
Upsi, thanks for reporting this @regnerisch
