### ISSUE TITLE
Auto-pick-up should be disabled for Wrath of the Blue Flight

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#6777]
### Description

This quest yeets you across the globe. It should have a bit more of a warning before you pick it up. (= 

At minimum it should be added to the do not auto accept list. Ha.

https://www.wowhead.com/classic/quest=5161/wrath-of-the-blue-flight

### Questie version

Latest

### Game flavor

Era/HC/Anniversary

**Comment by Cabro** [comment]
It's not an escort, to be bypassed :)
Blizzard themselves don't give you a confirmation box, so why should Questie?

**Comment by Gogo1951** [comment]
We added plenty of quests to the "don't auto pickup / turn in list" though. This should be on it.

**Comment by Gogo1951** [comment]
I think it gets turned off at the NPC level.

And the reason why... so you don't get punted across the globe while you still have a quest to turn in and then have to run all the way back.

**Comment by Gogo1951** [comment]
Anyway, same logic as why we turned off auto-complete for the Caverns of Time ring-giver. Cuz having it on creates a bad experience. It's late, we should have fixed the issue in Classic, but a lot of people are playing Anniversary and doing this quest now too.

**Comment by BreakBB** [comment]
Yeah Gogo is absolute right on this. There are plenty of similar quests which we already NOT auto accept because they fly you across stuff or teleport you to some place. Easy to fix.

**Comment by Gogo1951** [comment]
The guy I was leveling with yesterday... I said in Discord, "Hold shift before you turn it in..." and as I was talking I saw him go flying through the air. Then he had to run all the way back to Winterspring from Western Plague Lands. Kinda funny though. (=

**Comment by BreakBB** [comment]
Fixed in 5e20405d79b8b188786f90f3411d78e6595c8528 (linked the wrong issue in that commit)
