### ISSUE TITLE
The quest doesn't exist in QuestLogCache. 29210

### ISSUE THREAD

**Issue by SaintKatherine** [Questie/Questie#6779]
### Description

Questie: [string "@Interface/AddOns/Questie/Modules/Quest/QuestLogCache.lua"]:324: in function `GetQuestObjectives'
[string "@Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua"]:1415: in function `GetAllLeaderBoardDetails'
[string "@Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua"]:1389: in function `Update'
[string "@Interface/AddOns/Questie/Modules/Tracker/LinePool/TrackerLinePool.lua"]:355: in function `UpdateQuestLines'
[string "@Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua"]:2136: in function `UpdateQuestLines'
[string "@Interface/AddOns/Questie/Modules/EventHandler/QuestEventHandler.lua"]:436: in function `UpdateAllQuests'
[string "@Interface/AddOns/Questie/Modules/EventHandler/QuestEventHandler.lua"]:346: in function <...s/Questie/Modules/EventHandler/QuestEventHandler.lua:333>
[string "=[C]"]: ?
[string "@Interface/AddOns/AdiBags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:19: in function <...ags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Interface/AddOns/AdiBags/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Interface/AddOns/GatherMate2/Libs/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <...ddOns/GatherMate2/Libs/AceEvent-3.0/AceEvent-3.0.lua:119>

[01:42:05] Questie: [ERROR] Please report this error. GetQuestObjectives: The quest doesn't exist in QuestLogCache. 29210

### Questie version

Questie v10.11.0, Client 4.4.1 , Locale enUS

### Game flavor

Cata

**Comment by BreakBB** [comment]
Merging this with #6778 as they are the same error.
