### ISSUE TITLE
I think the data for the Ony Attune Quest is wrong in Classic Era now

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#6780]
### Description

I looted the blood but my "complete" announce didn't fire. That's what tipped me off!

<img width="1902" alt="image" src="https://github.com/user-attachments/assets/1b910d7b-04f9-4a1a-8626-7be0e9000cba" />

Questie doesn't see the quest as being complete

<img width="304" alt="image" src="https://github.com/user-attachments/assets/30a177a1-2038-4033-ad94-2ce2ba1cc6ec" />

But it is in the log. (This is after a reload.)

<img width="282" alt="image" src="https://github.com/user-attachments/assets/cffa5492-b6f2-47d3-b9d9-3c386bfadf35" />

Blood ID to check against.

<img width="399" alt="image" src="https://github.com/user-attachments/assets/86404ce9-7d8b-4ec7-8489-53a02c11a45c" />

### Questie version

10.11.0

### Game flavor

Era/HC/Anniversary

**Comment by Gogo1951** [comment]
Man, so much stuff just seems broken due to SoD changes. I wish I could get into SoD, but it just seems like it made a mess of the data. I know this isn't on you guys!

**Comment by BreakBB** [comment]
This is caused by this bug which is really hard for us to track down: #6689
