### ISSUE TITLE
Missing Objective Icon on Target Frame

### ISSUE THREAD

**Issue by MinhNBDao** [Questie/Questie#6807]
### Description

Before the update on 12/27/24, Questie showed on the target frame whether the entity selected was a kill quest, loot quest, etc. Now, the icon is gone and I have to hover over the frame manually to see if its part of a quest. I reverted back to 10.11.2 and it works on the older version. 

### Questie version

10.11.4

### Game flavor

Era/HC/Anniversary

**Comment by Cabro** [comment]
Temp fix: select pfquest theme then back to Questie, while we find the root of this bug

**Comment by BreakBB** [comment]
Hey @MinhNBDao v10.12.0 will be available shortly and fix this issue.

**Comment by MinhNBDao** [comment]
Nice! Cool to see you guys jump to action so quickly XD
