### ISSUE TITLE
Target Frame Icons Missing

### ISSUE THREAD

**Issue by gasserma** [Questie/Questie#6808]
### Description

Despite reinstalling, resetting questie to defaults, and resetting target frame defaults, I still see no target frame icons. The check box is enabled.

### Questie version

v10.11.4

### Game flavor

Era/HC/Anniversary

**Comment by Cabro** [comment]
Temp fix: select pfquest theme then back to Questie, while we find the root of this bug

**Comment by cbart2** [comment]
Thank you for reporting this, I've been going crazy trying to figure out the issue and didn't see this reported anywhere else online.

**Comment by BreakBB** [comment]
We're are already looking into this and hopefully find a fix very soon!
