### ISSUE TITLE
Localisation error

### ISSUE THREAD

**Issue by vyrnius** [Questie/Questie#6809]
### Description

Since the update all quests titles are displayed in English even though I use theGgerman client. Downgrading to v10.11.3 did not help, but works it again with v10.11.2

### Questie version

v10.11.4

### Game flavor

Era/HC/Anniversary

**Comment by BreakBB** [comment]
Thanks for reporting this @vyrnius we'll look into it to fix this rather soon.

**Comment by BreakBB** [comment]
Hey @vyrnius v10.12.0 will be available shortly and will fix this issue.
