### ISSUE TITLE
Truthbearer

### ISSUE THREAD

**Issue by NoModesty** [Questie/Questie#6811]
### Description

Almost the entirety of the Truthbearer questline for Paladins has the objective markers and turn-in locations linked to the wrong locations, or just missing completely.

### Questie version

v10.12.0

### Game flavor

Season of Discovery

**Comment by BreakBB** [comment]
Thanks for report thing. We'll look through the chain again. It's not easy to fix quest chains, when not being able to do it ingame ^^
